### ISSUE TITLE
Documentation: proper node takedown

### ISSUE THREAD

**Issue by hds1** [xrootd/xrootd#1004]
In the documentation a procedure about a proper node take down is missing.
Maybe an additional note in "Cluster Management Service Configuration Reference" FAQ 1.1.3
 

"The general way to take down an XRootD data server is to simply kill it. Kill cmsd if node was in a cluster.
The next thing is that the redirector will remember the server for 10 minutes. This is simply because it thinks that maybe it will come back (usually the case but not for you). All this means is that if a client tries to access a file that only existed on the shutdown server the redirector will ask the client to wait until the server comes back up (which it won't). But notice this is a benign action since if that server was the only one that had the file then the only other alternative is to give the client a "not found" error which would terminated the client. So, it only delays enevitable death by 10 minutes."

**Comment by abh3** [comment]
The suggestion has been incorporated into the R5 series of documentation (soon on the web).
