### ISSUE TITLE
Bad mapping of VOMS extensions using XrdSecgsiVOMSFun

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1006]
I've been trying to figure out why sometimes authentication to our XRootD storage still fails whenever the VOMS-role "production" is required - which we require for writing. 

With debugging active and also `dbg` for `XrdSecgsiVOMSFun`, I finally found this in the logs:
```
secgsi_Authenticate: WARNING: user mapping lookup failed - use DN or DN-hash as name
secgsiVOMS_Fun: proxy: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management/CN=1987664213/CN=3833218252/CN=1560720301
secgsiVOMS_Fun: adding cert: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management
secgsiVOMS_Fun: adding cert: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management/CN=1987664213
secgsiVOMS_Fun: adding cert: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management/CN=1987664213/CN=3833218252
secgsiVOMS_Fun: retrieval successful
secgsiVOMS_Fun: found VO: atlas
secgsiVOMS_Fun:  ---> group: '/atlas', role: 'production', cap: 'NULL'
secgsiVOMS_Fun:  ---> group: '/atlas', role: 'NULL', cap: 'NULL'
secgsiVOMS_Fun:  ---> group: '/atlas/lcg1', role: 'NULL', cap: 'NULL'
secgsiVOMS_Fun:  ---> group: '/atlas/usatlas', role: 'NULL', cap: 'NULL'
secgsiVOMS_Fun:  ---> fqan: '/atlas/Role=production/Capability=NULL'
secgsiVOMS_Fun:  ---> fqan: '/atlas/Role=NULL/Capability=NULL'
secgsiVOMS_Fun:  ---> fqan: '/atlas/lcg1/Role=NULL/Capability=NULL'
secgsiVOMS_Fun:  ---> fqan: '/atlas/usatlas/Role=NULL/Capability=NULL'
secgsi_Authenticate: VOMS: Entity.vorg:         atlas
secgsi_Authenticate: VOMS: Entity.grps:         /atlas
secgsi_Authenticate: VOMS: Entity.role:         NULL
secgsi_Authenticate: VOMS: Entity.endorsements: /atlas/Role=production/Capability=NULL,/atlas/Role=NULL/Capability=NULL,/atlas/lcg1/Role=NULL/Capability=NULL,/atlas/usatlas/Role=NULL/Capability=NULL
```

So it seems the VOMS proxy authenticating to us has the `production` role and `XrdSecgsiVOMSFun` sees it just fine, but it does not show up in `secgsi_Authenticate`. 
It rather seems that the role `NULL` is used here. 

Now I am unsure whether the loss of information happens in the `vomsxrd` library (pinging @gganis on this) or later in XrdSecGSI. 

Our config file contains:
```
sec.protocol /usr/lib64 gsi -dlgpxy:1 -exppxy:=creds -ca:1 -crl:3 -gridmap:/dev/null -cert:/etc/grid-security/hostcert.pem -key:/etc/grid-security/hostkey.pem -certdir:/etc/grid-security/certificates -vomsfun:/usr/lib64/libXrdSecgsiVOMS.so -vomsfunparms:certfmt=raw|vos=atlas,ops|grps=/atlas,/ops
```

Any ideas what is going wrong here?
Or is there a different library that should be used as drop-in replacement for `libXrdSecgsiVOMS` (is that one still maintained)?

**Comment by bbockelm** [comment]
@olifre - what version of `vomsxrd` are you running?  That looks like the default behavior prior to v0.4.0 (which was to take information only from the last matching FQAN).

**Comment by olifre** [comment]
@bbockelm Interesting! I am running 0.3.0, which is the latest version available via the WLCG repo at http://linuxsoft.cern.ch/wlcg/centos7/x86_64/  . Is a newer version packaged anywhere officially? 

Also, checking the corresponding change at https://github.com/gganis/vomsxrd/commit/22dc22d2a2b898b4dcacb424793695b474f8c3a5 , it seems there's now only an option to take a list of groups and roles (which you can not cleanly match against in an `auth_file`) or use the first one (which _might_ work if order is stable). Would the correct solution not be to ignore `NONE` for roles and caps if something other than NONE is available?

**Comment by bbockelm** [comment]
There's three options:

0.  Match against the first FQAN; ignore the rest.
1.  Match against the last FQN; ignore the rest.  (Old default)
2.  Copy all information.  (New default; didn't exist in v0.3.0)

The group information indeed can be multi-valued (space separated).  So if you have `/atlas` and `/atlas/usatlas` as groups in the proxy, then this would match against either an authfile rule for `g /atlas` or `g /atlas/usatlas`.

That said, I don't see how role-based matching could be useful here; there's no enforcement that the role comes from a given VO.  How do you know it was an `atlas` production user and not an `ops` production user?

For group-based matching, you have a pretty good idea that the group named `/atlas` comes from the ATLAS VO.  This is just a naming convention, however; the CMS VO can also have a group named `/atlas` but it doesn't.  To the best of my knowledge, only OSG goes the length of patching `libvomsapi` to enforce this convention (only the VO named `atlas` can have a group name beginning with `/atlas`.

With respect to having a very old version in the WLCG repo: I'm not the right person for that.  I can only point at what OSG has available (which isn't affected by the issues described above).

**Comment by xrootd-dev** [comment]
Hi Oliver,

The doc of vomsxrd

https://github.com/gganis/vomsxrd/blob/master/docs/man/libXrdSecgsiVOMS.1

specifies which VOMS attribute to use: first, last, etc. The doc unfortunately have a little typo. Option "grpopt" (not "groupopt") can be used to make selection.

In the authorization, you can specify role based authorization like this

= john o: atlas g: /atlas r: production
x john /data rl

This define a component ID john, which should be in ATLAS VO, with VO group /atlas and Role "production"

(OSG also has a lcmap based authorization if you want to use along with xrootd. It is good for an environment where you have other services that already use lcmap).

regards,
--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338

________________________________________

**Comment by olifre** [comment]
> The group information indeed can be multi-valued (space separated).

I understand. But does that mean that
```
= atlprod o atlas g /atlas r production
```
would match a hypothetical proxy with production role for VO CMS and role "NULL" for VO ATLAS (and group /ATLAS)?
That very example is from the xrootd docs, by the way (but without the group part) :wink:. 
At least, using "o" here instead of "g" would ensure it is not a CMS user with an ATLAS group. 
But do I understand correctly that it's not the "triple" of VO, Group and Role which is matched? 


> With respect to having a very old version in the WLCG repo: I'm not the right person for that. I can only point at what OSG has available (which isn't affected by the issues described above).

Ok, I will contact the WLCG repo admins on this then. At least it's good to know a working version exists, thanks for pointing me to it - maybe they can add it to the repo. 



> The doc unfortunately have a little typo. Option "grpopt" (not "groupopt") can be used to make selection

Thanks for the hint!
We don't have any service using lcmaps yet, so right now vomsxrd is the easiest solution for us.

**Comment by wyang007** [comment]
I did that kind of thing several years ago as a test. It was a legitimate concern.

In principle, a server should check with $X509_VOMS_DIR to verify that a X509 proxy with VOMS attribute atlas:/atlas/Role=production is signed by "atlas" VOMS server, and VO group "/atlas/xyz" matches VO name "atlas".

--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338

________________________________________

**Comment by abh3** [comment]
Hi Oliver,

= atlprod o atlas g /atlas r production

is, in fact, the tripple. However, I think the docs are wrong and should 
be

= atlprod o: atlas g: /atlas r: production

(notice the addition of the colon). We really should correct that, sigh.

Andy

**Comment by olifre** [comment]
Hi Andy,

thanks! 
Now just one question remains: IIUC, if vomsxrd maps all VOMS triplets, group and role will contain space-separated values, such as:
group: `atlas/de atlas/de atlas`
role: `NULL production NULL`
for a VOMS proxy with:
```
attribute : /atlas/de/Role=production/Capability=NULL
attribute : /atlas/de/Role=NULL/Capability=NULL
attribute : /atlas/Role=NULL/Capability=NULL
```
Will that (worngly) match:
```
= atlprod o: atlas g: /atlas r: production
```
or will the triplets be matched as full triplets, i.e. it will only (correctly) match:
```
= atlprod o: atlas g: /atlas/de r: production
```

Cheers,
Oliver

**Comment by abh3** [comment]
Hi Oliver,

At the moment, the only recognized multi-value field is "group" which 
makes the combinatoric question moot. Indeed, I hope we are not going down 
the path of an n! matching algorithm (shudder). What are the actual and 
realistic use cases. Likely we can accomodate but right now all values are 
considered single values except group which historically has always been 
that way.

Andy

**Comment by olifre** [comment]
Hi Andy,

I understand. My goal would be to support exactly the example stated in the documentation:
```
= atlprod o: atlas g: /atlas r: production
```
Seeing how vomxsrd seems to work, to do that, the triplets would have to be checked (i.e. not multi-valued fields, but a series of triplets). 

A real life example which should work (as you can see from the first post in this issue) would be:
```
secgsiVOMS_Fun:  ---> group: '/atlas', role: 'production', cap: 'NULL'
secgsiVOMS_Fun:  ---> group: '/atlas', role: 'NULL', cap: 'NULL'
secgsiVOMS_Fun:  ---> group: '/atlas/lcg1', role: 'NULL', cap: 'NULL'
secgsiVOMS_Fun:  ---> group: '/atlas/usatlas', role: 'NULL', cap: 'NULL'
```
This would result (if I parse the vomsxrd code correctly) in:
vo: `atlas atlas atlas atlas`
group: `/atlas /atlas /atlas/lcg1 /atlas/usatlas`
role: `producton NULL NULL NULL`
So for correct behaviour, the authorization code would have to go through these triplets in order - in other words, it is important that the `production` role belongs to group `/atlas` and VO `atlas`, and not to any of the other groups. 

A real life example which is broken right now (I think) is:
```
attribute : /atlas/de/Role=production/Capability=NULL
attribute : /atlas/de/Role=NULL/Capability=NULL
attribute : /atlas/Role=NULL/Capability=NULL
```
This proxy must _not_ match:
```
= atlprod o: atlas g: /atlas r: production
```
since it only has the `production` role for the "smaller" subgroup `/atlas/de`, but not for full `/atlas`. 

Cheers,
Oliver

**Comment by abh3** [comment]
Hi Oliver,

Indeed, I see your point. However, I don't think the current voms arranges 
attributes as tuples. As far as I can tell, it picks the last (or first, 
depending on an option) identity attribute and sets the various fields in 
the security entity tructure. Here, then, everything will be a singleton 
with the eception of groups (though that's usually a singleton as well).

So, are you proposing to chnage the VOMSFun to supply at attribute list of 
n-tuples? Are we actually structuring attributes that way with out certs 
today?

Of course, if that's the diretion we want to go in, wouldn't it be better 
to simply switch to the WLCG identity tokens?

Andy

**Comment by olifre** [comment]
Hi Andy,

my understanding of the vomsxrd code was that (if the "all" option is used) it should arrange each single field (VO, group, role) as a space-separated list from which the tuples could be reconstructed. 
That's rather ugly, but it might have been done due to the API being as it is. 

Here's the part from the code:
https://github.com/gganis/vomsxrd/blob/d4e18738331af0c905ce16ed99f634d102931585/src/XrdSecgsiVOMSFun.cc#L261-L275


> So, are you proposing to chnage the VOMSFun to supply at attribute list of n-tuples? Are we actually structuring attributes that way with out certs today?

Yes, that would be my expectation. I think all VOMS proxies are structured like this. 
For example, my very own VOMS proxy contains:
```
attribute : /atlas/de/Role=production/Capability=NULL
attribute : /atlas/de/Role=NULL/Capability=NULL
attribute : /atlas/Role=NULL/Capability=NULL
```
(which I used in the last post as example) and the one I have shown in the first post was also a "real" proxy used by an FTS. 


> Of course, if that's the diretion we want to go in, wouldn't it be better to simply switch to the WLCG identity tokens?

I am not sure we are there yet - we probably need a way to parse VOMS attributes correctly before. 

Cheers,
Oliver

**Comment by olifre** [comment]
Hi @gganis , @bbockelm @wyang007 ,

I have another partially related question for you. I contacted the WLCG repo admins and they do not know where to find new RPMs for vomsxrd - I think OSG does not have this packaged, right? 
Do you know of another source I could point them to? 

Cheers,
Oliver

**Comment by abh3** [comment]
Here is an unofficial location for the latest RPM's. I'm not quite sure 
what the hold up is to getting them into WLCG or OSG. I will follow up 
on that detail.

/afs/cern.ch/user/g/ganis/work/public/vomsxrd/RPMS/0.6.0

**Comment by wyang007** [comment]
Hi Oliver,

WLCG removed the 0.6 rpm because of some conflict with XrdHTTP (we guess) that we need to resolve. OSG does have one called xrootd-voms-plugin (0.6), which you can try.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338 (O)

**Comment by olifre** [comment]
Hi Wei,

sorry for the late reply! Indeed we also got vomsxrd 0.6 shortly from WLCG repos before it was pulled, and it led to a series of SIGSEGV of all our XRootD instances. 
We are also using XrdHTTP. Sadly, I did not store a stacktrace, but just reverted to 0.3 after seeing that 0.6 was pulled from the repos, assuming it was badly linked or otherwise broken and an accidental release. I asked the WLCG repo admins and apparently something very similar happened on the DPM testbed. 

I'd then rather wait for 0.4 or 0.5 making it to the WLCG repos and receiving proper testing in their testbed before rolling it out to our production nodes. But then they could use the OSG RPMs as their base, unless Gerri provides RPMs for the older versions. 

Cheers and thanks,
Oliver

**Comment by bbockelm** [comment]
@olifre - if you can reproduce the the segfault with `xrootd-voms-plugin`, I can provide support for that.

**Comment by abh3** [comment]
I think this has been resolved, If not, please reopen.

**Comment by olifre** [comment]
@abh3 Very nice, I just found the corresponding code changes! 
So to summarize, this will require >= XRootD 5.0 and vomsxrd >= 0.7 if I read things correctly. 
Once these are released (and after potentially necessary configuration changes) we can test and provide feedback, thanks again! 

@gganis Is there also a release of vomsxrd via the WLCG repos planned (and maybe a 0.8 including the fix for spaces?). Thanks for taking care of this!
