### ISSUE TITLE
python :: client.utils.CopyProgressHandler :: add redirected xrootd server information

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1020]
Hi! I think that if would be useful to have in the update and end methods of CopyProgressHandler information about the redirected destination.   
Also, it would be useful to have the source and target information available for all methods as
currently i have to do [this](https://github.com/adriansev/jalien_py/blob/dce3198242422abb96d26894e45a0a82bb61245e/alien.py#L114)   
Also, it would be useful to have a time and speed information in the end method (currently i am doing [this](https://github.com/adriansev/jalien_py/blob/master/alien.py#L131) )   
Thank you!!

**Comment by simonmichal** [comment]
@adriansev : I cannot change the interface of CopyProgressHandler as this would break both the API and ABI compatibility. I hope this is not a top priority issue for you?

**Comment by adriansev** [comment]
@simonmichal no, it was/is on the "nice to have" list, nothing major ... if i really need for debugging i can always use XRD_LOG vars. I will close, as breaking the API (and ABI) is not acceptable :)   
Thank you!
