### ISSUE TITLE
pip3 xrootd 4.10.0 : user install error : could not create '/usr/local/lib64/python3.7'

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1025]
It seems that `pip3 install --upgrade --user` still does not work :   
`creating /usr/local/lib64/python3.7    
error: could not create '/usr/local/lib64/python3.7': Permission denied`   
full error log [here](http://issaf.spacescience.ro/adrian/xrootd_pip/error.txt)   
el7 error log [here](http://issaf.spacescience.ro/adrian/xrootd_pip/error_el7.txt)

**Comment by simonmichal** [comment]
@adriansev : thanks for reporting it, it's an oversight on my side, actually it does install xrootd bindings in local user, however it also still tries to install them globally, it's fixed in 

- b43cc6eb4ba78dc2c3a5ae456ebe544e7de0f4cc
- 69aca6dea9edd4a79740a9db1fd114d2e016b5d4

this will be released in next bugfix release. In the meanwhile (before I close this issue) could you double check that the patch fixes the problem? You can install it in the following way:
```
git clone https://github.com/xrootd/xrootd
cd xrootd
cp packaging/wheel/* .
python37 ./setup.py install --user
```

**Comment by adriansev** [comment]
well, it is working .. sort of : meaning that it is successfully installed and i have    
```
running install_egg_info   
Writing /home/adrian/.local/lib/python3.7/site-packages/pyxrootd-v20190715_69aca6de-py3.7.egg-info   
``` 

and i have this   
```
>>> import XRootD
>>> print (XRootD.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'XRootD' has no attribute '__version__'
```

but when trying to use it in my tool i get this :   
```
  File "/home/adrian/bin/alien.py", line 100, in XrdCopy
    from XRootD import client
  File "/home/adrian/.local/lib/python3.7/site-packages/XRootD/client/__init__.py", line 3, in <module>
    from .glob_funcs import glob, iglob
  File "/home/adrian/.local/lib/python3.7/site-packages/XRootD/client/glob_funcs.py", line 26, in <module>
    from XRootD.client.filesystem import FileSystem
  File "/home/adrian/.local/lib/python3.7/site-packages/XRootD/client/filesystem.py", line 26, in <module>
    from pyxrootd import client
ImportError: /home/adrian/.local/lib/python3.7/site-packages/pyxrootd/client.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5XrdCl3URLC1EPKc

```
Any idea what could be the problem?   
Thank you!!

**Comment by simonmichal** [comment]
@adriansev: you have to install matching version of xrootd-client-libs, in this case 4.10.0 will be as close possible to master branch.

**Comment by adriansev** [comment]
well, then i see two options : either make the python installation look for system (or already present) xrootd and make the python bindings build based on what is found (compile a local xrootd ONLY if no other xrootd found), or make it somehow standalone (pack the libraries with the python bindings and make the binding use ONLY the libraries that are associated with the bindings). When the xrootd will be in repository it will have also the python bindings so the pip install no longer have a use. IMHO pip install is for user side installation,when the system repositories does not provide the needed package.

**Comment by simonmichal** [comment]
@adriansev : you made a fair point, let me see what I can do :-)

**Comment by simonmichal** [comment]
@adriansev : I just pushed fca51b27e2989b033b3ce889929e3d06b5258206 (this sets rpath for the bindings to its local client), could you test again?

**Comment by adriansev** [comment]
i can confirm that it works :   
```   
>>> import XRootD
>>> print (XRootD.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'XRootD' has no attribute '__version__'
>>> import inspect
>>> print (inspect.getfile(XRootD))
/home/adrian/.local/lib/python3.7/site-packages/XRootD/__init__.py   
```
also, i tried my xrootd based application and i could copy from remote

**Comment by adriansev** [comment]
btw, just in case a python application want to check the version of the xrootd (to be aware if some operations are possible or not), can the attribute of __version__ be added?   
Thanks a lot!!

**Comment by simonmichal** [comment]
@adriansev : perfect, so I suppose we can close this one, right? Could you open another one for the version attribute (I'll add it once I'm back from holidays)?

**Comment by adriansev** [comment]
@simonmichal yeah, sure, thanks a lot!!!
