### ISSUE TITLE
Segfaults in xcache

### ISSUE THREAD

**Issue by nikoladze** [xrootd/xrootd#1026]
Hi,

As we started discussing in #975, sometimes (usually every several days) our xrootd process on our xcache server crashes with SEGV. Since this is probably unrelated to the problem with open files i suggest to continue the discussion about this issue here.
Unfortunately i can't give much feedback yet on when/how this occurs. Last time i tried to attach a gdb to the xrootd process, but the only info i could get so far is the following:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f4fddfc7700 (LWP 15623)]
0x00007f4fde2e84bb in XrdFileCache::File::WriteBlockToDisk(XrdFileCache::Block*) () from /usr/lib64/libXrdFileCache-4.so
```

I would appreciate tips on how i can get a backtrace in these situation with multiple threads. But i managed now (thanks to the tip from @osschar in #975) to get the correct debug symbols, so if i can get a backtrace the next time it might be more useful.

This occurred with xrootd-4.9.1, we switched to 4.10.0 now - lets see.

Cheers,
Nikolai

**Comment by simonmichal** [comment]
@nikoladze : do you have a stack trace from the crash?

**Comment by osschar** [comment]
This one is fixed, it was originally reported by Wei. It only happened for forwarding mode proxies.

**Comment by nikoladze** [comment]
> @nikoladze : do you have a stack trace from the crash?

Unfortunately not, both typing `bt` and `thread apply all bt` in the gdb i had attached didn't give me anything. Whats the best strategy to get such a stack trace?

> This one is fixed, it was originally reported by Wei. It only happened for forwarding mode proxies.

Is this fix included in `4.10.0-1` ?

**Comment by abh3** [comment]
Hi Nikolai,

You ned to install the debug RPM for xroot to get symbols. You won't loose 
anything if it's not here you simply won't be able to get any reasonable 
information in the back trace,

Andy

**Comment by nikoladze** [comment]
Since i haven't seen any SEGV crashes since the update to `4.10` i'll close this issue. Thanks for your help!
