### ISSUE TITLE
python :: add version attribute to xrootd

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1027]
It would be useful to have for XRootD python module the attribute of ```__version__```    
It can be used to make different decisions on what features are known to be implemented on different versions.

**Comment by simonmichal** [comment]
@adriansev : short question, I suppose you expect the `__version__` to be string e.g. `'4.10.0'`?

**Comment by adriansev** [comment]
@simonmichal i don't know, i think that there is a standard ... does [this](https://www.python.org/dev/peps/pep-0440/) help you about the format of version?   
thanks a lot!

**Comment by QLeB** [comment]
I am facing an error that seems related with this commit:

>   File "/usr/lib64/python2.7/site-packages/XRootD/client/_version.py", line 27, in <module>
>    __version__ = client.XrdVersion_cpp()
> AttributeError: 'module' object has no attribute 'XrdVersion_cpp'

is this a known issue?

**Comment by simonmichal** [comment]
@QLeB : thanks for reporting this, to answer your question, no it is not a known issue, could you double check if the python interface is linked to correct `client.so` library?

**Comment by QLeB** [comment]
I reinstalled from scratch to check but I can't reproduce the issue now.
I think I had some leftover from previous wrong install, now it seems OK.
Sorry!
