### ISSUE TITLE
Returning errno "EINVAL" from Ofs plugin within XrdXrootdProtocol::do_Open() is translated to retryable error

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#1029]
When using an `XrdOfs` plugin, the file open call will be handed to the plugin Open function.
In case validation fails, the plugin should return a status code (e.g: `SFS_ERROR`), with more details in the `XrdOucErrInfo` error object.

For the following code (XrdXRootdXeq.cc::1393):
```cpp
// Open the file
//
   if ((rc = fp->open(fn, (XrdSfsFileOpenMode)openopts,
                     (mode_t)mode, CRED, opaque)))
      {rc = fsError(rc, opC, fp->error, fn, opaque); return rc;}
```

Providing a status != 0 will trigger parsing of the error object.
The errno from the error object is translated in the XProtocol::mapError() function. 
However, for EINVAL, it defaults to kXR_FSError, which is a retryable error.

The complementary `XProtocol::toErrno()` function provides a mapping between `kXR_ArgInvalid`/`kXR_ArgMissing` to `EINVAL`.

There's no benefit in retrying an `EINVAL` error from the `open` call.
Would be useful to have a mapping between `EINVAL` to a _kXR__ error code.

**Comment by abh3** [comment]
This was fixed by commit 43eb599f1ce223bd922d6a480a25938b94748159 on January, 22, 2020. Sorry it took so long to report the fix but this one fell through the cracks.
