### ISSUE TITLE
XrdCl: Redirect limit Status object provides errno set to 0

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#1031]
When reaching a redirect limit, the status object provided will not have errno set (defaulting to 0).

Processing the errno of this status object can lead to confusion, as an error is encountered (`!status.IsOk()` gives true) but the `errno` is 0.

The case I've identified happened in the following code section (XrdClXrootDMsgHandler.cc:493):
```cpp
        if( !pRedirectCounter )
        {
          log->Warning( XRootDMsg, "[%s] Redirect limit has been reached for "
                     "message %s, the last known error is: %s",
                     pUrl.GetHostId().c_str(),
                     pRequest->GetDescription().c_str(),
                     pLastError.ToString().c_str() );


          pStatus = Status( stFatal, errRedirectLimit );
          HandleResponse();
          return;
        }
```

At this point, the value of the last known error status is still available.
Should the new status object have its `errno` set from the last known error object?

**Comment by simonmichal** [comment]
Discussed offline, the conclusion is that the `XrdCl::Status::errNo` field should not be used as input for `strerror` function, instead the method `XrdCl::Status::ToString()` should be used.
