### ISSUE TITLE
libXrdHttpTPC does not support fallback for the fslib directive

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1034]
The code in XrdTpcConfigure uses its own mechanism to load a custom OFS plugin library but it doesn't handle the fallback scenario when the name doesn't contain "-4".

Code is here:
https://github.com/xrootd/xrootd/blob/master/src/XrdTpc/XrdTpcConfigure.cc#L163

Sample error:
```
Plugin loaded 
190802 16:37:33 30238 sysInitialize: Will load configuration for the TPC handler from /etc/xrd.cf.fst1
190802 16:37:33 30238 sysConfig: xrootd.fslib line successfully processed by TPC handler.  Base library: libXrdEosFst.so
=====> xrootd.fslib -2 libXrdEosFst.so
190802 16:37:33 30238 sysConfig: Failed to base plugin  libXrdEosFst-4.so libXrdEosFst-4.so: cannot open shared object file: No such file or directory
190802 16:37:33 30238 sysInitialize: Encountered a runtime failure when loading  Failed to configure the HTTP third-party-copy handler.
``

**Comment by bbockelm** [comment]
Sorry about the bug!

How urgent is this for you?  Does it block further evaluation of EOS / XrdHTTP?  Or is it just a general annoyance?

**Comment by xrootd-dev** [comment]
Just a note. The fallback is *not* to add the '-4' but to remove it. The 
standard plugin handler always appends a '-4' (or whatever the version of 
the day is) and looks for that. If it's allowed to fallback by looking for 
something actually specified, it does. Not all plugins are allowed a 
fallback. It's a bit late to change how we handle version numbers but one 
obvious improvement is to see if the library name alreay has the right 
version (people are *not* supposed to specify it) and not do it's one 
suffixing.

Andy

**Comment by esindril** [comment]
@bbokelm definitely not a blocker, just nice to have. Thanks!

@abh that's what I meant, I did's say adding. Our library is called libXrdEosFst.so. If I rename it with -4 then it works.

**Comment by bbockelm** [comment]
@esindril - this code dates back to when libXrdHttpTPC was shipped as a separate plugin (outside the Xrootd codebase).  The Xrootd function for loading filesystems is not in the public header - heck, it's not even in a private header (the `extern` line is copy/pasted about).

Now is good as any to do a quick code cleanup.

**Comment by abh3** [comment]
Agreed. Anything that ships with the XRootD package is free to use any 
header in that package (though we advise using restraint :-).

Andy

**Comment by abh3** [comment]
I think this is no longer an issue. If it is, please reopen this ticket.
