### ISSUE TITLE
XrdCl: if kXR_poscpend is set disable write recovery

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1036]
If the kXR_poscpend bit in stat response is set the write recovery mechanism should be disabled.
Storage like EOS that supports only POSC logic should always set kXR_poscpend bit to avoid problems with write recovery.

**Comment by jmuf** [comment]
As mentioned in https://github.com/xrootd/xrootd/issues/673 , would suggest to disable retry / recovery by default for anything that changes state (write or open/truncate).

This area perhaps could be reviewed in general - there are several tickets for 'recovery' or 'retry' (with very narrow fixes), and user communities use 'arcane' environment variable settings to disable them ('arcane' in the sense that the exact effect is not understood, just that "they told me that this prevents file loss").
