### ISSUE TITLE
Querying XRootD 5 extended attributes versus issuing  kXR_query->kXR_QPrep

### ISSUE THREAD

**Issue by murrayc3** [xrootd/xrootd#1043]
The main goal of this issue is to trigger discussions around the best way to implement the querying of pending "prepare from tape" requests.

The CERN Tape Archive (CTA) project is currently using EOS extended attributes to expose the status of pending "prepare from tape" requests.  We are hoping to replace this EOS specific solution with a standard XRootD one.  The current idea is to simply replace the extended attributes of EOS with the up and coming extended attribute feature of version 5 of XRootD.  Discussions within the CTA development team have led to the conclusion that this simple drop in replacement solution may not work.

There are two types of extended attributes in EOS, namely "user" and "sys".  End users are not permitted to modify "sys" attributes.  CTA therefore uses "sys" attributes to store the status and details of on going prepare requests.  This protects those attributes from end users.  To complete the picture, EOS can only index by file.  It cannot expand a prepare request ID into the list of files being prepared.  CTA relies on FTS to query EOS for each individual file in a "prepare" batch.  FTS is being used to remember the individual files in such a batch.

It may not be possible to simply replace EOS extended attributes by XRootD extended attributes because XRootD may not support the concept of "sys" attributes.

Stepping back from the details of extended attributes.  The problem we are trying to solve is how to query ongoing prepare requests via the standard XRootD protocol in a way that can be implemented by EOS.  There is already a `kXR_query` request which can be passed `kXR_QPrep` as its `reqcode`.  EOS can only index by file.  Maybe we could send the list of file paths and/or IDs in the `args` field of the `kXR_query` request?  Maybe a "kXR_query->kXR_QPrep" request would be better than individually querying the extended attributes of each file in a "prepare batch".

A discussion should be started between CTA, EOS and XRootD developers to decide on the most appropriate and feasible solution for querying on going "prepare from tape" requests.

**Comment by abh3** [comment]
Looks like ghe discussion has ended, so I am closing this.
