### ISSUE TITLE
python :: client.CopyProcess::addJob() - missing streams option

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1044]
Hi! the addJob of client.CopyProcess is missing the streams argument corresponding to -S argument of xrdcp

**Comment by simonmichal** [comment]
@adriansev : The number of substreams per channel is being set globally for the whole xrootd client instance not per CopyProcess. That said, I've added new API that allows Python users to set/get values in XrdCl::Env in c5455c7b84baa7cdb8c22ac3e252507ca80dbf4a . E.g. you can set the number of substreams in the following way:

```
from XRootD import client
client.EnvPutInt( 'SubStreamsPerChannel', 15 )
```
