### ISSUE TITLE
[XrdCl] client doesn't sign kXr_endsess request in the hand-shake even if instructed to do so by server

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1045]
Example client logs:

> [2019-08-22 10:28:22.688816 +0200][Debug  ][ExDbgMsg          ] [slc6-test:1094] Retry at server MsgHandler: 0x62d120 (message: kXR_open (file: /tmp/Makefile?oss.asize=55824, mode: 0644, flags: kXR_delete kXR_open_updt kXR_async kXR_retstat ) ).
> [2019-08-22 10:28:22.688827 +0200][Dump   ][PostMaster        ] [slc6-test:1094 #0] Sending message kXR_open (file: /tmp/Makefile?oss.asize=55824, mode: 0644, flags: kXR_delete kXR_open_updt kXR_async kXR_retstat ) (0x62ca90) through substream 0 expecting answer at 0
> [2019-08-22 10:28:22.690408 +0200][Debug  ][PostMaster        ] [slc6-test:1094] Found 1 address(es): [::ffff:128.142.137.121]:1094
> [2019-08-22 10:28:22.690470 +0200][Debug  ][AsyncSock         ] [slc6-test:1094 #0.0] Attempting connection to [::ffff:128.142.137.121]:1094
> [2019-08-22 10:28:22.690682 +0200][Debug  ][Poller            ] Adding socket 0x62a450 to the poller
> [2019-08-22 10:28:22.690729 +0200][Dump   ][TaskMgr           ] Will rerun task "TickGeneratorTask for: slc6-test:1094" at [2019-08-22 10:28:28 +0200]
> [2019-08-22 10:28:22.691290 +0200][Debug  ][AsyncSock         ] [slc6-test:1094 #0.0] Async connection call returned
> [2019-08-22 10:28:22.691308 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Sending out the initial hand shake + kXR_protocol
> [2019-08-22 10:28:22.691334 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Wrote a message:  (0xe8000f80), 44 bytes
> [2019-08-22 10:28:22.692191 +0200][Dump   ][XRootDTransport   ] [msg: 0xe8000f80] Expecting 8 bytes of message body
> [2019-08-22 10:28:22.692201 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received message header, size: 8
> [2019-08-22 10:28:22.692206 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received a message of 16 bytes
> [2019-08-22 10:28:22.692211 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Got the server hand shake response (type: server [], protocol version 400)
> [2019-08-22 10:28:22.692223 +0200][Dump   ][XRootDTransport   ] [msg: 0xe8000f80] Expecting 14 bytes of message body
> [2019-08-22 10:28:22.692226 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received message header, size: 8
> [2019-08-22 10:28:22.692230 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received a message of 22 bytes
> [2019-08-22 10:28:22.692234 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] kXR_protocol successful (type: server [], protocol version 400)
> [2019-08-22 10:28:22.694721 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Sending out kXR_login request, username: simonm, cgi: ?xrd.cc=ch&xrd.tz=1&xrd.appname=xrdcp&xrd.info=&xrd.hostname=idefix.dyndns.cern.ch&xrd.rn=4.8.8, dual-stack: true, private IPv4: false, private IPv6: false
> [2019-08-22 10:28:22.694753 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Wrote a message:  (0xe8038b30), 119 bytes
> [2019-08-22 10:28:22.695521 +0200][Dump   ][XRootDTransport   ] [msg: 0xe8038b30] Expecting 61 bytes of message body
> [2019-08-22 10:28:22.695530 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received message header, size: 8
> [2019-08-22 10:28:22.695535 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received a message of 69 bytes
> [2019-08-22 10:28:22.695540 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Logged in, session: 070000009f5900000700000008000000
> [2019-08-22 10:28:22.695544 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Authentication is required: &P=gsi,v:10400,c:ssl,ca:3bae64c4.0|995b6462.0
> [2019-08-22 10:28:22.695547 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Sending authentication data
> [2019-08-22 10:28:22.696172 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Trying to authenticate using gsi
> [2019-08-22 10:28:22.707639 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Wrote a message:  (0xe8000f80), 136 bytes
> [2019-08-22 10:28:22.724939 +0200][Dump   ][XRootDTransport   ] [msg: 0xe8000f80] Expecting 3341 bytes of message body
> [2019-08-22 10:28:22.724982 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received message header, size: 8
> [2019-08-22 10:28:22.724997 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received a message of 3349 bytes
> [2019-08-22 10:28:22.725010 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Sending more authentication data for gsi
> [2019-08-22 10:28:22.726110 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Wrote a message:  (0xe803af90), 6223 bytes
> [2019-08-22 10:28:22.728289 +0200][Dump   ][XRootDTransport   ] [msg: 0xe803af90] Expecting 0 bytes of message body
> [2019-08-22 10:28:22.728310 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received message header, size: 8
> [2019-08-22 10:28:22.728318 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received a message of 8 bytes
> [2019-08-22 10:28:22.728330 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] XrdSecProtect loaded.
> [2019-08-22 10:28:22.728338 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Authenticated with gsi.
> [2019-08-22 10:28:22.728350 +0200][Debug  ][XRootDTransport   ] [slc6-test:1094 #0.0] Sending out kXR_endsess for session: 060000009f5900001600000007000000
> [2019-08-22 10:28:22.728380 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Wrote a message:  (0xe8034e20), 24 bytes
> [2019-08-22 10:28:22.729901 +0200][Dump   ][XRootDTransport   ] [msg: 0xe8034e20] Expecting 23 bytes of message body
> [2019-08-22 10:28:22.729922 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received message header, size: 8
> [2019-08-22 10:28:22.729931 +0200][Dump   ][AsyncSock         ] [slc6-test:1094 #0.0] Received a message of 31 bytes
> [2019-08-22 10:28:22.729943 +0200][Error  ][XRootDTransport   ] [slc6-test:1094 #0.0] Got error response to kXR_endsess: Request not signed
> [2019-08-22 10:28:22.729959 +0200][Error  ][AsyncSock         ] [slc6-test:1094 #0.0] Socket error while handshaking: [FATAL] Hand shake failed
> [2019-08-22 10:28:22.729966 +0200][Debug  ][AsyncSock         ] [slc6-test:1094 #0.0] Closing the socket
> [2019-08-22 10:28:22.730010 +0200][Debug  ][Poller            ] <[::ffff:128.141.194.189]:45868><--><[::ffff:128.142.137.121]:1094> Removing socket from the poller
> [2019-08-22 10:28:22.730053 +0200][Error  ][PostMaster        ] [slc6-test:1094 #0] elapsed = 0, pConnectionWindow = 120 seconds.
> [2019-08-22 10:28:22.730065 +0200][Error  ][PostMaster        ] [slc6-test:1094 #0] Unable to recover: [FATAL] Hand shake failed.

**Comment by simonmichal** [comment]
Fixed in 7a97d988d5b61e727ee734d62360360641e0c4ea.

**Comment by alrossi** [comment]
(also left message on the commit)

Will this be back-ported to 4.9?

The issue was discovered using the 4.9.1 client against both 4.9 and 4.10 servers with security level set to pedantic.

Thanks!

**Comment by simonmichal** [comment]
@alrossi : our current advice for the users is to move to 4.10.0 (of course if there is a strong desire we can back-port this patch to 4.9.x series)
