### ISSUE TITLE
xrdfs query config/stats :: server not responding being blocked by IOwait

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1051]
So, while i remember being discussed in mail-list maybe it is better to have it here also:
When the load is high enough (maybe up to maxt) the server stop responding for queries of the type config/stats. While is understandable if the access is a IO type (reading from storage), for the config/stats queries that give monitoring and health related information of the serve, it is not.
If the server is loaded, one cannot even know where the problems is as xrdfs localhost does not answer to any query config/stat. I would expect that these should be answered irrespective of the load. for reference an unresponsive load have this structure : 
```
03:49:16 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
03:49:16 PM  all    0.13    0.00    1.79   68.86    0.00    1.00    0.00    0.00    0.00   28.22
```

**Comment by abh3** [comment]
Technically, there is no way to solve this via "the wire protocol" as we have no idea what the incoming request priority should be.  The appropriate solution here is to login to the machine and ask locally. If you cannot log into the machine then, clearly, the server is underpowered for the load it is being asked to serve. That we can do nothing about.
