### ISSUE TITLE
pfc.blocksize arbitrarily limited to 16MB.

### ISSUE THREAD

**Issue by aoanla** [xrootd/xrootd#1053]
We have an xrootd system where the underlying storage has a native blocksize of 64MB.

For efficiency in our caching proxies, we were advised to set the cache blocksize to the same:

pfc.blocksize 64MB 
 
Adding that line to the config prevents the xrootd cache service from staying up (and removing it makes it work again).

190906 19:03:37 19779 XrdFileCache_a2x: get block size 64M may not be greater than 16777216
190906 19:03:37 19779 XrdFileCache_Manager: error Cache::Config() error in parsing

We know of no reason why the blocksize should be limited to just 16MB...

can this limit be removed?

**Comment by osschar** [comment]
I bumped the limit to 512MB.

If you do vector reads against the cache or expect to have a large number of concurrent clients make sure you also set pfc.ram accordingly. And you'll likely need some fast disks to be actually able to cache the data :)

Also, be careful with prefetching. Do you know the access patterns for the files you want to cache? Maybe disabling it at first is a safe bet for blocks that large, or set it to 1 at most.
