### ISSUE TITLE
extract files from compressed zips

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1054]
Hi! It would be really useful if one could extract (and have transferred over the network) a file from a remote compressed zip archive. Thank you!!

**Comment by simonmichal** [comment]
@adriansev : I added the capability to inflate deflated files in a ZIP archive in: ee0e69289f29f544c11bc3f6f8bcc74fcbd7f945

this is the default and by far the most widely used compression algorithm in ZIP archives.

**Comment by adriansev** [comment]
@simonmichal i can confirm that it works! :) thanks a lot!
