### ISSUE TITLE
oss.space :: use full globbing

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1058]
Hi! Is is possible to use full globbing (or regex) for oss.space specification?
I would like to have something something `/storage*/mydatadir`
It would be nice also `/storage[0-4]/mydatadir`

**Comment by abh3** [comment]
After canvasing what most other sires do, we determined this feature has limited appeal.  Sorry to say, given the resources available vs applicability the tradeoff is in negative territory. Hence, we won't be doing this.
