### ISSUE TITLE
http redirections don't urlencode the parameters

### ISSUE THREAD

**Issue by costing** [xrootd/xrootd#1060]
Hi,

We're trying to use the HTTP endpoint in Xrootd and while browsing works, accessing files does not. We pass the url-encoded ALICE access token with `?authz=` but then the redirector sets the `Location` header to the decoded string, that is multi-line. This interferes with the HTTP headers and of course the data server only receives the first line and cannot decode the token.

So my request is to correctly url-encode the passed arguments when redirecting.

Cheers,

.costin

One line example (storage runs 4.10.0):

`curl -i -L -s http://alicegrid2.recas.ba.infn.it:1094//14/51881/fbba0702-8e03-11e9-ad41-674bfbba2083?authz=-----BEGIN%20SEALED%20CIPHER-----%0AQHtUw%2B0ItSWSrX7D4gcgCmoeZ13eBfMS7lbdSr%2Bjnl7aKJmKFFYF4j3N6kQ9GhRPDuVDvTfsZ9i4%0A9WLLY4ESe2W6jecpilDkv-DXchCaI%2BPSsbwOBhdfu3JfD45XrkWfkqr451KgNnoHXRFTreJsQJST%0AcS77bOHic33kC9NcLSw%3D%0A-----END%20SEALED%20CIPHER-----%0A-----BEGIN%20SEALED%20ENVELOPE-----%0AAAAAgF4feqA18MIy%2BQBJ2qnPcTL%2BFa9--gxwfktjilnT4rQ2z5oDJ3Z7JYLOALQg9ToilwmjxMDX%0AvyGWTAcfhVJ9HLqvi29v6PmadR-03qQIODG4o-bs5T0v6-WrWH-ufa%2BtP1iH5aZcQ7bPHsw5MBM8%0APi9sM3RF%2BtoZ7626XqPptYJB%2BkUqOEvusOa2ECZgMAoWbfkBdeLGsffwyBOKyTqgdVyo7JXcqli4%0Ag3UPzb4iUyq3WOksJIdMSXF3xKwyjH7XnKDRziZS6s-kpGhpTy7Hw5eOb-XUpMmT7DtWmrREYxCq%0ALMopPPcuiA8DL4iucVfney5SBs%2BXNiENTyuwkQOIRPdUksy%2BsocydvjfkIWctugMtRcJVVNi5fBJ%0AXkSUsipSZJWlQMDULQVZnytedktdIIRyUF2EsL%2BQj-kx6hxV46-nynDEgZOWYscfY20yOR-F%2BB3z%0ABSs1zhv2K1zGOiV09725yPdvoctCleHSfLNRert-wXaXi3Wbvy%2Bg1Yt9rBSaZZoSBMTHtdEE10Fp%0A-0q%2Bz49XRukv1ejqTPI84nRUZBoEy8UXaQS4vRBdLDoJpFVnu4-xlOLmQYNsgHiSWza2legbLB5j%0ADQI3eu57zFXwp%2B6HCb9V5fNZiAi2M5Pt3YSs8CxQpVOUK-LU3T34RsBCUQIMrvOUutK7eazkCQij%0AxuFtuyUL6IKbBtV%2B5-Xlw7ILiYxaZvRUR00nJMANgfma1-m-hic9-Aho3DIxfqeK-C3I4MFfsh2V%0ApiLmH8nmPXLJrecCPZjhjnU3cxqFkF7PRaEohP6KKjSusjRNfI31wgv1LgRgXcsZAdS8MsG56f6z%0ASdtEBBMMESI62FIp7hnAe9J519%2Bnu%2BKNCX8cerFezCvQ0gIs9dEdyGV23xdKMy2%2BdJ0FyMlqnAzZ%0AQd9HHIV1h5HFYVg6lUCmmPz1WK7pA2-aypcW5K%2BbHVwH1ZzFl1eChNVwS9fgzQuZg%2BeNaeII41j9%0AyhbdSIszl4RH06nHQ1pcabhZTlNnDzitecQbrt7cjXdPLeemEZcIAgtbm0XNBUc%3D%0A-----END%20SEALED%20ENVELOPE-----`

```

HTTP/1.1 302 Redirect
Connection: Keep-Alive
Content-Length: 0
Location: http://alice-xrootd-it-01.recas.ba.infn.it:1094/14/51881/fbba0702-8e03-11e9-ad41-674bfbba2083?authz=-----BEGIN%20SEALED%20CIPHER-----
QHtUw+0ItSWSrX7D4gcgCmoeZ13eBfMS7lbdSr+jnl7aKJmKFFYF4j3N6kQ9GhRPDuVDvTfsZ9i4
9WLLY4ESe2W6jecpilDkv-DXchCaI+PSsbwOBhdfu3JfD45XrkWfkqr451KgNnoHXRFTreJsQJST
...

```

**Comment by bbockelm** [comment]
@ffurano - would you have time to look at this?  I'm a bit booked up for at least another week.

**Comment by ffurano** [comment]
ok

**Comment by costing** [comment]
@ffurano Many thanks for the quick fix! Do you have a test instance with it that I could run the tests against?

I'm not sure it's completely correct, since some of the content was already encoded (like ' ' -> %20). Calling quote() wouldn't escape again this part? This is what I'd like to test on simple instance if you have one.

**Comment by costing** [comment]
Hi again,

Sorry for the long delay, we managed to get around to testing this again against a 4.11.1 server. There is one more problem regarding the encoding of the tokens when redirecting. New line characters (encoded as %0A in the original request) are encoded as %0C in the "Location" header. With a simple replacement of %0C -> %0A in the Location below the token was accepted, so I hope this is the last modification that would be needed for this to fully work.

```
curl -i -L -s http://rd.spacescience.ro:1094//home/aliprod/data/00/00000/099a8cba-c924-11e9-8ab0-c758c795bf3c?authz=-----BEGIN%20SEALED%20CIPHER-----%0AOxvV3wWEjgcEQ9kvH9eUs6e00iI%2By4BpYR1jw-t6PtrbJ3W4moySQPAgo-JJ2xRBrPNRi5lwdo9H%0ALj9HibEjIpNDL7tc1xbXxHX1hRXNsPLo0e-KSZCXLaEG7oU4B0pJP8nrs4fLMGucGaT2rSR1KXMu%0A7FjSSdHbyDAEW9thvWQ%3D%0A-----END%20SEALED%20CIPHER-----%0A-----BEGIN%20SEALED%20ENVELOPE-----%0AAAAAgCNhXbslaFobAXh4cJMbAnPwy1ig2Rn%2Bz38ux99YgwOXxEqlVuVC1ZHnIOmdpIGzE7VXukOR%0AWhbSzTpmg-VKLRAa7hRaWeZ67-K6BVylYqbSZuU2PpXVz4QBHrFSwvSgg7JoZD6g4DV-Q43vaGV0%0Ae%2BGQFUWylZMeMEM%2Bm0ryhFstecdPPsY%2BvAeZfyviKMTv4vd5M9oZY%2BtMBWsklLB7fw7MWrIdS-NN%0Aou2F%2Bbv6fgm9QArWK62-JjGgWipV79A%2BC11epGRDlhKDcbmzGkWEjxxf9qLJgzhjqPB%2BVQPVs1Gt%0A5l0vlceFehdNxRs-7OrdiBFJAAujbQxjIHk099BbWUM89QxaJDko7qBjTTkU2w2QsDYTuFJs-S7L%0AxB9Twas4sYufxJtf8JtFGgoUjgQ2XbpWUvD8-SXcJtXk2lpW69m5CqqfuhPxuIEcfSTrVXzHzral%0A6xvrI4L7Gi8iUYpVJROJQDTcjYIqah41ExIK6r%2BU925OXzyTfeVUM--enVQSxxyrYxhskxDPa6tm%0ARHLBrkcXQAfjBQBFj2Nd9oSurYrXNguY2G3yBPl%2BkAUsNwbE9EBbsunz8npJ26XAC8PO9vAWnuPe%0ALPY50WeCZ1l2Iv2dR5ywoEKCe-g60aFLSWT2-8PNTxjeCYGogMJ1wwa2uebA6i85Hrhs5D90ybPH%0A8VVt7ChYQjeyea0Q5wXZrV6Bra95NeTl21hbV6tr1kOZcNrPDEDBLz9nUP%2BnJJFu4S7RdRH5OH4R%0AhtjuPvutYurmuoqZCIBPY2Z2B0eUBvIwjq-8vSuIenMWsUHWnKKHP3EoWfegDmiHVp3jv5n4cI0p%0AtTRvAbSUppqhuWSyA0UWTVQ4TuSM1kTcOAo2BuDD-PQeOH2NRjhcTvLnPQ06uFPP-LQ2aOLGi7xU%0ASUMVxkYFZRiOeS1U8AOFc8WfUR-FETaR8ZGuICB4cpaEpF8jZl5d5Iv1Pv8sFhYUAL%2BBRYUOM2Tb%0AsdkjD9%2BdifulCggJTdCwUV1%2BXXQvIGIDroUnyjXnVr2cF2PnIzydNFY99bp4lMTKYzf8ii3HW3oK%0AV4y7DKfEkc8Rm6%2BkjgmwgFhosbguFsqoMmrzpW1NEN0R0yhLJPzBQmYIKYJV0Y5aV7NKPmAyM8DU%0A0IDX%2BA%2BoIrqlN4p1HhY3nHzy%2Bnl3CCelM2BOkV13iTXYc%2Bt-Jg%3D%3D%0A-----END%20SEALED%20ENVELOPE-----
HTTP/1.1 302 Redirect
Connection: Keep-Alive
Content-Length: 0
Location: http://storage08.spacescience.ro:1094/home/aliprod/data/00/00000/099a8cba-c924-11e9-8ab0-c758c795bf3c?authz=-----BEGIN%20SEALED%20CIPHER-----%0COxvV3wWEjgcEQ9kvH9eUs6e00iI+y4BpYR1jw-t6PtrbJ3W4moySQPAgo-JJ2xRBrPNRi5lwdo9H%0CLj9HibEjIpNDL7tc1xbXxHX1hRXNsPLo0e-KSZCXLaEG7oU4B0pJP8nrs4fLMGucGaT2rSR1KXMu%0C7FjSSdHbyDAEW9thvWQ=%0C-----END%20SEALED%20CIPHER-----%0C-----BEGIN%20SEALED%20ENVELOPE-----%0CAAAAgCNhXbslaFobAXh4cJMbAnPwy1ig2Rn+z38ux99YgwOXxEqlVuVC1ZHnIOmdpIGzE7VXukOR%0CWhbSzTpmg-VKLRAa7hRaWeZ67-K6BVylYqbSZuU2PpXVz4QBHrFSwvSgg7JoZD6g4DV-Q43vaGV0%0Ce+GQFUWylZMeMEM+m0ryhFstecdPPsY+vAeZfyviKMTv4vd5M9oZY+tMBWsklLB7fw7MWrIdS-NN%0Cou2F+bv6fgm9QArWK62-JjGgWipV79A+C11epGRDlhKDcbmzGkWEjxxf9qLJgzhjqPB+VQPVs1Gt%0C5l0vlceFehdNxRs-7OrdiBFJAAujbQxjIHk099BbWUM89QxaJDko7qBjTTkU2w2QsDYTuFJs-S7L%0CxB9Twas4sYufxJtf8JtFGgoUjgQ2XbpWUvD8-SXcJtXk2lpW69m5CqqfuhPxuIEcfSTrVXzHzral%0C6xvrI4L7Gi8iUYpVJROJQDTcjYIqah41ExIK6r+U925OXzyTfeVUM--enVQSxxyrYxhskxDPa6tm%0CRHLBrkcXQAfjBQBFj2Nd9oSurYrXNguY2G3yBPl+kAUsNwbE9EBbsunz8npJ26XAC8PO9vAWnuPe%0CLPY50WeCZ1l2Iv2dR5ywoEKCe-g60aFLSWT2-8PNTxjeCYGogMJ1wwa2uebA6i85Hrhs5D90ybPH%0C8VVt7ChYQjeyea0Q5wXZrV6Bra95NeTl21hbV6tr1kOZcNrPDEDBLz9nUP+nJJFu4S7RdRH5OH4R%0ChtjuPvutYurmuoqZCIBPY2Z2B0eUBvIwjq-8vSuIenMWsUHWnKKHP3EoWfegDmiHVp3jv5n4cI0p%0CtTRvAbSUppqhuWSyA0UWTVQ4TuSM1kTcOAo2BuDD-PQeOH2NRjhcTvLnPQ06uFPP-LQ2aOLGi7xU%0CSUMVxkYFZRiOeS1U8AOFc8WfUR-FETaR8ZGuICB4cpaEpF8jZl5d5Iv1Pv8sFhYUAL+BRYUOM2Tb%0CsdkjD9+difulCggJTdCwUV1+XXQvIGIDroUnyjXnVr2cF2PnIzydNFY99bp4lMTKYzf8ii3HW3oK%0CV4y7DKfEkc8Rm6+kjgmwgFhosbguFsqoMmrzpW1NEN0R0yhLJPzBQmYIKYJV0Y5aV7NKPmAyM8DU%0C0IDX+A+oIrqlN4p1HhY3nHzy+nl3CCelM2BOkV13iTXYc+t-Jg==%0C-----END%20SEALED%20ENVELOPE-----

HTTP/1.1 403 Forbidden
Connection: Close
Content-Length: 99

Unable to open /home/aliprod/data/00/00000/099a8cba-c924-11e9-8ab0-c758c795bf3c; permission denied
```

With my best wishes for 2020 to the entire team!

.costin

**Comment by ffurano** [comment]
Hi Costin,

 I just checked the quote/unquote functions in xrdhttp, and they look correct to me.
 Could you please try with davix-get (or whatever else), in order to be sure that those 0A/0C are not mangled by curl ?

Cheers
Fabrizio

**Comment by costing** [comment]
Ciao Fabrizio,

The client doesn't make any difference, the Location header is returned by the server. I think the issue is here:

https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpUtils.cc#L378

 ```
      case '\n':
        strcpy(r + j, "%0C");
        j += 3;
        break;
      case '\r':
        strcpy(r + j, "%0A");
        j += 3;
        break;
```

The correct values (https://en.wikipedia.org/wiki/Newline#Representation) are "%0A" for '\n' and "%0D" (!) for '\r'. Sorry for not spotting this before!

I found another, outdated, occurrence of the quote() method in XrdTpcTPC.cc. Maybe that should also be updated as per (or consolidated with) the above at this point.

Cheers,

.costin

**Comment by ffurano** [comment]
Hey Costin, you spotted a really stupid bug, I have inverted CR with LF in the quoting...
well I think you may well be the first one trying to encode CRs and LFs.

Cooking the (equally stupid) fix now.

XrdTpc is maintained by Brian. One more good catch!

Thanks
Fabrizio

**Comment by bbockelm** [comment]
@ffurano @costing - that duplicate copy of `quote` in the XrdTpc code dated back to when that module was a separate project.

It's obviously unwelcome duplication now that it is in the same code base and can just use the `quote` function from the HTTP utility library.  #1111 removes it (and fixes the header to boot).

**Comment by abh3** [comment]
Fabrizio has this fixed -- I think it has been.

**Comment by abh3** [comment]
I think this has been fixed, hasn't it?

**Comment by ffurano** [comment]
AFAIR yes



-----Original message-----

**Comment by abh3** [comment]
Fixed
