### ISSUE TITLE
[xrootd-ceph] Add support for ReadV

### ISSUE THREAD

**Issue by osschar** [xrootd/xrootd#1067]
Ceph plugin does not support ReadV. This effectively serializes each ReadV chunk and slows down operations considerably.

**Comment by abh3** [comment]
I think this has been done. Right? Can we close it then?

**Comment by ijjorama** [comment]
We're testing this at RAL now. I'll report when we have a PR to consider.

**Comment by simonmichal** [comment]
@ijjorama : I was wondering if there's any progress that is worth reporting?
