### ISSUE TITLE
Client Hides Error When Metalink Fails

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#1071]
So, we have a metalink and the client goes and tries each one of the links and each one fails with some erro *other* than file not found (e.g. authentication error). The actual reported error to the apprilixcation becomes ENOENT (file not found) which is clearly misleading. This has caused quite a few good chases along the way. Could the client keep track of the most comment error and append it to the error message. Perhaps something like:

File not found likely because .....

where .... is the error message text of the most relevant error. Even using the last non-enoent error would be better than always reporting ENOENT.

**Comment by adriansev** [comment]
I would suggest to keep a log of errors (for each link add the corresponding error - stderr) and if no success until the list end, return the exit code of the last error and put in stderr the whole error log. If success just return the output of successful operation (with an exit of 0 of course)

**Comment by simonmichal** [comment]
@abh3 & @adriansev  : there is the redirect trace-back which also applies to the metalinks, is this not enough?

**Comment by abh3** [comment]
No, that’s not enough because it doesn’t get produced until you set the logging above what people normally set (i.e. they usually accept the default). Even if it did get produced it doesn’t substitute for a more meaningful concise message.
