### ISSUE TITLE
CentOS 8 support

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1074]
We are looking into upgrading our data transfer nodes to CentOS 8 in the next months, and while the OS and configuration went very smooth, there are not XRootD packages available yet in the repos, and there's also no RedHat 8 flavour yet in the GitLab pipeline:
https://gitlab.cern.ch/dss/xrootd/-/jobs
Since Fedora Rawhide is there, I presume it might be a simple step to add CentOS 8 support. 

Is this still in scope for the 4.xx series, or for XRootD 5?

**Comment by simonmichal** [comment]
@olifre : from what I see @ellert (thanks a lot!) pushed already 4.11.0 to epel8:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-f5b5c2eee4

**Comment by olifre** [comment]
@simonmichal @ellert Many thanks to both of you!
I'll sadly still have to wait for actual production tests since vomsxrd and the WLCG repo are not yet CentOS8-ready, but they promised to look into it during autumn when CERN offers CentOS 8 images on the internal Koji, OpenStack etc.
