### ISSUE TITLE
Third party copying broken in v4.10+

### ISSUE THREAD

**Issue by costing** [xrootd/xrootd#1077]
Hi,

We have a bunch of problems with the third party transfers and we have traced it to the upgrade to 4.10.0 on the client side. After the upgrade EOS targets work fine but vanilla Xrootd storage elements reject the transfer with this error message:

> Run: [ERROR] Server responded with an error: [3005] Internal error processing file.

Executing exactly the same command line with 4.9.1 or below works fine. 4.10.1 and 4.11.0 also don't work, so the change seems to be in 4.10.0.

A script to reproduce the issue can be found [here](http://alimonitor.cern.ch/download/3rd-xrd4.10.0.sh). You can run it freely, with different client versions to try it out.

Cheers,

.costin

**Comment by simonmichal** [comment]
@costing : thanks for reporting this problem! So far if I run with 4.9.1 I'm getting `[3005] Too many attempts to gain dfs write access to the file`, running with 4.10.0 or greater indeed yields ` [3005] Internal error processing file`. If I do a third-party-copy from `eosalice` to my vanilla xrootd server it works like a charm. I will let you know once I have better understanding of this problem.

**Comment by costing** [comment]
@simonmichal You are right, removing `--path` fixes the issue at hand.

The explicit `--path` is needed for writing to non-xrootd targets so it was added to all write operations. Other implementations don't automatically create paths so we can't completely remove this option. I'd have to start distinguishing between target types and would rather not do that. This is not a problem, I can wait until it is fixed upstream, running the old client until then.

Many thanks for your quick help!

.costin

**Comment by simonmichal** [comment]
Any time :-)
