### ISSUE TITLE
gfal-sum fails for davs protocol for files on Lustre 2.5

### ISSUE THREAD

**Issue by bockjoo** [xrootd/xrootd#1080]
The file on lustre 1.9
gfal-sum  davs://cmsio6.rc.ufl.edu:1094/store/mc/test.root ADLER32
davs://cmsio6.rc.ufl.edu:1094/store/mc/test.root 9ecd7018

The file on Lustre 2.5
gfal-sum  davs://cmsio6.rc.ufl.edu:1094/store/mc/cmsuf/test.root ADLER32
gfal-sum error: 1 (Operation not permitted) - HTTP 403 : Permission refused 

The server log shows:
191030 09:11:25 7581 ofs_chksum: http Unable to checksum /cmsuf/test/data/store/mc/cmsuf/test.root; permission denied

**Comment by abh3** [comment]
In all honesty, this issue should be reported to the gfal team for resolution. You can file a ticket at
https://its.cern.ch/jira/projects/DMC/summary
I have notified the gfal team leader that a ticket will be posted.

**Comment by bockjoo** [comment]
In fact, the reason for the error was found to be due to xrootd user account on the Lustre MDS.
No need to report to the gfal team.
