### ISSUE TITLE
xrdcp -f deletes a file in Ceph

### ISSUE THREAD

**Issue by george-patargias** [xrootd/xrootd#1084]
Hello, 

Following several tests and I confirmed that  "xrdcp -f" definitely deletes a Ceph file; The first attempt 
to overwrite the file with "xrdcp -f" results in the following error. 

**Run: [ERROR] Server responded with an error: [3007] Unable to open dteam:overwritetest/test1; input/output error**

Examining the "overwritten" file at the rados level, one sees that it is not just that the striper.size is set to 0, but that all data stripes are gone. Further attempts to overwrite this (deleted) file result in xrdcp hanging and occassionaly issuing the message "Output file alice:... is already opened by 1 writer; open denied".

George

**Comment by george-patargias** [comment]
This is actually another version of the same issue reported here 

https://github.com/xrootd/xrootd/issues/442

**Comment by simonmichal** [comment]
Fixed in: https://github.com/xrootd/xrootd-ceph/commit/9e856d490c805928b3ace33150ea2256a5e00f82
