### ISSUE TITLE
The problems with libuuid and OpenSSL on MacOS

### ISSUE THREAD

**Issue by Atlantic777** [xrootd/xrootd#1091]
Hello,

I noticed some problems with building XRootD 4.11 on MacOS. I see that libuuid dependency has been added recently. There may be two issues:

1. The libuuid has been declared to have both header and library. However, on the MacOS it's a header only library. When building on MacOS it's maybe ok to pick only the header and exclude libuuid from linker flags.

2. I failed to override the libuuid location to non-system version without changing CMake. We build our own libuuid on Linux and we could do the same on MacOS, but the only way to override it was to add "no default path" in find_path() in FindLibUuid.cmake.

Let me know if you need any additional information. Thanks!

Cheers,
Nikola Hardi

**Comment by simonmichal** [comment]
I belive this has been addressed in https://github.com/xrootd/xrootd/pull/1082

**Comment by Atlantic777** [comment]
Oh, excellent, I missed that commit! Yes, that resolves the libuuid problem.

But, I have just noticed another problem - this time it's OpenSSL related. CMake managed to find my OpenSSL installation, but linker couldn't find the lib with just `-lssl -lcrypto`. Using `${OPENSSL_LIBRARIES}` helped, like here: https://github.com/Atlantic777/xrootd/commit/2bccb5ed581384db58b06944d59d76d49c393518 .

It looks like this is indeed the preferred way for specifying linker libraries, as recommended [here]( https://cmake.org/cmake/help/v3.16/command/link_directories.html).

Should I open a PR?

**Comment by simonmichal** [comment]
Thanks for noticing it! Yes please, open a PR.

**Comment by Atlantic777** [comment]
Alright, here's the PR: https://github.com/xrootd/xrootd/pull/1093
I would really appreciate it if you could include this commit in the 4.11.x branch as well. Thank you!

**Comment by simonmichal** [comment]
https://github.com/xrootd/xrootd/pull/1082 has been already ported to stable-4.11.x
regarding your PR (https://github.com/xrootd/xrootd/pull/1093) there is no need to port it as in 4.11.x there is no dependency on openssl libraries in the client and utils - encryption is a new feature that will be released only in 5.0.0.

Is there anything else, or can we close this issue?

**Comment by Atlantic777** [comment]
Yes, that seems to be all for this issue, thanks.
