### ISSUE TITLE
Xrootd serves incorrect file contents

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1097]
In CMS, we're hitting a rather bizarre (but nightmarish!) problem with Xrootd that appears to be something in the redirection code.  See here:

https://github.com/dmwm/WMCore/issues/9432

The basic symptom is that, when file A is opened the contents of file B are given.  This is a nightmare as the contents of file B are sometimes "similar enough" (differing, say, by physics process) to allow the job to succeed.  In the most common case, file A is not actually present at the site where the client is redirected to - but yet file B is served.

The problem seems limited to sites (primarily, one DPM site - but there are others!) that include significant CGI in the redirection hostname.  Example of one such hostname in the redirection response (not from an affected job, just to illustrate what I mean by "CGI in the hostname"):

```
YYYYYY.ac.uk?&dpm.time=1575473136&dpm.dhost=YYYYYY.ac.uk&dpm.loc=1&dpm.chunk0=0,0,YYYYYY.ac.uk:/data0/dp
mfs/cms/2019-12-04/30D1B46E-D055-704E-A492-4B364B10F13C.root.125675.1575462690&dpm.nonce=XXXXXX&dpm.hv2=YYYYYYY
```

Honestly, I'm at a loss on how this could happen -- whether the redirector is serving up bad redirection URLs, the site is serving the wrong files, or some memory bug in the client causes it to make the wrong requests.  All seem remarkably unlikely - but yet something is happening.

For example, how would a memory bug in the client cause it to serve data from the file `/store/unmerged/RunIIFall18wmLHEGS/JJH0PMToTauTauPlusTwoJets_Filtered_M125_TuneCP5_13TeV-mcatnloFXFX-pythia8/GEN-SIM/102X_upgrade2018_realistic_v11-v1/230000/B04C9BFD-09C6-0D4D-8E67-2D4DDCE88027.root` when we request `/store/unmerged/RunIISummer19UL17wmLHEGEN/QCD_HT100to200_TuneCP5_PSWeights_13TeV-madgraphMLM-pythia8/GEN/106X_mc2017_realistic_v6-v1/40017/81CB9803-B71C-464B-AD3F-5B53605EF41E.root`?  These are from unrelated datasets, different campaigns, and different versions -- and the incorrect filename (the one ending with `B04C9BFD-09C6-0D4D-8E67-2D4DDCE88027.root`) is nowhere within the job!

On the other hand, DPM seems to validate that the CGI presented matches the filename requested (@ffurano - can you confirm?).  So it's unlikely that the redirector simply cached some CGI in the hostname.  Further, if it was a DPM bug, why would the DPM site receive a redirection for a file it doesn't have?

Finally, for the culprit to be the redirector, why would it be changing the filename in the redirection (honestly, I thought that was impossible)?  Why does it affect one modest-sized T2 and not huge sites like CERN?  If it was a random cache corruption, wouldn't it affect all subscribed sites equally?

**Comment by xrootd-dev** [comment]
Are the server running in kubernetes as containers? If so, please read the 
following:

https://xrootd.slac.stanford.edu/doc/dev410/cms_config.htm#_Toc8247294

as well as the sections above it:

https://xrootd.slac.stanford.edu/doc/dev410/cms_config.htm#_Toc8247294

Andy

**Comment by bbockelm** [comment]
Nope, these are traditional WLCG sites.

That said, why would running these in k8s cause servers to serve the wrong filename?

**Comment by xrootd-dev** [comment]
Huh? It's pretty well explained in that document I thought. It 
specifically says why that can happen.

**Comment by xrootd-dev** [comment]
One more thing. It is impossible for the redirector to serve up the wrong 
filename. If you asked for file "A" the worst the redirector can do is 
send you to the wrong server. The redirector redirect useing only the 
hostname or IP address not a full URL. So unless he client is 
manufacturing a wrong filename (unlikely as this would have been obvious 
from he get go) then one would conclude that is some cases two different 
files got the same file name. I suppose it's also possible that something 
is messed up in the server and the file name is associated with the wrong 
data. Simple to test, open the file at the server and see if you get the 
right file.

**Comment by bbockelm** [comment]
> I suppose it's also possible that something is messed up in the server and the file name is associated with the wrong data

That's the very strange part of all of this.  The DPM site never saw a request for the "correct" filename.  That is, the client tried to open `81CB9803-B71C-464B-AD3F-5B53605EF41E.root` and recorded that in the client log.  Around the same time (within a 5 second skew), DPM site logged an access for `B04C9BFD-09C6-0D4D-8E67-2D4DDCE88027.root`.  The "correct" filename `81CB9803-B71C-464B-AD3F-5B53605EF41E.root` never existed at the DPM site and the client never logged anything about `81CB9803-B71C-464B-AD3F-5B53605EF41E.root`.

So for DPM to be the culprit, it would have to advertise the availability of a file it never had and, for an incoming client, record the wrong filename in the log but send the client to the contents of the wrong filename.

Theoretically, this can't be the fault of the DPM site, the redirector, or the client -- and yet it seems to happen multiple times a day!

> Simple to test, open the file at the server and see if you get the right file.

When done by hand, trying to open `81CB9803-B71C-464B-AD3F-5B53605EF41E.root` (which shouldn't exist at the DPM site) results in a file-not-found and opening `B04C9BFD-09C6-0D4D-8E67-2D4DDCE88027.root` results in the correct file contents.

**Comment by abh3** [comment]
OK, not that this is going to solve anything but...

"So for DPM to be the culprit, it would have to advertise the availability 
of a file it never had"

When we were doing ATLAS that was an enduring problem for certain DPM 
sites. Yes, they would advertise files they never had. However, in that 
case, the client would simply give up when it went to that server. So, 
something else is going on now.

Can we narrow this down? For instance, can we get a repeatable case? What 
if I search for the file you mentioned below, will I go to the wrong 
sever? Will the server provide the wrong file? Or those this just happen 
randomly? We need at least one file (hopefully more than one) that we can 
ask each redirector the state of the file and then follow up at each site.

Finally, do we have an idea of what client version is involved here. 
Again, the redirector can't substitute file names (though it has that 
ability -- presumably that is not being used here). So, that would mean 
the client is doing that in some weird fashion.

**Comment by abh3** [comment]
So, thinking over many, probably not all, possibilities over my morning 
coffee I come to the conclusion that is must be an MT unsafe problem.

Client A is opening two files X and Y, while X gets resolved the client is 
using the URL for Y to access the file while the code thinks it's actually 
using X. It just so happens that Y is located in the destination server so 
it works, incorrectly. Why? because the URL is perfectly valid so it isn't 
likely to be a storage overlay it is more likely to be a complete 
substitution. That can only happen in the client. Is it possible that 
there is a problem in the software framework that drives all of this?

Anyway, I am off to commue and will pick this thread up at my destination.

**Comment by bbockelm** [comment]
> When we were doing ATLAS that was an enduring problem for certain DPM sites.

Right, that was my first thought.  However, my recollection was this was very reproducible - they basically advertised the existence of every file.  This happens with the probability of something like `10^-5` (which also makes it extremely difficult to figure out where things are coming from).

> Can we narrow this down? For instance, can we get a repeatable case? 

Unfortunately, I've been trying for about 2 days to come up with something repeatable - or at least seeing this in the lab.  No luck :(

> Finally, do we have an idea of what client version is involved here

A number of versions of the client are used, depending on the software release.  If you want to zero in on one, 4.8.5 is perhaps the most common.

> Is it possible that there is a problem in the software framework that drives all of this?

Certainly - I haven't been able to rule this out.  However, the problem with this theory is that file names X & Y are sometimes completely different - different datasets, different software versions, different production "campaigns" and for the most part not mentioned in the same job.  We have only found one case where X & Y were both input files in the same job.

We are still waiting for redirector logs on this.  Depending on the redirector log contents, we should really be able to narrow down the suspects.

**Comment by bbockelm** [comment]
Just to quantify - we appear to be hitting about 30 of these errors a day globally (where 29 / 30 are from the same site).  Even if we can't reproduce it, we are moving that site to a new redirector and going to crank the log level as much we can ... if there are any particular flags you'd like to see set on the redirector, let me know.

**Comment by abh3** [comment]
The only thing you need to crank in the redirector is:

cms.trace files redirect stage

Anyway, which site are we talking about? It seems to be involved in 99.999% of these. Do you know which is the other lone site?

**Comment by abh3** [comment]
I am closing this as here has been no feedback on this issue since last year. Presumably the problem has been resolved or at least explained. Reopen this ticket if it's still an issue.
