### ISSUE TITLE
Lustre 2.12.3 files invisible from redirector from time to time

### ISSUE THREAD

**Issue by bockjoo** [xrootd/xrootd#1098]
I can see files on the Lustre 2.5 from the xrootd servers, but

they become invisible from time to time from the xrood redirector:

${bockjoo@ala:transfers}  xrdmapc --list all cmsio5.rc.ufl.edu:1094
0**** cmsio5.rc.ufl.edu:1094
      Srv cmsio7.rc.ufl.edu:1094
      Srv cmsio8.rc.ufl.edu:1094
${bockjoo@ala:transfers} xrdcp -d 1 -f root://cmsio5.rc.ufl.edu:1094//store/test/xrootd/T2_US_Florida/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/A64CCCF2-5C76-E711-B359-0CC47A78A3F8_cmsuf.root /dev/null
[0B/0B][100%][==================================================][0B/s] 
Run: [ERROR] Server responded with an error: [3011] Unable to access file; file does not exist.

${bockjoo@ala:transfers} xrdcp -d 1 -f root://cmsio7.rc.ufl.edu:1094//store/test/xrootd/T2_US_Florida/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/A64CCCF2-5C76-E711-B359-0CC47A78A3F8_cmsuf.root /dev/null
[24MB/229.3MB][ 10%][=====>                                            ][24MB/s][144MB/229.3MB][ 62%][===============================>                  ][72MB/s[229.3MB/229.3MB][100%][==================================================][114.[229.3MB/229.3MB][100%][==================================================][114.7MB/s] 

${bockjoo@ala:transfers} xrdcp -d 1 -f root://cmsio8.rc.ufl.edu:1094//store/test/xrootd/T2_US_Florida/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/A64CCCF2-5C76-E711-B359-0CC47A78A3F8_cmsuf.root /dev/null
[32MB/229.3MB][ 13%][======>                                           ][32MB/s][152MB/229.3MB][ 66%][=================================>                ][76MB/s[229.3MB/229.3MB][100%][==================================================][114.[229.3MB/229.3MB][100%][==================================================][114.7MB/s] 

Is this a redirector bug?

If I touch the file by invoking ls against the file on the redirector, the file becomes visible for 3 minutes or some short period of time.

**Comment by bockjoo** [comment]
I have straced the cmsd process with successful one and not:
Successful one looks like:
[pid 294823] <... recvfrom resumed> "\377/\0\0\n\0\0\207", 8, MSG_WAITALL, NULL, NULL) = 8
[pid 294823] recvfrom(21, "\0\1\0\240\0\0\0\10\0y/store/mc/SAM/GenericT"..., 135, MSG_WAITALL, NULL, NULL) = 135
[pid 294823] futex(0x64b1b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 300419] <... futex resumed> )      = 0
[pid 294823] recvfrom(21,  <unfinished ...>
[pid 300419] stat("/cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/A64CCCF2-5C76-E711-B359-0CC47A78A3F8.root", {st_mode=S_IFREG|0664, st_size=240461986, ...}) = 0
[pid 300419] writev(21, [{"\377/\0\0\2\0\0\27", 8}, {"\0\0\4Fcmsio10.rc.ufl.edu\0", 23}], 2) = 31
[pid 300419] futex(0x64b1b8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 294827] <... nanosleep resumed> 0x7f8093e46d60) = 0

Unsuccessful one has two types of strace outputs:
[pid 335099] nanosleep({1, 0},  <unfinished ...>
[pid 335110] <... recvfrom resumed> "\377\37\0\0\n\0\0\215", 8, MSG_WAITALL, NULL, NULL) = 8
[pid 335110] recvfrom(22, "\0\1\0\240\0\0\0\10\0\177/store/mc/SAM/GenericT"..., 141, MSG_WAITALL, NULL, NULL) = 141
[pid 335110] futex(0x64b1b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 336772] <... futex resumed> )      = 0
[pid 335110] recvfrom(22,  <unfinished ...>
[pid 336772] mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7fb378000000
[pid 336772] munmap(0x7fb37c000000, 67108864) = 0
[pid 336772] mprotect(0x7fb378000000, 135168, PROT_READ|PROT_WRITE) = 0
[pid 336772] stat("/cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root", 0x7fb3979f3950) = -1 EACCES (Permission denied)

[pid 336772] stat("/cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
[pid 336772] writev(22, [{"\377\37\0\0\1\0\0000", 8}, {"\0\0\0\1Unable to access file; file "..., 48}], 2) = 56
[pid 336772] futex(0x64b1b8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 335099] <... nanosleep resumed> 0x7fb39d6bed60) = 0


[pid 335099] nanosleep({1, 0},  <unfinished ...>
[pid 335110] <... recvfrom resumed> "\377+\0\0\n\0\0\215", 8, MSG_WAITALL, NULL, NULL) = 8
[pid 335110] recvfrom(22, "\0\1\0\240\0\0\0\10\0\177/store/mc/SAM/GenericT"..., 141, MSG_WAITALL, NULL, NULL) = 141
[pid 335110] futex(0x64b1b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 336772] <... futex resumed> )      = 0
[pid 335110] recvfrom(22,  <unfinished ...>
[pid 336772] writev(22, [{"\377+\0\0\1\0\0000", 8}, {"\0\0\0\1Unable to access file; file "..., 48}], 2) = 56
[pid 336772] futex(0x64b1b8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 335099] <... nanosleep resumed> 0x7fb39d6bed60) = 0
[pid 335099] nanosleep({1, 0}, 0x7fb39d6bed60) = 0

**Comment by abh3** [comment]
So, it would seem the culprit is here:
tat("/cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root", 0x7fb3979f3950) = -1 EACCES (Permission denied)

The redirector doesn't have access permissions. Is the directory/file owned by the user running the cmsd?

**Comment by bockjoo** [comment]
It is world readable:
[root@cms ~]# ls -al /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root
lrwxrwxrwx 1 root root 131 Dec 10 13:37 /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root -> /cmsuf/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root
[root@cms ~]# ls -al /cmsuf/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root
-rw-rw-r-- 1 cmsphedex cmsdata 1293057986 Oct 21  2017 /cmsuf/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root

**Comment by abh3** [comment]
Yes, but then that doesn't correspond to the error the ketnel gave. So, say you login to the redirector host using the same credentials that is being used by the cmsd on that host and then try to do an ls -l /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root
I presume the file is still there and, based on the previous config, you are using a vanilla setup.

**Comment by bockjoo** [comment]
I am mapped to the account called cmsphedex. It looks fine to me. I am not sure what a vanilla setup is, though. This redirector is working fine with the original Lustre filesystem (Lustre 1.9).
[root@cmsio3 ~]# su - cmsphedex
Last login: Tue Dec 10 16:26:10 EST 2019 on pts/0
-bash-4.2$ ls -al /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root
lrwxrwxrwx 1 root root 131 Dec 10 13:37 /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root -> /cmsuf/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root
-bash-4.2$ ls -al /cmsuf/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root
-rw-rw-r-- 1 cmsphedex cmsdata 1293057986 Oct 21  2017 /cmsuf/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root
-bash-4.2$ cksum /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root
687559508 1293057986 /cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root

**Comment by abh3** [comment]
What about the redirector cmsd log covering the time period where
pid 336772] stat("/cms/data/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A_cmsuf.root", 0x7fb3979f3950) = -1 EACCES (Permission denied)
occurred.

**Comment by bockjoo** [comment]
There is nothing about the file during that time in the cmsd log ( /var/log/xrootd/clustered/cmsd.log ).

**Comment by abh3** [comment]
OK, just send me the whole log (don't post it) from the time is started up.

**Comment by bockjoo** [comment]
I sent you the log files in the email.

**Comment by abh3** [comment]
I am closingthis as I believe we have determined that this was due to a Lustre bug in that particular version.

**Comment by bockjoo** [comment]
In fact, the reason for the error was found to be due to xrootd user account on the Lustre MDS.
