### ISSUE TITLE
configuration syntax :: add include directive (or directory parsing)

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1102]
It would be nice to have a simple include specification that would allow the parsing the contents of a directory (conf.d type of configuration). this include would have the behaviour of conf-dir/conf-file of dnsmasq or httpd include. This would help a lot with automatic provisioning or just on the fly tuning.
If automatic configuration is desired (without include directive), automatic parsing of a directory that have the name of the configuration file could be used (e.g if the conf file is myconf.conf let's parse automatically the .conf files from the directory myconf.d).

**Comment by abh3** [comment]
You actually already have something very similar using the "continue" directive. Please see
https://xrootd.slac.stanford.edu/doc/dev49/Syntax_config.htm#_Toc520499864
which allows you to continue into a directory of configuration files. Now, that said, I just had a very long debug session where someone used this feature and decided to break up the config file into 12 pieces. There is no way a standard human can co-ordinate that many fragments without making a mistake. Which, of course, there were numerous ones. So please be careful for what you ask for, Simplicity will always win out. I am closing this ticket assuming the continuation feature is sufficiently close to what you are asking for. If not, just reopen the ticket.
