### ISSUE TITLE
xrdcp checksum implementation is slow

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#1103]
**Examples**:

(These measurements are done in a 25GBit environment .... )

**MD5:**
Download 10G file => 5.7s 
md5sum 10G file => 16.5 s

Now let xrdcp do the same:
xrdcp --cksum md5 root://remote... /var/tmp/X => 54s

**ADLER32:**
Download 10G file => 5.7s 
adler32 10G file => 5.0 s

Now let xrdcp do the same:
xrdcp --cksum adler32 root://remote... /var/tmp/X => 23s

Similar behavior when uploading files.

**Comment by abh3** [comment]
There are two possible solutions:
md5 - use the implementation in libz, it should be about 20% faster.
adler32 - use a retrofitted CRC32C (i.e. change lookp table and parameters). The speed increase is yet unknown but there should be some gain here.

**Comment by simonmichal** [comment]
We have now hardware assisted crc32c, can we close this one?
