### ISSUE TITLE
python 4.11.1 local build:: import xrootd does not work

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1105]
Hi! It seems that something is still missing as if i build locally the python bindings i still cannot do `import xrootd`   
in user site-packages i have this :   
```
find -maxdepth 1 -iname "*xrootd*"   
./pyxrootd   
./xrootd-v4.11.1-py3.7.egg-info  
./XRootD
```   
Any idea about this? Moreover, is it required to have multiple directories? Wouldn't be more consistent to have everything in one single place and with one single name?

**Comment by simonmichal** [comment]
@adriansev : just to clarify, what do you mean by 'build locally', do you build from sources and install?

**Comment by adriansev** [comment]
@simonmichal yes, from v4.11.1 checkout.

**Comment by adriansev** [comment]
so, this is a failure to understand for me that the pip package name and the actual module name that is imported are two different things! (where module name is either the alias/dummy pyxrootd or the actual name XRootD)
