### ISSUE TITLE
Add an alternative file descriptor based read/write API in XrdClFile to avoid buffer management

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#1117]
For Applications like xrdcp or FUSE mounts it would be very beneficial to have an API like

      XRootDStatus Read( uint64_t         offset,
                         uint32_t         size,
                         int                  output_fd, 
                         uint64_t         output_offset,
                         ResponseHandler *handler,
                         uint16_t         timeout = 0 )
                         XRD_WARN_UNUSED_RESULT;

      XRootDStatus Write( uint64_t         offset,
                          uint32_t         size,
                          int                  input_fd, 
                          uint64_t         input_offset,
                          ResponseHandler *handler,
                          uint16_t         timeout = 0 )
                          XRD_WARN_UNUSED_RESULT;

This would allow to simplify the buffer management in particular with asynchronous callsbacks and avoids memory copy operations using splicing.

**Comment by simonmichal** [comment]
The support for `splicing` when writing has been introduced in `5.1.0`:
https://github.com/xrootd/xrootd/blob/d9c52f3c09b34f58c835f1a9d6b7414827d2f9fb/src/XrdCl/XrdClFile.hh#L276-L344

Currently we don't have a valid use case for reading so I'm closing this one.
