### ISSUE TITLE
XrdHttp does not populate the XrdSecEntity.prot field

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1122]
Some OFS plugin implementations i.e. EOS rely on the type of protocol the access is being done to properly redirect the clients to different storage nodes and ports. When a requests comes from XrdHttp the protocol information is missing from the XrdSecEntity.prot filed. This is present however in the tident fields but this looks like a hack and misleading since the tident info is totally different when access is done through the XRootD protocol.

Could this info be added to the XrdSecEntity object?

Thanks,
Elvin

**Comment by abh3** [comment]
Hi Elvin,

Indeed, this has been done for R5. Adding in a proper way breaks ABI. 
That's why we waited until R5 to do so. Look at XrdSecEntity::pros.

Andy

**Comment by ffurano** [comment]
Ah, I was remembering that there was something behind, because it used to be populated in previous versions.
What shall we do with this ticket then?

**Comment by abh3** [comment]
Let me see how to fix this. You are correct.

**Comment by abh3** [comment]
This has been fixed in R5.
