### ISSUE TITLE
metalink multi source: automatic fallback

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1128]
Hi! It would be useful that even with default sourcelimit=1 to fallback to the other sources specified in the metalink.

**Comment by xrootd-dev** [comment]
If so, how would someone force only one soure to be used? If it only 
applies to the default, then doesn'rt raining the default value 
accomplish the same thing?

**Comment by adriansev** [comment]
why would someone want to use/try only one url source? after the first url is tried and the file is downloaded and hash check is ok then the download is complete. if any if these 3 steps fail just move to the next url/replica.

**Comment by abh3** [comment]
I think the issue here is that the default specifes how many parallel 
sources are to be used (i.e. simultaneously). A default of 1 is 
reasonable. The processing allows, all sources may be tried, one at a 
time, until a working source has been found.

**Comment by adriansev** [comment]
Well, this is both weird and embarrassing and/or pointing to some other problem ..
My initial observation that there is no fallback come from usage of python bindings.. now, in order to be sure of what am i talking i saved the metafile that i use in python bindings and tried by hand with crippling of the first url and the fallback worked ..

**Comment by adriansev** [comment]
So, after a few tryouts with xrdcp and metalink file i can only conclude that the fallback works.
the only certain bug is multiple-source in combination with file in zip archive situation but it's not within purpose of this issue. Thank you and sorry for the noise!
