### ISSUE TITLE
Please reenable XrdClient build - important

### ISSUE THREAD

**Issue by cholmcc** [xrootd/xrootd#1132]
Hi, 

Commit   8123c4f17d14767ddb7095a1f73d2530ec25988a removes the libXrdClient library from the build.  However, external packages, such as XAlienFS (see https://github.com/alisw/xalienfs) uses this interface (albeit _private_).

Thanks. 

Chritian

**Comment by cholmcc** [comment]
BTW, commit e62ab78b4ff817792b09f4ca23df0acddd2fbaf0 removes XrdSysDNS from libXrdUtils.  This must also be included for XrdClient.

**Comment by adriansev** [comment]
@cholmcc the old obsolete xalienfs never compiled with anything greater than xrootd 3.x
and it's on the way to be completely removed. The current central services are based on java and client-server communication no longer used xrootd 3.x. See jalien related documentation for both server, ROOT plugin, and clients.

**Comment by cholmcc** [comment]
Are you sure? Default `aliBuild` still pulls in [`apmon-cpp`](https://github.com/alisw/alidist/blob/master/apmon-cpp.sh), [`xrootd` 4.11.1](https://github.com/alisw/alidist/blob/master/xrootd.sh), and [AliEn-ROOT-Legacy](https://github.com/alisw/alidist/blob/master/alien-root-legacy.sh).  Also the ROOT plugin [`Netx`](https://github.com/root-project/root/tree/master/net/netx) uses the `XrdClient` interface (often pulled in by the build). The alternative (`NetxNG` - guess `NG` stands for _Next Generation_) only uses the currently public interface `XrdCl` and is used by the [TJAliEn](https://gitlab.cern.ch/jalien/jalien-root) client plugin (the project still build-depends on `Netx` though - probably shouldn't). 

In any case, it seems that the use of `XrdClient` isn't completely dead yet, and perhaps it would be a good idea to re-enable that interface.  A few minor things need to be fixed in the build, but that is it.

**Comment by yuw726** [comment]
Hi,

`AliEn-ROOT-Legacy` and `xalienfs `are build only with specific XRootD tag: v3.3.6-alice2 (according to [defaults-prod-latest](https://github.com/alisw/alidist/blob/master/defaults-prod-latest.sh), [defaults-user](https://github.com/alisw/alidist/blob/master/defaults-user.sh) and [defaults-release](https://github.com/alisw/alidist/blob/master/defaults-release.sh).)
New `JAliEn-ROOT` uses XRootD 4.

We are already working on removal of `Netx` dependency both for `AliEn-ROOT-Legacy` and `JAliEn-ROOT`, it shouldn't become a problem for us if `XrdClient` disappears. However, it seems that there are some [Proof](https://github.com/root-project/root/blob/master/proof/proofx/inc/TXSocket.h) classes depending on it

Cheers,
Volodymyr

**Comment by simonmichal** [comment]
Hi guys, 

Sorry for the late response but I have been on holidays, `XrdClient` is currently deprecated hence following warning:
https://github.com/xrootd/xrootd/blob/babbe360c959c371b60c62b38dc992502f4cc76f/src/XrdClient/XrdCommandLine.cc#L1788

We intend to remove it from our releases starting with R5, I will ping the root team about the dependency in Proof (thanks for pointing it out).

**Comment by simonmichal** [comment]
I will close this one as it seems to me there is consensus that XrdClient is a non-critical and redundant component.
