### ISSUE TITLE
libXrdFileCache.so -> libXrdPfs.so

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1135]
in Xrootd 5 rpms, can we create a symlink libXrdFileCache.so -> libXrdPfs.so ?  This will allows packages that currently linked against libXrdFileCache.so to continue to work.

**Comment by osschar** [comment]
Hmmh, isn't it recommended to link against the versioned name, i.e., libXrdXyzz-5?
In this case the dependent packages need to be rebuilt anyway.

What are those packages, actually? I'd expect pfc to only be usable from xrootd / pss setup :)

**Comment by abh3** [comment]
Yes, the version number should be in thename.Other thn reompiling; no 
other changes are needed. Not having the link means people will need to 
chsge thei config fies. are.

Andy

**Comment by osschar** [comment]
But you said you made the hack in pss.cachelib processing to make it work.

**Comment by abh3** [comment]
Goo point! Indeed, if the config has FileCache in it the nasty message is 
issued and we go ahead and use Pfc-5.so instead.

**Comment by abh3** [comment]
No need. In R5 if the config file specifies XrdFileCache-4.so or XrdFileCache.so, a nasty message tells you that is outdated and you should use XrdPfc.so and hen it goes ahead and uses that. So, config files will not break.

**Comment by wyang007** [comment]
Not quite. the rucio n2n package for example, links against libXrdFileCache-N.so. If we change that to libXrdPfs-N.so, then OSG will have to release a new RPM of the rucio n2n for xrootd 5, even though the rucio n2n itself didn't change.

I omitted the -N.so to illustrate the issue.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338 (O)

**Comment by bbockelm** [comment]
From the OSG point-of-view: if we have to do a modest recompilation like this, it's no worry at all.  My worry from the OSG side is anything that can cause significant disruption / reconfiguration for sites.

**Comment by abh3** [comment]
The rucio N2N package must neve link against a plugin library. That is 
forbidden and not supported and never will be. It violates EPEL rules 
(among others). I will work wit you to come up with an alternative 
solution and I know they exist. Of course, that assumes you actually meant 
"link" and not dynamically load.

**Comment by abh3** [comment]
Indeed, there should not be any disruption if locally developed code 
followed the usage rules. We have tried vety hard to make sure that the 
only thing that is required is a recompliation. Existing config files 
should work just fine.
