### ISSUE TITLE
xrdcp (and bindings) metalink download: retry the list n times

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1139]
Hi! It would be useful a '-retry N' option where the action is tried a N times.
For metalink this would try the source list N times.

**Comment by adriansev** [comment]
ping @simonmichal Hi! this would be really useful for a lot of critical operation where, baring a server-side message error that point to an command error (file not found or a syntax error) one might want the the operation to be automatically retried (and this would be really useful for large lists of files).
the default 0 would mean no retry, and the option should work recursively (for a list of jobs of metafiles a retry of 2, with retry each metafile 2 times, and the whole list 2 times so a total of 4 trials per file/metafile. of course unless successful )
Thank you!!

**Comment by simonmichal** [comment]
@adriansev : I'm not sure I got your example ;-)

Let's say we have a `CopyProcess` with 2 `CopyJob`s (be the source a Metalink or an ordinary file, doesn't matter), I would assume that `retry=1` that in case of failure each of the `CopyJob`s should be retried once.

Also, I suppose it would be wise to come up with a criteria when it makes sense to retry a failed `CopyJob`, e.g. I suppose it doesn't make sense to retry file-does-not-exist or authentication-failed error.

Let me know your thoughts!

**Comment by adriansev** [comment]
@simonmichal 
> @adriansev : I'm not sure I got your example ;-)
> 
> Let's say we have a `CopyProcess` with 2 `CopyJob`s (be the source a Metalink or an ordinary file, doesn't matter), I would assume that `retry=1` means that in case of failure each of the `CopyJob`s should be retried once.

yeah, exactly!
but it would be fantastic if for metafiles also the internal list would also be retried with the same number of retries
 
> Also, I suppose it would be wise to come up with a criteria when it makes sense to retry a failed `CopyJob`, e.g. I suppose it doesn't make sense to retry file-does-not-exist or authentication-failed error.

yeah exactly .. i think that the only error conditions that make sense to retry are the timeouts .. maybe also for disk full when writing? because at retry another data server could be selected.. also i usually have in the external write tests an error like `[3011] Unable to access file; eligible servers shunned. (destination)`  maybe the retry could help?
also dropped connections i think that also go to timeout isn't it?

> Let me know your thoughts!

What do you think? Thanks a lot!!

**Comment by abh3** [comment]
Hi Adrian,

The reason you get these errors points out the standard behaviour of an 
XRootD cluster. To prevent you from leaving file turds around, once a 
write is started at a server the client is bound to that server and you 
can't simply ask for another one because you'll proliferate multiple files 
which are different but have the same filename; a nightmare scenario. 
This doesn't apply to clusters that offer write recovery like EOS where 
the client will be able to write recover at another server.

Ah, you say, but I enabled POSC. Indeed, if you did that you would be 
technically able to recover once that file gets deleted but that happens 
in an indeterminate time and the redirector won't let you recover 
elsewhere until that happens (which for a dead server might not happen 
for a long time). Even if the server were not dead, you would have to 
tune POSC to delete the file within the client's retry window which is 
essentially 0 seconds and from a practical standpoint that just 
creates a race condition and makes recovery non-deterministic.

Andy

**Comment by simonmichal** [comment]
@adriansev : if I understand correctly for `retry=1` and a single `CopyJob` with a metalink source with two replicas you would like each replica to be retired once, and then if that doesn't work try again the whole `CopyJob` (which would again try each replica twice). So this would mean each of the two replicas would be tried 4 times. Personally I would prefer to keep it simple and apply the retries only to the `CopyJob`.

**Comment by adriansev** [comment]
@simonmichal yeah, in the end it's enough that the copy job is retried, so it's fine as you said it

**Comment by simonmichal** [comment]
@adriansev : I just pushed 290367f4cbafd8276dc8e250f2aa3f236c668d90, this implements the copy-job retry, it should be also available in Python. It will retry all types of socket errors as well as operation expired and threshold exceeded errors.

Now, if you use say `xrdcp --retry 1 ...` and the destination file will be created before the copy job fails the retry will also fail due to `file-exists` error, so it does make sense to do either
- `xrdcp --force --retry 1 ...`  (truncate the file), or
- `xrdcp --continue --retry 1 ...` (continue from the point where the previous transfer was interrupted)

Let me know if this looks good!

**Comment by adriansev** [comment]
Hi @simonmichal ! thanks a lot! but i'm not very sure how to use it from python .. doing a grep for the name of the internal variable i get only this:
```
ag -i retry src/XrdCl/XrdClDefaultEnv.cc src/XrdCl/XrdClConstants.hh
src/XrdCl/XrdClDefaultEnv.cc
267:    REGISTER_VAR_INT( varsInt, "ConnectionRetry",         DefaultConnectionRetry         );
297:    REGISTER_VAR_INT( varsInt, "NotAuthorizedRetryLimit", DefaultNotAuthorizedRetryLimit );
305:    REGISTER_VAR_INT( varsInt, "RetryWrtAtLBLimit",       DefaultRetryWrtAtLBLimit       );

src/XrdCl/XrdClConstants.hh
52:  const int DefaultConnectionRetry         = 5;
87:  const int DefaultNotAuthorizedRetryLimit = 3;
95:  const int DefaultRetryWrtAtLBLimit       = 3;
116:      { "ConnectionRetry",         DefaultConnectionRetry },
146:      { "NotAuthorizedRetryLimit", DefaultNotAuthorizedRetryLimit },
154:      { "RetryWrtAtLBLimit",       DefaultRetryWrtAtLBLimit }
```

What parameter should i set to enable retry?
Thanks a lot!

**Comment by simonmichal** [comment]
@adriansev : I added a new parameter to `CopyProcess.add_job`:
https://github.com/xrootd/xrootd/blob/bbf477b876818485ac9250f97f53464a6a38f6a6/bindings/python/libs/client/copyprocess.py#L130-L131

you simply pass a `retry` argument.

That said, I just noticed it is missing the `continue` argument, I'll add it right away.

**Comment by simonmichal** [comment]
A `cont` argument should be now available in `CopyProcess.add_job`:
https://github.com/xrootd/xrootd/blob/af281a0b869ce028d7427d0380930ec0ccb35262/bindings/python/libs/client/copyprocess.py#L133-L134

**Comment by adriansev** [comment]
@simonmichal 

> @adriansev : I added a new parameter to `CopyProcess.add_job`:
> https://github.com/xrootd/xrootd/blob/bbf477b876818485ac9250f97f53464a6a38f6a6/bindings/python/libs/client/copyprocess.py#L130-L131
> 
> you simply pass a `retry` argument.

Thanks!! well, i would have like if it's possible to have an env variable ... my problem is that i do not know before hand what
xrootd is available, and changing the signature means for me to make a check on xrootd version (or git version if the deployment is from git) and then use (add to) another signature...
With the env variable approach i can set it anyway (when i'm parsing my received arguments) and nothing breaks,
it will just be ignored ... 

> That said, I just noticed it is missing the `continue` argument, I'll add it right away.
i have a default of always `posc` so, the file will be deleted if any error happened (and anyway outside of xrootd process i check if there is the destination and if not valid, the destination is deleted, if valid, it's skipped and not passed to xrootd)

Thanks!!

**Comment by simonmichal** [comment]
@adriansev : OK, I see your point, I will add an `XRD_CPRETRY` envar then.

Now, let's determine first the desired behaviour ;-) let's say the `CopyJob` times out and it is being retried, do you want the copy process to start from scratch or from the point where the previous `CopyJob` was interrupted? If the former is true we need the `force` flag and if the later the `continue` flag is needed. Do you want me also to set one of those flags if the `XRD_CPRETRY` is set?

**Comment by adriansev** [comment]
@simonmichal great, thanks a lot!
So about the behavior: having posc enabled (always) i trust that the incomplete data will be deleted .. The problem is that i cannot trust the continue as i cannot check the validity of the download as the md5 that i have is external to the xrootd subsystem (comes from central catalogue) and i do not know if it's possible and how to say to xrd copy job : "this file is valid if the md5 is X"
So, my preference would be to just start from scratch (especially that partial downloads cannot be verified in chunks.. or can they?)
Thanks a lot!

**Comment by simonmichal** [comment]
@adriansev : you should be able now to set the number of retries using: `XRD_CPRETRY`.

On retry I am adding by default the `force` flag (I did a simple test and having just `posc` was not enough), you can change this by setting `XRD_CPRETRYPOLICY`, the value should be either `force` or `continue`.

Please give it a try :-)

**Comment by simonmichal** [comment]
@adriansev : any thoughts? do you think we can close this issue?

**Comment by adriansev** [comment]
@simonmichal sorry, yes, this can be closed .. i do not have a failing target at this moment so i cannot test it, but i will use 'CpRetry' and `CpRetryPolicy` and i will see how they work. So, i will close this, and if i found a bug i will open a new issue. Thanks a lot!!
