### ISSUE TITLE
Metalink processing clobbers the auth tokens if 1st replica fails

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1140]
We discovered that the authorization token is somehow clobbered if the first replica fails, this having the effect of complete failure of download. See the relevant logs [here](https://cernbox.cern.ch/index.php/s/55Y3DdllLhBKPSz) 
We (ALICE) would appreciate any fast-path possibility for a resolution and tagging :)
(the new standard client the we use, make use metalinks for download)
Let me know how can i help!
Thanks a lot!!!
Adrian

**Comment by adriansev** [comment]
i think that this can be closed, as it was found by @simonmichal () that this is a Castor problem, and i quote from the email: 

> To be more precise, the issue is in the xrootd redirector plugin for CASTOR, where a wrong assumption is made on ... the type of the object (std::string vs. XrdOucString).

But it's up to you @simonmichal @abh3 if this could/should be closed now or after the Castor guys fix the xrootd plugin

**Comment by simonmichal** [comment]
@adriansev : thanks for reminding us about this one, actually I pushed a fix to castor: https://gitlab.cern.ch/castor/CASTOR/-/commit/5c5c692ef70ffda7d4f7855dd1fa2518543dbeee so this can be ceratainly closed
