### ISSUE TITLE
xrdcp 5.0.0 not failing xroots when redirected to data server with no TLS

### ISSUE THREAD

**Issue by alrossi** [xrootd/xrootd#1145]
I am not sure whether this is indeed a bug in the xrootd client, but am posting this issue to get some feedback to verify if the dCache pool (data server) is doing everything it should be doing.

Below, please find three logs:  the xrdcp log, the dCache door log and the dCache pool log.

Configuration for the run is as follows:

```
xrdcp500 -f -d 3 xroots://dmsdca15.fnal.gov:1094//pnfs/fs/usr/test/arossi/volatile/tls-5/testdata /dev/null >& xrdcp.log
```

The dCache door (manager) is configured:

```
GSI TLS LOGIN STRICT 
```

which, in terms of the xrootd server configuration, would be equivalent to

```
xrootd.tls login
```

plus GSI settings.

The pool (data server) is configured:

```
TLS OFF
```

which means no TLS support.

As you can see, the transfer succeeds.

I direct your attention to the pool log in particular:

```
[] Sending protocol message with server flags mode: OFF, flags: 1  ...
```

that is, the protocol response flag has only the least significant bit set, so there are no TLS directives sent back to the client.

I note in the client log that there is no indication that the client is trying to do TLS on the redirected endpoint.  I would expect a login failure, however, because the transfer uses 'xroots' and the pool (data server endpoint) does not support it.

If there is something else that needs to be done in order to get the client to fail in this case, or if the client shouldn't fail (though I would expect it to), I'd appreciate hearing the details.

Thanks, Al Rossi

[xrdcp.log](https://github.com/xrootd/xrootd/files/4277742/xrdcp.log)
[xrootd-gsi-dmsdca15Domain.log](https://github.com/xrootd/xrootd/files/4277744/xrootd-gsi-dmsdca15Domain.log)
[dmsdca21-Domain.log](https://github.com/xrootd/xrootd/files/4277745/dmsdca21-Domain.log)

**Comment by alrossi** [comment]
Hi Michal,

Sorry to bother again, but I'm an not sure this issue has been entirely solved.

I have built 5.0.0 both on my desktop, where I run the test client (the shell xrdcp500 you may have noticed in the command-lines), and on the xrootd server host.   The version I built was from the tip of master yesterday:
```
commit abb7b690009943e355cbe4b973d85839617af559
Author: Michal Simon <michal.simon@cern.ch>
Date:   Thu Mar 5 08:57:18 2020 +0100
```

It would seem that this fix takes care of the user client's interactions with the endpoints, but the TPC client exec'd by the server seems to clobber xroots with xroot when the source endpoint doesn't support TLS.

Here is an example.
```
DCACHE DOOR (dmsdca21:1094): GSI TLS OFF
DCACHE POOL (dmsdca15-1): TLS LOGIN STRICT
XROOTD (fndcatemp2:1094): GSI TLS SESSION STRICT
```

For the latter, the config file contains:

```
[root@fndcatemp2 ~]# grep tls /usr/share/xrootd/v5.0.0/etc/xrootd-1094.cf 
xrd.tls /etc/grid-security/xrootd/hostcert.pem /etc/grid-security/xrootd/hostkey.pem
xrd.tlsca noverify
xrootd.tls session tpc
```

My expectation would be that this attempt should fail when using xroots.   

The user client does not immediately fail, I suppose, because it does not try to do an open on the source (tpc lite).  However, I would expect the client on fndcatemp2 to fail.   In the server logs, however, we see:

```
200306 08:17:55 25885 XrootdXeq: arossi.21396:25@otfrid pub IP46 **TLSv1.2 login** as arossi
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 req=open dlen=283
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 open unmat /data/xrootdfs/testdata-Fri_Mar__6_08:17:54_CST_2020?oss.asize=0&tpc.dlg=dmsdca21.fnal.gov:1094&tpc.dlgon=1&tpc.key=0004599c539353945e625b93&tpc.lfn=/pnfs/fs/usr/test/arossi/volatile/tls-1/testdata&tpc.spr=**xroots**&tpc.src=dmsdca21.fnal.gov:1094&tpc.stage=copy&tpc.str=1&tpc.tpr=**xroots**
200306 08:17:55 25885 arossi.21396:25@otfrid ofs_open: 102-40600 fn=/data/xrootdfs/testdata-Fri_Mar__6_08:17:54_CST_2020
200306 08:17:55 25885 arossi.21396:25@otfrid oss_Open_ufs: fd=32767 flags=202 mode=40600 path=/data/xrootdfs/testdata-Fri_Mar__6_08:17:54_CST_2020
200306 08:17:55 25885 arossi.21396:25@otfrid ofs_fstat:  fn=/data/xrootdfs/testdata-Fri_Mar__6_08:17:54_CST_2020
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdResponse: 0100 sending 88 data bytes; status=0
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 req=query dlen=11
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 query config tpc
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 query config tpcdlg
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdResponse: 0100 sending 6 data bytes
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 req=sync dlen=0
200306 08:17:55 25885 arossi.21396:25@otfrid ofs_sync:  fn=/data/xrootdfs/testdata-Fri_Mar__6_08:17:54_CST_2020
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdProtocol: 0100 sync rc=0 fh=0
200306 08:17:55 25885 arossi.21396:25@otfrid XrootdResponse: 0100 sending OK
200306 08:17:55 29375 XrdXeq: TPC job thread started
TPC job 8: arossi.21396:25@otfrid copying **xroot**://dmsdca21.fnal.gov:1094//pnfs/fs/usr/test/arossi/volatile/tls-1/testdata to /data/xrootdfs/testdata-Fri_Mar__6_08:17:54_CST_2020
```

That is, the client logs in to the destination with TLS, but the destination launches the TPC job with xroot:  because the source endpoint does not support TLS.

As a sanity check, the dCache door (dmsdca21) log shows that the protocol only indicates a manager (flags=2):

```
06 Mar 2020 08:17:55 (xrootd-gsi-dmsdca21) [door:xrootd-gsi-dmsdca21@xrootd-gsi-dmsdca21Domain:AAWgMFHRVUg] doOnProtocolRequest, version 1280, expect 3, option 3.
06 Mar 2020 08:17:55 (xrootd-gsi-dmsdca21) [door:xrootd-gsi-dmsdca21@xrootd-gsi-dmsdca21Domain:AAWgMFHRVUg] [id: 0x508d47c4, L:/131.225.13.27:1094 - R:/131.225.240.93:33244] READ COMPLETE
06 Mar 2020 08:17:55 (xrootd-gsi-dmsdca21) [door:xrootd-gsi-dmsdca21@xrootd-gsi-dmsdca21Domain:AAWgMFHRVUg] Sending protocol message with server flags mode: OFF, flags: 2 (manager true, meta-server false, proxy-server false, server false, supervisor false, data-server false, load-balancer true, tlsData false, tlsGPF false, tlsLogin false, tlsSession 
false, tlsTPC false, goToTLS false, anonGPF false), signing policy (secLvl 0)(overrides {})(force false).
06 Mar 2020 08:17:55 (xrootd-gsi-dmsdca21) [door:xrootd-gsi-dmsdca21@xrootd-gsi-dmsdca21Domain:AAWgMFHRVUg] PROTOCOL RESPONSE TO CLIENT protocol-response[2][(secLvl 0)(overrides {})(force false)].
```

Are my expectations wrong here?  Note:  the server is configured 

> xrootd.tls session tpc

as well.   Between using xroots on the destination endpoint and the actual server-side tls, shouldn't this enforce TLS on the source connection?

Thanks again,

Al

**Comment by simonmichal** [comment]
@alrossi: could report this problem in a separate issue, the topic of tls encryption vs TPC seems to me more complex and probably also requires @abh attention

anyway after having a quick look, I can confirm that the client sets correctly the protocol in the url opaque info: `tpc.tpr=roots`

**Comment by alrossi** [comment]
yes, certainly.

Indeed, the user client indicates roots.  But the server forks the TPC client with xroot, it seems to me.

**Comment by abh3** [comment]
Hi Albert,

Thanks for catching that. That is a conundrum. I asssume you would say the 
correct behaviour is that if the client came in using TLS then the TPC job 
should use TLS as well. Note that we have no good way of carying over the 
fallback option (i.e. drop down to non-TLS if you have to). The correct 
approach will take a bit of mindful hinking here so that we don't box 
ourselves into a corner.

Andy
