### ISSUE TITLE
xrootd 5.0.0 server not failing against pre-TLS client when configured to

### ISSUE THREAD

**Issue by alrossi** [xrootd/xrootd#1146]
using xrdcp 4.10.0 with two xrootd 5.0.0 servers.

With 1094, which is configured:

```
xrd.tls /etc/grid-security/xrootd/hostcert.pem /etc/grid-security/xrootd/hostkey.pem
xrd.tlsca noverify
xrootd.tls session


ofs.tpc fcreds ?gsi =X509_USER_PROXY logok pgm /usr/share/xrootd/v5.0.0/bin/xrdcp --server
sec.protocol gsi -cert:/etc/grid-security/xrootd/hostcert.pem -key:/etc/grid-security/xrootd/hostkey.pem -dlgpxy:1 -exppxy:=creds
```

the client fails the TLS handshake but keeps retrying (attached log).

With 1096, configured:

```
xrd.tls /etc/grid-security/xrootd/hostcert.pem /etc/grid-security/xrootd/hostkey.pem
xrd.tlsca certdir /etc/grid-security/certificates log failure
xrootd.tls login

sec.protocol unix
```

the client fails with a login failed (from the TLS handshake).

In both cases, the "capable" directive is not given, so TLS should be enforced.

Client logs:

[1094.log](https://github.com/xrootd/xrootd/files/4281820/1094.log)
[1096.log](https://github.com/xrootd/xrootd/files/4281821/1096.log)

**Comment by abh3** [comment]
I am closing this as it is essentially a duplicate of #1152 and that was fixed by commit 1cc5904
 which should fix this issue as well.
