### ISSUE TITLE
Unreadable image in monitoring documentation

### ISSUE THREAD

**Issue by pmusset** [xrootd/xrootd#1153]
[This image](https://xrootd.slac.stanford.edu/doc/dev50/xrd_monitoring_files/image005.gif) present in [the monitoring documentation](https://xrootd.slac.stanford.edu/doc/dev50/xrd_monitoring.htm#_Toc26218298) is almost unreadable 

Not sure I opened the issue in the right repo as I didn't found where these files come from

**Comment by abh3** [comment]
Yeah, that's pretty bad. It looks just fine in the original. I'll see what 
I can do about that. It's actually much better rendered in the pdf 
document (though the link to the R5 pdf is broken). Thanks for bringing 
this to our attention.

**Comment by abh3** [comment]
This is now fixed in the R5 documentation. Please make sure to refresh the complete document to get a non-cached image.
