### ISSUE TITLE
Issues in the pfc documentation for xrootd5

### ISSUE THREAD

**Issue by pmusset** [xrootd/xrootd#1154]
- the library name seems to have changed for version 5 from libXrdFileCache.so to libXrdPfc.so
- in the documentation of the detailed monitoring for the "g" stream, it is said that the content is described in the pss documentation but it doesn't seems to be present.

I would like to do a PR for that but I didn't find where the documentation is in the repo

**Comment by abh3** [comment]
Yes, the library name has changed but we've made it backward compatible relative to the config file. That is if we see you specified libXrdFileCache.so we will change it to libXrdPfc.so so your current configuration file will continue to work. As for the file cache gStream documentation, it is still a work in progress.

**Comment by abh3** [comment]
The issue here was transitory and the documentation is correct at this point.
