### ISSUE TITLE
python::CopyProcess not interruptible

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1170]
Hi! I'm trying to to catch SIGINT in my client.utils.CopyProgressHandler without success so far..
I see [here](https://github.com/xrootd/xrootd/blob/master/bindings/python/libs/client/copyprocess.py#L50) that should_cancel applies per jobID but not further info...
My tryout look like [this](https://github.com/adriansev/jalien_py/blob/master/xjalienfs/alien.py#L1281) where i try to catch the SIGINT, enable a flag, and then [here](https://github.com/adriansev/jalien_py/blob/master/xjalienfs/alien.py#L1334) should return true for all jobIDs .. what i'm missing?   
Thank you!

**Comment by simonmichal** [comment]
@adriansev : I had a look into the issue, in Python `SIGINT` is by default translated into a `KeyboardInterrupt`, if you ignore this exception `SIGINT` will have no effect on you.

You can replace the default signal handler for `SIGINT` with `signal.signal()`, now the handler you provide will be called with two arguments, see: https://docs.python.org/3/library/signal.html#signal.signal

> The handler is called with two arguments: the signal number and the current stack frame (None or a frame object; for a description of frame objects, see the description in the type hierarchy or see the attribute descriptions in the inspect module).

I suppose that's why your script does not work as your handler expects 3 arguments:
` def catch(self, signum, frame):`

I tested it with the following code snippet:

```
import signal
from XRootD import client

interrupted=False
def handleSigInt( signalNumber, frame ):
  global interrupted
  interrupted=True
signal.signal( signal.SIGINT, handleSigInt )

class MyCopyProgressHandler(client.utils.CopyProgressHandler):
  def should_cancel(self, jobId):
    if interrupted : print 'cancelling due to SIGINT'
    return interrupted

process = client.CopyProcess()
process.add_job( source='/path/to/1GB',
                 target='root://hostname//dir/1GB',
                 force=True)

print process.prepare()
handler = MyCopyProgressHandler()
print process.run( handler )[1]
```

and it works reasonably well.

Could you have a look and let me know if we can close this issue?

**Comment by adriansev** [comment]
well, unfortunately does not work:
[here](https://github.com/adriansev/jalien_py/blob/sigint/xjalienfs/alien.py#L44) i have the handler
and [here](https://github.com/adriansev/jalien_py/blob/sigint/xjalienfs/alien.py#L1346) i have the should_cancel part .. the thing is that even for big files (not many small files) my should_cancel is not called at all! (at least update is called sometimes)   
so, even if i put sys.exit in sigint handler i get stuff like this (notice the order):   
```
XRootD CopyProcess is starting..
jobID: 1/1 >>> Start
^C^C^C^CjobID: 1/1 >>> ERRNO/CODE/XRDSTAT 0/0/0 >>> STATUS OK >>> SPEED 21.00 MiB/s MESSAGE: [SUCCESS]
Cought a SIGINT
Exit
XRootD CopyProcess ends.
```

without the exit function in handler look like this   
if i'm fast enough (notice the position of ^C)
```
XRootD CopyProcess is starting..
jobID: 1/1 >>> Start
^CjobID: 1/1 >>> ERRNO/CODE/XRDSTAT 3029/400/1 >>> STATUS ERROR >>> SPEED 0 B/s MESSAGE: [ERROR] Server responded with an error: [3029] Metalink: no more replicas to try. Last seen error: [ERROR] Error response: No such file or directory (source)

Cought a SIGINT
XRootD CopyProcess ends.
```
but if not    
```
XRootD CopyProcess is starting..
jobID: 1/1 >>> Start
^C^C^C^C^CjobID: 1/1 >>> ERRNO/CODE/XRDSTAT 0/0/0 >>> STATUS OK >>> SPEED 21.09 MiB/s MESSAGE: [SUCCESS]
Cought a SIGINT
XRootD CopyProcess ends.
```
so... what i'm missing?
Thank you!!
Adrian

**Comment by simonmichal** [comment]
@adriansev : good question, is the minimum example I posted in my previous msg working for you (for me it is)? Could you provide a minimum example where it is not working?

**Comment by adriansev** [comment]
@simonmichal well, the references that i posted are not a minimal example?
I mean the first reference is to the sigint handler which is the same as yours but with a print and the second reference is to the should_cancel implementation. did something seem different from what you told me? The thing is that i cannot do a minimum example as the xrootd copy for ALICE involves interrogating the central services for the replica authz envelopes and then creating the metafile that then is put as source link in jobqueue (link that can be amended if the file is in archive). But overall, it would seem to me that the actual copyprocess should somehow catch the sigint and stop all operations and clean up..
the command line xrdcp (while using the already generated metafile) stop immediately so this part is ok.

**Comment by adriansev** [comment]
@simonmichal so, things are too strange so this can be closed as unsolved. i actually derived CopyProcess to take it's thread id that i would sigterm when receiving sigint, see [jalien_py/compare/master...sigint](https://github.com/adriansev/jalien_py/compare/master...sigint)
but even then i get this situation:   
```
alien.py cp /alice/data/2018/LHC18a/000283620/TPC_Krypton/18000283620022.100/root_archive.zip file:
XRootD CopyProcess is starting..
139750979565248
jobID: 1/1 >>> Start
^C^CjobID: 1/1 >>> ERRNO/CODE/XRDSTAT 0/0/0 >>> STATUS OK >>> SPEED 23.00 MiB/s MESSAGE: [SUCCESS] 
doing xrd thread term
Terminated
```
the same happens with a list of small files, the CopyProcess thread is terminated **AFTER** the whole list of files was processed

it would seem that within python the copy jobs are immune to any kind of signal. strangely the xrdcp stop the copy on spot leaving the unfinished file on disk, so it would seem that it's a python problem. I will study further the problem on my own.
Thank you and sorry for taking your time.

**Comment by simonmichal** [comment]
@adriansev : any time, don't hesitate to ping me if you have some additional questions!
