### ISSUE TITLE
cksum :: delete target if check fails

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1173]
Hi! IMHO, if hash verification fails then the target should be deleted (given my understanding that the intent of check verification is that the target is valid). Maybe a flag can be used specially to only print a warning and not delete the target even if checksum fails.
Thank you!

**Comment by simonmichal** [comment]
@adriansev : I pushed today few commits that implement the functionality.

In `xrdcp` there is a new option `--rm-bad-cksum` that will make the client remove the target file if checksum verification fails (please not that this option enables POSC semantics).

You can also use the functionality from Python, e.g.:

```
from XRootD import client
process = client.CopyProcess()
process.add_job( source='/path/to/metalink.meta4',
                              target='/path/to',
                              force=True,
                              checksummode='end2end',
                              **checksumtype='auto'**,
                              rmBadCksum=True )
process.prepare()
process.run()
```
Please note the `checksum` type is set to `**auto**`, this is also a new functionality (that you asked for) that makes the client infer automatically the checksum type based on source/destination configuration, source file type (metalink, ZIP), and available checksum plug-ins.

Could you please give it a try?

**Comment by adriansev** [comment]
@simonmichal compilation have a problem
```
/home/adrian/software/xrootd/src/XrdCl/XrdClUtils.cc: In static member function ‘static std::vector<std::__cxx11::basic_string<char> > XrdCl::Utils::GetSupportedCheckSums(const XrdCl::URL&)’:
/home/adrian/software/xrootd/src/XrdCl/XrdClUtils.cc:636:21: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
  636 |     return std::move( ret );
      |            ~~~~~~~~~^~~~~~~
/home/adrian/software/xrootd/src/XrdCl/XrdClUtils.cc:636:21: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
```

**Comment by simonmichal** [comment]
@adriansev : what is the version of GCC you are using?

you need to turn of copy elision warning, e.g.:
https://github.com/xrootd/xrootd/blob/5c81143532c7ce61551811a6f8fbd28acd65b407/cmake/XRootDOSDefs.cmake#L67-L71

I though this was introduced only in 9+, but maybe it's also in younger compilers.

**Comment by adriansev** [comment]
commit 791617555 solved the issue
i'm on fedora31 with `gcc (GCC) 9.3.1 20200317 (Red Hat 9.3.1-1)`
i'm adapting my code right now, i'll be back with feedback

**Comment by adriansev** [comment]
@simonmichal  so, as i did not had an invalid checksum remote file, i tried the next best thing : missing checksum [xrd_log.txt](https://github.com/xrootd/xrootd/files/4447248/xrd_log.txt)
but it seems that is ignored... i would say that if the checksum checking was requested, if the hash entry is missing then just invalidate the checksumming process... even better, if the source is metalink, and the checksum is requested and metalink has no hash entry just ignore the copy process with a warning that checksum is requested but no hash info found about/in the source..
would this be all right?

**Comment by abh3** [comment]
Frankly, I think these hidden quirks of you asked for this but  I couldn't do it so I'll just assume you didn't need it is the wrong way to go. If you asked for a checksum and we couldn't do a checksum that should be considered a hard failure. Otherwise, you'll assume everything went fine (messages can be missed especially when there is no person to see them). So, if you get a hard failure and don't mind copying the file without check summing then you really should ask for it that way.

**Comment by adriansev** [comment]
erm, sorry, i did not get all what you said, but in principle i totally agree with you : if checksumming was requested, and the hash verification cannot be done, then skip the copy with a warning, if the copy was done and hash verification failed then just delete the target.

**Comment by abh3** [comment]
Sorry, for being so wordy. Your assessment is correct. I assume by "skip" 
the file is to terminate the whole xrdcp at that point with RC not equal 
to zero. Right?

**Comment by adriansev** [comment]
to skip the file would mean to terminate the copy of that file. my context is the python copyprocess queue where one have a list of copy jobs so from my point of view to "terminate the copy" would refer to the whole queue :)
so, i just chose my wording to mean that only the offending item from copy queue to be ignored :)

**Comment by xrootd-dev** [comment]
OK, so we are in agreement!

**Comment by simonmichal** [comment]
@adriansev & @abh3 : just to clarify, what should be the behaviour when user requested `--cksum auto` but `xrdcp` cannot infer the checksum type (e.g. there is no checksum in the metalink), should that particular copy job fail, or should `xrdcp` warn the user in the logs and go ahead with the copy anyway?
From what I gather, you guys prefer that the copy job fails, right?

**Comment by simonmichal** [comment]
Done in 18fb1aef66aae9882e6dff272be7b0594c024479.

**Comment by adriansev** [comment]
@simonmichal if the `--cksum` is requested and no information of the checksum is provided nor found then the copy should NOT be done and a warning to user should be issued (that cksum was requested but no hash/digest was provided/found)   
IMHO this would be in line with the intent of the user, that being that it really needs to check the validity of file.. so if this is not possible then no copy should be done

**Comment by simonmichal** [comment]
@adriansev : with the latest patch that's how it should work, could you give it a try?

**Comment by abh3** [comment]
Yes, I think we all came to the same conclusion, it should fail.

**Comment by adriansev** [comment]
@simonmichal it's perfect, works fantastic :)
Thanks a lot!!
