### ISSUE TITLE
Spurious XrdHttp authentication failures on manager node

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1177]
Using XRootD 4.11.3 and xrdhttpvoms 0.2.5 (not sure if this component is involved!), `gfal-copy` fails to authenticate ~50 % of the time with:
```
gfal-copy error: 13 (Permission denied) - TRANSFER  ERROR: Copy failed with mode streamed, with error: Authentication error, reached maximum number of attempts
```

Here's the test command:
```
for A in {1..9}; do gfal-copy file://$(pwd)/1M https://xrootd.physik.uni-bonn.de:1094//cephfs/grid/dteam/of_1M_${A}; done
```

I activated `http.trace all` and extracted the two cases. 

**Case A (working**
```
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp: received dlen: 16
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp: received dump: 22 03 01 02 00 01 00 01 -04 03 03 -19 -99 -18 -54 00 
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp: This does not look like http at pos 0
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp: This may look like https
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp: Protocol matched. https: 1
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  Process. lp:0x7f70200019a8 reqstate: 0
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  Setting host: [::ffff:188.184.98.75]
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  Entering SSL_accept...
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  SSL_accept returned :1
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  SSL_get_verify_result returned :0
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  Extracting auth info.
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  SSL_get_peer_certificate returned :0x7f701c00d5a0
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  Subject name is : '/C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth/CN=461443643'
200412 22:56:48 24968 ?:30@lxplus740.cern.ch sysXrdHttp:  Setting link name: 'eyermuth'
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  SSL_get_peer_certificate returned :0x7f701c00d5a0
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  SSL_get_verify_result returned :0
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  SSL_get_peer_cert_chain :0x7f701c000e20
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  VOMS data - user: '/C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth'
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  VOMS data - vorg: 'dteam'
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  VOMS data - fqan[0]:/dteam/Role=NULL/Capability=NULL
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  VOMS data - grps: '/dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL'
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  VOMS data - role: 'NULL'
200412 22:56:48 24968 eyermuth.0:30@lxplus740.cern.ch  VOMS proxy info - name: '/C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth' VO: dteam grps: '/dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL'
200412 22:56:48 24968 sysXrdHttp: getDataOneShot BuffAvailable: 1048576 maxread: 1048576
200412 22:56:48 24968 sysXrdHttp: getDataOneShot sslavail: 1048576
200412 22:56:48 24968 sysXrdHttp: read 190 of 1048576 bytes
200412 22:56:48 24968 sysXrdHttp:  rc:43 got hdr line: HEAD //cephfs/grid/dteam/of_1M_9 HTTP/1.1

200412 22:56:48 24968 sysXrdHttp:  Parsing first line: HEAD //cephfs/grid/dteam/of_1M_9 HTTP/1.1

200412 22:56:48 24968 sysXrdHttp:  rc:55 got hdr line: User-Agent: gfal2-util/1.5.3 gfal2/2.17.2 neon/0.0.29

200412 22:56:48 24968 sysXrdHttp:  rc:14 got hdr line: Keep-Alive: 

200412 22:56:48 24968 sysXrdHttp:  rc:24 got hdr line: Connection: Keep-Alive

200412 22:56:48 24968 sysXrdHttp:  rc:14 got hdr line: TE: trailers

200412 22:56:48 24968 sysXrdHttp:  rc:38 got hdr line: Host: xrootd.physik.uni-bonn.de:1094

200412 22:56:48 24968 sysXrdHttp:  rc:2 got hdr line: 

200412 22:56:48 24968 sysXrdHttp:  rc:2 detected header end.
200412 22:56:48 24968 XrootdBridge: /C=DE/O=.62:30@lxplus740.cern.ch login as /C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth
200412 22:56:48 24968 /C=DE/O=.62:30@lxplus740.cern.ch sysXrdHttp:  Process. lp:0x7f70200019a8 reqstate: 0
200412 22:56:48 24968 /C=DE/O=.62:30@lxplus740.cern.ch sysXrdHttp: Process is exiting rc:0
200412 22:56:48 24968 acc_Audit: http grant  /C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth@[::ffff:188.184.98.75] stat /cephfs/grid/dteam/of_1M_9
```

**Case B (not working)**
```
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp: received dlen: 16
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp: received dump: 22 03 01 14 -98 01 00 14 -102 03 03 -79 08 -12 06 00 
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp: This does not look like http at pos 0
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp: This may look like https
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp: Protocol matched. https: 1
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  Process. lp:0x7f7020000ee8 reqstate: 0
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  Setting host: [::ffff:188.184.98.75]
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  Entering SSL_accept...
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  SSL_accept returned :1
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  SSL_get_verify_result returned :0
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  Extracting auth info.
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  SSL_get_peer_certificate returned :0x7f70100015d0
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  Subject name is : '/C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth/CN=461443643'
200412 22:56:48 24985 ?:26@lxplus740.cern.ch sysXrdHttp:  Setting link name: 'eyermuth'
200412 22:56:48 24985 eyermuth.0:26@lxplus740.cern.ch  SSL_get_peer_certificate returned :0x7f70100015d0
200412 22:56:48 24985 eyermuth.0:26@lxplus740.cern.ch  SSL_get_verify_result returned :0
200412 22:56:48 24985 eyermuth.0:26@lxplus740.cern.ch  SSL_get_peer_cert_chain :0
200412 22:56:48 24985 sysXrdHttp: getDataOneShot BuffAvailable: 1048576 maxread: 1048576
200412 22:56:48 24985 sysXrdHttp: getDataOneShot sslavail: 1048576
200412 22:56:48 24985 sysXrdHttp: read 187 of 1048576 bytes
200412 22:56:48 24985 sysXrdHttp:  rc:43 got hdr line: HEAD //cephfs/grid/dteam/of_1M_9 HTTP/1.1

200412 22:56:48 24985 sysXrdHttp:  Parsing first line: HEAD //cephfs/grid/dteam/of_1M_9 HTTP/1.1

200412 22:56:48 24985 sysXrdHttp:  rc:55 got hdr line: User-Agent: gfal2-util/1.5.3 gfal2/2.17.2 neon/0.0.29

200412 22:56:48 24985 sysXrdHttp:  rc:14 got hdr line: TE: trailers

200412 22:56:48 24985 sysXrdHttp:  rc:38 got hdr line: Host: xrootd.physik.uni-bonn.de:1094

200412 22:56:48 24985 sysXrdHttp:  rc:35 got hdr line: Accept: application/metalink4+xml

200412 22:56:48 24985 sysXrdHttp:  rc:2 got hdr line: 

200412 22:56:48 24985 sysXrdHttp:  rc:2 detected header end.
200412 22:56:48 24985 XrootdBridge: Oliver F.63:26@lxplus740.cern.ch login as Oliver Freyermuth
200412 22:56:48 24985 Oliver F.63:26@lxplus740.cern.ch sysXrdHttp:  Process. lp:0x7f7020000ee8 reqstate: 0
200412 22:56:48 24985 Oliver F.63:26@lxplus740.cern.ch sysXrdHttp: Process is exiting rc:0
200412 22:56:48 24985 acc_Audit: http deny  Oliver Freyermuth@[::ffff:188.184.98.75] stat /cephfs/grid/dteam/of_1M_9
```

The notable difference is that `SSL_get_peer_cert_chain :0` did not get a chain. 

Here's our config on the redirector:
```
acc.audit deny grant
acc.authdb /etc/xrootd/auth_file-grid
acc.authrefresh 60
all.export /cephfs/grid/dteam r/w nostage
all.manager xrootd.physik.uni-bonn.de:1213
all.role server
all.role manager if xrootd.physik.uni-bonn.de
all.sitename UNI-BONN
cms.allow host xrootd.physik.uni-bonn.de
cms.allow host xrootd*.physik.uni-bonn.de
cms.dfs limit 0 lookup distrib mdhold 0 redirect immed retries 2
cms.perf int 60s pgm /usr/share/xrootd/utils/cms_monPerf 30
cms.sched cpu 10 io 60 mem 10 pag 10 runq 10 space 0 fuzz 20 gshr 100 affinity none refreset 3600
cms.trace all -debug
http.cadir /etc/grid-security/certificates
http.cert /etc/grid-security/hostcert.pem
http.exthandler xrdmacaroons libXrdMacaroons.so
http.exthandler xrdtpc libXrdHttpTPC.so
http.header2cgi Authorization authz
http.secretkey REMOVED_FROM_HERE
http.key /etc/grid-security/hostkey.pem
http.secxtractor /usr/lib64/libXrdHttpVOMS.so
if exec xrootd
xrd.protocol XrdHttp /usr/lib64/libXrdHttp.so
fi
if xrootd.physik.uni-bonn.de
else
http.selfhttps2http no
fi
if xrootd.physik.uni-bonn.de
http.desthttps yes
fi
macaroons.secretkey /etc/xrootd/macaroon-secret
ofs.authlib libXrdMacaroons.so
ofs.authorize 1
ofs.notify mkdir create |/usr/local/bin/xrootd-eventstream-permission-fix
ofs.tpc fcreds ?gsi =X509_USER_PROXY autorm ttl 180 1800 pgm /usr/local/bin/xrdcp-voms --server
sec.protocol /usr/lib64 gsi -dlgpxy:1 -exppxy:=creds -ca:1 -crl:3 -gridmap:/dev/null -cert:/etc/grid-security/hostcert.pem -key:/etc/grid-security/hostkey.pem -certdir:/etc/grid-security/certificates -vomsfun:/usr/lib64/libXrdSecgsiVOMS.so -vomsfunparms:certfmt=raw|vos=atlas,ops,dteam,wlcg|grps=/atlas,/ops,/dteam,/wlcg
xrd.port 1094
xrd.timeout hail 30 idle 0 kill 10 read 30
xrd.trace conn
xrootd.chksum adler32 crc32 md5
xrootd.seclib /usr/lib64/libXrdSec.so
```
(only some exports and the secretkey were removed).

**Comment by olifre** [comment]
@vokac suggested this might be a consequence of session reuse, and @bbockelm pointed out that XrdLCMAPS explicitly disables the session cache:
https://github.com/opensciencegrid/xrootd-lcmaps/blob/95161fd85b7f6e603c569b05ca8a7dd127678965/src/XrdHttpLcmaps.cc#L361-L365

Pinging @ffurano since that implies a bug in `libXrdHttpVOMS.so` could be the cause (does it have a separate bugtracker / repo, or is it fine to report these here?).

**Comment by wyang007** [comment]
Does the XrdLCMAPS have a dependence on Globus? If so we need a discussion within the WLCG-DOMA and OSG on how we will move forward.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by olifre** [comment]
@wyang007 Looks like it has:
https://github.com/opensciencegrid/xrootd-lcmaps/blob/95161fd85b7f6e603c569b05ca8a7dd127678965/CMakeLists.txt#L23

Additionally, I think it also depends on LCMAPS itself.  If mapping is not needed, but only VOMS attributes are used for authn/z, all of that is unused, which is why we went for the lightweight solution with `XrdHttpVOMS` and `vomsxrd` which does VOMS attribute mapping only and leaves authentication to XRootD.

**Comment by bbockelm** [comment]
Yes (and I suspect that its Globus's handling of CRL verification that is saving XrdLCMAPS from #750) - but that's a bit orthogonal given that `libXrdHttpVOMS.so` has a dependency on GSI as well via VOMS.

If it helps conserve effort, we can probably factor out completely the `LCMAPS` piece and also build a LCMAPS-free variant of the software to avoid the LCMAPS dependency chain.

**Comment by olifre** [comment]
@bbockelm From my point of view, this sounds like a great idea! :+1:

**Comment by xrootd-dev** [comment]
I just realized this: Is this really a problem with libXrdHttpVOMS, or libXrdHttp?
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by bbockelm** [comment]
@wyang007 - you could reasonably argue that this and #750 are really issues with `XrdHttp` that are bypassed by `XrdLCMAPS`.

- This ticket is caused because the session cache is not disabled in `XrdHttp`.  `XrdLCMAPS` does this when it is loaded.
- #750 is caused because the `SSL_CTX` object is loaded at initialization by `XrdHttp` and a corresponding `X509_STORE` is never refreshed.  The `X509_STORE` pointer is passed from `XrdHttp` to the VOMS library and things blow up when VOMS attempts the CRL check (note the error message from #750 is from `libvomsapi`, not OpenSSL).  `XrdLCMAPS` isn't affected because it doesn't use `XrdHttp`'s `X509_STORE` object periodically reloads its `X509_STORE` objects every 10 minutes (it also gets a bit clever in that is hashes the activity over 63 copies of the cert store so multiple threads don't have to share a single global mutex).

**Comment by wyang007** [comment]
@bbockelm is this issue also related to the issue reported here? https://opensciencegrid.atlassian.net/browse/SOFTWARE-3454

I was about to submit another ticket on this but thought maybe they are related.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by bbockelm** [comment]
@wyang007 - we can determine that from the `libdavix` version - the underlying bug was fixed in `0.7.1`.  @olifre - can you check your setup?  I seem to recall it might have also generated a distinct error message server-side.

**Comment by xrootd-dev** [comment]
Hi,

 XrdHTTPVoms is in gitlab:

https://gitlab.cern.ch/lcgdm/xrdhttpvoms

 And yes, I wrote it. I am not sure that the issue comes from that,
I'd investigate the session reuse and the CRLs in XrdHttpProtocol,
and sincerely the fact that with plain davix-put the problem cannot be
reproduced is pretty fishy to me.
 Also Davix itself had quite a varied story with its client side
session reuse and redirection cache, so where to look is not obvious to
me yet.

 I would also like to understand about the Xrootd R5 plans for
using the same SSL subsystem, as that will propagate
to XrdHttp, making useless any mod that we may make today...


 Today it was a holiday, this week I can have a look.

Cheers
Fabrizio




Il 13/04/20 18:09, Oliver Freyermuth ha scritto:

**Comment by xrootd-dev** [comment]
Hi,

 IMO disabling the session cache is not a good idea, as it will have
destructive consequences on the performance. Better to fix it if it's
broken.

Fabrizio



Il 13/04/20 22:25, Brian P Bockelman ha scritto:

**Comment by olifre** [comment]
>  @olifre - can you check your setup? I seem to recall it might have also generated a distinct error message server-side.

@bbockelm I'm getting confused a bit which issue you are referring to. For the one at hand, the logs are contained in the first post, i.e. there was no distinctive server-side error message. Or is this about the `KEEP_ALIVE` topic? I have not yet had a shot at reproducing that...

**Comment by abh3** [comment]
Not necessarily useless, indeed we would like to use the same ssl 
framework everywhere but if this is an easy fix then it's likely to make 
things better before the realignment occurs. Plus, we'll get a better 
understanding of what needs to happen in the common framework.

**Comment by bbockelm** [comment]
>  IMO disabling the session cache is not a good idea, as it will have destructive consequences on the performance. Better to fix it if it's broken.

To be clear, this is 100% broken and has never worked.  So there's not 'destructive' consequences on performance that has never been there.  It'd be a major new feature to add this.

> @bbockelm I'm getting confused a bit which issue you are referring to. For the one at hand, the logs are contained in the first post, i.e. there was no distinctive server-side error message

I was responding to the old OSG ticket that Wei had found.  The issue in the ticket - also solved by `KEEP_ALIVE=false` - was fixed in davix 0.7.1.

**Comment by xrootd-dev** [comment]
Hi Brian,

Il 14/04/20 04:19, Brian P Bockelman ha scritto:
>     IMO disabling the session cache is not a good idea, as it will have
>     destructive consequences on the performance. Better to fix it if
>     it's broken.
> 
> To be clear, this is 100% broken and has never worked. So there's not
> 'destructive' consequences on performance that has never been there.
> It'd be a major new feature to add this.
> 

 this makes me curious... What makes you say that the openssl
session cache is broken? I have never seen it as broken so far.

Thanks
Fabrizio

**Comment by ffurano** [comment]
Hi,

 just to add something, this issue IMO could be related to the CRLs, and
I never saw it in my testbed (which is up since years, with no CRLs)

 I would make a test removing by hand the CRLs in all the servers
of the cluster that happened to give this message. If this is it
then it may not be too problematic to fix.


Fabrizio





Il 13/04/20 16:08, Oliver Freyermuth ha scritto:
> |200412 22:56:48 24985 eyermuth.0:26@lxplus740.cern.ch
> SSL_get_peer_certificate returned :0x7f70100015d0 200412 22:56:48 24985
> eyermuth.0:26@lxplus740.cern.ch SSL_get_verify_result returned :0 200412
> 22:56:48 24985 eyermuth.0:26@lxplus740.cern.ch SSL_get_peer_cert_chain :0|

**Comment by olifre** [comment]
> I was responding to the old OSG ticket that Wei had found. The issue in the ticket - also solved by `KEEP_ALIVE=false` - was fixed in davix 0.7.1.

I am unable to reproduce that old issue even with davix 0.6.8 against our endpoint.

**Comment by olifre** [comment]
> I would make a test removing by hand the CRLs in all the servers of the cluster that happened to give this message. If this is it then it may not be too problematic to fix.

We only have a production setup here, so we sadly can not perform the test. Having a separate test setup got higher priority, though...

**Comment by olifre** [comment]
> I just realized this: Is this really a problem with libXrdHttpVOMS, or libXrdHttp?

I think this is the main point here. While the discussion also taking via mail is definitely needed and in the long-term, joining all the efforts is surely the way to go, all issues currently discussed here are likely issues in `libXrdHttp` and just worked around / "hidden" in the `XrdLCMAPS` plugin (as @bbockelm pointed out in https://github.com/xrootd/xrootd/issues/1177#issuecomment-613080475 ). So the bug fixing in XRootD should not be hindered by this ;-).

**Comment by abh3** [comment]
Eh? I don't immediately see why this is the case. What is the reasoning?

**Comment by olifre** [comment]
@abh3 Quoting @bbockelm :

> * This ticket is caused because the session cache is not disabled in `XrdHttp`.  `XrdLCMAPS` does this when it is loaded.
> 
> * #750 is caused because the `SSL_CTX` object is loaded at initialization by `XrdHttp` and a corresponding `X509_STORE` is never refreshed.  The `X509_STORE` pointer is passed from `XrdHttp` to the VOMS library and things blow up when VOMS attempts the CRL check (note the error message from #750 is from `libvomsapi`, not OpenSSL).  `XrdLCMAPS` isn't affected because it doesn't use `XrdHttp`'s `X509_STORE` object periodically reloads its `X509_STORE` objects every 10 minutes (it also gets a bit clever in that is hashes the activity over 63 copies of the cert store so multiple threads don't have to share a single global mutex).

On the first point, I think the main thing is that `XrdHTTP` should probably ensure the session handling works as expected. Whether that is "solved" by disabling it, or by fixing it in some way as @ffurano proposed, the plugins should be able to access the SSL chain for a client with a verified connection. Modifying `SSL_CTX` at the plugin level (as `XrdLCMAPS` does it) will of course also fix things, but does not seem right.

**Comment by esindril** [comment]
This **is** an XrdHttp issue. I already mentioned this in #750. In our setup this gets triggered in the SSL_accept part:
`https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpProtocol.cc#L662`

And some logs concerning this:

```
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp: received dlen: 16
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp: received dump: 22 03 01 02 00 01 00 01 -04 03 03 51 -41 41 40 00
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp: This does not look like http at pos 0
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp: This may look like https
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp: Protocol matched. https: 1
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp:  Process. lp:0x7ff7a5bc6818 reqstate: 0
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp:  Setting host: [2001:1458:201:e3::100:4d1]
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp:  Entering SSL_accept...
200331 14:32:18 11179 ?:475@fts3devel05 sysXrdHttp:  SSL_accept returned :-1
140701696083712:error:80066405:lib(128):func(102):reason(1029):sslutils.c:1915:
140701696083712:error:80066411:lib(128):func(102):reason(1041):sslutils.c:2110:: CRL has expired [subject=/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=tbeerman/CN=722011/CN=Thomas Beermann,issuer=/DC=ch/DC=cern/CN=CERN Grid Certification Authority]
140701696083712:error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify failed:s3_srvr.c:3327:
200331 14:32:18 11179 sysXrdHttp:  Cleanup
200331 14:32:18 11179 sysXrdHttp:  Reset
200331 14:32:18 11179 sysXrdHttp:  XrdHttpReq request ended.
```

Hope this helps,
Elvin

**Comment by abh3** [comment]
OK, how about pointing to the offending part? There a lot of people that 
are not necessarily convinced.

**Comment by bbockelm** [comment]
@abh3 -

The offending part is that the session cache is not disabled; that is, `XrdHttp` is missing the following lines:

https://github.com/opensciencegrid/xrootd-lcmaps/blob/master/src/XrdHttpLcmaps.cc#L361-L365

If the session cache is used (it's use is not typically triggered by davix but it is by gfal) to start a new SSL connection, then the client certificate chain is not associated to the session upon reuse.  OpenSSL does *not* cache the certificate chain information for you in the cache (you'd have to keep in memory the certificate chain for every connection that had been made over SSL) - that's left as an exercise to the user.

Because the session cache is used and the cert chain is not available to OpenSSL, `XrdHttp` ends up with this debug message when it asks for the peer chain:

```
200412 22:56:48 24985 eyermuth.0:26@lxplus740.cern.ch  SSL_get_peer_cert_chain :0
```

That is, the peer chain provided by OpenSSL is a `nullptr` and the client cannot be mapped by the security extractor module.  Accordingly, the username is set to random user-controlled gobbledy-gook:

```
200412 22:56:48 24985 acc_Audit: http deny  Oliver Freyermuth@[::ffff:188.184.98.75] stat /cephfs/grid/dteam/of_1M_9
```

instead of the DN in Oliver's case:

```
200412 22:56:48 24968 acc_Audit: http grant  /C=DE/O=GermanGrid/OU=UniBonn/CN=Oliver Freyermuth@[::ffff:188.184.98.75] stat /cephfs/grid/dteam/of_1M_9
```

Brian

(@esindril - while you're also correct about CRLs, I'm not addressing it here because it really belongs to #750...)

**Comment by olifre** [comment]
We're right now upgrading our production instance to 4.12.1. 
I re-ran the test against it:
```
$ for A in {1..9}; do gfal-copy file:///somewhere/1M https://xrootd.physik.uni-bonn.de:1094//cephfs/grid/dteam/of_1M_${A}; done   
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
Copying file:///somewhere/1M   [DONE]  after 0s                                                                                                                       
Copying file:///somewhere/1M   [DONE]  after 0s
```

So this issue is fixed and I'm closing it, thanks @bbockelm for https://github.com/xrootd/xrootd/commit/14a693077f201e4b6a30973456008eaa23c53e2d ! :+1:
