### ISSUE TITLE
request to drop the '--path' option on the xrootd client (xrdcp)

### ISSUE THREAD

**Issue by alrossi** [xrootd/xrootd#1184]
Since the server is caught in a bind having to support automatic creation of missing directories for backward compatibility, this option on the client is now meaningless.   

Would it be possible to simply drop it, for the sake of consistency?

Thanks,

Al

**Comment by alrossi** [comment]
Since the server is caught in a bind having to support automatic creation of missing directories for backward compatibility, this option on the client is now meaningless.   

Would it be possible to simply drop it, for the sake of consistency?

Thanks,

Al

**Comment by costing** [comment]
That is actually not ok for ALICE. We have to pass `--path` on dCache SEs, that do not create the intermediate directories if not indicated to do so. So even if for Xrootd servers this is not important, we need it in the client. Could it be brought back?

**Comment by alrossi** [comment]
dCache xroot creates all intermediate paths since

https://rb.dcache.org/r/12326/
master commit 229210209cd99376a62b6452731e3129aae4c369

This went into 6.2, and was backported to
6.1.3
6.0.14
5.2.20

thus dCache should be behaving exactly like the xrootd server since then.  Please let us know if this is not the case.

**Comment by costing** [comment]
Thanks a lot @alrossi  for your quick answer!

All our dCache instances are newer than the indicated tags so indeed it should be fine. In that case I can drop `--path` from the commands and see what happens. Nothing better than testing in production :)
