### ISSUE TITLE
gfal-copy fails due to a checksum issue on Lustre 2.13 with davs protocol

### ISSUE THREAD

**Issue by bockjoo** [xrootd/xrootd#1185]
I am seeing somewhat frequent local stageout error with

"davs protocol has this error from time to time: gfal-copy error: 5 (Input/output error) - DESTINATION CHECKSUM HTTP 500 : Unexpected server error: 500"

We use the davs protocol for the local stageout.
We have recently upgraded our Lustre to 2.13.
Sometimes, if I set the parent directories permission to group-writable, the error appears, but 
it is not always so. I am seeing the same failure with all group-writable parent directories, too.

**Comment by bockjoo** [comment]
On the server side, the error looks like:
200424 13:41:03 7646 ofs_FAttr: Unable to set attr XrdCks.adler32 from /cmsuf/data/store/temp/user/pellicci.061cd60b8606012074a29dd9c80afc645d40c303/LFVAnalysis_HEMu_2016_8028V1/LFVAnalysis_HEMu_GENSIM_2016_8028V1/200424_141250/0005/ZEMuAnalysis_pythia8_GENSIM_2016_5162.root; permission denied"

**Comment by xrootd-dev** [comment]
Hi Bockjoo,

You my want to review the oustanding bugs in Lustre 2.13 (there are quite 
a few) to see is any of them match what you are seeing...

https://jira.whamcloud.com/browse/LU-12564?filter=15418

Andy

**Comment by xrootd-dev** [comment]
This may be due to a no longer compatible SELINUX setting. If the file is 
changed to R/O then setting extended attributes will fail with "permission 
denied" this is considered, apparently, a bug in Lustre 2.13. I don't know 
if it's the case here. As for SELinux setting check...

https://github.com/DDNStorage/lustre_manual_markdown/blob/master/03.18-Managing%20Security%20in%20a%20Lustre%20File%20System.md

**Comment by bockjoo** [comment]
Thanks for that, Andy!
But I tracked down a server that had the mounted Lustre that did not function and
that failed gfal-copy with the error "CHECKSUM HTTP 500 : Unexpected server error: 500".
But this error:
200424 13:41:03 7646 ofs_FAttr: Unable to set attr XrdCks.adler32 from /cmsuf/data/store/temp/user/pellicci.061cd60b8606012074a29dd9c80afc645d40c303/LFVAnalysis_HEMu_2016_8028V1/LFVAnalysis_HEMu_GENSIM_2016_8028V1/200424_141250/0005/ZEMuAnalysis_pythia8_GENSIM_2016_5162.root; permission denied"
is always there, though the gfal-copy -K ADLER32 actually sets the adler32 sum correctly.

**Comment by xrootd-dev** [comment]
Hi Bockjoo,

Well, that definitely sounds like a Lustre bug. It should not be returning 
an error if it actually does what you want it to do, right?

Andy

**Comment by bockjoo** [comment]
Hi Andy,
Probably, it is. But I am no Lustre expert. I will work with my research computing on that.
Thanks,
Bockjoo

**Comment by abh3** [comment]
I think we resolved this as a Lustre 2.13 problem.
