### ISSUE TITLE
XRootD 5.0-rc2: Handshake fails with TLS turned on, but no client verification

### ISSUE THREAD

**Issue by djw8605** [xrootd/xrootd#1188]
I am testing the xrootd 5.0-rc2 and having issues when turning TLS on.  I have am using a cache -> origin architecture.

On the cache, I have no special configuration.  It is OSG's build: xrootd-server-5.0.0-0.rc2.2.osgup.el7.x86_64.  The cache has the proxy line removed, so it cannot use a proxy to force other authentication methods.

On the origin, I have the TLS lines:
```
xrd.tls /etc/grid-security/xrd/xrdcert.pem /etc/grid-security/xrd/xrdkey.pem
xrd.tlsca noverify
xrd.trace all
xrd.trace tls
xrd.protocol tls xrootd:1095 *
```

The origin also has `gsi` enabled.  Same version of xrootd as the cache.

### Cache Log
```
200501 00:14:32 13399 XrdInet: Accepted connection from 161@natnode
200501 00:14:32 13399 XrdProtLoad: matched port 8443 protocol http
200501 00:14:32 13399 anon:161@natnode XrdPoll: FD 161 attached to poller 0; num=1
200501 00:14:32 13399 XrootdBridge: unknown.1:161@natnode login as nobody
200501 00:14:32 13399 unknown.1:161@natnode ofs_stat:  fn=/hcc/PROTECTED/dweitzel-test/blah2.txt
[2020-05-01 00:14:33.148553 +0000][Error  ][XRootDTransport   ] [p0@origin:1095.0] No protocols left to try
[2020-05-01 00:14:33.148609 +0000][Error  ][AsyncSock         ] [p0@origin:1095.0] Socket error while handshaking: [FATAL] Auth failed
[2020-05-01 00:14:33.148660 +0000][Error  ][PostMaster        ] [p0@origin:1095] elapsed = 0, pConnectionWindow = 120 seconds.
[2020-05-01 00:14:33.148682 +0000][Error  ][PostMaster        ] [p0@origin:1095] Unable to recover: [FATAL] Auth failed.
[2020-05-01 00:14:33.148689 +0000][Error  ][XRootD            ] [p0@origin:1095] Impossible to send message kXR_stat (path: /hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20biglongbearertoken&oss.lcl=1&pss.tid=http, flags: none). Trying to recover.
200501 00:14:33 13399 ofs_stat: unknown.1:161@natnode Unable to locate /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200501 00:14:33 13399 unknown.1:161@natnode XrootdResponse: sending err 3010: Unable to locate /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200501 00:14:33 13399 unknown.1:161@natnode ofs_open: 0-600 fn=/hcc/PROTECTED/dweitzel-test/blah2.txt
[2020-05-01 00:14:33.174253 +0000][Error  ][XRootDTransport   ] [origin:1095.0] No protocols left to try
[2020-05-01 00:14:33.174280 +0000][Error  ][AsyncSock         ] origin:1095.0] Socket error while handshaking: [FATAL] Auth failed
[2020-05-01 00:14:33.174323 +0000][Error  ][PostMaster        ] [origin:1095] elapsed = 0, pConnectionWindow = 120 seconds.
[2020-05-01 00:14:33.174334 +0000][Error  ][PostMaster        ] [origin:1095] Unable to recover: [FATAL] Auth failed.
[2020-05-01 00:14:33.174339 +0000][Error  ][XRootD            ] [origin:1095] Impossible to send message kXR_open (file: /hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20biglongbearertoken&oss.lcl=1&pss.tid=http, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
200501 00:14:33 13399 Posix_Open: [FATAL] Auth failed open root://origin:1095//hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20biglongbearertoken&pss.tid=http&oss.lcl=1
200501 00:14:33 13399 ofs_open: unknown.1:161@natnode Unable to open /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200501 00:14:33 13399 unknown.1:161@natnode XrootdResponse: sending err 3010: Unable to open /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200501 00:14:33 13399 unknown.1:161@natnode ofs_close: use=0 fn=dummy
200501 00:14:33 13399 XrootdXeq: unknown.1:161@natnode disc 0:00:01 (send failure)
200501 00:14:33 13399 unknown.1:161@natnode XrdPoll: FD 161 detached from poller 0; num=0
```

### Origin Log
```
200501 00:14:33 20363 XrdInet: Accepted connection from 141@cachenode
200501 00:14:33 20363 XrdProtLoad: matched port 1095 protocol xroot
200501 00:14:33 20363 anon:141@cachenode XrdPoll: FD 141 attached to poller 0; num=1
200501 00:14:33 20363 XrootdXeq: p0.13393:141@cachenode disc 0:00:00
200501 00:14:33 20363 p0.13393:141@cachenode XrdPoll: FD 141 detached from poller 0; num=0
200501 00:14:33 20364 XrdInet: Accepted connection from 143@cachenode
200501 00:14:33 20993 XrdSched: running main accept inq=0
200501 00:14:33 20364 XrdProtLoad: matched port 1095 protocol xroot
200501 00:14:33 20364 anon:143@cachenode XrdPoll: FD 143 attached to poller 0; num=1
200501 00:14:33 20364 XrootdXeq: xrootd.13393:143@cachenode disc 0:00:00
200501 00:14:33 20364 xrootd.13393:143@cachenode XrdPoll: FD 143 detached from poller 0; num=0
```

I'm not sure if the TLS is conflicting with gsi?  What further debugging information would be useful?

**Comment by abh3** [comment]
Hi Derek,

You didn't show the commands you used to do all of this so it's 
mysterious. If you didn't use "xroots://" to the port that is designated 
as a TLS-only port then it wouldn't work. Otherwise, it looks OK. The best 
idea is to first try xrdfs or xrdcp directly to the origin server to make 
sure it's working fine. Then making sure that the proxy is setup in the 
same way.

Andy

**Comment by xrootd-dev** [comment]
Ah, but before you do too much work here we found a flaw in the 
client-side TLS stack that we are fixing. I think RC3 is around the 
corner!

Andy

**Comment by djw8605** [comment]
Hi, sorry for not including the commands.  This was a cache -> origin communication.  The cache is set to directly access the origin with the line:
```
pss.origin origin:1095
```

I think I misunderstood your email from before.
> Please note that if he redirector sends you off to a server that needs TLS then you will automatically get TLS no matter what.

I thought that meant that the xroots wasn't required to be explicit anywhere, and the cache would use the appropriate protocol.

Btw, I can't explicitly put a roots or xroots protocol on the pss.origin line because they are commented out in the PSS config:
https://github.com/xrootd/xrootd/blob/master/src/XrdPss/XrdPssConfig.cc#L487

**Comment by simonmichal** [comment]
Hi Derek,

Please try replacing `xrd.protocol tls xrootd:1095 *` with `xrootd.tls all`.

The former tells the server to accept only xroots/roots connections on port 1095. The later, on the other hand, configures the server to tell the client to upgrade all types of connections to TLS.

Cheers,
Michal

**Comment by abh3** [comment]
Hi Derek,

That correct but you made in non-tional by specifying a port that always 
had TLS enabled. There is no negotiation possible under that circumstance 
and the client needs to start with TLS from the get-go. Had the server 
been configured to do "soft" TLS, that is require it only when needed, 
then you could use xroot and it would upgrade to TLS as needed.

So, why did you decide to use a non-negotiable port?

Andy

**Comment by djw8605** [comment]
Hi,

The `xrootd.tls all` seems to have improved the situation.  But... now getting auth error, which could certainly be my fault.  Unless it looks like the client error you saw.

On the origin (receiving the connection):
```
200504 20:16:18 9176 XrdInet: Accepted connection from 113@cache
200504 20:16:18 9176 XrdProtLoad: matched port 1095 protocol xroot
200504 20:16:18 9176 anon:113@cache XrdPoll: FD 113 attached to poller 0; num=1
200504 20:16:18 9176 XrootdXeq: anon:113@cache connection upgraded to TLSv1.2
200504 20:16:18 9176 XrdPoll: Poller 0 enabled p0.13393:113@cache
200504 20:16:18 9177 p0.13393:113@cache XrdPoll: Link 113 terminating: hangup
200504 20:16:18 9237 XrdSched: running p0.13393:113@cache inq=0
200504 20:16:18 9237 XrootdXeq: p0.13393:113@cache disc 0:00:00
200504 20:16:18 9237 p0.13393:113@cache XrdPoll: FD 113 detached from poller 0; num=0
200504 20:16:18 9175 XrdInet: Accepted connection from 115@cache
200504 20:16:18 9176 XrdSched: running main accept inq=0
200504 20:16:18 9175 XrdProtLoad: matched port 1095 protocol xroot
200504 20:16:18 9175 anon:115@cache XrdPoll: FD 115 attached to poller 0; num=1
200504 20:16:18 9175 XrootdXeq: anon:115@cache connection upgraded to TLSv1.2
200504 20:16:18 9175 XrdPoll: Poller 0 enabled xrootd.13393:115@cache
200504 20:16:18 9177 xrootd.13393:115@cache XrdPoll: Link 115 terminating: hangup
200504 20:16:18 9237 XrdSched: running xrootd.13393:115@cache inq=0
200504 20:16:18 9237 XrootdXeq: xrootd.13393:115@cache disc 0:00:00
200504 20:16:18 9237 xrootd.13393:115@cache XrdPoll: FD 115 detached from poller 0; num=0
```

On the cache server:
```
200504 20:16:18 16921 anon:196@client XrdPoll: FD 196 attached to poller 0; num=1
200504 20:16:18 16921 XrootdBridge: unknown.2732:196@client login as nobody
200504 20:16:18 16921 unknown.2732:196@client ofs_stat:  fn=/hcc/PROTECTED/dweitzel-test/blah2.txt
200504 20:16:18 16921 scitokens_Reconfig: Parsing configuration file: /run/stash-cache-auth/scitokens.conf
200504 20:16:18 13421 XrdSched: running monitor fstat inq=0
200504 20:16:18 13421 XrdSched: scheduling monitor fstat in 60 seconds
[2020-05-04 20:16:18.802790 +0000][Error  ][XRootDTransport   ] [p0@origin:1095.0] No protocols left to try
[2020-05-04 20:16:18.802832 +0000][Error  ][AsyncSock         ] [p0@origin:1095.0] Socket error while handshaking: [FATAL] Auth failed
[2020-05-04 20:16:18.802871 +0000][Error  ][PostMaster        ] [p0@origin:1095] elapsed = 0, pConnectionWindow = 120 seconds.
[2020-05-04 20:16:18.802882 +0000][Error  ][PostMaster        ] [p0@origin:1095] Unable to recover: [FATAL] Auth failed.
[2020-05-04 20:16:18.802893 +0000][Error  ][XRootD            ] [p0@origin:1095] Impossible to send message kXR_stat (path: /hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20longtoken&oss.lcl=1&pss.tid=http, flags: none). Trying to recover.
200504 20:16:18 16921 ofs_stat: unknown.2732:196@client Unable to locate /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200504 20:16:18 16921 unknown.2732:196@client XrootdResponse: sending err 3010: Unable to locate /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200504 20:16:18 16921 unknown.2732:196@client ofs_open: 0-600 fn=/hcc/PROTECTED/dweitzel-test/blah2.txt
[2020-05-04 20:16:18.869276 +0000][Error  ][XRootDTransport   ] [origin:1095.0] No protocols left to try
[2020-05-04 20:16:18.869303 +0000][Error  ][AsyncSock         ] [origin:1095.0] Socket error while handshaking: [FATAL] Auth failed
[2020-05-04 20:16:18.869363 +0000][Error  ][PostMaster        ] [origin:1095] elapsed = 0, pConnectionWindow = 120 seconds.
[2020-05-04 20:16:18.869374 +0000][Error  ][PostMaster        ] [origin:1095] Unable to recover: [FATAL] Auth failed.
[2020-05-04 20:16:18.869379 +0000][Error  ][XRootD            ] [origin:1095] Impossible to send message kXR_open (file: /hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20longtoken&oss.lcl=1&pss.tid=http, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
200504 20:16:18 16921 Posix_Open: [FATAL] Auth failed open root://origin:1095//hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20longtoken&pss.tid=http&oss.lcl=1
200504 20:16:18 16921 ofs_open: unknown.2732:196@client Unable to open /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200504 20:16:18 16921 unknown.2732:196@client XrootdResponse: sending err 3010: Unable to open /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200504 20:16:18 16921 unknown.2732:196@client ofs_close: use=0 fn=dummy
200504 20:16:18 16921 XrootdXeq: unknown.2732:196@client disc 0:00:00 (send failure)
200504 20:16:18 16921 unknown.2732:196@client XrdPoll: FD 196 detached from poller 0; num=0
```

**Comment by xrootd-dev** [comment]
Hi Derek,

Try limiting TLS to session so that GSI doesn't run over a TLS channel. 
There may be an issue here as we found out that GSI shares common 
structures with TLS and may leave it in a strange state. Michal pushed a 
fix for this in the client but we have no couterpart in the server.

Andy

**Comment by djw8605** [comment]
Hi,

I'm not sure what you mean by:
> Try limiting TLS to session

Should I just try turning off GSI as an option?  In the end I would want both options for some backward compatibility.

**Comment by abh3** [comment]
Hi Derek,

Please look at the xrootd.tls directive. You will notice that "all" 
includes login. You can say "session" that excludes login. You can also 
try without GSI but that's a completely different test. Please note that 
the RC2 has some issues regarding TLS that we are solving for RC3 which 
will come out within a week or so. Alternatively, so a source build from 
git head whcih already has these fixes.

Andy

**Comment by djw8605** [comment]
Ah, ok.  I set the value to `session`.  The cache seems to just "stall"... it connects to the origin then nothing.

Here's the origin's logs:
```
200504 21:03:13 22229 XrdSched: running main accept inq=0
200504 21:03:13 22186 XrdInet: Accepted connection from 113@cache
200504 21:03:17 22187 XrdSched: Now have 4 workers
200504 21:03:17 22187 XrdSched: running monitor window clock inq=0
200504 21:03:17 22187 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:03:22 22281 XrdSched: running monitor window clock inq=0
200504 21:03:22 22281 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:03:27 22187 XrdSched: running monitor window clock inq=0
200504 21:03:27 22187 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:03:32 22281 XrdSched: running monitor window clock inq=0
200504 21:03:32 22281 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:03:37 22187 XrdSched: running monitor window clock inq=0
200504 21:03:37 22187 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:03:42 22281 XrdSched: running monitor window clock inq=0
200504 21:03:42 22281 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:03:43 22186 XrdProtocol: anon:113@cache terminated handshake not received
...
```

**Comment by abh3** [comment]
Just rerun with the origin started with the -d command line option to see 
where it stalled.

**Comment by djw8605** [comment]
No stall this time...  Can't recreate the stall...  But the debugging seems to indicate that the server is asking for GSI?  Or the cache is trying to use GSI, even though it doesn't have a proxy?

Origin Debug output:
```
200504 21:27:53 29981 XrdXeq: Worker thread started
200504 21:27:53 29886 XrdInet: Accepted connection from 113@cache
200504 21:27:53 29886 XrdProtLoad: matched port 1095 protocol xroot
200504 21:27:53 29886 anon:113@cache XrdPoll: FD 113 attached to poller 0; num=1
200504 21:27:53 29886 anon:113@cache XrootdProtocol: 0000 req=protocol dlen=0
200504 21:27:53 29886 anon:113@cache XrootdResponse: 0000 sending 8 data bytes
200504 21:27:53 29886 anon:113@cache XrootdProtocol: 0000 req=login dlen=112
200504 21:27:53 29886 sec_getParms: cache sectoken=&P=gsi,v:10400,c:ssl,ca:4f06f81d.0|4a0a35c0.0
200504 21:27:53 29886 p0.7047:113@cache XrootdResponse: 0000 sending 61 data bytes; status=0
200504 21:27:53 29981 XrdSched: Now have 4 workers
200504 21:27:53 29981 XrdSched: running monitor window clock inq=0
200504 21:27:53 29981 XrdSched: scheduling monitor window clock in 5 seconds
200504 21:27:53 29982 XrdXeq: Worker thread started
200504 21:27:53 29886 XrootdXeq: p0.7047:113@cache disc 0:00:00
200504 21:27:53 29886 p0.7047:113@cache XrdPoll: FD 113 detached from poller 0; num=0
```

Cache debug output:
```
200504 21:27:53 7076 secgsi_InitProxy: Not a tty: cannot prompt for proxies - do nothing 
200504 21:27:53 7076 secgsi_QueryProxy: problems initializing proxy via external shell
[2020-05-04 21:27:53.222688 +0000][Error  ][XRootDTransport   ] [p0@origin:1095.0] No protocols left to try
[2020-05-04 21:27:53.222710 +0000][Error  ][AsyncSock         ] [p0@origin:1095.0] Socket error while handshaking: [FATAL] Auth failed
[2020-05-04 21:27:53.222748 +0000][Error  ][PostMaster        ] [p0@origin:1095] elapsed = 0, pConnectionWindow = 120 seconds.
[2020-05-04 21:27:53.222759 +0000][Error  ][PostMaster        ] [p0@origin:1095] Unable to recover: [FATAL] Auth failed.
[2020-05-04 21:27:53.222771 +0000][Error  ][XRootD            ] [p0@origin:1095] Impossible to send message kXR_stat (path: /hcc/PROTECTED/dweitzel-test/blah2.txt?authz=Bearer%20longtoken&oss.lcl=1&pss.tid=http, flags: none). Trying to recover.
200504 21:27:53 7053 ofs_stat: unknown.1:161@client Unable to locate /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
200504 21:27:53 7053 unknown.1:161@client XrootdProtocol: 0000 rc=-1 stat /hcc/PROTECTED/dweitzel-test/blah2.txt
200504 21:27:53 7053 unknown.1:161@client XrootdResponse: 0000 sending err 3010: Unable to locate /hcc/PROTECTED/dweitzel-test/blah2.txt; permission denied
```

**Comment by abh3** [comment]
Well, you should make sure xcache has a proxy cert if you are going to an 
origin that requires GSI authentication, which all of them usually do 
unless you didn't configure that. Presumably, you want to test 
authirzation tokens in the presence of authentication (e.g. gsi).

**Comment by djw8605** [comment]
My goal is to make an origin that will accept GSI or tokens for authentication.  But a cache should be able to just use tokens and not GSI to retrieve a file.

**Comment by abh3** [comment]
OK, we don't have a token authentication plugin. Do you? I know you have 
an authorization plugin for tokens but that is not an identity scheme. You 
will need a identity plugin based on a token. You can then run gsi along 
side of that but you will have to either order the choice to try token 
identity first or set in the proxy what authentication schemes are 
acceptable to you (much easier). Afer succesful authentication you can 
use the authorization token for, well, actual authorization.

**Comment by djw8605** [comment]
Ah, I think I used the wrong words.  My goal is to have a server that will use GSI or Tokens to retrieve data.  Is there a way for a xrootd server to accept a non-gsi authentication (no authentication), then use tokens for authorization?  While at the same time, also allowing connections with GSI authentication and authorization?

**Comment by abh3** [comment]
Well, the short answer is yes, it is possible but then you have a server 
where anyone can actually come in wihout authentication because I can 
easily setup a client that bypasses GSI. What your banking on that if some 
does bypass strong authentication you will *always* catch it because they 
wouldn't have the correct authorization token. We haven't certified that 
this is the case so in effect you're allowing anonymous logins. Yes, I am 
not a proponent of that scheme for obvious security implications.

Tha said, you can do that by adding some useless authentication scheme in 
addition to GSI (e.g. unix authentication). In this case, define GSI 
first, then unix second. If gsi fails, the client will try unix which 
always succeeds.

Andy

**Comment by bbockelm** [comment]
@djw8605 - don't forget that the GSI authentication protocol for Xrootd _only_ works with proxies.  It does not work with 'normal' client certificates and does not have the concept of anonymous sessions.

@abh3 - is it possible to mix GSI auth'n and Unix auth'n when using the built-in authorization file mechanism?  IIRC, there's no way to provide authorizations based upon the authentication protocol.  That is, if I wanted to provide an authorization line like this:

```
g /cms /store a
```

is it possible that this only matches groups coming from GSI authentication but _not_ Unix authentication?

**Comment by abh3** [comment]
On Mon, 4 May 2020, Brian P Bockelman wrote:

> @djw8605 - don't forget that the GSI authentication protocol for Xrootd 
>_only_ works with proxies.  It does not work with 'normal' client 
>certificates and does not have the concept of anonymous sessions.
Well, not yet anyway. Once we replace TPC with get/putfile you will be 
able to use get/putfile for third party transfers without logging in (i.e. 
essentially an anonymous login). But yes, login requires some kind of 
authentication even if it bogus (the default is bogus).

> @abh3 - is it possible to mix GSI auth'n and Unix auth'n when using the 
>built-in authorization file mechanism?  IIRC, there's no way to provide 
>authorizations based upon the authentication protocol.  That is, if I 
>wanted to provide an authorization line like this:
>
> ```
> g /cms /store a
> ```
>
> is it possible that this only matches groups coming from GSI 
>authentication but _not_ Unix authentication?
Yes. If you have a set of authorization plugins that are 
authentication type sensitive, you can stack them. Then if the auth 
protocol of the first in sequence is not handled, it simply calls the 
next one in the chain and returns its result. In this way you can have 
authentication sensitive authorization. That exists in R5.

I thougth that was what you will be doing anyway. So, you would stack 
token authorization on top of the generic authorization. If the incomming 
thing was token based you would handle it and if not you would pass it to 
the next stacked plugin.

Andy

**Comment by bbockelm** [comment]
> Yes. If you have a set of authorization plugins that are authentication type sensitive, you can stack them

This isn't exactly what I was getting at.  Within the default authorization module, is there any way to setup rules that *only* match authentication information coming from a specific plugin?

Let's say I do a "SciTokens" plugin stacked with the default one and then a client performs Unix authentication without a token.  How do I stop it from matching a rule like:

```
u bbockelm /store a
```

?  I only trust the user information filled in by the GSI authentication, not the Unix auth.

**Comment by abh3** [comment]
Well, that should have been prevented. If you don't have a SciToken and 
you expected one with, say, unix then you shouldn't forward the request. 
If you don't have it but it is GSI (or some other strong authentication 
mechanism you trust) then you can forward it.

From my understanding, based on what I read, is that SciToken is self 
describing. That is, if you have one then it encodes all possible 
priveleges for the resource it describes and you neither want to 
further restrict them nor expand them using some other authorization 
scheme. Doing so makes auditing next to impossible.

Adding authentication protocol rules to the basic authorization database 
adds sufficient complexity, I think, that people would have a hard time to 
properly specify the rules; defeating the whole purpose here (I could be 
convinced otherwise, I suppose). The system expects, whatever 
authentication scheme is used, it properly fills out the SecEntity 
structure. That should be sufficient for what is used here. Unix nor any 
other untrusted authentiation does not fill in fields on which decisions 
are made. Hence, there is no information to grant privileges.

Andy

**Comment by bbockelm** [comment]
> If you don't have a SciToken and you expected one with, say, unix then you shouldn't forward the request. If you don't have it but it is GSI (or some other strong authentication mechanism you trust) then you can forward it.

Actually, I think Derek was considering the settings for the origin -- right @djw8605 ?

That said, it looks like, during the transition period, we have the following sequence:
1.  All caches will need registered host certificates, enabling GSI authentication between cache and origin.
2. Start introducing the use of SciTokens chained to the default Authfile; because the SciToken plugin is listed first, authorization will be done preferentially with that.
3.  As each VO converts to SciToken authorization, you can remove their corresponding rules from the Authfile.
4.  Once all VOs have converted over to SciTokens, you can add the Unix authentication method to origins.
5.  Once all origins have updated then you can remove the requirement of host certificates for caches and start removing the GSI authentication method.

**Comment by djw8605** [comment]
Yes, origins.  

I just ran a test with a cache that does not have a registered host certificate.  The GSI authentication works, and it appears to use the scitoken for authorization.

How do I list a preference list of SciToken over GSI?

**Comment by bbockelm** [comment]
> How do I list a preference list of SciToken over GSI?

That's not precisely the right question.  You want to prefer Scitokens over the Authfile authorization.

To do so, you setup the stackable plugin mechanism and make sure that SciTokens is configured first.

**Comment by xrootd-dev** [comment]
To be more precise. Stackable plugins are strictly LIFO. That is the last 
plugin stacked is the first to be called in the chain. So, order is 
important. Then there is the default plugin which is the one specified 
without the "++". The default is automatically made the last plugin in the 
chain when you specify ofs.authorize. You can of course displace it 
with your own plugin. Here, Brian is saying not to do that. Taking all of 
this into account, the sciToken plugin should be specified as a "++" 
plugin.

**Comment by abh3** [comment]
Has this issue been resolved so we can close it?

**Comment by abh3** [comment]
I think this has been resolved so I am closing the ticket.
