### ISSUE TITLE
el7::python:: client.__version__ is unknown

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1210]
so, i just noticed that on el7 (lxplus) with native python (3.6.8) the client version is not properly shown..
to reproduce, just `pip install --user xrootd` and then:  
```
python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from XRootD import client
>>> print(f'XRootD version: {client.__version__}\nXRootD path: {client.__file__}', flush = True)
XRootD version: unknown
XRootD path: /afs/cern.ch/user/a/asevcenc/.local/lib/python3.6/site-packages/XRootD/client/__init__.py
```

```
pip3 freeze | grep xrootd
xrootd==4.12.0
```

**Comment by adriansev** [comment]
ping @simonmichal i just tried again and also with 4.12.2 i get an "unknown" `__version__`
any idea about this?

**Comment by simonmichal** [comment]
@adriansev :

Thanks for reporting this issue and sorry for the delay!

Yes, you are absolutely right, the `__version__` is not reporting the correct version of the package but a string `"unknown"`.

I had a look and the reason for this is that the wheel tarball is stripped from git specific staff and the version is generated from a git tag.

Sorry for that, apparently I test the `__version__` only with RPM python bindings, it shall be fixed!

**Comment by simonmichal** [comment]
Here's the fix for the issue: https://github.com/xrootd/xrootd/commit/bd77c93bf6b7f7e53bfc93cce44b285481a263a2

**Comment by simonmichal** [comment]
@adriansev : just checked and the problem is still there in 4.12.3, let me prepare another fix

**Comment by simonmichal** [comment]
@adriansev : I just pushed 5980a617d7d9f32380771b6b88b988b621b8f397 which should fix the problem, tested it by installing th wheel by hand and it worked for me, however I'll keep the issue open until next release

**Comment by simonmichal** [comment]
@adriansev  : I just tested the bugfix with freshly released XRootD5 and it works :-)
