### ISSUE TITLE
File "collision" / duplicate packaging XrdSecgsiVOMS symlink

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1212]
With XRootD 4.12.1 and 4.12.2 RPMs, I find:
```
# rpm -qf /usr/lib64/libXrdSecgsiVOMS-4.so 
xrootd-libs-4.12.2-1.el7.x86_64
xrootd-voms-4.12.2-1.el7.x86_64
```
For XRootD 4.12.1, this means the binary is packaged twice (luckily, bit-identical, so `yum` does not become unhappy). 

Starting with 4.12.2, the newly named library is only packaged once:
```
# rpm -qf /usr/lib64/libXrdVoms-4.so 
xrootd-voms-4.12.2-1.el7.x86_64
```

That's not an "actual" issue with any bad observable effect, but maybe the duplicate packaging of the symlink should be dropped to avoid potential file collisions? 
Unless it will be deprecated soonish anyways. 

Very low priority I'd say, feel free to close, but thought I should report it to leave the decision to you ;-).

**Comment by abh3** [comment]
Hi Oliver,

Yes, this will be corrected. This is our first attempt to package a 
symlink within an RPM. It seems not exactly as straightforward as one 
might think. In the future more symlinks will be packaged as we move to 
using the standard shared library versioning scheme for plugins.

Andy

**Comment by simonmichal** [comment]
The problem has been fixed in:
https://github.com/xrootd/xrootd/commit/1bb4af4510d80f88c3da52ceeaf4f5b1315a3c07
