### ISSUE TITLE
XRootD space usage gets messed up at every xrootd/cmsd restart and is hard to correct

### ISSUE THREAD

**Issue by hseverini** [xrootd/xrootd#1213]
We've been having space reporting issues here at OU for quite some time. 
After every xrootd/cmsd restart, commands like

df /xrd/?oss.cgroup=ATLASDATADISK
xrdfs cstore11 query space /xrd/?oss.cgroup=ATLASDATADISK

report completely nonsensical numbers; mostly 0, or at least MUCH too small.

I can usually get it fixed, but I have to run

frm_admin -c /etc/xrootd/xrootd-clustered.cfg -n clustered audit -fix -force usage

on all storage servers, and usually multiple times, before the numbers
make sense and are stable again. Every time I run this command,
the output is reasonable, something like this:

Audit of 545721 files in ATLASDATADISK space completed with no errors.
Claimed:            0
Actual:  71600543709295

But then when I then run the above oss.cgroup commands again, they're back
to 0 or very small, and I have to do this several times. 

I don't think there's a problem with any of the space configuration
or reporting in general, since it's behaving perfectly normal and
consistent once it's stable -- but every time I have to restart,
it's completely messed up, and I can only get it stable again
by re-running the fix multiple times, and even then it only seems
to 'take' when the file system is idle. So that makes me think
that there might be some kind of 'caching' or race condition going on
which keeps messing things up even after 'fixing' it again and again.

Each 'fix' by itself looks perfectly fine, too, the reported fixed
'Actual:' numbers are perfectly reasonable. But they don't stay,
but seem to be getting overwritten by the wrong numbers again.

Here's an example from the fix I just ran on one of the (7 identical) storage servers:

Audit of 35069 files in ATLASSCRATCHDISK space completed with no errors.
Claimed:           20
Actual:  1734698250629

Yet a few minutes later, the oss.cgroup commands above report this again:

ATLASSCRATCHDISK:
Filesystem        1K-blocks  Used    Available Use% Mounted on
xrootdfs       765694027776     0 299222330089   0% /xrd
0

The space/usage configuration looks fine:

       oss.usage log $(osscachepath)/.logs
       oss.space ATLASDATADISK assign /xrd/atlasdatadisk/
       oss.space ATLASLOCALGROUPDISK assign /xrd/atlaslocalgroupdisk/
       oss.space ATLASSCRATCHDISK assign /xrd/atlasscratchdisk/

And all that works perfectly fine, and tracks very reasonably with file transfers and deletions on the storage -- until I need to restart xrootd, then it's messed up again.

Let me know what other details I can add to help debug this.

Thanks a lot,
    Horst

**Comment by abh3** [comment]
Hi Horst,

If you have a messed up space value now. Could you send me the usage file? That files tracks space usage across restarts. You must have specified the oss.usage directive to get feaure:

https://xrootd.slac.stanford.edu/doc/dev50/ofs_config.htm#_Toc42094201

and you must have specified the "log" option which indicates where the usage file is stored. The file itself is named ".Usage".

**Comment by abh3** [comment]
Also, could you send me (privately) your config file? You should have gotten a message for all three space groups when you ran frm_admin, though in the post you show only one.

**Comment by abh3** [comment]
OK, I pushed a patch that likely solves the usage update issue upon restart. I still can't figure out how your usage stats go way off the deep end. Anyway, I think I also see why the server may miss detecting the frm_admin audit updates as well. So, stay tuned.

**Comment by hseverini** [comment]
Hi Andy,

thanks! In case this is still useful, here's some more information.

Yes, all space groups were fixed, I only sent you one as an example. Here's the complete output of cstore11's last fix:

----
Audit of 35069 files in ATLASSCRATCHDISK space completed with no errors.
Claimed:            0
Actual:  1734698250629
Audit of 5214 files in ATLASLOCALGROUPDISK space completed with no errors.
Claimed:            0
Actual:  2307556894528
Audit of 498365 files in ATLASDATADISK space completed with no errors.
Claimed:  11993149362
Actual:  65010776295655
Audit of 116 files in public space completed with no errors.
Claimed: 223340914190
Actual:  223340914190
----

That was a few days ago, so things have changed since, but the current usage shows that LOCALGROUPDISK is way off again, at least on that server. The first number below is from cstore11, and then the other 6 servers. They should all show roughly the same, since the servers are pretty well balanced.

----
ATLASDATADISK:
68445699487289
56094782846807
68959311467158
56282078410523
63124517732464
69535660379334
69536269420556

ATLASLOCALGROUPDISK:
2307556897528
2291028980971
2355459965719
3280
3180
2296649283341
3260

ATLASSCRATCHDISK:
2400
3640
2600
1573175712257
1714778431188
2900
2520

public:
225955379726
172443302061
216656392931
227284052402
212123373809
216416678677
233566653469
----

So only ATLASDATADISK and public make sense -- the 20% or so differences between the servers are real, I can verify that with 'df' on those xfs partitions -- but the other two groups are completely off on some of the other servers.

Here's the relevant info from /etc/xrootd/xrootd-clustered.cfg:
----
        oss.usage log $(osscachepath)/.logs
        oss.space ATLASDATADISK assign /xrd/atlasdatadisk/
        oss.space ATLASLOCALGROUPDISK assign /xrd/atlaslocalgroupdisk/
        oss.space ATLASSCRATCHDISK assign /xrd/atlasscratchdisk/
----

That all makes sense, since it works fine when things are stable.

I can't figure out how to attach a file here, so I'll email you cstore11's .Usage file privately.

So into which release will the patch you just submitted will make it?
I guess it's too late for 4.12.3?

Thanks a lot,
    Horst

**Comment by xrootd-dev** [comment]
Hi Horst,

Interesting. Anyway, there are some more fixes I have to make. You are 
correct that it's too late for the 4.x series and we don't plan another 
release (yet) for that series. So, it will be in R5 for sure.

Andy

**Comment by abh3** [comment]
OK, I pushed a set of fixes to solve this problem. As far as I can tell it was due to some MT loopholes in the way usage was tracked. I will leave this ticket open as this will be included in R5 and there are no current plans to back port it to the 4.x series.

**Comment by abh3** [comment]
This has been fix last 4.12 patch.
