### ISSUE TITLE
Xcache in Xrootd 5 rc4 crash when access a fully cached file created by xrootd 4.12.1

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1217]
I have a Xcache configured like this:

all.export /
ofs.osslib libXrdPss.so
pss.origin =
xrootd.async nosf
pss.cachelib libXrdFileCache.so
oss.localroot /tmp/data
all.adminpath /tmp/xrootd/var/spool
all.pidpath   /tmp/xrootd/var/run

The storage has a file fully cache when Xcache run under xrootd 4.12.1. When I change to use xrootd 5rc4, and access the same file, it crashed. here is the trace out. Did I miss something?

$ gdb /u/sf/yangw/xrd/git/xrdgithead/amd64_rhel70/src/xrootd /tmp/yangw/core.79902
...
#0  0x00007fcb53201387 in raise () from /lib64/libc.so.6
#1  0x00007fcb53202a78 in abort () from /lib64/libc.so.6
#2  0x00007fcb531fa1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fcb531fa252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fcb4c3e9b20 in XrdPfc::Info::CompactifyAccessRecords (this=0x12a8a18) at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/XrdPfc/XrdPfcInfo.cc:380
#5  0x00007fcb4c3e9362 in XrdPfc::Info::Write (this=0x12a8a18, fp=0x1262820, fname="<unknown>")
    at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/XrdPfc/XrdPfcInfo.cc:290
#6  0x00007fcb4c3db0a6 in XrdPfc::File::Sync (this=0x12a8a00) at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/XrdPfc/XrdPfcFile.cc:980
#7  0x00007fcb4c3bb353 in (anonymous namespace)::DiskSyncer::DoIt (this=0x1310cc0) at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/XrdPfc/XrdPfc.cc:522
#8  0x00007fcb54499b66 in XrdScheduler::Run (this=0x61bde0 <XrdGlobal::Sched>) at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/Xrd/XrdScheduler.cc:382
#9  0x00007fcb54498c9a in XrdStartWorking (carg=0x61bde0 <XrdGlobal::Sched>) at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/Xrd/XrdScheduler.cc:88
#10 0x00007fcb544450a6 in XrdSysThread_Xeq (myargs=0x12354e0) at /u/sf/yangw/xrd/git/xrdgithead/xrootd/src/XrdSys/XrdSysPthread.cc:86
#11 0x00007fcb53fc7ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007fcb532c98dd in clone () from /lib64/libc.so.6

**Comment by osschar** [comment]
I'll check this later today, thanks! It was probably me that missed something :)

**Comment by wyang007** [comment]
Addressed by commit 0676cc114a304b46d27e76fa47d61ed09d687ff0

**Comment by osschar** [comment]
I also made a change in xcache to avoid assertion failure #1220
