### ISSUE TITLE
Using real uid/gid in mount and on server

### ISSUE THREAD

**Issue by mstud** [xrootd/xrootd#1219]
Hi all, 
I'm new to xrootd and am wondering if it can be used as a POSIX-like replacement for NFS where the files in the mounted directories (using xrootd-fuse) are visible under their real uid/gids, and all access is checked server-side against permissions of those uid/gids? By default, all files seem to be owned by the xrootd user on the server side, which doesn't work for me.

I have tried this: https://github.com/joaquimrocha/xrootd-auth-change-uid
but my problem is that all client requests seem to come with the uid of the user I specified in the fuse mount options, and not the real users. Also, I don't see the real uids/gid/permissions in "ls -l" on the client.

Do I need to change some client configuration I have no found out about, yet? Or is there some kind of guide or documentation on how to set this up properly? Or is xrootd not suited to be a full-blown NFS replacement and does not support my use-case?
Thanks in advance.

**Comment by wyang007** [comment]
Hi, xrootd doesn't have the concept of file ownership. it uses ACL. For example, you can use username/group name based (not uid/gid) ACL rules. The xrootdfs man page described how to do this with the "sss" security module.

**Comment by olifre** [comment]
Wei is completely right, of course. 

I believe:
https://github.com/opensciencegrid/xrootd-multiuser
does something similar to what you may want, but I have never actually used that myself (we also use ACLs, and use `ofs.notify` to enforce ACLs and umasks as-needed).

**Comment by wyang007** [comment]
thanks Oliver. I thought there was such a thing. There should be a review about this plugin because it could have a significant value.

**Comment by olifre** [comment]
Hi Wei, indeed, I think this can solve some issues both for the Grid usecases (mapping to VO users), and also for fully independent projects (we'd for example also consider using XRootD with our local identities and Kerberos, if files could be mapped to the correct UID s/ GIDs). 
So yes, I think this can have considerable value, and I only stumbled upon it by accident, so getting that reviewed would be a good thing :-).

**Comment by abh3** [comment]
Hi Oliver et al,

It was indeed our intention to merge in the functionality of that plugin 
into the base code. he only things in the way are:

a) Verifying that a true mapping has been done,
b) Trapsing through all the places where using setfsuid() and setfsgid() 
(the heart of the whole thing) would cause problems.

It is on out list though we don't yet know what priority to give it.

Andy

**Comment by bbockelm** [comment]
I recall the plugin was waiting on some feature of XRootD V5 that would make it simpler -- although honestly I can't recall what that was.

Anyhow, it's been running well at a few sites over the past few years.  Looking at the code, there's a few opportunities for cleanup.

That said, it's not clear if this would fix the original problem?  Looks like the original problem was that `xrootd-fuse` wasn't passing along the username from the client to the server itself.

**Comment by wyang007** [comment]
Hi Brian,

With the “sss” security, the xrootd-fuse does pass the original client’s username to the server, in XrdSecEntity (again, username, not uid)

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 6/19/20, 1:14 PM, "Brian P Bockelman" <notifications@github.com<mailto:notifications@github.com>> wrote:


I recall the plugin was waiting on some feature of XRootD V5 that would make it simpler -- although honestly I can't recall what that was.

Anyhow, it's been running well at a few sites over the past few years. Looking at the code, there's a few opportunities for cleanup.

That said, it's not clear if this would fix the original problem? Looks like the original problem was that xrootd-fuse wasn't passing along the username from the client to the server itself.

**Comment by bbockelm** [comment]
> With the “sss” security, the xrootd-fuse does pass the original client’s username to the server, in XrdSecEntity (again, username, not uid)

Right - it strikes me that perhaps the underlying problem was `sss` is not setup for this install?

**Comment by abh3** [comment]
Actually, with the R5 SSI the fuse client should be passing the actual 
uid/gid which makes the whole thing much simpler. There isn't any code 
changes required to do that just configuring SSI to pass along the 
information.

**Comment by abh3** [comment]
I meant SSS security -- the problem when working on unrelated plugins, 
sigh.

**Comment by wyang007** [comment]
I don’t know whether the setup use “sss”. But using “sss” doesn’t address the ownership problem. It only allow ACL to work based on the actual username.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 6/19/20, 1:27 PM, "Brian P Bockelman" <notifications@github.com<mailto:notifications@github.com>> wrote:


With the “sss” security, the xrootd-fuse does pass the original client’s username to the server, in XrdSecEntity (again, username, not uid)

Right - it strikes me that perhaps the underlying problem was sss is not setup for this install?

**Comment by wyang007** [comment]
I guess you meant ‘sss, not ssi‘. Currently xrootdfs explicitly fill the XrdSecEntity with username. Maybe that can be simplied somehow.

We should take this discussion to somewhere else. Not polluting this ticket.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 6/19/20, 1:40 PM, "Andrew Hanushevsky" <notifications@github.com<mailto:notifications@github.com>> wrote:

I meant SSS security -- the problem when working on unrelated plugins,
sigh.

**Comment by abh3** [comment]
Likely so. Since proxy security is a sensitive subject there are a few 
more things that you have to specify so hat we can be sure you are not 
spoofing the identity.

**Comment by abh3** [comment]
Sure, we can take this offline. I can point to the topic on how to set it 
up and you can pass along the uid/gid. Then we have everything we need to 
do the fsuid() fsgid() magic.

**Comment by ajkotobi** [comment]
This is also a pressing issue for us as we want to replace NFS and have xrootd used locally for transfer, xrootd-fuse etc..

**Comment by abh3** [comment]
Hi Amjad,

Duly noted. There are a few thing we still need to do to make sure the 
information is passed and that requires some coordination with other 
developers. I don't think this will take a long time but we won't have 
this available until R5.1 which is scheduled to occcur shortly after R5.

Andy

**Comment by abh3** [comment]
I think we resolved this by saying you need to use the multi-user plugin. So, I am closing this.
