### ISSUE TITLE
[HTTP] XrdCmsClient::Locate isn't handed a correct XrdOucEnv *EnvInfo in case of HTTP

### ISSUE THREAD

**Issue by pkramp** [xrootd/xrootd#1233]
Hi,

to give some context, I am currently adding redirect to local filesystem functionality to XRootd-HTTP.

The current plug-in for redirectToLocal **XrdCmsRedirLocal** is working for the root-protocol,  but not for http.

This is due to the fact that **EnvInfo->secEnv()->addrInfo;** is accessed in the Locate method, to make the necessary checks to see, if a redirect to local is allowed. [Source](https://github.com/xrootd/xrootd/blob/master/src/XrdCms/XrdCmsRedirLocal.cc#L111)

However, when using HTTP to access the redirector, the addrInfo is null.

Is this by design? Was it simply not required?
Is there a possibility to get the addrInfo added for HTTP?

Cheers,
Paul

**Comment by abh3** [comment]
No, this is clearly an oversight. I think I fixed that in R5 but I will 
look again.

**Comment by abh3** [comment]
Indeed, this is fixed in R5. A back port is relatively messy. OK, if you get that starting in R5?

**Comment by pkramp** [comment]
I think we will be fine with R5.
I will get back to you soon with a pull-request.

So far, the changes seem to be minor.

Thanks,
Paul

**Comment by pkramp** [comment]
I have created the pull-request, closing this as the underlying bug was fixed for R5
