### ISSUE TITLE
XrdPfc_CInfo: error Info:::Write() <unknown>  lock failed bad file descriptor

### ISSUE THREAD

**Issue by riccardodimaria** [xrootd/xrootd#1241]
In a testing env that uses XRootD HEAD, aka new R5-rc5, a simple request to a file readable worldwide succeeds:
`xrdcp -f -v  xroot://escape-wp2-puppet-xcache-level0-02.cern.ch:1094//xroot://escape-wp2-puppet-mockdata-server.cern.ch:1213//escape/escape_origin.txt_1024_0 /dev/null
[1024B/1024B][100%][==================================================][1024B/s] 
`
but the log [1.9] of XCache shows “XrdPfc_CInfo: error Info:::Write() <unknown>  lock failed bad file descriptor”.

[1.9] /afs/cern.ch/user/r/rdimaria/public/xrootd.log-badFileDescriptor

**Comment by xrootd-dev** [comment]
Hi Riccardo,

We've been looking at the code path and it does not provide a clue as to 
what may be causing this. We also cannot reproduce it so it's something 
special about your configuration. Would it be be possible for me to 
provide a source branch that aborts the server when this happens so we can 
look at a core file? I know it's particularly challenging as this is 
containerized.

Andy

**Comment by osschar** [comment]
Riccardo, don't bother, I found this message in my log as well, will figure out what is happening here :)

Thanks!

**Comment by xrootd-dev** [comment]
OK, I pushed teh patch. Please test ASAP!

**Comment by osschar** [comment]
Yup, this works now, thanks!
