### ISSUE TITLE
xrdfs: cat multiple files at once

### ISSUE THREAD

**Issue by vindex10** [xrootd/xrootd#1243]
Hello!

It would be nice to have an option to "cat" several files in a row somehow.

The real life situation:

I've generated lots of events, and they end up stored in a single gzip file split into smaller pieces, so that header is only in the first file. I stored them at CERNBox.

Now I want to "gunzip" them, but since I don't have an option to "cat" multiple files neither with "eos" nor with "xrdfs", I end up in a situation when I have to either write my own xrootd stream reader or download all files back.

As an alternative, that would be really helpful in my situation, I'd prefer doing the following:

`xrdfs $EOS_MGM_URL cat /eos/user/.../file.gz.1 /eos/user/.../file.gz.2 | gunzip - > file`

Thank you!

**Comment by vindex10** [comment]
As a temporary workaround I have the following solution:


1. Create an executable bash script to iterate over pieces (`iterate.sh`):

```
#!/bin/bash

for i in "/eos/user/.../events.lhe.0" "/eos/user/.../events.lhe.1"; do
    xrdfs $EOS_MGM_URL cat $i
done
```

2. Then run the script, and feed it's output to gunzip:

```
./iterate.sh | gunzip - > events.lhe
```

Of course, this is viable solution, but it would be much more convenient to have a one liner for this :)

**Comment by simonmichal** [comment]
@vindex10 : you can actually copy multiple files and redirect them to `stdout`, e.g.:

```
xrdcp  -N  root://eos-instance//eos/.../file.gz.1  root://eos-instance//eos/.../file.gz.2  -  |  gunzip
```

**Comment by vindex10** [comment]
Wow, that's great! I didn't know it is there :) So, then it is just a semantic request, since functionality is already present!

Thank you so much for the prompt reply!

**Comment by simonmichal** [comment]
@vindex10 : anytime, yes `xrdfs cat` is just a wrapper around `xrdcp` ;-)
