### ISSUE TITLE
dbg option in http.secxtractor causes stuck of HTTP protocol initialization

### ISSUE THREAD

**Issue by riccardodimaria** [xrootd/xrootd#1245]
Hi, 
while testing XRootD HEAD I noticed that one of the options I was using before for http.secxtractor directive causes now stuck of the HTTP protocol initialization.

In particular, setting:
`http.secxtractor libXrdSecgsiVOMS.so vos=atlas,cms,escape,dteam|grpopt=02|dbg`
results in an unfinished log in the cache as:
```
Plugin unreleased XrdHttpProtocolTest v20200708-9364927 is using unreleased XrdVomsHttp v20200708-9364927 version in secxtractorlib libXrdSecgsiVOMS-5.so
200708 17:24:10 21406  XrdVomsInit: ++++++++++++++++++ VOMS plug-in +++++++++++++++++++++++++++++++
200708 17:24:10 21406  XrdVomsInit: +++ proxy fmt:    raw
200708 17:24:10 21406  XrdVomsInit: +++ group option: all of all groups
200708 17:24:10 21406  XrdVomsInit: +++ group(s):      <not specified>
200708 17:24:10 21406  XrdVomsInit: +++ VO(s):        atlas,cms,escape,dteam
200708 17:24:10 21406  XrdVomsInit: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

The removal of option `|dbg` results in the success of the HTTP protocol initialization, and hence of the cache, otherwise stuck.

**Comment by xrootd-dev** [comment]
Could you attach gdb and do:

thread apply bt all

and send me the output? It will be too large to post. If you need more 
specific instructions on how to capture the backtrace I can supply that.

Andy

**Comment by riccardodimaria** [comment]
To be honest, I am quite new to GDB. So not sure what I did is correct. Please tell me otherwise.
- start xrootd and get PID process
- (gdb) attach PID
- (gdb) thread apply all bt

The file attached contains the output of these 2 actions.
[gdb.log](https://github.com/xrootd/xrootd/files/4897503/gdb.log)
