### ISSUE TITLE
[XrdCl] Allow the redirector to force copy from scratch on write failure

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1246]
It would be highly beneficial for EOS if a redirector (MGM in EOS case) could append cgi telling the client to retry the copy from scratch (appending force flag) at the redirector in case of an error on write.

**Comment by abh3** [comment]
In the context that there are several EOS-specific actions that would be nice to have the client handle we really should come up with a way to signal these without using CGI that usually winds up interfering with already present CGI. So, let's think about a good way of doing this with going down that path.

**Comment by simonmichal** [comment]
Implemented in: 78996d7b10ec5f9a0b5a1a67049d5320a481f3b7
