### ISSUE TITLE
libXrdVoms rejects old (non-RFC) VOMS proxies

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1247]
Using either XRootD 4.12.3 or XRootD 5.0.0 with the line:
```
http.secxtractor  /usr/lib64/libXrdVoms.so
```
I observe the following behaviour when accesing it via WebDAVs:
```
$ voms-proxy-init3 -voms atlas -old
$ curl -vvL --capath /etc/grid-security/certificates --cacert $X509_USER_PROXY --cert $X509_USER_PROXY "https://the-host.example.com/some/path
[...]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS alert, unknown CA (560):
* error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
* Closing connection 0
curl: (35) error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
```
In the server logs, I find:
```
200710 16:59:06 2474471 XrdTLS: CertVerify: Cert verification failed for DN=/C=DE/O=GermanGrid/redacted/CN=proxy
200710 16:59:06 2474471 XrdTLS: CertVerify: Failing cert issuer=/C=DE/O=GermanGrid/OU=redacted
200710 16:59:06 2474471 XrdTLS: CertVerify Error 20 at depth 0 [unable to get local issuer certificate]
139757501679360:error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify failed:s3_srvr.c:3327:
```

I do not observe this problem when:
- Using an RFC proxy (`voms-proxy-init3 -voms atlas -rfc`). 
- Using the old secxtractor (`/usr/lib64/libXrdHttpVOMS.so`). 

Note I only tested the latter with 4.12.3. 

Is it expected that the old-style VOMS proxies are not supported anymore?

**Comment by olifre** [comment]
Note that connections via the XRootD protocol, using the configuration:
```
sec.protocol /usr/lib64 gsi -dlgpxy:1 -exppxy:=creds -ca:1 -crl:3 -gridmap:/dev/null -cert:/etc/grid-security/hostcert.pem -key:/etc/grid-security/hostkey.pem -certdir:/etc/grid-security/certificates -vomsfun:/usr/lib64/libXrdVoms.so -vomsfunparms:certfmt=raw|grpopt=useall|vos=atlas,ops,dteam,wlcg|grps=/atlas,/atlas/de,/ops,/dteam,/wlcg|dbg
```
on the same system still accept old (non-RFC) proxies.

**Comment by abh3** [comment]
I think the issue here is that in GSI the stack_of(x509) is not used. 
Instead, raw or pem certs are fed into VomsFun and it creates the 
stack_of(x509). In the HTTP case we don't have access to raw or pem certs 
and instead ask OpenSSL to supply the stack_of(x509). It would seem that 
OpenSSL doesn't know (and probably shouldn't know) how to deal with 
non-RFC compliant certs.

Frankly, we can't keep doing the backward non-standards compliant 
compatibility route for this kind of stuff. If you want to use HTTP then 
you *really* need to use the standards compliant stuff otherwise why do 
you even want to use HTTP in the first place, just for window dressing?

**Comment by olifre** [comment]
Thanks for the elaborate reply!
Since with this we have now understood the "why", I believe this issue can be closed — it's certainly good that we finally get rid of the non-RFC legacy :-).

**Comment by bbockelm** [comment]
> In the HTTP case we don't have access to raw or pem certs
> and instead ask OpenSSL to supply the stack_of(x509). It would seem that
> OpenSSL doesn't know (and probably shouldn't know) how to deal with
> non-RFC compliant certs.

I don't understand this.

OpenSSL provides the `STACK_OF(X509*)` without doing any sort of chain validation (which is where non-RFC compliance is relevant).  It is literally just a pointer to the ordered list of parsed X509 objects from OpenSSL.  It's also what gets passed to security extractors and what worked in 4.x.

The fact you're seeing issues with old-style certificates suggests that something is either (a) not feeding the right chain to the certificate validation routines in XRootD or (b) somehow OpenSSL validation is being used.  Either case is bad; even though the OpenSSL validation of RFC proxies can be invoked, these are known to be fairly buggy and I'd suggest to use the XRootD ones instead.

While I'm also ambivalent on fixing old-style proxies, this is a bit of a warning signal that something is broken in the new code for proxy validation.  I wouldn't be surprised if we see other issues crop up here.

**Comment by olifre** [comment]
>  [...] It's also what gets passed to security extractors and what worked in 4.x.

From the tests I did, I think the main cause of the changed behaviour is switching the `secextractor` from `libXrdHttpVOMS` (of which no build against XRootD 5 was readily available in EPEL) to `libXrdVoms`. 
My test showed: `XrdVoms` with XRootD 4 or 5 does not accept old-style proxies, but `XrdHttpVOMS` with XRootD 4 does accept old-style proxies. I did not test `XrdHttpVOMS` with XRootD 5, though, which means my test is inherently flawed, since `XrdVoms` has only become a fully working secxtractor quite recently (I think).

**Comment by bbockelm** [comment]
> From the tests I did, I think the main cause of the changed behaviour is switching the secextractor from libXrdHttpVOMS (of which no build against XRootD 5 was readily available in EPEL) to libXrdVoms.

Ok, I'm willing to buy this as an explanation and am a little less worried.  This simply means the new code consistently doesn't work and it's not due to unknown issues in the framework.
