### ISSUE TITLE
XrdTpc still uses http.cadir exclusively

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1248]
While `http.cadir` is deprecated and replaced by `xrd.tlsca certdir`, this place of the code:
https://github.com/xrootd/xrootd/blob/fb6a9f2c4c1afb2a546fe25c074479cb8f9f776c/src/XrdTpc/XrdTpcConfigure.cc#L49
still exclusively checks for the deprecated parameter and will not honour `xrd.tlsca certdir`.

**Comment by abh3** [comment]
Well, who would have thought! You are correct and it should be fixed. I 
hate code leakage and this is a classic case of it and totally slipped 
through the cracks.

**Comment by olifre** [comment]
I tried to do a PR for this, but the "easy way out" (looking for `tls.ca certdir`) does not seem to be the best approach,
ideally, the code would also handle `certfile` and inherit the parsed configuration. 
Implementing that, though, requires a better feeling for the code base than I currently have, so I'll hand over the implementation to you :-).

**Comment by olifre** [comment]
This was fixed via https://github.com/xrootd/xrootd/commit/2a7dccc5e9e9c5a54de8e066db3fe992453f703f (together with #1323 ), so I'm also closing this one :-).
