### ISSUE TITLE
virtual user with a dot triggers a failure

### ISSUE THREAD

**Issue by chaen** [xrootd/xrootd#1283]
When the virtual user name contains a dot, xroot is unhappy :-) 
Note that I can notice that only at IN2P3, but I thought a bug report here is more appropriate. Let me know if you'd rather me open a ticket against IN2P3. 

Example bellow

```
bash-4.2$ xrdcp root://a.b@ccxrootdlhcb.in2p3.fr//pnfs/in2p3.fr/data/lhcb/myFile.txt .
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] Login failed
```

```
bash-4.2$ gfal-stat  root://a.b@ccxrootdlhcb.in2p3.fr//pnfs/in2p3.fr/data/lhcb/myFile.txt
gfal-stat error: 103 (Software caused connection abort) - Failed to stat file (Software caused connection abort)
```

```
bash-4.2$ gfal-stat  root://a@ccxrootdlhcb.in2p3.fr//pnfs/in2p3.fr/data/lhcb/myFile.txt
[ANSWER OK]
```

```
bash-4.2$ xrdcp --version
v4.11.2
```

**Comment by chaen** [comment]
Argh ! Sorry, I forgot that dCache has it's own xroot implementation ! I'll close this, sorry :-)

**Comment by abh3** [comment]
Not a problem. However, dCache is very sensitive to these userids and you should limit yourself to the valid UNIX username character set. The latest version of dCache sanitizes the name. That has it's own drawbacks as the name you specify may not be name that is used if it has "bad" characters. The native XRootD implementation, starting in R5, also adopted this scheme to be consistent with dCache.

**Comment by chaen** [comment]
Ah right, I remember now ! Anyway, as of R5 I will not need virtual user anymore :-) (https://github.com/xrootd/xrootd/issues/992)
