### ISSUE TITLE
python:: client.__version__:: erroneous 'v'

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1285]
Hi! Would it be possible to have (return to) strict decimal numbers in the module version?
Currently it is:
```
>>> print(client.__version__)
v5.0.1
```

**Comment by adriansev** [comment]
and for 4.12.4 installed with `pip3_install_user xrootd==4.12.4` i get  
```
python3
Python 3.7.9 (default, Aug 19 2020, 17:05:11)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from XRootD import client
>>> print(client.__version__)
v-
```
ping @simonmichal

**Comment by simonmichal** [comment]
Hi @adriansev,

- regarding the `v-` version, I just backported the respective commit to the stable branch (8f77fe378418b844762e28434e977b983d5c8f01) my apologies it has not been done earlier

- regarding the version format itself, my understanding is you would like to see `5.0.1` instead of `v5.0.1`? Yes, certainly that's doable.

**Comment by simonmichal** [comment]
@adriansev : I'm stripping now the leading `v` from the `__version__` -> 30350cdd2ceeafd7fe82f6f332e199b58eb1921e (also backported to stable branches).

**Comment by adriansev** [comment]
@simonmichal Great!!! thanks a lot!! in principle the advantage of strictly numeric versions (also easily splittable) is that allow really easy version checking when a downstream application use the different signatures that can happen from version to version in upstream. (as i do for the checking hash when copy).

**Comment by simonmichal** [comment]
@adriansev : is there anything else that needs to be sorted out, or can we close this one?

**Comment by adriansev** [comment]
sorry, i forgot about this one, this can be closed (and of course i cannot test it until a release is out :) )
