### ISSUE TITLE
Bug fix release 4.12.5

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1296]
Dear XRootD community,

I'm planning to cut the 4.12.5 with backports of bugfixes from XRootD5, I'm creating this issue so we have a place where we can discuss the upcoming release.

The stable branch has been already updated:
https://github.com/xrootd/xrootd/tree/stable-5.0.x

and a release candidate has been tagged:
https://github.com/xrootd/xrootd/releases/tag/v4.12.5-rc1

Here's the full list of new commits in the upcoming release (so far):
a61e9ec [PIP] Convert egg-info into proper dist-info.
b186bbe [CMake] Set rpath for pip build.
6548db5 [XrdCl] Make sure kXR_attrVirtRdr flag is set properly.
df67dff [CI] Let publish:koji jobs use the updated kojicli image to fix unexpected auth failures
449416d [CI] Make all koji builds manual.
23f0cbc [CI] Set DEBIAN_FRONTEND=noninteractive for Ubuntu builds.
a2a7615 [CI] Replace ubuntu eoan build with focal.
dbad132 [CI] Fix publish weekly script.
d888567 [CI] Publish nightlies only for platforms that have been built.
385a7fb [CI] Update docker test script.
80000a6 [CI] Make sure publish steps are not mixed up on web trigger.
99bdc63 [CI] Make sure only nightlies can be triggered from web interface.
f7d18d9 [CI] Allow to trigger nightlies from web interface for cc7.
6108f8f [CI] Temporarily allow tests to fail.
88da43f [CI] Get data for nightly tests.
d2fce48 [Python] Strip the leading v from __version__.
8f77fe3 [PIP] Generate XrdVersion.hh before packaging xrootd source for pip.

Please let me know if there are any other bugfixes that need backporting to `4.12.5`.

Cheers,
Michal

**Comment by bbockelm** [comment]
@simonmichal - I am working on https://github.com/xrootd/xrootd/issues/1293; can you delay for another day or two?

**Comment by ffurano** [comment]
Hi Michal,

 I may have one for XrdHttp, yet it's taking quite some time to test...

Fabrizio

**Comment by xrootd-dev** [comment]
This is only an RC so it can potentially get additional critical bug fixes 
before final release, though that would first go through another RC 
release.

**Comment by simonmichal** [comment]
@bbockelm & @ffurano : certainly we can wait for your bugfixes!

**Comment by ellert** [comment]
Cherrypick commit 8cb9cbe80bae2beaa14968ef9c28d40301b5d124 to xrootd 4.

**Comment by simonmichal** [comment]
@ellert : done, https://github.com/xrootd/xrootd/commit/8cb0c40513b26d2daa9da516dbf02fac6d172554

**Comment by simonmichal** [comment]
@ffurano : just for the record I cherry-picked ab3e0f914b978874e304090ebf91db805bcee185

**Comment by bbockelm** [comment]
For record, @esindril asked that https://github.com/xrootd/xrootd/pull/1298 be backported as well.

**Comment by simonmichal** [comment]
@bbockelm : noted!

Added:
7dd3692a4b47c172fe2bfd31acbbd5981de56227 Prevent unterminated/corrupted headers from looping the server
03ea695d40708d0ac878a205caaae87e02e67fc3 Bump the max size for an Http header line to 16K

**Comment by simonmichal** [comment]
I added following commit to the stable branch
d7dbae0b1f1bf41476409fb12485be27847c30a4 Improve HTTP-TPC error messages.
c6978d702393170325eccf077c7a7ba7525d8e3f Overhaul logging approach for TPC
2caa8a94e5f0dac3f562b2f6ae5fc67a642b929a Include a list of connections in the performance marker. 
dd91dd87bbd4023f2941324a9a3edd940229ceb5 Add some comments about how the performance markers work in HTTP-TPC. 
000121974659e286f0806bca2bdb5dd29ada8268 Have HTTP-TPC reuse the SFS from the environment. 
6b9d06772dd2df8c4fd9bc217b3f16c378784084 [XrdTPC] Fix slc6 build.
5fd4c2fdcc5032666bc6b91b53ccfd8e97474b5b Avoid old versions of libcurl that do not support CURLINFO_PRIMARY_PORT
81bfa159d3e5823675017a78a8d2fb3adfa01a7c [TPC] Fix potential null pointer dereference on Push.
bd79425b1bba1e52a06a1586345e726069fc129e URI-quote outgoing opaque data for HTTP-TPC
2a6b36c0a120506372ee38a355fbb4fd410e5a4b Per request, use curl's escaping function to match EOS practice.
c0e79df2b4a0e8b5c516fd9f2dca7b362b044b8a [XrdTpc] Clean up after backporting.

Now stable-4.12.x and master should be almost the same in respect to `XrdTpc`.

**Comment by bbockelm** [comment]
Ah, thanks @simonmichal!  The extra work was not necessary but greatly appreciated.

**Comment by simonmichal** [comment]
Following commits have been added to the stable branch:
da1376c1a6ba93aed05fc9c6ddb44ac2e56d30a3 BUILD: Really pass the user version when building
447800d25037c89829fdbf586750eaa024112f35 [XrdCl] Utils::GetHostAddresses: use shuffle insted of random_shuffle.
8602b10b3d5a53f7e0352c720d62a8d6e578b843 [XrdCeph] Update submodule.

**Comment by simonmichal** [comment]
I just tagged `v4.12.5-rc2`, we would like to fast track the procedure and cut the final release tomorrow. Please let me know in case there is a show stopper!

**Comment by simonmichal** [comment]
The XRootD 4.12.5 bugfix release has been tagged. Please follow the link below for more details:
http://xrootd.org/2020/10/16/announcement_4_12_5.html

Sincerely,
Michal
