### ISSUE TITLE
macOS Catalina: failure linking libXrdHttpUtils "not an allowed client"

### ISSUE THREAD

**Issue by Axel-Naumann** [xrootd/xrootd#1302]
Hi,

We have a couple of reports
https://root-forum.cern.ch/t/building-root-on-macos-catalina-10-15-3/37977/6
https://root-forum.cern.ch/t/problems-compiling-root-6-22-02-on-mac-os-catalina-10-15-6/41786

```
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [src/libXrdHttpUtils.1.0.0.dylib] Error 1
```

Is that something we should fix on ROOT's side?

Cheers, Axel.

**Comment by simonmichal** [comment]
@Axel-Naumann : thanks for reporting this problem, I'll have a look!

**Comment by simonmichal** [comment]
@Axel-Naumann : I think this is done intentionally by Apple, if I do `strings /usr/lib/libcrypto.dylib` on `Catalina` I see:
```
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```
we are building XRootD against openssl installed from brew, you can force `cmake` to pick up correct dependencies using following options:
```
-D OPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2t/include/  \
-D OPENSSL_SSL_LIBRARY=/usr/local/Cellar/openssl/1.0.2t/lib/libssl.dylib  \
-D OPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl/1.0.2t/lib/libcrypto.1.0.0.dylib
```
(the actual path come from our buildnode and might vary)

Let me know if this helps!

**Comment by simonmichal** [comment]
@Axel-Naumann : is this still a problem?

**Comment by Axel-Naumann** [comment]
Several people have reported it. But it looks like the newest macOS, newest Xcode solves it: https://root-forum.cern.ch/t/building-root-on-macos-catalina-10-15-3/37977/13

Let's close.

**Comment by nsmith-** [comment]
This stackoverflow post claims the root cause is a CMake bug: https://stackoverflow.com/a/62063357/12657814 and suggests the workaround:
```diff
diff --git a/cmake/XRootDFindLibs.cmake b/cmake/XRootDFindLibs.cmake
index 532c8ce1c..de71c6613 100644
--- a/cmake/XRootDFindLibs.cmake
+++ b/cmake/XRootDFindLibs.cmake
@@ -34,6 +34,13 @@ endif()
 find_package( CURL )

 if( ENABLE_CRYPTO )
+  if (APPLE)
+      # This is a bug in CMake that causes it to prefer the system version over
+      # the one in the specified ROOT folder.
+      set(OPENSSL_ROOT_DIR ${OPENSSL_ROOT_DIR} /usr/local/opt/openssl@1.1)
+      set(OPENSSL_CRYPTO_LIBRARY ${OPENSSL_ROOT_DIR}/lib/libcrypto.dylib CACHE FILEPATH "" FORCE)
+      set(OPENSSL_SSL_LIBRARY ${OPENSSL_ROOT_DIR}/lib/libssl.dylib CACHE FILEPATH "" FORCE)
+  endif()
   find_package( OpenSSL )
   if( OPENSSL_FOUND )
     add_definitions( -DHAVE_XRDCRYPTO )
```
which worked on my machine (assuming brew install path)
