### ISSUE TITLE
Can not find the configuration file for xrootd

### ISSUE THREAD

**Issue by MasudulHasan** [xrootd/xrootd#1308]
I am trying to edit the configuration file for xrdcp to check the integrity verification option. Unfortunately, I can not find/locate the configuration file for xrootd. I found some documentation that suggests it is supposed to be in **/opt/xrootd** but on my machine, I don't find any folder in this location.

**Comment by abh3** [comment]
You really need to create your own configuration file using the available documentation. Please tell me which documentation mentions /opt/xrootd as this is outdated and no longer applicable. In the source tree, you will find sample configuration file in "xrootd/packaging/". Files ending with ".cfg" are sample configurations are are by no means complete.

**Comment by adriansev** [comment]
@MasudulHasan for client configuration `~/.xrootd/client.conf` is processed additionally to `/etc/xrootd/client.conf`. As far i can tell the locations are _not_ configurable

**Comment by abh3** [comment]
This has been resolved.
