### ISSUE TITLE
XrdTpc: Use AIO interface when available

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1312]
On systems that support AIO (and have a high cost for synchronous IO -- for example, if there's no OS page cache that is causing synchronous IO to have the performance of async), we could pick up some performance benefits from using the AIO write interfaces.

**Comment by bbockelm** [comment]
Note: while still relevant, this is less important after #1310, which ensures that the size of each filesystem IO operation is at least 1MB.

**Comment by abh3** [comment]
This is true but esoteric, hence I am designating you as the assignee.

**Comment by bbockelm** [comment]
Hi @abh3 -

Actually, should we just close for now?  I don't think we realistically have effort to tackle this currently.  No need to have issues open and cluttering up the interfaces that aren't being worked on.  At any point in the future where we think this becomes pressing, it's very inexpensive to reopen.

Brian

**Comment by abh3** [comment]
Closing until the need arises.
