### ISSUE TITLE
TLS config and HTTP TPC

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1323]
In HTTP TPC, it seems I have to set http.cadir, and can't depend on "xrd.tlsca certdir" directive. This issue seems to only exist in HTTP TPC, not other HTTPs operations.

**Comment by bbockelm** [comment]
Hi @wyang007 -

Indeed, it looks like @abh3's overhaul of the OpenSSL handling inside XrdHttp for XRootD5 converted over almost everything to `xrd.tlsca`.

A quick grep reveals the following still refer to the old-style configs:

- https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/xrootd-http-rdr.cf#L14 (just a sample config file)
- https://github.com/xrootd/xrootd/blob/master/src/XrdTpc/XrdTpcConfigure.cc#L49 (the issue you note)

Brian

**Comment by olifre** [comment]
That's already reported in #1248, but that report missed the sample config file ;-).

**Comment by wyang007** [comment]
Thanks Oliver. It looks like we lost track of it…

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 11/9/20, 1:54 PM, "Oliver Freyermuth" <notifications@github.com<mailto:notifications@github.com>> wrote:


That's already reported in #1248<https://github.com/xrootd/xrootd/issues/1248>, but that report missed the sample config file ;-).

**Comment by abh3** [comment]
Yes, we still recognize the old-style directives and honor them. If they 
override teh new-style directives and you haven't indicated that it was 
your intention to do so, a warning is issued to give you incentive to 
change the config file. Otherwise, it should work as before.

Andy

**Comment by bbockelm** [comment]
> Otherwise, it should work as before.

I don't think that's what @wyang007 was asking.  He and Oliver are noting there is one place (https://github.com/xrootd/xrootd/blob/master/src/XrdTpc/XrdTpcConfigure.cc#L49) in the code that does not honor the new-style directives.  It seems it was simply an oversight, probably because that source file is in a different directory?

**Comment by xrootd-dev** [comment]
Ah, that is corerct. I did not pay attention to XrdTpc at all, especially 
since it was changing often. The question is whether than should be 
realigned for 5.0.3 or can wait for 5.1.0.

Andy

**Comment by wyang007** [comment]
I view this as a minor bug so 5.0.3 is preferred.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 11/9/20, 2:39 PM, "xrootd-dev" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah, that is corerct. I did not pay attention to XrdTpc at all, especially
since it was changing often. The question is whether than should be
realigned for 5.0.3 or can wait for 5.1.0.

Andy
