### ISSUE TITLE
Need checksum error reporting for pgread/write 

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#1327]
The client should report how many pages had checksum errors that could be corrected in the async response to pgRead/pgWrite.

**Comment by simonmichal** [comment]
@abh3 : I just pushed 292a14020cef4870411d2ef1b82ab6af48f11453, now in you will have `PageInfo::GetNbRepair()` method that will give you the number of corrected pages.

Can we close this issue?

**Comment by abh3** [comment]
Hi Michal,

Yes, you can close it. Now, of course, I need to integrate it.

Andy
