### ISSUE TITLE
Ver32C return code

### ISSUE THREAD

**Issue by smithdh** [xrootd/xrootd#1332]
In XrdOss/XrdOss.cc (current head 8db3054), XrdOssDF::pgWrite:

```
228:       if (!XrdOucCRC::Ver32C((void *)buffer, wrlen, csvec, valcs))
229:          return -EDOM;
230:      }
```

There are several overloaded versions of Ver32C, but I believe this one returns the index of the first mismatching checksum, so the check on line 228 is not general enough to catch all mismatches, probably it should be >= 0.

**Comment by abh3** [comment]
Hi David,

Correct! Thank you. If you want to get credit for this could you create a 
pull request with the change? Otherwise, I can change it but then your 
obervation gets lost.

Andy

**Comment by smithdh** [comment]
Hi Andy,

OK. I'll open a PR (in a few minutes) - not because it's an issue of wanting credit, but I guess it's a better tracked process, a place to review before merge etc.

David

**Comment by abh3** [comment]
Thanks David. Actually, I've already reviewed it and you are correct 
(assuming the patch will be the expected one). I am big on giving credit 
where it's due. In github this is the only way of doing it publicly which 
I am a big fan of. Anyone who corrects a bug should be the one that 
gets credit for it! Yes, for more involved patches, this is the only way 
of doing a review but it is still relevant to IP recognition.

Andy

**Comment by smithdh** [comment]
Opened PR #1333. Will close this issue.

Thanks,
David
