### ISSUE TITLE
can we export XRDLCLROOT when N2N lib is used?

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1341]
In https://github.com/xrootd/xrootd/blob/master/src/XrdOuc/XrdOucN2NLoader.cc#L60, XRDLCLROOT is exported where there is no N2N library to load, but is not exported when a N2N library is in use. 

Is there a reason to not export XRDLCLROOT when a N2N library is used? Can we export XRDLCLROOT in all cases?

**Comment by abh3** [comment]
Well, the reason XRDLCLROOT is not exported when an N2N is used is because 
it may not relevant. The N2N makes it's own translation and whether or 
not it uses localroot is not known. So, if the N2N actually does use 
localroot in the "common" way, it should export it.

**Comment by wyang007** [comment]
I found that In XrdOucName2Name::lfn2pfn(), the returned pfn has to include localroot otherwise it won't work.

**Comment by abh3** [comment]
Could you give me more context here? There is no requirement for lfn2pfn to include localroot and many do not.

**Comment by wyang007** [comment]
For example, I have the following in xrootd config:

all.export /data
oss.localroot /tmp

For a test, I use an dummy N2N that does nothing but return a pfn=lfn. When user access this file /data/myfile, xrootd will call XrdOucName2Name::lfn2pfn(lfn=/data/myfile, pfn, len).

If I return pfn=/data/myfile, xrootd will tell user that the file is not found / can not open. If I return pfn=/tmp/data/myfile, then everything will be OK.

**Comment by abh3** [comment]
OK, but you wrote the N2N so you know that you will be using the localroot. When the plugin gets loaded you are told what the localroot is set to. So, use that information. See XrdOucName2Name::XrdOucgetName2Name and just follow the recipe.

**Comment by wyang007** [comment]
Indeed that is what I need. Thanks!

**Comment by wyang007** [comment]
close
