### ISSUE TITLE
Fix in case of nstreams = 0 in TPC via http

### ISSUE THREAD

**Issue by snafus** [xrootd/xrootd#1347]
In FTS transfers for TPC transfer via xrootd it is possible (for some reason) for the number of streams to be defined as 0.
In a previous attempt to fix this the streams_req variable should have been set to 1. Unfortunately it appears there was a typo in the statement in the original fix.
The PR #1339, fixes that typo.
@bbockelm helped identify the issue, and might wish to add any further relevant information.

Kind regards,
James Walder

**Comment by abh3** [comment]
I believe this was fixed.
