### ISSUE TITLE
Include the submodules in the source tarballs published at xrootd.org

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#1354]
The source tarballs published at xrootd.org, e.g.
https://xrootd.slac.stanford.edu/download/v5.0.3/xrootd-5.0.3.tar.gz
do not include the code from the submodules.
Would you consider adding the submodules to the published source of future releases?
The attached script would generate such a tarball. E.g.

./get-src.sh v5.0.3

will create a xrootd-5.0.3.tar.gz that contains the submodules. (Added .txt extension since .sh was not allowed)

[get-src.sh.txt](https://github.com/xrootd/xrootd/files/5658582/get-src.sh.txt)

**Comment by simonmichal** [comment]
@ellert : sure it shall be done

**Comment by ellert** [comment]
@simonmichal : Did you intend for the just published 4.12.6 to contain the submodules? It does not.

$ find xrootd-4.12.6/src/XrdClHttp/ xrootd-4.12.6/src/XrdCeph/
xrootd-4.12.6/src/XrdClHttp/
xrootd-4.12.6/src/XrdCeph/

**Comment by simonmichal** [comment]
@ellert: no actually cut first `4.12.6` and then went to my todo list for `5.1.0`, but that's ok, this is just a small bug fix release for EOS (they don't care about the tarball).
