### ISSUE TITLE
pid file(s) created even if specified in command line

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1357]
-s argument should disable the automatic creation of _another_ set of pidfiles;
moreover if -b is _not_ specified no pidfiles should be created unless specified with -s

**Comment by abh3** [comment]
Well, it never  worked that way and I don't know if we would simply be creating an incompatibility by doing so. What is the administrative downside of creating pid files?

**Comment by adriansev** [comment]
well, there are two cases : 
* -b (user/by hand management) : one will for sure specify -s .. is specified, why create another pid file? is confusing (of course if -s is missing then do the default in /tmp (or in TMPDIR if set))
* -b *IS NOT USED*, that means that the service management is done a management framework like systemd. while systemd supports the management of services that do the forking (-b in our case) but it requires the specification of the exact path of pidfile within the service unit, the recommended way is to run the service in foreground as systemd will take care of all descriptors, lifetime of service, including the status of service (can do restart if service is dead, etc..).. so the creation of pidfiles is more than useless...

in the end, the simple proposition is: do not create pidfile unless '-b' AND NOT '-s'

**Comment by adriansev** [comment]
oh, i did not answer the question: it bring confusion, they should not create problems directly ... why create them if not requested by administrator?

**Comment by abh3** [comment]
OK, as annoying as it is the behavior does not cause any harm and the specified pid file is still created (along with the default one). Fixing this would not be trivial to fix and given that the extra pid files are merely annoying the effort would not be worth it. So, I am closing this as won't fix.
