### ISSUE TITLE
export path/local root resolving order

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1358]
If localroot and the export path is specified the resolved path is
LOCALROOT/EXPORT_PATH instead of EXPORT_PATH/LOCALROOT .. is this expected?

while LOCALROOT is defined as the location where filesystem is rooted
the mechanics is that the xrootd append LOCALROOT to any file request

so, IMHO, actually this LOCALROOT should be relative to what path is actually
exported, so if i export /DATA01 then requests should go to
/DATA01/LOCALROOT ... do i miss something here?

**Comment by abh3** [comment]
Local root is where LFN's are rooted in the file system. By definition and since xrootd was written decades ago, the file must reside in <localroot>/lfn. If that is not what is wanted there is a LFN to PFN mapping plugin that one can write and loaded to change that mapping.

**Comment by adriansev** [comment]
@abh3 i understand what you are saying, but why would the export path be added AFTER local root?
in my case i had an legacy localroot of /home/aliprod/data and i tried to export /storage01
the end result was that the actual seen path was /home/aliprod/data/storage01 and i know this because it was reported by xrootd that it sees a 400gb size export instead of the 30 TB that /storage01 has...

**Comment by adriansev** [comment]
@abh3 So, i would like to have a clear picture of the interplay of export, localroot and namelib name2name declarations.
So, AFAIU the name2name setting prepend to the queried path the site level setup of name2name (and maybe remove it if found in the path?) so this is a somehow external way to re-base all accesses to a certain path.
Now, the problem is with export and localroot ... AFAIU the localroot is used when using oss.space declaration to gather together all physical space into a single symlink based namespace. but if i want to just export a single mount point  the oss.space is not used, so the localroot should be similarly not used and i would expect to just `all.export /my_single_mountpoint` , the problem in this case is that name2name is prepended to `/my_single_mountpoint` instead of appended. My strong suspicion is that i do not understand what `all.export` means and that it does not refer to a physical path. So, could you please shed some light on this, and what is the way use a single mountpoint?
Thank you!
