### ISSUE TITLE
cmsd becomes inoperable after thread limit is hit

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#137]
If a thread limit is hit, the cmsd stops functioning until the process is restarted.  This has resulted in us having to continually increase the thread limits - the regional redirector cmsd in the US is currently at a limit of 200k threads.

It would be acceptable if the cmsd queues requests, just silently drops them, or returns an error message.  However, the current behavior (functionality permanently stops) is a bit too painful.

**Comment by efajardo** [comment]
Hi @abh3 ,

Is the plan to have this in 4.2.2?

**Comment by abh3** [comment]
Yes,

All of the patches in git head should be included in 4.4.2.

Andy

**Comment by gerardba** [comment]
Hi,

what xrootd version contains the bugfixes for this problem?

thanks,
 Gerard

**Comment by efajardo** [comment]
Hi @gerardba ,

AFAIK this shoud all be included in the current version that is in the osg repos 4.2.3
