### ISSUE TITLE
xrdgsiproxy ignores X509_USER_PROXY environment variable

### ISSUE THREAD

**Issue by kpedro88** [xrootd/xrootd#1370]
In the source for `xrdgsiproxy`, the default proxy file path is hardcoded: https://github.com/xrootd/xrootd/blob/24b89dbf91dbf170a1f97fd21825c9f332dd1d6a/src/XrdSecgsi/XrdSecgsiProxy.cc#L108

However, the globus tools generally recognize the value of `$X509_USER_PROXY`, overriding the default path.

Can similar behavior be added to `xrdgsiproxy`?

**Comment by abh3** [comment]
Having a quick look, gsi already recognizes X509_USER_PROXY when set.

**Comment by kpedro88** [comment]
Could you point out exactly where this is recognized? Right now, if I run `xrdgsiproxy info`, it returns an error: `proxy file: /tmp/x509up_u***** not found`. My `X509_USER_PROXY` is set to a different location than `/tmp`.

**Comment by abh3** [comment]
The envar XrdSecGSIUSERCERT takes precedence over X509_USER_CERT. Is that 
envar set? If so, the X509_USER_CERT one is ignored.

**Comment by kpedro88** [comment]
I get the same error from `xrdgsiproxy info` after `export XrdSecGSIUSERCERT=$X509_USER_PROXY`.

Maybe this behavior has been updated in a newer version? I currently have v4.12.3.

**Comment by xrootd-dev** [comment]
Hi Kevin,

No, 4.12.3 has that code there. So, could set the envar
XrdSecDEBUG=3
and try the test where is failed even when the proxy cert location was 
specified? Then send it to me as I don'tthink you want to necessarily 
publicly post it.

Andy

**Comment by kpedro88** [comment]
Both of these had the same output as before (i.e. no additional information appeared):
```
export XrdSecDEBUG=3
xrdgsiproxy info
```
```
XrdSecDEBUG=3 xrdgsiproxy info
```

I think this must be a problem specific to `xrdgsiproxy`.

**Comment by abh3** [comment]
Hi Kevin,

If no additional information appeared then the gsi security plugin was 
never loaded. That can only happen if the server you contacted was not 
setup to do gsi security. Do you know how the server was configured?

Andy

**Comment by gganis** [comment]
Hello,
Sorry for the late input, I have just saw this thread.

As shown by the man or help pages, xrdgsiproxy controls the proxy file location via the switch -f .
In particular this works:
 $ xrdgsiproxy -f $X509_USER_PROXY init
Enter PEM pass phrase: ...

which sorts of reproduces the looked-for behaviour.

Gerri

**Comment by abh3** [comment]
Thanks for the input. Indeed, that is true. The issue here was that the envar was being set manually with no effect. However,  it would seem that the sever wasn't interested in using gsi in the first place. I am waiting for confirmation on that observation.

**Comment by kpedro88** [comment]
This is what I was told by our system administrators:
> the xrootd redirectors just pass the proxy to the underlying storage for authentication/authorization

However, it's not clear to me that this actually has any impact on the problem that I reported. I think that `xrdgsiproxy` should be aware of the `X509_USER_PROXY` environment variable regardless of any other server setting.

**Comment by abh3** [comment]
Let say this again, the gsi plugin does use X509_USER_PROXY environment variable should it be set absent of the corresponding XrdSecGSIUSERPROXY envar. This is documented in https://xrootd.slac.stanford.edu/doc/dev50/sec_config.htm#_Toc56021428
If the server is not requesting gsi authentication than the setting has no bearing. So, this already works the way it supposed to work if the server wants to use gsi authentication.

**Comment by abh3** [comment]
We seem not to be getting anywhere here. As I said gsi accepts the X509_USER_PROXY environment variable so we don't see a problem with the software. I am about to close this as it seems like a configuration issue.
