### ISSUE TITLE
Timestamp precision for SSI client logs

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#1379]
XRootD client log messages have a timestamp with microsecond precision. However, the SSI log messages only have second precision. Example:
```
|201210 12:47:51 12355 T 0#0 Ssi_TaskKill: Status=isDone defer=True mhPend=False |
|201210 12:47:51 12355 T 0#0 Ssi_TaskReqFin: Task removal deferred. 201210 12:47:51 12355 T 0#0 Ssi_TaskXeqEnd: Calling TaskFinished; mhPend=False defer=True |
|201210 12:47:51 12355 S 0# Ssi_RelTask: Deleting task=0x1b66200 id=0 201210 12:47:51 12355 S 0# Ssi_Unprovision: Closing /ctafrontend |
```
Andy said:
> those messages can get high precision, I just didn't expose a mechanism to turn that on. You get a choice, a settable call that you can use during initialization or an envar, when set, turns on high precision.

Either of these options would be fine, the environment variable is probably slightly preferable as it doesn't require changing any code.

Thanks!

**Comment by abh3** [comment]
Done. On the server size you need to use the -z command line option. On the client side you can do it in one of two ways:
a} Use the "hiResTime" option with XrdSsiProvider::SetConfig()
b) Set the envar XRDSSI_HIRESLOG to any value (it's immaterial).
