### ISSUE TITLE
Xcache failure after file is fully cached (5.1.0rc4)

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1381]
It seems Xcache works when the file isn't fully cached, but once it is fully cached (or perhaps after .cinfo is updated), I got a read only file systems error. This is with xrootd 5.1.0rc4. The following is a repeated xrdcp of the same file from a Xcache

$ xrdcp -f root://dtn01.nersc.gov:46750//root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/atlasdatadisk/rucio/mc16_13TeV/72/7f/log.23681514._000288.job.log.tgz.1 /dev/null
[3.23MB/3.23MB][100%][==================================================][3.23MB/s]  
$ xrdcp -f root://dtn01.nersc.gov:46750//root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/atlasdatadisk/rucio/mc16_13TeV/72/7f/log.23681514._000288.job.log.tgz.1 /dev/null
[3.23MB/3.23MB][100%][==================================================][3.23MB/s]  
$ xrdcp -f root://dtn01.nersc.gov:46750//root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/atlasdatadisk/rucio/mc16_13TeV/72/7f/log.23681514._000288.job.log.tgz.1 /dev/null
[3.23MB/3.23MB][100%][==================================================][3.23MB/s]  
$ xrdcp -f root://dtn01.nersc.gov:46750//root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/atlasdatadisk/rucio/mc16_13TeV/72/7f/log.23681514._000288.job.log.tgz.1 /dev/null
[3.23MB/3.23MB][100%][==================================================][3.23MB/s]  
$ xrdcp -f root://dtn01.nersc.gov:46750//root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/atlasdatadisk/rucio/mc16_13TeV/72/7f/log.23681514._000288.job.log.tgz.1 /dev/null
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3025] read-only file system (source)

I attached the corresponding xrootd log file.
[xrd.log](https://github.com/xrootd/xrootd/files/5810243/xrd.log)

**Comment by osschar** [comment]
I see in the log that you are using a shared file system with potential local access. Is this true?
[ See LocalFilePath calls in the log.]

I sort of remember Andy was changing something with file permissions in this case relatively recently.

I'm not sure if it matters ... is xrdcp local, i.e., running on the same machine as xcache?

Can you also check the actual file / directory permissions in the localroot. Can you read the file as xrootd user (or whatever xcache is running as)?

**Comment by wyang007** [comment]
You are right. it is that pss.dca option. so when the xcache run at NERSC and xrdcp run at SLAC, it won't work. I forgot about this. 

closing this ticket.

**Comment by osschar** [comment]
Well, Andy implemented this so I don't know the details how it's supposed to work. Maybe there is a way to make it work for remote clients as well ... maybe it would need to be a two-stage process, like:
1. server says: try file:/lustre/somewhere/xxx.root
2. client says, nope, can't do, give me data!
3. xcache serves the file as it normally would

**Comment by wyang007** [comment]
Well, I requested that feature so I know that it does (it redirects reading of a fully cached file to shared filesystem as a cheap way to take the advantage of RDMA on HPCs)

We just have lots of features to remember :--) Thanks for the hint

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 1/13/21, 11:26 AM, "Matevž Tadel" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, Andy implemented this so I don't know the details how it's supposed to work. Maybe there is a way to make it work for remote clients as well ... maybe it would need to be a two-stage process, like:

  1.  server says: try file:/lustre/somewhere/xxx.root
  2.  client says, nope, can't do, give me data!
  3.  xcache serves the file as it normally would
