### ISSUE TITLE
CRL is not considered for HTTP-TPC

### ISSUE THREAD

**Issue by vokac** [xrootd/xrootd#1383]
When XRootD act as active party in the HTTP-TPC it doesn't verify if remote site certificate (+ CAs certificates in the chain) is valid with respect to CRLs. This means XRootD is happy to establish TLS connection with storage endpoint with revoked certificate and e.g. sent there valid tokens.

**Comment by abh3** [comment]
This actually should be happening as lincurl is used to connect to the SE and, by default, libcurl verifies the certificate. So, I am closing ticket. Please reopen if this is not so but we have set i up so it should be the case.
