### ISSUE TITLE
pip install does not work with virtual environment

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1397]
As reported by @nikoladze in #1377 :

However, the case where i originally found the issue was installing in a virtual environment. I didn't know this would make a difference, but apparently this is still a problem:

```
$ docker run --rm -it python:3.8-buster bash
$ apt-get update && apt-get -y install cmake
$ python3 -m venv test-venv
$ source test-venv/bin/activate
$ pip install wheel
$ pip install --index-url https://test.pypi.org/simple/ xrootd==7.7.20
$ python
>>> import pyxrootd.client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyxrootd.client'
```

The `client.<something>.so` file seems missing:
```
$ ls /test-venv/lib/python3.8/site-packages/pyxrootd/
include  lib  share
```

For comparison when installing globally (not in venv) the folder looks like this:
```
$ ls /usr/local/lib/python3.8/site-packages/pyxrootd
_init__.py  __pycache__  client.cpython-38-x86_64-linux-gnu.so  include  lib  share
```

Also, the `XRootD` module folder is missing when installing in the venv.

It is maybe worth noting that during installation pip tries to install via "wheel" and then falls back to setup.py install. In newer versions there is this warning: "DEPRECATION: Could not build wheels for xrootd which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality."
I don't really know much about the different ways to make python packages, but maybe this should be kept in mind since it sounds like it could break the package again in the future.

**Comment by simonmichal** [comment]
Additional observations:

the `client.cpython-38-x86_64-linux-gnu.so` gets actually installed outside of the environment:
`/usr/local/lib/python3.8/site-packages/pyxrootd/client.cpython-38-x86_64-linux-gnu.so`

**Comment by dcervenkov** [comment]
@simonmichal Has there been any progress on this issue?

As a workaround, one can simply copy `XRootD` and `pyxrootd` dirs from the non-venv `site-packages` to the venv `site-packages`. Still, breaking out of a virtual environment and messing up the global python install is a serious issue.

**Comment by simonmichal** [comment]
@dcervenkov : sorry I haven't had time yet to fix it, but it is scheduled for the next release!

**Comment by dcervenkov** [comment]
@simonmichal Sure, I understand. Is there a tentative ETA for the next release?

**Comment by simonmichal** [comment]
@dcervenkov : we would like to have one by the end of April

**Comment by simonmichal** [comment]
@dcervenkov & @nikoladze : it should be fix now, could you give it a try: (test-venv) root@3a7a35a58342:/# pip install --index-url https://test.pypi.org/simple/ xrootd==5.1.1.post2

**Comment by adriansev** [comment]
@simonmichal following the exact recipe of @nikoladze the installation was successful and i got this:
```
(test-venv) root@aae4b952ab9f:/# python
Python 3.8.9 (default, Apr 10 2021, 15:47:22)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from XRootD import client
>>> print(client.__file__)
/test-venv/lib/python3.8/site-packages/XRootD/client/__init__.py
```

**Comment by simonmichal** [comment]
@adriansev : thanks a lot for testing :-) I suppose we can close this one.

**Comment by nikoladze** [comment]
I can also confirm it works, both in the docker container and on my laptop environment. Thanks a lot! This will make life much easier - i had a few setups where a simple python venv would have been sufficient, but i had to install conda because of xrootd.

**Comment by dcervenkov** [comment]
@simonmichal This is great, thanks a lot! I can also confirm that it works.

**Comment by simonmichal** [comment]
@nikoladze & @dcervenkov : thanks a lot guys for testing!
