### ISSUE TITLE
XrdHttpReq truncates header value for the 'Range' header

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#1399]
```
XrdHttpReq::parseLine
```
makes all HTTP headers visible in a map, which can be used by external plug-ins.

The decoding function for range requests uses strtok_r, which writes a \0 bytes into the string. 

Afterwards we assign the range value in the external header map, so that instead of seeing:

allheaders["Range"] = "bytes=2-8" 

we see only

allheaderes["Range"] ="bytes"

which breaks range requests in external plug-ins.

The simple solution is to move
```
 // We memorize the heaers also as a string                                                                                                                                              
    // because external plugins may need to process it differently                                                                                                                          
    std::string ss = val;
    trim(ss);
    allheaders[key] = ss;
```
before all the header key parsing is called ...

**Comment by ffurano** [comment]
Makes a lot of sense indeed, as the eos plugins need to process autonomously these things
