### ISSUE TITLE
python stalls with ProcessPoolExecutor and multiprocessing when using xroot_glob

### ISSUE THREAD

**Issue by asnaylor** [xrootd/xrootd#1405]
Original made a git issue https://github.com/scikit-hep/uproot4/issues/224 with uproot as i thought it could be uproot and xrootd clashing but after discussing with Jim Pivarksi at uproot, he determined simply calling `glob` was putting XRootD into a state which determines where it hangs or not and it was not related uproot. 

Jim created a minimally reproducible example with 8 test cases (see code below). The only two test cases which hang is when using `glob` from `XRootD.client.glob_funcs` and either using `ProcessPoolExecutor ` or `multiprocessing`.

|  | `ProcessPoolExecutor ` | `ThreadPoolExecutor ` | `multiprocessing` | `threading` |
| --- | --- | --- | --- | --- |
| **`XRootD.client.glob_funcs.glob`** | 🚫  (hangs) | ✅ | 🚫 (hangs) | ✅ |
| **no glob** | ✅ | ✅ | ✅ | ✅ |

```python
import XRootD.client
from concurrent import futures
import threading
import multiprocessing
from XRootD.client.glob_funcs import glob

def simple_func(input_path, tree):
    file = XRootD.client.File()
    status, _ = file.open(input_data[0])
    print(status)

    status, some_raw_bytes = file.read(0, 100)
    print(status)
    print(some_raw_bytes)

    status, some_raw_bytes = file.read(100, 200)
    print(status)
    print(some_raw_bytes)

    return "yay"

# Call it and forget about it.
glob("root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root")

input_data = ["root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root"]
tree = 'Events'

which_test = "multiprocessing"

if which_test == "ProcessPoolExecutor":
    with futures.ProcessPoolExecutor(max_workers=1) as executor:
        future = executor.submit(simple_func, input_data[0], tree)
        print(future.result())

elif which_test == "ThreadPoolExecutor":
    with futures.ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(simple_func, input_data[0], tree)
        print(future.result())

elif which_test == "multiprocessing":
    class MyProcess(multiprocessing.Process):
        def run(self):
            print("before")
            print(simple_func(input_data[0], tree))
            print("after")
    myprocess = MyProcess()
    myprocess.start()
    myprocess.join()

else:
    class MyThread(threading.Thread):
        def run(self):
            print("before")
            print(simple_func(input_data[0], tree))
            print("after")
    mythread = MyThread()
    mythread.start()
    mythread.join()
```

Tested with versions:
```
python==3.8.5
xrootd===5.0.3-
```

**Comment by simonmichal** [comment]
Thanks for reporting the problem and for the test cases!

**Comment by simonmichal** [comment]
@asnaylor : sorry for the delay, so the problem is you haven't enabled the fork handler that initialises the client runtime in the new process

Could you try setting: `export XRD_RUNFORKHANDLER=1` before running the script, this should fix the problem.

**Comment by simonmichal** [comment]
I enabled the fork handler by default: 801a020b9d896f85b909d612bb832870ab148a15, this way we will avoid this problem in the future.

Could you give it try, and then if everything is fine I suppose we can close this one?

**Comment by asnaylor** [comment]
Ah perfect, tested it and it's all working now. Thanks
