### ISSUE TITLE
Xrootd stop working after update to version 4.0.0

### ISSUE THREAD

**Issue by marcelkuri** [xrootd/xrootd#141]
At the beginning of September xrootd updated to version 4.0.0. 
Since then our /atlas mountpoint do not show the data servers space. This is our /etc/fstab
xrootdfs      /atlas     fuse rw,rdr=root://lipnode01:1094//data/xrootdfs,uid=496 0 0

With "df -h" it is showed:
Filesystem           Size    Used   Avail   Use%   Mounted on
xrootdfs               1.6T    135G  1.5T     9%    /atlas

We have 3 data servers with a shared partition (oss.localroot) of 1.6 Tb each.
So "df -h" would show 1.6T x 4 = 64T. But only 1.6T is showed.

The copy command with xrdcp works.

**Comment by abh3** [comment]
Looks like this was resolved. I am closing this ticket.
