### ISSUE TITLE
Value returned by XRootDStatus::ToStr() includes an embedded NULL

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#1416]
In `XrdClXRootDResponses.hh`, method `XRootDStatus::ToStr()` :

The `std::string` returned by this method includes an extra NULL character at the end.

This causes problems with code such as the following:
```
os << status.ToStr() << " code:" << status.code << " errNo:" << status.errNo << " status:" << status.status;
```
which gives output:
```
[ERROR] Server responded with an error: [3007] Unable to read file - wrong file checksum fn= /fst/00000000/0000003e; input/output error\u0000\n code:400 errNo:3007 status:1
```
(note the extra `\u0000` after "input/output error", which causes the output to be truncated).

Please remove this unwanted NULL from the end of `ToStr()`, thanks!

**Comment by simonmichal** [comment]
Hi @slithy, thanks for reporting the problem! I think it has been already fixed in https://github.com/xrootd/xrootd/commit/22d308a3dd689607ee0396860d377145836ef55b

**Comment by slithy** [comment]
Thanks, I have implemented a workaround which will do the job until we upgrade to XRootD v5, so I'll close the ticket.
