### ISSUE TITLE
xrdfs ls :: allow listing with the same semantic as in shell

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1417]
Hi! It would be great that if ls is applied to a file to return a similar answer like in shell including for -l information on size and change time (currently for a file it responds with `[3005] Unable to open directory`)

**Comment by abh3** [comment]
Hi Adrian,

Can you provide the case that you are using to elicit this error?

Andy

**Comment by adriansev** [comment]
@abh3 any ls on a file (instead of a directory) will throw this error. the use case was to check the existence of a file without the processing of the stat output.

**Comment by xrootd-dev** [comment]
OK, I have had a chat with Michal and indeed this is a defieciency in 
xrdfs. We will likely correct that in 5.1.1 but it will not be backported.

Andy

**Comment by adriansev** [comment]
great! thanks a lot! (also i got the message with backporting and i already started a discussion with relevant persons from collaboration. it will help tremendously an official post about the support status of the 4.x branch ;) )

**Comment by simonmichal** [comment]
This: c76cc296ac5322be73f86694bc96c5d0cff06024 should do the trick.

**Comment by simonmichal** [comment]
The patch has been released in `5.1.1`.
