### ISSUE TITLE
Netlogger Format to log XRootD Transfers/Accesses

### ISSUE THREAD

**Issue by juztas** [xrootd/xrootd#1418]
Following this: https://github.com/xrootd/xrootd/issues/1049 which was done for TPC Transfers, It should be nice also to have it for xrootd based accesses (root:// https:// davs://) - I would say any xrootd access (e.g. if in future we have another protocol)

@bbockelm FYI

**Comment by bbockelm** [comment]
@juztas - how about we start with just HTTP for now?  Step up the ladder one foot at a time...

What events would you like to see?  For example, on HTTP-TPC, we have the ability to do:

1.  Transfer start.
2. Periodic transfer updates.
3. Transfer finish (success or failure).

Do you want all three for 'regular' HTTP transfers?  Is there a need to turn these on / off independently?

Do you want this only for transfers or for _all_ HTTP operations?

**Comment by juztas** [comment]
Sounds good (not sure if there is any diff between https and dav inside the code) - as CMS Start to use davs more - davs is a start :)

For ON/OFF flag - that is nice to have;

For operations: I am mainly interested in 'Transfer finish'. I use all these values (this is taken from the GridFTP example [1]) and use it to monitor failed/success transfers. This allows me to see all success, failures and by whom ;) [2]

[1]
```
DATE=20210303180254.064101 HOST=transfer-4.ultralight.org PROG=globus-gridftp-server NL.EVNT=FTP_INFO START=20210303180252.889257 USER=sixie FILE=/mnt/hadoop/store/.......... BUFFER=65536 BLOCK=1048576 NBYTES=107624 VOLUME=/ STREAMS=1 STRIPES=1 DEST=[2001:720:1C14:0:0:FFFF:C192:4B7B] TYPE=STOR CODE=226 TASKID=none retrans=0
```
[2]
![image](https://user-images.githubusercontent.com/646582/109851533-a5e89d80-7c08-11eb-8b0d-383152de20a4.png)

**Comment by abh3** [comment]
Hmmmm, let me give my two cents worth of opinion here. Netlogger is a decades old proprietary format that is not widely used. On the xroot side we've started to move to JSON for low to mid-intensive monitoring streams as this format is trivial to use with a vast number of popular collectors that are already out there. Frankly, I don't think this is a forward looking approach and further balkanizes monitoring data. At the very least, the code to generate this needs to be centralized in *one* location with a generic API so that it can be replaced with something more standard; as I suspect will happen sooner than later.

**Comment by juztas** [comment]
json, yaml, pkl, etc - fine with me. I can adapt code to parse it. The only requirement from my side is it to provide the minimum same information that I get on Gridftp and all params, mainly DATE, SOURCE, DEST, ACCESSTYPE, USER, FILENAME, EXITSTATUS

**Comment by bbockelm** [comment]
I guess I think NetLogger less as a "format" and more as semi-structured log with the information all in one place.  That is, something that a human can read through -- but can also grep through and can send to other places.

JSON is a good transport format if all you do is upload to some monitoring system.  If I'm logged in to a system and trying to debug, I strongly dislike it.

**Comment by abh3** [comment]
Agreed, it's not great when debugging though there are several interactive web sites that will do that for you. I use those a lot. I just think most of the world has pretty much settled on this format for the foreseeable future. Given you can feed elastic search and many other collectors/visualizers by simply giving them the schema makes it pretty much the go-to format. As for Netlogger, sure if you want to grep log files but relatively few people do that anymore; though that was De Rigueur in the day but I'm glad those days are largely gone.

**Comment by abh3** [comment]
Discussion closed because agreement reached.
