### ISSUE TITLE
client :: [zlib] inflate : corrupted data

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1422]
Hi! so i have a strange situation : for a number of files (200 tried) all on the same place (eosalice.cern.ch) i have:
Succesful copy jobs: 157/200 (within my python application)
(all the files are the same type: AliESD.root within zip archives)

the errors are reproductible and a metafile for reproducing the problem is at :
https://asevcenc.web.cern.ch/asevcenc/xrdzip_corrupt_data/

the same meta can be used for download the archive as well as the file
(the commands are in commands.txt)
and xrdcp_file and xrdcp_xip are the dump logs for file from archive and archive download

to have a reproductible common ground i used the system xrdcp which is 5.1.0 (on fedora 33)

I get the same errors also in my application with the python bindings installed by hand (the top of stable-5.1.x 60f46d5c3) 
Any idea what is going on?
Thanks a lot!!!

**Comment by simonmichal** [comment]
@adriansev : sorry for the delay! The issue should be fix now with following commits: 04eb74a15857d62520e3a2cbc3260beca6684c51, 11f4ef78709c9b81d0b13e629125348eaf96c1aa and 3011213e3ee6a71bba1958ca7d5f6928f5c31c4b

There were actually two problems:
- the client was not correctly handling the `data descriptor` record present at the end of file
- this particular example is a corner case where the compressed size is slightly bigger then the uncompressed size:

```
zipinfo -v 66b0b4b0-c27c-11e8-82d6-626f12b4f71d
...
Central directory entry #4:
---------------------------

  There are an extra 16 bytes preceding this file.

  AliESDs.root

  offset of local header from start of archive:   75869382
                                                  (000000000485ACC6h) bytes
  file system or operating system of origin:      MS-DOS, OS/2 or NT FAT
  version of encoding software:                   2.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   2.0
  compression method:                             deflated
  compression sub-type (deflation):               normal
  file security status:                           not encrypted
  extended local header:                          yes
  file last modified on (DOS date/time):          2018 Sep 27 19:40:16
  32-bit CRC value (hex):                         c9faa31d
  compressed size:                                27764158 bytes
  uncompressed size:                              27759918 bytes
  length of filename:                             12 characters
  length of extra field:                          0 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  non-MSDOS external file attributes:             000000 hex
  MS-DOS file attributes (00 hex):                none

  There is no file comment.
...
```

Note:
  **compressed size:                                27764158 bytes
  uncompressed size:                            27759918 bytes**

Now also this corner case should be handled correctly!

Could you give it a try before I close the ticket?

**Comment by adriansev** [comment]
@simonmichal unfortunately no joy .. see [xrdzip_corrupt_data/try2](https://asevcenc.web.cern.ch/asevcenc/xrdzip_corrupt_data/try2/)   
my app report correctly :  
```
XRootD version: 20210401-3011213e3
XRootD path: /home/adrian/.local/lib/python3.9/site-packages/XRootD/client/__init__.py
```
the actual command line client xrdcp i cannot test as i'm not sure if i can correctly rebuild the srpm on fedora 33
do you spot in the xrdlog anything weird?
Thank you!

**Comment by simonmichal** [comment]
@adriansev : thanks for testing, in the XrdCl logs everything looks OK, let me give it a try!

**Comment by adriansev** [comment]
@simonmichal in fact now i see another problem: with the master (python bindings) i cannot copy the normal zip archive (the process is stuck, and when i terminated a zero file is present) but with the v5.1.1 tag the copy is succesfull

**Comment by adriansev** [comment]
so, i uploaded [here](https://asevcenc.web.cern.ch/asevcenc/xrdzip_corrupt_data/zip_download/) the copy logs between v5.1.1 (succesfull) and master (stuck, seems from strace with `read(22, 0x7f9b79e3f080, 102500244)     = -1 EAGAIN (Resource temporarily unavailable)` )

**Comment by simonmichal** [comment]
@adriansev : you are right, this is a regression I introduced earlier this week (sight), fixed: d7f340674c79a00572b71566be5c273fc090d2e4

Could you give it another try?

**Comment by adriansev** [comment]
@simonmichal i tried again (`XRootD version: 20210401-d7f340674`) and the copy process is still stuck for both the normal file (root_archive.zip) and for within archive file .. i updated the log in the `master` directory

**Comment by simonmichal** [comment]
I see what you mean, this happens only with EOS, I run my test with vanilla xrootd and it works just fine. I need to investigate bit more ...

**Comment by simonmichal** [comment]
@adriansev : should work now (20342cf0b6ea45bcee7417328427202196b2e5a2 + d4ef4edc70ef29d28f986aa7caa87e59386cfd8e), could you give it a try?

**Comment by adriansev** [comment]
I can confirm that previous unsuccessful operations (download of root_archive.zip and contained file) are now successful!! 
Can these fixes please be back-ported to 4.x branch? :D 
Thanks a lot!!

**Comment by simonmichal** [comment]
@adriansev : perfect, thanks a lot for testing! Well, `MsgHandler` class differs already significantly in 4 and 5, I will se what I can do ;-) that said I strongly encourage you to move to 5 ;-)

**Comment by adriansev** [comment]
@simonmichal well, it's up to you guys :) .. i will just forward the resolution up to the deciding factors :)

**Comment by simonmichal** [comment]
@adriansev : I'll be back from holidays on 12/04, I will let you know then if a back-port is possible.

**Comment by adriansev** [comment]
@simonmichal sure. thanks a lot! i will ping you after the holidays then, this issue i will close as it is solved. Thanks a lot!!!
