### ISSUE TITLE
Automated XRD_PARALLELEVTLOOP  settings

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#1425]
While running some high-performance benchmark of a multithreaded application on a 100GE client, 
we noticed, that although our storage endpoint can deliver 20 GiB/s, a single application was limited to ~2.5 GiB/s data input (single multithreaded application running 85% idle) (streaming many files in parallel)

After some investigation, it turned out, that setting:
env XRD_PARALLELEVTLOOP=16

allowed to run this application at 5.8 GiB/s 

This ticket is about the possibility of some automatic configuration of the eventloop size in XrdCl to avoid tweaking the settings for each environment.

**Comment by amadio** [comment]
We've just increased the default value of `XRD_PARALLELEVTLOOP` to 10, which should be enough in most situations. Should we proceed to close this ticket, or is there still the need to have a better approach which dynamically sets the number using some heuristics?

**Comment by apeters1971** [comment]
I think that is good enough.
