### ISSUE TITLE
"triedrc" is missing when XrdCl get no errNo

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1435]
In some cases XrdCl will not get an errNo. For example, when the connection and retry timeout. In that case, XRootDMsgHandler::UpdateTriedCGI() set "tried=" but does not set "triedrc=". Do we want to set "triedrc" to something?

**Comment by xrootd-dev** [comment]
Yes, we want triedrc=srverr as that's the closest approximation of the 
problem.

**Comment by simonmichal** [comment]
Wouldn't it make more sense to introduce 2 new codes say **connerr** for timeouts and **redirlim** for redirect limit?

**Comment by osschar** [comment]
What happens in such a case when triedrc=resel is already set? Does the additional code (srverr or one of the new ones) get appended, like triedrc=resel,srverr?

**Comment by simonmichal** [comment]
well, I suppose it's for us to decide ;-) currently from what I see `triedrc` has just one value.

**Comment by abh3** [comment]
The triedrc is a rather blunt approximation of what is wrong. The server uses it to determine how the selection of a new node should proceed. It doesn't much matter what the error is for server related errors, so keeping it as srverr is just fine. For ioerrs, the redirector may decide to blacklist the server for that file for a while, for enoent the redirector will refresh the cache before selecting a new node. The resel rc limits the selection process. So, I don't think it's necessary to introduce any more error codes as the ones we have are good enough. The triedrc only has to indicate the last immediate error, the redirector does not need nor use any history/ So, additional codes are never appended to the triedrc.

**Comment by simonmichal** [comment]
@abh3 : thanks for the clarification, so `srverr` it is!

**Comment by simonmichal** [comment]
That's about it: e9fb99b66ebacdc0124ad39fef8be1868e432641

I'll close this one, if there are any problems with the solution please reopen.
