### ISSUE TITLE
libcurl memory leak/crash in HTTP TPC

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1436]
We are working on resolving libcurl issues in HTTP TPC. This is a place holder requested by OSG, so info here is NOT updated.

**Comment by simonmichal** [comment]
I think this has been solved, hasn't it? Can we close the issue?

**Comment by bbockelm** [comment]
I believe so; 5.2.0 solves this to the greatest extent possible (there remains a minimum memory leak in the libnss that cannot be solved unless one switches to libcurl on RHEL8 or hand-compiles a custom libcurl).

**Comment by abh3** [comment]
This has finally been addressed in 5.3.0.
