### ISSUE TITLE
missing piece of frm documentation

### ISSUE THREAD

**Issue by dougbenjamin** [xrootd/xrootd#144]
In the last line of section " 1.1.3.2      Staging Files"  there is a link to Sample configuration files -

"Would copy a file whose name is contained in $SRC from an xrootd cluster control by the redirector redirhost to the local disk at $DST. View some of the sample configuration files to get additional ideas on how to specify the handling of stage-in copies."  

The hyper link points to a section that does not contain anything. -

5.2.3       Sample Configuration Files

To be added.

**Comment by abh3** [comment]
It's been like that for 7 years now and doesn't seem to have caused an issue. So, I will close this by saying that we deleted all references to the missing documentation to avoid confusion. I know that doesn't solve the problem you are alluding to but, frankly, as don't have time to pursue it.
