### ISSUE TITLE
xrd.protocol directive with v5.1.1-1

### ISSUE THREAD

**Issue by ycalas** [xrootd/xrootd#1444]
Hi,

With XRootD version <= 4.12.3, the directive _xrd.protocol_ in the configuration file did not trigger an error when cmsd was started. It is no more the case with XRootD 5.1.1-1: 

`210420 14:51:08 1003972 XrdConfig: the builtin protocol is 'cms' not 'xrootd'; the following protocol directive should be corrected!`
`------ cmsd grid@.xxxx:1094 initialization failed.`

This problem can be solved by adding the `if-fi` conditional directives, e.g. with: 

```
if exec xrootd
  xrd.protocol xrootd *
fi
```
I am not sure if this is a bug or if this new behavior is expected though.

Cheers,

Yvan

**Comment by abh3** [comment]
This is merely an explanation to the previous behaviour. Originally, we 
would ignore the directive and plow on. Now we tell you that we are 
ignoring the directive but still plow on.

**Comment by ycalas** [comment]
Well cmsd does not start anymore if the `if-fi` conditional directives are not used. If you think this is normal behavior, you can close ticket ;)

Thanks for your feedback.

**Comment by abh3** [comment]
Ah, got it. No, it should likely keep on going and ignore this directive. 
Could you cut a ticket for this as it's not backwardly compatible 
behaviour.

Andy

**Comment by abh3** [comment]
Oh never mind, I see you already cut a ticket. So much for my attention 
span this morning :-(
