### ISSUE TITLE
File mapping is inconsistent on the redirector.

### ISSUE THREAD

**Issue by juztas** [xrootd/xrootd#1459]
Split from: https://github.com/xrootd/xrootd/issues/1456
Running versions/configs: https://github.com/xrootd/xrootd/issues/1456#issuecomment-840891725

Andy's comment:
```
As for the mapping, I will look at that but I don't see why that should be happening. So, yes, the config file would be helpful here.
```

**Comment by abh3** [comment]
It seems that 4.12 is being used. That version does not correctly report uid/gid and version info is incomplete. That was corrected in the 5.x series.

**Comment by juztas** [comment]
Do you mean client?

**Comment by abh3** [comment]
Well, the epel stuff which is for the client and server is 4.12. I don't know what version OSG is using as  it's tagged with the OSG version number. No matter, the issue existed on both sides.

**Comment by abh3** [comment]
Is this still a problem? We haven't gotten supporting information yet to even know where to look.

**Comment by abh3** [comment]
Any updates on this or should I close this ticket?

**Comment by juztas** [comment]
There seems to be an issue with gfal, but for what concern's xrootd - I do not see this issue with 5.3.x release anymore. Closing
