### ISSUE TITLE
mkdir error during FTS 3rd party transfers

### ISSUE THREAD

**Issue by bockjoo** [xrootd/xrootd#1466]
With 5.2.0, during FTS 3rd party transfers, FTS sees "ERR     Thu, 10 Jun 2021 00:13:19 +0200; Recoverable error: [2] Result HTTP 404 : File not found  after 1 attempts"

In the xrootd server log, I am seeing mkdir error:
210609 15:57:34 1739 sysXrdHttp:  rc:2 detected header end.
210609 15:57:34 1739 XrootdBridge: cmsprod.80:99@fts-devel-09.cern.ch login as cmsprod
210609 15:57:34 1739 multiuser_UserSentry: Switching FS uid for user cmsprod
210609 15:57:34 1739 cmsprod.80:99@fts-devel-09.cern.ch sysXrdHttp:  Process. lp:0x7fcf6c081a20 reqstate: 0
210609 15:57:34 1739 cmsprod.80:99@fts-devel-09.cern.ch sysXrdHttp: Process is exiting rc:1
210609 15:57:34 1739 multiuser_UserSentry: Switching FS uid for user cmsprod
210609 15:57:34 1739 ofs_mkdir: cmsprod.80:99@fts-devel-09.cern.ch Unable to mkdir /store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13TeV-madgraph-pythia8; no such file or directory
210609 15:57:34 1739 sysXrdHttp:  XrdHttpReq::Error
210609 15:57:34 1739 cmsprod.80:99@fts-devel-09.cern.ch sysXrdHttp: PostProcessHTTPReq req: 9 reqstate: 0
210609 15:57:34 1739 cmsprod.80:99@fts-devel-09.cern.ch sysXrdHttp: PostProcessHTTPReq mapping Xrd error [3011] to status code [404]
210609 15:57:34 1739 cmsprod.80:99@fts-devel-09.cern.ch sysXrdHttp: Sending resp: 404 header len:66

The directory is created but it's just this mkdir error and this results in the error in the FTS.

**Comment by xrootd-dev** [comment]
Could you do an ls -l on

/store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13
TeV-madgraph-pythia8

and set the output. I'm suprised that the directory is actually created as 
it says it can't.

Andy

**Comment by bockjoo** [comment]
The actual directory is /cmsuf/data/store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13
TeV-madgraph-pythia8 because of mapping ( oss.namelib /usr/lib64/libXrdCmsTfc.so file:/cvmfs/cms.cern.ch/SITECONF/local/Ph
EDEx/storage.xml?protocol=direct )

So, 
[root@cmsio2 ~]# ls -l /cmsuf/data/store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13TeV-madgraph-pythia8
total 4
drwxr-xr-x 3 cmsprod cmsdata 4096 Jun  9 15:57 MINIAODSIM

**Comment by xrootd-dev** [comment]
Hi Bockjoo,

So, I at a loss unless there is a problem with the mapping. I think it's 
probably best you ask one of the cms DM people what may be wrong here as I 
am not familiar with how they sort out the paths.

Andy

**Comment by bockjoo** [comment]
There is no problem with the mapping. OK, Brian might have an idea.
By the way, if I use a specific xrootd server instead of the redirector, there is no such issue.

**Comment by bockjoo** [comment]
Although the issue is about mkdir, but I think the following reproduction of the HTTP 404 error is related.


[1] Reproduce the error HTTP 404 in gfal-ls
I set up a second redirector consisting of cmsio3 as the redirector and cmsio2 as the server.
After gfal-copy, at gfal-ls, I am getting this error with the redirector:
-bash-4.2$ gfal-ls davs://cmsio3.rc.ufl.edu:1094/store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13TeV-madgraph-pythia8/MINIAODSIM/106X_mcRun2_asymptotic_v17-v1/280000/BBE94A2B-0D62-A84B-B815-BFB214475BDF.root ; echo gfal-ls status=$?
***ERROR*** in propagateError, *newErr is not NULL impossible to overwrite ...  old error wasHTTP 404 : File not found 
gfal-ls error: 2 (No such file or directory) - Failure HTTP 404 : File not found  after 1 attempts
gfal-ls status=2
In the server, I am seeing this corresponding error:
210611 11:49:31 41154 XrootdXeq: cmsprod.43:35@cmsio6.rc.ufl.edu disc 0:00:00 (send failure)



On the other hand, with the server, gfal-ls runs fine:
-bash-4.2$ gfal-ls davs://cmsio2.rc.ufl.edu:1094/store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13TeV-madgraph-pythia8/MINIAODSIM/106X_mcRun2_asymptotic_v17-v1/280000/BBE94A2B-0D62-A84B-B815-BFB214475BDF.root ; echo gfal-ls status=$?
davs://cmsio2.rc.ufl.edu:1094/store/mc/RunIISummer20UL16MiniAODv2_TEST1/NMSSM_XtoHYto4b_MX_1900_MY_700_TuneCP5_13TeV-madgraph-pythia8/MINIAODSIM/106X_mcRun2_asymptotic_v17-v1/280000/BBE94A2B-0D62-A84B-B815-BFB214475BDF.root
gfal-ls status=0
Although it return 0 status, the server has this error:
210611 11:49:38 28792 XrootdXeq: cmsprod.6:38@cmsio6.rc.ufl.edu disc 0:00:00 (link SSL read error)
210611 11:49:38 28792 multiuser_UserSentry: Anonymous client; no user set, cannot change FS UIDs


[2] Reproduce the error HTTP 404 in gfal-mkdir  
This is mkdir test:
-bash-4.2$ gfal-mkdir davs://cmsio3.rc.ufl.edu:1094/store/mc/RunIISummer20UL16MiniAODv2_TEST2 ; echo gfal-mkdir status=$?
gfal-mkdir status=0
-bash-4.2$ gfal-mkdir davs://cmsio3.rc.ufl.edu:1094/store/mc/RunIISummer20UL16MiniAODv2_TEST3/TEST3/TEST3 ; echo gfal-mkdir status=$?
gfal-mkdir error: 2 (No such file or directory) - HTTP 404 : File not found  with url davs://cmsio3.rc.ufl.edu:1094/store/mc/RunIISummer20UL16MiniAODv2_TEST3/TEST3/TEST3
gfal-mkdir status=2

Of course, the option -p is provided with gfal-mkdir, there is no problem with creating parent directory with children directories.

However, the error "gfal-ls error: 2 (No such file or directory) - Failure HTTP 404 : File not found  after 1 attempts" goes away after 20 minutes or so later.

Anyway, I am wondering if there is some cache in the redirector that thinks there is no such file.
Is there a directive that controls this behavior?

**Comment by bockjoo** [comment]
In the redirector config file, there was this line:
cms.dfs lookup central mdhold 20m redirect verify
After chaning it to 
cms.dfs lookup central redirect verify
mkdir issue and HTTP 404 issue have disappeared.

You can close this one.
Thanks,
Bockjoo

**Comment by abh3** [comment]
Thanks for figuring it out. It makes sense that mdhold would be incompatible with http. I will add that warning to the documentation.

**Comment by bbockelm** [comment]
I don't think it's incompatible with HTTP -- it's simply having problems with the sequence of operations FTS is performing.  I believe they are something like this:

```
mkdir /foo/bar/baz # error - does not exist
mkdir /foo/bar # success
mkdir /foo/bar/baz # success
stat /foo/bar/baz # FAIL: the prior mkdir failed with "does not exist"
```

Actually - @abh3, why doesn't the `mkdir` invalidate the negative cache entry in this case?

**Comment by abh3** [comment]
Because we decided a long time ago to keep positive as well as negative 
entries in the cache as apps that were issuing repetitive requests could 
do either negative or positive operations (not a great explanation but 
one that tries to capture that the issue was on both sides of the fence). 
Atleast that's what I recall as we did that a very long time ago.

**Comment by bbockelm** [comment]
Hm - I think I'm still confused.  Are you saying there's an entry in both the positive and negative cache (as there's a mkdir in both) but the negative cache "wins"?

The nice thing about invalidation would be it captures the sequence - the fact there was a positive result after the negative result.

**Comment by xrootd-dev** [comment]
Hi Brian,

It's all documented here under mdhold:

https://xrootd.slac.stanford.edu/doc/dev50/cms_config.htm#_Toc53611070

this what we agreed upon a long time ago as this feature was specific to 
CMS at the time. At the moment there is a bypass. Whether we could 
actually capture directory activity in real time at this level to provide 
a sequence needs some research. We do that for the non-DFS case but when 
DFS is turned on a different "sequence" path is used because the 
semantics of a DFS cluster is very different from a shared nothing 
cluster.

Andy
