### ISSUE TITLE
HTTP TPC error due to empty files: .xrdtls/ca_file.pem and .xrdtls/crl_file.pem

### ISSUE THREAD

**Issue by ddavila0** [xrootd/xrootd#1467]
After updating a server to 5.2.0 I noticed some errors when trying to do a http TPC. Thanks to the help of @jthiltges we track this down to the fact that the files .xrdtls/ca_file.pem and .xrdtls/crl_file.pem were empty.

Doing some debugging I found that the reason for the above is that in my system this line:
https://github.com/xrootd/xrootd/blob/4ca38eb63e2172778d6e804593f0fe8cae65280e/src/XrdTls/XrdTlsTempCA.cc#L370
will always goes to the continue statement due to the fact that d_type is returned as DT_UNKNOWN, which is expected in some systems according to:
https://man7.org/linux/man-pages/man3/readdir.3.html

**Comment by xrootd-dev** [comment]
It would appear that the only portable solution is to always use fstatat() 
relative to the directory to get the actual filetype. What filesystem do 
the certs live on?

**Comment by ddavila0** [comment]
It fails in CentOS 7.7 and works in 7.9 both running the same version of XRootD 5.2.0

**Comment by xrootd-dev** [comment]
Then I presume it's exactly the same filesystem. OK, we can optimize this 
if so.

**Comment by abh3** [comment]
I am about to push a fix for this (it will also close this issue). Could test it and tell me if it indeed solves the issue. It wound up being it bit more involved as the original code made some incorrect assumptions regarding symlinks. If we still have a problem, please reopen the ticket.

**Comment by ddavila0** [comment]
I just tested the code in `v5.0.2-osghotfix-test00` and the problem is gone!.
One thing I noticed is that before I used to see the directory `/tmp/.xrdtls` being created and now I don't see it. Is that expected?

**Comment by ddavila0** [comment]
> I just tested the code in `v5.0.2-osghotfix-test00` and the problem is gone!.
> One thing I noticed is that before I used to see the directory `/tmp/.xrdtls` being created and now I don't see it. Is that expected?

Thanks @osschar to make me realized I used the wrong version, that explains why I don;t see the .xrdtls directory... Testing again...

**Comment by ddavila0** [comment]
The right version still works! and now I see the .xrdtls directory in /tmp
