### ISSUE TITLE
FTS request: Query the IP Stack used during TPC

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#1471]
Hello,

With an increased focus on IP Stack monitoring during WLCG transfers, requests for FTS to report the IP stack used during XRootd transfers will soon follow. 

FTS/Gfal2 needs a way to query the TPC transfer for the IP stack used. This should be the IP Stack of the actual transfer (between `<src>` and `<dst>`) and not the one of the triggering client.

Cheers,
Mihai

**Comment by bbockelm** [comment]
Hi @mpatrascoiu -

This is part of the periodic events in HTTP-TPC, no?  It includes the IP address of all the active connections used for transfer, from which you should be able to determine if they are using IPv4, v6, or both.

Brian

**Comment by mpatrascoiu** [comment]
Hello Brian,

I'm thinking XRootD TPC transfers here.

Regarding HTTP-TPC transfers, the performance markers allow reporting of the IP addresses. Over there, it's more a question for FTS/Gfal2 to parse these replies and for the storage endpoints to send them.

Cheers,
Mihai

**Comment by bbockelm** [comment]
Ah, thanks -- wasn't clear which protocol you were thinking about here!

**Comment by abh3** [comment]
OK, as fas I can see someone is mangling what is being set in the perf market. I typed out what get sent back to the client and this is it:

Perf Marker: Perf Marker
Timestamp: 1663042098
Stripe Index: 0
Stripe Bytes Transferred: 6209667072
Total Stripe Count: 1
RemoteConnections: tcp:134.79.120.8:2094
End

Notice the remote connection here indicates that IPv4 is being used. Now what get printed on the console but gfal-copy is rather useless:
Copying https://osggridftp01.slac.stanford.edu:2094/xrootd/atlas/usr/a/abh/zeros.256G 
Copying https://osggridftp01.slac.stanford.edu:2094/xrootd/atlas/usr/a/abh/zeros.256G.
Copying https://osggridftp01.slac.stanford.edu:2094/xrootd/atlas/usr/a/abh/zeros.256G..
Copying https://osggridftp01.slac.stanford.edu:2094/xrootd/atlas/usr/a/abh/zeros.256G...
Copying https://osggridftp01.slac.stanford.edu:2094/xrootd/atlas/usr/a/abh/zeros.256G   

So, for http the IP type is being sent back what happens inside gfal is unbeknownst to me, BTW we won't be doing the same for xroot protocol as most places are switching to http for this.

**Comment by mpatrascoiu** [comment]
Hello Andy,

Using `gfal-copy` with `-v` option will print out the IP event. Example:
```
event: [1663058803002] DEST   http_plugin	IPV6	TRUE
```
This will only show up during a larger transfers, which goes on for a couple seconds or more.

The example you've provided is for HTTP-TPC transfers. The initial request was to identify the IP stack for XRoot TPC transfers. 

I take it this is the final response?
> BTW we won't be doing the same for xroot protocol as most places are switching to http for this.

**Comment by xrootd-dev** [comment]
On Tue, 13 Sep 2022, Mihai Patrascoiu wrote:
> Using `gfal-copy` with `-v` option will print out the IP event. Example:
> ```
> event: [1663058803002] DEST   http_plugin	IPV6	TRUE
That for letting me know that. I will use it.

> I take it this is the final response?
>> BTW we won't be doing the same for xroot protocol as most places are switching to http for this.
As you know in LHC nothing is final. That is the operative statement.

Andy

**Comment by abh3** [comment]
Given that the community is moving to http and xroot TPC represents a very small percentage of all transfer, we are closing this ticket until the usage changes to make spending time on this necessary.
