### ISSUE TITLE
Checksum calculation on the fly

### ISSUE THREAD

**Issue by juztas** [xrootd/xrootd#1473]
From OSG Software slack dicussion:
For HDFS Storage - we used https://github.com/opensciencegrid/xrootd-hdfs plugin and for any transfers, it does checksum on the fly. http-tpc also invokes xrootd-hdfs through the plugin layer and checksums are also done on the fly. But...

This is not the case for POSIX Sites. We will definitely will need checksum calculation "on the fly" moving forward. 

@djw8605 @bbockelm

**Comment by abh3** [comment]
Actually, anyone running XRootD 5.2.x gets checksums on the fly 
irrespective of what the underlying filesystem is. It's builtin.

Andy

**Comment by juztas** [comment]
Is it? Let me drain 1 node and give a try (is there some special config for
this?)

**Comment by abh3** [comment]
OK, I was a bit too quick. The on-the-fly checksums apply to Xcache, it 
has yet to be rolled into xrdcp. But you will see it being used for 
Xcache. The xrdcp portion should be in the next release.

Andy

**Comment by juztas** [comment]
Let me understand, xrdcp will be the client thing, not the server related. So for third party copy - this still needs to be implemented.

**Comment by abh3** [comment]
Correct, I was a bit to swift on the draw. It will be implemented 
relatively soon (I will get an exact date for our Thursday's meeting). 
Now, it all requires that the data servers involved in the copy also 
support on-the-fly checksums. Most will once they upgrade but there is 
this nagging dCache thing. We can, of course, substitute TLS but that's 
not a very good option all around.

Andy

**Comment by juztas** [comment]
Cool Thanks!

**Comment by abh3** [comment]
The discussion is over.
