### ISSUE TITLE
'group' definition unclear in authZ db docs

### ISSUE THREAD

**Issue by brianhlin** [xrootd/xrootd#1475]
In the [authorization database file documentation|https://xrootd.slac.stanford.edu/doc/dev50/sec_config.htm#_Toc64492263], it's implied that `g` corresponds solely to the unix group name when the group can be whatever group the configured authentication plugin passes along, e.g. VOMS group. Instead of the following:

> - template name,
> - unix group name,
> - user name

It would be clearer if this was worded something like:

> - template name,
> - group name (such as Unix or VOMS groups depending on the configured authentication plugin),
> - user name

**Comment by abh3** [comment]
This will be corrected in the new set of docs issued this week.
