### ISSUE TITLE
EL7 build of xrootd-voms in official repos is not signed

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1477]
Trying to upgrade to XRootD 5.3.0, I get an error since `xrootd-voms` is not signed — see:
```
$ wget https://xrootd.slac.stanford.edu/binaries/stable/slc/7/x86_64/xrootd-voms-5.3.0-1.el7.x86_64.rpm
$ rpm -qpi xrootd-voms-5.3.0-1.el7.x86_64.rpm
...
Signature   : (none)
...
```
Subsequently, `yum` refuses to install the RPM. The RPM of `xrootd-voms` for EL8 is signed fine, and also other RPMs for EL7 seem signed fine.

**Comment by simonmichal** [comment]
@olifre : thanks for reporting this problem, I rerun the script that signs the RPMs and creates the repo, it should work now, could you give it a try?

**Comment by olifre** [comment]
@simonmichal Many thanks, indeed, now all is well :-).
