### ISSUE TITLE
Unable to get transport handler for file protocol

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#1478]
Forwarded from Fedora bidhi: https://bodhi.fedoraproject.org/updates/FEDORA-2021-ba25d90bf5

With -d1 option appeared message

xrdcp -f -d1 root://... /dev/null

[2021-07-11 23:36:45.965324 +0300][Error ][PostMaster ] Unable to get transport handler for file protocol

With 5.2.0 and previous versions no such error.

**Comment by simonmichal** [comment]
@ellert : thanks for reporting this problem upstream, should be fixed in 6c1729e56a3c4efd0704c4c0427c73ea0de7a4db
