### ISSUE TITLE
Cannot install Python bindings on Mac OS (M1)

### ISSUE THREAD

**Issue by dcervenkov** [xrootd/xrootd#1480]
It is trivial to install xrootd 5.3.0 via brew on M1 machines. However, I don't know how to install the xrootd Python bindings. The newest xrootd on PyPI is 5.2.0. Any advice?

**Comment by simonmichal** [comment]
@dcervenkov : thank you for reporting this problem, I just pushed `5.3.0` to PyPI: https://pypi.org/project/xrootd/5.3.0/

**Comment by dcervenkov** [comment]
@simonmichal Thanks for the response. I just gave it a try. Unfortunately, the [xrootd in brew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/xrootd.rb) is built with `-DENABLE_PYTHON=OFF`, so this is not something the new PyPI version solves.

Furthermore, I'm unable to install xrootd 5.3.0 via `pip`. It reports missing dependencies - openssl development package. Note that openssl is installed via `brew` (including the headers). However, the following is part of what `brew` prints when installing `openssl`:
```
    openssl@1.1 is keg-only, which means it was not symlinked into /opt/homebrew,
    because macOS provides LibreSSL.
    If you need to have openssl@1.1 first in your PATH run:
    echo 'export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
    For compilers to find openssl@1.1 you may need to set:
    export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
    export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
```
Maybe the makefiles would need to be updated for use on M1 Macs?

In any case, I was able to compile with Python bindings from source and it works without problems. The steps are somewhat convoluted, so I'll write them here for others looking for a solution.

### Compiling XRootD with Python bindings on M1 Macs
 - Run `cmake` like this

```shell
cmake -DENABLE_PYTHON=TRUE -DCMAKE_INSTALL_PREFIX=/opt/xrootd -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl ..
```
 - Edit `CMakeCache.txt` and change the following variables to point to the `brew` Python, like so:
```
PYTHON_EXECUTABLE:FILEPATH=/opt/homebrew/bin/python3
PYTHON_INCLUDE_DIR:PATH=/opt/homebrew/Frameworks/Python.framework/Versions/3.9/include/python3.9
PYTHON_LIBRARY:FILEPATH=/opt/homebrew/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
```
- Run `make` and `sudo make install`
- Add `export PYTHONPATH=/opt/xrootd/lib/python3.9/site-packages:$PYTHONPATH` to `.zshrc`/`.bashrc`/...
- Confirm that it is working by running `python3 -c "import pyxrootd"`

**Comment by simonmichal** [comment]
@dcervenkov : it's no us who do the packaging for `brew` so unfortunately I cannot do much, regarding installing python-bindings with `pip` I should be able to make this work, I will put it on my to do list.

**Comment by dcervenkov** [comment]
@simonmichal Of course, I wouldn't ask you to take care of the brew package, just reporting my observations.

If you could figure out the `pip` issue, that would be much appreciated.

**Comment by amadio** [comment]
This will hopefully be solved by https://github.com/Homebrew/homebrew-core/pull/117063, where I enabled support for installing also the Python bindings to the brew formula.

**Comment by amadio** [comment]
New pull request updating to just released XRootD 5.5.2: https://github.com/Homebrew/homebrew-core/pull/122569

**Comment by amadio** [comment]
The pull request with XRootD 5.5.2 was merged. Please use `brew install xrootd` now to get the Python bindings on Mac. XRootD 5.5.2 is now also available on PyPI: https://pypi.org/project/xrootd/.

**Comment by dcervenkov** [comment]
Thanks, @amadio! A comment that can be useful for others that find this thread - when installing via Homebrew, the bindings are currently only available for Python 3.11.

**Comment by amadio** [comment]
That would be 3.10, no?

**Comment by amadio** [comment]
Indeed, this was something that was asked when I put up the pull request, so I used it. Hopefully they move the default to 3.11 soon.
