### ISSUE TITLE
 PyEval_ThreadsInitialized is deprecated in Python >= 3.7

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#1482]
Once again, python moves faster than most projects. In this case Python 3.7 started deprecating use of  PyEval_ThreadsInitialized() plus some other functions used in PyXRootDModule.cc and should be version checked. An example of such a fix can be seen in:

https://github.com/gjcarneiro/pybindgen/commit/5fbeb8d0659531b2c237947dd1d26931175f29dd

The specific error was reported in https://github.com/xrootd/xrootd/issues/1481 and the excerpt of the issue is below.

7: warning: 'int PyEval_ThreadsInitialized()' is deprecated [-Wdeprecated-declarations]
84 | if ( !PyEval_ThreadsInitialized() ) {
| ^
In file included from /usr/include/python3.9/Python.h:145,
from /home/saba/alice/sw/BUILD/70f7dfa756380c5669baf922e0068ee424a0ba3d/XRootD/bindings/python/src/PyXRootD.hh:28,
from /home/saba/alice/sw/BUILD/70f7dfa756380c5669baf922e0068ee424a0ba3d/XRootD/bindings/python/src/PyXRootDModule.cc:25:
/usr/include/python3.9/ceval.h:129:36: note: declared here
129 | Py_DEPRECATED(3.9) PyAPI_FUNC(int) PyEval_ThreadsInitialized(void);

**Comment by simonmichal** [comment]
find in 2a98bf2ca783e3b10572c3f036841f46fcaefde8
