### ISSUE TITLE
5.3.0 :: el7 pip install fails

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1485]
I'm trying to pip install xrootd on el7 but i get this:
```
Some dependencies are missing:
devtoolset-7 package is missing
```

but actually is already loaded:
```
[Monday 26.07.21 21:22] adrian@issaf : ~  $
which gcc
/opt/rh/devtoolset-7/root/usr/bin/gcc
[Monday 26.07.21 21:23] adrian@issaf : ~  $
gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

any idea about this?
Thanks a lot!
Adrian

**Comment by simonmichal** [comment]
@adriansev : that's what I'm doing to determine if `devtoolset-7` is available:

https://github.com/xrootd/xrootd/blob/3be51d9f8056a4ad9b46dd7600cb64060f66cc5b/packaging/wheel/setup.py#L64-L70

(the check is only for RHEL7)

Could you try running: `/usr/bin/rpm -q` ?

**Comment by adriansev** [comment]
@simonmichal well, there are different things:
```
[Tuesday 27.07.21 15:55] adrian@issaf : ~  $ 
/usr/bin/rpm -q devtoolset
package devtoolset is not installed

[Tuesday 27.07.21 15:58] adrian@issaf : ~  $
rpm -qa | grep devtoolset-7-gcc*
devtoolset-7-gcc-plugin-devel-7.3.1-5.16.el7.x86_64
devtoolset-7-gcc-gdb-plugin-7.3.1-5.16.el7.x86_64
devtoolset-7-gcc-gfortran-7.3.1-5.16.el7.x86_64
devtoolset-7-gcc-c++-7.3.1-5.16.el7.x86_64
devtoolset-7-gcc-7.3.1-5.16.el7.x86_64
```
i usually do not install everything ..  only what i need .. so i would say that is better to check only for what is needed ...
even better would be just to check for the version of the gcc, as gcc can come from other sources (like a cvmfs distributed software that is not cvmfs)

**Comment by simonmichal** [comment]
@adriansev : OK, that makes sense, let me experiment a bit so I can find a proper solution!

**Comment by simonmichal** [comment]
@adriansev : I just pushed 2 patches to master that address this problem: first of all the install script will check if the compiler selected by `cmake` has full `C++14` support, (secondly) if not the script will require `devtoolset-7-gcc-c++` to be installed.

Hope this solves the problem (we want to tag `5.3.1` by tomorrow).

**Comment by adriansev** [comment]
@simonmichal seems to work : built, loaded and reported as `20210729-bdf3ceb` and tested a small copy, all green

**Comment by simonmichal** [comment]
@adriansev : perfect, thanks a lot for testing it so quickly :-)

I will close this issue and go ahead with the release.
