### ISSUE TITLE
Update xrdcp to allow the user to specify the desired block size

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#1491]
For direct transfers, xrdcp seems to use a fixed 8 MiB block size when requesting data over the network.

We've seen a problem in which a remote server misbehaves if the requested data is 4 MiB, but seems to work fine if the block size is 8 MiB (see #1454).

I think it would be helpful if `xrdcp` supported some mechanism that allowed a user to specify the size of read blocks.  This might be to optimise network transfers, but also easy reproduction of problems such as in #1454.  It would also allow a site to validate their endpoint works correctly at different requested block sizes.

I note that there is an environment variable `XRD_XCPBLOCKSIZE`; however, it wasn't clear to me (from the man page) whether this has the desired effect.  Its description refers to an "extreme copy transfer": a term that is not defined in the man page.

(I don't consider this urgent.  I'm creating the issue just so it doesn't get lost.)

**Comment by simonmichal** [comment]
@paulmillar : please have a look at `XRD_CPCHUNKSIZE`, it should allow you to specify the desired read/write chunk size, the default value is 8MB (8388608 bytes), AFAIR, currently we don't support suffixes so you have to provide the value in bytes.

You can also tune the number of in-flight chunks with `XRD_CPPARALLELCHUNKS` (4 by default).

The `XRD_XCPBLOCKSIZE` applies to extreme copy and is the size of a data block allocated to each source that spans over several chunks.

I hope this helps.

**Comment by paulmillar** [comment]
Thanks for the quick reply @simonmichal 

Using these options, I've selected arguments that should allow `xrdcp` to simulate the behaviour of dCache's embedded client:

    xrdcp -DICPParallelChunks 1  -DICPChunkSize 4194304 root://ceph-gw8.gridpp.rl.ac.uk:1094/dteam:test1/domatest/jwalder/HTTP_1GB .

**Comment by simonmichal** [comment]
@paulmillar my pleasure :-) can we close this issue?

**Comment by paulmillar** [comment]
Yes, I think so.

There's a related issue that I'm unable to reproduce the failure (from which dCache's embedded client is suffering) with the RAL endpoint using `xrdcp` (described in #1454).  I don't think dCache's client is doing anything crazy, so my impression is that the problem _should_ be reproducible, if the problem is properly understood.

However, that is something that could be discussed further in the other issue.
