### ISSUE TITLE
Allow turning off plain HTTP without turning off HTTPS

### ISSUE THREAD

**Issue by matyasselmeci** [xrootd/xrootd#1494]
For security reasons, we'd like an option in the HTTP plugin that will forbid plain HTTP but still allow HTTPS.

**Comment by abh3** [comment]
This feature can be handled via a config setup. Let's assume you want to use port 443 as the https only port (note that you will need to use systemd to allocate this port to be used by xrootd). So, what you
would do is speify that port 443 is a tls only port

xrd.port tls 443

then you specify that http protocol is to run on this port

xrd.protocol tls https:443 libXrdHttp.so

This effectively prohibits using http and only https is available. Note any port canbe used here, though 443 is the official https-only port. The relevant documentation:

port: https://xrootd.slac.stanford.edu/doc/dev55/xrd_config.htm#_Toc88513975
protocol: https://xrootd.slac.stanford.edu/doc/dev55/xrd_config.htm#_Toc88513976
