### ISSUE TITLE
zip member:: file corruption/bogus content when downloading

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1496]
@simonmichal Hi! we just noticed a problem with downloading small zip members: the content is garbled and with debug options enabled we can even see in the garbled output part of either command line or part of log file!! relevant files can be seen here: https://asevcenc.web.cern.ch/asevcenc/xrootd_inzip_corruption/  (and another interesting example in example2 sub-directory)

Let me know when you return and have time to tackle this.. 
Thanks a lot!!

**Comment by simonmichal** [comment]
Hi @adriansev, thanks for reporting this problem! It should be now fixed by 3a36679a20adcbf07645b19a35c889a27c03e58f, could you give it a try?

**Comment by adriansev** [comment]
Hi @simonmichal and thanks a lot! I can confirm that the problem is solved.
