### ISSUE TITLE
xrootd change runtime configuration without restart (debug/logging)

### ISSUE THREAD

**Issue by juztas** [xrootd/xrootd#1499]
Restart in most cases is not the best solution as it will evict all the clients connected. It would be nice to have an option to increase debug level for any component without a service restart. Is there such?
e.g. I want to set to `xrootd.trace emsg stall redirect fs` or change to `xrootd.trace all -debug` without restart.

**Comment by abh3** [comment]
There is no such interface as of yet, though we could add one; though it 
wouldn't be particularly thread-safe. That said, it need not be 
thread-safe for the purpose here.

Andy

**Comment by adriansev** [comment]
Maybe it would be enough if a SIGUSR sent to process would make it to put pause to all incoming requests (somehow), reset all configuration to defaults and then re-read the configuration files? (with the assumption that the ongoing operations have already a set of properties/configs and can go on)

**Comment by abh3** [comment]
Whi;le such an approach is doable for simple services, the complex nature of the server makes is unfeasable. Consider that each plugin would have to re-initialize and persistent state may get invalidated and providing consistency across a existing sesssions would be incredibly difficult if not impossible. Instead, we chose to provide recoverability via the client. Restating a server should not fail any existing client as it simply reconnects after a restart and continues where it left off if the new configuration allows it (think, among other issues like changes in security or exports). That has proven to be the most reliable way allow on-the-fly configuration changes.

**Comment by abh3** [comment]
There is way too much interrelated information that is constructed during initialization and to reconstruct would effectively squelch the server which is about the same as doing a restart. Add to that, this would be a massive change to the internal initialization of not only the base server but every plugin. So, I'd say this cannot be practically done.
