### ISSUE TITLE
kXR_move failing on names with whitespaces

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#150]
The XROOTD protocol uses a space character to seperate source and target path in the kXR_move request. This breaks for filenames which contain whitespaces. Maybe it would be beneficial for the future to think about an encoding scheme for paths. Same conceptional problem exists for '&' and '?' and '=' which have a dedicated meaning in XRootd paths.

**Comment by gbehrmann** [comment]
The core issue is that two separate parameters (the two paths) are encoded into a single character array in the binary request format. If instead the two paths each had their own field with their own length header, this encoding issue would not have appeared in the first place.

**Comment by abh3** [comment]
We are well aware of this problem. Originally, we had n intention of supporting names with spaces in them as there never was an experimental requirement to do so. We are still looking to see how we can do this without creating other issues (e.g. old server compatibility).

**Comment by gbehrmann** [comment]
Great. Do you have an update to the protocol specification to document the solution?

**Comment by abh3** [comment]
Hi Gerd,

Yes, the new spec will be published real soon (within a few 
days).Interference with CHEP is slowingthings down.

Andy

**Comment by gbehrmann** [comment]
Thanks!

Cheers,

/gerd

PS I am no longer working full time for NDGF/dCache, but if I don't find time to implement the changes, I will make sure to pass this on to @paulmillar.
