### ISSUE TITLE
xrdcp reports no error/wrong error message when destination file exists

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1508]
xrdcp and xrootd 5.3.0/5.3.1 seems to not report error message correctly. See the following tests. Note in the test, 
* osggridftp01.slac.stanford.edu:2094 is an xrootd proxy running 5.3.0. 
* atlrdr1.slac.stanford.edu is a local storage running 4.12.6. I simply used name "atlrdr1" in the test

$ xrdcp --version
v4.12.6
$ xrdcp root://atlrdr1//xrootd/atlas/tpctest/junk-wei root://atlrdr1//xrootd/atlas/tpctest/junk-wei-DD
[1024kB/1024kB][100%][==================================================][1024kB/s]  
$ xrdcp root://atlrdr1//xrootd/atlas/tpctest/junk-wei root://atlrdr1//xrootd/atlas/tpctest/junk-wei-DD
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3011] Unable to create new file; file already exists. (destination)
$ echo $?
54
$ xrdcp root://atlrdr1//xrootd/atlas/tpctest/junk-wei root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/tpctest/junk-wei-DD
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3011] Unable to open /xrootd/atlas/tpctest/junk-wei-DD; no such file or directory (destination)
$ echo $?
54
 (in the last xrdcp test, the error message is wrong)

$ xrdfs atlrdr1 rm /xrootd/atlas/tpctest/junk-wei-DD

$ xrdcp --version
v5.3.1
$ xrdcp root://atlrdr1//xrootd/atlas/tpctest/junk-wei root://atlrdr1//xrootd/atlas/tpctest/junk-wei-DD
[1024kB/1024kB][100%][==================================================][1024kB/s]  
$ xrdcp root://atlrdr1//xrootd/atlas/tpctest/junk-wei root://atlrdr1//xrootd/atlas/tpctest/junk-wei-DD
$ echo $?
50
$ xrdcp root://atlrdr1//xrootd/atlas/tpctest/junk-wei root://osggridftp01.slac.stanford.edu:2094//xrootd/atlas/tpctest/junk-wei-DD
$ echo $?
50

In the last two cases, xrdcp gives no error message, but return errno 50.

**Comment by simonmichal** [comment]
@wyang007 : thanks for reporting this problem, the missing error message should be fixed in: 49e7ff482023cfb739433a4e7b354ee6e93af355

Could you give it a try?

The return code 54 means that there was an error response on open, the code 50 means that there was an invalid operation (the stat was successful and the file exists, so there was no error response from the server).

**Comment by simonmichal** [comment]
@wyang007 : let me know if we can close this one?

**Comment by wyang007** [comment]
Should I just test with a updated xrdcp or should I also test with an update Xrootd proxy (which also use XrdCl) ?

**Comment by simonmichal** [comment]
This shouldn't have any effect on the proxy.

**Comment by simonmichal** [comment]
@wyang007 : can we close this issue?

**Comment by abh3** [comment]
Fixed in 5.3.4.
