### ISSUE TITLE
Cannot create directory

### ISSUE THREAD

**Issue by marcelkuri** [xrootd/xrootd#151]
I create a automount file with this content:
/atlas -fstype=fuse,rw,uid=496,gid=492,allow_other,rdr=root://lipnode01\:1094//data/xrootdfs :xrootdfs.sh

where:
496 is the xrootd uid number
492 is the xrootd gid number

"/atlas" is mounted correctly, I can list the files and even create a new file under /atlas.
But when I try to create a directory I get this error:

$ mkdir teste2
mkdir: cannot create directory `teste2': No such file or directory

Thanks
Marcel

**Comment by abh3** [comment]
I believe this has been resolved. Please reopen if that is not the case.
