### ISSUE TITLE
Report any file open/delete in xrootd logs

### ISSUE THREAD

**Issue by juztas** [xrootd/xrootd#1513]
From mailing list discussion - "Xrootd trace report fs stats (not too deep)" it would be nice if xrootd reports any file open/delete in the log. 
Default xrootd trace level does not report that and `xrootd.trace fs` is way too verbose

**Comment by abh3** [comment]
Actually, that ability is already implemented in the ofs layer with all of the information you would likely want (e.g. the path). Use 

ofs.trace open remove

to get the information you want. Now, if the complaint is that the ofs plugin you are using does not provide that information, I would suggest that be brought up with the plugin provider. In the standard XRootD you can get this information in the log.
