### ISSUE TITLE
openssl 3 plans?

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1516]
Hi! Are there plans for supporting the very fresh openssl 3?
Thanks!

**Comment by simonmichal** [comment]
@adriansev : yes, we do have to support it as it is now available on Fedora rawhide (and we are obliged to built on Fedora rawhide as we release XRootD in EPEL).

**Comment by abh3** [comment]
We have a compatible compilation version in 5.4.0. Since there are few sites using xrootd with openSSL 3 we have no idea whether this works to everyone's satisfaction. Anyway, I am closing this ticket as the support is there even if untested.

**Comment by rob-c** [comment]
@abh3 should I correct in saying that v5.4.x should be compiling with openssl v3.0.x (vanilla from the project gh) with gcc10+ on a centos host?
I am getting a lot of compilation errors, initially just some const-casting but then some more compilation errors about deprecation headers and such which is where I stopped debugging.

Is there a different branch/compilation-flag I'm supposed to use for testing this? From what I can tell most changes are wrapped behind ifdef version checks.
or,
Should the openssl libraries be compiled in a certain way as of v3 for best xrootd support?
