### ISSUE TITLE
XrdHTTP mkdir operation does not respect umask

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1521]
I suspect the mkdir command here needs to be slightly refined:

https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L1690-L1703

Justas @ Caltech reports this is ignoring the umask he is setting (expecting directories created with 0755 ); I suspect the `mode` attribute needs to be set here.

Brian

**Comment by juztas** [comment]
Is there a workaround for this? I start to see more and more failures on davs stageout.

```
https://fts-cms-03.cern.ch:8449/var/log/fts3/transfers/2021-10-04/grid-webdav.physik.rwth-aachen.de__xrootd-redir.ultralight.org/2021-10-04-1715__grid-webdav.physik.rwth-aachen.de__xrootd-redir.ultralight.org__3163394795__b80da2b2-2536-11ec-9240-fa163e7b2a22
INFO    Mon, 04 Oct 2021 19:15:54 +0200; File size: 2127904974
INFO    Mon, 04 Oct 2021 19:15:54 +0200; IPv6: indeterminate
INFO    Mon, 04 Oct 2021 19:15:54 +0200; TCP streams: 0
INFO    Mon, 04 Oct 2021 19:15:54 +0200; TCP buffer size: 0
INFO    Mon, 04 Oct 2021 19:15:54 +0200; Timeout set to: 4659
INFO    Mon, 04 Oct 2021 19:15:54 +0200; [1633367754430] BOTH GFAL2:CORE:COPY	LIST:ENTER	
INFO    Mon, 04 Oct 2021 19:15:54 +0200; [1633367754430] BOTH GFAL2:CORE:COPY	LIST:ITEM	davs://grid-webdav.physik.rwth-aachen.de:2889/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_1_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v2/230000/DC538CEF-F623-EC11-940A-484D7E8DF085.root => davs://xrootd-redir.ultralight.org:1094/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_1_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v2/230000/DC538CEF-F623-EC11-940A-484D7E8DF085.root
INFO    Mon, 04 Oct 2021 19:15:54 +0200; [1633367754430] BOTH GFAL2:CORE:COPY	LIST:EXIT	
INFO    Mon, 04 Oct 2021 19:15:54 +0200; [1633367754430] BOTH http_plugin	PREPARE:ENTER	davs://grid-webdav.physik.rwth-aachen.de:2889/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_1_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v2/230000/DC538CEF-F623-EC11-940A-484D7E8DF085.root => davs://xrootd-redir.ultralight.org:1094/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_1_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v2/230000/DC538CEF-F623-EC11-940A-484D7E8DF085.root
INFO    Mon, 04 Oct 2021 19:15:54 +0200; [1633367754430] SOURCE http_plugin	CHECKSUM:ENTER	
INFO    Mon, 04 Oct 2021 19:15:54 +0200; [1633367754455] SOURCE http_plugin	CHECKSUM:EXIT	
WARNING Mon, 04 Oct 2021 19:15:59 +0200; Timeout stopped
ERR     Mon, 04 Oct 2021 19:15:59 +0200; Recoverable error: [5] DESTINATION MAKE_PARENT HTTP 500 : Unexpected server error: 500  with url davs://xrootd-redir.ultralight.org:1094/store/mc/RunIIFall17MiniAODv2/PMSSM_set_2_prompt_1_TuneCP2_13TeV-pythia8/MINIAODSIM/PUFall17Fast_GridpackScan_94X_mc2017_realistic_v15-v2/230000
```

**Comment by abh3** [comment]
Ah, found it. The problem is that the http side is setting the wrong option to create the path. So, if the path does not exist you will get an error. The only solution is to make sure the http side is actually setting the correct bit. As for Brian's comment, the http side never sets the mode bits (webdav does not appear to support specifying the mode bits). However, the xroot side makes sure that the owner's read/write/search bits are set. So, in this case the mode will always be 0700 for directories created by mkcol. Anyway, this is a bug in the http side and I can correct that for 5.3.2 but we still have the question whether or not keeping the mode handling the way it is now. Bottom line, there is no bypass via the http route.

**Comment by bbockelm** [comment]
@abh3 - is there an idea of a `umask` within the protocol call (I didn't see any, so I'm expecting not)?  That's probably better than trying to make the HTTP layer calculate the correct mode.

What does the xrootd client do for the default directory permissions?  That's probably what we want to copy, no?

**Comment by abh3** [comment]
@bbockelm There is no default other than enforcing atleast 0700 mode bits plus any others you may want. except for world  writable which is forbidden.  The issue here was not the mode bit settings but that the path was never created. A mode of 0700 works in practically all cases except, perhaps, for multi-user. However, that plugin is responsible for setting whatever it needs to have.

**Comment by juztas** [comment]
Maybe I missed something... Seems it works if I set `multiuser.umask 0022`, so dirs are `755` and files `644`. If I set `0002` - dirs `775` and files `664`.

**Comment by bbockelm** [comment]
@juztas - now I'm confused.  Weren't you the one with the original issue?  Or are you saying that you started setting `multiuser.umask` after reporting the above issue and it's now cleared up?

**Comment by juztas** [comment]
Cha here is more debug.
1. No `multiuser.umask` config set.  Using gfal-copy <source_file> <dest_location> (I did from local file, and using TPC from another site - all works and permissions are correct:
```
gfal-copy davs://grid-webdav.physik.rwth-aachen.de:2889/store/mc/....long_source_file davs://xrootd-redir.ultralight.org:1094//store/user/jbalcas/1/2/1.root
# ll /storage/cms/store/user/jbalcas/
drwxr-xr-x 3 jbalcas jbalcas 1 Oct  5 12:26 1
# ll /storage/cms/store/user/jbalcas/1/
drwxr-xr-x 2 jbalcas jbalcas 1 Oct  5 12:26 2
# ll /storage/cms/store/user/jbalcas/1/2/
-rw-r--r-- 1 jbalcas jbalcas 30408704 Oct  5 12:27 1.root
```
2. `multiuser.umask 0022`; gfal-copy same as in 1.
```
# ll /storage/cms/store/user/jbalcas/
drwxr-xr-x 3 jbalcas jbalcas 1 Oct  5 12:28 1
# ll /storage/cms/store/user/jbalcas/1/
drwxr-xr-x 2 jbalcas jbalcas 1 Oct  5 12:28 2
# ll /storage/cms/store/user/jbalcas/1/2/
-rw-r--r-- 1 jbalcas jbalcas 23068672 Oct  5 12:28 1.root
```
3. `multiuser.umask 0002`; gfal-copy same as in 1.
```
# ll /storage/cms/store/user/jbalcas/
drwxrwxr-x 3 jbalcas jbalcas 1 Oct  5 12:29 1
# ll /storage/cms/store/user/jbalcas/1/
drwxrwxr-x 2 jbalcas jbalcas 1 Oct  5 12:29 2
# ll /storage/cms/store/user/jbalcas/1/2/
-rw-rw-r-- 1 jbalcas jbalcas 26214400 Oct  5 12:30 1.root
```
4. No `multiuser.umask` config set. Using same gfal-copy (but with -p flag) commands (TPC,Local)
```
# ll /storage/cms/store/user/jbalcas/
drwx------ 3 jbalcas jbalcas 1 Oct  5 12:31 1
# ll /storage/cms/store/user/jbalcas/1/
drwx------ 2 jbalcas jbalcas 1 Oct  5 12:31 2
# ll /storage/cms/store/user/jbalcas/1/2/
-rw-r--r-- 1 jbalcas jbalcas 695205888 Oct  5 12:31 1.root
```
5.`multiuser.umask 0022`; gfal-copy same as in 4 with -p flag.
```
# ll /storage/cms/store/user/jbalcas/
drwxr-xr-x 3 jbalcas jbalcas 1 Oct  5 12:32 1
# ll /storage/cms/store/user/jbalcas/1/
drwxr-xr-x 2 jbalcas jbalcas 1 Oct  5 12:32 2
# ll /storage/cms/store/user/jbalcas/1/2/
-rw-r--r-- 1 jbalcas jbalcas 36700160 Oct  5 12:33 1.root
```
6. `multiuser.umask 0002`; gfal-copy same as in 4 with -p flag.
```
# ll /storage/cms/store/user/jbalcas/
drwxrwxr-x 3 jbalcas jbalcas 1 Oct  5 12:34 1
# ll /storage/cms/store/user/jbalcas/1/
drwxrwxr-x 2 jbalcas jbalcas 1 Oct  5 12:34 2
# ll /storage/cms/store/user/jbalcas/1/2/
-rw-rw-r-- 1 jbalcas jbalcas 131072000 Oct  5 12:34 1.root
```
So the question/issue remains why xrootd behaves differently for `gfal-copy | gfal-copy -p` whenever `multiuser.umask` is not set.

**Comment by bbockelm** [comment]
Ah - I think this is precisely what @abh3 already fixed: he changed it so the `mkdir` operation (technically, WebDAV calls it `MKCOL`) no longer does recursive directory creation.

I _think_ you're being hit by the default recursive directory creation logic in the case without `-p`.  Would you be in position to test his patch?

Thanks!

**Comment by juztas** [comment]
Sure, let me know RPM loc and I can test it out

**Comment by abh3** [comment]
No, I did exactly the opposite. MKCOL is *supposed* to create the full 
path. The code used the wrong flag to indicate this. I fixed it by using 
the correct flag.

**Comment by abh3** [comment]
There should be the nightly rpm you can use.

https://xrootd.slac.stanford.edu/binaries/xrootd-experimental-slc7.repo

**Comment by juztas** [comment]
```
[root@transfer-10 yum.repos.d]# yum list installed | grep xrootd
gfal2-plugin-xrootd.x86_64             2.18.1-1.2.osg35.el7            @osg
gratia-probe-xrootd-storage.x86_64     1.23.3-1.osg35.el7              @osg
gratia-probe-xrootd-transfer.x86_64    1.23.3-1.osg35.el7              @osg
xrootd.x86_64                          1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-client.x86_64                   1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-client-libs.x86_64              1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-cmstfc.x86_64                   1.5.2-6.osg35up.el7             @osg-upcoming-development
xrootd-lcmaps.x86_64                   1.7.8-3.osgup.el7               @osg-upcoming-testing
xrootd-libs.x86_64                     1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-multiuser.x86_64                2.0.2-1.osg35up.el7             @osg-upcoming-development
xrootd-scitokens.x86_64                1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-selinux.noarch                  1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-server.x86_64                   1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
xrootd-server-libs.x86_64              1:5.3.2-0.experimental.3088749.db9bf87b.el7.cern
                                                                       @xrootd-experimental
```
And issue remains (dir name 1 created with gfal-copy -p, dirname 2 - without -p flag):
```
ll /storage/cms/store/user/jbalcas/
drwx------ 3 jbalcas jbalcas 1 Oct  5 12:56 1
drwxr-xr-x 3 jbalcas jbalcas 1 Oct  5 12:58 2

```

**Comment by abh3** [comment]
The http protocol doesn't do anything with umask. So there is nothing to 
respect. MKCOL does not specify the mode, it's up to the implementation. 
So, you are getting the xroot version of what happens. Since this only 
affects multi-user, I suggest that it be fixed there which apparently it 
can be. Am I missing something here?

**Comment by abh3** [comment]
Given the no response, I take it that my suggestion was accepted and I am closing the ticket.
