### ISSUE TITLE
python:: monitoring stream:: data structures

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1527]
Hi! It would be great if the python bindings could contain also the data structures of the monitoring stream to make it easier to process them in python. A real wonderful work is already done by @maxfischer2781 in his project https://github.com/maxfischer2781/xrootdlib/  but i think that at least data structures should be defined upstream as to have a reference (and always right) implementation of data content. (after this, contributions of interested parties would be easier to be made).
Thank you!

**Comment by abh3** [comment]
I believe OSG has these already for their Python based collector. Let me 
ask if they can help here.

**Comment by abh3** [comment]
Where are we with this? I don't see a clear next step other than closing the ticket.

**Comment by simonmichal** [comment]
@adriansev : after a discussion within the team we decided we don't have enough manpower to provide those Python interfaces within the core framework, that said we are always happy to receives a PR (preferably from someone who would commit to maintain those interfaces.)

**Comment by adriansev** [comment]
i see, thanks for info!
