### ISSUE TITLE
Auto-generated login token has initial `?`

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#1535]
The xrdcp client will generate a login token that contains various pieces of environmental information the server might find useful.

For the most part, this information is serialised as key-value pairs, with `=` separating the key and value, and a  `&` separating two key-value pairs.  The keys are organised into a namespace, with values starting with the `xrd.` prefix.

However, this information is (inexplicitly) sent as a login token with a `?` prefix.

Here is an example:

```
?xrd.cc=de&xrd.tz=1&xrd.appname=xrdcp&xrd.info=&xrd.hostname=sprocket.desy.de&xrd.rn=v20211011-f1d4e89e2
```
This is odd because a login token may also be provided by the server as part of the `kXR_redirect` response.  In that response the `?` character plays a significant role in framing/serialising the response.

Therefore, this looks like a mistake and the token shouldn't include the initial `?`.

If so, the above login token should have been:

```
xrd.cc=de&xrd.tz=1&xrd.appname=xrdcp&xrd.info=&xrd.hostname=sprocket.desy.de&xrd.rn=v20211011-f1d4e89e2
```

**Comment by paulmillar** [comment]
Up until now, dCache simply ignored the login token.

I'm adding support in dCache (and so catching these idiosyncrasies) because I think it could lead to a more robust behaviour for the client; for example, by using login tokens, the change (where xrdcp queried a xroot-TPC copied file's checksum over a separate TCP connection) that broke xroot-TPC with dCache as the destination _could_ have been supported if dCache used login tokens.

In #1534 I've suggested some text that includes something on how an initial `?` should be ignored.

**Comment by simonmichal** [comment]
@paulmillar : yep you're right, it shall be fixed
