### ISSUE TITLE
Add mapfile support for XrdVoms

### ISSUE THREAD

**Issue by matyasselmeci** [xrootd/xrootd#1538]
We'd like to be able to create a mapfile for voms authentication such that we can choose the mappings between FQANs and Unix users; this is needed for multiuser to work. VOMS mapfiles are made of lines like

    "FQAN-PATTERN" USERNAME

where USERNAME is a Unix user and FQAN-PATTERN is a glob.

For GSI, mapfile support is built in, but we've been told it's better to write a post-auth plugin for VOMS instead.

**Comment by bbockelm** [comment]
Hey Wei,

I think the VOMS mapfile tackles the case where there's an underlying storage system that really needs a "user name" that can't be derived algorithmically via the FQAN.

Examples I know about are EOS and xrootd-multiuser (the former does the "VOMS mapfile" by converting a VOMS FQAN to a long list of DNs and maps those to a single username... that kinda works but is problematic for other reasons).

Brian

**Comment by abh3** [comment]
Brian kindly provided a patch for this, so I am closing this ticket. This should appear in 5.5.0.
