### ISSUE TITLE
File open with the python fails from time to time 

### ISSUE THREAD

**Issue by bockjoo** [xrootd/xrootd#1539]
Files are accessible from xrdcp but opening them times out with the python open.
As a result, the SAM tests are failing from time to time.
Because of the intermittent failure, it's difficult for me to reproduce the issue.
Why is the python open behaving differently from the xrdcp?

**Comment by simonmichal** [comment]
@bockjoo : thanks for reporting this problem, and sorry for the late reply!

>  Why is the python open behaving differently from the xrdcp?

Now this is an excellent question! Both `xrdcp` and the python bindings call same `C++` implementation of open. Could you please share the error message? Also, it would be great if you could enable client side logging (`export XRD_LOGLEVEL=Dump`) and post here the respective logs?

**Comment by abh3** [comment]
What is the status of this request Bokjoo? Shall we close this?

**Comment by bockjoo** [comment]
Hi Andy,
Sorry for late response!
Yes, this symptom disappeared with recent updates.
You may close this one.
Thanks,
Bockjoo

**Comment by abh3** [comment]
Problem solved.
