### ISSUE TITLE
[XrdHttpTpc] Set CLOEXEC for curl file descriptors.

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1566]
It would be great if the `CURL` transfer agent could set the `CLOEXEC` flags when opening file descriptors, here are some details on how to do this:
https://curl.se/libcurl/c/CURLOPT_SOCKOPTFUNCTION.html

**Comment by ccaffy** [comment]
Closed by this PR: https://github.com/xrootd/xrootd/pull/1653
