### ISSUE TITLE
XrdSciTokens default mapping not applied

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1567]
When using a simple configuration for scitokens as the following one, for example:

```
[Global]
audience = https://wlcg.cern.ch/jwt/v1/any,https://elvin-dev01.cern.ch

[Issuer OSG-Connect]
issuer = https://wlcg.cloud.cnaf.infn.it/
base_path = /
map_subject = False
default_user = dteam001
```

The default user is not propagated to the XrdSecEntity structure since there is not rule to apply and this then defaults to setting an empty string for the username:
https://github.com/xrootd/xrootd/blob/master/src/XrdSciTokens/XrdSciTokensAccess.cc#L244

Therefore, a few lines below both `scope` and `mapping` are false, so this falls through any configured chained library:
https://github.com/xrootd/xrootd/blob/master/src/XrdSciTokens/XrdSciTokensAccess.cc#L387

This was behaving differently in the 4.8.* branch, where the given `default_user` was properly passed to the XrdSecEntity structure using the same configuration as above.

**Comment by bbockelm** [comment]
Hi Elvin,

Isn't this related to the other ticket?  Default user is only set when there's scope-based mapping... otherwise you end up with quite broad permissions if there's no storage authorizations.

https://github.com/xrootd/xrootd/blob/master/src/XrdSciTokens/XrdSciTokensAccess.cc#L398-L401

Brian

**Comment by abh3** [comment]
That's quite true but I assume the idea is that there is authorization 
that is stacked behind the SciToken auth plug-in. We could set an envar 
indicating that this is actually the case and then the code could set the 
username if further user-based authorization exists and not so otherwise.

**Comment by bbockelm** [comment]
Yes - we can also make it a config option.  I guess I just want to understand the use case a bit better.

Elvin, let's say I give you a pilot token - which explicitly should NOT be used for storage.  What would you want to do with the extracted username in the stacked authorization module?

**Comment by esindril** [comment]
Hi Brian,

Let me give you a bit of background on this - indeed this is also related to the other ticket. I started looking at the results of the "WLCG JWT compliance tests", like for example this one:
https://ci.cloud.cnaf.infn.it/job/wlcg-jwt-compliance-tests/job/master/lastSuccessfulBuild/artifact/reports/reports/latest/joint-log.html#s1-s5

My aim was to make EOS pass as many tests as possible. One example that is expected to pass is "Read access granted for WLCG members" which uses a token like this: `oidc-token -s openid  wlcg 2>&1`. It looks to me that such a token scope will never be satisfied for a storage element. So my assumption was that if at least the mapping works then the chained authz plugin will use the username to actually check if the user has the rights for the requested operation and reply accordingly. Otherwise, such a request will just fail as it currently happens.

Thanks,
Elvin

**Comment by bbockelm** [comment]
Hi Elvin,

I think the test is wrong.  Let's bring it up on the mailing list.  A token with no authorizations should not imply unrestricted access (well, in my opinion!)...

Brian

**Comment by esindril** [comment]
Hi Brian, 

Indeed, it also looks to me that the expectations from these tests are a bit inconsistent. FWIW, there are some prerequisites concerning these tests, but they seem contradictory: 
https://github.com/indigo-iam/wlcg-jwt-compliance-tests/tree/master

Sure, we can follow this up over email.

Thanks,
Elvin

**Comment by abh3** [comment]
So, the presumption is that this will continue offline. So, I am closing this ticket.
