### ISSUE TITLE
Improve the mapfile defaults

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1577]
Around 5.0, we cleaned up the default TLS settings such that both the xrootd and http protocols could share the same configuration knobs -- e.g., you set the CA location once and it goes into effect for both protocols.

Currently, however, the mapfile settings for each protocol are different by default.  Could they be similarly unified?

**Comment by abh3** [comment]
OK, but given that this stuff is quicklt fading into oblivion do we really need to spend time on something that will become irrelevant in a short while?

**Comment by bbockelm** [comment]
Yup, I think this has far decreased in importance over the last few years.

(Since I opened the ticket originally, seems like I can also close the ticket)
