### ISSUE TITLE
Codify support for Python 2 and Python 3 in tests

### ISSUE THREAD

**Issue by matthewfeickert** [xrootd/xrootd#1588]
Hi. While trying to run tests for PR #1585 I realized that the tests for the Python bindings are written to be Python 2 only (as of 98d83fb4b70159f31c3311ce9d1d217874ccef45). Doing some quick checks with a rough pass of 

```
2to3 --write .
```

also show that the examples and tests all contain Python 2 only code.

* The `bindings/python/examples/` can be easily fixed by just properly applying the `print()` function.
* The `bindings/python/tests/` are mostly also just need `print()` functions but also have some string encoding differences and a breaking `xrange` vs. `range` change

https://github.com/xrootd/xrootd/blob/98d83fb4b70159f31c3311ce9d1d217874ccef45/bindings/python/tests/test_threads.py#L31

* I see that there has been some work and care put into ensuring that the Python 2 only code in `bindings/python/libs/` is properly guarded, so I think that's fine as is. :+1: 

To be able to run tests I'm willing to contribute a PR that updates the example and tests code to Python 3, but is there a desire to continue to run the tests for Python 2? I don't know how long the XRootD team plans to support Python 2 as it is now EOL for over a year and there isn't any clear statements in the docs about LTS given that the supported OS part of the docs

https://github.com/xrootd/xrootd/blob/98d83fb4b70159f31c3311ce9d1d217874ccef45/README#L12-L19

was [added 10 years ago in 2011](https://github.com/xrootd/xrootd/commit/e5a2ad11456b18fa24b04f483bbeef481635488c) and I don't think is accurate anymore.

Also, if I have this correct, is the https://gitlab.cern.ch/dss/xrootd GitLab mirror used to run the CI. Do you have instructions on how to have contributed PRs run the CI _before_ they get merged so that PRs can link a passing test suite?

**Comment by simonmichal** [comment]
@matthewfeickert : sorry for the late reply, there's no need to keep the tests compatible with Python2, if you could submit a PR that ports them to Python3 it would be great. (Unfortunately we are not able at the moment to run the CI in gitlab for PR.)

**Comment by amadio** [comment]
Since we will drop support for Python 2.x in XRootD 6.0.0, I'm marking this with that milestone, but will try to port the tests to Python 3.x and add them to run in our CI earlier than that (and mark the correct milestone fixing this later on).
