### ISSUE TITLE
Resolve tag discrepancy with Python packages

### ISSUE THREAD

**Issue by matthewfeickert** [xrootd/xrootd#1604]
> @matthewfeickert : I just notice two problems after merging #1585:
> 
> - cannot uninstall the package anymore:
> ```
> [root@77ad5541c633 xrootd]# python3 -m pip uninstall xrootd                  
> Can't uninstall 'xrootd'. No files were found to uninstall.
> ```
> - if I tag the repository, say: `git tag -a v6.0.0 -m test` it is no longer possible to install the package:
> ```
> [root@77ad5541c633 xrootd]# cp packaging/wheel/* .
> [root@77ad5541c633 xrootd]# ./publish.sh
> [root@77ad5541c633 xrootd]# python3 -m pip install dist/xrootd-6.0.0.tar.gz 
> WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
> Processing ./dist/xrootd-6.0.0.tar.gz
>   Requirement already satisfied (use --upgrade to upgrade): xrootd==6.0.0 from file:///xrootd/dist/xrootd-6.0.0.tar.gz in /xrootd
> Building wheels for collected packages: xrootd
>   Running setup.py bdist_wheel for xrootd ... done
>   Running setup.py clean for xrootd
> Failed to build xrootd
> ```
> 
> Could you please fix those two regressions?

_Originally posted by @simonmichal in https://github.com/xrootd/xrootd/issues/1602#issuecomment-1022376828_

**Comment by matthewfeickert** [comment]
@simonmichal for reproduction are you using the workflow described here https://github.com/xrootd/xrootd/pull/1585#issuecomment-1021344620?

I'll open PRs for these, but my (maybe wrong hunch) might be related to the fact that the naming scheme that you currently use violates PEP 440 (I have fixes for that already on my fork, but want to step through things in PRs so it is easy to understand when/why things might cause problems like this).

**Comment by simonmichal** [comment]
correct, I was using the same workflow as in #1585, thanks for taking care of it!

**Comment by matthewfeickert** [comment]
@simonmichal I am unable to reproduce your experience and see no regression. The following works as expected:

```Dockerfile
FROM cern/cc7-base:latest

RUN yum update -y && \
    yum install --nogpg -y \
        cmake3 \
        make \
        krb5-devel \
        libuuid-devel \
        libxml2-devel \
        openssl-devel \
        systemd-devel \
        zlib-devel \
        devtoolset-7-gcc-c++ \
        which \
        python3-devel \
        python3-setuptools \
        git \
        cppunit-devel && \
    python3 -m pip install --upgrade pip setuptools wheel

ENV OFFENDING_COMMINT=65950acd7ab15dc91e31fdc4de089e14d474ecf9
RUN . /opt/rh/devtoolset-7/enable && \
    git clone https://github.com/xrootd/xrootd && \
    cd xrootd && \
    git reset --hard ${OFFENDING_COMMINT} && \
    git show HEAD && \
    git config --global user.email "test@test.com" && \
    git config --global user.name "test test" && \
    git tag -a v6.0.0 -m test && \
    git tag && \
    cp packaging/wheel/* . && \
    ./publish.sh && \
    python3 -m pip --verbose install dist/xrootd-*.tar.gz && \
    python3 -m pip list
```

build with

```console
$ docker build . -f docker/Dockerfile --tag xrootd/xrootd:debug-uninstall
```

and the following works

```console
$ docker run --rm -ti xrootd/xrootd:debug-uninstall
[root@eab92ce8483c /]# python3 -m pip list
WARNING: No metadata found in /usr/local/lib64/python3.6/site-packages
WARNING: No metadata found in /usr/local/lib64/python3.6/site-packages
Package            Version
------------------ -------
build              0.7.0
importlib-metadata 4.8.3
packaging          21.3
pep517             0.12.0
pip                21.3.1
pyparsing          3.0.7
setuptools         59.6.0
tomli              1.2.3
typing_extensions  4.0.1
wheel              0.37.1
xrootd             6.0.0
zipp               3.6.0
[root@eab92ce8483c /]# python3 -m pip show xrootd
WARNING: No metadata found in /usr/local/lib64/python3.6/site-packages
WARNING: No metadata found in /usr/local/lib64/python3.6/site-packages
WARNING: No metadata found in /usr/local/lib64/python3.6/site-packages
Name: xrootd
Version: 6.0.0
Summary: 
Home-page: 
Author: 
Author-email: 
License: 
Location: /usr/local/lib64/python3.6/site-packages
Requires: 
Required-by: 
[root@eab92ce8483c /]# python3 -c 'from XRootD import client; print(client.FileSystem("root://someserver:1094"))'
<XRootD.client.filesystem.FileSystem object at 0x7f0facbfa2b0>
[root@eab92ce8483c /]# python3 -m pip uninstall -y xrootd
Found existing installation: xrootd 6.0.0
Uninstalling xrootd-6.0.0:
  Successfully uninstalled xrootd-6.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@eab92ce8483c /]# python3 -m pip show xrootd
WARNING: Package(s) not found: xrootd
[root@eab92ce8483c /]# 

```

Can you please make sure that you are testing with a clean environment?

**Comment by simonmichal** [comment]
The environment is absolutely fresh, here's what I am doing:
```
docker run -it --rm cern/cc7-base /bin/bash
[root@e76590fa385f xrootd]# yum install --nogpg -y git python3-pip which
[root@e76590fa385f xrootd]# git clone https://github.com/xrootd/xrootd
[root@e76590fa385f xrootd]# cd xrootd
[root@e76590fa385f xrootd]# git tag -a v6.0.0 -m test
[root@e76590fa385f xrootd]# cp packaging/wheel/* .
[root@e76590fa385f xrootd]# ./publish.sh
[root@e76590fa385f xrootd]# python3 -m pip install dist/xrootd-6.0.0.tar.gz 
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Processing ./dist/xrootd-6.0.0.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): xrootd==6.0.0 from file:///xrootd/dist/xrootd-6.0.0.tar.gz in /xrootd
Building wheels for collected packages: xrootd
  Running setup.py bdist_wheel for xrootd ... done
  Running setup.py clean for xrootd
Failed to build xrootd
```

**Comment by simonmichal** [comment]
Just to clarify without the dummy tag (`git tag -a v6.0.0 -m test`) it works just fine.

**Comment by matthewfeickert** [comment]
> The environment is absolutely fresh, here's what I am doing:
> 
> ```
> docker run -it --rm cern/cc7-base /bin/bash
> [root@e76590fa385f xrootd]# yum install --nogpg -y git python3-pip which
> [root@e76590fa385f xrootd]# git clone https://github.com/xrootd/xrootd
> [root@e76590fa385f xrootd]# cd xrootd
> [root@e76590fa385f xrootd]# git tag -a v6.0.0 -m test
> [root@e76590fa385f xrootd]# cp packaging/wheel/* .
> [root@e76590fa385f xrootd]# ./publish.sh
> [root@e76590fa385f xrootd]# python3 -m pip install dist/xrootd-6.0.0.tar.gz 
> WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
> Processing ./dist/xrootd-6.0.0.tar.gz
>   Requirement already satisfied (use --upgrade to upgrade): xrootd==6.0.0 from file:///xrootd/dist/xrootd-6.0.0.tar.gz in /xrootd
> Building wheels for collected packages: xrootd
>   Running setup.py bdist_wheel for xrootd ... done
>   Running setup.py clean for xrootd
> Failed to build xrootd
> ```

Your example is unfortunately not reproducible and 

> Just to clarify without the dummy tag (`git tag -a v6.0.0 -m test`) it works just fine.

is not reproducible either. `cern/cc7-base:latest` does not contain any of the necessary build dependencies, so the instructions you have above aren't able to be reproduced as the install command will fail as it lacks the tools to build from the sdist.

Here's a minimal failing example that demonstrates the lack of build dependencies in your base image:

```Dockerfile
FROM cern/cc7-base:latest

RUN yum update -y && \
    yum install --nogpg -y \
        git \
        python3-pip \
        which

ENV OFFENDING_COMMINT=65950acd7ab15dc91e31fdc4de089e14d474ecf9
RUN git clone https://github.com/xrootd/xrootd && \
    cd xrootd && \
    git reset --hard ${OFFENDING_COMMINT} && \
    git show HEAD && \
    cp packaging/wheel/* . && \
    ./publish.sh

# This will fail as lacking all build dependencies
RUN cd xrootd && \
    python3 -m pip --verbose install dist/xrootd-*.tar.gz && \
    python3 -m pip list
```

```console
$ docker pull cern/cc7-base:latest
latest: Pulling from cern/cc7-base
Digest: sha256:e2dd774d6abce5e67eaa561e599f999085524f99e0ed10acffa40b050db89d17
Status: Image is up to date for cern/cc7-base:latest
docker.io/cern/cc7-base:latest
$ docker images cern/cc7-base:latest
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
cern/cc7-base   latest    e1b07fd8b81c   8 weeks ago   311MB
$ docker build . -f Dockerfile --tag xrootd/xrootd:debug-uninstall
```
```
...
Step 5/5 : RUN cd xrootd &&     python3 -m pip --verbose install dist/xrootd-*.tar.gz &&     python3 -m pip list
 ---> Running in 4fe29c3a0d75
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Processing ./dist/xrootd-20220126-65950ac-.tar.gz
  Running setup.py (path:/tmp/pip-k30jrsoa-build/setup.py) egg_info for package from file:///xrootd/dist/xrootd-20220126-65950ac-.tar.gz
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/xrootd.egg-info
    writing pip-egg-info/xrootd.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/xrootd.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/xrootd.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/xrootd.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/xrootd.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/xrootd.egg-info/SOURCES.txt'
  Source in /tmp/pip-k30jrsoa-build has version 20220126, which satisfies requirement xrootd==20220126 from file:///xrootd/dist/xrootd-20220126-65950ac-.tar.gz
Building wheels for collected packages: xrootd
  Running setup.py bdist_wheel for xrootd: started
  Destination directory: /tmp/tmpngo5wj1bpip-wheel-
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-k30jrsoa-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpngo5wj1bpip-wheel- --python-tag cp36
  running bdist_wheel
  Running setup.py bdist_wheel for xrootd: finished with status 'done'
  Running setup.py clean for xrootd
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-k30jrsoa-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  'build/lib' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
Failed to build xrootd
Installing collected packages: xrootd
  Running setup.py install for xrootd: started
    Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-k30jrsoa-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aktgv7n8-record/install-record.txt --single-version-externally-managed --compile
    running install
    ./has_c++14.sh: line 8: cmake3: command not found
    Some dependencies are missing:
    	cmake (version 3) is missing!
    	make is missing!
    	C++ compiler is missing (g++, c++, clang, etc.)!
    	zlib development package is missing!
    	openssl development package is missing!
    	python3 development package is missing!
    	uuid development package is missing
    	devtoolset-7-gcc-c++ package is missing
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-k30jrsoa-build/setup.py", line 195, in <module>
        'bdist_wheel': CustomWheelGen
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-k30jrsoa-build/setup.py", line 142, in run
        raise Exception( 'Dependencies missing!' )
    Exception: Dependencies missing!
    Running setup.py install for xrootd: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-k30jrsoa-build
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-k30jrsoa-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aktgv7n8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-k30jrsoa-build/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 882, in install
    spinner=spinner,
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 717, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-k30jrsoa-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aktgv7n8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-k30jrsoa-build/
The command '/bin/sh -c cd xrootd &&     python3 -m pip --verbose install dist/xrootd-*.tar.gz &&     python3 -m pip list' returned a non-zero code: 1
```

Can you please pull `cern/cc7-base:latest` and verify that your image is the same?

**Comment by kratsg** [comment]
@simonmichal your `publish.sh` script isn't actually building the wheel. All it's doing is creating a source distribution (`sdist`) and just copies files over. Your goal is to build -- based on your MRE -- a package that is `pip install`-able, which means you want a wheel given you have python bindings in this package. You should drop the `--sdist` command to actually build the wheel

```
$  python3 -m build .
```

which will quickly run into errors due to missing dependencies in the `cc7` base image. To be clear, you could've just used `python:3` for your example since all you're doing is building an `sdist` (and I've checked and it works with just `python:3`) so your MRE isn't really enlightening.

**Comment by matthewfeickert** [comment]
> You should drop the `--sdist` command to actually build the wheel

@kratsg I put the `--sdist` flag in explicitly in 111662e7c52ce3d4d5ecbe0d8054d45d6063d954 in PR #1585 because XRootD has things named confusingly as `packaging/wheel/publish.sh` has never built wheels, but always only built sdists (This is most easily seen by just checking the contents of PyPI and noting that everything on is an sdist (made even easier with the simple view): https://pypi.org/simple/xrootd/).

The maintainers already know all of this though as wheel building is actively disabled (as of [`v5.0.0-rc2`](https://github.com/xrootd/xrootd/releases/tag/v5.0.0-rc2))

https://github.com/xrootd/xrootd/blob/93839a8001e75af4e29bc086d1b7b2cd94645c7f/packaging/wheel/setup.py#L174-L177

https://github.com/xrootd/xrootd/blob/93839a8001e75af4e29bc086d1b7b2cd94645c7f/packaging/wheel/setup.py#L192-L195

so I assume (maintainer please correct me if I'm totally wrong) the maintainers' plan is to enable wheel building at some later date using different tools (`cibuildwheel` would probably be handy here).

**Comment by simonmichal** [comment]
@kratsg & @matthewfeickert : well, I'm not an expert on pip packaging (actually the person who did the packaging left the team while ago), now my understanding is that the wheel is not build because number packages you can build against once you push a release to pip is very limited and not enough to build xrootd, so it has been on purpose done so everything is build on install.


@matthewfeickert :  in your docker image you don't tag it, don't you? It does complain about the missing dependencies but that's expect (that's what I meant it works just fine ;-) sorry for the confusion!!!):

```
FROM cern/cc7-base:latest

RUN yum update -y && \
    yum install --nogpg -y \
        git \
        python3-pip \
        which

ENV OFFENDING_COMMINT=65950acd7ab15dc91e31fdc4de089e14d474ecf9
RUN git clone https://github.com/xrootd/xrootd && \
    cd xrootd && \
    git reset --hard ${OFFENDING_COMMINT} && \
    git show HEAD && \
    cp packaging/wheel/* . && \
    ./publish.sh

# This will fail as lacking all build dependencies
#
# Run pip install from outside of xrootd Git repo directory to avoid
# xrootd.egg-info artifact from publish.sh that pollutes PYTHONPATH
# which includes the local directory by default
RUN python3 -m pip --verbose install /xrootd/dist/xrootd-*.tar.gz && \
    python3 -m pip list
```

while, in my example if I tag the repo (for example **git tag -a v6.0.0 -m test**) and then publish and try to build it fails without giving me any reason why: 

```
Building wheels for collected packages: xrootd
  Running setup.py bdist_wheel for xrootd ... done
  Running setup.py clean for xrootd
Failed to build xrootd
```

did you actually try to tag it?

Just for the record, the necessary build dependencies are:
```
yum -y install cmake3 make gcc-c++ zlib-devel openssl-devel python3-devel libuuid-devel devtoolset-7-gcc-c++
```

**Comment by simonmichal** [comment]
So just to summarise, this works:

```
docker run -it --rm cern/cc7-base:latest /bin/bash
yum install --nogpg -y git python3-pip which
git clone https://github.com/xrootd/xrootd
cd xrootd
cp packaging/wheel/* .
./publish.sh
yum -y install cmake3 make gcc-c++ zlib-devel openssl-devel python3-devel libuuid-devel devtoolset-7-gcc-c++
python3 -m pip install dist/xrootd-6.0.0.tar.gz
```

and this does not:

```
docker run -it --rm cern/cc7-base:latest /bin/bash
yum install --nogpg -y git python3-pip which
git clone https://github.com/xrootd/xrootd
cd xrootd
git config --global user.email "whatever@whatever.com"
git config --global user.name "whatever whatever"
git tag -a v6.0.0 -m test
cp packaging/wheel/* .
./publish.sh
yum -y install cmake3 make gcc-c++ zlib-devel openssl-devel python3-devel libuuid-devel devtoolset-7-gcc-c++
python3 -m pip install dist/xrootd-6.0.0.tar.gz
```

How about a zoom call to discuss this in more details, let me know if this would help :-)

**Comment by matthewfeickert** [comment]
> now my understanding is that the wheel is not build because number packages you can build against once you push a release to [PyPI] is very limited and not enough to build xrootd

As far as I know (which isn't much), this is luckily not correct. XRootD does not have a large number of build dependencies compared to some of the most difficult Python libraries to build wheels for (e.g. TensorFlow, PyTorch). Maybe in the future we can have some discussions about wheel building, but that's for another Issue. :+1: (Here I would probably see if you could get @henryiii (a true expert of the entire Python packaging world) to give some advice on wheel building, but I think `cibuildwheel` would be the way to go.) 

> in your docker image you don't tag it, don't you?
...
> it fails without giving me any reason why

Please see the the example in https://github.com/xrootd/xrootd/issues/1604#issuecomment-1022498193 for a tag with things working and installing successfully. For examples of things failing in 970d86d see the two examples that I gave above in https://github.com/xrootd/xrootd/issues/1604#issuecomment-1022632219 

> Example of failing with 970d86d:
>
> Example of failing with 970d86d and git tag:

where I show it failing for untagged and tagged.

> How about a zoom call to discuss this in more details, let me know if this would help

If we need to have a Zoom call, but I think it would be faster to go through the Dockerfile examples I've given.

As I've mentioned (but only in code comments, which isn't great), one of the problems that you have in your copy-and-paste commands examples is that running `pip install` from inside the `xrootd` Git repo directory will have problems as the `xrootd.egg-info` artifact from `publish.sh` pollutes `PYTHONPATH` which includes the local directory by default (this has been true since before PR #1585).

Here's a copy-and-paste set of commands that demonstrates and succeeds:

```
$ docker run -it --rm cern/cc7-base:latest /bin/bash
yum install --nogpg -y git python3-pip which cmake3 make gcc-c++ zlib-devel openssl-devel python3-devel libuuid-devel devtoolset-7-gcc-c++
git config --global user.email "whatever@whatever.com"
git config --global user.name "whatever whatever"
git clone https://github.com/xrootd/xrootd  # Same things apply to 970d86d as to HEAD
cd xrootd
git tag -a v6.0.0 -m test
cp packaging/wheel/* .
./publish.sh
# 3 options now of how to have an install suceed:
# 1. Run with --upgrade flag to override the existence of what it thinks already lives on PYTHONPATH
# python3 -m pip install --verbose --upgrade dist/xrootd*.tar.gz
# 2. Run from anywhere not the xrootd directory (you're building from an sdist)
# cd  && python3 -m pip install --verbose /xrootd/dist/xrootd*.tar.gz
# This is what I've demonstrated in my previous examples
# 3. Rename or delete the `xrootd.egg-info` that `publish.sh` builds
# which we'll run here
mv xrootd.egg-info any_other_name
python3 -m pip install --verbose dist/xrootd*.tar.gz
python3 -m pip list
```

Does this make sense? If not we can try to setup a Zoom call for me to explain more.

I agree that the `publish.sh` workflow could get improved so that these sorts of rather not obvious things don't pop up. We can do that in another PR later, but let's make a separate GitHub Issue for it. :+1:

**Comment by simonmichal** [comment]
@matthewfeickert : thanks for the comments, I will give it a try first thing tomorrow! Regarding pip / python packaging would you be willing to join our collaboration and take over the this part (or maybe there's someone you could recommend)?

**Comment by matthewfeickert** [comment]
> thanks for the comments, I will give it a try first thing tomorrow!

Sounds good and thanks for the ping on Mattermost (:wave:). If we need to have a call we can aim for next week. :+1: 

> Regarding pip / python packaging would you be willing to join our collaboration and take over the this part (or maybe there's someone you could recommend)?

I appreciate the offer, but I'm a bit wary to commit to joining the collaboration as I do not want to commit to any work that I can't prioritize and I don't want to disappoint people or end up creating additional work for others if I fall through. Between my software work for ATLAS, IRIS-HEP, and Scikit-HEP, I'm already probably at the limits of what I can responsibly commit to. That being said, I'm happy to make contributions where I can for packaging and also help out if there are areas where you and the rest of the maintainer team don't have the bandwidth to prioritize it at the moment. XRootD is used _everywhere_ in HEP and if there are small contributions I can make that are helpful (and not a time burden for the maintainers) I'm happy to do so. 

As far as other people I might recommend, most of them are already even more overburdened with software responsibilities than me. I don't think he has the time at the moment, but I will mention that @aryan26roy did an _amazing_ job with the `pybind11` Python bindings for FastJet: https://github.com/scikit-hep/fastjet :rocket: Not only was everyone in Scikit-HEP impressed with his work, but the FastJet authors were also quite excited to have a clean and robust solution. So even if @aryan26roy is too busy at the moment to work on this directly he can probably offer lots of good advice if pinged. :)

**Comment by simonmichal** [comment]
@matthewfeickert : OK, works like a charm, thanks for the copy-and-paste set of commands that walk me through the building process, `uninstall` also works :-) I think in this case we can close this one :-)

Again thanks a lot for your contributions and suggestion!

> I appreciate the offer, but I'm a bit wary to commit to joining the collaboration as I do not want to commit to any work that I can't prioritize and I don't want to disappoint people or end up creating additional work for others if I fall through.

 it's really a pity, we wouald love to have you on board ;-)
