### ISSUE TITLE
Xcode 12 build error due to XrdSysPlatform.hh / posix_memalign

### ISSUE THREAD

**Issue by Axel-Naumann** [xrootd/xrootd#1611]
Hi,

A ROOT user [reports](https://root-forum.cern.ch/t/compile-root-with-apple-m1max/48664):

```
In file included from /Users/xin/onedrive/program/physics/tools/rootmax/XROOTD-prefix/src/XROOTD/src/XrdNet/XrdNetIF.cc:48:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/__locale:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/string:511:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/string_view:179:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/__string:57:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/algorithm:653:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/memory:673:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/new:319:5: error: expected unqualified-id
  ::posix_memalign(&__result, __alignment, __size);
    ^
/Users/xin/onedrive/program/physics/tools/rootmax/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPlatform.hh:126:9: note: expanded from macro 'posix_memalign'
        ((*memp = memalign(algn, sz)) ? 0 : ENOMEM)
        ^
```

It seems - courageous to `#define` `posix_memalign` if the stdlib is using it itself?

Cheers, Axel

**Comment by simonmichal** [comment]
@Axel-Naumann : thanks for letting us know, from what I see the offending code has been removed in 9ec715be74370746efb3ab9de4ce90d3ee584342, if I remember correctly this has been released in 5.1.0, to clarify I've asked the user to provide the version of xrootd he's using on root-forum.

Just for the record, right now we only have:
https://github.com/xrootd/xrootd/blob/f2fdaf0044d57537348f95841420636052b2e551/src/XrdSys/XrdSysPlatform.hh#L91-L95
to uphold historical support for solaris.

**Comment by Axel-Naumann** [comment]
Thanks! I didn't find the error submitted in your issues so thought it's worthwhile to leave a trace nonetheless :-)

And indeed, for ROOT v6.24 we pull your 4.12.8 by default.

**Comment by To-be-or-not** [comment]
Hi experts,
      I am using apple M1max. I am trying to install root6.24.06(the latest one) with python following this guide
     “[Building ROOT from source - ROOT](https://root.cern/install/build_from_source/)”
     When I tried “cmake --build . – -j10”, there is an error like:

     CMake Error at /Users/xin/onedrive/program/physics/tools/rootmax/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build- 
      Release.cmake:49 (message):
     Command failed: 2

     ‘/Library/Developer/CommandLineTools/usr/bin/make’
    See also
    /Users/xin/onedrive/program/physics/tools/rootmax/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-*.log

    Here is the log link:
   [https://drive.google.com/drive/folders/1e-zZVhvcs8bHeQgsgiMzvaL8-h15V1C7?usp=sharing](https://drive.google.com/drive/folders/1e-zZVhvcs8bHeQgsgiMzvaL8-h15V1C7?usp=sharing)
