### ISSUE TITLE
XrdCl: Opaque information during open recovery?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#162]
Hi,

(Full debug log is here: http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms1590/141114_184357_crab3test-2:bbockelm_crab_xrd_multi1/job_out.36.0.txt)

During a file-open recovery, the client keeps the opaque information from dCache (org.dcache.uuid=63425c0f-eefc-4990-83ec-82a4419d4e50) when it returns to the redirector.  This later gets passed to other sites within the federation.

If we return to the redirector, other than updating tried, should we keep all opaque info?

Brian

PS - Is there a way to disable automatic recovery?  We kinda re-implement it within CMSSW now.

**Comment by abh3** [comment]
This has been fixed in 4.2. The server is now propagating the opaque information. It also allows the server to test for redirection loops.
