### ISSUE TITLE
`xrootd-client-libs-5.4.1-1.el7.x86_64.rpm` not signed in stable repos

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1631]
It seems the package is not signed, preventing installation:
```
$ wget  http://xrootd.org/binaries/stable/slc/7/x86_64/xrootd-client-libs-5.4.1-1.el7.x86_64.rpm
$ rpm -qpi  xrootd-client-libs-5.4.1-1.el7.x86_64.rpm | grep Signature
Signature   : (none)
$ yum update
....
Package xrootd-client-libs-5.4.1-1.el7.x86_64.rpm is not signed
```

**Comment by simonmichal** [comment]
@olifre : thanks for reporting this, I will run respective scripts tomorrow to fix the problem.

**Comment by simonmichal** [comment]
@olifre : the RPM is signed now:
```
$ rpm -qpi xrootd-client-libs-5.4.1-1.el7.x86_64.rpm | grep Signature
Signature   : RSA/SHA1, Wed 02 Mar 2022 04:27:59 PM CET, Key ID 1207a669ac9b8588
```

Could you please confirm that it works for you?

**Comment by olifre** [comment]
@simonmichal Indeed, I can confirm it works now — both for version 5.4.1 and also for the fresh bugfix release 5.4.2 (tested on CentOS 7). Many thanks! :+1:
