### ISSUE TITLE
[RFC] [XrdHttp] Using 307 for redirects instead of 302?

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1638]
Dear XRootD devs,

trying to use rclone against an XRootD redirector using `cms.dfs lookup distrib`, I realized it fails. The cause is that the Go stdlib would rewrite the request method to `GET` when a 302 status is encountered. 

Going through history, it seems the cause is that 302 allowed clients to rewrite the request method to `GET` at least for `POST` requests, as shown in [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-10.3.3). 
Later on, it was recommended to clarify server intent by using one of:
* `303` in case the request method should indeed be changed to `GET`. 
* `307` in case the request method should be kept on redirect. 

You can find a more in-depth discussion at:
* https://github.com/rclone/rclone/issues/6029
* https://github.com/golang/go/issues/41377

dCache seems to use 307 at least on `PUT` requests, to clarify the request method should not be changed upon redirect:
https://github.com/dCache/dcache/blob/edb81b0cc1120721137e15f32800ee4dc7a740c4/skel/share/defaults/webdav.properties#L258-L260

Before trying to push a workaround into rclone, I wonder whether there would be any concerns against changing XrdHttp to use 307 for redirects instead of 302? 
So I am opening this as an RFC to get opinions.

**Comment by ffurano** [comment]
Hello Oliver,

 so, to summarize, you propose that POST and PUT requests get a 307 instead than 302, did I correctly understand?

 If this is the case I do not see blocking concerns, and I don't remember having heard of Davix/Gfal being problematic for that.
 I can have a better lookat the details tomorrow, as I get back to the office. 

Please let me know
Fabrizio

**Comment by ffurano** [comment]
Hi Oliver, would you like to try out the master branch? I have merged in a simple improvement that should do what you describe.
Please let me know, thanks

**Comment by olifre** [comment]
@ffurano I also found we should add:
```cpp
    else if (code == 307) ss << "Temporary Redirect";
``
in `XrdHttpProtocol::StartSimpleResp` so we won't send `Unknown` along with `307` ;-).

**Comment by ffurano** [comment]
Hi Oliver,

 thanks for the feedback, I am committing your two proposed changes.

 About redirection on PUT... that's a very long story, a minority of the mainstream clients support it. I hope that they enhance the go code that you are using.

**Comment by olifre** [comment]
Hi Fabrizio,

many thanks! This works perfectly, so I think there is nothing more XRootD / `XrdHttp` can to in terms of compatibility with other tools such as `rclone`. 
I also delved a bit more into dCache code and now understand why rclone works in their case: In case the client does not send `Expect: 100-continue`, dCache believes the client is "incapable" to follow redirects on `PUT`, and does not redirect `PUT` to doors, but proxies the data through the initially contacted storage server instead. This means rclone will be proxied on `PUT`. 

I don't think there's anything XRootD can improve on what it is doing now, so I will continue to try to get rclone (or maybe even the Go stdlib) changed. We can of course close this issue if you want, many thanks again! :+1:
