### ISSUE TITLE
Add CMake flag `PIP_OPTIONS` to allow for passing specific options to pip during the install

### ISSUE THREAD

**Issue by matthewfeickert** [xrootd/xrootd#1646]
In Issue #1641 @adriansev has explained that for software maintainers installing things at the system level there can be clear reasons why one would want to install the Python bindings with the `--ignore-installed` `pip` option (e.g. https://github.com/matthewfeickert/cvmfs-venv#disadvantages) instead of the `--force-reinstall` option

https://github.com/xrootd/xrootd/blob/3d64cdad97f0f93a04dd01234e88a27525285d8d/bindings/python/CMakeLists.txt#L89-L98

Instead of trying to guess what users may or may not need, he also points out that by adding a `PIP_OPTIONS` CMake option this would allow expert users to exactly choose what they want, making it much more adaptable to installs across the board from a local user to a system admin.

This seems like a great idea to me, that should also be easy to implement. :+1:

**Comment by adriansev** [comment]
https://github.com/xrootd/xrootd/pull/1647 :)
