### ISSUE TITLE
XrdCl: Race condition in SetLogLevel

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#166]
From Helgrind:

==29093== Locks held: 1, at address 0x200EE9B0
==29093==    at 0x650773C9: XrdCl::DefaultEnv::SetLogLevel(std::string const&) (in /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc481/external/xrootd/4.0.4/lib/libXrdCl.so.2.0.0)

==29093== Locks held: none
==29093==    at 0x65073D21: XrdCl::Log::Dump(unsigned long, char const*, ...) (in /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc481/external/xrootd/4.0.4/lib/libXrdCl.so.2.0.0)

The current use of SetLogLevel / Dump are not thread-safe.  Here's the corresponding code:

https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClLog.hh#L195
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClLog.hh#L222

simultaneous calls result in undefined behavior.

**Comment by esindril** [comment]
@bbockelm did you already push your commit for this? Can I close this one?

Thanks,
Elvin

**Comment by abh3** [comment]
The last patch addressed the essence of this problem. So, I am closing this issue.
