### ISSUE TITLE
xrootd::python::macos wheel usage of clang does not set the correct cxx standard

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1660]
So, when building the wheel pip does not the the correct cxx flags. for us (ALICE) a quick fix was to do https://github.com/xrootd/xrootd/pull/1651 but would be better to find the cause of pip not using the correct flags (the same used also for building the rest of the software).
The actual errors (building v5.4.2) can be seen [here](https://asevcenc.web.cern.ch/asevcenc/xrootd_py_macos_err/log)
For the moment (because we want 5.4.2) we build our fork that contains our workable fix, but would be great to find the solution upstream (for the next tag)

**Comment by adriansev** [comment]
@ktf @matthewfeickert FYI, thanks guys!

**Comment by matthewfeickert** [comment]
> So, when building the wheel pip does not the the correct cxx flags.

What CXX flags are you passing now? Not like in PR #1651, but what CXX flags are you passing in at CMake build configure time?

> for us (ALICE) a quick fix was to do #1651 but would be better to find the cause of pip not using the correct flags (the same used also for building the rest of the software). The actual errors (building v5.4.2) can be seen [here](https://asevcenc.web.cern.ch/asevcenc/xrootd_py_macos_err/log)

Can you also detail what the macOS software environment is that you're using? I don't have much experience building C++ software with macOS in CI, but it seems to be a bit of a more unstable mess around versions with things getting pulled in from both XCode and homebrew at times. As you're building this in CI can you link to the GitLab Pipelines file and section, or if private, share the relevant build config? In short, wow can someone reproduce the macOS build environment in CI?

**Comment by adriansev** [comment]
Hi @matthewfeickert ! So the env vars used are these https://github.com/alisw/alidist/blob/master/defaults-o2.sh#L1
then in the xrootd recipe we have: https://github.com/alisw/alidist/blob/master/xrootd.sh#L53

On the macos information i cannot help (unless you give me some commands), these days was my first time logging in a macos account :)
We do have a CI but the general building is the same i described to you last time (with aliBuild ..etc..) and no matter the platform the building procedure is the same (and with the same recipes that take care of adaptation to underlying platform).
So, on the xcode/homebrew stuff maybe Giulio Eulisse can comment (weird that i cannot mention him)

**Comment by matthewfeickert** [comment]
> On the macos information i cannot help (unless you give me some commands), these days was my first time logging in a macos account :) We do have a CI but the general building is the same i described to you last time (with aliBuild ..etc..) and no matter the platform the building procedure is the same (and with the same recipes that take care of adaptation to underlying platform). So, on the xcode/homebrew stuff maybe Giulio Eulisse can comment (weird that i cannot mention him)

Yeah, maybe @ktf can comment here on if they can look at PR #1661 and compare that to what they have in the existing ALICE workflow and then give a summary here in the Issue.

**Comment by adriansev** [comment]
@matthewfeickert well, as far as environment this is what is present:
```
[Tuesday 22.03.22 09:26] asevcenc@aido2osx3 : ~  $ 
xcode-select -v
xcode-select version 2384.
[Tuesday 22.03.22 09:26] asevcenc@aido2osx3 : ~  $ 
brew list
==> Formulae
alibuild                freetype                icu4c                   libtool                 mpfr                    pigz                    tcl-tk
alice-build-machine     gcc                     isl                     libunistring            msgpack                 pkg-config              tmux
autoconf                gdbm                    libcbor                 libxml2                 mysql                   protobuf                utf8proc
automake                gettext                 libevent                libyaml                 ncurses                 python@3.10             xz
berkeley-db             glfw                    libfido2                llvm                    o2-full-deps            python@3.8              zeromq
ca-certificates         gmp                     libidn2                 lz4                     openjdk                 python@3.9              zstd
cmake                   gsl                     libmpc                  m4                      openssl@1.1             readline
coreutils               gtk-doc                 libomp                  make                    openssl@3               s3cmd
docbook                 htop                    libpng                  modules                 pcre                    six
docbook-xsl             hub                     libsodium               mpdecimal               perl                    sqlite
```
on top of these runs the recipes that i mentioned .. 
Thanks a lot!

**Comment by ktf** [comment]
It think happens with setuptools < 60.0.8 and python 3.9 actually. Regardless of it being ubuntu or macOS.

I think you are lacking a language="c++" in the Extension in setup.py. I will check in a bit.

**Comment by ktf** [comment]
Because we use c++17 in the rest of the stack. Keep in mind that what happens is that without my patch it tries to compile using "clang", and that defaults to C++98.

**Comment by simonmichal** [comment]
@ktf : OK, fair enough, but your PR is setting C++17 for everyone not only for your stack, please keep in mind that we still support some platforms where C++17 is not available, hence this is a no-go. But fear not, we will do our best to accommodate your use case, we just need to find the right way of doing it :-) I do agree with @matthewfeickert that we probably need to use `CXX_STANDARD` similarly as `root` does.

As a side note, we also have those that probably need updating:
https://github.com/xrootd/xrootd/blob/d54b632c2291ad563b596efe7365e0271c9ef7ee/bindings/python/setup.py.in#L11-L19

**Comment by simonmichal** [comment]
> To be clear, the PR was just to illustrate a problem and provide what works for us.
We do appreciate it! :-)

> On a second sight, I wonder if the problem is not indeed just a matter of changing to c++11 what you currently have with c++0x.
@ktf : could you change it to `c++14` in your build environment and give it a try?

**Comment by matthewfeickert** [comment]
> It think happens with setuptools < 60.0.8 and python 3.9 actually. Regardless of it being ubuntu or macOS.

@ktf Can you verify this? It would be significantly easier to have a discussion around Linux where we can cleanly have minimal failing/working examples in Docker images then trying to attempt to test things in CI workflows if we keep it in macOS only.

**Comment by matthewfeickert** [comment]
> > On a second sight, I wonder if the problem is not indeed just a matter of changing to c++11 what you currently have with c++0x.
> 
> @ktf : could you change it to `c++14` in your build environment and give it a try?

@ktf, now that @simonmichal has added d2fe17323e6cacf6d13b0c940ffd49a7308c6c08 can you give this a try?

**Comment by adriansev** [comment]
@ktf gentle ping to give green light and have this in the next release

**Comment by adriansev** [comment]
actually this in an issue, the the commit is already in master... checking up this right now

**Comment by adriansev** [comment]
@simonmichal @matthewfeickert so, i just checked, the current master still does not properly install the python bindings, see [the log](https://asevcenc.web.cern.ch/asevcenc/xrootd_py_macos_err/log)
i will try to checkout #1672 to see if this fix the problem

**Comment by adriansev** [comment]
@simonmichal unfortunately this was not solved by d2fe17323e6cacf6d13b0c940ffd49a7308c6c08, the master still show an error like:
`error: no template named 'tuple' in namespace 'std'`
about this i found only this mention:
https://stackoverflow.com/questions/65920834/no-template-named-tuple-in-c
Does this shed any light on the problem?
Thanks a lot!

**Comment by adriansev** [comment]
Hi @simonmichal @matthewfeickert !
I just tried with v5.4.3-rc1, and the new log is [this](https://asevcenc.web.cern.ch/asevcenc/xrootd_py_macos_err/log). It would be wonderful if this can be solved for 5.4.3 .. Any idea how can the pip be convinced to use the proper c++ standard?
Thanks a lot!

**Comment by matthewfeickert** [comment]
> could give me some details on your environment, what is the version clang and python you are building against?

Yeah, it would be useful to have a minimal reproducer that one could drop into a clean environment (read as GitHub Actions CI as I don't have a Mac). It would be helpful to understand what exactly you're doing as you mentioned

> when building the wheel pip does not the the correct cxx flags

but in https://github.com/xrootd/xrootd/issues/1660#issuecomment-1074244837 you linked to a [cmake build](https://github.com/alisw/alidist/blob/5ccb99ee65e547e9336ef71c3ca40c9f3e4db828/xrootd.sh#L53-L71)

but it is unclear from that specific build environment if you're providing CMake with the relevant details. Your environment is different, but given how homebrew sets up things by default the easiest way to get things to be discoverable / set correctly in CI was

https://github.com/xrootd/xrootd/blob/217382ec3e4026a6d1a5b302bc770057661bf577/.github/workflows/build.yml#L320-L341

I think providing a minimal failing example would probably help anyone trying to look at this.

**Comment by simonmichal** [comment]
OK I see in the logs:
- `PYTHON_EXECUTABLE=/usr/local/opt/python@3.9/bin/python3.9`
- `The C compiler identification is AppleClang 13.0.0.13000029`
- `The CXX compiler identification is AppleClang 13.0.0.13000029`

On mine I have clang Apple LLVM version 10.0.1 (clang-1001.0.46.4) and it says `The default C++ language standard is gnu++14.`, could you check what is the default in your case?

**Comment by simonmichal** [comment]
@adriansev : could you grand me access to your build node? ( I totally cannot reproduce it : / )

**Comment by adriansev** [comment]
Hi @simonmichal and sorry for the late answer! so, i made a gist that reproduce the ALICE case, see https://gist.github.com/adriansev/758c2eedc4b38e1417ec4937e2b513ab
this is python 3.9 (/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/bin/python3.9)
and AppleClang 13.0.0.13000029

The weird thing is that the actual compilation have no problem but only the bindings compilation have problems.. 
also, for complete info, the xrootd recipe of ALICE is this:
https://github.com/alisw/alidist/blob/master/xrootd.sh#L53

on this mac build machine we have:
xcode-select -v
xcode-select version 2384.

clang --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

how can i check what default stadard it use?

Thanks a lot!

**Comment by adriansev** [comment]
and i forgot to mention that these are our mac requirements for installation:
https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-macos.html

**Comment by simonmichal** [comment]
@adriansev 👍 

> how can i check what default stadard it use?

Just check the man page of the compiler it should have somewhere the information.

Running this `aliBuild` tool seems quite complex I haven't been able yet to get it working on my Mac : /

Now, I'm getting desperate to have a fix included in `5.4.3` but I run out of ideas.
As a work around, we could provide a setting, let's say `XROOTD_PYBUILD_ENV`, that would allow you to set the environment for the python bindings build, something like:

```
     COMMAND /usr/bin/env ${XROOTD_PYBUILD_ENV} ${PYTHON_EXECUTABLE} -m pip install \
```

Would this work for you? (then, you would just pass the environment setting to cmake using `-DXROOTD_PYBUILD_ENV`)

**Comment by simonmichal** [comment]
@adriansev : I've just pushed fa83acfdb5d7101bf8ac50b61a1018a366fa2d7a, could you give it a try?

**Comment by adriansev** [comment]
Hi @simonmichal !

> > oh, i found it and it says: The default C++ language standard is gnu++14
> 
> so how comes it cannot compile c++11 code?
i have no idea .. actually i do not understand what instructions follow pip to compile the xrootd wheel (i mean beside the obvious ones from setup.py.in) where std is stated and it should have been followed

> > yes, it would be really helpful to have -DXROOTD_PYBUILD_ENV, thanks a lot!!!
> 
> OK, lets go ahead with this
thanks a lot, works like a charm!! i can confirm that i could properly use the master of xrootd on osx_x86-64 and do:
```
[XRootD/latest-xrootd-upstream-o2] ~/alisw/xrootd-upstream $> python3 -c 'from XRootD import client;import logging;print(client.__version__);'
20220509-fa83acfdb
```

**Comment by simonmichal** [comment]
@adriansev : thanks for testing! the patch has been backported to stable branch.

**Comment by matthewfeickert** [comment]
@adriansev If fa83acfdb5d7101bf8ac50b61a1018a366fa2d7a resolves the problem in your mind, can this Issue get closed?

**Comment by adriansev** [comment]
yes, indeed, thanks a lot!
