### ISSUE TITLE
Error 500 (server error) on mkdir over HTTPS when directory exists

### ISSUE THREAD

**Issue by sfayer** [xrootd/xrootd#1663]
Hi,

I've noticed with newer versions of xrootd (tested on v5.4.2) the return code for mkdir (mkcol) over HTTP(S) seems to be 500 if the directory already exists (quite possibly related to issue  #1360). This upsets gfal-mkdir as it seems to expect an error code of 405 in this case, an error code 500 is seen as an I/O error:

```
# Directory doesn't exist, no error...
$ gfal-mkdir https://test.host:1094/data/testdir
# Directory now exists, expect "File exists" error, but get I/O error instead:
$ gfal-mkdir https://test.host:1094/data/testdir
gfal-mkdir error: 5 (Input/output error) - HTTP 500 : Unexpected server error: 500  with url https://test.host:1094/data/testdir
```

The error I would expect is "File exists":
```
$ gfal-mkdir https://test.host:1094/data/testdir
gfal-mkdir error: 17 (File exists) - HTTP 405 : Method Not Allowed, File Exist  with url https://test.host:1094/data/testdir
```

I think RFC4918 specifies a return code of 405 in this case to indicate that the directory already exists (although I may well be reading the wrong RFC). I'm using a transfer tool that's built on-top of gfal and this difference in code is critical: An I/O error stops any further operations, whereas it knows to continue if it gets "file exists" on an mkdir command.

I was able to get the behaviour I expected with this patch, although I don't know if this has any other negative effects on the other http methods:
```
--- a/src/XrdHttp/XrdHttpReq.cc
+++ b/src/XrdHttp/XrdHttpReq.cc
@@ -965,6 +965,9 @@ void XrdHttpReq::mapXrdErrorToHttpStatus() {
       case kXR_InvalidRequest:
         httpStatusCode = 405; httpStatusText = "Method is not allowed";
         break;
+      case kXR_ItExists:
+        httpStatusCode = 405; httpStatusText = "Resource exists";
+        break;
       default:
         break;
     }
```

Would it be possible for something like this patch be merged to fix this issue?

Regards,
Simon

**Comment by bbockelm** [comment]
@sfayer - any idea when this issue crept up?  From the ticket you linked, it may be relatively old (dating back >1 year) which makes me surprised that it's not biting FTS.

(Trying to understand impact and urgency... I think your suggested fix is likely correct)

**Comment by sfayer** [comment]
I'm not really sure: I suspect the answer is "5.0.0 and FTS is relying on the implicit directory creation so it doesn't hit the mkdir bug": I'm sure we would have seen it somewhere in production if it did affect FTS (the transfer system I'm having trouble with is an older/simpler DIRAC one that isn't FTS based).

Regards,
Simon

**Comment by abh3** [comment]
Then this may be an issue. If the current behaviour is OK for FTS but not 
for DIRAC then we can't just simply change the behaviour to suit DIRAC as 
it may break FTS. So, more investigation is needed here. Mind you that 
reading the HTTP spec either code should be handled but it appears that 
409 is the preferable one in this particular case (your intepretation of 
the the may vary https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).

Andy

**Comment by sfayer** [comment]
Hi Andy,

I looked into this a bit more and it seems this change in behaviour was accepted for v5.0.0-rc2 (https://github.com/xrootd/xrootd/pull/1164), but v5.0.0-rc3 added the more specific "kXR_ItExists" error code (https://github.com/xrootd/xrootd/commit/cece19ddc8f6bebe5eb2768549ca474714f65cc9) meaning it doesn't hit that specific case in the original patch any more. I don't think this will cause any problems with FTS: other storage servers also return 405 in this case and don't run into FTS issues.

While I agree that 409 would made more sense, it's reserved for a different case by the webdav RFC (for when a user tries to make a directory before the parent exists): I don't know why it's this way around but 405 is what they picked for the mkcol "already exists" case (https://datatracker.ietf.org/doc/html/rfc4918#section-9.3.1).

Regards,
Simon

**Comment by ffurano** [comment]
Hi Simon,
 your proposed patch makes perfect sense to me, we are just trying to understand the rationale behind this behaviour of the redirector, it seems that the road is traced, though.

Fabrizio

**Comment by abh3** [comment]
As an update while researching this problem we came up with an unresolvable conflict. GFAL2 interprets 405 as does not exist and is biases to interpret 409 as already exists. This is exactly the opposite to webdav. So, we are stuck at the moment.

**Comment by sfayer** [comment]
Hi,

Could you please elaborate on the instances where GFAL2 misinterprets the response codes?

I've been looking through the davix library code that GFAL2 uses for its webdav support and it looks to me like it has the 405/409 special cases for mkdir(mkcol) the same way around as the webdav RFC (with 405 for already exists):
https://github.com/cern-fts/davix/blob/master/src/request/httprequest.cpp#L400-L403

Is the problem that patching the `mapXrdErrorToHttpStatus` function would cause issues for other methods? If that's the case, would it be possible to just patch the mkcol case return code? e.g. something like:
```
--- a/src/XrdHttp/XrdHttpReq.cc
+++ b/src/XrdHttp/XrdHttpReq.cc
@@ -2686,8 +2686,12 @@ int XrdHttpReq::PostProcessHTTPReq(bool final_) {
     {
 
       if (xrdresp != kXR_ok) {
-        prot->SendSimpleResp(httpStatusCode, NULL, NULL,
-                             httpStatusText.c_str(), httpStatusText.length(), false);
+        if (xrderrcode == kXR_ItExists) {
+          prot->SendSimpleResp(405, NULL, NULL, (char *) "Method is not allowed", 0, false);
+        } else {
+          prot->SendSimpleResp(httpStatusCode, NULL, NULL,
+                               httpStatusText.c_str(), httpStatusText.length(), false);
+        }
         return -1;
       }
```

I've tried running a standalone xrootd-5.4.2 instance with the patch above and doing an mkdir using the current EPEL7 version of gfal2 (gfal2-2.20.5-1.el7.x86_64) and it seems to map it to the correct "file exists" response:
```
$ gfal-mkdir http://localhost:1094/opt/xrootd/data/test
gfal-mkdir error: 17 (File exists) - HTTP 405 : Method Not Allowed, File Exist  with url http://localhost:1094/opt/xrootd/data/test
```

Regards,
Simon

**Comment by abh3** [comment]
According to the last message I received from the gfal team (out of band) 
corresponds to you assesment. Now I have to get a couple of other people 
on board and we will go ahead.

Andy

**Comment by abh3** [comment]
@sfayer Could create a pull request with the proposed changes? I think we have resolved all conflicts here and it appears the suggested fix is workable and won't break any existing code.
