### ISSUE TITLE
Wrong error from loading external modules with unresolved symbol(s)

### ISSUE THREAD

**Issue by rob-c** [xrootd/xrootd#1670]
Hi,

I'd like to report a small issue which has now hit a few different people developing 3rd party plugins/modules.

When an external module contains missing symbols which can't be resolved XRootD skips the loading of these modules as-if the file doesn't exist.

Ideally it would be better if XRootD would report the full error as to why the module failed to load rather than hiding it and reporting that the file isn't found in the startup log.

Regards,

Rob

**Comment by abh3** [comment]
Oddly, we fixed this some time ago. At least the situation no longer happens. For instance, loading a plugin with a missing symbol produces the message:
=====> ofs.osslib libXrdPss.so
Plugin /sdf/home/a/abh/xrd/devel/almalinux9/src/libXrdPss-5.so: undefined symbol: _ZN8XrdProxy18SymbolDoesNotExistE osslib libXrdPss-5.so

You may quibble that now the generic message is no longer produced.
