### ISSUE TITLE
Subprocesses aborted with "bad file descriptor polling for events" on macOS

### ISSUE THREAD

**Issue by chrisburr** [xrootd/xrootd#1673]
Similar to https://github.com/xrootd/xrootd/issues/1198 I've found that XRootD's Python bindings break Python's subprocess module. Unlike on Linux it's trivially reproducible:

```python
$ python -c 'import XRootD.client; eos = XRootD.client.FileSystem("root://eoslhcb.cern.ch/"); eos.dirlist("/eos"); import subprocess; subprocess.check_output(["ls"])'                                               (logse-sqlite)
KQ: bad file descriptor polling for events
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cburr/mambaforge/envs/logse-sqlite/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/cburr/mambaforge/envs/logse-sqlite/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ls']' died with <Signals.SIGABRT: 6>.
```

I guess the other three `XrdSysIOEventsPoll` implementations need to have a similar patch applied to only abort if the parent PID doesn't match.

**Comment by adriansev** [comment]
I encountered this also on macos but i run the subprocess in the `end` method of a derived class from `.utils.CopyProgressHandler` https://github.com/adriansev/jalien_py/blob/master/alienpy/alien.py#L2639-L2640
and i just get an
```
Unable to write to the log file:
KQ: bad file descriptor polling for events
bad file descriptor
```
but i do not have actually an Exception and a traceback .. 
this completely mystifies me, i do not have any idea what to search for .. 
all i could find was this https://www.freebsd.org/cgi/man.cgi?query=kqueue
