### ISSUE TITLE
Webdav does not support absolute URIs

### ISSUE THREAD

**Issue by davidgcameron** [xrootd/xrootd#1675]
Hi,

This was first reported to EOS (https://its.cern.ch/jira/browse/EOS-5203) but they told me it was an xrood issue.

ARC clients (for historical reasons) use the full URI in HTTP requests by default. This fails on EOS with 404:

```
[dcameron@lxplus722] ~> arccp -d DEBUG https://eosatlas.cern.ch/eos/atlas/atlasdatadisk/rucio/data18_13TeV/ff/ff/HIST_HLTMON.14686823._000075.pool.root.1 /tmp/dcameron/

...

DEBUG: > GET https://eosatlas.cern.ch/eos/atlas/atlasdatadisk/rucio/data18_13TeV/ff/ff/HIST_HLTMON.14686823._000075.pool.root.1 HTTP/1.1
Host: eosatlas.cern.ch:443
Connection: keep-alive
user-agent: ARC
DEBUG: No security processing/check requested for 'incoming'
DEBUG: < HTTP/1.1 404 NOT_FOUND
DEBUG: < Connection: Keep-Alive
DEBUG: < Content-Length: 3846
DEBUG: < Content-Type: text/html
DEBUG: < Date: Mon, 11 Apr 2022 06:44:33 GMT
```

 

Although the client behaviour is not really correct, [RFC 7230](https://www.rfc-editor.org/rfc/rfc7230#section-5.3.2) states that the server must support it:

> To allow for transition to the absolute-form for all requests in some
> future version of HTTP, a server MUST accept the absolute-form in
> requests, even though HTTP/1.1 clients will only send them in
> requests to proxies.

Cheers,
David

**Comment by apeters1971** [comment]
Found this .... 

https://softwareengineering.stackexchange.com/questions/298130/how-should-an-http-server-respond-to-a-get-of-an-absolute-uri-of-a-different-ser

... 

(RFC 7230 § 5.5) **HTTP servers which receive the absolute form of a URI in the request-line ignore the Host: header and use only that absolute URI for any further processing. The server then has to decide what to do with it.**

...

While the RFC does note that this situation can occur, it does not mandate a particular response. If you are implementing a server capable of serving virtual hosts, you can do what other servers do and serve it with the default virtual host. Or you can decide to refuse such requests and explicitly serve a 403 Forbidden. (RFC 7231 § 6.5.3)

**Comment by abh3** [comment]
Thanks Andreas; though it's not a particularly satisfying situation. 
People appear to be making things up based on what is expedient. I suppose 
given what most people are implementing -- simply strip off the absolute 
header and give it a go -- is the simplest solution though, in my mind, 
rather hacky.

Andy

**Comment by xrootd-dev** [comment]
Hi,

  and I agree with this behaviour. After all, XrdHttp
is a "pragmatic implementation".

  You can assign the tkt to me,
I think I'll be able to do it tomorrow


Fabrizio



Il 11/04/2022 12:31, Andrew Hanushevsky ha scritto:
