### ISSUE TITLE
Requests for the CMS XrdAdaptor logging development

### ISSUE THREAD

**Issue by 4quarks** [xrootd/xrootd#1677]
Hi Michal, et al., 
As we discussed last week, in order to enhance the XrdAdaptor logging, we need some small developments on the XRootD side. I will summarize what needs to be done with some examples:

# Requests
1. Get the actual hostname instead of the DNS alias on the URL GetHostName() function [1].

Now: 
```
Traceroute:    cms-xrd-global.cern.ch  ...
```
Desired: 
```
Traceroute:    cms-xrd-global02.cern.ch   ...
```
```
$ nslookup cms-xrd-global.cern.ch
Name:	cms-xrd-global.cern.ch
Address: 188.184.30.79
Name:	cms-xrd-global.cern.ch
Address: 188.184.29.87
Name:	cms-xrd-global.cern.ch
Address: 2001:1458:d00:2f::100:326
Name:	cms-xrd-global.cern.ch
Address: 2001:1458:201:e5::100:49

$ nslookup 188.184.30.79
79.30.184.188.in-addr.arpa	name = cms-xrd-global02.cern.ch.
```
2. Know what protocol is it using IPv4 or IPv6.
```
Traceroute:    cms-xrd-global02.cern.ch  (2001:1458:d00:2f::100:326) ...
```
3. Get further authentication and authorization info from the `XrdCl::DefaultEnv::GetPostMaster()->QueryTransport` not just the auth system. 
i.e. for GSI: CAdir, CRLdir, UsrProxy... [2]
For instance, the principle/subject/username and the expiration (user mappings) to identify which user it was would already be a good enhancement. 

Thank you in advance for your time!
Cheers

------------------------------------------------------------------------------------------------------------------------------------
[1] 
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClURL.hh#L165

[2]
https://github.com/xrootd/xrootd/blob/master/src/XrdSecgsi/XrdSecProtocolgsi.hh#L323

**Comment by 4quarks** [comment]
Hi! 
Do you have any update on this? Would be good to have an (aprox) idea of when this change could be integrated so we can schedule the CMSSW update accordingly. 
Thanks! 
Pau

**Comment by simonmichal** [comment]
Hi @4quarks, sorry for the late response, I'm on holidays until the end of this week ;-) I think we can schedule this for 5.5.0 which is planned for mid May. The _1._ should be relatively easy to implement, the _2._ is already implemented in master branch (see 36e062022a29935a5135fb18c395e55b4360607b), regarding _3._ I will need to dwell a bit on it to find the best way of providing those details.

**Comment by 4quarks** [comment]
I hope you had a good vacations! :) 
Thanks for the information! Mid-May is perfect. We can wait until then and push all the changes together so we can use the latest version of XRootD. 
Cheers!

**Comment by simonmichal** [comment]
@4quarks : just to let you know with aab1dc436a136c9a9e30d057b3218d14abe907fb I have introduced `Stream` queries, with this you can:
- get the IP address used by the Channel labeled with given URL (`StreamQuery::IpAddr`)
- get the IP stack (`IPv4` vs `IPv6`) for given URL (`StreamQuery::IpStack`)

**Comment by abh3** [comment]
Presumably this addresses this ticket, yes?
