### ISSUE TITLE
Add an option to fail XrootD build if explicitly enabled features can not be build

### ISSUE THREAD

**Issue by smuzaffar** [xrootd/xrootd#1682]
Hi,
  We noticed that `xrootd` build system silently disables features which were explicitly enabled e.g. see https://github.com/xrootd/xrootd/issues/1662#issuecomment-1091282521 where though `-DENABLE_KRB5=TRUE` was used but `cmake` decided to disable `krb5` support due to missing `krb5 headers`. Ideally build process should fail if an explicitly enable feature/plugin can not be build. Can you please provide an option to enforce such behavior.

Thanks,
--Shahzad

**Comment by simonmichal** [comment]
@smuzaffar : I just pushed 23c8fae23a4118ee9a84f65dffecc22c29b32514, could you give it a try? You need to specify `-DFORCE_ENABLED=ON` in your cmake cmandline.

**Comment by smuzaffar** [comment]
thanks a lot @simonmichal , I am testing this now

**Comment by smuzaffar** [comment]
@simonmichal , can you please review and include https://github.com/xrootd/xrootd/pull/1708
