### ISSUE TITLE
DNs containing commas are not matched in gridmap

### ISSUE THREAD

**Issue by jthiltges** [xrootd/xrootd#1684]
DNs appear to be transformed, replacing `,<space>` with `/` ahead of comparison to the mapfile.

```C++
s.replace(", ", "/");
```
https://github.com/xrootd/xrootd/blob/v5.4.2/src/XrdCrypto/XrdCryptosslAux.cc#L779

For example, a client intended to match the following gridmap line
```"/DC=org/DC=incommon/C=US/ST=California/L=La Jolla/O=University of California, San Diego/CN=stashcache.t2.ucsd.edu" ligo```
will result in xrootd comparing the client's DN as 
```/DC=org/DC=incommon/C=US/ST=California/L=La Jolla/O=University of California/San Diego/CN=stashcache.t2.ucsd.edu```
which does not match.

**Comment by bbockelm** [comment]
Note this might be a duplicate of https://github.com/xrootd/xrootd/issues/1681

**Comment by jthiltges** [comment]
This is indeed a duplicate of that issue. Thanks for opening it.
