### ISSUE TITLE
macos m1:: latest setuptools breaks python bindings

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1686]
Hi @matthewfeickert @simonmichal ! So, we encountered a strange situation, __ONLY__ on M1 macs:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/phristov/opt/miniconda3/lib -L/Users/phristov/opt/miniconda3/lib -Wl,-rpath,/Users/phristov/opt/miniconda3/lib -L/Users/phristov/opt/miniconda3/lib -Wl,-rpath,$ORIGIN/../../.. -std=c++17 build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/PyXRootDCopyProcess.o build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/PyXRootDCopyProgressHandler.o build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/PyXRootDFile.o build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/PyXRootDFileSystem.o build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/PyXRootDModule.o build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/PyXRootDURL.o build/temp.macosx-11.0-arm64-cpython-39/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/bindings/python/src/Utils.o -L/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/build/src -L/Users/phristov/alisw/sw/BUILD/15c75174a0a1efe679d9440664506fcfe915f5bc/XRootD/build/src/XrdCl -lXrdCl -lXrdUtils -ldl -o build/lib.macosx-11.0-arm64-cpython-39/pyxrootd/client.cpython-39-darwin.so

      ld: library not found for -ldl
```
again, only with latest setuptools not with 60.8.2...
while the `setuptools==60.8.2` works and seem to be our "solution" i'm unwilling to let this unsolved..

any idea about this strange thing?
Thanks a lot!

**Comment by matthewfeickert** [comment]
I don't have any real advice when it comes to M1 macs given that there's no real way for people without them to test on these environments. @henryiii or @alexander-held might have experience on building things on them but I don't think they have any time to do additional debugging.

@adriansev what are you actually doing though? Are you just running CMake with Python enabled

https://github.com/xrootd/xrootd/blob/1f765a485783a4ca2e643e3fecfc80f86569a066/.github/workflows/build.yml#L323-L341

? Or are you trying to install from an sdist? If the later, can you try to use my fork's `build/next-pr` branch (as the name suggests it is a debug branch which I will make a PR for once PR #1672 is merged that moves things off of `distutils` with some `setuptools` and onto `setuptools` only for modern Python).

**Comment by abh3** [comment]
Wasn't this fixed with the latest commits'?

**Comment by adriansev** [comment]
i will ask again ... i have no access to M1, the error was reported to me "as is"

**Comment by abh3** [comment]
It looks like this was corrected so I am closing the ticket.
