### ISSUE TITLE
async read

### ISSUE THREAD

**Issue by scrgiorgio** [xrootd/xrootd#1694]
I am experimenting with an xrootd plugin (`class MyPlugin: public XrdOssDF`). 

I have a `xroot.config` file with `async` enabled and a `segsize` of 1MiB:

```
xrootd.async force limit 8 maxsegs 8 maxstalls 5 maxtot 4096 segsize 1048576
```

Then I implement the async Read (`virtual int Read(XrdSfsAio *aiop)`) and I copy a big file (~100MiB) using `xrdcp`. 

Debugging the plugin, it seems I am always getting a ` aiop->sfsAio.aio_nbytes` of 64KiB instead of 1 MiB. 

Could you help me? Thanks.

**Comment by abh3** [comment]
What you are seeing is the result of a page read (kXR_pgread) being converted to normal reads as your plugin has not overridden pgRead() method (the same hold for page writes). Page read and writes are fixed at a 64K segment size (i.e. they are not subject to the xrootd.async directive). This was done for latency reasons and to simplify checksum handling. Currently, only xrdcp and Xcache use page reads/writes. Any other application that uses normal reads and writes would be subject to that directive. This would imply that you are testing your plugin with one or the other application.

**Comment by scrgiorgio** [comment]
Thanks for the help.

So to force the use of `xrdcp` command, I recompiled a custom xrootd modifying line 55 of `XrdXrootdPgrwAio.hh` (new line `static const int    aioSZ = 1024*1024`) and it's working as expected. Any way to change it using some env variable? (tried with XRD_CPCHUNKSIZE but it seems not to be the right param).

After that, I tried to mount the directory xrootd as a FUSE. In my config I disabled the `sendfile` option (not implemented by the plugin):

```
xrootd.async force limit 8 maxsegs 8 maxstalls 5 maxtot 4096 segsize 1024k nosf 
```

and from the client side:

```
xrootdfs -o rdr=root://localhost:8094/my/directory,uid=daemon /my/mount/point
cp /my/mount/point/big.bin ./ # big.bin is 10MiB 
```
 but this time I am getting async-read request (i.e. `aio_nbytes`) of 131 KiB (still not `1MiB`).
What am I doing wrong?

**Comment by abh3** [comment]
I would dare sat that's the block size either cp uses of fuse uses. For cp you can easily find out by using the strace command. I didn't see anything in fuse plugin that would limit it to that value.

**Comment by scrgiorgio** [comment]
You were right.

The limit seems to be somewhere related to fuse.
If I add the `strace` I see the kernel call to be aligned to 128KB:

```
...
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 131072) = 131072
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 131072) = 131072
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 131072) = 131072
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 131072) = 131072
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 131072) = 131072
```

I tried several fuse_main options:

```
xrootdfs ... -o max_read=1048576
cat /proc/mounts
# xrootdfs ....user_id=1000,group_id=1000,allow_other,max_read=1048576...
```

but doing a `cp` I see the correct alignment for any size <=128KiB. 
As far as I grow bigger than that there is something that is limiting the read request size.

Googling around, it could be related to the fact that setting `max_read` is not enough, and when creating a `fuse session` the `max_pages` should be set. But this is out of my expertise.

**Comment by abh3** [comment]
I think we have not really gotten very far on this other than there is a system limit outside of xroot that is imposing this limit and I think that is as far as we can go with this.
