### ISSUE TITLE
too many bad blocks 

### ISSUE THREAD

**Issue by ivukotic** [xrootd/xrootd#1701]
XCaches now check checksums of all the block transferred before writing them down.
If the checksums did not match, the block was retransmitted.
In the g-stream, xcaches report number of retransmits that happened at each file access.
We monitor that number.
But it is unrealistically large. 
It seems that all our xcaches and all our origins show excessive checksum errors.
So, either there is something wrong in checksum calculation, or in reporting numbers of retransmits.

**Comment by wyang007** [comment]
Hi Ilija,

[Maybe this is useful to you...]

At SLAC we recently ran into data corruption issue with Xcache. It happens to almost all data sources that enabled async IO (Xrootd proxies by default enables async IO, e.g. CPB and OU). 

While we are investigating, we found a mitigation: setting pfc.blocksize 64k (or smaller) will not cause this kind of data c​orruption. For long latency data source, the drop of efficiency can be compensated by using pfc.prefetch 32.

--
Wei​

________________________________________
From: Ilija Vukotic ***@***.***>
Sent: Monday, May 9, 2022 12:13 PM
To: xrootd/xrootd
Cc: Subscribed
Subject: [xrootd/xrootd] too many bad blocks  (Issue #1701)

XCaches now check checksums of all the block transferred before writing them down.
If the checksums did not match, the block was retransmitted.
In the g-stream, xcaches report number of retransmits that happened at each file access.
We monitor that number.
But it is unrealistically large.
It seems that all our xcaches and all our origins show excessive checksum errors.
So, either there is something wrong in checksum calculation, or in reporting numbers of retransmits.
