### ISSUE TITLE
Timing issue with rename: possible workarounds?

### ISSUE THREAD

**Issue by kreczko** [xrootd/xrootd#1703]
Dear all,

We are running Xrootd `5.4.2-3` in an `redirector` (xrootd.phy.bris.ac.uk:1094) &rarr; `gateway` (io-37-02.acrc.bris.ac.uk:1194) setup on CentOS 7 and connect storage via `xrootd-hdfs` (async disabled). 
We offer `xrootd` and `https-over-xrootd`, our issue is mostly for the latter.

The issue we are experiencing can be summarized in the mermaid graph:
```mermaid
sequenceDiagram
    participant Client
    participant XrootD Redirector
    participant XrootD Gateway
    participant HDFS

    Client ->> XrootD Redirector: rename /path/to/file /path/to/file.new
    XrootD Redirector ->> XrootD Gateway: rename /path/to/file /path/to/file.new
    XrootD Gateway ->> HDFS: rename /path/to/file /path/to/file.new
    HDFS -->> XrootD Gateway: rename done
    Note left of Client: Waits 5 seconds
    Client ->> XrootD Redirector: stat /path/to/file.new
    XrootD Redirector ->> Client: /path/to/file.new does not exist
```
and is explained in more detail in https://github.com/xrootd/xrootd/issues/235#issuecomment-219182669.
In short: file is renamed on disk, but redirector thinks it is not there.

This is not an issue for most VOs, but operational tests (OPS VO) are failing - very bad.
Since this is unlikely to be solved internally in xrootd (based on the comment in issue 235), I was wondering if it would be possible to solve it at config level.

Can we change stat/propfind requests to

always query the gateway and file system:
```mermaid
sequenceDiagram
    participant Client
    participant XrootD Redirector
    participant XrootD Gateway
    participant HDFS

    Client ->> XrootD Redirector: stat /path/to/file.new
    XrootD Redirector ->> XrootD Gateway: stat /path/to/file.new
    XrootD Gateway ->> HDFS: stat /path/to/file.new
    HDFS -->> XrootD Gateway: stat results
    XrootD Gateway -->> Client: stat results
```

or can we change the redirector to directly query the file system (read-only):
```mermaid
sequenceDiagram
    participant Client
    participant XrootD Redirector
    participant HDFS

    Client ->> XrootD Redirector: stat /path/to/file.new
    XrootD Redirector ->> HDFS: stat /path/to/file.new
    HDFS -->> XrootD Redirector: stat results
    XrootD Redirector -->> Client: stat results
```

The particular test we are failing: [argo-mon](https://argo-mon.egi.eu/nagios/cgi-bin/extinfo.cgi?type=2&host=xrootd.phy.bris.ac.uk&service=ch.cern.WebDAV) - not sure if this is available to everyone.

Apparently, more info on that test is on a [twiki](https://twiki.cern.ch/twiki/bin/view/LCG/HTTPTFSAMProbe)

Additional info:
- [our xrootd config](https://github.com/BristolComputing/xrootd-se/tree/main/etc/xrootd) [using `xrootd-clustered.cfg` in production]
- [XrootD-HDFS  config](https://github.com/BristolComputing/xrootd-se/blob/main/optional/etc/xrootd/config.d/10-hdfs.cfg)

**Comment by abh3** [comment]
What should be happening here, unless the gateway thinks it's not under the control of a redirector, is that the gateway would tell its redirector that the original file no longer exists and the rename target does exist. Now, it could be the case (though unlikely) that the subsequent stat is issued faster than the time it takes for the gateway to update the information in the redirector. So, is the stat issued by the client doing the rename or by some parallel client?

Another issue here is that http was never designed to deal with such scenarios. In xroot protocol you do have the option to query the server directly and refresh the redirector's cache. This actually happens automatically when a mismatch is discovered in the redirector's cache. However, doing this all the time would quickly bring the whole system to its knees under even medium sized loads. So, it's not a practical option.

So, it seems we need to delve into this deeper to find out a) what happened to the notification that should have been sent to the redirector, b) what is the actual timing of the stat call, and c) if you issue the stat call directly to the gateway does it correctly respond?

**Comment by bbockelm** [comment]
@kreczko - Have you tried tinkering with the `cms.dfs` configuration:

https://xrootd.slac.stanford.edu/doc/dev54/cms_config.htm#_Toc53611070

I'm not entirely sure I'm following but what you describe sure sounds like `cms.dfs lookup central`.

You *do* want to make sure you have negative existence caching disabled as updating that cache is relatively race-prone.

**Comment by kreczko** [comment]
@bbockelm Thank you for the info!

I've been playing with `cms.fxhold` and `cms.delay`, but to no avail.

> You do want to make sure you have negative existence caching disabled as updating that cache is relatively race-prone.
I've searched the documentation, but could not find how. 

@abh3 
> So, is the stat issued by the client doing the rename or by some parallel client
Same client, 5s after the rename.

a) How can I do that?
b) 5 seconds after rename
c) I would have to check manually - will write a quick test

**Comment by bbockelm** [comment]
Ah - I don't think you want `cms.fxhold` and `cms.delay`.  I think you want `cms.dfs` as that allows the redirector to do the existence check.

**Comment by kreczko** [comment]
Yes, after talking to S. Skipsey, these settings solved the issue:
```
cms.dfs lookup central redirect immed
```

BTW, a local test of
```bash
gfal-copy /bin/sh https://xrootd.phy.bris.ac.uk:1094/xrootd/dteam/test/test_https_latency.txt
gfal-stat https://xrootd.phy.bris.ac.uk:1094/xrootd/dteam/test/test_https_latency.txt
gfal-rename \
        https://xrootd.phy.bris.ac.uk:1094/xrootd/dteam/test/test_https_latency.txt \
        https://xrootd.phy.bris.ac.uk:1094/xrootd/dteam/test/test_https_latency.txt_moved
gfal-stat https://xrootd.phy.bris.ac.uk:1094/xrootd/dteam/test/test_https_latency.txt_moved
gfal-rm https://xrootd.phy.bris.ac.uk:1094/xrootd/dteam/test/test_https_latency.txt_moved
```
worked without issue even before the changes. The difference to the OPS tests is `gfal` &harr; `curl`. This is the test we were failing: https://gitlab.cern.ch/lcgdm/nagios-plugins-webdav/-/blob/master/src/check_webdav#L514

**Comment by bbockelm** [comment]
Wonderful!  I'm really sorry i didn't point you at this before in the prior ticket.

**Comment by abh3** [comment]
Problem has been solved.

**Comment by olifre** [comment]
@kreczko Oh, yes, indeed, this is a known problem, see e.g. https://github.com/xrootd/xrootd/issues/1252#issuecomment-661607710 and follow up comments explaining the nitty-gritty details (and the work which would be needed to cache authentication info if session caching is required).  
For this reason, `tlsreuse` should be off by default in recent XRootD versions,

**Comment by kreczko** [comment]
@olifre That's exactly the issue that helped me resolve the problem :). Thank you for the intensive debugging!
