### ISSUE TITLE
[Server] Unnecessary kXR_oksofar when reading past the end of file.

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#1705]
Let us consider following scenario: 
- we have 1MB file 
- we send a read request of 1MB but at offset 524KB ( 1/2 MB )

The server replies with kXR_oksofar containing 0.5MB of data, and then with kXR_ok containing 0 data.

Why is the server not sending a single kXR_ok with 0.5 MB of data?

**Comment by abh3** [comment]
This is an historic artifact that is difficult to change. Old versions of the file system plugin required the plugin to return 0 bytes to indicate EOF. There is a very old ticket about this and the plugin writers preferred to keep it this way for backward compatibility.

**Comment by abh3** [comment]
We have resolved the essentials here.
