### ISSUE TITLE
Missing Server HTTP response header

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#1706]
RFC 7231 defines the [Server response header](https://httpwg.org/specs/rfc7231.html#header.server).  This is an optional field that the origin server may use to describe itself.

Currently, xrootd does not respond with a `Server` HTTP response header.  This makes it impossible for the client to know that the endpoint is xrootd and which version of xrootd is deployed.

There are several legitimate reasons why a client may wish to know the implementation and version that is providing an endpoint.  Providing accurate information when filing a bug-report is one example.

**Comment by ffurano** [comment]
Done, please reopen if needed
