### ISSUE TITLE
500 Internal Server Error on unknown checksum algorithm

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#1707]
I can request an adler32 checksum of a file:
```console
paul@sprocket:~$ curl -I -H "Want-Digest: adler32" -H "Authorization: Bearer $TOKEN" https://xrootd-hv1-vanderbilt.sites.opensciencegrid.org:1094/store/test/bad-zero-file.root
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 0
Digest: adler32=f08fab4f

paul@sprocket:~$ 
```

I can also ask for an MD5 checksum:
```console
paul@sprocket:~$ curl -I -H "Want-Digest: md5" -H "Authorization: Bearer $TOKEN" https://xrootd-hv1-vanderbilt.sites.opensciencegrid.org:1094/store/test/bad-zero-file.root
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 0
Digest: md5=niK3oCxW39lw3BDVMDfimw==

paul@sprocket:~$ 
```

However, if I ask for a SHA checksum, the server replies with a 500 error:
```console
paul@sprocket:~$ curl -I -H "Want-Digest: sha" -H "Authorization: Bearer $TOKEN" https://xrootd-hv1-vanderbilt.sites.opensciencegrid.org:1094/store/test/bad-zero-file.root
HTTP/1.1 500 Internal Server Error
Connection: Close
Content-Length: 0

paul@sprocket:~$ 
```

The server should ignore checksum algorithms it does not understand.

**Comment by abh3** [comment]
The reason you cannot ask for a SHA checksum (other than it is ambiguous) is that none of the SHA checksums are natively supported. As whether or not the server should ignore the request, it certainly will not do so for xroot protocol as that is the defined behavior. As for http, I see no advantage in ignoring there either.

**Comment by paulmillar** [comment]
Hi Andy,

Thanks for the quick reply.

When opening this issue, I perhaps didn't give sufficient information to fully understand what's happening, so let me provide more details.

First, the label `sha` is not ambiguous.  It's defined in RFC 3230 as the SHA-1 algorithm from FIPS 180.

Second, unlike in the xroot protocol, HTTP 3230 allows the client to specify a list of algorithms, partially ordered by "priority".  Here's a couple of examples:
  * `Want-Digest: adler32, md5` 
    Here, the client would like either an adler32 or MD5 checksum (or both), with no priority given to either algorithm.
 * `Want-Digest: md5,adler32;q=0.5`
    In this example, the client would like either an adler32 or MD5 checksum, but this time, the MD5 checksum is preferred (the "`;q=1`" is implied).

I believe the `Want-Digest` request header is meant to implement a negotiation between the client and server.  The main purpose is to avoid the server incurring overhead from generating checksum information that the client will ignore.

However, the RFC is annoyingly vague on what is correct behaviour if one (or more) of the requested algorithms isn't supported by the server.  From reading the RFC, I believe the intention was that the server should ignore any algorithm it does not support (and not fail the request).  RFC 3230 makes it clear that the server is free to ignore requests for any specific algorithm, which (I feel) lends weight to this interpretation.  However, it's a deficiency in the RFC that this is not better described.

You mentioned that you didn't see an advantage of ignoring unknown algorithms.

For me, there is a clear advantage: it allows for smooth transitions as new algorithms are supported.

Apparently, dCache supports additional checksum algorithms than xrootd (SHA-512, SHA-256, SHA-1).  An HTTP-TPC third-party transfer between two dCache instances may be protected using one of these new checksums.

If xrootd were simply to ignore `Want-Digest` checksum algorithms it doesn't support then this improved support would have no impact on HTTP-TPC transfers from an xrootd server to a dCache server.  Such transfers would continue to be protected with ADLER32 or MD5.

The current behaviour of xrootd (failing the request) makes HTTP-TPC brittle and causes transfer failures.

Just to be explicit, this is the `Want-Digest` that the current `master` branch dCache sends:
```
Want-Digest: sha-512,sha-256;q=0.8,sha;q=0.6,md5;q=0.4,adler32;q=0.2
```

In terms of fixing this issue as quickly and with the least effort, I was wondering whether xrootd ever triggers checksum calculation if the client specifies a `Want-Digest`?  If not then the server could simply ignore the `Want-Digest` header value and simply return all the known checksums for the file.  That behaviour would be allowed by RFC 3230.

Cheers,
Paul.

**Comment by abh3** [comment]
I suppose I wasn't clear either. At the face of it, if the client asks for a single checksum and it isn't supported, I think he server is well in it's bounds to return an error. If the list of checksums is given and at least one of the checksums is supported then the server should return that checksum and I think it's plausible to interpret the RFC in that way -- don't return an error if you encounter an unsupported checksum in a list of checksums. However, if none are supported it would be legitimate to treat it as a single checksum failure. The only case I can see where the header could plausibly be ignored is when it is combined with a file transfer. So, we supply the bytes (if we can) but do not return a checksum. In each of these cases the client has to deal with the outcome whether it's an error or missing information, structurally it's the same thing. Note that this may be very inefficient if the client can't do anything with the bytes without a checksum. In that case, the transfer is a total waste of resources. As for supplying the default when none of the checksums are supported is rather odd. Generally, if someone wants the default checksum they would ask for it.

**Comment by paulmillar** [comment]
Thanks for the update, Andy.

I might have a different opinion on when it's appropriate for the server to return an error, but you're right about the client having to handle error cases.

However, for me, these are more philosophical points.

The core problem underlying this issue is quite specific: xrootd currently returns a 500 status code if a client issues a `GET` request with  `Want-Digest: sha-512,sha-256;q=0.8,sha;q=0.6,md5;q=0.4,adler32;q=0.2`.

In essence, dCache is asking for checksums, calculated with any algorithm it supports.  dCache and xrootd implement a common subset of algorithms: at least ADLER32 and MD5.  Therefore, (theoretically) xrootd should always be able to answer such a query.

**Comment by abh3** [comment]
Hi Paul, I think upon re-reading my response I did say that the server should not return an error if it can satisfy a checksum request using one in the checksum list. So, I agree with you on that one.

**Comment by paulmillar** [comment]
Sorry.  I didn't say it explicitly, but that's why I'm keen to focus on the "core" problem :-)  We're in agreement!

**Comment by ccaffy** [comment]
Hi all and happy new year !

I do not manage to reproduce this issue on a vanilla XRootD server.

Which version are you running? How does the config file look like?

```
$ curl -I -H "Want-Digest: sha-512,sha-256;q=0.8,sha;q=0.6,md5;q=0.4,adler32;q=0.2" -L https://localhost:1096/tmp/bigfile_5M_copy
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 5242880
Digest: SHA-512=dias4A==

$ curl -I -H "Want-Digest: adler32" -L https://localhost:1096/tmp/bigfile_5M_copy
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 5242880
Digest: adler32=7626ace0

$ curl -I -H "Want-Digest: DOES_NOT_EXIST" -L https://localhost:1096/tmp/bigfile_5M_copy
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 5242880
Digest: unknown=dias4A==

$ curl -I -H "Want-Digest: sha"  -L https://localhost:1096/tmp/bigfile_5M_copy
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 5242880
Digest: SHA=dias4A==
```

I do not manage to get a 500 error on the server side.

Thanks in advance.

Cheers,
Cedric

**Comment by paulmillar** [comment]
Hi Cedric

Happy New Year!

Your posts are certainly very interesting.

My particular examples of this issue (500 Internal Server Error response) were using the Vanderbilt endpoint: that's where I discovered this problem.

I'm speculating here, but the problem could be somehow related to the underlying xrootd "plugin" (sorry if that's the wrong term) for accessing the underlying storage.  I believe they (Vanderbilt) are running something a little out of the ordinary, but I don't remember the details.  I discovered this problem while we were investigating the cause of data corruption, which was also the result of the interface to their storage.

Did you try exercising the Vanderbilt endpoint?

However, you reply is still interesting, surprising and rather concerning.  I'd say it is worthy of opening a separate issue!

When faced with a request, asking for an unknown algorithm (algorithm `DOES_NOT_EXIST`), the xrootd server is somehow still able to come up with a checksum value.  The reply says it knows the checksum for the file using the algorithm `unknown`.

I'm also rather suspicious that the file (apparently) has the same value (`dias4A==`) for the `SHA-512`, `unknown` and `SHA-1` algorithms.  The values should be distinct for each algorithm, particular as the different algorithms produce values with different bit-lengths.

Just to labour the point, this returned value is also way too short for those algorithms:  `thvDyvhfIqlvFe+A9MYgxAfm1q5=` is a valid SHA-1 value, in base-64.

If it helps any, `dias4A==` decodes to the four byte sequence `76 26 ac e0` (in hex) .

**Comment by ccaffy** [comment]
I did not try against the Vanderbilt endpoint because I do not have any token to access it nor a directory I can use...

I identified a bug in the code which is easily fixable: The four bytes sequence `76 26 ac e0` is the adler32 checksum of the file I compute the checksum against via curl... Though, the output is base64 encoded while it should not be --> I found the code to fix.

By default, if a user passes a checksum type that is unknown by XRootD, XRootD will use the one that is configured here: https://xrootd.slac.stanford.edu/doc/dev55/xrd_config.htm#_Toc88513998
In my case, I configured `xrootd.chksum adler32`.

In the case the user asks for sha, sha-256, the server returns the base64 encoding of the adler32 checksum of the file (like shown above).

@abh3 or @bbockelm shall we change the behaviour ? (I believe the answer is yes... :D)

**Comment by abh3** [comment]
Hu Cedric,

Hmmm, the behaviour should not be as described. XRootD never returns 
anything in base64, so it would appear there is some misunderstanding on 
what is happening. Paul and I have gone through this exercise several 
times as to what should happen when a series of checksums are requested. 
The behaviour differs from the xroot side vs the http side and we still 
have no concrete example as to why. Anyway, I'd like to see the easy fix 
as I expect it's not going to be all that easy given unexpected 
side-effects.

Andy

**Comment by ccaffy** [comment]
Ah yes, what I describe here is for HTTP only. Here is the link where the buggy code is: https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L145

The easy fix is to add the `!` before `strcasecamp` for each line. But it will not fix the overall behaviour, of course.

**Comment by bbockelm** [comment]
@ccaffy - yup, I think you're right!

FWIW, the rules of what's base64 encoded versus hexadecimal encoded versus decimal encoded are managed by IANA: https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml

Does this also cover the case of ignoring checksums it doesn't understand?

**Comment by ccaffy** [comment]
Thanks for the link ! Now I understand from where this encoding comes from !!

For checksums it does not understand, the base64 encoding is not performed.

**Comment by paulmillar** [comment]
Hi @ccaffy ,

At the risk of mentioning what you already know ... the correct behaviour is defined by RFC 3230.

In particular, the server should simply ignore requested algorithms if it doesn't understand or support them.

For example, if the server doesn't understand `unknown-alg` then a request with:

    Want-Digest: adler32, unknown-alg

should be treated the same as a request for:

    Want-Digest: adler32

**Comment by ccaffy** [comment]
> At the risk of mentioning what you already know ... the correct behaviour is defined by RFC 3230.

I did not know, now things are clear! Thanks ! ;)

**Comment by bbockelm** [comment]
@ccaffy - additionally, this case caught my eye:
```
$ curl -I -H "Want-Digest: DOES_NOT_EXIST" -L https://localhost:1096/tmp/bigfile_5M_copy
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 5242880
Digest: unknown=dias4A==
```
The behavior is _almost_ correct -- I think it's returning the default (adler32) checksum in your case.  The digest should be labelled as `adler32` and not "unknown", however.

**Comment by ccaffy** [comment]
The digest name is deduced from what the user has put in his `Want-Digest` header during their request. XRootD HTTP transforms that name to `unknown` if it does not do it.

Now, I don't see in the RFC 3230 what the server is supposed to return if a user asks for a digest that is not supported ? An error or something else ?

**Comment by bbockelm** [comment]
Hi @ccaffy -

I think Paul gave a good overview in his comment above: https://github.com/xrootd/xrootd/issues/1707#issuecomment-1125790804

Basically, the RFC is unfortunately vague in this area but practical experience has shown that unsupported digests are best ignored (this is quite helpful in rolling out new digest algorithms for example) instead of an error.  I believe that if only unsupported digests are requested, it's probably best to return a default (adler32 in your example above).

The current behavior of returning an invalid digest (`unknown`) but with a HTTP 200 status is probably the least desirable option.

**Comment by ccaffy** [comment]
Alright thanks! So I believe I can just return the digest configured by default in the server with the proper name (in my case `adler32`) in the case a user asks for a checksum type that does not exist...

**Comment by paulmillar** [comment]
IIRC (please double-check with the RFC!), the server is always free to return any checksum values (or combination of checksum values), independent of the client's request.  So, I believe it would be fine for xrootd to always return an ADLER32 value.

However, supporting algorithm negotiation would be good :-)

**Comment by ccaffy** [comment]
While doing further testing I managed to find how to have a 500 error while asking for an checksum that exists but that was not configured on the xrootd server.

The error happens only if the config file of the server contains two checksums: `xrootd.chksum adler32 md5`

Now if I ask for a checksum that does not exist, the server will return a 500 error:

```
[xrootddev@xrootd-ccaffy-dev01 http_server_certificate_tests]$ curl -I -H "Want-Digest: does_not_exist"  -L https://xrootd-ccaffy-dev01.cern.ch:1096/tmp/bigfile_5M_copy
HTTP/1.1 500 Internal Server Error
Connection: Close
Server: XrootD/v20220509-f2bdd84
Content-Length: 0
```

Investigating that bug too... ;)

**Comment by ccaffy** [comment]
> While doing further testing I managed to find how to have a 500 error while asking for an checksum that exists but that was not configured on the xrootd server.
> 
> The error happens only if the config file of the server contains two or more checksums: `xrootd.chksum adler32 md5`
> 
> Now if I ask for a checksum that does not exist, the server will return a 500 error:
> 
> ```
> [xrootddev@xrootd-ccaffy-dev01 http_server_certificate_tests]$ curl -I -H "Want-Digest: does_not_exist"  -L https://xrootd-ccaffy-dev01.cern.ch:1096/tmp/bigfile_5M_copy
> HTTP/1.1 500 Internal Server Error
> Connection: Close
> Server: XrootD/v20220509-f2bdd84
> Content-Length: 0
> ```
> 
> Investigating that bug too... ;)

And the documentation says :

>  If more than one algorithm has been specified, a cgi scan is made for cks.type and, if specified, its argument must match one of the specified algorithms in the configuration file or an error results.

Hence the 500 error...

**Comment by abh3** [comment]
I thought we all decided some time ago that
a) Ignore unsupported checksums,
b) On the first supported checksum return that checksum,
c) If no requested checksums are supported return the default checksum 
(with the proper name),
d) If checksums are not supported at all, return an error.

I thnk (c) above is the new distinction in this recent thread. Right?

**Comment by abh3** [comment]
Likely the easiest solution here is for the server to set an envar with a 
list of supported checksums. I presume a blank separated list would be OK 
unless some other delimiter is better.

Andy

**Comment by bbockelm** [comment]
> I thought we all decided some time ago that ...

I think all your items (a) - (d) are correct

**Comment by paulmillar** [comment]
Hi Andy,

Some comments on your four points above:
  a) yup, absolutely,

  b) Ideally xrootd would select the requested algorithm(s) with the highest (non-zero) q value.  However, I'm pretty sure selecting the first supported algorithm (ignoring any q-values) will not break anything.  Just by-the-by, dCache (IIRC) builds the `Want-Digest` with descending q-value, based on the number of bits.  If xrootd selects the first algorithm, it should even select the one dCache prefers :-)

  c) This is perfectly fine behaviour.  The xrootd could also return an empty "Digest" header; i.e.,
  
    Digest: 

  d) Returning an error is certainly OK (any HTTP request may return a 500 status code) but, in this case, I don't think it is necessary.  The xrootd server could simply return an empty "Digest" header to indicate that none of the client's requested algorithms are supported.

Just to confirm: RFC 3230 defines the digest-algorithm values in terms of "token" (as per RFC 2616).  A token may not have spaces, commas, semicolons or colons.  Therefore, it's safe to use any of these to build the list.

HTH,
Paul.
