### ISSUE TITLE
cmsd: Have ability to quarantine blacklisted hosts to a different cmsd cluster

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#171]
This came up during the CMS Offline & Computing Week - 

We'd like to have the ability to blacklist certain sites from our central redirectors.  Instead of disabling them within the current cmsd cluster, we'd like to be able to redirect the incoming cmsd into a separate testing cluster.

**Comment by bbockelm** [comment]
Hi,

Had the first AAA meeting of the year and Ken kindly reminded me I let this one drop.

The consensus is the proposed change (in terms of the semantics of "only redirect for newer cmsd; otherwise blacklists" and the config file format) would work for us.  Full steam ahead, I suppose!

Brian

**Comment by abh3** [comment]
Thanks for the feedback. You will see a commit implementing this in a week or so.

**Comment by abh3** [comment]
The feature has been added to git head and will appear in 4.2.
