### ISSUE TITLE
Build XrdPosix for XRDCL_ONLY

### ISSUE THREAD

**Issue by smuzaffar** [xrootd/xrootd#1710]
`XrdPosix` is build when `Server/non-XRDCL_ONLY` part is enabled ( https://github.com/xrootd/xrootd/blob/fedfc834dcc5e8ce7e972eca9f4e775a5d92cb74/src/CMakeLists.txt#L55 ) . Can we make  `XrdPosix` to be build for client part too?

**Comment by simonmichal** [comment]
@smuzaffar : done: beea7c305fdaec28dfd5bfd108482eb54703157f

**Comment by smuzaffar** [comment]
thanks @simonmichal

**Comment by smuzaffar** [comment]
@simonmichal , although https://github.com/xrootd/xrootd/commit/beea7c305fdaec28dfd5bfd108482eb54703157f allowed to build `libXrdPosix.so  libXrdPosixPreload.so` libraries but the build system did not copy the `XrdPosix` headers under `include/xrootd` directory. With `-DXRCL_ONLY=TRUE` my include directory has
```
> ls xrootd/5.4.2/include/xrootd/ 
XProtocol  Xrd  XrdCl  XrdHttp  XrdNet  XrdOuc  XrdSec  XrdSys  XrdVersion.hh  XrdXml  XrdXrootd  private
> ls xrootd/5.4.2/include/xrootd/private
Xrd  XrdCl  XrdNet  XrdOuc  XrdPosix  XrdSecsss  XrdSys  XrdZip
```

**Comment by smuzaffar** [comment]
@simonmichal , can you also please look in to (this issue)[https://github.com/xrootd/xrootd/issues/1710#issuecomment-1131665164]?

**Comment by simonmichal** [comment]
@smuzaffar : absolutely, it shell be fixed!

**Comment by simonmichal** [comment]
@smuzaffar : just pushed cc064c63a1d15be1a1825611785789c33c298a55, it should do the trick, please double check, I will sneak it into `5.4.3` (I don't think we need an RC only because of this one commit).

**Comment by simonmichal** [comment]
@smuzaffar : how is it going? is it working for you? if yes can we close this issue?

**Comment by smuzaffar** [comment]
ah sorry I forgot to update here. Yes `-DXRCL_ONLY=TRUE` works now and all the required headers are properly copy
