### ISSUE TITLE
xrootd initiailization fails when it fails to delete files listed in posc.log

### ISSUE THREAD

**Issue by cvuosalo** [xrootd/xrootd#1721]
With XRootD 5.4.1 running on CentOS Linux 7.9.2009, we have observed `xrootd` failing initialization after a re-start. The `xrootd.log` shows `xrootd` attempting to delete files listed in `/var/run/xrootd/t2wisc/.ofs/posc.log`, but each attempt fails with "permission denied". After these failed attempts, the log reports:
```
------ File system server initialization failed.
220616 04:46:12 2228 XrootdConfig: Unable to load base file system using default
------ xroot protocol initialization failed.
220616 04:46:12 2228 XrdProtocol: Protocol xroot could not be loaded
------ xrootd t2wisc@g32n20.hep.wisc.edu:-1 initialization failed.
```
We have discovered that deleting the `/var/run/xrootd/t2wisc/.ofs/posc.log` and then starting `xrootd` results in a successful start-up without errors.

We have hundreds of xrootd nodes, but only a handful show this initialization failure. On most of our nodes the `posc.log` is 64 bytes in size. On the nodes that show the failures, the `posc.log` is larger and seems to contain file names.

Here is an example of a file that helps trigger this failure. Before xrootd re-start, xrootd reports a problem with this file:
```
220612 12:19:18 5913 acc_Audit: cmspilot.367:188@[::ffff:129.93.227.92] grant gsi osg_cmsuser@[::ffff:18.12.8.19] create /store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log/cmsRun_9.log.tar.gz
220612 12:19:18 5913 hdfs_stat: Unable to stat /store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log/cmsRun_9.log.tar.gz; No such file or directory
File we will access: /store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log/cmsRun_9.log.tar.gz
220612 12:19:18 5913 ofs_open: cmspilot.367:188@[::ffff:129.93.227.92] Unable to fchmod /store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log/cmsRun_9.log.tar.gz; is a directory
hdfsDelete(path=/store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log/cmsRun_9.log.tar.gz, recursive=0): FileSystem#delete error:
RemoteException: Permission denied: user=nobody, access=WRITE, inode="/store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log":osg_cmsuser:cmsprod:drwxr-xr-x
```
This file is created as a zero-size file:
```
-rw-r--r-- 1 osg_cmsuser 0 Jun 12 12:19 /hdfs/store/temp/user/santocch.a98004385da0008d4e6aefa9b0a59973eeb30ede/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/crab_wjets-madgraph-2018/220612_150920/0000/log/cmsRun_9.log.tar.gz
```
It is not a directory, even though the `xrootd.log` claims it "is a directory".
After this initial failure to delete the file, when `xrootd` is re-started, it again fails to delete the file, along with other files, and then reports that initialization failed.

There are at least two questions. Why does `xrootd` fail to delete the file in the first place, even though it would seem to have permission. And then second, why does `xrootd` keep trying to delete files that it didn't have permission to delete when it first tried?

**Comment by cvuosalo** [comment]
We learned some more about this bug. It relates to issue #1366. There are three ingredients for this problem: `gfal-copy` trying to write files, the `root:` protocol, and HDFS as the file system. The sequence of events is as follows.
1. A request is made by `gfal-copy` to write a file using the `root:` protocol.
2. At the data node, this request fails due to #1366. The file name is added to the `posc.log`.
3. The sysadmin re-starts `xrootd` on the data node (for maintenance or other reasons).
4. During start-up, `xrootd` goes through the `posc.log` to clean up the files. It tries to delete the files from step 2, but once again it fails because of bug #1366.
5. Because `xrootd` can't clean up the files in the `posc.log`, it enters a non-responsive state and does nothing.

**Comment by cvuosalo** [comment]
We would request, even if #1366 can't be fixed, that `xrootd` would terminate and shut down `cmsd` if it cannot initialize. For `xrootd` to enter a non-responsive state but keep running is not helpful.

**Comment by abh3** [comment]
First, could you tell me what the error was that prevented the file from being deleted? I am looking at the log snippet posted above but it does not appear to be related to the error encountered during initialization. However, it does seem to imply that   the multi-user plugin is being used. If so, it is incompatible with POSC and the only solution is to turn off POSC:
ofs.persist off
https://xrootd.slac.stanford.edu/doc/dev54/ofs_config.htm#_Toc89982386

I should note that multi-user is incompatible with checkpointing as well and that needs to be turned off as well:
ofs.chkpnt disable
https://xrootd.slac.stanford.edu/doc/dev54/ofs_config.htm#_Toc89982374

The next question is what do you mean by 'unresponsive state'? For any kind of initialization failure the xrootd daemon  simply exits. So, clients connecting to the daemon will get an error (i.e. unable to connect). The cmsd will continue but will tell the redirectors that it is connected to that server operation has been suspended (i.e. there is no xrootd daemon running) and no clients should be sent to that server. This would be the case whether or not the cmsd there was running.

**Comment by cvuosalo** [comment]
@abh3 Here's a failed deletion attempt during `xrootd` initialization:
```
hdfsDelete(path=/store/unmerged/SAM/StageOutTest-OS-73-Tue-Jun-14-19_59_12-2022, recursive=0): FileSystem#delete error:
RemoteException: Permission denied: user=nobody, access=WRITE, inode="/store/unmerged/SAM":cmsprod:cmsprod:drwxrwxr-x
220616 01:30:40 2515 hdfs_unlink: Unable to unlink /store/unmerged/SAM/StageOutTest-OS-73-Tue-Jun-14-19_59_12-2022; Permission denied
220616 01:30:40 2515 ofs_Config: Unable to unpersist /store/unmerged/SAM/StageOutTest-OS-73-Tue-Jun-14-19_59_12-2022; permission denied
```
The very lengthy Hadoop java stack trace has been omitted here.

**Comment by cvuosalo** [comment]
@abh3 Concerning the unresponsive state, it is just that. `xrootd` continues to run. It does not terminate. It just does nothing and doesn't respond. It is confusing for our monitoring because `xrootd` appears to be running even though it is effectively dead. The data node becomes a black hole that receives requests and ignores them. The way I found to recognize this problem is to check the `xrootd.log`. If it ends with "initialization failed.", that indicates the problem.

**Comment by abh3** [comment]
So, the log lines still imply that multi-user is being used since the incoming user is tagged as nobody and that should not happen. Is the multi-user plug-in being used?

As for the black hole, that should not happen and likely is being caused by some hang-up in a plugin (e.g. hdfs) that causes the whole process to hang. When it does get into that state, attach gdb and capture the output of

thread apply all bt

there should not be much output but the thread that is hanging the process should be obvious.

**Comment by cvuosalo** [comment]
@abh3 Sorry, I can't quite reproduce the hanging problem. I can re-create the `xrootd` "initialization failed" condition, but in this case, `xrootd` terminates. With `xrootd` down, requests to the data node time out.

Previously, we observed that the redirector sent requests to data nodes that had experienced initialization failure, and the requests failed. That's how we noticed all these issues in the first place. I haven't been able to reproduce that behavior now.

Since we will be changing our configuration to disable the `persist` option, I think all these issues will be prevented at our site in the future. It seems these problems occur because `persist` was enabled by default in multi-user mode, which, you say, is not supported. It would be good if multi-user mode would automatically disable both `chkpnt` and `persist` so these errors would not be able to occur.

**Comment by cvuosalo** [comment]
@abh3 I must correct a previous comment. At T2_US_Wisconsin, multi-user mode is NOT enabled. The `xrootd-mulituser` plugin is NOT installed. The `xrootd-hdfs` plugin does write files to HDFS as their authenticated users, but, apparently, that does not use the multi-user mechanism.
You said that POSC mode and checkpointing are incompatible with multi-user mode. However, since our configuration does not operate in multi-user mode, what are your recommendations for these two configuration options?

**Comment by abh3** [comment]
Unfortunately, the recommendation is still the same. The issue stems from changing the file ownership from the server's uid either via multi-user or via some other mechanism (like the one here). Not having the file owned by the server prevents the server from cleaning up errors during initialization. In the POSC case it's to delete a file that was not properly closed and for checkpointing to roll back any changes to the file that occurred prior to a crash. Both of these operations occur under the server's uid which obviously won't work here.

**Comment by cvuosalo** [comment]
@abh3 Thanks for the explanation. We will disable the checkpointing and POSC options, and the initialization problem should then be prevented. We will test the revised configuration Tuesday, and then I will close this issue if all goes well.

**Comment by cvuosalo** [comment]
We disabled checkpointing and POSC in our configuration:
```
ofs.chkpnt disable
ofs.persist off
```
With these options disabled, `xrootd` will not attempt the clean-up actions at re-start that caused the failure described in this issue, so it can be considered resolved. Closing this issue.

**Comment by xrootd-dev** [comment]
I will assume you are running the multi-user plug-in. If so, this is a 
known problem and is not the fault of xrootd but the result of the
multi-user plugin. That plugin it incompatible with POSC as well as 
checkpointing. These features must be turned off when running 
multi-user. Specifically,

ofs.persist off
https://xrootd.slac.stanford.edu/doc/dev54/ofs_config.htm#_Toc89982386

ofs.chkpnt disable
https://xrootd.slac.stanford.edu/doc/dev54/ofs_config.htm#_Toc89982374

**Comment by cvuosalo** [comment]
@xrootd-dev As I mentioned in a previous comment (https://github.com/xrootd/xrootd/issues/1721#issuecomment-1188244688), our site does NOT use the multi-user plug-in. However, we do use the `xrootd-hdfs` plug-in, which may provide similar functionality with regard to user file ownership. As I said in my previous comment (https://github.com/xrootd/xrootd/issues/1721#issuecomment-1189582751), we disabled checkpointing and persistence and thereby resolved this issue.
