### ISSUE TITLE
requirement of both uuid and libuuid

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1727]
Hi @simonmichal ! It seems that xrootd requires both libuuid and uuid packages ..
Are really both required? could this be reduced to a single dependency? (maybe just on libuuid)?
Thanks a lot!

**Comment by simonmichal** [comment]
Hi @adriansev, on which platform is this, is the error coming from cmake or rpmbuild? Or intension is to be dependent only on `libuuid`

**Comment by adriansev** [comment]
Hi @simonmichal ! this is on ubuntu 1804 and the messages comes from cmake in this form (i dump bellow all related to uuid):
```
CMake Warning (dev) at /home/jgrosseo/o2/sw/ubuntu1804_x86-64/CMake/v3.23.1-local1/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (uuid) does
  not match the name of the calling package (LibUuid).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindLibUuid.cmake:55 (find_package_handle_standard_args)
  cmake/XRootDFindLibs.cmake:6 (find_package)
  CMakeLists.txt:31 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found uuid: /home/jgrosseo/o2/sw/ubuntu1804_x86-64/UUID/v2.27.1-local4/include  

.....

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'json-c'
--   No package 'json-c' found
-- Checking for module 'uuid'
--   No package 'uuid' found
CMake Error at /home/jgrosseo/o2/sw/ubuntu1804_x86-64/CMake/v3.23.1-local1/share/cmake-3.23/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/jgrosseo/o2/sw/ubuntu1804_x86-64/CMake/v3.23.1-local1/share/cmake-3.23/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  cmake/XRootDFindLibs.cmake:127 (pkg_check_modules)
  CMakeLists.txt:31 (include)

```

this was solved by installing `uuid-dev` system package

Thanks a lot!

**Comment by adriansev** [comment]
oh, also it's not clear to me where json-c is required.. at first glance only Macaroons use json-c but then if Macaroons are not found or disabled, then json-c should not be used ...

**Comment by adriansev** [comment]
on my fedora desktop ("Christmas tree installed packages" style) i see this:
```
 Looking for uuid_generate_random in uuid
 Looking for uuid_generate_random in uuid - found
 CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
   The package name passed to `find_package_handle_standard_args` (uuid) does
   not match the name of the calling package (LibUuid).  This can lead to
   problems in calling code that expects `find_package` result variables
   (e.g., `_FOUND`) to follow a certain pattern.
 Call Stack (most recent call first):
   cmake/FindLibUuid.cmake:55 (find_package_handle_standard_args)
   cmake/XRootDFindLibs.cmake:6 (find_package)
   CMakeLists.txt:31 (include)
 This warning is for project developers.  Use -Wno-dev to suppress it.
 Found uuid: /usr/include
 
 and later :

  Found Macaroons: /usr/include
 Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0")
 Checking for module 'json-c'
   Found json-c, version 0.15
 Checking for module 'uuid'
   Found uuid, version 2.38.0

```
the same output is also on centos 7

so it's not clear if uuid or libuuid is searched for, found and used

**Comment by simonmichal** [comment]
@adriansev : after having a closer look my impression is that the counterpart of rhel's `libuuid-devel` on ubuntu is `uuid-dev`. It seems OK to me this one is required on ubuntu.

On rhel we require only `libuuid-devel` for build-time, there is also a package called `uuid-devel` but this is not required. Now regarding the `cmake` message that references `uuid`, I do see this can be misleading but the package is called differently on different platforms, and also the shared lib is called `uuid` with the `lib` prefix. I don't know there's much I can do, but I'm open to suggestions ...

**Comment by adriansev** [comment]
@simonmichal Not quite, there are two distinct packages no matter the distro:
```
root@ALICE2:~# apt search uuid | grep '^uuid'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

uuid/focal,now 1.6.2-1.5build7 amd64 [installed]
uuid-dev/focal-updates,focal-security,now 2.34-0.1ubuntu9.3 amd64 [installed]
uuid-runtime/focal-updates,focal-security,now 2.34-0.1ubuntu9.3 amd64 [installed,automatic]
uuidcdef/focal 0.3.13-7 amd64
root@ALICE2:~# apt search uuid | grep '^libuuid'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libuuid-perl/focal 0.28-1build1 amd64
libuuid-tiny-perl/focal,focal 1.0400-2 all
libuuid-urandom-perl/focal,focal 0.001-1 all
libuuid1/focal-updates,focal-security,now 2.34-0.1ubuntu9.3 amd64 [installed]
libuuidm-ocaml-dev/focal 0.9.7-1build1 amd64
```

so, given that there is package building CI in place, maybe just remove the `pkg_check_modules(UUID REQUIRED uuid)` from cmake/XRootDFindLibs.cmake and `uuid` requirements from packaging/wheel/setup.py (where it should be replaced by libuuid) as well as in packaging/debian/control and let's see if CI works...

for reference:
```
root@issaf: ~ # rpm -ql libuuid-devel | grep -v man
/usr/include/uuid
/usr/include/uuid/uuid.h
/usr/lib64/libuuid.so
/usr/lib64/pkgconfig/uuid.pc
/usr/share/doc/libuuid-devel-2.23.2
/usr/share/doc/libuuid-devel-2.23.2/COPYING
root@issaf: ~ # rpm -ql uuid-devel | grep -v man
/usr/bin/uuid-config
/usr/bin/uuid-config.64
/usr/include/uuid.h
/usr/lib64/libossp-uuid.so
/usr/lib64/pkgconfig/ossp-uuid.pc
```

so, given that i get this (note the usage of `uuid/uuid.h` (of libuuid) and absence of `uuid.h` provided by `uuid` ):
```
ag uuid.h
cmake/FindLibUuid.cmake
13:#   True if libuuid has been found.
15:#   Where to find uuid/uuid.h.
27:#   where to find the uuid/uuid.h header (same as UUID_INCLUDE_DIRS).
34:  find_path(UUID_INCLUDE_DIR uuid/uuid.h)
40:  check_cxx_symbol_exists("uuid_generate_random" "uuid/uuid.h" _uuid_header_only)
43:if(NOT _uuid_header_only AND NOT UUID_LIBRARY)
52:unset(_uuid_header_only)

src/XrdMacaroons/XrdMacaroonsHandler.cc
7:#include <uuid/uuid.h>

src/XrdCl/XrdClFileStateHandler.cc
58:#include <uuid/uuid.h>
```

i'm pretty sure that xrootd does not use `uuid` package, it only use `libuuid` package
so the dependencies should not re{quest,quire} `uuid` but only `libuuid` ..
Maybe it's better if you can do it, so the package building CI to be able to show the problems?

**Comment by simonmichal** [comment]
OK, I see your point, it's this line:
https://github.com/xrootd/xrootd/blob/425b6b25bf6c816226d202192fd8d010d7b7743a/cmake/XRootDFindLibs.cmake#L127
yes we don't need a build dependency on `uuid` only on `libuuid`

But to be on the safe side, let me run some tests first ...

**Comment by amadio** [comment]
This reminds me of a similar discussion that happened in Davix. See https://github.com/cern-fts/davix/commit/bfffca06374b666f22084f7209fa5b1a8a9e6371. Depending on where you are building, you may or may not need libuuid to provide the symbols, depending on if the kernel provides them or not. I don't know what XRootD will need, but it might be worth taking a look at the relevant man pages, like `uuid(3)` and `uuid_generate(3)`, and the headers provided by the OS. On Linux, libuuid is usually part of the [util-linux](https://github.com/util-linux/util-linux/tree/master/libuuid) package, but on MacOS the `uuid/uuid.h` header is part of the command line tools, and there is no libuuid.

**Comment by simonmichal** [comment]
@adriansev : after investigating a bit more, `pkg_check_modules(UUID REQUIRED uuid) ` will look for the libuuid installation, so it is redundant but does not introduce dependency on another package (all the vars point to libuuid installation).
