### ISSUE TITLE
XrdEc or XrdZip : can it handle more than 32k entries in a .zip ?

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1733]
While playing with XrdEc, I ran into an issue that when a file is really large, and require putting more than 32k chunks in backend .zip archives, I can't read them back. If this very large file itself is a non-zip file, xrdcp (with XrdEc config loaded) will get:

Run: [ERROR] Received corrupted data: End-of-central-directory signature not found. (source)

If this very large file is a .zip file, xrdcp will crash.

Furthermore, if I go to the backend data servers that host those corresponding zip archives, and trying to unzip them, unzip will complain:

  End-of-central-directory signature not found.

**Comment by xrootd-dev** [comment]
The issue here is that the "directory" is assumed to be no more than 64K 
and that is all that is read. Obviously, in your case, it is bigger than 
that and will not be able to be processed. Michal may be able to correct 
this but given the odditities of zip files it may not be all that easy.

Andy

**Comment by abh3** [comment]
I am closing this ticket. Please reopen if necessary.
