### ISSUE TITLE
Documented client chunk size is incorrect

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#1757]
4.2.6 XRD CPCHUNKSIZE
Size of a single data chunk handled by xrdcp / XrdCl::CopyProcess.
Default: 16KiB
```
but the code (XrdClConstants.hh, line ), has
```
  const int DefaultCPChunkSize             = 8388608;
```
and this is what I see being used when I run xrdcp with `d -3`

**Comment by simonmichal** [comment]
@abh3 : thank you for reporting the issue, the docs have been updated.
