### ISSUE TITLE
[xroot spec] clarification requested on IP-based kXR_redirect response

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#1762]
My reading of the [kXR_redirect response](https://xrootd.slac.stanford.edu/doc/dev55/XRdv511.htm#_Toc78833351) does not make it clear whether or not returning an IP address is valid.  The spec describes `host` as:
> ASCII name of the to which the client should connect. [...]

Through informal communication, I believe the intention here is to return a DNS-resolvable name for the host; e.g., the FQDN.

It would be helpful to know whether an IP address is a valid response.  If so, in which format the response should be presented; for example, should IPv6 addresses be placed in square brackets?  Are double-colons allowed?  ...etc..

Please update the spec to include a more extensive description of this response and, in particular:
  1. whether an IP address is a valid response for `host`
  2. how to represent/serialise an IP address in the response; in particular, for IPv6 addresses.

Cheers,
Paul.

**Comment by abh3** [comment]
I'll correct that. In general, we used to return an IP address and it is still valid to do so. However, it has been deprecated for two main reasons: a) IP address natting common in firewalled sites and endemic to k8s, and b) few people add an IP address to a SAN extension making it impossible to connect using TLS.

**Comment by abh3** [comment]
The documentation will be updated withon 24 hours so I am closing this ticket.
