### ISSUE TITLE
Feature request: Add an option to configure an XRootD redirector as readonly

### ISSUE THREAD

**Issue by yujunwu2010** [xrootd/xrootd#1764]
Hello,

I exchanged email with Andy on this and he suggested to open a github feature request. Hope this is the right place. My request is: Could you please add a new feature in XRootD redirector so that admins can configure a high tier-ed XRootD redirector as readonly? If there are write requests to this redirector, the requests will be rejected. Some background info are:

CMS experiment uses Xrootd Service (AAA) for Remote Data Access. Users are supposed to only read files from remote site through our tier-ed XRootD redirectors. Recently, it was noticed some user(s) was trying to write to the high-tiered XRootD redirector, e.g., USCMS regional redirector. Since some site XRootD servers are allowed to write, some expected amount of data were written to some site storage. Since our regional redirector is supposed readonly, it will be great if all requests to this redirector are forced readonly (and writes are rejected/denied).

Thanks in advance for your help on this.

Regards,
Yujun

**Comment by abh3** [comment]
A new directive is introduced, cms.mode, that can be used to configure
a redirector to disallow write requests. This is equivalent to using
the globalro export option on every server connecting to the
redirector but allows such a configuration to be centralized.
This patch is for R6. Sorry that it took us so long to do.

**Comment by amadio** [comment]
Marking as 5.7.1 for correctness, since we included this feature there.
