### ISSUE TITLE
Where to find (the equivalent of) vomsxrd-0.2.0-1.el6.x86_64 for xrootd4.1?

### ISSUE THREAD

**Issue by tommasoboccali** [xrootd/xrootd#178]
Hi, I was trying to update 3.6 -> 4.1 via Yum, but I seem to miss a library

vomsxrd-0.2.0-1.el6.x86_64 (assuming it need to be updated...)

which we used to have VOMS based authentication (via

sec.protparm gsi -vomsfun:/usr/lib64/libXrdSecgsiVOMS.so -vomsfunparms:grpopt=0|vos=cms|grps=/cms|certfmt=raw

) 

I had understood this library (by G.Ganis) was entering the stable tree ... Is that not the case? Should I ask him for a new library?

Many sites use this, so it would be helpful to have it in the standard repository ... thanks

tom

**Comment by abh3** [comment]
I believe this has been resolved.
