### ISSUE TITLE
Compilation error: class Davix::RequestParams has no member named setAwsAlternate

### ISSUE THREAD

**Issue by Axel-Naumann** [xrootd/xrootd#1803]
Hi,

With Ubuntu16's Daxiv and xrootd v5.5.0 we get:

```
/mnt/build/night/LABEL/ROOT-ubuntu16/SPEC/cxx14/V/6-26/build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/XrdClHttp/XrdClHttpPosix.cc: In function ‘void {anonymous}::SetAuthS3(Davix::RequestParams&)’:
/mnt/build/night/LABEL/ROOT-ubuntu16/SPEC/cxx14/V/6-26/build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/XrdClHttp/XrdClHttpPosix.cc:149:10: error: ‘class Davix::RequestParams’ has no member named ‘setAwsAlternate’
   params.setAwsAlternate(true);
          ^
/mnt/build/night/LABEL/ROOT-ubuntu16/SPEC/cxx14/V/6-26/build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/XrdClHttp/XrdClHttpPosix.cc:152:13: error: ‘class Davix::RequestParams’ has no member named ‘setAwsRegion’
      params.setAwsRegion(getenv("AWS_REGION"));
             ^
/mnt/build/night/LABEL/ROOT-ubuntu16/SPEC/cxx14/V/6-26/build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/XrdClHttp/XrdClHttpPosix.cc:154:13: error: ‘class Davix::RequestParams’ has no member named ‘setAwsRegion’
      params.setAwsRegion("mars");
             ^
```

Can xrootd keep compatibility with old Davix or are we out of luck?

Cheers, Axel

**Comment by xrootd-dev** [comment]
Hi Axel,

I am researching this with the relevant developers but it may come down to 
the "out of luck" case as the code here relies on S3 compatability.

Andy

**Comment by wyang007** [comment]
Hi Alex,

I don't know what version of Davix available on Ubuntu 16. I only compiled this on CentOS 7, which has davix-0.8.2. If you have a lower version, I would suggest that you build your own davix. The reason is that in addition to those functions you mentioned, it is possible that older versions of Davix also doesn't support newer S3 protocol version (v3).

**Comment by Axel-Naumann** [comment]
FYI it's [davix 0.5.0-1build1](https://launchpad.net/ubuntu/xenial/amd64/davix/0.5.0-1build1). It's not about me, it's about ROOT trying to guild against the distro packages.

**Comment by wyang007** [comment]
I see, so you ran into this issue when you try to built ROOT on Ubuntu 16?

If so, I wonder if you can disable the built of submodule XrdClHttp (it is a submodule so far), perhaps via this flag to cmake3: -DXRDCLHTTP_SUBMODULE=0 (or not define it at all). The module is used for xrootd to access HTTP data source (including S3). ROOT already knows how to access HTTP and  I don't think ROOT currently support accessing S3.

**Comment by abh3** [comment]
So, the resolution really is to build with the latest Davix release.
