### ISSUE TITLE
Xrootd 5.5.1 failed to build when -DFORCE_ENABLED=ON -DXRDCL_ONLY=TRUE is used

### ISSUE THREAD

**Issue by smuzaffar** [xrootd/xrootd#1804]
Hi,
  I am trying to build xrootd 5.5.1 client for CMS and it failed with error [a] . Note that the cmake options we use to build includes
```
-DFORCE_ENABLED=ON -DXRDCL_ONLY=TRUE
```

I think https://github.com/xrootd/xrootd/blob/master/cmake/XRootDDefaults.cmake#L31-L32 should be set to `FALSE` for `XRDCL_ONLY=TRUE`

[a]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f4ea1a/28381/external/xrootd/5.5.1-85b58a07b6557565b78005c924a2a88a/log

```
-- Found KERBEROS5: /usr/lib64/libkrb5.so;/usr/lib64/libcom_err.so  
-- Looking for curl_multi_wait
-- Looking for curl_multi_wait - found
CMake Error at /cvmfs/cms-ib.cern.ch/nweek-02755/el8_amd64_gcc10/external/cmake/3.18.2-9266e9e57a6fac9dc658f5e66a697c43/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Macaroons (missing: MACAROONS_INCLUDES MACAROONS_LIB)
Call Stack (most recent call first):
  /cvmfs/cms-ib.cern.ch/nweek-02755/el8_amd64_gcc10/external/cmake/3.18.2-9266e9e57a6fac9dc658f5e66a697c43/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMacaroons.cmake:20 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/XRootDFindLibs.cmake:124 (find_package)
  CMakeLists.txt:31 (include)
```

**Comment by amadio** [comment]
Hi @smuzaffar, can you please try the patch from the pull request above? Then we can add it to 5.5.2 (to be released next month).

**Comment by smuzaffar** [comment]
thanks @amadio , I confirm that  #1805 works

**Comment by amadio** [comment]
Closing as #1805 has been merged.
