### ISSUE TITLE
XrdSecgsi vomsat and vomsfun don't behave as documented

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1817]
Hi,

While trying to enable the extraction of the VOMS attributes from certificates for gsi authentication, from the documentation it seems that setting the `vomsat` to `extract` should be sufficient to also enable the `vomsfun` to be set to `default`.
https://xrootd.slac.stanford.edu/doc/dev54/sec_config.htm#_Toc79101994
More precisely the last statement in the documentation snippet below is not reflected in the code:
```
vomsfun: {file|default}
            specifies the location of the voms plug-in:
            file  -   is the full path if a shared library containing a plug-in function to be called to extract information from the VOMS certificate extension;
            default  -  use the default [extractor](https://xrootd.slac.stanford.edu/doc/dev54/sec_config.htm#_The_voms_plug-in) that comes with the gsi package.

Default is default when the extract or require option is in effect.
```

Therefore, to have things working one needs to specify both `vomsat` and `vomsfun`. Therefore, either the documentation should be updated to reflect the current situation or the code needs to be fixed to have `vomsfun` set to default if `vomsat` is enabled.
Using XRootD 5.5.1.

Thanks!

**Comment by abh3** [comment]
This seems to have gotten caught up in the humanizing of the options that occured some time ago. The documentation sets out the desired interaction as it's the logical and expected. However, the code was never implemented. Now it is.

**Comment by amadio** [comment]
@abh3 I think your commit uses `vomsfun == "default"` when you meant `vomsfun = "default"`. Could you please fix if that's really the case? See also https://my.cdash.org/viewBuildError.php?type=1&buildid=2626294
