### ISSUE TITLE
python pip package no longer installs on ubuntu 20

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1830]
Hi @simonmichal @matthewfeickert ! I just noticed on my codeql github actions that xrootd no longer works being installed (with pip).. i also tried on a local ubuntu 20 machine and i can confirm the lack of functionality .. any idea about this? 
the setuptools is up to date (65.6.0) and the error:
```
      Processing /home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/xrootdbuild/bindings/python
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [14 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'egg_info'
            Version file path: /home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/bindings/python/VERSION
            Version from file: 5.5.1
      
            XRootD library dir:     /home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/xrootdbuild/src
            XRootD src include dir: /home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/src
            XRootD bin include dir: /home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/xrootdbuild/src
            Version:                5.5.1
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/setup.py", line 205, in <module>
          setup(
        File "/home/adrian/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/adrian/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/adrian/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/adrian/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/adrian/.local/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/adrian/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/adrian/tmp/pip-install-lbfysn9e/xrootd_b81d3a0f65dd4bcc834e863b1ab5c4dd/setup.py", line 182, in run
          raise Exception( 'Install step failed!' )
      Exception: Install step failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

```

**Comment by matthewfeickert** [comment]
I'm traveling at the moment and won't have time to look at this before Monday at the earliest.

In general a fully reproducible minimal failing example of the exact commands used in a Docker container (or better yet a Dockerfile) make these discussions a lot easier as there is no guessing about what setup people have then. Can you please provide one?

**Comment by adriansev** [comment]
@matthewfeickert there is no rush at all, we can talk whenever you have time ..
actually by downgrading setuptools to 65.5.1 this was solved and i confirmed this on my ubuntu machine (note that i could reproduce this also on fedora after updating to latest setuptools)
my workflow is this: https://github.com/adriansev/jalien_py/blob/master/.github/workflows/codeql-analysis.yml
and the output of failed xrootd installs can be seen here:
https://github.com/adriansev/jalien_py/actions/runs/3505620883/jobs/5872030993#step:7:821

the exact command used is `python3 -m pip instal --user xrootd`
Thanks a lot!

**Comment by adriansev** [comment]
oh, found the problem: https://github.com/pypa/setuptools/issues/3693
i will close later this when there is a resolution upstream

**Comment by matthewfeickert** [comment]
@adriansev thanks for this nice info. Yeah, I happened to notice this in a test build lately, and indeed the `setuptools` `v65.5.1` seems to be an issue.

I'll look up in the changelog what happened and see if we can make things more robust in general here.

**Comment by matthewfeickert** [comment]
I'm struggling to understand what has changed. The only thing I've determined so far is that things are failing when in the `xrootdbuild/bindings/python/` directory

https://github.com/xrootd/xrootd/blob/f00acdc7559b5189583945b4c27e06dc2637df3e/packaging/wheel/install.sh#L4-L5
https://github.com/xrootd/xrootd/blob/f00acdc7559b5189583945b4c27e06dc2637df3e/packaging/wheel/install.sh#L40

the install command 

https://github.com/xrootd/xrootd/blob/f00acdc7559b5189583945b4c27e06dc2637df3e/packaging/wheel/install.sh#L51

is run which uses the `setup.py` that is generated from the [`bindings/python/setup.py.in`](https://github.com/xrootd/xrootd/blob/f00acdc7559b5189583945b4c27e06dc2637df3e/bindings/python/setup.py.in).

This `setup.py.in` only imports from `setuptools` in

https://github.com/xrootd/xrootd/blob/f00acdc7559b5189583945b4c27e06dc2637df3e/bindings/python/setup.py.in#L6

so I'm not sure why this is so fragile as to break.

Not sure if @henryiii, @jpivarski, or @agoose77 might have more `setuptools` informed thoughts on this next week.

**Comment by amadio** [comment]
From [this page](https://setuptools.pypa.io/en/latest/history.html#v48-0-0) I found the following:
>  To avoid getting any legacy behavior from the standard library, projects are advised to always “import setuptools” prior to importing anything from distutils. This behavior happens by default when using pip install or pep517.build. Workflows that rely on setup.py (anything) will need to first ensure setuptools is imported.

So we will probably need to at least add `import setuptools` by itself somewhere in our `setup.py.in`. Reverting commit 9e01966ff7973fa88cdd30ac20c2181bb76d8e5a fixes the problem in the CI builds that are currently failing, but breaks elsewhere. I am trying to find a solution that will work everywhere.

**Comment by henryiii** [comment]
When you `import setuptools`, or anything inside `setuptools`, that injects ([1](https://github.com/pypa/setuptools/blob/6f7dd7c12ceffa2aefe28c2fbafbad2273980b2b/setuptools/__init__.py#L8), [2](https://github.com/pypa/setuptools/blob/6f7dd7c12ceffa2aefe28c2fbafbad2273980b2b/_distutils_hack/__init__.py#L18-L25)) `setuptools._distutils` as `distutils` in `sys.modules`. IIRC, pip also injects setuptool's distutils for you in some cases, but I wouldn't depend on that. But yes, you should always `import setuptools` before touching distutils. This is especially true in Python 3.12a2+, where distutils has been removed.

Though it looks like you do avoid that? Why are you getting `setup` & `Extension` from `setuptools._distutils.core` instead of `setuptools`, though? `egg_info` is a setuptools thing, so that's likely why the distutils version is broken.

**Comment by amadio** [comment]
Hi @henryiii, thanks for the comments. I tried to use
```python
try:
    import setuptools
except ImportError:
    pass

from distutils.core import setup, Extension
from distutils import sysconfig
```
but unfortunately this still fails in some cases. The idea is to use `import setuptools` to override `distutils` when that's available. I also tried a variant in which I do `from setuptools import setup, Extension` then just `import sysconfig`, but that also didn't work everywhere. Tomorrow I will try to debug the failures and find a solution, but in the longer term, I think I will just take some time to write new python packaging code following [PEP 517](https://peps.python.org/pep-0517/) and [PEP 632](https://peps.python.org/pep-0632/), dropping usage of deprecated stuff altogether.

**Comment by henryiii** [comment]
```python
try:
    from setuptools import setup, Extension
    import sysconfig
except ImportError:
    from distutils.core import setup, Extension
    from distutils import sysconfig
```

? Where does the `import setuptools` fail, though? Ideally, with a pyproject.toml pulling in setuptools, you can ignore the fallback.

**Comment by matthewfeickert** [comment]
> I do note that using `import distutils` rather than the vendored copy _does_ work.

The point of PR #1700 was to move off `distutils` as it is being deprecated, as @henryiii mentioned.

There I was already trying to do the guard that @henryiii suggests

https://github.com/xrootd/xrootd/blob/8e1e528232d8ead08468eefcbf991737eb5751da/bindings/python/setup.py.in#L3-L19

though as to

> Where does the `import setuptools` fail, though?

this was attempted in PR #1585, but 

> This PR was meant to also change:
> 
> * `distutils.setup` -> `setuptools.setup`
> * `distutils.sysconfig` -> CPython's `sysconfig`
> 
> but it seems that these are still required given the current state of the build and will need to be revised in a later PR.

I don't remember where exactly this failed, so let me post this and rerun the Docker build that is described there.

**Comment by henryiii** [comment]
I'd try dropping in a `pyproject.toml` with:

```python
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta
```

And just seeing what happens. I'd try that, but I'm not sure how to trigger the generation properly.

**Comment by amadio** [comment]
> ```python
> try:
>     from setuptools import setup, Extension
>     import sysconfig
> except ImportError:
>     from distutils.core import setup, Extension
>     from distutils import sysconfig
> ```
> 
> ? Where does the `import setuptools` fail, though? Ideally, with a pyproject.toml pulling in setuptools, you can ignore the fallback.

This is exactly what I tried, but on some of the CI checks it failed.

**Comment by henryiii** [comment]
Is there a link to the CI?

**Comment by matthewfeickert** [comment]
> ```python
> try:
>     from setuptools import setup, Extension
>     import sysconfig
> except ImportError:
>     from distutils.core import setup, Extension
>     from distutils import sysconfig
> ```

This 

```diff
diff --git a/bindings/python/setup.py.in b/bindings/python/setup.py.in
index fbac3e6df..c5bbec503 100644
--- a/bindings/python/setup.py.in
+++ b/bindings/python/setup.py.in
@@ -3,7 +3,7 @@ from __future__ import print_function
 # setuptools._distutils added in setuptools v48.0.0
 # c.f. https://setuptools.pypa.io/en/latest/history.html#v48-0-0
 try:
-    from setuptools._distutils.core import setup, Extension
+    from setuptools import setup, Extension
     # sysconfig v48.0.0+ is incompatible for Python 3.6 only, so fall back to distutils.
     # Instead of checking setuptools.__version__ explicitly, use the knowledge that
     # to get here in the 'try' block requires setuptools v48.0.0+.

```


works now (including for [`setuptools` `v65.6.0+`](https://setuptools.pypa.io/en/latest/history.html#v65-6-0).)

![Screenshot from 2022-11-30 14-23-30](https://user-images.githubusercontent.com/5142394/204900576-2f505f14-f53b-48ee-9526-f0583d4d5b47.png)


Making a PR now.
