### ISSUE TITLE
Respect needTLS in the ZTN authentication protocol (?)

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1842]
ZTN (quite correctly IMHO) asserts that it needs a TLS connection to be used:

https://github.com/xrootd/xrootd/blob/master/src/XrdSecztn/XrdSecProtocolztn.cc#L188

It's dangerous, of course, to send out tokens on a connection that hasn't been upgraded to TLS.

However, from reading the code, I'm unable to tell if the needTLS attribute is respected.  Can someone confirm/deny that this is working as expected?

(This topic came up during the WLCG DOMA BDT meeting today)

**Comment by xrootd-dev** [comment]
Last time I check it was respected. You can easily confirm by specifying 
ztnas a protocol but not configuring TLS. When I try to start xrootd with 
this kind of configuration I get the following error

Config Authentication protocol(s) ztn require TLS; login now requires TLS.
Config failure: unable to honor TLS requirement; TLS not configured!
------ xroot protocol initialization failed.

So, without TLS and with ztn you cannot start the server.

Andy

**Comment by bbockelm** [comment]
Yes, I recalled that this is probably done right at the server level.  @simonmichal - does the client refuse to send the token if `needTLS` is set?

**Comment by xrootd-dev** [comment]
Since the client needs to connect and be prompted to send the token, it's 
impossible for the client to do so unless a TLS connection has been 
established.

Andy

**Comment by bbockelm** [comment]
@abh3 -

I'm thinking the other way around, I think.  If I have a malicious server (which refuses to do TLS because it doesn't have a valid certificate) asks the for the token, will the client cough it up?

**Comment by xrootd-dev** [comment]
Actually, the protocol object creator checks whether the associated 
connection is using TLS and if it is not and the object requires TLS, it 
refuses to create the object. This happens both on the server as well as 
client. So, for ztn in the absence of TLS it would be impossible to 
instantiate the protocol in the first place.

Andy

**Comment by bbockelm** [comment]
Makes sense, thanks!  That's precisely what I was looking for.
