### ISSUE TITLE
Explicitly override the hostname used by XRootD

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1855]
Right now, the hostname that will be used by an XRootD daemon is bootstrapped here:

https://github.com/xrootd/xrootd/blob/master/src/Xrd/XrdConfig.cc#L574-L579

Basically, it selects an IP address and does a reverse DNS resolution to determine the hostname.  This hostname can't be overridden as far as I can tell.

We've run into two cases where an override is necessary:

1. Where the forward DNS resolution (name -> IP address) configured as desired but it's essentially impossible to setup the reverse DNS.  This is because the university that owns the project (and the DNS zone for the project) is different than the university that owns the IPs.
2. When running inside Kubernetes, the visible device IP is distinct from the incoming IP address meaning neither forward nor reverse DNS lookups result in the correct value.  We need to explicitly set the hostname instead of having it autodetected.

**Comment by bockjoo** [comment]
+1
Currently, I use
hostnamectl set-hostname <desired hostname> ;
systemctl start xrootd@clustered
to cheat.

**Comment by bbockelm** [comment]
Indeed - unfortunately, that's not possible in unprivileged containers so even the "cheat" isn't available.

**Comment by abh3** [comment]
We will provide two mechanisms to do this: 1) If XRDIDENTITY envar is set, that will be the assumed identity, 2) if the -N CLI option is used to specify the identity, it will override the envar (if set). Mind you, one will need to be very careful as this can cause a lot of problems if it is incorrectly specified. You can, of course, say that one or the other is sufficient and you don't need both.

**Comment by bockjoo** [comment]
At the moment, we use
the systemd file /etc/systemd/system/xrootd-privileged@.service and add the EnvirionmentFile:
[Service]
EnvironmentFile=-/etc/sysconfig/xrootd
The desired hostname is provided in the file /etc/sysconfig/xrootd
We are happy with this.

**Comment by abh3** [comment]
Hmmm, does this mean you no longer need other workarounds? If so, could you send over the /etc/sysconfig/xrootd so that we can use it as an example in the documentation?

**Comment by bbockelm** [comment]
@abh3 - I believe Bockjoo is relying on a patch to set the identity that we've been carrying since December 2022.

At the time, your comment on this idea was:

> This is not the way I envisioned doing this and definitely not via an envar that tends to get forgotten buruied and creates enormous problems

I would love it if you implement what you propose above as no one likes out-of-tree patches.  One Less Thing, right?

**Comment by abh3** [comment]
I check it in. Use -N <netid> command line option or simply set XRDNET_IDENTITY to the value you want prior to starting up the server. It's in the devl branch but please do try it out and tell me if it works for you @bbockelm

**Comment by amadio** [comment]
This has been added to XRootD 5.7.1, marking the milestone accordingly (you can see by clicking on the commit hash where it has been merged).
