### ISSUE TITLE
Optionally ignore permissions when loading secrets from filesystem

### ISSUE THREAD

**Issue by jthiltges** [xrootd/xrootd#1858]
XRootD prudently refuses to load insecure secrets. E.g.
https://github.com/xrootd/xrootd/blob/1f80cbb0d1a5efc55b19215b72972e668616d6de/src/XrdSecztn/XrdSecProtocolztn.cc#L486-L488

But in containers, permission and ownership of files often does not follow the best practices for a standalone system, while still being (relatively) secure. Working around this requires additional plumbing: cronjobs and startup scripts to copy files and set permissions.

Would you consider including an option (envvar?) to allow clients and servers to ignore strict permissions checks?

**Comment by abh3** [comment]
The security team thinks this is a real bad idea. I tend to agree. I know security can be painful (I have to live it every day) but relaxing access rules generally leads to bad outcomes. So, the policy will not change.
