### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by noloader** [xrootd/xrootd#1861]
Hi Everyone,

I have a few documentation comments based on my experience. The docs at https://github.com/xrootd/xrootd/blob/master/README are good. There are a few minor gaps when building from Git sources.

* 2.0 Build dependencies: missing a dependency on `libuuid-devel`
* 2.2 Build parameters: missing a variable for tests
* 2.3 Build steps: missing the steps to run the tests

I think a step for the self tests is an important one. Folks need to get into the habit of testing things. They should not install the software if there's a problem with the build or test results.

And based on https://github.com/xrootd/xrootd/issues/858, building the self tests are an on-going problem.

-----

I am trying to run the equivalent of `./configure && make && make check`. I'm currently stuck at:

```bash
$ cmake ../ -DENABLE_PERL=FALSE -DENABLE_TESTS=TRUE
...
-- ----------------------------------------
-- Installation path: /usr/local
-- ...
-- Tests:             disabled
```

I could not get the self tests enabled with either `-DENABLE_TEST=TRUE` or `-DENABLE_TESTS=TRUE`.

I'm going start rummaging around in `CmakeFileList.txt` to see if I can spot a variable that controls the self tests.

**Comment by amadio** [comment]
In #858, you used `-DBUILD_TESTS=ON` instead of `-DENABLE_TESTS=ON`. Please make sure to use the right option. I linked there where the build options are listed.

**Comment by noloader** [comment]
Thanks @amadio.

Does xrootd have a mailing list? I have some questions but I don't know where to ask them. (It may be useful to add it to the README).

**Comment by amadio** [comment]
Yes, please see https://xrootd.slac.stanford.edu/contact.html on how to subscribe.

**Comment by amadio** [comment]
I believe the current [README.md](https://github.com/xrootd/xrootd#readme) and [INSTALL.md](https://github.com/xrootd/xrootd/blob/master/docs/INSTALL.md) address this, so I'm closing this ticket.
