### ISSUE TITLE
openssl3 gsi segfault

### ISSUE THREAD

**Issue by andrejfilipcic** [xrootd/xrootd#1877]
xrootd 5.5.1 gsi does not work well with openssl3 (centos9 stream)

segfaults here:
7 0x00007f71d1ee3f24 in BN_get_flags () from /lib64/libcrypto.so.3
#8 0x00007f71d1ee5291 in BN_copy () from /lib64/libcrypto.so.3
#9 0x00007f71d1fa9186 in ossl_ffc_validate_public_key_partial () from /lib64/libcrypto.so.3
#10 0x00007f71d1fa920e in ossl_ffc_validate_public_key () from /lib64/libcrypto.so.3
#11 0x00007f71d206c460 in dh_validate.lto_priv () from /lib64/libcrypto.so.3
#12 0x00007f71d1fa19e1 in try_provided_check () from /lib64/libcrypto.so.3
#13 0x00007f71d1fa1a71 in evp_pkey_public_check_combined () from /lib64/libcrypto.so.3
#14 0x00007f71d1f97683 in EVP_PKEY_derive_set_peer_ex () from /lib64/libcrypto.so.3
#15 0x00007f71d09ea459 in XrdCryptosslCipher::Finalize(bool, char*, int, char const*) () from /opt/eos/xrootd/lib64/libXrdCryptossl-5.so
#16 0x00007f71d0a2ddf3 in XrdSecProtocolgsi::ServerDoCert(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /opt/eos/xrootd/lib64/libXrdSecgsi-5.so

Same configuration works fine on rhel8.
(original information on https://eos-community.web.cern.ch/t/gsi-crashes-mgm-on-centos9/824/1)

Andrej

**Comment by amadio** [comment]
Dear @andrejfilipcic, could you please install the debug info packages for XRootD and try again? It would also help if you have a core dump from the crash or if you have any additional info on what caused the crash (which command was running) so we can try to reproduce this problem on our end. Thank you!
