### ISSUE TITLE
XrdCl: Mark file API with attribute warn_unused_result

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#188]
I just got bit by code that looks somewhat like this:

    SyncHostResponse handler;
    file->Open(m_filename, m_flags, m_perms, &handler);
    handler.WaitForResponse();

(here, file is a XrdCl::File*; actual code is slightly more complex, but the above suffices).  For a long time, this code worked fine - the Open was the first call to XrdCl, so it never failed.  However, an unrelated commit added a prior call to XrdCl::FileSystem::Query.  If that ended in a fatal error, the call to file->Open failed immediately -- and the WaitForResponse() hangs indefinitely as there is no callback.

We should mark the relevant XrdCl::File and XrdCl::FileSystem asynchronous calls with the attribute warn_unused_result where available; this would have resulted in a compiler warning, which would have allowed me to avoid a deadlock.

**Comment by bbockelm** [comment]
Kind reminder on this item.  Any interest in it?

**Comment by ljanyst** [comment]
Yes, it will be done. Patience please. :)
