### ISSUE TITLE
xrdfs rm not printing error codes

### ISSUE THREAD

**Issue by costing** [xrootd/xrootd#1885]
Hi,

There is something funny in the xrootd client command line tools, there is no error message printed if the only file given as an argument cannot be removed. See the first command below, while the second one (with two arguments) prints both errors. And neither returns a non-zero exit code.

It might be related to the changes introduced to allow multiple arguments to the `rm` command, some revisiting might be needed.

Cheers,

.costin

```
[grigoras@lxplus734 ~]$ xrdfs lxalird.gsi.de:1094 rm /14/51110/732b358f-98b0-11ed-9a02-6c02e09897e9
[grigoras@lxplus734 ~]$ echo $?
0

[grigoras@lxplus734 ~]$ xrdfs lxalird.gsi.de:1094 rm /14/51110/732b358f-98b0-11ed-9a02-6c02e09897e9 /14/51110/732b358f-98b0-11ed-9a02-6c02e09897e1
rm /14/51110/732b358f-98b0-11ed-9a02-6c02e09897e1 : [ERROR] Error response: permission denied
rm /14/51110/732b358f-98b0-11ed-9a02-6c02e09897e9 : [ERROR] Error response: permission denied
[grigoras@lxplus734 ~]$ echo $?
0
```

**Comment by simonmichal** [comment]
@costing : thanks for reporting this problem, it should be fix now in: 012c5fe9318ba3ce302be30cb2134dbd3469a5d9 and c1cf1f658daa4ba27f87794da6f6850c6cfa88b9

**Comment by costing** [comment]
Thank you @simonmichal ! Looking forward for 5.5.2 :)

**Comment by costing** [comment]
Hi,

This bug  seems to have reappeared at least from 5.6.0 and beyond. Even for single files, regardless of the success or failure of the operation, the exit code is always `0`:

```
$ v5.6.0-6/bin/xrdfs eosalice.cern.ch rm '/33/33333/33333'
rm /33/33333/33333 : [ERROR] Error response: permission denied
$ echo $?
0

$ v5.6.0-6/bin/xrdfs eosalice.cern.ch rm '/33/33333/33333' '/44/44444/444444'
rm /33/33333/33333 : [ERROR] Error response: permission denied
rm /44/44444/444444 : [ERROR] Error response: permission denied
$ echo $?
0
```

and the same in 5.6.2:
```
$ xrdcp -version
v5.6.2
$ xrdfs eosalice.cern.ch rm '/33/33333/33333'
rm /33/33333/33333 : [ERROR] Error response: permission denied
$ echo $?
0
```

Could you please re-apply the fix?

Cheers,

.costin
