### ISSUE TITLE
Issue "Accept-Ranges: bytes" in HTTP response

### ISSUE THREAD

**Issue by simpsonst** [xrootd/xrootd#1889]
Hi!
We're observing different results using a WebDAV client library against our XRootD instance versus a dCache, whereby it's using a `HEAD` to test for `Accept-Ranges: bytes`, and selecting subsequent functionality (such as `GET`-with-range) based on it.  Examination of the headers show it is present in the dCache response but not in XRootD's.
Our instance is only 5.4.2, so not the latest, but I think the relevant code is in [`XrdHttpProtocol::StartSimpleResp`](https://github.com/xrootd/xrootd/blob/c421d3d35041772c86576ee94200360f128f375d/src/XrdHttp/XrdHttpProtocol.cc#L1504-L1533), and it doesn't mention `Accept-Ranges`.  Could the field be included in appropriate HTTP responses?  Not sure if it could be applied unconditionally.
Thanks!

**Comment by ccaffy** [comment]
Done by @bbockelm, merged after this PR was reviewed: https://github.com/xrootd/xrootd/pull/1920/
