### ISSUE TITLE
Have cconfig print config to stdout, not stderr

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1894]
Currently, the `cconfig` tool prints the configuration to `stderr`.

This is a strange behavior as it becomes difficult to work with the traditional suite of command line tools as debug messages are interspersed with the actual configuration directives.

An example:

```
# cconfig -c /etc/xrootd/xrootd-origin.cfg 
all.manager redirector.example.com+ 1213
xrd.port 1094
all.role server
continue /etc/xrootd/config.d
Config continuing with file /etc/xrootd/config.d/10-common-site-local.cfg ...
Config continuing with file /etc/xrootd/config.d/10-docker-env-var.cfg ...
Config continuing with file /etc/xrootd/config.d/10-origin-docker-env-var.cfg ...
Config continuing with file /etc/xrootd/config.d/10-origin-site-local.cfg ...
Config continuing with file /etc/xrootd/config.d/10-osg-xrdvoms.cfg ...
Config continuing with file /etc/xrootd/config.d/40-stash-cache-plugin.cfg ...
xrd.tcpmonlib ++ /usr/lib64/libXrdTCPStats.so 
...
```

Now yes, I can redirect stderr to stdout and then start grepping out known debug messages ("Config continuing with ...").  In terms of user interface, it's just strange/unexpected behavior for a Unix command line tool to use stderr for the output.

**Comment by xrootd-dev** [comment]
Well, the issue as you saw is the other messages that come out 
"continui8ng etc) that are just as cumbersome. I suppose we could add a 
stdout option that only output the cobnfig while the "extra" messages 
continue to be written to stderr. However, the default behaviour should 
remain so that you get a complete picture wehere all the pieces come from.

Andy

**Comment by abh3** [comment]
OK, I have added a -o option to cconfig and it will write out the single config file to the output file without any commentary. So, you can use that file as a real config file. You can also wrap the command with a script that display the result via stdout though I think capturing the file is what you really wanted. This change will appear in R6.

**Comment by amadio** [comment]
@abh3 Since this is just a command line tool to which we are adding a new command-line switch, I would be fine with adding this to 5.7.1. Please let me know what you think. I will keep the commits in `devel` for now.

**Comment by abh3** [comment]
I'm fine with it going into 5.7.1.
