### ISSUE TITLE
WebDAV method DELETE fails for non-empty directory, 500 response returned

### ISSUE THREAD

**Issue by ptrlv** [xrootd/xrootd#1896]
(this issue described by @airnandez)

WebDAV method DELETE fails for non-empty directory, using Server: XrootD/v5.5.0
Message returned:
Unable to remove /cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/; directory not empty

The response status code 500 Internal Server Error is inconvenient since that is one of the return codes that are typically retried.

According to the [RFC](http://www.webdav.org/specs/rfc4918.html#delete-collections):
The DELETE method on a collection MUST act as if a "Depth: infinity" header was used on it.
The server may return a 4xx status response, rather than a 207, if the request failed completely.
DELETE works correctly when the path is a file.

```
$ curl -i -L -v \
--
--capath /etc/grid-security/certificates \
--cacert ${X509_USER_PROXY} \
--cert ${X509_USER_PROXY}  \
--output /dev/stdout \
-X DELETE \
https://xgate.hec.lancs.ac.uk:1094/cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/
 
> DELETE /cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: xgate.hec.lancs.ac.uk:1094
> Accept: */*
>
< HTTP/1.1 302 Redirect
HTTP/1.1 302 Redirect
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 0
Content-Length: 0
< Location: https://stor015.hec.lancs.ac.uk:1095/cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/
Location: https://stor015.hec.lancs.ac.uk:1095/cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/
 
> DELETE /cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: stor015.hec.lancs.ac.uk:1095
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
< Connection: Keep-Alive
Connection: Keep-Alive
< Server: XrootD/v5.5.0
Server: XrootD/v5.5.0
< Content-Length: 88
Content-Length: 88
 
<
{ [data not shown]
Unable to remove /cephfs/grid/lsst/user/fabioh/tests/dir-vtz3iejc/; directory not empty

```

**Comment by abh3** [comment]
Correct/ This is a known problem and has been with us day 1. In general, the thought of allowing delete on non-empty directories presents a serious DOS exposure and we have not allowed it (i.e. we implement the Unix behavior here). I agree that 500 might not be the best return code. Could you suggest what you think should return code should be?

**Comment by ptrlv** [comment]
Referring to the WEBDAV RFC I think 423 (Locked) would be ok. It's nice of xrootd to protect the user from mistakes (or DOS) however there is probably a valid usecase to allow users to delete 'collections'.

**Comment by airnandez** [comment]
If I may suggest, from the client point of view, [501 Not Implemented](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501) (or even [405 Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)) would be informative enough for the client to determine how to proceed.

**Comment by ptrlv** [comment]
405 sounds good and would raise fewer questions than a 50x.

**Comment by abh3** [comment]
I agree that following the Unix convention (i.e. delete allowed only for empty directories) contravenes the WebDav RFC. On the other hand we actually never got more than 2 (now) raised eyebrows over the last 5 years. I suppose we could add a config option to allow such deletion requests. Be aware these kinds of requests may run for a very long time when the collection is large.
