### ISSUE TITLE
xrdcopy: support reading from STDIN

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#190]
We have a use case where we would like to pipe (compressed/encrypted) data to xrdcopy without going via a local temp file first. While "xrdcopy" can pipe out to STDOUT, it apparently does not support reading from STDIN - could this be changed? (of course, things such as transfer checksumming or preallocating on the receiver won't work).

Tests done:
* cat /etc/group | xrdcopy -d 2  - root://eospps//eos/pps/users/iven/test-stdin

 => gives an empty file on the destination, no error.
*  cat /etc/group | xrdcopy -d 2  /dev/stdin root://eospps//eos/pps/users/iven/test-dev-stdin

xrdcopy: Operation not supported processing /dev/stdin
* cat /etc/group | xrdcp -d 2  - root://eospps//eos/pps/users/iven/test-stdin-xrdcp

xrdcp: Using stdin as a source is disallowed.
* cat /etc/group | xrdcp -d 2  /dev/stdin root://eospps//eos/pps/users/iven/test-dev-stdin-xrdcp

xrdcp: Operation not supported processing /dev/stdin

**Comment by ljanyst** [comment]
This works fine. Use newer version.

```
]==> cat /etc/group | xrdcp - root://localhost//tmp/test
[1.149kB/0B][100%][==================================================][0B/s]
]==> md5sum /tmp/test /etc/group
5abb44f8dedb48aed937e44f62dda810  /tmp/test
5abb44f8dedb48aed937e44f62dda810  /etc/group
```
