### ISSUE TITLE
WebDav: Invalid server checksum answer (5.5.2)

### ISSUE THREAD

**Issue by kreczko** [xrootd/xrootd#1901]
Dear all,

I just tried version 5.5.2 today, which caused the CMS WebDav tests to fail.

Their test command is
```
gfal-sum -D "HTTP PLUGIN:RETRIEVE_BEARER_TOKEN=false" -t 90 davs://xrootd.phy.bris.ac.uk:1094/xrootd/cms/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root ADLER32
```
which returns 
```
davs://xrootd.phy.bris.ac.uk:1094/xrootd/cms/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root 96fb2295
```
for version 5.5.0

and
```
gfal-sum error: 5 (Input/output error) - Invalid server checksum answer
```
for version 5.5.2

### our setup
We use a script to get the checksum: ` xrootd.chksum max 100 adler32 /etc/xrootd/xrdsum.sh`, which content:
```bash
#!/usr/bin/env bash

RESULT=$(xrdsum --verbose --debug -l /var/log/xrootd/clustered/checksum.log get --store-result --read-size 128 "$1")
ECODE=$?

# XRootD expects return on stdout - checksum followed by a new line
printf "%s\n" "$RESULT"
exit "$ECODE"
```

`RESULT` is just the checksum, `96fb2295` in this case.
The script is run successfully in both 5.5.0 and 5.5.2, but the response the client gets is different.

EDIT:
Debug info on gfal-sum show the checksum as unknown
```
DEBUG    Davix: < HTTP/1.1 200 OK
DEBUG    Davix: < Connection: Keep-Alive
DEBUG    Davix: < Server: XrootD/v5.5.2
DEBUG    Davix: < Content-Length: 1293057986
DEBUG    Davix: < Digest: unknown=96fb2295
DEBUG    Davix: <
DEBUG    Davix: End of headers.
```

Relates to #1707

**Comment by ccaffy** [comment]
Hi Luke,

Thanks a lot for reporting this.
Can you please tell me what is the request sent by gfal to ask for the checksum ? (The content of the `Want-Digest:` header)

Thanks again,

Cheers,
Cedric

**Comment by kreczko** [comment]
Hi Cedric,

In both cases, the want digest is:

```
 Want-Digest: ADLER32
```

Cheers,
Luke

**Comment by ccaffy** [comment]
Thanks a lot, out of curiosity, can you try it with lower case adler32 ?

**Comment by kreczko** [comment]
Lower case works for 5.5.0 but not for 5.5.2 - same error as with upper case:
```
DEBUG    Davix: < Digest: unknown=96fb229
...
gfal-sum error: 5 (Input/output error) - [gfal2_checksum][davix2gliberr] Invalid server checksum answer
```

**Comment by ccaffy** [comment]
Interesting... Now last test, if you put : `xrootd.chksum adler32` in your server config ?

**Comment by kreczko** [comment]
I do have that:
```bash
xrdconfig display /opt/xrootd-se/etc/xrootd/xrootd-clustered.cfg| grep adler
xrootd.chksum max 100 adler32 /etc/xrootd/xrdsum.sh
```

how would you like me to modify it?

**Comment by ccaffy** [comment]
Ah, yes without all the other parameters:
Just `xrootd.chksum adler32`

**Comment by kreczko** [comment]
That will break the server - but let;s try:

```
gfal-sum   -D "HTTP PLUGIN:RETRIEVE_BEARER_TOKEN=false" -t 90 davs://xrootd.phy.bris.ac.uk:1094/xrootd/cms/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root adler32
gfal-sum error: 13 (Permission denied) - Authentication error, reached maximum number of attempts
```
--> for both versions

I also had to enable
```
ofs.ckslib * /usr/lib64/libXrdHdfs.so
```

while the checksum file exists (`/hdfs/cksums/xrootd/cms/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/CE860B10-5D76-E711-BCA8-FA163EAA761A.root`) and contains the correct entries, something goes wrong.

**Comment by ccaffy** [comment]
Xrootd supports Adler32 natively so you normally don't need to specify anything else than adler32 for the algorithm

**Comment by kreczko** [comment]
> Xrootd supports Adler32 natively so you normally don't need to specify anything else than adler32 for the algorithm

Sure, but it has no idea how to talk to HDFS, does it?

> I'll Keep you updated here. 

Thanks!

> In the meanwhile, maybe consider rolling back to the previous version

Only tested 5.5.2 for a brief moment ;). It takes 30s for me to change versions, so as soon as I discovered the issue, I changed back.

**Comment by ccaffy** [comment]
This issue has been solved by the PR https://github.com/xrootd/xrootd/pull/1904

Closing!

Thanks again for your input!
