### ISSUE TITLE
XRootD day-light savings handling wrong again

### ISSUE THREAD

**Issue by stlammel** [xrootd/xrootd#1955]
Dear xrootd team,
   a few years ago we opened an issue reporting that out services in the US have authentication failures for a little over an hour after the US switches to day-light savings time. We had an exchange and traced this down to the daemons calculating the timezone offset to UTC at start time and then using it throughout their execution. I thought the issue was fixed and all recent versions would include the fix.
   But aparently not: All CMS xrootd services in the US failed aur tests with authentication error this morning Sunday, March 12th at 2 am UTC for a bit over an hour. This smells like the day-light savings bug. Sites run xrootd versions between 5.3.1 and 5.5.3, i.e. rather recent. The error is XRootDStatus.code=204 "[FATAL] Auth failed: No protocols left to try".
   Could you please take a look if the old fix got lost? or a new issue was introduced?
   Thanks,
 - Stephan

**Comment by stlammel** [comment]
One of my colleagues found the old bug report,
https://github.com/xrootd/xrootd/issues/985

**Comment by amadio** [comment]
Closing, fixed by #1958.
