### ISSUE TITLE
XRootD HTTP erroneously returns old `Digest` header

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1956]
The variable holding the `Digest` response header, `m_digest_header`, is not reset between requests.  This causes the digest header to be sent when the object is reused by a later request.

Note if the subsequent request sets the `Want-Digest` header, the stale header is not returned.  Hence, it's only set when the client isn't expecting it.

**Comment by smithdh** [comment]
hi @bbockelm . Shall I open a PR for this, or would you like to do that?

**Comment by bbockelm** [comment]
@smithdh - this fix got incorporated into the PR #1957 (see https://github.com/xrootd/xrootd/pull/1957/files#diff-56f7321e31ac4f62330e63a316d3c25360b99c453e09956a1730052d09c367ebR3020).  Let's see if that one gets merged in a timely manner; otherwise, I'll send in the one-liner.

**Comment by smithdh** [comment]
ah, that's great, thanks.

**Comment by xrootd-dev** [comment]
It should be available in 5.5.4 coming out shortly after the workshop 
(well that's the current plan). The fix is tied up is sveral other HTTP 
issues that we are trying to resolve.

**Comment by amadio** [comment]
@bbockelm Could you please split the fix for this issue into a separate pull request? I think that since #1957 is adding a new feature, and we'd like to apply the fix for this to XRootD 5.5.4, it's better to have just the fix for this as its own commit. Thanks!
