### ISSUE TITLE
xrootd memory consumption scales unboundly with RLIMIT_NOFILE 

### ISSUE THREAD

**Issue by rcarpa** [xrootd/xrootd#1962]
To reproduce the issue it's enough to set a very high RLIMIT_NOFILE. For example 
```
ulimit -n
1073741816
```
This value, for example, results in xrootd consuming 10+ Gb of ram. 

xrootd uses 
https://github.com/xrootd/xrootd/blob/aaf638df423f22cee3a09aba76febcc7152ef34b/src/Xrd/XrdConfig.cc#L1191
this value to set the actual poller size.
https://github.com/xrootd/xrootd/blob/aaf638df423f22cee3a09aba76febcc7152ef34b/src/Xrd/XrdPollE.icc#L44

The ulimit value shouldn't be used blindly without any upper bound and/or configuration parameter allowing the user to explicitly set the desired upper bound.

**Comment by esindril** [comment]
:+1:  We were also hit by this since in Alma 9 the limits are through the roof. A more conservative approach in this case can save some debugging time for the ops.

**Comment by abh3** [comment]
Yes,I agree that this is not desirable. However, most people set the upper limit to be something reasonable (e.g. 16K or 32K a few even 64K). When set to something reasonable, this problem does not occur. We will put this in the queue to enforce a reasonable limit unless told otherwise.

**Comment by xrootd-dev** [comment]
Indeed it would. Now that you suggested it you can generate a pull request 
and become a documented recognized source contributor? Do you want to do 
that or shall we proceed with a misattributed change?

**Comment by rcarpa** [comment]
Done: https://github.com/xrootd/xrootd/pull/1966

**Comment by xrootd-dev** [comment]
Thanks! You are now an official XRootD contributor :-)

**Comment by maxnoe** [comment]
This fix should be included in any recent release, right? 

If yes, there might be a regression or a second similar issue, since I ran into this today with xrootd 5.6.7:

> rucio-storage-3-1  | Config maximum number of connections restricted to 178956970

Which resulted in the OOM killer killing xrootd. After setting `ulimit -n 1024`, we get:

> rucio-storage-3-1  | Config maximum number of connections restricted to 1024

and no OOM killer action.

**Comment by amadio** [comment]
You may need to set `xrd.maxfd` in your configuration file. Please see the documentation about this option at https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc152596839

**Comment by maxnoe** [comment]
Just note, the link above is broken, this one works: https://xrootd.web.cern.ch/doc/dev56/xrd_config.htm#_Toc152596839

**Comment by amadio** [comment]
Yes, it's a consequence of SLAC dropping AFS and us moving things partly to EOS (https://xrootd.web.cern.ch) and partly to GitHub (https://xrootd.github.io). We are aware and will fix this soon.
