### ISSUE TITLE
HTTP-TPC transfer monitoring - stripe source and destination perf marker

### ISSUE THREAD

**Issue by vokac** [xrootd/xrootd#1963]
To improve HTTP-TPC transfer monitoring and for better transfer issue diagnosis WLCG BDT group [proposed HTTP-TPC update](https://twiki.cern.ch/twiki/bin/view/LCG/HttpTpcUpdates#Update4) which adds new `Perf Marker` entries that provide real transfer connection source (`Stripe Source`) and destination (`Stripe Source`) addresses. The address format is same as defined for [`RemoteConnections`](https://twiki.cern.ch/twiki/bin/view/LCG/HttpTpcUpdates#Performance_markers) and it is composed of transport protocol, address and port separated by `:`, e.g. `tcp:192.0.2.100:1234` or `tcp:[2001:db8::100]:1234`.

[Example of whole performance marker](https://twiki.cern.ch/twiki/bin/view/LCG/HttpTpcUpdates#Update4) with proposed extension:
```
Perf Marker\n
Timestamp: 1537788010\n
Stripe Index: 0\n
Stripe Bytes Transferred: 238745\n
Total Stripe Count: 1\n
RemoteConnections: tcp:147.231.25.166:21234,tcp:[2001:718:401:6017:2::28]:24081\n
Stripe Source: tcp:[2001:718:401:6017:2::28]:24081\n
Stripe Destination: tcp:[2001:1458:301:105::100:5]:8443\n
End\n
```

**Comment by bbockelm** [comment]
Hi @vokac!
- Why is there the assumption the transfer is done in stripes?  This isn’t true for XRootD.
- Why is there the assumption anything stripe-like has a single source?

Not to bikeshed too much but simply “sources” and “destinations” may suffice, no?

**Comment by vokac** [comment]
Nobody complained when this was [discussed](https://indico.cern.ch/event/1243007/#4-aob?note=225797) (or in the related email thread) and my understanding of "stripe" from quick look into [GFD.20](https://ogf.org/documents/GFD.20.pdf) is that connections running in parallel have different `Stripe Index`.

**Comment by bbockelm** [comment]
> Nobody complained when this was [discussed](https://indico.cern.ch/event/1243007/#4-aob?note=225797) (or in the related email thread)

Yes, we definitely could have caught this sooner ... but yet to correct it before it's coded and released!

> my understanding of "stripe" from quick look into [GFD.20](https://ogf.org/documents/GFD.20.pdf)

Right -- GridFTP has a very specific transfer model based on the concept stripes.  My concern is HTTP doesn't so we would be better served by simply dropping the word.

**Comment by vokac** [comment]
Updated proposal came during today's [WLCG BDT meeting](https://indico.cern.ch/event/1288011/?note=238154#4-aob) with suggestion to deprecate old "Stripe" markers.

**Comment by abh3** [comment]
I think the latest document makes this discussion moot so I am closing this ticket.
