### ISSUE TITLE
XRootD does not compile with Clang 15.x

### ISSUE THREAD

**Issue by amadio** [xrootd/xrootd#1975]
There are several errors due to redefinition of `extern inline` functions in XrdPosixPreload:
```
xrootd/src/XrdPosix/XrdPosixPreload32.cc:375:9: 
  error: redefinition of a 'extern inline' function 'pread' is not supported in C++
ssize_t pread(int fildes, void *buf, size_t nbyte, off_t offset)
        ^
/usr/include/bits/unistd.h:72:1: note: previous definition is here
pread (int __fd, void *__buf, size_t __nbytes, __off_t __offset)
^
```
We should try to fix this, as eventually XRootD will stop compiling on macOS if we don't.

**Comment by xrootd-dev** [comment]
So, when did the support for this end or is it just a Clang thing?

**Comment by amadio** [comment]
I looked into this today. The problem is that my distribution has `#define _FORTIFY_SOURCE 2` by default and Clang doesn't really like that (with GCC it works fine). So I guess the course of action is to forcibly disable it for Clang. I will open a pull request with a patch.
