### ISSUE TITLE
Tape WebDAV support misses from verbs

### ISSUE THREAD

**Issue by PerilousApricot** [xrootd/xrootd#1983]
XRootD supports the additional verbs needed for tape support (i.e. to bring files online, etc).. but only with the root:// protocol and not webdav. This is needed so xrootd-based tape sites can communicate with other sites in CMS the majority of whom only participate in transfers via WebDAV

**Comment by abh3** [comment]
This has been noted and we are pursuing several options her but in the context of the WLCG Tape Rest API. We will not be developing anything different from that.

**Comment by ccaffy** [comment]
Closing this ticket, a discussion has been created around this topic: https://github.com/xrootd/xrootd/discussions/2249
