### ISSUE TITLE
Implement SciTags support in HTTP-TPC

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1984]
There are a few proposed headers (see https://twiki.cern.ch/twiki/bin/view/LCG/HttpTpcUpdates; https://its.cern.ch/jira/projects/DMC/issues/DMC-1344) which allow experiments to self-assert the SciTags ID associated with a transfer.

We should look for the headers and periodically send out the UDP "fireflies".  I'm not familiar with the existing implementation for xrootd-tpc but I imagine this can largely reuse existing code.

@ccaffy - this might be a good issue for learning more of the HTTP-TPC code base.

**Comment by abh3** [comment]
Yes, I want re-iterate that the whole firefly/scitags infrastructure has already been implemented  in XRootD and there should be no duplication of code as far as this is concerned. It's simply a matter of relaying the information to the xrootd side.
