### ISSUE TITLE
Gstream TPC negative file size

### ISSUE THREAD

**Issue by biozit** [xrootd/xrootd#1989]
Hi All,

  Is there a reason the file size is negative ("size": -1205088130) on the GStream TPC?

{
  "_index": "monit_prod_cms-xrootd-cache_raw_tpc-2023-03-17",
  "_id": "4434bb28-f0b8-4e4c-8df1-e7f4c6520669",
  "_version": 1,
  "_score": null,
  "_source": {
    "data": {
      "tpc_protocol": "http",
      "client": "anon.0:37@fts-cms-008.cern.ch",
      "xeq": {
        "begin_transfer": "2023-03-17T16:09:20.875459Z",
        "end_transfer": "2023-03-17T16:10:53.110557Z",
        "ip_version": 6,
        "return_code": 0,
        "used_streams": 1,
        "flow_direction": "push"
      },
      "source": "http://gftp-8.t2.ucsd.edu:1095//store/data/Run2022E/EGamma/AOD/10Dec2022-v2/80005/b7efd9b7-34ac-4e89-bc8a-0498c463d3d6.root",
      "destination": "https://lcgsedr08.jinr.ru:2880/pnfs/jinr.ru/data/cms/store/data/Run2022E/EGamma/AOD/10Dec2022-v2/80005/b7efd9b7-34ac-4e89-bc8a-0498c463d3d6.root",
      "size": -1205088130,
      "metadata": {}
    },
    "metadata": {
      "hostname": "monit-amqsource-ee2e71080d.cern.ch",
      "partition": "4",
      "type_prefix": "raw",
      "kafka_timestamp": 1679069491844,
      "host": "xrootd-mon-collector-bb4cb9cb9-2t7lc",
      "topic": "cms-xrootd-cache_raw",
      "producer": "cms-xrootd-cache",
      "_id": "4434bb28-f0b8-4e4c-8df1-e7f4c6520669",
      "type": "tpc",
      "timestamp": 1679069487978
    }
  },
  "fields": {
    "data.xeq.begin_transfer": [
      "2023-03-17T16:09:20.875Z"
    ],
    "data.xeq.end_transfer": [
      "2023-03-17T16:10:53.110Z"
    ],
    "metadata.kafka_timestamp": [
      "2023-03-17T16:11:31.844Z"
    ],
    "metadata.timestamp": [
      "2023-03-17T16:11:27.978Z"
    ]
  },
  "sort": [
    1679069487978,
    -1205088130
  ]
}

**Comment by xrootd-dev** [comment]
None that I can think of. Is it always the same negative value? Anyway, I 
will look at the code.

**Comment by biozit** [comment]
We have different negative numbers on the file size.
