### ISSUE TITLE
xrdcopy is CPU bound and limiting on 10Gbit networks

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#20]
Doing some testing I have seen that the copy command is CPU bound and limits file downloads (serverside cached file 4Gb) to ~ 770 MB/s

The single stream performance is ~ 350 MB/s to reach 770 MB/s I need to use 15 parallel sockets and export XRD_CPPARALLELCHUNKS=10

It is mainly system time.

model name	: Intel(R) Xeon(R) CPU           L5520  @ 2.27GHz
stepping	: 5
cpu MHz		: 1600.000
cache size	: 8192 KB

The poller implementation has marginal effect (<2%) on the performance.

I can saturate the 10GB network by running two copy commands.

PS: the default 'xrdcp' command has weird performance ranging from 40-500 MB/s with regular hick-ups ...

**Comment by simonmichal** [comment]
Hi guys,

I run some tests on two machines (32 CPUs, 2.6 GHz) in wigner linked with 10Gbit. Here's a longish summary:


* transfer a 20G file with empty cache on the server side to /dev/null:

server:
   [root@p05799459s78866 ~]# free -g
                total       used       free     shared    buffers     cached
   Mem:            62          1         61          0          0          0
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

client:
   [xrootd-test@p05799459m77145 XrdCl]$ time strace -c ./xrdcp -f root://p05799459s78866//tmp/data01/20G_big_file /dev/null
   [19.53GB/19.53GB][100%][==================================================][162.6MB/s]  
   % time     seconds  usecs/call     calls    errors syscall
   ------ ----------- ----------- --------- --------- ----------------
    99.82    8.599052        2308      3725         2 futex
     0.12    0.009998        1111         9           socket
     0.03    0.002859        2859         1           readlink
     0.01    0.001123          10       107        87 open
     0.01    0.000760          45        17           recvmsg
     0.00    0.000235           0      1257           epoll_ctl
     0.00    0.000214          24         9           brk
     0.00    0.000207          52         4         1 connect
     0.00    0.000155          13        12           munmap
     0.00    0.000036           0       284           write
     0.00    0.000032           0      1250           pwrite
     0.00    0.000000           0        20           read
     0.00    0.000000           0        41           close
     0.00    0.000000           0        16        14 stat
     0.00    0.000000           0        20           fstat
     0.00    0.000000           0         3           poll
     0.00    0.000000           0         1           lseek
     0.00    0.000000           0        55           mmap
     0.00    0.000000           0        27           mprotect
     0.00    0.000000           0         2           rt_sigaction
     0.00    0.000000           0         1           rt_sigprocmask
     0.00    0.000000           0         1         1 access
     0.00    0.000000           0         8           sendto
     0.00    0.000000           0         4           bind
     0.00    0.000000           0         4           getsockname
     0.00    0.000000           0         8           clone
     0.00    0.000000           0         1           execve
     0.00    0.000000           0         2           uname
     0.00    0.000000           0         5           fcntl
     0.00    0.000000           0         1           getcwd
     0.00    0.000000           0         1           getrlimit
     0.00    0.000000           0         2           getuid
     0.00    0.000000           0         1           arch_prctl
     0.00    0.000000           0         1           set_tid_address
     0.00    0.000000           0         4           tgkill
     0.00    0.000000           0         1           set_robust_list
     0.00    0.000000           0         4           epoll_create1
     0.00    0.000000           0         4           pipe2
   ------ ----------- ----------- --------- --------- ----------------
   100.00    8.614671                  6913       105 total

   real	2m3.596s
   user	0m0.416s
   sys	0m8.814s

The limiting factor is the server side read speed (100% reproducible).


* transfer a 20G file that is already cached on the server side to /dev/null:

server:
   [root@p05799459s78866 ~]# free -g
                total       used       free     shared    buffers     cached
   Mem:            62         20         42          0          0         19
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

client:
   [xrootd-test@p05799459m77145 XrdCl]$ time strace -c ./xrdcp -f root://p05799459s78866//tmp/data01/20G_big_file /dev/null
   [19.53GB/19.53GB][100%][==================================================][1.028GB/s]  
   % time     seconds  usecs/call     calls    errors syscall
   ------ ----------- ----------- --------- --------- ----------------
    99.88    7.983796        3686      2166         8 futex
     0.09    0.006999         778         9           socket
     0.01    0.001003         111         9           brk
     0.01    0.000945          79        12           munmap
     0.01    0.000506         506         1           readlink
     0.00    0.000121           0      1257           epoll_ctl
     0.00    0.000053           0      1250           pwrite
     0.00    0.000012           0       562           write
     0.00    0.000009           0        41           close
     0.00    0.000008           1         8           sendto
     0.00    0.000000           0        20           read
     0.00    0.000000           0       107        87 open
     0.00    0.000000           0        16        14 stat
     0.00    0.000000           0        20           fstat
     0.00    0.000000           0         3           poll
     0.00    0.000000           0         1           lseek
     0.00    0.000000           0        55           mmap
     0.00    0.000000           0        27           mprotect
     0.00    0.000000           0         2           rt_sigaction
     0.00    0.000000           0         1           rt_sigprocmask
     0.00    0.000000           0         1         1 access
     0.00    0.000000           0         4         1 connect
     0.00    0.000000           0        17           recvmsg
     0.00    0.000000           0         4           bind
     0.00    0.000000           0         4           getsockname
     0.00    0.000000           0         8           clone
     0.00    0.000000           0         1           execve
     0.00    0.000000           0         2           uname
     0.00    0.000000           0         5           fcntl
     0.00    0.000000           0         1           getcwd
     0.00    0.000000           0         1           getrlimit
     0.00    0.000000           0         2           getuid
     0.00    0.000000           0         1           arch_prctl
     0.00    0.000000           0         1           set_tid_address
     0.00    0.000000           0         4           tgkill
     0.00    0.000000           0         1           set_robust_list
     0.00    0.000000           0         4           epoll_create1
     0.00    0.000000           0         4           pipe2
   ------ ----------- ----------- --------- --------- ----------------
   100.00    7.993452                  5632       111 total

   real	0m18.797s
   user	0m0.314s
   sys	0m8.145s

It is pretty close to filling up the pipe. There is one busy xrootd thread that takes about 40-45% CPU (100% reproducible).


* transfer a 20G file that is already cached on the server side to disk (with empty cache on the server side):

server:
   [root@p05799459s78866 ~]# free -g
                total       used       free     shared    buffers     cached
   Mem:            62         20         42          0          0         19
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

client:
   [xrootd-test@p05799459m77145 XrdCl]$ free -g
                total       used       free     shared    buffers     cached
   Mem:            62          1         61          0          0          0
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

   [xrootd-test@p05799459m77145 XrdCl]$ time strace -c ./xrdcp -f root://p05799459s78866//tmp/data01/20G_big_file /data07/tmp/
   [19.53GB/19.53GB][100%][==================================================][1.085GB/s]  
   % time     seconds  usecs/call     calls    errors syscall
   ------ ----------- ----------- --------- --------- ----------------
    76.55   10.780198        8624      1250           pwrite
    23.45    3.301757        1280      2579         2 futex
     0.00    0.000370          31        12           munmap
     0.00    0.000095           0      1253           epoll_ctl
     0.00    0.000022          22         1           readlink
     0.00    0.000010           0       107        87 open
     0.00    0.000000           0        20           read
     0.00    0.000000           0       277           write
     0.00    0.000000           0        32           close
     0.00    0.000000           0        16        14 stat
     0.00    0.000000           0        19           fstat
     0.00    0.000000           0         3           poll
     0.00    0.000000           0         1           lseek
     0.00    0.000000           0        51           mmap
     0.00    0.000000           0        24           mprotect
     0.00    0.000000           0         8           brk
     0.00    0.000000           0         2           rt_sigaction
     0.00    0.000000           0         1           rt_sigprocmask
     0.00    0.000000           0         1         1 access
     0.00    0.000000           0         9           socket
     0.00    0.000000           0         4         1 connect
     0.00    0.000000           0         8           sendto
     0.00    0.000000           0        17           recvmsg
     0.00    0.000000           0         4           bind
     0.00    0.000000           0         4           getsockname
     0.00    0.000000           0         5           clone
     0.00    0.000000           0         1           execve
     0.00    0.000000           0         2           uname
     0.00    0.000000           0         5           fcntl
     0.00    0.000000           0         1           getcwd
     0.00    0.000000           0         1           getrlimit
     0.00    0.000000           0         2           getuid
     0.00    0.000000           0         1           arch_prctl
     0.00    0.000000           0         1           set_tid_address
     0.00    0.000000           0         4           tgkill
     0.00    0.000000           0         1           set_robust_list
     0.00    0.000000           0         1           epoll_create1
     0.00    0.000000           0         1           pipe2
   ------ ----------- ----------- --------- --------- ----------------
   100.00   14.082452                  5729       105 total

   real	0m18.231s
   user	0m0.286s
   sys	0m19.176s

Again, it is pretty close to filling up the pipe. Now in top I can see 2 xrootd threads that are quite busy, respectively 40-45% and 55-60% CPU (100% reproducible).


* transfer a 20G file that is already cached on the server side to disk (with full cache on the server side):

server:
   [root@p05799459s78866 ~]# free -g
                total       used       free     shared    buffers     cached
   Mem:            62         20         42          0          0         19
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

client:
   [xrootd-test@p05799459m77145 XrdCl]$ free -g
                total       used       free     shared    buffers     cached
   Mem:            62         61          1          0          0         58
   -/+ buffers/cache:          2         60 
   Swap:            1          0          1 

   [xrootd-test@p05799459m77145 XrdCl]$ time strace -c ./xrdcp -f root://p05799459s78866//tmp/data01/20G_big_file /data07/tmp/
   [19.53GB/19.53GB][100%][==================================================][217.4MB/s]  
   % time     seconds  usecs/call     calls    errors syscall
   ------ ----------- ----------- --------- --------- ----------------
    95.50   19.843486       15875      1250           pwrite
     4.50    0.934266         518      1803         1 futex
     0.00    0.000660          55        12           munmap
     0.00    0.000608          76         8           brk
     0.00    0.000272           0      1253           epoll_ctl
     0.00    0.000118           0       631           write
     0.00    0.000008           0       107        87 open
     0.00    0.000000           0        20           read
     0.00    0.000000           0        32           close
     0.00    0.000000           0        16        14 stat
     0.00    0.000000           0        19           fstat
     0.00    0.000000           0         3           poll
     0.00    0.000000           0         1           lseek
     0.00    0.000000           0        51           mmap
     0.00    0.000000           0        24           mprotect
     0.00    0.000000           0         2           rt_sigaction
     0.00    0.000000           0         1           rt_sigprocmask
     0.00    0.000000           0         1         1 access
     0.00    0.000000           0         9           socket
     0.00    0.000000           0         4         1 connect
     0.00    0.000000           0         8           sendto
     0.00    0.000000           0        17           recvmsg
     0.00    0.000000           0         4           bind
     0.00    0.000000           0         4           getsockname
     0.00    0.000000           0         5           clone
     0.00    0.000000           0         1           execve
     0.00    0.000000           0         2           uname
     0.00    0.000000           0         5           fcntl
     0.00    0.000000           0         1           getcwd
     0.00    0.000000           0         1           readlink
     0.00    0.000000           0         1           getrlimit
     0.00    0.000000           0         2           getuid
     0.00    0.000000           0         1           arch_prctl
     0.00    0.000000           0         1           set_tid_address
     0.00    0.000000           0         4           tgkill
     0.00    0.000000           0         1           set_robust_list
     0.00    0.000000           0         1           epoll_create1
     0.00    0.000000           0         1           pipe2
   ------ ----------- ----------- --------- --------- ----------------
   100.00   20.779418                  5307       104 total

   real	1m31.164s
   user	0m0.313s
   sys	0m23.084s

Now the limiting factor is the write speed to the disk on the client side, the xrootd threads are not so busy any more: respectively 6-8% and 9-11% CPU (100% reproducible).


* I also tried to transfer the same file with curl and httpd on the server side:

server:
   [root@p05799459s78866 ~]# free -g
                total       used       free     shared    buffers     cached
   Mem:            62         20         42          0          0         19
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

client:
   [xrootd-test@p05799459m77145 XrdCl]$ free -g
                total       used       free     shared    buffers     cached
   Mem:            62          1         61          0          0          0
   -/+ buffers/cache:          1         61 
   Swap:            1          0          1 

   [root@p05799459m77145 tmp]# time curl --url http://p05799459s78866/data01/tmp/20G_big_file -o 20G_big_file
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 19.5G  100 19.5G    0     0   897M      0  0:00:22  0:00:22 --:--:--  882M

   real	0m22.283s
   user	0m1.466s
   sys	0m20.818s

curl is slightly slower than xrdcp, it seems to be CPU bound (100% CPU in top)



I also did some tests with multiple streams and XRD_CPPARALLELCHUNKS=10, and also modified the code so multiple event loops are being used, but I didn't observe any effect on the transfer rate.

Now to summarize it seems to me that xrdcp works just fine. If you would like me to do other tests let me know!

**Comment by ljanyst** [comment]
Only ~20 calls to `read` in each case and many more calls to `close`? This does not seem right.

**Comment by ljanyst** [comment]
You could try to figure out which version of BSD supports socket watermarking and run a test with that. I strongly suspect that excessive returns from epoll are the cause here. Socket watermarking does not work on Linux. http://lkml.iu.edu/hypermail/linux/kernel/0412.1/0680.html

**Comment by abh3** [comment]
Yes, I also am mystified by some of the counts like:

0.01    0.001123          10       107        87 open
0.00    0.000000           0        16        14 stat

among others. Why so many opens? Why are most of the opens and stat calls 
returning an error? It does seem consistent run to run. Quite strange.

Andy

**Comment by klabattermann** [comment]
Hello Andy

I guess most of the stat/open calls are from opening shared libraries and
directories. Depending on your LD_LIBRARY_PATH there could be many
failed attempts to open or stat a file.
For example opening libc.so I see three attempts:
  open("/opt/xrootd/prod/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
  open("/reg/g/psdm/sw/releases/dm-current/arch/x86_64-rhel7-gcc48-opt/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
  open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3

Also the strace didn't include the '-f' flag so not all threads are traced
and therefore the reads are very low.

I ran "strace -c -f" for a 24 GB file and I see:

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  71.19   50.881974        5098      9981      1097 futex
  17.94   12.818864      312655        41         1 nanosleep
   9.99    7.138469          23    314920     36189 read
   0.79    0.564963          14     40227           epoll_wait
   0.03    0.020346          14      1479           pwrite
   0.02    0.016862           6      2973           epoll_ctl
   0.02    0.011628           8      1494           sendto
   0.01    0.007300         456        16           munmap
   0.01    0.007009         467        15           brk
   0.00    0.000850           9        91           write
   0.00    0.000734          56        13         6 stat
   0.00    0.000572          11        50        26 open
   0.00    0.000434           7        66           mmap
   0.00    0.000239           6        37           close
   0.00    0.000156           4        43           mprotect
   0.00    0.000152          30         5           madvise
   0.00    0.000103           5        21           fstat
   0.00    0.000064          32         2         2 access
   0.00    0.000062           7         9           socket
   0.00    0.000059          15         4           tgkill
   0.00    0.000053           6         9           recvmsg
   0.00    0.000045           6         7           poll
   0.00    0.000045          45         1           execve
   0.00    0.000043           6         7         2 connect
   0.00    0.000017           6         3           getsockname
   0.00    0.000010          10         1           bind
   0.00    0.000010           2         6           fcntl
   0.00    0.000007           4         2           getsockopt
   0.00    0.000006           1         8           uname
   0.00    0.000004           2         2           getpeername
   0.00    0.000004           1         3           geteuid
   0.00    0.000004           4         1           arch_prctl
   0.00    0.000002           1         2           readv
   0.00    0.000001           1         1           getegid
   0.00    0.000000           0         1           lseek
   0.00    0.000000           0         2           rt_sigaction
   0.00    0.000000           0         1           rt_sigprocmask
   0.00    0.000000           0         6           clone
   0.00    0.000000           0         1           readlink
   0.00    0.000000           0         1           getrlimit
   0.00    0.000000           0         2           getuid
   0.00    0.000000           0         1           set_tid_address
   0.00    0.000000           0         2         2 openat
   0.00    0.000000           0         7           set_robust_list
   0.00    0.000000           0         1           epoll_create1
   0.00    0.000000           0         1           pipe2
------ ----------- ----------- --------- --------- ----------------
100.00   71.471091                371566     37325 total


Cheers,
   Wilko

**Comment by abh3** [comment]
Good point Wilko. I retract my observation. I didn't think of that.

Andy

**Comment by ljanyst** [comment]
Thanks Wilko! 314920 read calls gives you roughly 75kB of data retrieved from the socket per read syscall which is incredibly expensive. This gives some backing to my hypothesis about epoll returns and explains why the system scales well with larger number of active sockets but not when there is only few of them.

Michal, a way to test if it's a valid explanation would be to put a `nanosleep` in the poller loop between epoll calls and experiment with sleeping time. If the test is successful, you could think of fixing it in two ways:

1) Put a `nanosleep` in the poller depending on the number of active sockets. This is super ugly and will likely backfire.
2) Linux apparently supports the `FIONREAD` ioctl which tells you how many bytes are immediately readable from the socket. This likely means that the reason that Alan Cox gave 10 years ago for not supporting `SO_RCVLOWAT` is no longer valid and the kernel actually now gathers all the required statistics to implement watermarking. If so, this may be a fairly trivial patch.

**Comment by xrootd-dev** [comment]
Some background.... These studies are part of the larger problem that the 
client employs a single event loop. When the event loop reaches 100% CPU 
utilization, a performance limit is reached. While this doesn't much 
affect xrdcp performance (though that is not completely clear) it does 
affect a proxy server. Performance limitation in the proxy server is what 
sparked all of this. So, eventhough xrdcp may seem to be operating well it 
only represents a single data stream. That is not what we have in a proxy 
server and a single event loop would definitely represent a performance 
limitation.

Andy

**Comment by ljanyst** [comment]
Your ticket #303 seems to be a pretty valid explanation for that. You should have a look at how much data you get per event triggered. Each event results with quite a lot of locking in the client code (both IOEvents and client proper), hence the futex calls shown by strace. Note that locking/unlocking an uncongested mutex does not result with a syscall in Linux. I think we would not see the problem if watermarking worked properly. In principle there is also no reason why you cannot have multiple poller threads as long as all the parallel stream associated with one session are assigned the same thread.
