### ISSUE TITLE
Multiple places setting process limits 

### ISSUE THREAD

**Issue by theanalyst** [xrootd/xrootd#2010]
This stems from https://github.com/xrootd/xrootd/issues/1962 where ALMA's exceedingly high numbers caused high memory consumption. However we actually already set decent limits at the spec file https://github.com/xrootd/xrootd/blob/7846b1cc8cb2b163d3ee6ddc07b983529d232f64/packaging/common/xrootd%40.service#L16 which would've actually limited the damage had we not explicitly overriden these at https://github.com/xrootd/xrootd/blob/7846b1cc8cb2b163d3ee6ddc07b983529d232f64/src/Xrd/XrdConfig.cc#L1190. So this is a discussion to start off whether such an artificial limiting is needed in code at all; where we override an admin written max/inifinity values to a code constant versus a more canonical systemd/per service configuration where admins choosing higher limits can choose them. 

 The advantage with the systemd style configuration is downstream packages can decide in the spec file a higher default, without needing to override config values.

**Comment by amadio** [comment]
This has been fixed now on master, and will appear in the 5.6 release this month. (The link to the older pull request is just for reference). The documentation item for the new configuration option added is here: https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc135684303
