### ISSUE TITLE
[XrdHttp] Error 500 response when issuing GET with checksum request on a file that does not exist

### ISSUE THREAD

**Issue by ccaffy** [xrootd/xrootd#2018]
Interesting :)

When I issued a HEAD request with a `Want-Digest: adler32` header on a file that does not exist,  I properly get 404 Not Found Error.

```
$ curl -H 'Want-Digest: sha-512' -I https://something.cern.ch:1096/tmp/non-empty-dir/does_not_exist.txt
HTTP/1.1 404 Not Found
Connection: Close
Server: XrootD/v5.2.0-99-osghotfix...687
Content-Length: 0
```
But if I do a GET with a 'Want-Digest: sha-512' header on a file that does not exist:

```
$ curl -H 'Want-Digest: sha-512' -X GET https://something.cern.ch:1096/tmp/non-empty-dir/does_not_exist.txt
HTTP/1.1 500 Internal Server Error
Connection: Close
Server: XrootD/v5.2.0-99-osghotfix...687
Content-Length: 51

Underlying filesystem failed to calculate checksum.
```

**Comment by abh3** [comment]
Could you try the same test using xroot protocol to see where the problem 
really lies?

**Comment by ccaffy** [comment]
I spotted this "Ugly hack": https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L2096

If the server is NOT a manager, then the error on stat() is ignored... Will investigate further and look on how to NOT modify this behaviour ;)

**Comment by abh3** [comment]
It may be that Fabrizio knows the history behind that hack.

**Comment by ccaffy** [comment]
Yes, I asked him directly. My fix has been done according to what he said to me ;)
