### ISSUE TITLE
XrdClLog.hh should be a public header

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#202]
Hi,

Currently, XrdClLog.hh is an XrdCl-private header.

However, this makes it fairly difficult to write a usable XrdCl plugin - the plugin author needs a to write a separate logging subsystem.

Brian

**Comment by ljanyst** [comment]
This requests has been made a couple of times already, but this header has changed once or twice...

**Comment by bbockelm** [comment]
Can't this be taken care of via the existing versioning mechanisms?

Looking through git history, I see only one change that would have broken ABI (add virtual destructor) and one change in data structure size (addition of PID).

Even if there's only a lightweight interface, it would be very useful for plugin authors.
