### ISSUE TITLE
Lazy-download plugin for XrdCl

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#203]
Hi all,

I've been working on migrating CMSSW's "lazy-download" feature to a XrdCl plugin.  See:

https://github.com/bbockelm/xrootd-lazy-download

The idea behind lazy-download is latency-hiding: the file is downloaded to local disk in large chunks (and on demand).  No prefetching (chunk download is started on first access) and no persistence (file is unlinked at close).

I note no XrdCl plugins are packaged with Xrootd core itself.  Is there interest in hosting this plugin?  Or should I just keep it separate?  I'd like to see it somehow tied into Xrootd, as I think others would benefit from it.

Brian

**Comment by bbockelm** [comment]
One suggestion from Andreas is that this is may be generally useful enough that we can build it into XrdCl itself (especially as plugins cannot be stacked).  @ljanyst?

**Comment by ljanyst** [comment]
You can write a plug-in that stacks plug-ins in any way you wish. Stacking was not provided in the default implementation of the plug-in system because I could not think of a generic enough way to do it.

I think this stuff is useful and generic enough to be integrated directly into XrdCl, but since I only have a couple of work-weeks left I will not do it myself.

**Comment by bbockelm** [comment]
Oh?  It wasn't clear to me how to prevent infinite recursion from a plugin loading itself.  Do you mean invoking other plugins explicitly (i.e., I write my own plugin loader)?

**Comment by ljanyst** [comment]
You disable the default plug-in loader by passing false to appropriate constructor parameter:
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClFile.hh#L48

And then you can write your own plugin loader using `XrdSysPlugin` to reference the plugins explicitly in a couple of lines of code.

**Comment by ljanyst** [comment]
I mean you write a plug-in that is a plug-in loader.

**Comment by abh3** [comment]
This will be addressed by using a client-side XCache setup. This will have all the features described here.
