### ISSUE TITLE
Update default message digest algorithm for GSI

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2030]
@adriansev noted that none of the default message digest algorithms are supported out-of-the-box by OpenSSL 3 / RHEL 9.

The current code (https://github.com/xrootd/xrootd/blob/master/src/XrdSecgsi/XrdSecProtocolgsi.cc#L161) has set `sha1:md5`.

Can we simply update this to `sha256` (remove sha1 and md5)?  Don't know when `sha256` was added to OpenSSL (could have been named SSLeay at the time!) but I can't imagine we support clients old enough that they don't have `sha256`.

**Comment by xrootd-dev** [comment]
The question is when do we make SHA256 the default. I didn't see any way 
to make this a run-time decision (i.e. use SHA1 only when the thing you're 
connected to can't use SHA256). Do you see any wayto do that?

**Comment by bbockelm** [comment]
Doing some Googling, it seems SHA256 support was released with OpenSSL 0.9.8 which was included with RHEL5.

So, setting the default to sha256 only would drop support for RHEL4.  That’s probably OK.
