### ISSUE TITLE
Is iv4 option ignored in recent versions?

### ISSUE THREAD

**Issue by maksiks** [xrootd/xrootd#2035]
Hi, after upgrading one of the doors to version xrootd-5.5.5 (from 5.4.2) it stopped functioning. Both xrootd and cmsd start and service shows as running, however I see in the cmsd log:
230613 07:33:12 1776620 Config: server service enabled.
230613 07:33:12 1776620 Xrd_Sched: running cms protocol handler inq=0
230613 07:33:12 1776620 cms_Pander: server services to dtn20.nese.rc.fas.harvard.edu:1213
230613 07:33:12 1776620 cms_Pander: trying to connect to lvl 0 dtn20.nese.rc.fas.harvard.edu:1213
230613 07:33:12 1776635 State: Status changed to active + nostaging
230613 07:33:12 1776620 XrdOpen: Unable to connect socket to dtn20.nese.rc.fas.harvard.edu; connection refused
230613 07:33:18 1776620 cms_Pander: trying to connect to lvl 0 dtn20.nese.rc.fas.harvard.edu:1213
230613 07:33:24 1776620 cms_Pander: trying to connect to lvl 0 dtn20.nese.rc.fas.harvard.edu:1213

while looking at ifconfig one can get an impression that ipv6 is enabled, but in reality it is not

bond0.2117: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 140.247.236.31  netmask 255.255.255.128  broadcast 140.247.236.127
        inet6 fe80::be97:e1ff:fef1:ff40  prefixlen 64  scopeid 0x20<link>
        inet6 2607:fb60:2406:8:be97:e1ff:fef1:ff40  prefixlen 64  scopeid 0x0<global>

I do have -I v4 flag enabled, however it looks to me that it is ignored now
[Service]
ExecStart=/usr/bin/cmsd -l /var/log/xrootd/cmsd.log -c /etc/xrootd/xrootd-%i.cfg -k fifo -s /run/xrootd/cmsd-%i.pid -n %i -I v4

Please advise on what I can do to make this door work (please no comments like: enable ipv6 everwhere)
Thank you, --Max

**Comment by xrootd-dev** [comment]
Hi Max,

From what I see in the log, this does not seem like an IP issue. In fact, 
dtn20.nese.rc.fas.harvard.edu only has an IPv4 address so IPv4 would have 
been used. The problem seem that no one was listing on port 1213 on 
dtn20.nese.rc.fas.harvard.edu. The "connection refused" is the tellig 
part. So, the host was eached but there was no one on port 1213.

So, I would check what is going on at dtn20.nese.rc.fas.harvard.edu.

Andy

On Tue, 13 Jun 2023, maksiks wrote:

> Hi, after upgrading one of the doors to version xrootd-5.5.5 (from 5.4.2) it stopped functioning. Both xrootd and cmsd start and service shows as running, however I see in the cmsd log:
> 230613 07:33:12 1776620 Config: server service enabled.
> 230613 07:33:12 1776620 Xrd_Sched: running cms protocol handler inq=0
> 230613 07:33:12 1776620 cms_Pander: server services to 
dtn20.nese.rc.fas.harvard.edu:1213
> 230613 07:33:12 1776620 cms_Pander: trying to connect to lvl 0 dtn20.nese.rc.fas.harvard.edu:1213
> 230613 07:33:12 1776635 State: Status changed to active + nostaging
> 230613 07:33:12 1776620 XrdOpen: Unable to connect socket to 
dtn20.nese.rc.fas.harvard.edu; connection refused

**Comment by maksiks** [comment]
Hi Andy,
If I start on that same node xrootd version 5.4.2 from the container it will have no problem talking with dtn20. This started to happen only after upgrade. 
In fact on this monitoring page you can see that the service with dtn20 as redirector functions.
https://etf-cms-prod.cern.ch/etf/check_mk/index.py?start_url=%2Fetf%2Fcheck_mk%2Fview.py%3Fhost%3Ddtn20.nese.rc.fas.harvard.edu%26site%3Detf%26view_name%3Dhost

--Max

**Comment by abh3** [comment]
One more thing. I know the monitoring says what it says but I get he following trying to do a simple test:

telnet dtn20.nese.rc.fas.harvard.edu 1213
Trying 140.247.236.34...
telnet: connect to address 140.247.236.34: Connection refused

If someone was actually listening on the port I would not get this message. This could also be a firewall issue. Anyway, you can try this yourself as a test that is independent of cmsd.

**Comment by maksiks** [comment]
Yes, your request from outside gets blocked by iptables, I can clearly see it if the rules.
 Please notice that telnet with hostname does not work while with IP address it works:
... in the config file I put explicitly IP ( all.manager 140.247.236.34:1213)
And if I start container on dtn17 with older version it works. The only way I can explain what I see is that the way cmsd does things was changed. My speculation is that it used to resolve hostname to ip (either ipv4 or ipv6) but now just goes ahead with hostname straight up.

Anyway, I need to make it work somehow, it sounds to me that what you are saying is: 'make sure telnet with hostname on that port works'. Or there is anything else I can do?

[maxi@dtn17 ~]$ telnet dtn20.nese.rc.fas.harvard.edu 1213
Trying 10.255.125.103...
telnet: connect to address 10.255.125.103: Connection refused
[maxi@dtn17 ~]$ telnet 140.247.236.34 1213
Trying 140.247.236.34...
Connected to 140.247.236.34.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by maksiks** [comment]
The network setup on these nodes is somewhat complicated. From the beginning I used this directive in the config to make it work
xrd.network use bond0.2117
where bond0.2117 is the name of the public interface

after turning on all debugging I notice this in the log file:
=====> xrd.port 1094
=====> all.sitename T2_US_MIT_Tape
Config warning: ignoring invalid net option 'use'.
Config warning: ignoring invalid net option 'bond0.2117'.
=====> xrd.network use bond0.2117
....
------ Protection system initialization completed.
Config Routing for 10.255.125.100: local pub4 prv4 
Config Route all4: 10.255.125.100 Dest=[::10.255.125.100]:1094

Am I using xrd.network directive correctly? Those entries about routing, can they indicate a problem? 10.255.125.100 interface should not be used at all as far as I can tell.
Thank you, --Max

**Comment by xrootd-dev** [comment]
Well, yes. If it is telling it's using a routing that is not going to 
work, then I would expect the error. Notice that the documentation shows 
that you need to specify more than the "use" option because the network 
handler needs to know the context of how the interfaces will be used:

[routes {split|common|local} [use if1[,if2]]] }

Yes, the documentation is misleading as it's missing the ending brace. 
That said, you need to secify how interfaces are routed and then you are 
allowed to pick up to two interfaces. In your case the routing is either 
common or local based on the fact that you use IPTables. So,for example it 
would look like

routes common use bond0.2117

Use local if all routing occurs only on a network that uses only private 
addresses. Now, bond0.2117 should be the actual interface name.

Now, the basic question here is if the otainer that runs 5.4.2 works why 
can't the container that runs 5.5.5 be setup in exactly the same way? That 
certainly would simplify things.

**Comment by maksiks** [comment]
I think I somewhat misled earlier:
I run 5.4.2 in podman, while 5.5.5 I am trying to install on OS as is.
While looking at what I do in the container I suspect the difference is that in the container I use
/etc/hosts that looks like this:
140.247.236.31 dtn17.nese.rc.fas.harvard.edu
140.247.236.32 dtn18.nese.rc.fas.harvard.edu
140.247.236.33 dtn19.nese.rc.fas.harvard.edu
140.247.236.34 dtn20.nese.rc.fas.harvard.edu

while on OS we have:
cat /etc/hosts 
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
169.254.1.1 idrac.local drac.local

... that probably explains why container is running all fine and running on OS does not work. Does it sound plausible?
So either I adjust /etc/hosts on OS, or use xrd.network option in the config.
The correct syntax should look like: 
xrd.network routes common use bond0.2117 ?

Thank you, --Max

**Comment by abh3** [comment]
I'm closing this as it apparently has been resolved.
