### ISSUE TITLE
Unexpected stream timeout

### ISSUE THREAD

**Issue by smithdh** [xrootd/xrootd#2042]
It's possible to get a XrdCl "stream timeout" in an unexpected situation: When a stream has been idle (i.e. no outstanding requests) for longer than the stream timeout time, (60s by default) there's a small chance that when a new request is sent a stream timeout is triggered. e.g. for a Read() the connection might recover; file be reopened and the read() be reissued successfully. But in some situations not. e.g. if "ReadRecovery=false" property is set, the Read() returns "Invalid session" in that situation. 

e.g. a client code snippet to open and read a few bytes:

```
XrdCl::File f;
char buf[16];
uint32_t BytesRead = 0;

XrdCl::Env *env  = XrdCl::DefaultEnv::GetEnv();
env->PutInt("StreamTimeout", 30); //60 is default
env->PutInt("TimeoutResolution", 1); //15 is default

f.SetProperty("ReadRecovery", "false");
auto st = f.Open("root://pmpe01:1194//file01", XrdCl::OpenFlags::Read);
if (!st.IsOK()) {
  std::cerr << "Open not ok" << std::endl;
  exit(1);
}
sleep(35);
st = f.Read(0, 5, buf, BytesRead, 0);
if (!st.IsOK()) {
    std::cerr << "Read not ok: " << st.ToString() << std::endl;
    exit(1);
}
```

Assuming a test server is available and the test file is present etc, this should open and read a few bytes. The obseration is there's a small chance the read can fail with Invalid session. This almost never happens - making a client doing similar things repeatedly and with a somewhat loaded client machine is probably needed. But, for example, adding the delay, below, within the client appears to reliably show the possibility even with a simple client program on an unloaded test server.

```
diff --git a/src/XrdCl/XrdClMessageUtils.cc b/src/XrdCl/XrdClMessageUtils.cc
index a56c156..db24c1d 100644
--- a/src/XrdCl/XrdClMessageUtils.cc
+++ b/src/XrdCl/XrdClMessageUtils.cc
@@ -35,6 +35,8 @@
 
 #include "XProtocol/XProtocol.hh"
 
+#include <unistd.h>
+
 namespace XrdCl
 {
   //----------------------------------------------------------------------------
@@ -69,6 +71,7 @@ namespace XrdCl
     // Allocate the SID and marshall the message
     //--------------------------------------------------------------------------
     st = sidMgr->AllocateSID( req->streamid );
+sleep(2);
     if( !st.IsOK() )
     {
       log->Error( XRootDMsg, "[%s] Unable to allocate stream id",
```

**Comment by smithdh** [comment]
I think this is seen within EOS, in some situations. But I'm not sure if this is causing some issues or not. At first I put this as non-critical, however it might be found to be more important, later.

**Comment by amadio** [comment]
Hi @smithdh, I tried to turn the snippet from this ticket into a test, but even when I added the sleep call into `XrdClMessageUtils.cc` and launch 1000 copies of the test at the same time, I do not see any failure. Do you have some sort of authentication enabled on your test server which could play into the timings to make it fail? I'd like to add a test that can reproduce this problem along with the fix to ensure it won't break again.

**Comment by smithdh** [comment]
[xrdclient_test66.cc.txt](https://github.com/xrootd/xrootd/files/11815207/xrdclient_test66.cc.txt)

Hi @amadio 

Maybe you could try with this reproducer ('xrdclient_test66.cc`) e.g.

c++ -std=c++17 xrdclient_test66.cc  -I/usr/include/xrootd -lXrdCl -lpthread
XrdSecPROTOCOL=unix XRD_LOGLEVEL=Error  ./a.out <test_server_name>

(I've used it with the fast 'unix' authentication). The above small example tries 200 concurrent connect/read/close with a 20s streamtimeout, and with 22s between the connect & read, 10 times. I got errors on about 6 out of 10 tries. I didn't make the streamtimeout very short for the test, since it might actually trigger in a valid timeout.

**Comment by amadio** [comment]
Thank you, @smithdh, I will se if I can convert this new example into a test and merge it together with this fix.

**Comment by amadio** [comment]
I will add the test later. All current tests pass with this patch, so I will merge and tag the release later today. Thanks!
