### ISSUE TITLE
Remove support for oss.runmodeold

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#2048]
The oss.runmodeold directive was introduced in release 3 when external file attributes (e.g. lock and pin files) were internalized into file attributes. This directive allowed sites to still use the old filesystem layout until they could migrate to the new layout. Now, after three major releases and a decade later it is time to remove this support to eliminate dual tracking code within the XrdOss plugin. This will simplify the plugin code paths. The plan is to eliminate the support in R6.

**Comment by abh3** [comment]
This was done.

**Comment by amadio** [comment]
Can we link here the commit that did this change? I don't remember seeing a change for this after this has been discussed.

**Comment by abh3** [comment]
That happened some time ago but I have been unable to find the commit that 
removed the support. It cetainly is not in the source anymore.

**Comment by amadio** [comment]
Ok, so I guess we can drop this from 6.0 milestone, then, as it's been done before it.
