### ISSUE TITLE
username != username in commit #1978

### ISSUE THREAD

**Issue by s-thiele** [xrootd/xrootd#2056]
Hello,
in commit #1978 in the file [src/XrdSciTokens/XrdSciTokensAccess.cc](https://github.com/xrootd/xrootd/pull/1978/files#diff-8cd57d0057f83be94fb75362e5c1c31c8592a2b6ef6403192d00e28837bc001d) line 241 reads
`if (!m_username.empty() && username != username) {return "";}`(https://github.com/xrootd/xrootd/pull/1978/files#diff-8cd57d0057f83be94fb75362e5c1c31c8592a2b6ef6403192d00e28837bc001dR241)
Where `username != username` is always going to return false, right? Is that intended?
I assume this is supposed to be `m_username != username`?
In the current version on the masterbranch, the line is still the same (it's just line 242 in there: https://github.com/xrootd/xrootd/blob/master/src/XrdSciTokens/XrdSciTokensAccess.cc#L242)
Cheers,
Simon

**Comment by amadio** [comment]
Indeed, that does sound right. Sadly, I literally announced the latest patch release a minute ago. I will look into making a 5.6.2 with a fix for this issue tomorrow.

**Comment by amadio** [comment]
@bbockelm Could you please take a look at this? Thank you!

**Comment by matyasselmeci** [comment]
Has #2064 fixed this or is there still something that needs doing here?

**Comment by amadio** [comment]
Yes, but it only closes automatically when merged to master, while this has been merged to devel. It would be closed with the release of 5.6.2 (coming soon).
