### ISSUE TITLE
Improve TPC error message on "no bytes received" timeout

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#2060]
Hello,

The HTTP TPC code monitors the progress of the transfer, namely how many bytes have moved. In case no bytes move in a predefined window (2 minutes initially, 1 minute afterwards), then the following error message is given:
```
Transfer failed because no bytes have been received in <timeout> seconds.
```

The message is printed both for HTTP TPC Pull and HTTP TPC Push.

**Request**
Modify the error message according to the TPC type:
- TPC Pull: keep the error message as it is
- TPC Push: modify the error message to make it evident that the destination did not write any bytes. Example message: `no bytes have been sent to the destination`

Files that would be affected:
https://github.com/xrootd/xrootd/blob/v5.6.1/src/XrdTpc/XrdTpcTPC.cc#L639
https://github.com/xrootd/xrootd/blob/v5.6.1/src/XrdTpc/XrdTpcMultistream.cc#L334

**Comment by amadio** [comment]
@mpatrascoiu Is this different enough?
```
# PUSH MODE
$ davix-cp --capath /etc/grid-security/certificates/ --copy-mode push https://gentoo.cern.ch:8081/test.raw https://gentoo.cern.ch:8082/test.raw
(Davix::HttpThirdPartyCopy) Error: Transfer failure: Error when interacting with local filesystem:
  Transfer failed because no bytes have been transmitted in 120 seconds.
# PULL MODE
$ davix-cp --capath /etc/grid-security/certificates/ --copy-mode pull https://gentoo.cern.ch:8081/test.raw https://gentoo.cern.ch:8082/test.raw
(Davix::HttpThirdPartyCopy) Error: Transfer failure: Error when interacting with local filesystem:
  Transfer failed because no bytes have been received in 120 seconds.
```
