### ISSUE TITLE
XrdHttpTpc better reporting of underlying curl errors

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#2067]
It would be good, especially for end-users, to get more information when the underlying curl copy that drives HTTP TPC transfers fails. For example the following two transfers report the same error message, but the actual reason is very different:

1. `https://fts3-atlas.cern.ch:8449/fts3/ftsmon/#/job/067ed092-2c51-11ee-a2d9-fa163e087e6b`
**Reported error**
reason_text:TRANSFER ERROR: Copy failed (3rd pull). Last attempt: Transfer failure: Error when interacting with local filesystem: Failure when closing file handle: Unable to store file - file has been cleaned because the stored file does not match the provided targetsize /eos/atlas/atlasscratchdisk/rucio/user/skadir/b4/19/user.skadir.34199691.EXT0._001551.IDPVM.root; input/output error (code=5)
**Actual error message**
TPC_PullRequest: event=SIZE_FAIL, local=/eos/atlas/atlasscratchdisk/rucio/user/skadir/b4/19/user.skadir.34199691.EXT0._001551.IDPVM.root, remote=https://ccdavatlas.in2p3.fr:2880/atlasscratchdisk/rucio/user/skadir/b4/19/user.skadir.34199691.EXT0._001551.IDPVM.ro ot?copy_mode=pull, user=(anonymous), status=500; HTTP library failed: Failed to load CRL file (path? access rights?, format?)

2. `https://fts3-atlas.cern.ch:8449/fts3/ftsmon/#/job/fb91fad2-2d8c-11ee-9e19-fa163eb04ff0`
**Reported error**
reason_text:TRANSFER ERROR: Copy failed (3rd pull). Last attempt: Transfer failure: Error when interacting with local filesystem: Failure when closing file handle: Unable to store file - file has been cleaned because the stored file does not match the provided targetsize /eos/atlas/atlasdatadisk/rucio/mc16_13TeV/65/99/HITS.34202576._005271.pool.root.1; input/output error (code=5)
**Actual error**
This is actually not visible in the logs, as it comes from a 120 seconds timeout in curl when no data moves. Or after a 60 seconds timeout after the transfer starts but then it blocks for whatever reason.

It would be extremely helpful for operators to distinguish between such types of errors as they have really different underlying causes.

**Comment by ccaffy** [comment]
Done and merged via https://github.com/xrootd/xrootd/pull/2260
