### ISSUE TITLE
pss.origin directive URL doesn't support API endpoints

### ISSUE THREAD

**Issue by jhiemstrawisc** [xrootd/xrootd#2068]
I'm working on a new redirector service that can detect whether it should redirect to a cache or an origin, and I've broken those two endpoints out at `/api/v1.0/director/origin` and `/api/v1.0/director/object`, respectively. However, in my testing cache, when I try to set `pss.origin <redirector-domain>:443/api/v1.0/director/origin`, xrootd fails to initialize with the error:
`badly formed origin URL` (error in source code is [here](https://github.com/xrootd/xrootd/blob/8f0a3ebf6b14c65c57667d07c0c624f3d4b215a8/src/XrdPss/XrdPssConfig.cc#L770))

Is it possible to make parsing the redirector URL a little more flexible so something like this can work?

**Comment by abh3** [comment]
The problem here is that the code doesn't know what to do with the "path" argument. So, what is it that the origin URL is really supposed to do? That is, what is the expected final URL supposed to look like given the example?

**Comment by jhiemstrawisc** [comment]
In our case, yes, the final URL would have that form. The intention is that our redirector service has the ability to redirect clients to either caches or origins. A `GET` request to `<redirector-domain>:443/api/v1.0/director/origin/foo/bar` should redirect the client to `<origin-domain>:1094/foo/bar`, whereas a `GET` request to `<redirector-domain>:443/api/v1.0/director/object/foo/bar` should redirect to `<cache-domain:>8443/foo/bar`. The redirector knows what kind of redirection to serve based on the endpoint. I think all we would need is for the path to be appended.

**Comment by abh3** [comment]
We have addressed this issue by introducing a new directive pss.hostarena with which you specify the text you want inserted in from of any client-specified path. This directive only applies to fixed remote origins (i.e. this who have a specified host:port). The directive should appear in R6 comming out later this year. While being able to extend the url specification was the preferred solution, the way the origin directive is structured made it error prone. So, using a new directive was the simplest approach.

**Comment by amadio** [comment]
@abh3 Is this fine for 5.7.1? Please add the milestone which you think is more appropriate, either 5.7.1 or 6.0.0. Thank you!
