### ISSUE TITLE
Compound ID parsing broken for Authfile in XRootD 5.6.2

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#2088]
Using a previously working Authfile with lines such as:
```
= atlasprd      o: atlas g: /atlas r: production
```
now breaks with:
```
230916 17:59:27 2278823 acc_AuthFile: Invalid ID sprecifier - o
230916 17:59:27 2278823 acc_ConfigXeq: No id selectors specified for atlasprd
```
Trying with:
```
= atlasprd      o atlas g /atlas r production
```
yields the same error. 

Going through the changelog, it seems the fix for https://github.com/xrootd/xrootd/issues/2061 has a logic error, namely, it does:
https://github.com/xrootd/xrootd/blob/478ad4b4c4ce305d072249d7f25c5aa134d44f69/src/XrdAcc/XrdAccAuthFile.cc#L164-L165
so any idspec less or equal two characters long is discarded, which breaks both the `o` and `o:` case. I also read through the code at the time the fix came in, but sadly I was irritated by the inverted logic, too, and hence did not catch this bug :cry: . 

Since longer idspec are accepted, I tried with:
```
= atlasprd      o:: atlas g:: /atlas r:: production
```
which in fact (accidentally) works with XRootD 5.6.2. 

So I think we actually need:
```c
if (strlen(pp) > 2 || !index("ghoru", *pp))
```
here to cover all cases.

**Comment by amadio** [comment]
Likely due to https://github.com/xrootd/xrootd/commit/478ad4b4c4ce305d072249d7f25c5aa134d44f69.

**Comment by abh3** [comment]
Good grief. Oliver is correct and the problem was misreading the negative logic to provide a fix. The statement
if (strlen(pp) <= 2 || !index("ghoru", *pp))
should have been
if (strlen(pp) > 2 || !index("ghoru", *pp))

Looks like we will need a 5.6.3 in post haste. This is quite embarrassing.

**Comment by amadio** [comment]
I think I will add a patch in the spec file and re-release 5.6.2 with a fix for this, what do you think?

**Comment by amadio** [comment]
Ok, I see the fix was already pushed. Nevermind. Thanks, @abh!

**Comment by olifre** [comment]
@amadio @abh3 Thanks for the quick fix / quick action! No worries, such things happen... 

I believe changing the content of a release post-release is often frowned upon by distros — notably, distros packaging the source from the GitHub tag will still get the original 5.6.2 as of now (without the patch). It does not affect me personally since we use XRootD repos directly on our servers (and on my workstation, I am using Gentoo, which @amadio will cover :wink: ), but other distro packagers may be irritated.

**Comment by amadio** [comment]
Note that I did not change the tarball, I actually added a patch file and used it in the spec file. Same for Gentoo, I added a patch as separate file. :-)

**Comment by amadio** [comment]
> It does not affect me personally since we use XRootD repos directly on our servers

Which of the repos do you actually use? I'd like to move to a single official one, as the release process is complicated now with several places to update each time.

**Comment by olifre** [comment]
> Note that I did not change the tarball, I actually added a patch file and used it in the spec file. Same for Gentoo, I added a patch as separate file. :-) But I plan to release 5.6.3 soon enough (in a few days), this was just a way to have a quick fix for those using RPMs.

Thanks, that sounds very reasonable :+1: . 



> > It does not affect me personally since we use XRootD repos directly on our servers
> 
> Which of the repos do you actually use? I'd like to move to a single official one, as the release process is complicated now with several places to update each time.

I'm using `http://xrootd.org/binaries/stable/slc/` and `http://xrootd.org/binaries/testing/slc/` for good old CentOS 7 and RockyLinux 8.

**Comment by amadio** [comment]
Ok, thank you. At CERN, EOS uses http://xrootd.cern.ch/sw/repos/stable/slc/7. I need to discuss this with others, but the new one will likely go into a single place in EOS (i.e. xrootd.web.cern.ch) and be mirrored into SLAC, but `slc/X` will be likely renamed to `elX`.

**Comment by abh3** [comment]
I agree, he says meekly.

**Comment by ellert** [comment]
Patch applied in Fedora and EPEL packaging (5.6.2-2) and in Debian (5.6.2-2).
https://bodhi.fedoraproject.org/updates/?packages=xrootd
https://tracker.debian.org/pkg/xrootd

**Comment by amadio** [comment]
Thank you @ellert. Please note that I have some updates to the spec file and debian packaging relative to what you have downstream, this will come with XRootD 5.7, but I recommend you taking a look at my branch at https://github.com/amadio/xrootd/tree/packaging before I merge it into `devel` and `master` in the main repo in case there are things that make your life as packager more difficult (especially for debian). Thanks for the quick packaging of our new versions!
