### ISSUE TITLE
[XrdHttp] Add an option to allow the loading of external handlers if TLS is not configured

### ISSUE THREAD

**Issue by ccaffy** [xrootd/xrootd#2099]
@amadio found an interesting issue when he tried to setup XrdHttpTPC on his devbox.
Without TLS configured, the XrdHttpTPC library could not be loaded.

It comes from the following line: https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpProtocol.cc#L1085

Some external HTTP plugins don't necessary need TLS to be configured. E.g: XrdHttpTPC should work without the need for TLS.

We will add a new option to the http.exthandler configuration, named `notls` to allow a user to specify that the plugin to load does not require TLS.

Implementation idea: 
- create a second vector for plugins to be loaded without TLS support.
- Don't remember to update the doc: https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc135684370

**Comment by esindril** [comment]
Are you sure you really want XrdHttpTPC without TLS? This would mean that the tokens would be transmitted in clear text ...

**Comment by abh3** [comment]
The default is to require TLS. The option is strictly for those people 
that use an alternate security protocol that is not TLS dependent.

**Comment by amadio** [comment]
Yes, I'd like write tests for the TPC functionality which do not require authentication, but I guess you could use just X509 as well, or find other uses for `notls`.

**Comment by esindril** [comment]
Fine, as long as it's not the default thing, otherwise this might bite many.

**Comment by ccaffy** [comment]
Done with https://github.com/xrootd/xrootd/pull/2253
