### ISSUE TITLE
Environment file does not respect `all.adminpath`

### ISSUE THREAD

**Issue by amadio** [xrootd/xrootd#2106]
In https://xrootd.slac.stanford.edu/doc/dev561/xrd_config.htm#_Toc135684283, the docs say that the environment file should be opened inside `all.adminpath`. However, in code, `/tmp` is hard-coded:

https://github.com/xrootd/xrootd/blob/e7cf81f82d177b768f740b9db28e669b09273ca6/src/Xrd/XrdConfig.cc#L1057-L1061

I made a change for "fixing" this, in case it should indeed respect `all.adminpath`. I found this out because I saw test failures after running the newly added tests as different users on my machine. They both wanto create `/tmp/xrootd.anon.env`, but in the second attempt, it already exists and is owned by someone else, which makes xrootd fail to initialize.

Proposed solution:

```diff
--- a/src/Xrd/XrdConfig.cc
+++ b/src/Xrd/XrdConfig.cc
@@ -1058,7 +1058,7 @@ void XrdConfig::Manifest(const char *pidfn)
 //
    if (pidfn && (Slash = rindex(pidfn, '/')))
       {strncpy(manBuff, pidfn, Slash-pidfn); pidP = manBuff+(Slash-pidfn);}
-      else {strcpy(manBuff, "/tmp");         pidP = manBuff+4;}
+      else {strcpy(manBuff, ProtInfo.AdmPath); pidP = manBuff+strlen(ProtInfo.AdmPath);}
 
```

Tested and it works to make the env file appear inside `all.adminpath` instead of `/tmp`.

**Comment by abh3** [comment]
Hi Guilherme.

By all means, please fix this as suggested.

Andy

**Comment by amadio** [comment]
@abh3, ok, great. I will merge this into 5.6.3 then. Cheers,
