### ISSUE TITLE
Documentation error for async parameters

### ISSUE THREAD

**Issue by sponce** [xrootd/xrootd#211]
The doc says : 

xrootd.async parms
parms: ....  [segsz segsz[k | m | g]]

But the code is : 

 struct asyncopts {const char *opname; int minv; int *oploc;
                             const char *opmsg;} asopts[] = {
...
       {"segsize", 4096, &V_segsz, "async segsize"},

Note the difference "segsz" versus segsize.
The comment in the code is correct, but settings according to the documentation are perfectly useless !

**Comment by abh3** [comment]
Fixed in 4.2 documentation that is now available.
