### ISSUE TITLE
XRootD TLS missing certificate chain, causing verification failures

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2126]
When configuring TLS via `xrd.tls`, we should export the full chain in the specified cert file during the TLS handshake.  Instead, only the first entry in the file is exported.

For example, suppose you set the following line:

```
xrd.tls /etc/xrootd/certificates/tls.crt /etc/xrootd/certificates/tls.key
```

Then, I'd expect the full contents of `/etc/xrootd/certificates/tls.crt` to be sent during the TLS handshake, not just the first entry.

Without the full chain, connections with alternate verification paths -- or with requiring intermediate certificates -- fail.

To test:

1.  Configure a XRootD on the public internet.
2. Use `certbot` to get a Let's Encrypt certificate for the host.
3. Set the host cert file to be the `fullchain.pem` from Let's Encrypt.
4. Run `curl` against the XRootD instance; note that it fails.
5. Run `openssl s_client -connect <hostname>:<port>` and look at the reported `Certificate chain`.

For the last item, when XRootD is used, you see a chain like this:

```
Certificate chain
 0 s:/CN=hcc-briantest7.unl.edu
   i:/C=US/O=Let's Encrypt/CN=R3
```

That can't be verified as `/C=US/O=Let's Encrypt/CN=R3` is not a trust root.

When you use the same set of files with Apache, you'll see:

```
Certificate chain
 0 s:/CN=hcc-briantest7.unl.edu
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
```

and verification works.

In general, this prevents use outside the "grid" context: for browser authentication (and most grid CAs - except the CERN CA - are cross-signed so they are valid in the browser as well), intermediate CAs are used and only roots are distributed to clients.

**Comment by amadio** [comment]
Fixed by #2127.
