### ISSUE TITLE
Non-unique user IDs in monitoring

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2133]
In the [documentation](https://xrootd.slac.stanford.edu/doc/dev56/xrd_monitoring.htm), the user ID is listed as having this interpretation:

```
userid:     prot/user.pid:sid@host
```

Where the fields are as follows:
- `prot`: "Communication protocol being used by the client"
- `user`: "Unix username of the user as reported by the client (i.e. unverified) or the plug-in identifier. You can distinguish between the two as plug-ins always report a pid of zero. The user name is the plug-in component name (e.g. pfc)."
- `pid`: "User’s process number that issued the request."
- `sid`:  "Server’s fingerprint for the connection to user:pid at host."

Now, the `sid` documentation here is incorrect (or, at least, confusing).  It is actually the server instance fingerprint and static until the server restarts.

For the `https` protocol, `pid` is set to a monotonically increasing integer, meaning the `userid` string is always unique for a connection (in fact, the tuple of (pid, sid) is unique).

Now, for the `xroot` protocol, `pid` is set to the client-identified PID, meaning there's no guaranteed of uniqueness of `userid`.

Hence, for the `xroot` protocol, you can't associate a file open (`d` record type) record with a user login (`U`) or a token access (`T`).  This means the token-based monitoring done during #1987 only will work with the f-stream (as those records include the user dictID as part of the f-stream's open record).

I see two approaches here:

1.  The `userid` is not meant to be unique.  That's fine, though I'd request re-wording `sid` to say it's simply the server's unique fingerprint, not the "fingerprint for the connection".
2. The `userid` should be made unique.  For the xrootd protocol, compute the `pid` the same way with `getSID` as is done for the HTTP protocol.

**Comment by abh3** [comment]
I see your point. The idea was that in xrootd (pid,sid,host) would be unique; which I think it is; well until the pid is recycled. I agree that it's inconsistent between the protocols. We will happily accept a patch that converges the two. If you do supply the patch, please provide text that needs to be changed in the documentation.

**Comment by abh3** [comment]
@bbockelm I'm trying to resolve this. Could you point me to the code in http that makes "username" a monotonically increasing number? I could not find it. In fact it looks like username is always "http".

**Comment by abh3** [comment]
@bbockelm Never mind, I found it.

**Comment by abh3** [comment]
I just pushed a new patch that does what you want but only affects the monitoring not everything else. The commit is d25051cd0 if you want to see what needed to be done.

**Comment by amadio** [comment]
CI is not happy with the change, could you please take a look? Thanks!

**Comment by abh3** [comment]
I wonder why gcc never complained about this obvious error. I suppose it may have something to do with the pragmas, sigh.
________________________________

**Comment by abh3** [comment]
Presumably, we are set to go with this, right?

**Comment by amadio** [comment]
Yes, I just assigned old issues to the people who solved them to give proper credit for the work.
