### ISSUE TITLE
xrootd segfaults if pss.origin uses https protocol with no port

### ISSUE THREAD

**Issue by turetske** [xrootd/xrootd#2140]
As 443 is the default port for tls, if xrootd uses https protocol, I think it should assume the port is 443 if one isn't given rather than seg faulting.

`pss.origin https://<url>` should be interpreted as `pss.origin https://<url>:443` for example.

**Comment by bbockelm** [comment]
Particularly, the failure is here:

https://github.com/xrootd/xrootd/blob/master/src/XrdPss/XrdPssConfig.cc#L782-L785

If `isURL` is true and there is no `:`, then `val` is set to `nullptr` in line 784 but then in line 785, the null pointer is written to.
