### ISSUE TITLE
automatically generated voms proxy key is too weak 

### ISSUE THREAD

**Issue by rcarpa** [xrootd/xrootd#2147]
In the following example , a proxy is automatically generated by xrdfs. And this newly generated proxy cannot be used on AlmaLinux 9 because the key is too weak for the default security policies. 

```
[root@034fb8ac52bc rucio]# rm -f /tmp/x509up_u0 
[root@034fb8ac52bc rucio]# env | grep X509
X509_USER_CERT=/opt/rucio/etc/usercert.pem
X509_USER_KEY=/opt/rucio/etc/userkey.pem
[root@034fb8ac52bc rucio]# xrdfs xrd1:1094 query config xrd1:1094
231213 08:23:40 729 cryptossl_X509CreateProxy: Your identity: /CN=Rucio User
xrd1:1094

[root@034fb8ac52bc rucio]# cat /tmp/x509up_u0 | openssl rsa -text -noout | grep Private-Key
Private-Key: (512 bit, 2 primes)
```

I wonder if it's due to this line of code, but I didn't dig far into debugging:
https://github.com/xrootd/xrootd/blob/730df73734e3d3f6fd09714c0b4812f0efb67bd6/src/XrdSecgsi/XrdSecProtocolgsi.cc#L152

**Comment by amadio** [comment]
Thank you for the bug report! However, this is already fixed in master (#2117) and will be released early next year with XRootD 5.7.
