### ISSUE TITLE
Deletion of github.com/xrootd/xrdcl-http

### ISSUE THREAD

**Issue by clelange** [xrootd/xrootd#2153]
I found that when trying to build ROOT 6.22.08 from source on CentOS7, `cmake` fails when trying to clone https://github.com/xrootd/xrdcl-http:

```shell
[...]
-- Could NOT find VOMS (missing: VOMS_LIBRARY VOMS_INCLUDE_DIR) 
[I] Determining version from git
-- Submodule update
Submodule 'src/XrdCeph' (https://github.com/xrootd/xrootd-ceph) registered for path 'src/XrdCeph'
Submodule 'src/XrdClHttp' (https://github.com/xrootd/xrdcl-http) registered for path 'src/XrdClHttp'
Cloning into 'src/XrdCeph'...
Submodule path 'src/XrdCeph': checked out 'fcd63a2c239c6f1d370e3b2d2e57235af11bf176'
Cloning into 'src/XrdClHttp'...
fatal: could not read Username for 'https://github.com': No such device or address
Clone of 'https://github.com/xrootd/xrdcl-http' into submodule path 'src/XrdClHttp' failed
CMake Error at CMakeLists.txt:69 (message):
  git submodule update --init failed with 1, please checkout submodules
```

I know that this is in principle a ROOT bug but it could be fixed by restoring the repository (and archiving it instead of deleting it entirely). Could you please look into that?

**Comment by clelange** [comment]
Small correction: This actually seems related to XRootD itself, using version 4.12.3. Would be fixed by restoring the repository mentioned above.

**Comment by amadio** [comment]
We decided to make it private to avoid issues filed against it, because it was merged back into the main repository and no longer needed. However, since ROOT  still need to clone older versions of XRootD that have it as a git submodule, I made it public again and archived it instead. Thanks for reporting this!

**Comment by clelange** [comment]
Thank you very much!
