### ISSUE TITLE
Add ability for server to bind to Unix domain socket

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2158]
For writing unit/integration tests against XRootD, it would be immensely convenient if we could have protocols bind to a Unix domain socket instead of a TCP socket.  A domain socket avoids potential port conflicts or other unit test running in parallel accidentally interacting with the XRootD-based process.

One potential way of doing this would be through the `xrd.port` directive.  It could be extended to say:
```
xrd.port /foo/bar/domain.sock
```

**Comment by abh3** [comment]
This is a fairly monumental task. The best we ocould concievably offer is a directive that maps a port number to a unix domain socket (e.g. xrd.portmap <port> <path>) and the specified path would have to exist (i.e. it needs to be pre-created as a tcp named socket). This sounds like a lot of work for all parties. Generally, if you simply pick a port number in the high range you shouldn't get a conflict (well usually not). Given the constraints here is this still relevant?

**Comment by amadio** [comment]
I've played around with using `xrd.port any` for testing, then detecting the port by reading it in the log file, which works ok to avoid port conflicts without having to create too much work on the code itself, which could also create new problems. The only drawback is there's no equivalent for HTTP. Alternatively, we could add a function in CMake to find a random unused port and use that for testing. Using one of these two approaches will probably make binding unix domain sockets unnecessary.

**Comment by bbockelm** [comment]
Two thoughts:

1.  Could we simplify the implementation by having Xrootd implement the systemd socket passing protocol?  That would cause XRootD to adopt a given file descriptor as its socket and leave it as an "exercise to the user" on how to create the socket in the first place.
2. For Pelican unit tests, we ended up using something akin to `xrd.port any` (which allocates a random available port) followed by scraping the logfile to determine the allocated port.  Log scraping is distasteful for obvious reasons -- log line format shouldn't be considered part of the API!  Could xrootd instead drop a file indicating what port it has bound to (just write the port number into the file)?

The second approach would probably require minimal changes compared to domain sockets and avoid port conflicts for many unit tests running concurrently.  It doesn't implement the original idea but would solve the motivating case.

**Comment by bbockelm** [comment]
@amadio - for HTTP, I believe the following works:

```
xrd.protocol http:any libXrdHttp.so
```

no?

At least, reading the Pelican code, I believe that's what we're doing.

**Comment by abh3** [comment]
Correct, from the documentation on the xrd.protocol ditective, the notes say:
7)      A port of any assigns an arbitrary port number to the protocol.

**Comment by bbockelm** [comment]
Closing this out as stale.

Still think it's a good idea - it would solve the fact multiple XRootD tests can't currently run in parallel.  However, with the workaround described above in place in the Pelican unit tests, someone else can reopen if they want to tackle it.
