### ISSUE TITLE
Deadlock in XrdCl when files are deleted from the callback

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#216]
Here's a simplified case of a deadlock we saw in production in CMS (see https://github.com/bbockelm/cmssw/commit/ac0156350d2aa2539cf91ad2ec5f7318dd520807 for the full case, which involved a third mutex).

Thread 1:
- FileTimer::Run holds FileTimer::pMutex
- FileStateHandler::Tick wants to take the FileStateHandler::pMutex

Thread 2:
- FileStateHandler::OnStateError holds the FileStateHandler::pMutex lock
- User callback is invoked, deletes an XrdCl::File object
- ~FileStateHandler calls FileTimer::UnRegisterFileObject which tries to get the FileTimer::pMutex.

This hasn't been seen in production (yet) but seems plausible.

**Comment by ljanyst** [comment]
Yes, error callbacks should be moved to the worker thread pool. A good starting task for my successor. :)

**Comment by bbockelm** [comment]
@abh3 - any thoughts on where to assign this?

It should be possible to trigger this deadlock when using XrdCl from a single-thread.

**Comment by ljanyst** [comment]
Well, you have not seen it occurring because the lock in the FileStateHandler::Tick is acquired and immediately released. I will clean this up.

**Comment by ljanyst** [comment]
Actually, the fact that this lock is misplaced may be the exact reason for #163 and the problems that @abh3 is seeing...

**Comment by abh3** [comment]
Hi Lukasz,

Could you at least outline what the solution here should be so that if you don't get around to fixing this we can at least have a good starting point.

Andy

**Comment by abh3** [comment]
Hi Brian,

We can assign this to Elvin for now.

Andy

**Comment by bbockelm** [comment]
Doesn't f9442d764162503e551438e335fc27beae599a56 fix this?

**Comment by abh3** [comment]
Well, it likely fixes the deadlock but may introduce a possible loop hole for a timed out object to escape (though, frankly I don't see how).

**Comment by bbockelm** [comment]
We have hit another deadlock that has a similar signature.  From Chris Jones:

```
Thread 1
	FileStateHandler::VectorRead takes FileStateHandler lock
	Stream::Send tries to take Stream lock
	
Thread 5
	FileTimer::Run takes FileTimer lock
	FileStateHandler::Tick tries to take FileStateHandler
	
Thread 6
	Stream::OnReadTimeout takes Stream lock
	DelayedClose::HandleResponseWithHosts  (this is callback code in CMSSW); this deletes a File object, which eventually calls
	FileTimer::UnRegisterFileObject tries to take FileTimer lock
```

**Comment by abh3** [comment]
This is related to issue 257 and solving that one would solve this one. I had a similar problem and the ultimate solution was not to do anything significant in the callback but just hands the work off to another thread and return. This keeps the callback code from interfering with the callback mechanism. I think that Michal, Elvin, and I decided that all callbacks need to go to the worker thread pool, though in some cases care has to be taken that whatever the callback is given remains valid.

**Comment by simonmichal** [comment]
@bbockelm : I moved all the callback handling to the thread-pool. Is there a chance you could test if it fixes this issue?

Thanks,
Michal
