### ISSUE TITLE
Wrong port used by meta-manager cmsd in v4.1.1

### ISSUE THREAD

**Issue by klabattermann** [xrootd/xrootd#217]
In v4.1.1 a cmsd that is configured as a meta-manager will use the the wrong port if it is using the following directives:
 > all.role meta manager
 > all.manager meta <hostname>:8551
 > xrd.port 18761

The cmsd is using the port specified by *xrd.port* instead of the one from *all.manager*. A cmsd configured as a manager using the corresponding config as above will use the proper port.

**Comment by abh3** [comment]
This was fixed in patch 1ea97d1d and will appear in release 4.2.0 The bypass for this problem is to either not use the xrd.port directive or if it must be used to steer the xrootd port choice to say:

xrd.port 18761 if exec xrootd
