### ISSUE TITLE
Do not enumerate supported protocols (maybe ?)

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2171]
In both XCache and `xrdcp`, there's a list of supported protocols (think: `http://`, `https://`, `xroot://`, etc) and a check to ensure the URLs passed are on the list.

However, due to the XrdCl plugin mechanism, it's possible to add new protocols that aren't on this hardcoded list.

I'm developing a new "protocol", `pelican://`, as a part of a separate project (in reality, it's a small twist on HTTPS provided by libcurl).  The only way to make it work is to add a small patch along these lines:

```
--- a/src/XrdPss/XrdPssUtils.cc
+++ b/src/XrdPss/XrdPssUtils.cc
@@ -42,7 +42,8 @@ namespace
    struct pEnt {const char *pname; int pnlen;} pTab[] =
                {{ "https://", 8},  { "http://", 7},
                 { "roots://", 8},  { "root://", 7},
-                {"xroots://", 9},  {"xroot://", 8}
+                {"xroots://", 9},  {"xroot://", 8},
+                {"pelican://", 10}
                };
    int pTNum = sizeof(pTab)/sizeof(pEnt);
    int xrBeg = 2;
```

Instead of shipping small patches or extending the lists in a future XRootD release, can we simply remove the hardcoded lists and let the XrdCl library manage things?

**Comment by abh3** [comment]
There are a couple of reasons we do this: 1) to issue config-time errors which are more direct and understandable than run-time errors with not necessarily a relevant error message, and 2) allowing certain transformations of the protocol name in forwarded URLs (i.e. we need to know the validity ahead of time). Now, we could allow additions to the table via a config directive but that directive would need to be specified ahead of any use of the protocol name (not a deal breaker). On the other hand, given that protocol additions occur maybe once every 5 or so years, requiring the registration of the protocol in the table is hardly onerous.

**Comment by amadio** [comment]
Merged into `devel`, so I'm closing this, it will be in 5.7.0 when it comes out. Thanks!
