### ISSUE TITLE
stat permissions required to create or modify files

### ISSUE THREAD

**Issue by Jo-stfc** [xrootd/xrootd#2185]
Hi, 
stat permissions are needed for most operations (including write and deletes), but scitokens currently includes them only in the read scope, meaning write operations need read scopes added to it.
I've made a PR to amend this
https://github.com/xrootd/xrootd/pull/2184

**Comment by Jo-stfc** [comment]
an additional related issue was found on a VO workflow. According to the WLCG token spec, for storage.create and storage.modify scopes:
`This includes renaming files if the destination file does not already exist. This capability includes the creation of directories and subdirectories at the specified path, and the creation of any non-existent directories required to create the path itself (note the server implementation MUST NOT automatically create directories for a client).`

meaning if a scope is set to storage.create:/foo/bar, the same token must be able to be used to create the /foo directory.
I've added a commit in the PR addressing this

**Comment by Jo-stfc** [comment]
@amadio a reminder on https://github.com/xrootd/xrootd/pull/2195 that was missed from the first merge

**Comment by amadio** [comment]
Sorry, I am aware, just didn't get to it yet. I will merge it soon.

**Comment by Jo-stfc** [comment]
thanks!

**Comment by amadio** [comment]
Can I assign this issue to you as recognition for the fix? I'd also need to invite you to the project as external collaborator, which would allow you to triage tickets as well.
