### ISSUE TITLE
Compression detection in XrdOfs might disable async/read IO

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#219]
When using an OSS plug-in  using the default OFS implementation, the OFS disables asynchronous reads if 'isCompressed' is not implemented by the OSS.

I suggest the default behaviour of the OFS to assume not compressed if the detection is not implemented (-EISDIR response by XrdOssDF).

```
XrdOfs.cc:
// Set compression values and activate the handle
//
if (oP.fP->isCompressed())
   {oP.hP->isCompressed = 1;
   dorawio = (open_mode & SFS_O_RAWIO ? 1 : 0);
}

```
```
XrdOss.hh:
virtual int isCompressed(char *cxidp=0) {(void)cxidp; return -EISDIR;}
```
Is there actually anything implemented with compression?

**Comment by abh3** [comment]
Quite correct; thank you Andreas for pointing this out. A patch is on it's way. Oh yes, I don't know of anyone who has implemented compression. I still have all the archived code that mates with the oss that implements random access compressed files from the Objectivity days. It was pretty good for Objectivity files. However, root files don't compress that well so few people are interested in compressing files.
