### ISSUE TITLE
Re-resolve IP address when reconnecting a socket (needed when running under Kubernetes)

### ISSUE THREAD

**Issue by amadio** [xrootd/xrootd#2204]

**Comment by amadio** [comment]
The client already does it:

https://github.com/xrootd/xrootd/blob/619e93fe896f23ac04fd424ac5223c2443fec296/src/XrdCl/XrdClStream.cc#L235-L292

**Comment by abh3** [comment]
This is a duplicate of issue #2289 so I am closing this one.

**Comment by amadio** [comment]
Removing milestone and closing as not planned. #2289 was a bug in CTA, this is not a duplicate of that one, but the address *does* get re-resolved when needed by the client in any case.
