### ISSUE TITLE
CC7 logrotate cron job is too noisy (sends mail)

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#221]
on Centos7, the supplied logrotate entry causes a mail to be sent:

On 03/25/2015 03:25 AM, Anacron wrote:> /etc/cron.daily/logrotate:
> 
> spawn/bin/sh -c echo ping > /var/log/xrootd/fed/.cmsd.log
> spawn/bin/sh -c echo ping > /var/log/xrootd/fed/.xrootd.log

Comes straight from the RPM:

[root@xrdcmsglobal01 ~]# rpm -qf /etc/logrotate.d/xrootd 
xrootd-server-4.1.1-1.el7.x86_64
[root@xrdcmsglobal01 ~]# rpm -Vvf /etc/logrotate.d/xrootd | grep /etc/logrotate.d/xrootd
.........  c /etc/logrotate.d/xrootd

(whatever this "ping" does).

**Comment by abh3** [comment]
The ping causes xrootd/cmsd to close and reopen the log file, creating it if necessary. One would normally use a signal (e.g. SIGHUP) and that is all well and fine except for daemons that can be outfitted with custom plugins. We have found that some plugins use signals for other things and using them for log file rotation conflicts with those plugins leading to all sorts of other problems. So, the safest way to do this is via a dedicated pipe. A message appearing on the pipe means close/open the log file.

**Comment by ljanyst** [comment]
I am not sure I can do anything about it. Is there a way you can configure logrotate on your side not to echo the `postrotate` scriptlets?

**Comment by ljanyst** [comment]
As discussed, I will silence the output from `expect`.
