### ISSUE TITLE
XrdMacaroons should support "trace all -debug"

### ISSUE THREAD

**Issue by amadio** [xrootd/xrootd#2224]
The main XRootD config mentions "Each option may be optionally prefixed by a minus sign to turn off the setting", and `XYZ.trace all -debug` seems a common directive pattern.

However, the XrdMacaroons plugin does not accept
```
macaroons.trace  all -debug
```
and fails to load:
```
240323 21:01:59 time=1711224119.764940 func=GetHttpExtPlugin         level=INFO  logid=3566c9a2-e950-11ee-bbc4-a4bf01795678 unit=mgm@eoshome-i04-vega.cern.ch:1094 tid=00007f9e486678c0 source=EosMgmHttpHandler:646          tident=<service> sec=      uid=0 gid=0 name= geo="" msg="loading HttpExtHandler(XrdMacaroons) plugin" path="libXrdMacaroons-5.so"
Plugin loaded XrdMacaroons 5.6.6 from httpexthandler libXrdMacaroons-5.so
240323 21:01:59 186134 sysInitialize: Creating new Macaroon handler object
=====> macaroons.secretkey /etc/eos.macaroon.secret
240323 21:01:59 186134 sysConfig: macaroons.trace encountered an unknown directive: -debug
=====> macaroons.trace all -debug
240323 21:01:59 186134 sysConfig: Generation of Macaroon handler failed Macaroon handler config failed.
```
See also original ticket at https://its.cern.ch/jira/browse/EOS-6104

**Comment by abh3** [comment]
Well, yes that is true but we are getting into Pandora's territory. Plugin writers use their own thinking when it comes to various directives and, I agree, it leads to inconsistency. The Macaroon plugin is only one of many that have this kind of inconsistency. I suspect the solution here is to better document the inconsistency and leave well enough alone.

**Comment by amadio** [comment]
At least for the trace option of each plugin, if it's not too difficult, I think having consistent behavior would be appreciated by users.

**Comment by abh3** [comment]
I'm not against that but it would mean going to each externally contributed plugin and retrofitting the code. Not impossible but time consuming if only because of the number of them.
________________________________
