### ISSUE TITLE
[XrdTpcTPC] Add new option to allow  for unrestricted redirection

### ISSUE THREAD

**Issue by ccaffy** [xrootd/xrootd#2228]
As discussed in issue [2221](https://github.com/xrootd/xrootd/issues/2221) , we need to add a configuration allowing administrators to allow that the clients credentials are passed to the hosts towards which they are redirected.

We will add a new option `http.tpcallowunrestrictedredirect on/off` (the names are subject to change) that by default will be disabled.

If the option is enabled, we will set the option https://curl.se/libcurl/c/CURLOPT_UNRESTRICTED_AUTH.html to curl for HTTP TPC transfers: In `XrdTpcState.cc:75` for example.

**Comment by ccaffy** [comment]
> > We will add a new option `http.tpcallowunrestrictedredirect on/off` (the names are subject to change) that by default will be disabled.
> 
> I hope we can find a shorter name for this :-) Let me suggest `http.tpc fcreds all/trusted`, similar to `ofs.tpc fcreds`. See https://xrootd.slac.stanford.edu/doc/dev56/ofs_config.htm#_Toc136617306

I like this option name, thanks @amadio !

**Comment by ccaffy** [comment]
I'll do `http.tpc fcreds on/off` as it is clear at the first sight that if that option is `on`, the credentials will be forwarded :)

**Comment by amadio** [comment]
You could also do it the same way as `ofs.tpc`, where `fcreds` already means `fcreds on`, and the default is off.

**Comment by ccaffy** [comment]
Sure, yes, it will allow to simplify the parsing of this command...

**Comment by amadio** [comment]
To make things clear, we normally use
```
ofs.tpc fcreds ?gsi =X509_USER_PROXY
```
to forward delegated credentials using gsi authentication. We could have
```
http.tpc fcreds ?ztn =BEARER_TOKEN
```
for forwarding tokens while reusing the same code for `ofs.tpc`.

**Comment by ccaffy** [comment]
But that's not the goal of the issue right? we just want an option to pass the credentials to the redirected host whatever the authentication is, right?

**Comment by amadio** [comment]
Yes, but if the code for parsing is reused, it creates more consistency between `ofs.tpc` and `http.tpc`, while also allowing to put the contents of the token in a file using 4ef0f2f388f877d0715ffc345afe1b988398749b. What do you think?

**Comment by ccaffy** [comment]
The code is not reused at all, I just use the same parameters name...
