### ISSUE TITLE
Typo in g-stream documentation

### ISSUE THREAD

**Issue by haoming29** [xrootd/xrootd#2229]
In https://xrootd.slac.stanford.edu/doc/dev56/xrd_monitoring.htm#_Toc138968524,  in the diagram to show the g-stream packet structure, it says `XrdXrootdMonMonHeader` while it should be `XrdXrootdMonHeader`:

```
struct XrdXrootdMonGS;
      {struct XrdXrootdMonMonHeader hdr;
       int       tBeg; // UNIX time of first entry
       int       tEnd; // UNIX time of last  entry
       kXR_int64 sID;  // Provider identification
      }
*
* 1 or more newline separated ASCII text strings with the last
* such string ending with a null byte.
*
```

**Comment by abh3** [comment]
Thank you for reporting this. It will be corrected.
________________________________
From: Haoming Meng ***@***.***>
Sent: Thursday, March 28, 2024 9:57 AM
To: xrootd/xrootd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xrootd/xrootd] Typo in g-stream documentation (Issue #2229)


In https://xrootd.slac.stanford.edu/doc/dev56/xrd_monitoring.htm#_Toc138968524, in the diagram to show the g-stream packet structure, it says XrdXrootdMonMonHeader while it should be XrdXrootdMonHeader:

struct XrdXrootdMonGS;
      {struct XrdXrootdMonMonHeader hdr;
       int       tBeg; // UNIX time of first entry
       int       tEnd; // UNIX time of last  entry
       kXR_int64 sID;  // Provider identification
      }
*
* 1 or more newline separated ASCII text strings with the last
* such string ending with a null byte.
*

**Comment by abh3** [comment]
Updated documentation available.
