### ISSUE TITLE
IPV6/IPV4 host name mismatch fails locate 

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#224]
I am using a CERN OpenStack machine with XRootD 4.1.1.

These machines have by default names like:
IPV4 <name>.cern.ch
IPV6 <name>.ipv6.cern.ch

The OFS fails the 'fsctl' command and returns ENETUNREACH:
```
if ((Resp1Len = myIF->GetDest(pbuff, sizeof(pbuff), ifType, retHN)))
           {einfo.setErrInfo(Resp1Len+3, (const char **)Resp, 2);
            return SFS_DATA;
           }
return Emsg(epname, einfo, ENETUNREACH, "locate", Path);
```

Running with -I v4 bypasses the problem.

**Comment by ljanyst** [comment]
Just to clarify: the ethernet interface has both a public IPv6 and a public IPv4 address assigned.

**Comment by abh3** [comment]
Hi Andreas,

Would it be possible to get the value  of "ifType"? If you can get that 
then you can lso dump out the contents of myIF. The only way this can 
happen is if there is an incompatability between the requestor and how the 
node is configured, which should not be the case here. So, I suspect what 
the expected config s is not what the real config is.

Andy

**Comment by abh3** [comment]
Just following up, any more news on this or should this be closed?

**Comment by abh3** [comment]
OK, no additional information here so I will close this ticket.
