### ISSUE TITLE
TPC issue via davs:// to redirector with multiple independent servers behind it

### ISSUE THREAD

**Issue by MarcusEbert** [xrootd/xrootd#2241]
Using davs:// in a TPC via gfal-copy/davix-cp results in a high failure rate when the system consist of a redirector and multiple servers each with their own local file system. Issue described below happens when the xrootd install is the destination and the TPC is done in pull mode (xrootd is the active site).

Test system to replicate the issue we saw in the production system:
- one redirector and two server processes, all on elephant36.heprc.uvic.ca with different ports and different oss.localroot
- ports on the machines (cmsd/xrd): redirector (1095/1094), server1 (1093/1092), server2 (1091/1090)
- file does not exist on any of the servers yet; destination directory /TMP/belle3/ exists in the file system of server1 but not in the filesystem of server2; /TMP exists in both file systems

command used: 
gfal-copy -p -f --copy-mode pull https://belle2-webdav-analysis-data.cc.kek.jp:8443/disk/belle/TMP/belle/Raw/e0012_8GBTest/physics/r04420/sub00/physics.0012.4420.8GBTest.f00000.root https://elephant36.heprc.uvic.ca:1094/TMP/belle3/some_test_file4

Error: TRANSFER ERROR: Copy failed (3rd pull). Last attempt: copy HTTP 400 : Server Error
 
From the redirector log: the copy request fails since on server2 it does not exist yet. 

In case of having the directory not existent on any server, there would be an additional step in between to create it, but that again does not prevent the final copy redirect to go to a server which does not have the directory yet. Failure rate is ~50% with 2 equal servers. 

Logs from the redirector and the servers are attached.  

Since the server that gets the copy command in the end checked on the permissions of doing the copy and only fails because the full path doesn't exist yet; shouldn't the server itself just create the directory instead of failing to the client?

[cmsd_redirector.log](https://github.com/xrootd/xrootd/files/15030268/cmsd_redirector.log)
[xrd_server2.log](https://github.com/xrootd/xrootd/files/15030269/xrd_server2.log)
[xrd_server1.log](https://github.com/xrootd/xrootd/files/15030270/xrd_server1.log)
[xrd_redirector.log](https://github.com/xrootd/xrootd/files/15030271/xrd_redirector.log)
(server1 had a bit more debug enabled than server2; let me know if you want me to redo it with different debug output)

**Comment by MarcusEbert** [comment]
Is there any progress on that issue?  Currently, this prevents to use davs:// on a system with multiple independent (==non-shared file system) servers behind a redirector when TPC transfers via pull are needed. (We may run out on our single server mid-June and it would be great if we could extend the space with additional servers by then; push unfortunately doesn't work in the experiment's setup)

**Comment by MarcusEbert** [comment]
Thanks for the good news!  We'll try it out when 5.7.0 comes out.

**Comment by amadio** [comment]
Fixed by f564c61990e6beb73d3d2a3e042e4ed0471a4c2d in devel.

**Comment by MarcusEbert** [comment]
@amadio I need to download devel and compile it to test?

**Comment by amadio** [comment]
No, I just launched a build of the RPMs for the devel branch. You can download the pre-built RPMs from here: https://github.com/xrootd/xrootd/actions/runs/9618617477 and install them with dnf. Just go into the right subdirectory and use `dnf install *.rpm`.

**Comment by MarcusEbert** [comment]
Thanks! Will do so; probably early next week.

**Comment by amadio** [comment]
Very good, thank you for confirming it. Closing!
