### ISSUE TITLE
Run: [FATAL] TLS error: resource temporarily unavailable

### ISSUE THREAD

**Issue by rahmans1** [xrootd/xrootd#2251]
We are using a xrootd client built into our container with the following config using spack:

xrootd@5.6.9+client_only~davix+http~ipo~krb5+python+readline+scitokens-cpp build_system=cmake build_type=Release cxxstd=20 generator=make patches=0d03eed

However, attempting to write to our site results in the following error:

> xrdcp --version 
v5.6.9
> htgettoken -v -a <vault> -i eic
Storing bearer token in /tmp/bt_u0
>  xrdcp install.sh xroots://<site>//eic/eic2/EPIC/xrdtest/
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] TLS error: resource temporarily unavailable: Unable to connect to <site>; error_ssl (destination)

I have tested it on another machine outside our container environment and it seems to be working fine. So, it does not seem like a site specific issue but something to do with how we have configured xrootd within our container. 
> xrdcp --version
v5.6.8
> htgettoken -v -a <vault> -i eic
Storing bearer token in /run/user/8323/bt_u8323
> xrdcp install.sh xroots://<site>//eic/eic2/EPIC/xrdtest/
[13.1kB/13.1kB][100%][==================================================][13.1kB/s]  
 
Is there any insight into this issue?

Thanks in advance.

**Comment by amadio** [comment]
Do you have the necessary CA certificates installed in your container?

**Comment by rahmans1** [comment]
Seems like the CA certificates were indeed outdated in the container and after fixing that issue, I see a new error. Is it because xrootd is failing to locate the bearer token. Is there a environment variable that can be fixed to point it to the token location?
jug_xl> rahmans@ASUS:~$ xrdcp hello.txt xroots://<server>//eic/eic2/EPIC/xrdtest/
[0B/0B][100%][==================================================][0B/s]
Run: [FATAL] Auth failed: No protocols left to try (destination)

The bearer token is at /tmp/bt_u0

**Comment by amadio** [comment]
Yes, you can set either `BEARER_TOKEN` to the contents of the token, or `BEARER_TOKEN_FILE` to the name of the file that contains it.

**Comment by rahmans1** [comment]
Setting BEARER_TOKEN to the contents of the token did the job 👍🏽 
```
jug_xl> rahmans@ASUS:~$  htgettoken -v -a <vault> -i eic
Storing bearer token in /tmp/bt_u0
jug_xl> rahmans@ASUS:~$ export BEARER_TOKEN=$(cat /tmp/bt_u0)
jug_xl> rahmans@ASUS:~$ touch hello.txt
jug_xl> rahmans@ASUS:~$  xrdcp hello.txt xroots://<server>//eic/eic2/EPIC/xrdtest/
[0B/0B][100%][==================================================][0B/s]
```
I also tried the other method with BEARER_TOKEN_FILE but that one didn't work
```                                                  
jug_xl> rahmans@ASUS:~$  htgettoken -v -a <vault> -i eic
Storing bearer token in /tmp/bt_u0
jug_xl> rahmans@ASUS:~$ export BEARER_TOKEN_FILE=/tmp/bt_u0
jug_xl> rahmans@ASUS:~$ touch hello2.txt
jug_xl> rahmans@ASUS:~$ xrdcp hello2.txt xroots://<server>//eic/eic2/EPIC/xrdtest/
[0B/0B][100%][==================================================][0B/s]
Run: [FATAL] Auth failed: No protocols left to try (destination)
```                    

Regardless, I am closing this issue. Thanks a lot for the help.

**Comment by amadio** [comment]
Strange, according to the [documentation](https://xrootd.slac.stanford.edu/doc/dev56/sec_config.htm#_Toc119617461), 
it should have worked. I will see if there is a bug there and fix it.

**Comment by olifre** [comment]
An easy way to have the `BEARER_TOKEN_FILE` ignored is if permissions on said file are too extensive. Then `XRootD` silently ignores it (on default loglevel). 
You may want to run `XRD_LOGLEVEL=Dump xrdcp ...` and check the output, then XRootD will log whether the file was ignored for that reason.

**Comment by wdconinc** [comment]
> Then XRootD silently ignores it (on default loglevel).

Would it be possible to increase the log level to warning when BEARER_TOKEN_FILE is ignored due to permissions?Looking at https://github.com/xrootd/xrootd/blame/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/src/XrdSecztn/XrdSecProtocolztn.cc#L442 it seems that the message should have been printed to std::cerr so I am not sure I understand why it is not showing up.

**Comment by amadio** [comment]
> > Then XRootD silently ignores it (on default loglevel).
> 
> Would it be possible to increase the log level to warning when BEARER_TOKEN_FILE is ignored due to permissions?

Yes, that is a good idea, I will do that. Thanks for the suggestion.
