### ISSUE TITLE
Intermittent SSL errors with version 5.6.9 on alma 9

### ISSUE THREAD

**Issue by jmarra13** [xrootd/xrootd#2252]
Hi,

This week I installed version 5.6.9 on my servers running on Alma 9 and this error shows up from time to time:

`240425 20:30:13 8919 XrdTLS: root.640148:42@vocms036.cern.ch 40766EF8D37F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:320:`

After googling a bit I saw that error is because openssl 3.0.x changed the way it deal with clients abruptly closing connections. After changing line 594 /src/XrdTls/XrdTlsContext.cc from

`  static const int sslOpts = SSL_OP_ALL | SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3
                            | SSL_OP_NO_COMPRESSION ;`

to

`  static const int sslOpts = SSL_OP_ALL | SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3
                            | SSL_OP_NO_COMPRESSION | SSL_OP_IGNORE_UNEXPECTED_EOF;`

and compiling again the errors stopped. Since I'm not a developer and I just wanted a quick fix for my problem I decide to report here and maybe help others facing the same issue.If you known other options to fix this, maybe a configuration knob, I will appreciate a lot.

**Comment by amadio** [comment]
Interesting, thank you for the bug report. We will consider adding this to 5.7.0 which will be released soon.
