### ISSUE TITLE
[Doc] Document +notls and http.tpc auth fcreds

### ISSUE THREAD

**Issue by ccaffy** [xrootd/xrootd#2257]
Hi @abh3 ,

Just so we do not forget when we will create 5.7.0.

The following 2 PRs ([xrootd/xrootd#2232](https://github.com/xrootd/xrootd/pull/2232) and [xrootd/xrootd#2253](https://github.com/xrootd/xrootd/pull/2253) come with new flags, therefore they need to be documented.

1. Can you please add to the documentation the new `http.exthandler name +notls path parm` where `+notls` can be specified by adminstrators to allow XrdHttp to load the corresponding external handler despite not having TLS configured.

2. Can you please add to the documentation the new `http.auth tpc fcreds`, probably under https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc152596888 ?
`http.auth tpc fcreds` allows the active server in the HTTP TPC transfer to forward the client credentials to the redirection server.

Thanks in advance!

Cheers,
Cedric

**Comment by abh3** [comment]
Thanks Cedric, Will do. Andy
________________________________
From: ccaffy ***@***.***>
Sent: Friday, May 3, 2024 8:09 AM
To: xrootd/xrootd ***@***.***>
Cc: Andrew Hanushevsky ***@***.***>; Mention ***@***.***>
Subject: [xrootd/xrootd] [Doc] Document +notls and http.tpc auth fcreds (Issue #2257)


Hi @abh3<https://github.com/abh3> ,

Just so we do not forget when we will create 5.7.0.

The following 2 PRs (xrootd/xrootd#2232<https://github.com/xrootd/xrootd/pull/2232> and xrootd/xrootd#2253<https://github.com/xrootd/xrootd/pull/2253> come with new flags, therefore they need to be documented.

  1.  Can you please add to the documentation the new http.exthandler name +notls path parm where +notls can be specified by adminstrators to allow XrdHttp to load the corresponding external handler despite not having TLS configured.

  2.  Can you please add to the documentation the new http.auth tpc fcreds, probably under https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc152596888 ?
http.auth tpc fcreds allows the active server in the HTTP TPC transfer to forward the client credentials to the redirection server.

Thanks in advance!

Cheers,
Cedric

**Comment by abh3** [comment]
If you look at the latest documentation you will see this is fixed:
auth: https://xrootd.slac.stanford.edu/doc/dev57/xrd_config.htm#_Toc171719991
exthandler: https://xrootd.slac.stanford.edu/doc/dev57/xrd_config.htm#_Toc171720007
