### ISSUE TITLE
XrdTLS report ssl error when user tries to xrdcp in the glideinWMS job

### ISSUE THREAD

**Issue by z4027163** [xrootd/xrootd#2258]
Dear experts,

   After the upgrade of the xrootd configuration from:
   
```
http.cadir /etc/grid-security/certificates
http.cert /etc/grid-security/xrd/xrdcert.pem
http.key /etc/grid-security/xrd/xrdkey.pem
```

to 

```
sec.protocol ztn
xrd.tlsca certdir /etc/grid-security/certificates
xrd.tls /etc/grid-security/xrd/xrdcert.pem /etc/grid-security/xrd/xrdkey.pem
xrootd.tls capable all
```
The xrdcp fails when I try to submit jobs via a glideinWMS whose pilot is using GSI authentication. From the user side, the xrdcp failed because of the error:
`Run: [FATAL] TLS error: Unable to use key file /condor/execute/dir_9386/glide_WR8Nw4/hostkey.pem; does not exist. (source)`

From the xrootd server side, the error report is:

```
240505 13:58:00 3390419 anon.0:36@t3btch042 TLS_Accept: Accepting a TLS connection...
240505 13:58:00 3390419 XrdTLS: anon.0:36@t3btch042 TLS error rc=-1 ec=1 (error_ssl) errno=0.
240505 13:58:00 3390419 XrdTLS: anon.0:36@t3btch042 4016375B587F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:320:

240505 13:58:00 3390419 XrdLinkXeq: TLS connection from anon.0:36@t3btch042 failed; error_ssl
```

However, any local xrdcp or xrdcp directly through condor job (no glidein involved) is working. I am wondering what is needed so this SSL will success? Why it tries to look for a hostkey.pem, since all I have is a user x509 certificate for the access check. 

Sincerely,
Zhangqier Wang from MIT

**Comment by amadio** [comment]
Do you have `X509_USER_KEY` set in the environment, maybe? It would help to have the log of the client with `XRD_LOGLEVEL=Debug` or `Dump` (better). Please just make sure there are no credentials (e.g. tokens) in the log when pasting/attaching here. Note that enabling ZTN forces the server to require TLS from clients (see note number 2 in the [online documentation](https://xrootd.slac.stanford.edu/doc/dev56/sec_config.htm#_Toc119617460)), so try also disabling ZTN and compare the logs for transfers using `root://` and `roots://`. Finally, what versions of client/server are you using?

**Comment by z4027163** [comment]
Dear experts,

   Thanks for the reply.  I don't have X509_USER_KEY defined via condor. In condor job, it defines `X509_USER_PROXY` with the user x509proxy. 
   I have tested several scenarios:
   1. when using glidienWMS, xrdcp fails even when I remove  `sec.protocol ztn` from xrootd server. Using `root://` and `roots://` both failed (the output log of XRD_LOGLEVEL=Debug are attached). 
[log_root_fail.txt](https://github.com/xrootd/xrootd/files/15242075/log_root_fail.txt)
[log_roots_fail.txt](https://github.com/xrootd/xrootd/files/15242076/log_roots_fail.txt)
   They are showing the same error which starts with:
```
   [2024-05-07 19:00:26.316649 -0400][Debug  ][AsyncSock         ] [submit30.mit.edu:1094.0] TLS hand-shake exchange.
[2024-05-07 19:00:26.321058 -0400][Error  ][TlsMsg            ] [TLS_Context:] Unable to use key file /condor/execute/dir_21327/glide_aCoM7Y/hostkey.pem; does not exist.
[2024-05-07 19:00:26.321648 -0400][Error  ][AsyncSock         ] [submit30.mit.edu:1094.0] Socket error while handshaking: [FATAL] TLS error
[2024-05-07 19:00:26.321671 -0400][Debug  ][AsyncSock         ] [submit30.mit.edu:1094.0] Closing the socket
```
 2. When not using glideinWMS, when I directly log into worknode as condor pilot user (bosco_tier3), and use my x509proxy with the defined `X509_USER_PROXY`, it works.

**Comment by amadio** [comment]
I don't know why the client is trying to use this file as key. Have you printed the environment and checked that no environment variable is pointing to this file? That is not a standard path, so something must be set that makes the client try to use the file as a key. Maybe try something like `env | grep hostkey` before the xrdcp command in your job and let's see what is in the output. The debug log doesn't help much in this regard, unfortunately.

**Comment by z4027163** [comment]
Hi,

   Thanks. It is resolved now. 
    It turns out there is a default `X509_USER_KEY` set up in the glidein that leads to the failure.  In the old xrootd configuration, with 
```
http.cadir /etc/grid-security/certificates
http.cert /etc/grid-security/xrd/xrdcert.pem
http.key /etc/grid-security/xrd/xrdkey.pem
```
   it works even the key doesn't exist as long as it has the correct x509proxy. 
   
   In the new configuration with TLS, it fails when the key doesn't exist. The xrootd copy works once I manually unset the `X509_USER_KEY` in the execute script. 
   
   I am wondering if it's the current mechanism is desired or in the future it will change to the similar set up as before, where the authentication passes as long as x509proxy is correct. 
   
   Best,
   Zhangqier Wang

**Comment by amadio** [comment]
Thank you, I am closing this issue then. Best regards,
