### ISSUE TITLE
API compatibility break in devel

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2263]
In [this commit](https://github.com/xrootd/xrootd/commit/67680f732639fa24395e54ad4f85e2ddcdcab086), the signature for `XrdCl::FilePlugIn` changed, causing an API compatibility break.

Was that intentional?  I thought API breaks only were supposed to occur at the major release version changes.

**Comment by bbockelm** [comment]
Ah, ok, sounds good!  I thought devel currently maps to a future 5.7.0.

**Comment by abh3** [comment]
Indeed, I do see the issue here, but we have no way of doing that in devel; though Guilherme could probably figure out how to do it. I'll bring it up as it does present additional challenges when developing code for a non-major release.

Andy
________________________________

**Comment by amadio** [comment]
Yes, that was my thought, a recompilation should be enough in most cases. For ROOT it's sufficient, but for EOS, I needed to make matching changes in classes that used these timeouts and job ids. I assume plugins may fall on the same case as EOS. In any case, it seems like we should assess the impact more thoroughly before putting this in a release. We should not waste the opportunities a major release provides for improvements by adding only this change to it, so let's say that the commits changing job ids and timeouts will stay out of v5.7 for now (maybe they can go into 5.8 if we conclude it's fine for a minor release).

**Comment by bbockelm** [comment]
FWIW -- the thing that broke on my side wasn't the invocation of the API (where the silent promotion indeed occurs) but the declaration of the plugin (the virtual function definitions no longer matched the parent class and hence were no longer overrides).

The issue with the declaration may be fixable by providing multiple virtual functions.

**Comment by abh3** [comment]
I'd say not only may but will fix this. Yes, all the methods where the timeout changes should have the original virtual simply calling the new virtual. Those should be at the end of the class as this is a necessary evil that we don't want to highlight. I should have caught that on review but I didn't think of overrides.

Andy

________________________________
