### ISSUE TITLE
Request backport of "Timer expired" error code

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2264]
I'd like to generate some "Gateway Timeout" errors from my XCache setup, generated by my XrdCl plugin.

This requires the new `kXR_TimerExpired` error code and corresponding XrdHTTP codes introduced here: https://github.com/xrootd/xrootd/commit/a5566f5d5a3ee47a760cf27a77875144689d8b96

Could that commit be backported?  If no, can just the error handling be backported (leaving the "cache-control" pieces in `devel`)?

**Comment by bbockelm** [comment]
Right -- I'm happy to create the branch + PR if, in principle, it's OK to bring the error code to the 5.x series.

**Comment by abh3** [comment]
I talked with @bbockelm about this. Given that the code in question will appear in 5.7.0 and we do not expect releasing any more 5.6.x patches prior to releasing 5.7.0, this issue will be addressed by the next release. So, I am closing this.
