### ISSUE TITLE
Bump generated XrdVERSION version in devel

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2270]
I'd like to put in a conditional compilation in my plugin code so it can be compiled against either the current version 5.x or a future 6.x (see #2263 for a case where a conditional compilation is needed).

However, when I compile the `devel` branch, the generated version number in `XrdVERSION` starts with `5`.

Is there a way to get `devel` to identify itself as the 6.x series to keep the conditional simpler?

**Comment by amadio** [comment]
The version reported by any branch is based on `git describe`, so if you just need to test something, simply creating a `v6.0` tag on your clone or fork should make `devel` identify itself as `6.x`. In CMake you can use `VERSION_GREATER` to compare with current version and choose what to do. Please let me know if you have any other questions. If what I describe is enough, we can probably close this ticket.

**Comment by amadio** [comment]
Ok, I assume the recipe suggested above is enough for you to do what you plan in your code. If not, please reopen. Thank you.
