### ISSUE TITLE
[XrdXrootDXeqPgrw] Out of bound array assignment in paged reads

### ISSUE THREAD

**Issue by Jo-stfc** [xrootd/xrootd#2287]
In https://github.com/xrootd/xrootd/blob/619e93fe896f23ac04fd424ac5223c2443fec296/src/XrdXrootd/XrdXrootdXeqPgrw.cc#L268 
The loop overshoots the size of the iovec array (1023) and tries to write into size 1024 and 1025, causing server crashes if the out of bound memory is in a protected address e.g. 0x4c. 
From an email thread with @abh3 the condition on the loop should be (i<n) to prevent this from happening.

**Comment by amadio** [comment]
Related issue: #1743

**Comment by Jo-stfc** [comment]
thanks. I'll test that change on a test host

**Comment by Jo-stfc** [comment]
yes that commit fixes it

**Comment by amadio** [comment]
@Jo-stfc Great, thank you very much for confirming!
