### ISSUE TITLE
Problems with identity/certificate during FTS tape polling calls when using XRootd with "xrd.gsiusrpxy" opaque

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#2292]
Hello,

This problem started manifesting itself on the FTS3-Public the past days, as here we have different clients interacting with the same tape storage (EOSCTAPUBLIC).

We observe that during our tape polling calls (stage poll or archive poll), if the requests are within a short time window, the identity used for the polls may be mixed. FTS sets the proxy certificate to be used via the `xrd.gsiusrpxy=<cert-file-path>`. Example:
1. Perform tape poll for (batch#1, vo#1) with `xrd.gsiusrpxy=<cert#1>`
  a. EOSCTA sees the correct certificate
2. Within a short time frame (but in the span of tens of seconds), perform second tape poll for (batch#2, vo#2) with `xrd.gsiusrpxy=<cert#2>`
  b. EOSCTA reports seeing the previous `<cert#1>` certificate and maps us to the wrong identity

We've investigated this problem quite a bit on our side. One suggestion we had was to add the username when creating the new batch. Now, for the `query prepare` command, we craft the endpoint URL as follows:
`root://fts<counter-id>@eosctapublic.cern.ch:1094:/?xrd.gsiusrpxy=<cert>`

This has been suggested to us in order to force XRootd to create a new channel with the storage endpoint. This seems to have reduced the amount of errors, but we still see problems for polling requests that happen in parallel. At this point, we believe there might still be a caching mechanism in the XRootd library which doesn't work correctly.

Can you have a look at this?
If needed, I can provide XRootd debug logs for the investigation.

Cheers,
Mihai

**Comment by smithdh** [comment]
I'll assign this to myself for now, as I'd already heard about this issue and had started to look into it.

**Comment by amadio** [comment]
Fixed by #2293 (i.e. 921a65e2ffaf1a7b369d7c34a056555f58ae6076 and 459967d223aa3e6a79bfd42fdb8228888a03384d).
