### ISSUE TITLE
xrootd.slac.stanford.edu: unable to validate certificate, "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by wdconinc** [xrootd/xrootd#2295]
As of this past week (presumably July 11 since that's when the server certificate was changed), downloads with curl on debian and ubuntu fail with:
```
$ curl -L https://xrootd.slac.stanford.edu/download/v5.6.9/xrootd-5.6.9.tar.gz -o xrootd-5.6.9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

There is indeed no Internet2 certificate in `/etc/ssl/certs` for debian-based operationg systems.
```
$ ls /etc/ssl/certs/I*
/etc/ssl/certs/IdenTrust_Commercial_Root_CA_1.pem  /etc/ssl/certs/IdenTrust_Public_Sector_Root_CA_1.pem  /etc/ssl/certs/ISRG_Root_X1.pem  /etc/ssl/certs/ISRG_Root_X2.pem  /etc/ssl/certs/Izenpe.com.pem
```

Openssl confirms that:
```
$ openssl s_client -showcerts -verify_return_error -connect xrootd.slac.stanford.edu:443
Connecting to 134.79.138.26
CONNECTED(00000003)
depth=0 C=US, ST=California, O=Stanford University, CN=*.slac.stanford.edu
verify error:num=20:unable to get local issuer certificate
C01745AD59720000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
---
Certificate chain
 0 s:C=US, ST=California, O=Stanford University, CN=*.slac.stanford.edu
   i:C=US, O=Internet2, CN=InCommon RSA Server CA 2
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA384
   v:NotBefore: Jul 12 00:00:00 2024 GMT; NotAfter: Jul 12 23:59:59 2025 GMT
-----BEGIN CERTIFICATE-----
MIIG4TCCBUmgAwIBAgIQZHBVI50H0bqs6998MaT5NjANBgkqhkiG9w0BAQwFADBE
MQswCQYDVQQGEwJVUzESMBAGA1UEChMJSW50ZXJuZXQyMSEwHwYDVQQDExhJbkNv
bW1vbiBSU0EgU2VydmVyIENBIDIwHhcNMjQwNzEyMDAwMDAwWhcNMjUwNzEyMjM1
OTU5WjBeMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEcMBoGA1UE
ChMTU3RhbmZvcmQgVW5pdmVyc2l0eTEcMBoGA1UEAwwTKi5zbGFjLnN0YW5mb3Jk
LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKfahiVvEt+X4QbC
H6jKgmXcer6u7I1guCJ6mop5xjQqOMpDxosYgIM7WFfNBxtrJyWW6QafHrhlBMNn
Zto80rdiS1LjThrQUdGez9jGBCgW4Tuf5ot0newUVEgFucJ4cI+aVEoPa8pWCe8u
wQcfvPe1MISp8W06Fl1N/MvkDoYGvPuoP2WOf4z5Pwyw07V1pvuAjSSs3GOFEin+
5JbOMaiArPpRU4a25gLdQLE72o9S8NT/l6vh2Ilu9hmHx4t3cBDDBYB2LjGB2zkK
9W/yoHKogvJn9k2W4NvXh9siaOu1wT+d7+g69b1h2+fsV+zyr+bWFJwddhNkmoNP
4jkGHAcCAwEAAaOCAzMwggMvMB8GA1UdIwQYMBaAFO9MAJKm+3YuXpXiyV+HGxnV
TeLZMB0GA1UdDgQWBBTPQRG0Xd5BQ9BL39cVDAlu+VBUfzAOBgNVHQ8BAf8EBAMC
BaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
SQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICZzAlMCMGCCsGAQUFBwIBFhdodHRwczov
L3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgIwQAYDVR0fBDkwNzA1oDOgMYYvaHR0
cDovL2NybC5zZWN0aWdvLmNvbS9JbkNvbW1vblJTQVNlcnZlckNBMi5jcmwwcAYI
KwYBBQUHAQEEZDBiMDsGCCsGAQUFBzAChi9odHRwOi8vY3J0LnNlY3RpZ28uY29t
L0luQ29tbW9uUlNBU2VydmVyQ0EyLmNydDAjBggrBgEFBQcwAYYXaHR0cDovL29j
c3Auc2VjdGlnby5jb20wggF8BgorBgEEAdZ5AgQCBIIBbASCAWgBZgB2AN3cyjSV
1+EWBeeVMvrHn/g9HFDf2wA6FBJ2Ciysu8gqAAABkKeqTigAAAQDAEcwRQIhAOTz
pVKW+i4C9Jo0qI+Y61GmGo5Ky75jWHBNZNRB0LiiAiBr5mFfdTCS31cFy+ll14bd
0871/Q4QF3qhJ3DnLLUVzgB1AA3h8jAr0w3BQGISCepVLvxHdHyx1+kw7w5CHrR+
Tqo0AAABkKeqTgkAAAQDAEYwRAIgfE7d6xANOvH81L5Gm83oTZ5OLzvURMmGZWo9
UtlOoSYCIDRHa/RmJKIbQsoknQhc3dyvit6gdDItqpVTIIWLHIzqAHUAEvFONL1T
ckyEBhnDjz96E/jntWKHiJxtMAWE6+WGJjoAAAGQp6pOBwAABAMARjBEAiBH0LnK
7YEOS+CrMKs/iHV1K7YhjOKP0wBWDXmdhOLipwIgTiXkmausqpOuSZ1PWMtIjg95
6G+VXmqoA6wg7CHEoKEwMQYDVR0RBCowKIITKi5zbGFjLnN0YW5mb3JkLmVkdYIR
c2xhYy5zdGFuZm9yZC5lZHUwDQYJKoZIhvcNAQEMBQADggGBAD2wQk155hHuFMu3
Zd8vGEoGugd5TwrWW9yPhv/fu/qS+uJ0pf8s+pZNQ8LI1QaoDc/PUbBsedssiACh
XpMjHdpt+b0P8T20giAS6MuQo9tOTiUTXaWv+VXUAGlv6ty0qUcGhmZf9fL7z1aI
XeG/QoFJnxN9aKT2kZWVbqV0ZBlE5+eQ6hcGNTK8YefUtJy8etYi19U8sqWYHih4
8rn6yHFc/gUUSLmeFp0Bdg/7m8QDhgKSoq0HjyzslSvjFgbKGJOcCxz6hoZVZ7gx
IWxewhOdZ/zekhCgyb7Tv6YoanqbsjSK1k7A4/hhjpyBQyKCcIVwJMAEF/ZVheaL
x6pmFHMK5tLOc1TDC1IrXOE37KPdwpV3ApkSxe23bKGHRJ0mqkbYK7Hd1M4EOTc3
vPzKU5g9w0nAGU6AiklpOfaDguhSDZWDAfyP56dBjsERvTpLJ2rV5z8/Bbcd81LW
RcOMG5FbMrAOQq9BNrQgnc/I/gEOH/8zONYEbrQ9QaE/VEv6IA==
-----END CERTIFICATE-----
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 1876 bytes and written 346 bytes
Verification error: unable to get local issuer certificate
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: CED431CFE3D96472361C929FC9A18C78D877BB778BCC59246CE7BC019A31DC8B
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1720990810
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

Finally, https://www.ssllabs.com/ssltest/analyze.html?d=xrootd.slac.stanford.edu indicates "This server's certificate chain is incomplete".

**Comment by wdconinc** [comment]
Confirming that the missing Internet2 InCommon certificate is the issue. Downloading it, and using it to download from the server works:
```console
16:21:04 wdconinc@menelaos ~ $ curl -L https://spaces.at.internet2.edu/download/attachments/24576265/InCommon%20RSA%20Server%20CA%202.pem?api=v2 -o InCommon\ RSA\ Server\ CA\ 2.pem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2240  100  2240    0     0   9679      0 --:--:-- --:--:-- --:--:--  9696
16:21:12 wdconinc@menelaos ~ $ curl --cacert InCommon\ RSA\ Server\ CA\ 2.pem -L https://xrootd.slac.stanford.edu/download/v5.6.9/xrootd-5.6.9.tar.gz -o xrootd-5.6.9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6544k  100 6544k    0     0  1369k      0  0:00:04  0:00:04 --:--:-- 1395k
```
Nevertheless, this is an extra step that should not be required, and wasn't until recently.

**Comment by abh3** [comment]
It looks like the new certificate used a CA that was not automatically distributed to various sites. We have no control over certificates, nor do we have control over the CA distribution policy/mechanism. These are handled by your site administrator. You should discuss this problem with them.
________________________________

**Comment by wdconinc** [comment]
I don't think this is a problem of the users' configuration (or every intermediate CA would have to be added to each system that wishes to access sites that use it). 

Compare xrootd.slac.standford.edu with adfs.slac.stanford.edu (first one I happened upon that also uses InCommon):
- both use the same InCommon intermediate CA,
- but adfs.slac.stanford.edu provides the intermediate CA certificate to users as well.

That is why `curl -L https://adfs.slac.stanford.edu` doesn't return a certificate error, like `curl -L https://xrootd.slac.stanford.edu` does.

Here is the full certificate chain reported by openssl for `adfs.slac.stanford.edu`:
```console
$ openssl s_client -showcerts -verify_return_error -connect adfs.slac.stanford.edu:443
Connecting to 134.79.138.45
CONNECTED(00000003)
depth=2 C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
verify return:1
depth=1 C=US, O=Internet2, CN=InCommon RSA Server CA 2
verify return:1
depth=0 C=US, ST=California, O=Stanford University, CN=adfs.slac.stanford.edu
verify return:1
---
Certificate chain
 0 s:C=US, ST=California, O=Stanford University, CN=adfs.slac.stanford.edu
   i:C=US, O=Internet2, CN=InCommon RSA Server CA 2
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA384
   v:NotBefore: Jul  5 00:00:00 2024 GMT; NotAfter: Jul  5 23:59:59 2025 GMT
-----BEGIN CERTIFICATE-----
MIIHUzCCBbugAwIBAgIQJ1YR+y8uIh7eOta9Dn0RZDANBgkqhkiG9w0BAQwFADBE
MQswCQYDVQQGEwJVUzESMBAGA1UEChMJSW50ZXJuZXQyMSEwHwYDVQQDExhJbkNv
bW1vbiBSU0EgU2VydmVyIENBIDIwHhcNMjQwNzA1MDAwMDAwWhcNMjUwNzA1MjM1
OTU5WjBhMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEcMBoGA1UE
ChMTU3RhbmZvcmQgVW5pdmVyc2l0eTEfMB0GA1UEAxMWYWRmcy5zbGFjLnN0YW5m
b3JkLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPQiyqAb2js8
7JWBY+Nwpthy+oXlxO1Ni59cOIqDSqvio/EHO9zvrButGTh6jdBqtUy2MppINWI2
tSGxbY/xo6inkxlXQvLEA6PPOiPymOq5rB68x+vpBe3OM3O5b3v2+EmShS57g9Se
sfrd0ueZRaxwDxHa7u5yiPvNqqZz0A4S3cabiXV7oXGZTgeyWvtEfAP8n7L3Mju9
Cz3V2BnH9KomrNGoxMb68WvNx7/362qm684m39OifGMj2wdRve9ur8NbHsNUFYRz
S+vuOAQs2C4wEmtvBN8aDfNvhQzehYpLVq1fG0z0wI1+gN6Yd7wfXAKbnQSUKkzd
/sEVr2SwNgUCAwEAAaOCA6IwggOeMB8GA1UdIwQYMBaAFO9MAJKm+3YuXpXiyV+H
GxnVTeLZMB0GA1UdDgQWBBRZZy91EbRQY6ltJoamaZ6kJJGtMjAOBgNVHQ8BAf8E
BAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
AwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICZzAlMCMGCCsGAQUFBwIBFhdodHRw
czovL3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgIwQAYDVR0fBDkwNzA1oDOgMYYv
aHR0cDovL2NybC5zZWN0aWdvLmNvbS9JbkNvbW1vblJTQVNlcnZlckNBMi5jcmww
cAYIKwYBBQUHAQEEZDBiMDsGCCsGAQUFBzAChi9odHRwOi8vY3J0LnNlY3RpZ28u
Y29tL0luQ29tbW9uUlNBU2VydmVyQ0EyLmNydDAjBggrBgEFBQcwAYYXaHR0cDov
L29jc3Auc2VjdGlnby5jb20wggF/BgorBgEEAdZ5AgQCBIIBbwSCAWsBaQB3AN3c
yjSV1+EWBeeVMvrHn/g9HFDf2wA6FBJ2Ciysu8gqAAABkISlVasAAAQDAEgwRgIh
ALDQUKSpnmLycB7pY5HhanhYuBLmo4rpA4f9UkuKlAcPAiEA+o5HZVtt1+bH7cMP
Kc5y/J/Umj0Xnd4uSihBGqHF0bEAdgAN4fIwK9MNwUBiEgnqVS78R3R8sdfpMO8O
Qh60fk6qNAAAAZCEpVWKAAAEAwBHMEUCIC1cKPQ4dVGoFZqGbqvHYjcBkTyRf25D
CFyqoQtsO269AiEAlII7+jUQHU6viiEkBZnJh37c68LQA0bsBmecN/mw7/0AdgAS
8U40vVNyTIQGGcOPP3oT+Oe1YoeInG0wBYTr5YYmOgAAAZCEpVWIAAAEAwBHMEUC
IQCfr/8Thumrq66NgSkuKs4Et0zhDBvUJ9lCT+ArVVNNWgIgJcNmWikbmKBnWox1
fUyBs5Yv8/sXqkRFQIagKOOAtY0wgZwGA1UdEQSBlDCBkYIWYWRmcy5zbGFjLnN0
YW5mb3JkLmVkdYIfY2VydGF1dGguYWRmcy5zbGFjLnN0YW5mb3JkLmVkdYIoZW50
ZXJwcmlzZXJlZ2lzdHJhdGlvbi5zbGFjLnN0YW5mb3JkLmVkdYIsZW50ZXJwcmlz
ZXJlZ2lzdHJhdGlvbi53aW4uc2xhYy5zdGFuZm9yZC5lZHUwDQYJKoZIhvcNAQEM
BQADggGBABsS8dY/hIMcYUe83CCycIO0521NUyhCC/v7FwtkbelcqVRXBE8VQ5vj
jET2uY7wkYpT4eRkjseXfHjGxHXa7I1ZTYXOkPd2AcTpHRTxY/uTcX7p89FKexSV
JND2e4M43xenpGQhh2ffOO4sJtlAtt5gh2VmPRz4+XTDF0quqWHIcDAGzUh0OqOJ
Q3/t4I/3JzQES0aMpSjTD8kpRa6NBZh6DlWEmvSyrR7v8q2FeSRuc6Aj11u5bM5y
bXXJZmV1JrcL13kuZIehZwyD/i7ajqvtuZX+UDccgCKXHLIFw9EL7YhoitmAg6vT
1MjLOe2dYOzX60Wzj48wh7nemNchJTmimVK9x7LiXZMo5sss0LIaHpvK8LQLTfOh
ODAFusbtlCDDqqLk6CE/UWDht7jBDf+RI3GDLkCGN7M3y6QzD2TH02317Iz+A+lO
k9XDzU+xJ+JtDrf6HyhVSfUu2tJKQfgqNhhXrsS5qNSpsCyJo11iAbWzu/6NOpKG
h8jZCQK+hg==
-----END CERTIFICATE-----
 1 s:C=US, O=Internet2, CN=InCommon RSA Server CA 2
   i:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
   a:PKEY: rsaEncryption, 3072 (bit); sigalg: RSA-SHA384
   v:NotBefore: Nov 16 00:00:00 2022 GMT; NotAfter: Nov 15 23:59:59 2032 GMT
-----BEGIN CERTIFICATE-----
MIIGSjCCBDKgAwIBAgIRAINbdhUgbS1uCX4LbkCf78AwDQYJKoZIhvcNAQEMBQAw
gYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5MRQwEgYDVQQHEwtK
ZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMS4wLAYD
VQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTIy
MTExNjAwMDAwMFoXDTMyMTExNTIzNTk1OVowRDELMAkGA1UEBhMCVVMxEjAQBgNV
BAoTCUludGVybmV0MjEhMB8GA1UEAxMYSW5Db21tb24gUlNBIFNlcnZlciBDQSAy
MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAifBcxDi60DRXr5dVoPQi
Q/w+GBE62216UiEGMdbUt7eSiIaFj/iZ/xiFop0rWuH4BCFJ3kSvQF+aIhEsOnuX
R6mViSpUx53HM5ApIzFIVbd4GqY6tgwaPzu/XRI/4Dmz+hoLW/i/zD19iXvS95qf
NU8qP7/3/USf2/VNSUNmuMKlaRgwkouue0usidYK7V8W3ze+rTFvWR2JtWKNTInc
NyWD3GhVy/7G09PwTAu7h0qqRyTkETLf+z7FWtc8c12f+SfvmKHKFVqKpNPtgMkr
wqwaOgOOD4Q00AihVT+UzJ6MmhNPGg+/Xf0BavmXKCGDTv5uzQeOdD35o/Zw16V4
C4J4toj1WLY7hkVhrzKG+UWJiSn8Hv3dUTj4dkneJBNQrUfcIfTHV3gCtKwXn1eX
mrxhH+tWu9RVwsDegRG0s28OMdVeOwljZvYrUjRomutNO5GzynveVxJVCn3Cbn7a
c4L+5vwPNgs04DdOAGzNYdG5t6ryyYPosSLH2B8qDNzxAgMBAAGjggFwMIIBbDAf
BgNVHSMEGDAWgBRTeb9aqitKz1SA4dibwJ3ysgNmyzAdBgNVHQ4EFgQU70wAkqb7
di5eleLJX4cbGdVN4tkwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8C
AQAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMCIGA1UdIAQbMBkwDQYL
KwYBBAGyMQECAmcwCAYGZ4EMAQICMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9j
cmwudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9y
aXR5LmNybDBxBggrBgEFBQcBAQRlMGMwOgYIKwYBBQUHMAKGLmh0dHA6Ly9jcnQu
dXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FBQUFDQS5jcnQwJQYIKwYBBQUHMAGG
GWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggIBACaA
DTTkHq4ivq8+puKE+ca3JbH32y+odcJqgqzDts5bgsapBswRYypjmXLel11Q2U6w
rySldlIjBRDZ8Ah8NOs85A6MKJQLaU9qHzRyG6w2UQTzRwx2seY30Mks3ZdIe9rj
s5rEYliIOh9Dwy8wUTJxXzmYf/A1Gkp4JJp0xIhCVR1gCSOX5JW6185kwid242bs
Lm0vCQBAA/rQgxvLpItZhC9US/r33lgtX/cYFzB4jGOd+Xs2sEAUlGyu8grLohYh
kgWN6hqyoFdOpmrl8yu7CSGV7gmVQf9viwVBDIKm+2zLDo/nhRkk8xA0Bb1BqPzy
bPESSVh4y5rZ5bzB4Lo2YN061HV9+HDnnIDBffNIicACdv4JGyGfpbS6xsi3UCN1
5ypaG43PJqQ0UnBQDuR60io1ApeSNkYhkaHQ9Tk/0C4A+EM3MW/KFuU53eHLVlX9
ss1iG2AJfVktaZ2l/SbY7py8JUYMkL/jqZBRjNkD6srsmpJ6utUMmAlt7m1+cTX8
6/VEBc5Dp9VfuD6hNbNKDSg7YxyEVaBqBEtN5dppj4xSiCrs6LxLHnNo3rG8VJRf
NVQdgFbMb7dOIBokklzfmU69lS0kgyz2mZMJmW2G/hhEdddJWHh3FcLi2MaeYiOV
RFrLHtJvXEdf2aEaZ0LOb2Xo3zO6BJvjXldv2woN
-----END CERTIFICATE-----
---
Server certificate
subject=C=US, ST=California, O=Stanford University, CN=adfs.slac.stanford.edu
issuer=C=US, O=Internet2, CN=InCommon RSA Server CA 2
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3955 bytes and written 430 bytes
Verification: OK
---
```

**Comment by wdconinc** [comment]
I don't know which webserver runs xrootd.slac.stanford.edu, but the relevant [configuration section for nginx](https://nginx.org/en/docs/http/configuring_https_servers.html#chains) contains some general information on certificate chains which explains why this may appear to work in a browser but not in programs like curl that don't cache intermediate certificates.

**Comment by wdconinc** [comment]
Gentle ping.

This is leading to [build](https://gitlab.spack.io/spack/spack/-/jobs/12005876#L187) [failures](https://gitlab.spack.io/spack/spack/-/jobs/12005878#L327) in CI pipelines for the spack project (and likely therefore also key4hep).

We could switch the package recipe in spack to using the uploaded artifacts on github for increased reliability, but those are not universally available for older versions.

**Comment by xrootd-dev** [comment]
I agree with you that this is a problem but it's a problem with the web site administrator which we do not control. We are in the process of identifying the correct person to contact
________________________________

**Comment by jezwilkinson** [comment]
Hello, Is there any news on the certificate fix, or a possible workaround (an alternative mirror that can be used temporarily, maybe)? This issue is currently blocking the installation of any of xrootd's dependents via spack.

**Comment by amadio** [comment]
@abh3 We could mirror tarballs at CERN as well, we already put DEBs/RPMs only on EOS due to lack of space on AFS at SLAC...

**Comment by wdconinc** [comment]
Adding more mirrors is not really a solution to the underlying issue here. We (and other packager managers and maintainers) rely on automatic processes to pick up new releases, verify tarballs, etc. Therefore, having an authoritative source of tarballs (one that is configured with a working certificate chain, one that is prominently identified on the project page) is preferable over relying on a mirrored location (and, implicitly, the mirroring process) that is only partially available for past versions. That's why I have not gone ahead and changed the download URL in spack's xrootd package: the authoritative tarball location of the project remains xrootd.slac.stanford.edu. But I was thinking this would be resolved sooner, based on past experience reporting certificate issues for similar reasons. It is definitely starting to have an impact on our users.

**Comment by bbockelm** [comment]
Perhaps it's time to change the authoritative source of the release artifacts?  Is there some benefit to the SLAC web server, especially given the tradeoff of its difficulties in being maintained?

I agree having a single source is better than two - it just seems the current single source isn't the obviously best option?

**Comment by abh3** [comment]
Well, let's not knee jerk about this. There is a lot going on here and we just need to work through it. Every site has its moments.
________________________________

**Comment by abh3** [comment]
I have reached out to the SLAC admins to address this issue.

**Comment by greenc-FNAL** [comment]
@abh3 Any news on this issue, please?

**Comment by abh3** [comment]
We will be moving those artifacts to a different web server that won't have such ossues. In fact, I thought that was done already buty I see it was not. I'll ping the release manager. The actual final resting place is still unclear but whatever it is it will play with curl.

**Comment by amadio** [comment]
A backup of (almost) the whole website has been made on EOS on Aug 16th. All tarballs are now accessible there as well. So, say, if you want to download XRootD 5.7.0 (latest tarball), instead of https://xrootd.slac.stanford.edu/download/v5.7.0/xrootd-5.7.0.tar.gz you can now use https://xrootd.web.cern.ch/download/v5.7.0/xrootd-5.7.0.tar.gz which should not have any problems with certificates. All tarballs from the old website are accessible in the backup on EOS.

**Comment by wdconinc** [comment]
So, https://xrootd.web.cern.ch is now the new official web site for xrootd that we can use as reference location for downloads and to direct users to?

**Comment by wdconinc** [comment]
I am asking because if this is a snapshot of the August 16 state of the SLAC page then what guarantees are there about updates?

**Comment by amadio** [comment]
For the tarballs, the plan is to move them. For the website itself, this is not decided yet. I made a backup of the website for testing only, Andy and I will meet later today and this will be one of the topics of our discussion. It might be better to wait for a resolution to this certificate issue before pointing users to the website on EOS. I'd prefer to wait for a final decision from Andy on this.

**Comment by amadio** [comment]
@wdconinc In our meeting yesterday, Andy and I decided to make the tarballs on EOS the official location for downloads in the future, so while the website work is still ongoing (see https://xrootd.github.io from https://github.com/xrootd/xrootd.github.io), in the end all links on the website will point to the download location on EOS. So, in spack, you can just replace https://xrootd.slac.stanford.edu with https://xrootd.web.cern.ch in the URLs [here](https://github.com/spack/spack/blob/b623f58782c53bc465d14b84b44e91ffc2b872cd/var/spack/repos/builtin/packages/xrootd/package.py#L16-L17). Apologies for the trouble. We will update both locations with tarballs (and also GitHub), for a while, then with XRootD 6.0, maybe, we will start updating only the new official location. Best regards,

**Comment by amadio** [comment]
@ellert Please take note of the changes above. If you download tarballs from the current website, from the next version onwards I'd recommend to get the tarballs from https://xrootd.web.cern.ch instead. Thank you for maintaining XRootD RPMs!
