### ISSUE TITLE
Error when calling truncate

### ISSUE THREAD

**Issue by maxgalli** [xrootd/xrootd#2304]
Hi, I'm opening this ticket as a follow-up to the issue reported [here](https://github.com/scikit-hep/uproot5/issues/1252), in which the user tries to write an array to a remote location via xrootd.
I was able to reproduce the error with the following minimal reproducer that uses only xrootd Python bindings
```
from XRootD import client

myclient = client.FileSystem("root://eoshome-g.cern.ch")
path = "/eos/user/g/gallim/tmp/target.root"
status, _ = myclient.truncate(path, size=0, timeout=30)
print(status)
```

which outputs
```
[ERROR] Server responded with an error: [3013] Unable to truncate (null); Operation not supported
```

Not being familiar with the ```truncate``` function, I should point out that ```"/eos/user/g/gallim/tmp/target.root"``` does not exist yet in the moment in which the function is called, and the same happens in the [original issue](https://github.com/scikit-hep/uproot5/issues/1252) reported, that I mentioned above.

Does anyone know if this a bug or an incorrect usage of xrootd in the other libraries?

**Comment by amadio** [comment]
Hi @maxgalli, I think EOS might not support the call to truncate, and the file needs to exist before truncate is called. When I try it on a vanilla XRootD server, it works:

```sh
gentoo ~ $ xrdfs root://gentoo.cern.ch ls -l /test.txt
-rw-r--r-- xrootd xrootd 28 2024-04-04 07:15:59 /test.txt
gentoo ~ $ xrdfs root://gentoo.cern.ch cat /test.txt
This is a sample text file.
gentoo ~ $ python3.12
Python 3.12.4 (main, Aug  5 2024, 18:23:43) [GCC 14.1.1 20240507 d54151df3ba0ee3203e0b8cb8f8fcd168a766c51] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from XRootD import client
>>> fs = client.FileSystem('root://gentoo.cern.ch')
>>> status, _ = fs.truncate('/test2.txt', 0)
>>> print(status)
[ERROR] Server responded with an error: [3011] Unable to trunc /test2.txt; no such file or directory

>>> status, _ = fs.truncate('/test.txt', 0)
>>> print(status)
[SUCCESS] 
$ xrdfs root://gentoo.cern.ch cat /test.txt
$ # file is now truncated to zero size
```

**Comment by amadio** [comment]
Indeed, I looked at this a bit deeper and it's not supported:

https://github.com/cern-eos/eos/blob/5.2.24/auth_plugin/EosAuthOfsFile.cc#L430-L438
https://github.com/cern-eos/eos/blob/5.2.24/mgm/XrdMgmOfs.cc#L801-L827

According to @esindril, you need to use the file interface for that with EOS. So, your options are:

- Open the file for reading/writing, then call the truncate method on it.
  ```py
  from XRootD.client import *
  f = File()
  status, _ = f.open('root://eoshome-a.cern.ch//eos/user/a/amadio/test.root', flags.OpenFlags.UPDATE)
  status, _ = f.truncate(0)
  print(status)
  [SUCCESS]
  ```
- Open the file with the truncate on open option
  ```py
  from XRootD.client import *
  f = File()
  status, _ = f.open('root://eoshome-a.cern.ch//eos/user/a/amadio/test.root', flags.OpenFlags.DELETE)
  print(status)
  [SUCCESS]
  ```

I am therefore closing this as not planned, as it's not an issue with XRootD itself.
I hope the above is enought o address the issue for you.

**Comment by ikrommyd** [comment]
@jpivarski tagging in case you didn’t see this as it affects writing root files over xrootd in uproot.

**Comment by maxgalli** [comment]
> Indeed, I looked at this a bit deeper and it's not supported:
> 
> https://github.com/cern-eos/eos/blob/5.2.24/auth_plugin/EosAuthOfsFile.cc#L430-L438 https://github.com/cern-eos/eos/blob/5.2.24/mgm/XrdMgmOfs.cc#L801-L827
> 
> According to @esindril, you need to use the file interface for that with EOS. So, your options are:
> 
> * Open the file for reading/writing, then call the truncate method on it.
>   ```python
>   from XRootD.client import *
>   f = File()
>   status, _ = f.open('root://eoshome-a.cern.ch//eos/user/a/amadio/test.root', flags.OpenFlags.UPDATE)
>   status, _ = f.truncate(0)
>   print(status)
>   [SUCCESS]
>   ```
> * Open the file with the truncate on open option
>   ```python
>   from XRootD.client import *
>   f = File()
>   status, _ = f.open('root://eoshome-a.cern.ch//eos/user/a/amadio/test.root', flags.OpenFlags.DELETE)
>   print(status)
>   [SUCCESS]
>   ```
> 
> I am therefore closing this as not planned, as it's not an issue with XRootD itself. I hope the above is enough o address the issue for you.

Hi @amadio, thanks a lot for the hint!
