### ISSUE TITLE
[FATAL] Socket timeout error during xrdmapc

### ISSUE THREAD

**Issue by preeti-bhat** [xrootd/xrootd#2309]
Hi Team, 

I am facing an issue with the xrootd.  My xrootd server and client are running on kubernetes cluster. They run on multus ipv6 network. It was working all fine until last week. Then I changed the docker image to different one and it stopped working. I switched back to the previous image which was working all fine until last week, also has stopped working. They both use version 5.6. I upgraded to 5.7. but the same issue.
 
**Issue**:
 
I have redirectors and origins (xrootd-server-5.6.9-1.1.osg23.el8.x86_64). When I try to xrdmapc from the xrootd-client which is cern lxplus node,  I get the listing. However, if I try to do it from one of my clients (xrootd-client-5.6.4-1.1.osg23.el8.x86_64), I am getting the following error. But if I try to xrdmapc to other xrootd servers from my client, I get the listings.
 
`xrdmapc --list all redir-06.t2-sense.ultralight.org:1094 xrdmapc: Unable to get redir-06.t2-sense.ultralight.org:1094 subscribers; [FATAL] Socket timeout 0**** redir-06.t2-sense.ultralight.org:1094 [timeout]`
 
The xrootd log on the server says resource temporarily unavailable with some SSL error. 

`240808 20:04:51 945 Xrd_Poll: Poller 2 enabled anon.0:75@[2605:d9c0:6:2000::ffff:aa06]
240808 20:04:55 944 XrdLink: Unable to receive from anon.0:86@[2620:f:a:50:ae1f:6bff:febb:e2e8]; resource temporarily unavailable
240808 20:04:55 944 anon.0:86@[2620:f:a:50:ae1f:6bff:febb:e2e8] http_Protocol:  SSL_accept returned :-1
240808 20:04:55 944 anon.0:86@[2620:f:a:50:ae1f:6bff:febb:e2e8] http_Protocol:  SSL_accept wants to read more bytes... err:2
240808 20:04:55 944 Xrd_Poll: Poller 0 enabled anon.0:86@[2620:f:a:50:ae1f:6bff:febb:e2e8]
240808 20:05:10 2026 Xrd_Inet: Accepted connection on port 1094 from 236@[2605:d9c0:6:2000::ffff:aa06]
240808 20:05:10 4788 Xrd_Sched: running main accept inq=0
240808 20:05:10 2026 Xrd_ProtLoad: matched port 1094 protocol xroot
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] Xrd_Poll: FD 236 attached to poller 1; num=79
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Protocol: 0000 req=protocol dlen=0
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Response: 0000 sending 8 data bytes; status=0
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Accept: Accepting a TLS connection...
240808 20:05:10 2026 XrdLinkXeq: anon.0:236@[2605:d9c0:6:2000::ffff:aa06] connection upgraded to TLSv1.3
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Read: 24 out of 24 bytes.
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Protocol: 0000 req=login dlen=129
240808 20:05:10 2026 anon.0:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Read: 129 out of 129 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Response: 0000 sending 75 data bytes; status=0
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Write: 8 out of 8 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Write: 16 out of 16 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Write: 59 out of 59 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Read: 24 out of 24 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Protocol: 0000 req=auth dlen=112
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Read: 112 out of 112 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Protocol: 0000 more auth requested; sz=5111
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Response: 0000 sending 5111 data bytes; status=4002
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Write: 8 out of 8 bytes.
240808 20:05:10 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] TLS_Write: 5111 out of 5111 bytes.
240808 20:05:13 2026 root.11681:236@[2605:d9c0:6:2000::ffff:aa06] Xrootd_Protocol: 0000 request timeout; read 0 of 24 bytes
240808 20:05:13 2026 Xrd_Poll: Poller 1 enabled root.11681:236@[2605:d9c0:6:2000::ffff:aa06]`

Also, curl command gets stuck at the TLS. here is output:
```
curl -L -v -6 --cert $X509_USER_PROXY --cacert $X509_USER_PROXY --capath /etc/grid-security/certificates https://redir-06.t2-sense.ultralight.org:1094/
*   Trying 2605:d9c0:6:2645::1:f...
* TCP_NODELAY set
* Connected to redir-06.t2-sense.ultralight.org (2605:d9c0:6:2645::1:f) port 1094 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/xcache-proxy/x509-proxy
  CApath: /etc/grid-security/certificates
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: DC=org; DC=incommon; C=US; ST=California; O=California Institute of Technology; CN=redir-06.t2-sense.ultralight.org
*  start date: Feb 21 00:00:00 2024 GMT
*  expire date: Feb 20 23:59:59 2025 GMT
*  subjectAltName: host "redir-06.t2-sense.ultralight.org" matched cert's "redir-06.t2-sense.ultralight.org"
*  issuer: C=US; O=Internet2; CN=InCommon RSA IGTF Server CA 3
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET / HTTP/1.1
> Host: redir-06.t2-sense.ultralight.org:1094
> User-Agent: curl/7.61.1
> Accept: */*
>

```

Could you please assist me on this ?

Many Thanks,
Preeti Bhat

**Comment by abh3** [comment]
First of all, what system is running in the docker container (i.e. version of Linux)? What was in he container in the previous version tha used to work? For a test, would it be possible to run the server outside of Kubernetes?

**Comment by preeti-bhat** [comment]
It runs on alma linux 8.9.
It’s the same image that worked before but not working now.
We need it on the kubernetes. I can try with docker containers mostly.

Thanks
Preeti

**Comment by abh3** [comment]
Yes, please do try outside of K8S as we are dealing with virtual networking here. Alma 8 should not be a problem, though we have heard there may be issues with Alma 9. The other problem is that there may have been new firwall rules established by your network admins. So, you need to check with them on what is and is not allowed to go through the network.

**Comment by preeti-bhat** [comment]
Hi,
The issue was with dell switch z9100 (os 10). it was fragmenting the packets and creating MTU mismatch. The issue is now resolved.
