### ISSUE TITLE
Bug: Proc Summary Data is strange

### ISSUE THREAD

**Issue by patrickbrophy** [xrootd/xrootd#2310]
The process summary data returns strange data. Below is an example of the data I am seeing
```xml
<stats id="proc">
<usr>
	<s>0</s>
	<u>92870</u>
</usr>
<sys>
	<s>0</s>
	<u>10517</u>
</sys>
</stats>
```

As you can see, the values for the seconds are both zero and the values for the microseconds definitely don't appear to be in microseconds. The values for seconds are always populated to zero and fail to change. This appears to be an issue within the `ProcStats` function, defined [here](https://github.com/xrootd/xrootd/blob/master/src/Xrd/XrdStats.cc#L283). I would imagine that it is an issue with the conversions taking place.

**Comment by abh3** [comment]
As you can see from the gdb trace below the values are properly reported. Given that 1 second has 1,000,000 microseconds the values reported in the ticket above fall comfortably in that range. I think you may have mixed up the scale with milliseconds. In any case, I am closing the ticket as it appears everything is working here.

p r_usage
$1 = {ru_utime = {tv_sec = 0, tv_usec = 2270}, ru_stime = {tv_sec = 0, tv_usec = 10670},
"<stats id=\"proc\"><usr><s>0</s><u>2270</u></usr><sys><s>0</s><u>10670</u></sys></stats>"
[Do some work and ask again for the statistics]
"<stats id=\"proc\"><usr><s>0</s><u>2270</u></usr><sys><s>0</s><u>13704</u></sys></stats>"
