### ISSUE TITLE
Make stale checksum check optional for ceph storage endpoints

### ISSUE THREAD

**Issue by Jo-stfc** [xrootd/xrootd#2338]
in ceph, reads and metadata calls change the file modification time. This means the stale checksum check ends up recalculating the checksum every time it's requested instead of fetching from metadata.
In
https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/src/XrdCks/XrdCksManager.cc#L477
and 
https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/src/XrdCks/XrdCksManager.cc#L481
Could the stale check be chained with a configuration setting with default true?
e.g.
 if ((rc = ModTime(Pfn, MTime)) && stalecheck )
(Cks.fmTime != MTime) && stalecheck || ...

**Comment by abh3** [comment]
We have solved ths problem by implementing a nomtchk option for default plugins. Th fix should appear in R6.

**Comment by abh3** [comment]
Done.
