### ISSUE TITLE
[XrdCms]dfs file not found log message improvement

### ISSUE THREAD

**Issue by Jo-stfc** [xrootd/xrootd#2345]
for CMSD dfs systems, the error message for a file not found response can be confusing for users:
[3011] Too many attempts to gain dfs read access to the file (source)
This might be better put as something like
[3011] File not found - Too many attempts to gain dfs read access to the file (source)
I made a simple patch in

https://github.com/Jo-stfc/xrootd/tree/patch-6
but I notice that line also might be called on too many write attempts?

**Comment by abh3** [comment]
I would use the phrase "access denied" not "file not found" because, in fact, the file might not really exist. The code here is actually denying access because the client tried to gain access to many times.

**Comment by abh3** [comment]
This would be inconsistent. The file may actually exist it's simply you tried to often to select a different server. This could be considered a denial of service attack for all intense and purposes. OK, how about "access refused". File not found is miosleading and inappropriate.

**Comment by Jo-stfc** [comment]
Would '<operation> attempts exhausted' be better? I'd prefer not having 'access' or 'permission' in the message as those can mislead into thinking it's a user permission issue

**Comment by abh3** [comment]
How about "Too many failed dfs <op> attempts; operation terminated"?

**Comment by Jo-stfc** [comment]
yes, that sounds good. Thanks!

**Comment by amadio** [comment]
@abh3 @Jo-stfc Do we have consensus here? Could you push the change, @abh3? Or shall I do it?

**Comment by abh3** [comment]
Sorry about letting this fall through the cracks. I just pushed the change to the devel branch.
