### ISSUE TITLE
Invalid chunk framing for HTTP

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2351]
Under heavy load, we are getting an error from our HTTP clients, "invalid byte in chunk length".  This occurs when XrdPfc gets into a bad state and starts spitting out frequent errors.

In chunked mode, after a complete chunk is sent there is a header containing a hexadecimal number encoded as an ASCII string followed by a CRLF.  The client error message suggests there's something in the header that's not an ASCII-encoded digit; I'm thinking there's potentially some sort of server error message bleeding through.

I've not been able to reproduce it reliably but, to me, this suggests there's something in the `GET` error path that is incorrectly returning an error message when in chunked mode.  We should review the error handling around the `GET` path and see if there's an obvious place where we write to the socket _not_ in chunked mode.

**Comment by bbockelm** [comment]
For example, for `GET`, we always start the HTTP response in the post-processing of request state 2.

That means, any subsequent calls to `SendSimpleResp` in request state 3 or later cause a 'double response' to a single request and will *break* the HTTP protocol.

Quick code review shows three cases:
- https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L1230
- https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L1301
- https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L1292

We can send the error message in the footer if the client requested it.  See [this example](https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L2292-L2316).

Can't guarantee those particular call sites are what the user experienced -- but they're definitely incorrect.

**Comment by bbockelm** [comment]
I setup the following test:
- XCache and origin.  Origin has 100, 4MB files.
- Tweaked a load generator (https://github.com/bbockelm/go-wrk) to download random files.
- Ran the load generator to have 200 separate HTTP sessions for 10 seconds.

The result was about 0.5% (37 out of 8,025) of the HTTP responses were corrupted by this issue.

**Comment by ccaffy** [comment]
I see the issue indeed. Once the GET returns 200 OK, no other response should be sent to the client. 

So in the case the XRootD server has an issue after the 200 OK response is returned, we will just log the error in the logs and if the client requested the footer, we will also send this error message to it.

**Comment by amadio** [comment]
Fixed by #2300 (merged into master now), will be in 5.7.2.
