### ISSUE TITLE
Race condition during HTTP-TPC requests leading to unintended file deletion

### ISSUE THREAD

**Issue by gmgigi96** [xrootd/xrootd#2354]
During a series of HTTP-TPC requests, we saw a race condition that led to the deletion of a file in EOS.

I will report here all the logs, in both EOS and FTS to show what happened:

- At 00:37:19, FTS initiates an HTTP-TPC request (in PULL mode):
```
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > COPY /eos/cms/xxx.root HTTP/1.1
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > Host: eoscms-ns-ip563.cern.ch
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > Accept: */*
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > Source: https://xxx:1095/xxx.root
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > X-Number-Of-Streams: 1
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > Secure-Redirection: 1
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > ClientInfo: file-id=xxx;retry=0
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > TransferHeaderAuthorization: xxx
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > Credential: none
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > Authorization: xxx
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > RequireChecksumVerification: false
INFO    Sat, 05 Oct 2024 00:37:19 +0200; Davix: > User-Agent: libdavix/0.8.7 libcurl/7.76.1
```

On EOS we got the request:
```
241005 00:37:19 time=1728081439.869261 func=MatchesPath              level=INFO  logid=static.............................. unit=mgm@eoscms-ns-ip563.cern.ch:1094 tid=00007fbbfb3ff700 source=EosMgmHttpHandler:198          tident= sec=(null) uid=99 gid=99 name=- geo="" verb=COPY path=xxx.root
```

- At 00:47:20, FTS timeout after 10 minutes:
```
INFO    Sat, 05 Oct 2024 00:47:20 +0200; Gfal2: Copy failed with mode 3rd pull: copy timeout of 601s
```
- At 00:47:21, FTS retries in PUSH mode:

```
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > COPY xxxroot HTTP/1.1
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > Host: xxx:1095
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > Accept: */*
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > Destination: https://xxx:443/xxx.root
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > X-Number-Of-Streams: 1
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > Secure-Redirection: 1
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > ClientInfo: file-id=xxx;retry=0
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > Authorization: xxx
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > TransferHeaderAuthorization: xxx
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > Credential: none
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > RequireChecksumVerification: false
INFO    Sat, 05 Oct 2024 00:47:21 +0200; Davix: > User-Agent: libdavix/0.8.7 libcurl/7.76.1
```
which succeeds at 00:47:22.

- 00:47:24, the file is on EOS:
```
INFO    Sat, 05 Oct 2024 00:47:24 +0200; Davix: > HEAD xxx.root HTTP/1.1
[...]
INFO    Sat, 05 Oct 2024 00:47:24 +0200; Davix: 
INFO    Sat, 05 Oct 2024 00:47:24 +0200; Davix: < HTTP/1.1 200 OK
[...]
INFO    Sat, 05 Oct 2024 00:47:24 +0200; Davix: < Content-Length: 355383
[...]
```

- 00:49:20, on EOS the first TPC request (PULL mode), times out:
```
241005 00:49:20 9306 TPC_PullRequest: event=SIZE_FAIL, local=/xxx.root, remote=https://xxx:1095/xxx.root, user=xxx, status=500; HTTP library failed: Timeout was reached
```

The internal timeout in EOS, triggered a delete of the file.

**Comment by ccaffy** [comment]
Thanks @gmgigi96 for opening this issue.

I suspect this comes from the fact that for PULL, we determine the size of the file before opening it and if that request times-out, XrdHTTPTPC anyway opened the file for writing. The transfer started but the FTS client had disconnected which stops the TPC transfer from going on --> EOS sees that the file got opened, but the transfer is incomplete --> delete on close!

The first easy solution I can think of right now may be that if the size request is not successful (DetermineXferSize() is not successful), we immediately fail the TPC transfer without trying to open the file.

Second solution would be : we don't open the file if the client is already gone.

**Comment by ccaffy** [comment]
Another nice thing to improve:
I notice that the size request is performed twice during the TPC PULL transfer. The first one happens before the file is opened, the second one before the file transfer starts. I believe that the second size request is NOT necessary as we already have the size with the first one. Therefore, a size request that times out would completely prevent the open from happening.
