### ISSUE TITLE
Client plugin returning `XrdCl::errSocketTimeout` triggers near-infinite loop in XrdHttp

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2357]
I have a client plugin that's causing a`XrdCl::errSocketTimeout` to be returned to PFC (I _think_ it's not returned directly from the plugin but due to the fact the client plugin doesn't invoke the callback in time).

This causes the XrdPosix to map the error to [ETIMEDOUT](https://github.com/xrootd/xrootd/blob/master/src/XrdPosix/XrdPosixMap.cc#L102).  Then, XrdOfs takes the failure and [turns it into a retry](https://github.com/xrootd/xrootd/blob/devel/src/XrdOfs/XrdOfs.cc#L2650).

The bridge propagates the response up to XrdHttp as a success, causing the `XrdHttp` to [post-process](https://github.com/xrootd/xrootd/blob/devel/src/XrdHttp/XrdHttpReq.cc#L2323) the non-success as a success (it sends 30 bytes of garbage, it seems, to the client). Since the failure is marked as a success, the event state machine for XrdHttp goes forward again and repeats the whole process.

This effectively performs a DDoS attack on the origin.  The cache generates 16-32 parallel requests (2MB request per HTTP event loop with 64KB blocks in the cache is 32 requests -- the max parallelism may limit this, however.  Our config keeps it to 16), times out on a busy origin, and then immediately sends another 16 parallel requests.

**Comment by bbockelm** [comment]
Arguably the problem is in XrdOfsFile::read.

The function is supposed to return SFS_ERROR or the number of bytes read.

However, the Emsg routine converts ETIMEDOUT to 30 (which is interpreted as 30 bytes) and EBUSY to 5.

I assume any time the OSS returns one of those two error codes for a read that it is converted to a corrupt response.

**Comment by abh3** [comment]
Good catch @bbockelm - I should have fixed it. It was tied up with the extended error messages and the issue is not present in master or any release.

**Comment by bbockelm** [comment]
The behavior was observed in 5.7.0 in the wild.  My reproducer setup / dev laptop only tried on the devel branch.  I think we should assume it is in the releases too.

**Comment by bbockelm** [comment]
Thanks!

Impact-wise, this can cause corrupt data being served for the PFC use case.

It does require an origin that is sufficiently slow - slow enough to trigger a timeout.  To me, probably the corruption is more impactful than the effective DDoS on the slow origin.

I have not investigated whether this can be triggered without a client plugin or over the xrootd protocol.
