### ISSUE TITLE
Build script not compatible with nvc++

### ISSUE THREAD

**Issue by mmha** [xrootd/xrootd#2361]
Hello,

when trying to build XRootD with nvc++ I encountered these two issues while configuring the project:

* In `cmake/XRootDOSDefs.cmake` the variable `XrdClPipelines` is not set to `TRUE` because the `CMAKE_CXX_COMPILER_ID` is neither gcc nor clang but `"NVHPC"`. This caused some required source files to not get built, resulting in some undefined references during linking.
* In `src/XrdPosix.cmake` the compiler flag `-fno-lto` gets added to the target `XrdPosixPreload` without checking whether the compiler supports it or not. nvc++ does not support LTO and therefore there are no `-f[no-]lto` flags available. The addition of the flag should be guarded with checking the `CMAKE_CXX_COMPILER_ID`, using the [CheckCXXCompilerFlag](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html) module to test the compiler (this is probably most robust) or using the [`INTERPROCEDURAL_OPTIMIZATION`](https://cmake.org/cmake/help/latest/prop_tgt/INTERPROCEDURAL_OPTIMIZATION.html) target property instead of `-flto` if that gets added somewhere else.

**Comment by amadio** [comment]
I agree that the items listed above are real problems and we will fix them for the next release of XRootD. However, given that XRootD does not have support for GPUs, could you maybe clarify the motivations to build it with nvc++?

**Comment by amadio** [comment]
@mmha You should now be able to take the current `master` branch and build with `nvc++`. When we release XRootD 5.7.2, we should ensure the builtin version of XRootD in ROOT is updated accordingly. Thanks for the bug report.
