### ISSUE TITLE
HTTP tracing could go in debug instead of info

### ISSUE THREAD

**Issue by ccaffy** [xrootd/xrootd#2377]
We should consider having the following lines printed only in debug mode:

```
http Protocol 'https'
http Name 'dteam001'
http Host '[2001:1458:201:e4::100:68d]'
http Vorg ''
http Role ''
http Grps ''
http Caps ''
http Pidn ''
http Crlen 0
http ueid  0
http uid   0
http gid   0
http Attr  gridmap.name = '1'
http Attr   = ''
```

The configuration is:
```
http.trace  all -debug
http.auth  tpc fcreds
http.gridmap  /etc/grid-security/grid-mapfile
http.secxtractor  libXrdVoms.so
http.exthandler  EosMgmHttp libEosMgmHttp.so eos::mgm::http::redirect-to-https=0
http.exthandler  xrdtpc libXrdHttpTPC.so
```

1. Investigate from where these lines are printed (Do they come from XrdHttp? or do they come from some security plugin?)
2. Turn these lines into debug printing instead of info if possible

**Comment by amadio** [comment]
Looks like it comes from here:

https://github.com/xrootd/xrootd/blob/58fb995c3fa67b5d5d151a81130097738dfcbaff/src/XrdHttp/XrdHttpSecurity.cc#L271-L274

**Comment by amadio** [comment]
If @abh3 agrees to it, in principle this could go into 5.7.2 instead of 5.8.0.

**Comment by amadio** [comment]
It's all the same message, no?

**Comment by ccaffy** [comment]
Nope, does not come from  this as this prints only one line ;) : `241126 00:00:34 735056 anon.0:703@eosmon02 http_Security:  Certificate data extraction failed: /DC=ch/DC=cern/OU=computers/CN=eosmon02.cern.ch Failed. err: -1`

**Comment by ccaffy** [comment]
Comes from there: https://github.com/xrootd/xrootd/blob/58fb995c3fa67b5d5d151a81130097738dfcbaff/src/XrdSec/XrdSecEntity.cc#L87-L101

**Comment by ccaffy** [comment]
And called here: https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpProtocol.cc#L564

**Comment by ccaffy** [comment]
Actually, one can remove the authentication logging by doing adding `-auth` to the tracing config line of http:
`http.trace all -debug -auth`

**Comment by amadio** [comment]
I see. I thought that the `<< SecEntity.moninfo` would do that. Ok, thanks for digging it through.

**Comment by abh3** [comment]
So, I think this was resolved and no changes are needed, right?

**Comment by ccaffy** [comment]
Yes, no changes are needed. If people don't like these lines, then they can suppress it.
By the way, the "auth" is not documented here https://xrootd.web.cern.ch/doc/dev57/xrd_config.htm#_Toc171720013

Do you think you can add it @abh3 ?

Thanks in advance. Closing this ticket as "Not planned"

**Comment by abh3** [comment]
Oops, another doc item slips through the cracks. Thanks for letting me know!
