### ISSUE TITLE
Python 2 vs 3

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#238]
The configuration currently prefers python 3 over python 2. A build with both python 2 and 3 installed finds the python 3 interpreter and libraries:
```
-- Found PythonLibs: /usr/lib64/libpython3.4m.so (found version "3.4.2") 
-- Found PythonInterp: /usr/bin/python3.4 (found version "3.4.2") 
```
However, the setup.py script that is used to do the actual build is not valid python 3 syntax and fails:
```
  File "/home/ellert/Fedora-GIT/xrootd/xrootd-4.2.0/build/bindings/python/setup.py", line 28
    print 'XRootD library dir:    ', xrdlibdir
                                  ^
SyntaxError: Missing parentheses in call to 'print'
bindings/python/CMakeFiles/python_target.dir/build.make:55: recipe for target 'bindings/python/python_bindings' failed
make[2]: *** [bindings/python/python_bindings] Error 1
```
Preferably the configuration should search for both python 2 and python 3 and build the python module for both.

**Comment by esindril** [comment]
The XRootD python C API needs to be ported to Python 3, therefore the issue with print in the setuptools script is only the tip of the iceberg. We support only Python 2 for the time begin.
