### ISSUE TITLE
https://xrootd.org/ not reachable?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2383]
Looks like https://xrootd.org/ is not currently accessible.

Don't know when it started but I noticed it yesterday.

**Comment by amadio** [comment]
Indeed, please go directly to https://xrootd.github.io or to https://xrootd.web.cern.ch (website backup on EOS) in the mean time.

**Comment by amadio** [comment]
Actually, the `xrootd.org` domain does not support https, you need to use http://xrootd.org, which works fine. We will look into adding https support later, but for now, I'm closing this bug.
