### ISSUE TITLE
[XrdHttpTPC - PULL] Credential forwarding does not work in case the client is immediately redirected

### ISSUE THREAD

**Issue by ccaffy** [xrootd/xrootd#2386]
The credential forwarding does not work in the case the client initiating the HTTP TPC transfer is immediately redirected to a host.

The reason is that the initial curl handle that will be used to redirect the client does not have the CURLOPT_UNRESTRICTED_AUTH flag set! We only set it in the State object...

The code not setting this flag:

```cpp
    int open_results = OpenWaitStall(*fh, full_url, SFS_O_RDONLY, 0644,
                                     req.GetSecEntity(), authz);
    if (SFS_REDIRECT == open_results) {
        int result = RedirectTransfer(curl, redirect_resource, req, fh->error, rec);
        return result;
    }
```

**Comment by bbockelm** [comment]
@ccaffy - can this be fixed server-side too?  The server shouldn't assume the client has one-behavior-or-the-other in terms of re-adding the `Authorization:` header.

What's the server in the case you're testing?  This case you describe sounds exactly like most of the XRootD deploys in the US yet the credential forwarding works fine there (so there must be some additional subtle.

**Comment by ccaffy** [comment]
Closing issue as won't do. One can ask curl to pass the credential upon redirection by passing the flag `--location-trusted`. It's not a server side fix that needs to be done.

**Comment by abh3** [comment]
So, I am confused. If it's just the matter of setting the right option to allow a redirect to also forward the credentials, why is that something not to be done? One assumes that enabling http fccreds for a server should forward the credentials on a redirect, we also assume that the target, should it be a redirector would also forward the credentials *if* fcreds were configured for it as well. Obviously, I must not understanding something here.

**Comment by ccaffy** [comment]
Hi @abh3,

I need to test this further then. My guess was it was the responsibility of the curl client to decide whether the Authorization headers should be passed to the redirected host. 
In a TPC PULL, the server receiving the COPY command  (active party) first acts as a server, then as a client in order to download the file from the passive party. It's only during this client phase (the GET is issued to do the PULL) that we programmatically tell curl to forward the credentials.

Here it's when the first COPY command of the client is redirected to issue another COPY --> I'm not sure the active server can tell the client to forward the credentials. I'll test this.

Cheers,
Cedric

**Comment by abh3** [comment]
Hi Cedric,

Yes, please do. My understanding that when fccreds is enabled any instance of a client created in the server should always set the trusted host setting to have the credentials forwarded. This should work no matter the context.

Andy

**Comment by ccaffy** [comment]
Hi @abh3,

Happy New Year !

Apparently, my assumption was correct, the server cannot enforce a client to forward the credentials upon redirection.

I did the following test:

Modified the HTTP TPC PULL code to allow unrestricted auth before the server will send the redirection to the client:

```cpp
    int open_result = OpenWaitStall(*fh, full_url, mode|SFS_O_WRONLY,
                                    0644 | SFS_O_MKPTH,
                                    req.GetSecEntity(), authz);
    if (SFS_REDIRECT == open_result) {
        curl_easy_setopt(curl,CURLOPT_UNRESTRICTED_AUTH,1L);
        int result = RedirectTransfer(curl, redirect_resource, req, fh->error, rec);
        return result;
    }
```

Then triggered a HTTP TPC PULL transfer (with Authorization header set) with the active server being a xrootd redirector (the OpenWaitStall results in a SFS_REDIRECT). 

Unfortunately, the client did not forward the Authorization header to the redirected host.

```
curl -v --capath /etc/grid-security/certificates -L -X COPY -H 'Authorization: Bearer test' -H "source: https://xrootd-server.cern.ch:1096/tmp/BIGFILE_5GB_COPY" "https://xrootd-server.cern.ch:11940/srvdata/BIGFILE_5GB_COPY"
> COPY /srvdata/BIGFILE_5GB_COPY HTTP/1.1
> Host: xrootd-server.cern.ch:11940
> User-Agent: curl/7.76.1
> Accept: */*
> Authorization: Bearer test
> source: https://xrootd-server.cern.ch:1096/tmp/BIGFILE_5GB_COPY
> 

< HTTP/1.1 307 Temporary Redirect
< Connection: Keep-Alive
< Server: XrootD/v5.7.1-22-g82a3fc0e8
< Content-Length: 0
< Location: http://[::1]:10942//srvdata/BIGFILE_5GB_COPY
< 
* Connection #0 to host xrootd-server.cern.ch left intact
* Clear auth, redirects to port from 11940 to 10942Issue another request to this URL: 'http://[::1]:10942//srvdata/BIGFILE_5GB_COPY'
*   Trying ::1:10942...
* Connected to ::1 (::1) port 10942 (#1)
> COPY //srvdata/BIGFILE_5GB_COPY HTTP/1.1
> Host: [::1]:10942
> User-Agent: curl/7.76.1
> Accept: */*
> source: https://xrootd-server.cern.ch:1096/tmp/BIGFILE_5GB_COPY
> 

```
