### ISSUE TITLE
Xrd: Disconnect: Destroying nonexistent logconn

### ISSUE THREAD

**Issue by geoffherbert** [xrootd/xrootd#253]
Hello,
I am not an expert on this, so please accept my apologies if I am posting in the wrong place or asking a stupid question.
I am trying to read root ntuples using xrootd version 2.9.7 build v3.2.4
When trying to access some files, my jobs hang until they are killed by runtime limits. When I try to run over the files on the login server, the jobs also hang when trying to read the files.
After I kill the job, I get the error message "Xrd: Disconnect: Destroying nonexistent logconn"
I'm not sure what this means, and I don't know how to fix it. I also don't know where I can find my xrootd log files.
Any help with identifying and solving the problem would be greatly appreciated.
Many thanks,
Geoff

**Comment by abh3** [comment]
Hi Geoff, well this isn't exactly the right place for these kinds of questions. That said, where is the data (i.e. host:port)? As for the message, it usually means nothing as fa as I can see. It simply says the client thread was trying to disconnect from a server but before it could do so the connection was closed by someone else. Finally. there have been many releases past 3.2.4, which is almost 3 years old. Is there any particular reason you can't switch top a current release?

**Comment by geoffherbert** [comment]
Hello,
The problem has been identified - Many thanks for your help. We think the problem was caused by a high file transfer load between data nodes, which slowed down access to the files causing the jobs to hang.
Cheers,
Geoff
