### ISSUE TITLE
implementation of XrdClStream::OnError is error prone and migh result in a deadlock

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#257]
Currently, if the callee holds the stream lock, the handlers (lines 780 - 783) are called with the stream lock locked although the lock is being unlocked (line 778) because it is recursive. This might result in a deadlock (see discussion #247 ).

Either the stream lock (line 690) has to be non-recursive or the callback processing needs to be delegated to the worker thread pool.

**Comment by bbockelm** [comment]
Thanks for looking into this!

It might be reasonable to do all callback handling in a separate thread pool.  It might be more straightforward than trying to validate that the entire client is reentrant.

We can solve the recursive lock for this particular instance, but I worry what else might be lurking around.

**Comment by simonmichal** [comment]
Any time :) 

I agree, most likely it would be better to use separate thread pool.

**Comment by abh3** [comment]
Thaks to both of you for looking into this. I agree, moving this to the thread pool is the best solution. I already had to something similar in another package. There a synchronous file operation was invoked in the callback which resulted in a stuck thread because the callback code path kept the socket disabled until the callback returned; which of course would never happen. So, let's just solve all of these issues at once instead of battling each when we come across it. Unfortunately, this is not a quick solution either.

**Comment by simonmichal** [comment]
@bbockelm : I moved all the callback handling to the thread-pool. Is there a chance you could test if it fixes this issue?

Thanks,
Michal

**Comment by ljanyst** [comment]
I did not read the code carefully, so bear with me, but the point of moving the error callbacks to the thread pool was to make sure client holds no locks during these callbacks. I am not sure the patch you pushed helps in that regard.

**Comment by simonmichal** [comment]
I think the problem (in particular) was that some callbacks were executed within a thread that was holding the stream lock. Since now all the error/timeout callbacks are delegated to the thread-pool, this should be fixed by definition ;-) (the thread-pool worker threads are not holding any additional locks, right?).

That said, fell free to point out which part of the patch is working you! ;-)

**Comment by xrootd-dev** [comment]
You're right. It should work fine. Thanks for explaining and refreshing
my memory!

**Comment by abh3** [comment]
I suppose that also means that SSI need not redispatch callbacks on 
another thread as well (it does so now), right?

**Comment by ljanyst** [comment]
It only affects error callbacks. Regular callbacks were always handled by the worker thread pool.
