### ISSUE TITLE
Request new 4.2 bugfix release with PFC fixes

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#258]
Two bugs - #239 and #249 - hit caching proxy users fairly hard.

Can I request these be ported to stable-4.2.x branch a new 4.2.2 release made?

Thanks!

**Comment by abh3** [comment]
Hi Brian,

Indeed, we plan to release 4.2.2 in the next couple of weeks. We need to also include several other fixes and work around some vacation schedules.

Andy

**Comment by bbockelm** [comment]
Great, thanks!

To make it into the next OSG release, we need a tag by August 4 (at the latest).

Can you do backports of the above bugs into the stable branch so I can at least give someone a test build?

**Comment by abh3** [comment]
We should be able to do that. Now, you said you wanted this back ported to an older release. Which one did you have in mind?

**Comment by bbockelm** [comment]
I was thinking the 4.2.x series.

**Comment by alja** [comment]
I will make new PR for stable-4.2.x branch with backport of pfc bugfixes from master branch.

**Comment by abh3** [comment]
Well, yes. The next release will be 4.2.2 since it's only bug fixes, no new stuff really. If by 4.2.x you mean 4.2.2 then no back porting is needed. I thought you wanted it in 4.1 (i.e. 4.1.4) or in 4.0 (4.0.5). Am I misunderstanding something here?

**Comment by alja** [comment]
@abh3 
I thought that 4.2.2 will be build from branch stable-4.2.x. In case you will be using that branch than PR #240, #254, #255, and #261 from master have to be merged to  stable-4.2.x.
Let me know if you want a PR for this.

**Comment by abh3** [comment]
Ah, I see the confusion. I thought we would role out 4.2.2 with all the accumulated fixes (i.e. what is in git head). The root team needs many of those patches as well. Anyway, Michal will be doing this so he'll tell everyone what the final scoop is.

**Comment by alja** [comment]
Two changes are still missing in the stable-4.2 branch: #255 and #261.

**Comment by simonmichal** [comment]
It's my bad, I though only the commits market for milestone 4.2.2 will go to the release, but since the HEAD contains only bug fixes the whole master will be merged into stable-4.2.x. Sorry for the confusion.

Anyway, for the future it would be good to mark all the commits with the corresponding milestone, it makes things more transparent and makes it easier to do proper release notes.

Michal

**Comment by alja** [comment]
@simonmichal 
I have inactive field for labels and milestones in my PR. I don't know if this is because I don't have permissions or there is a git trick which I don't know about.

**Comment by alja** [comment]
I could edit labels and milestones for issues and labels if I would be in list of the project collaborators.

**Comment by simonmichal** [comment]
I will have a look, for sure we will figure something out.

**Comment by alja** [comment]
All the PFC bugfixes have been merged to  stable-4.2.x. This issue can be closed.

**Comment by abh3** [comment]
Patches have been included in 4.2.2.

**Comment by bbockelm** [comment]
I don't see a 4.2.2 tag in github.  Am I looking in the wrong place?

**Comment by abh3** [comment]
Yes, I am confused too. It apparently was put in branch named 4.2.x. I will look into it.

Andy

**Comment by esindril** [comment]
At the top of the main page in the releases part you can find all the tags:
https://github.com/xrootd/xrootd/releases/tag/v4.2.2
