### ISSUE TITLE
File cache client access silently fails if cache directories are unwritable

### ISSUE THREAD

**Issue by illingwo** [xrootd/xrootd#259]
If the server cache is unwritable, or it's not possible to create the necessary directories, then data access from the client fails in a confusing way - the server returns no data instead of an error. For example, my cache directory is /stash, and I deliberately make it impossible to cache new files in a particular directory

```
# chmod 0111 /stash//pnfs/fnal.gov/usr/nova/data/flux/gsimple/nova_v06/nd/mn
```

then xrdcp fails like this:

```
$ XRD_LOGLEVEL=Error xrdcp -f root://fermicloud058.fnal.gov//pnfs/fnal.gov/usr/nova/data/flux/gsimple/nova_v06/nd/mn/rhc/gsimple_NOvA-ND_mn000z-200i_rp11_bs1.1_pnut_lowth_f11f093bbird_target_q34_00001.root /tmp/
[0B/330.8MB][  0%][>                                                 ][0B/s] 
[2015-07-09 16:54:54.291474 -0500][Error  ][Utility           ] The declared source size is 346873679 bytes, but received 0 bytes.

Run: [ERROR] Received corrupted data
```

and anything using the POSIX read function just gets a zero return value with no error.

If pss.trace is enabled on the server you get a message that doesn't really explain what is wrong

```
[2015-07-09 17:10:54.961823 -0500][Error  ][App               ] Prefetch::Open() can't get data-FD for /stash/pnfs/fnal.gov/usr/nova/data/flux/gsimple/nova_v06/nd/mn/rhc/gsimple_NOvA-ND_mn000z-200i_rp11_bs1.1_pnut_lowth_f11f093bbird_target_q34_00001.root /stash/pnfs/fnal.gov/usr/nova/data/flux/gsimple/nova_v06/nd/mn/rhc/gsimple_NOvA-ND_mn000z-200i_rp11_bs1.1_pnut_lowth_f11f093bbird_target_q34_00001.root
```

**Comment by alja** [comment]
What would you like that the behavior should be?
There are two potions. File can be served directly from the origin server. The second option is to exit with a file open error in a posix layer.

**Comment by illingwo** [comment]
I think the most appropriate behaviour would be to return an error. In our case the server was misconfigured; if it passed the request through we might not have noticed for some time.

On the other hand, passing it through could be useful if your cache disk drops offline.

It'd also be nice if the logging recorded the real problem. Presumably there was an EPERM when trying to create the directories; displaying that would have made it easier for us to realize there was a directory with incorrect ownership.

**Comment by bbockelm** [comment]
I would prefer that the file is served directly from the origin but a _very loud_ message logged to the server logs.

**Comment by alja** [comment]
I now checked in detail in Posix/OucCache implementation. In case missing file cache permissions, file can only be served directly. I added here link to code details of XrdPosixXroord::Open() and XrdPosixFile::Open():
https://github.com/alja/xrootd/blob/master/src/XrdPosix/XrdPosixXrootd.cc#L458
https://github.com/alja/xrootd/blob/master/src/XrdPosix/XrdPosixFile.cc#L147

You can see open will be successful in posix layer regardless of cache attach return value.

In the file caching  code I will make a fix, were I will make a clear log  message about missing permission and let client to serve data directly from origin server.
