### ISSUE TITLE
Documentation of diskUsage seems backwards

### ISSUE THREAD

**Issue by brianhlin** [xrootd/xrootd#264]
Perhaps I'm reading the documentation incorrectly but the documentation found [here](http://xrootd.org/doc/dev42/pss_config.pdf) says the following:

> diskusage fracLow fracHigh
> specified the low and high watermark that starts and suspends purging of cached blocksto free up disk space. Specify for fracLow the percentage of space in cpath that triggers purging. Specify for fracHigh the percentage of space in cpath that must be free in order for purging to stop. The default is “0.9 0.95” (i.e. 90% 95%).

I would think fracHigh would trigger the purging until the used space percentage met fracLow or is that wrong?

**Comment by alja** [comment]
@brianhlin
Yes, in this case (the default) the disk purge starts when it is more than 95% full and stops when it is 90% full.

**Comment by esindril** [comment]
@alja could you please fix the documentation? I don't know where this is stored or who actually builds it ... 

Thanks,
Elvin

**Comment by alja** [comment]
The diskusage is documented in Proxy Storage Reference guide http://xrootd.org/doc/dev4/pss_config.htm#_Toc392104463
And, in README https://github.com/xrootd/xrootd/blob/master/src/XrdFileCache/README#L121

If no one objects I will close this issue.

**Comment by esindril** [comment]
To be honest I am a bit confused. I think that the documentation in the first link is wrong. Shouldn't the **high watermark** initiate the purging and the **low watermark** stop the purging? With hmw=.9 and lmw=.7?

Also in the second link maybe you can keep the order of the two watermarks also in the description i.e.:
```bash
pfc.diskusage <lwm fraction> <hwm fraction>: low / high watermarks for disk cache purge operation (default 0.7 and 0.9)
```

**Comment by alja** [comment]
@esindril 
By mistake I referenced 4.0 documentation. Here is 4.2 link:
http://xrootd.org/doc/dev42/pss_config.htm#_Toc411973933

I will update README to have the correct default values.

**Comment by alja** [comment]
@abh3 
I've talked with Matevz and Lincoln. We agreed to document pfc.diskusage parameter in 4.3 like this:

**diskusage** [*low*[**g**|**t**]] [*high*[**g**|**t**]]

specifies the low and high watermark values that control automatic cache purging. Purging is started when disk usage reaches the high watermark and stopped when low watermark is reached.

If there is no suffix specified for the values of low and high watermark they are taken as representing a percentage of total disk space available in the caching directory.

If g or t suffix is specified the values are taken as actual disk usage in giga or tera bytes respectively.

Floating point values are supported in both cases.

**Comment by brianhlin** [comment]
That's much clearer!

**Comment by abh3** [comment]
I believe this has been corrected in the documentation.
