### ISSUE TITLE
xrdmapc should silently go instead of an error

### ISSUE THREAD

**Issue by zvada** [xrootd/xrootd#269]
Hi,

here is situation:

$ xrdmapc --list all xrdcmsglobal01.cern.ch:1094
xrdmapc: Unable to connect to xrootd.unl.edu:1094; [ERROR] Server
responded with an error: [3010] Unable to locate /; permission denied

Citing Andy:
All that means is that there are no subscribers to that cmsd. I checked and indeed that is the problem. The bug is that it should not produce this error and silently go on since that is an OK situation.

-Marian

**Comment by abh3** [comment]
Actually, the message hat should be squelched is:

xrdmapc: Unable to connect to xrdcmseu01.cern.ch:1294; [ERROR] Server
responded with an error: [3011] No servers have the file

The "permission denied" error is still a problem to be solved.

Andy

**Comment by abh3** [comment]
I am closing this ticket as after 9 years no one is complaining about this.
