### ISSUE TITLE
Compilation error when building in ubuntu 14 

### ISSUE THREAD

**Issue by peremato** [xrootd/xrootd#274]
[ 72%] Building CXX object src/CMakeFiles/XrdFileCache-4.dir/XrdFileCache/XrdFileCacheFactory.cc.o
cd /build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd-4.2.1-build/src && /usr/bin/g++   -DHAVE_ATOMICS -DHAVE_CRYPT -DHAVE_ET_COM_ERR_H -DHAVE_FSTATAT -DHAVE_GETHBYXR -DHAVE_GETIFADDRS -DHAVE_LIBZ -DHAVE_NAMEINFO -DHAVE_PROTOR -DHAVE_SENDFILE -DHAVE_SETRESUID -DHAVE_SHADOWPW -DHAVE_SIGWTI -DHAVE_SSL -DHAVE_XRDCRYPTO -DXRDPLUGIN_SOVERSION=\"4\" -DXrdFileCache_4_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D__linux__=1 -Wall -Wextra -Werror -Wno-unused-parameter -O2 -g -DNDEBUG -fPIC -I/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/.. -I/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/. -I/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src -I/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd-4.2.1-build/src -I/usr/local/include    -o CMakeFiles/XrdFileCache-4.dir/XrdFileCache/XrdFileCacheFactory.cc.o -c /build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/XrdFileCache/XrdFileCacheFactory.cc
/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/XrdFileCache/XrdFileCacheFactory.cc: In member function ‘bool XrdFileCache::Factory::Config(XrdSysLogger*, const char*, const char*)’:
/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/XrdFileCache/XrdFileCacheFactory.cc:273:60: error: format not a string literal and no format arguments [-Werror=format-security]
          loff += snprintf(&buff[loff], strlen(buff2), buff2);
                                                            ^
/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/XrdFileCache/XrdFileCacheFactory.cc:273:60: error: format not a string literal and no format arguments [-Werror=format-security]
/build/workspace/lcg_ext_dev4/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/x86_64-ubuntu14-gcc48-opt-build/externals/xrootd-4.2.1/src/xrootd/4.2.1/src/XrdFileCache/XrdFileCacheFactory.cc:284:67: error: format not a string literal and no format arguments [-Werror=format-security]
         loff += snprintf(&buff[loff], strlen(unameBuff), unameBuff);
                                                                   ^

**Comment by esindril** [comment]
This has already been fixed in 4.2.2 by the following commit: https://github.com/xrootd/xrootd/commit/d91f76f7cc7a5bb8df01929003e40e7af06c651f
