### ISSUE TITLE
Review error type on socket timeout

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#277]
XrdClXRootDTransport.cc:571 returns errSocketError when the stream times out.

XrdClAsyncSocketHandler::Event
-> XrdClAsyncSocketHandler::OnReadTimeout()
-> XrdClStream::OnReadTimeout(uint16_t)
   -> XrdClXRootDTransport::IsStreamBroken( ... ) - that creates the Status object used later on
-> XrdclStream::OnError()

And the action taken in the OnError method is basically a retry and makes no difference between the exact error type returned by the Status object. But this should be changed so as to be less ambiguous.

**Comment by alja** [comment]
FYI
When I was accessing a file from server with broken hadoop file system I had lots of socket errors and retries to connect every minute. The retries lasted for 30 min, until request time out elapsed. Setting  XRD_REQUESTTIMEOUT environment  variable to smaller value solved my problem.

**Comment by xrootd-dev** [comment]
Yes, the default request timeout is set to 30 minutes. Unfortuantely, 
there is no single value that is good for every type of circumstance. So, 
we chose one that would cover the most cases in a resoable amount of time 
(well, for non-interactve cases).

Andy

**Comment by abh3** [comment]
Yes, the timeouts are set to cover most batch cases. Even then some people complain they are too small. I do agree, that we need better documentation on hw to change the defaults.

**Comment by abh3** [comment]
Yes, the timeouts are set to cover most batch cases. Even then some people complain they are too small. I do agree, that we need better documentation on hw to change the defaults.

**Comment by esindril** [comment]
I will leave this as is, since the `errSocketError` code is actually used in the XrdClFileStateHandler to decide whether the operation should be recovered or not. 
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClFileStateHandler.cc#L1400

**Comment by abh3** [comment]
OK, I see your point but that, I must say, is very ugly.
