### ISSUE TITLE
re-resolving upstream redirector IP

### ISSUE THREAD

**Issue by ivukotic** [xrootd/xrootd#280]
From time to time our redirectors change IP. It would be great if the endpoints could re-resolve IP addresses of their managers from time to time and not only at the start up.

**Comment by jmuf** [comment]
a good moment to re-resolve might be whenever the connection to one of the registered upstream cmsd (or actually anything daemon->daemon) drops (unless this could happen in a tight loop).

**Comment by abh3** [comment]
I checked the code and the cmsd does re-resolve addresses when initiating a connection. The problem appears to be that the new addresses are not being propagated very quickly.
