### ISSUE TITLE
no server available

### ISSUE THREAD

**Issue by vveckaln** [xrootd/xrootd#282]
Hello!
I have encountered a new type of situation using xrootd - no server available:

[vveckaln@lxplus0159 TauAnalysis]$ xrdcp -d 1 -f root://xrootd.unl.edu//store/mc/RunIIWinter15GS/TT_TuneCUETP8M1_13TeV-powheg-pythia8/GEN-SIM/MCRUN2_71_V1-v1/10000/0228E2F1-EEC7-E411-A5D3-B083FED177B1.root /dev/null
[2015-08-28 16:29:52.180458 +0200][Error  ][XRootD            ] [cms-xrd-transit.cern.ch:1094] Handling error while processing kXR_open (file: /store/mc/RunIIWinter15GS/TT_TuneCUETP8M1_13TeV-powheg-pythia8/GEN-SIM/MCRUN2_71_V1-v1/10000/0228E2F1-EEC7-E411-A5D3-B083FED177B1.root?tried=+1098xrdcmsglobal02.cern.ch,+1213cmsxrootd1.fnal.gov1213xrootd.unl.edu, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ): [ERROR] Error response.
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3011] No servers are available to read the file.

I am trying to access a sample very important for my analysis and all of the files are on the server xrootd.unl.edu.
What is the action required from me or should I just wait until the server becomes available?
What could be the root of this problem?
Thanks,
Viesturs

**Comment by bbockelm** [comment]
Hi Viesturs,

I think this is a CMS-specific issue, not a problem for the Xrootd software.  Please file a ticket at:

https://ggus.eu/?mode=ticket_cms

to reach the CMS transfer team.

Brian

**Comment by zvada** [comment]
Hi Viestrus,

Brian is right, have you reached CMS Transfer Team via GGUS about this or do you need further help? Also, this is useful CMS user guide unless you are aware of it:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookXrootdService

Thanks,
Marian

**Comment by abh3** [comment]
This is a cms issue not an xroot issue.

**Comment by vveckaln** [comment]
I think the problem was not providing

--voms cms

to

voms-proxy-init

due to my ignorance. I also did not set the environmental variable 
X509_USER_PROXY storing the non-standard proxy location.

Viesturs

A 2015-09-03 22:10, Andrew Hanushevsky escreveu:
