### ISSUE TITLE
false missing certificate notification

### ISSUE THREAD

**Issue by vveckaln** [xrootd/xrootd#283]
Hello,
From time to time I receive notification as if my certificate did not exist, although I am able to access the files at the next try:
150901 18:38:00 4998 crypto_X509CreateProxy: Your identity: /C=PT/O=LIPCA/O=LIP/OU=Lisboa/CN=Viesturs Veckalns
140662672606976:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:647:Expecting: CERTIFICATE
140662672606976:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:647:Expecting: ANY PRIVATE KEY

What could be the reason? 
Cheers,
Viesturs

**Comment by vveckaln** [comment]
After some observations, I think the reason stems from creating the proxy in a non-standard location (different from /tmp/x509up_u<user_id>) via 
voms-proxy-init <COMMANDS>  --out <NON_STANDARD_LOCATION>
If a new process is forked where this proxy will be used then an environmental variable X509_USER_PROXY should be set in that process like this:
export X509_USER_PROXY=<NON_STANDARD_LOCATION>
If this environmental variable is not set, then the proxy will be looked for in the standard location /tmp/x509up_u<user_id> where it might not even exist.
I am not so sure if 
voms-proxy-init --noregen
should also be supplied for that process.

Some of my other troubles posted in other threads could also be linked to creating the proxy in a non-standard location.
Viesturs

**Comment by abh3** [comment]
I believe the issue has been explained, so I am closing this ticket. Please reopen it if this is still a problem.
