### ISSUE TITLE
OS Error: File exists

### ISSUE THREAD

**Issue by vveckaln** [xrootd/xrootd#284]
Hello!
Here is another error that I sometimes receive:

xrdcp root://xrootd.unl.edu//store/mc/RunIISpring15DR74/TT_TuneZ2star_13TeV-powheg-pythia6-tauola/MINIAODSIM/Asympt50ns_MCRUN2_74_V9A-v3/00000/22A50E5E-AF08-E511-8380-B8CA3A70A410.root /dev/null       
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] OS Error: File exists

What could be the reason?
Cheers,
Viesturs

**Comment by ljanyst** [comment]
Well, the target file exists, so you need to use the `-f` flag to overwrite.

**Comment by abh3** [comment]
Missing option to over-write an existing file. This is not a bug.

**Comment by vveckaln** [comment]
Well, then I am surprised that the file already exists in the directory /dev/null
Viesturs

**Comment by abh3** [comment]
This is a long standing quibble. Technically, /dev/null already exists and 
you can't really place any files in it. You can just write to it. So, the 
-f option is needed. The quibble is that xrdcp should recognize /dev/null 
as a special file and not require the -f option.

Andy

**Comment by ljanyst** [comment]
`xrdcp` warns you if you overwrite existing files. `/dev/null` is not a directory, it is a file that happens to represent a character device that will accept an infinite amount of data, the same as `/dev/sda1` is a file representing a block device - the first partition of your SCSI disk. I don't see why `/dev/null` should be treated any different than other files.

**Comment by abh3** [comment]
Hi Lukasz,

The only reason to treat /dev/null differently is because you really can't 
remove it. It's a special system file and because it is special many 
people think it should be treated as such. So, the -f flag is sort of 
strange in this particular case.

Andy

**Comment by ljanyst** [comment]
OK, I see.

Just for the sake of the argument, you also cannot remove a normal file if you don't have write permissions to the directory it's in.

```
]==> mkdir test
]==> touch test/asdf
]==> chmod 500 test
]==> rm test/asdf 
rm: cannot remove ‘test/asdf’: Permission denied
]==> echo "asdf" > test/asdf
]==> cat test/asdf 
asdf
```

You'll obviously do whatever you want. I am just a consistency zealot :)

**Comment by abh3** [comment]
Well, yes. We will likely keep it the way it is :-)

Andy
