### ISSUE TITLE
XrdOfsTPCAuth deadlock

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#290]
The XrdOfsTPCAuth code deadlocks for expired TPC transfers for which the client probably went away. I have the complete gdb trace but below is the thread responsible to taking the lock and never releasing it. The rest of the 1000+ threads dealing with TPC transfers are blocked while acquiring the mutex.

Thread 1093 (Thread 0x7f6def411700 (LWP 7666)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:86
#1  0x0000003def035079 in Wait (this=0x7f6b78014270, retVal=-1, eValue=13, eText=0x3def4a1d25 "tpc authorization expired", Path=0x7f6b78025060 "/srv/castor/02/96/1456266296@castorns.21055927776") at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.hh:345
#2  XrdOucCallBack::Reply (this=0x7f6b78014270, retVal=-1, eValue=13, eText=0x3def4a1d25 "tpc authorization expired", Path=0x7f6b78025060 "/srv/castor/02/96/1456266296@castorns.21055927776") at /usr/src/debug/xrootd/xrootd/src/XrdOuc/XrdOucCallBack.cc:95
#3  0x0000003def46eb66 in XrdOfsTPCInfo::Reply (this=0x7f6b78024fa8, rC=<value optimized out>, eC=<value optimized out>, eMsg=<value optimized out>, mP=<value optimized out>) at /usr/src/debug/xrootd/xrootd/src/XrdOfs/XrdOfsTPCInfo.cc:108
#4  0x0000003def46deb8 in XrdOfsTPCAuth::Expired (this=0x7f6b78024fa0, Dst=0x3def4a1d87 "localhost", cnt=0) at /usr/src/debug/xrootd/xrootd/src/XrdOfs/XrdOfsTPCAuth.cc:153
#5  0x0000003def46e004 in XrdOfsTPCAuth::RunTTL (Init=<value optimized out>) at /usr/src/debug/xrootd/xrootd/src/XrdOfs/XrdOfsTPCAuth.cc:278
#6  0x0000003def46e0fb in XrdOfsTPCAuthttl (pp=<value optimized out>) at /usr/src/debug/xrootd/xrootd/src/XrdOfs/XrdOfsTPCAuth.cc:62
#7  0x0000003def0263af in XrdSysThread_Xeq (myargs=0x21f1b60) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.cc:86
#8  0x000000336cc07a51 in start_thread (arg=0x7f6def411700) at pthread_create.c:301
#9  0x000000336c8e89ad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

**Comment by abh3** [comment]
The previous patch was misguided so we are opening this up again. The critical question is where does the deadlock happen? On the source or the destination server? I can see various scenarios but none should happen and one clearly does. So, destination or source deadlock?

**Comment by esindril** [comment]
So the deadlock happens at the source of the TPC transfer. Attached is a gdb trace of such a deadlocked server. Thread 1278 is the one blocked in the `Wait` with the mutex lock taken which then prevents all other TPC transfers to advance.
[gdb_22359.txt](https://github.com/xrootd/xrootd/files/6633/gdb_22359.txt)

**Comment by esindril** [comment]
Hi Andy, 

First of all, thanks for the suggestion related to the SFS_STARTED return code for the `XrdOfsFile::open` function. I was able to reliably reproduce this "deadlock" in Castor by delaying the initiator of the TPC transfer, therefore having the destination connect to the source but without a `tpc.key` registered for the transfer. At this point the OFS layer replies with SFS_STARTED but I was converting it to SFS_ERROR in the Castor plugin. Now, this is well understood and fixed. 

As a side node: the CastorOfs plugin actually inherits from the default OFS plugin, therefore the `error` object is the same and I don't need to call it explicitly. But nevertheless, thanks for the detailed explanation.

Now, after fixing the problems in the Castor plugin the server would not deadlock anymore but the slow TPC transfers would still not succeed - here by slow I mean a transfer in which the destination would first receive a SFS_STARTED response. When such a response is given there a several things happening:

- there is kXR_waitresp message sent to the client which is completely ignored. 
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClStream.cc#L449
The time value specified by this response is not taken into consideration at all since the message is discarded. I believe the follwoing line has been modified recently by adding the `Ignore` flag:
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDMsgHandler.cc#L150
Event without the `Ignore` flag the timeout value would still be discarded but it would at least print some info about it here:
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDMsgHandler.cc#L563
At the moment such a `kXR_waitresp` message appears in the logs of the client as:
```bash
[2015-10-06 00:38:03.422196 +0200][Dump   ][XRootDTransport   ] [msg: 0xf8000b70] Expecting 4 bytes of message body
[2015-10-06 00:38:03.422228 +0200][Dump   ][AsyncSock         ] [lxc2dev6d1.cern.ch:1095 #0.0] Received message header for 0xf8000b70 size: 8
[2015-10-06 00:38:03.422258 +0200][Dump   ][AsyncSock         ] [lxc2dev6d1.cern.ch:1095 #0.0] Received message 0xf8000b70 of 12 bytes
[2015-10-06 00:38:03.422285 +0200][Dump   ][PostMaster        ] [lxc2dev6d1.cern.ch:1095 #0] Handling received message: 0xf8000b70.
[2015-10-06 00:38:03.422310 +0200][Dump   ][PostMaster        ] [lxc2dev6d1.cern.ch:1095 #0] Ignoring the processing handler for: 0x60dd18.
[20
```

- before the SFS_STARTED response was replied, there was a callback registered for the initial open operation which is triggered from here: https://github.com/xrootd/xrootd/blob/master/src/XrdXrootd/XrdXrootdXeq.cc#L2854
 When the callback is executed it performs specific actions depending on the initial operation. In this case i.e. for open it will send a `kXR_wait` response to the client with a value of 0. See: https://github.com/xrootd/xrootd/blob/master/src/XrdXrootd/XrdXrootdCallBack.cc#L146

- this `kXR_wait` response will actually be wrapped in a `kXR_attn` response for `kXR_asynresp`. The format of the message is here: http://www.xrootd.org/doc/dev42/XRdv300.htm#_Toc414892715

- on the client side the parsing of this message is done in here: https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDMsgHandler.cc#L258 
What happens here is that the fields specific to the `kXR_attn` response are stripped and we are only left with the so called `embeddedMsg`. 

- in our case this message is actually a `kXR_wait` response. Therefore, when processing the response we call the unmarshaling function corresponding to this type of response: https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDTransport.cc#L881
Here we expect that the message has the format for the `kXR_wait` response i.e.: http://www.xrootd.org/doc/dev42/XRdv300.htm#_Toc414892723

- but if we look at our embedded message we see that it has the following structure which represents the last 4 entries from  `kXR_attn` response:
    kXR_char  streamid[2]
    kXR_unt16 status
    kXR_int32 dlen
    kXR_char data[dlen] 

- so we are missing the seconds value which normally appears in the `kXR_wait` response. Therefore, the unmarshaling of this response fails and in the client logs one can see the following message (scroll all the way to the right for the interesting part):

```bash
[2015-10-06 00:38:07.412154 +0200][Dump   ][PostMaster        ] [lxc2dev6d1.cern.ch:1095 #0] Queuing received message: 0xf8000b70.
[2015-10-06 00:38:07.412250 +0200][Dump   ][XRootD            ] [lxc2dev6d1.cern.ch:1095] Got an async response to message kXR_open (file: /castor/cern.ch/dev/e/esindril/dir_default/test2G_1.dat?tpc.key=00060120712f64035612fbcb&tpc.org=esindril.25603@esdss001.cern.ch, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ), processing it
[2015-10-06 00:38:07.412363 +0200][Dump   ][XRootD            ] [lxc2dev6d1.cern.ch:1095] Invalid msg while unmarshalling body, resp->hdr.status=4005
[2015-10-06 00:38:07.412466 +0200][Debug  ][File              ] [0x10dde80@xroot://lxc2dev6d1.cern.ch:1095//castor/cern.ch/dev/e/esindril/dir_default/test2G_1.dat?tpc.key=00060120712f64035612fbcb&tpc.org=esindril.25603@esdss001.cern.ch] Open has returned with status [FATAL] Invalid message
[2015-10-06 00:38:07.412497 +0200][Debug  ][File              ] [0x10dde80@xroot://lxc2dev6d1.cern.ch:1095//castor/cern.ch/dev/e/esindril/dir_default/test2G_1.dat?tpc.key=00060120712f64035612fbcb&tpc.org=esindril.25603@esdss001.cern.ch] Error while opening at lxc2dev6d1.cern.ch:1095: [FATAL] Invalid message
```
So, in this case the transfer will fail with a `[FATAL] Invalid message. What is the expected behaviour for this? Should the unmarshaling be adapted for `kXR_attn` messages?

Thanks,
Elvin

**Comment by esindril** [comment]
The third line in the last log output is a message which I added to the client code so don't waste time looking for it.

**Comment by abh3** [comment]
Hi Elvin,

When I traced through the code, the wait time inthe waitresp is actually 
set in the message handler early on and that value controls the wait (at 
least that is what I saw). So, having it ignored should be just fine in 
this context. The SFS_WAIT with 0 seconds is simply our way of saying 
retry the operation. You should apply my latest fix (f8ec5c61d) as the TPC 
code was indeed sending the message back without a value (well, it was 
actually sending an SFS_OK which has no wait value). I caught that and it 
should have made the client complain about an invalid message. Anyway, 
with those fixes my stuff works here.

Andy

**Comment by esindril** [comment]
Hi Andy, 

Indeed using the current HEAD of the `master` the problem of the `Invalid message` goes way. At this point the client received a `kXR_wait` response but for 1 second and not for 0 seconds as it is specified here: https://github.com/xrootd/xrootd/blob/master/src/XrdXrootd/XrdXrootdCallBack.cc#L141

The client logs look like this:
```bash 
[2015-10-06 09:45:29.953368 +0200][Dump   ][XRootDTransport   ] [msg: 0xb8000b70] Expecting 20 bytes of message body
[2015-10-06 09:45:29.953429 +0200][Dump   ][AsyncSock         ] [lxc2dev6d1.cern.ch:1095 #0.0] Received message header for 0xb8000b70 size: 8
[2015-10-06 09:45:29.953458 +0200][Dump   ][AsyncSock         ] [lxc2dev6d1.cern.ch:1095 #0.0] Received message 0xb8000b70 of 28 bytes
[2015-10-06 09:45:29.953483 +0200][Dump   ][PostMaster        ] [lxc2dev6d1.cern.ch:1095 #0] Queuing received message: 0xb8000b70.
[2015-10-06 09:45:29.953572 +0200][Dump   ][XRootD            ] [lxc2dev6d1.cern.ch:1095] Got an async response to message kXR_open (file: /castor/cern.ch/dev/e/esindril/dir_default/test2G_1.dat?tpc.key=000e6309712f6faf56137c15&tpc.or
g=esindril.28591@esdss001.cern.ch, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ), processing it
[2015-10-06 09:45:29.953646 +0200][Dump   ][XRootD            ] [lxc2dev6d1.cern.ch:1095] Got kXR_wait response of 1 seconds to message kXR_open (file: /castor/cern.ch/dev/e/esindril/dir_default/test2G_1.dat?tpc.key=000e6309712f6faf56137c15&tpc.org=esindril.28591@esdss001.cern.ch, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ): 
```

I've looked deeper into this and the problem actually comes for the latest commit. Therefore, instead of using commit f8ec5c61d2071dd41e, I used the following patch:

```bash 
diff --git a/src/XrdOfs/XrdOfsTPCAuth.cc b/src/XrdOfs/XrdOfsTPCAuth.cc
index b1f7f62..2367717 100644
--- a/src/XrdOfs/XrdOfsTPCAuth.cc
+++ b/src/XrdOfs/XrdOfsTPCAuth.cc
@@ -87,7 +87,7 @@ int XrdOfsTPCAuth::Add(XrdOfsTPC::Facts &Args)
       {if (aP->Info.cbP)
           {aP->expT = expT;
            aP->Next = authQ; authQ = aP;
-           aP->Info.Reply(SFS_STALL, 0, "", &authMutex);
+           aP->Info.Reply(SFS_OK, 0, "", &authMutex);
            return 1;
           } else {
            authMutex.UnLock();
diff --git a/src/XrdXrootd/XrdXrootdCallBack.cc b/src/XrdXrootd/XrdXrootdCallBack.cc
index aaf300f..6d37572 100644
--- a/src/XrdXrootd/XrdXrootdCallBack.cc
+++ b/src/XrdXrootd/XrdXrootdCallBack.cc
@@ -143,7 +143,7 @@ void XrdXrootdCBJob::DoIt()
 // the client to wait zero seconds. Protocol demands a client retry.
 //
    if (SFS_OK == Result)
-      {if (*(cbFunc->Func()) == 'o') cbFunc->sendResp(eInfo, kXR_wait, 0);
+     {if (*(cbFunc->Func()) == 'o') {int rc = 0; cbFunc->sendResp(eInfo, kXR_wait, &rc);}
           else {if (*(cbFunc->Func()) == 'x') DoStatx(eInfo);
                 cbFunc->sendResp(eInfo, kXR_ok, 0, eInfo->getErrText(),
                                                    eInfo->getErrTextLen());
```

This I believe fixes the underlying problem as in the `XrdXrootdCBJob::DoIt` function there is a special code path dealing with async responses for open which is not used if we return SFS_STALL in the `XrdOfsTPCAuth::Add`. The `Invalid message` was coming form the fact that the `XrdXrootdCBJob::sendResp` called above, was not properly building the message.

Let me know you thoughts on this and if it makes sense I can push it to the master.

Thanks,
Elvin

**Comment by esindril** [comment]
Hi Andy, 

After looking over the code, I get you point related to the `Ignore` flag but this also means that this branch of the `switch` is dead code: https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDMsgHandler.cc#L560

Since such a response as you said in the comments is handled synchronously here: https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClStream.cc#L449

All this is true if a `kXR_attn` response can not contain an embedded `kXR_waitreps`. Can it? If not, what do you think about removing the dead case branch?

Elvin

**Comment by abh3** [comment]
Hi Elvin,

Well, nothing prohibits a kXR_attn from sending a kXR_waitresp. Of course, that would be a silly thing to do and we could just say it’s not allowed in the documentation and if it does happen declare an error. I left the dead code in there because I could not guarantee it wouldn’t be triggered at some point in the future (I guess that was good because of the problem you point out). Anyway, what do you think – prohibit attn+waitresp?

Andy

**Comment by esindril** [comment]
Hi Andy, 

It's no harm in having it there, maybe it will be useful in the future - but I will still add a comment to explain that we expect the handling of such messages to be done in the layer below. Just to make things clearer when someone reads the code.

When it comes to the `sendResp` issue detailed 3 posts above, there are several places in the code where the function is called with a direct 0 value for a `kXR_wait` response that probably should also be reviewed. I just fixed the one related to the callback for open operations.

Elvin

**Comment by abh3** [comment]
Hi Elvin,

Indeed, what you discovered is the problem. I wonder when that code changed as the open retry has been used for the longest time in sites that do staging. It may be that it was always wrong but the old client was more forgiving than the new one. Anyway, please push your fix.

Andy

**Comment by abh3** [comment]
Hi Elvin,

I only found one other place with sendResp()+kXR_wait and it looks fine to me. Greping for _wait I could not find any other combination with zero. Hmmm, what were you looking at?

Andy

**Comment by esindril** [comment]
Hi Andy, 

You are right this is the only problematic place ... it was my `grep ` which misled me. I will push this fix and also add some comments for the `kXR_waitresp`.

Elvin

**Comment by abh3** [comment]
Thanks Elvin! Please close out this problem with your push.

Andy

**Comment by ljanyst** [comment]
Why do you need to handle `kXR_waitresp` synchronously? The only reason for doing this that I can see, is when the server sends the corresponding `kXR_attn` immediately after `kXR_waitresp`. Which makes it kind of pointless to send `kXR_waitresp` in the first place.

**Comment by abh3** [comment]
You need to do this because the corresponding response to the waitresp may arrive before the waitresp thread runs and async processing order is not guaranteed. If the reply is processed before the waitresp is processed you get a SEGV. That's just the way the code works.

**Comment by ljanyst** [comment]
I agree that it's a security bug that needed fixing. What I was asking is: why did we end up in this situation in the first place. By sending `kXR_waitresp` the server essentially indicates to the client that it is impossible to answer immediately and the client may need to wait a long time for the answer. The server then answers so fast that it causes a data race in the client, it's a bit strange :)

By returning `Take` the handler indicates to the queuing system that it wants to consume the current message and the message should not be given to any other handler. By returning `Ignore` the handler tells the queuing system that it is not interested and other handlers should be polled. Returning both `Take` and `Ignore` at the same time is a bit confusing. It would be probably better to add another flag called `Sync` that would cause the queuing system to call the handler from current context instead of scheduling the asynchronous job. This way Elvin probably wouldn't have to add clarifying comments :)

**Comment by xrootd-dev** [comment]
The problem here is that on a very heavily loaded client (think proxy 
server) one can get a waitresp and that waitresp isn't dispatched for for 
a relatively long time due to thread contention. Unfortunately, the 
response comes in during that time. It can (and does) happen. Anyway, he 
server is free to answer any way it wants, including sending a waitresp 
followed almost immediately with a response for all sorts of reasons. 
Setting up a race condition does not help. I agree with you that adding 
a new flag would have been better but I was working within the existing 
parameters and tried to minimize changes to rather complicated code.
