### ISSUE TITLE
xrdcp add option/env var to disable recovery

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#298]
Add environment variable to disable the read/write recovery mechanism.

**Comment by ljanyst** [comment]
It was there already, although in a different form and settable for source and destination separately, which is probably what you want...

https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClFileStateHandler.cc#L416

**Comment by esindril** [comment]
Thanks @ljanyst for the tip that probably only you were aware of! :) Even so, this mechanism is totally different from what the `xrdcp` usually has . I would still keep the patch since the env variable approach can also be applied separately to the source (read) and/or destination(write), and is the common way to tweak things for `xrdcp`.

**Comment by ljanyst** [comment]
There's nothing wrong with the envvar. Just pointing out.

**Comment by ljanyst** [comment]
It was done this way for Andreas, who wanted to recover some writes in EOS but not the others.

**Comment by esindril** [comment]
Thanks for the background on this! Indeed using the opaque info is a bit more convenient when using the XrdCl API directly.

**Comment by ljanyst** [comment]
I don't think there is any other way if you want to got through the POSIX layer.
