### ISSUE TITLE
Xrootd should be aware of pid_max

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#301]
The ticket #288 about RLIM_INFINITY reminded me of a separate failure mode we noticed - the system hitting pid_max.

The file `/proc/sys/kernel/pid_max` indicates the maximum number of processes on the system (in Linux, a thread is a process).  By default, this is 32k - meaning there's an implicit limit of 32k threads in a single daemon.

However, to be safe, we should probably limit the Xrootd threads to `pid_max - epsilon` (epsilon is maybe 2000) to account for the fact that there are likely other threads on the system!

**Comment by abh3** [comment]
Currently, we set the max to 64000 if infinity has been specified. You are right, it should be based on pid_max - 2000. But even then, I'd rather not have it go above 30000 regardless. NPROC is sensitive to the maximum amount of memory you have and nothing prevents an admin of ignoring that. Of course, givn that the default pid_max is typically set too 32768 and few people change that. Setting the absolute maximum to 30000 should work out just fine. That would be the simplest solution.
