### ISSUE TITLE
[xrdcp] Legacy checksum options work as desired, but not as expected

### ISSUE THREAD

**Issue by cshimmin** [xrootd/xrootd#304]
Hi,
I'm using the xrdcp client v4.2.3. According to the man page, the legacy checksum options are "equivalent" to using `--cksum`:
```
--adler
            equivalent to "--cksum adler32:print".
[...]
-md5
            equivalent to "--cksum md5:print".
```
_(minor aside: note that the man page has a typo, the CLI accepts `-adler` not `--adler`)_

However, this is not true. If try to use `--cksum` with the `--recursive` option, I get the following result:
```
xrdcp -p --cksum adler32:print --recursive some_directory root://my-server//some/other/directory/
xrdcp: Checksum with fixed value conflicts with '--recursive'.
```

whereas the following works, in that the checksum is printed after each file, even though it is running in recursive mode:
```
xrdcp -p -adler --recursive some_directory root://my-server//some/other/directory/
[[ ... its working! ]]
```

I'm thinking that maybe in the first case the error is falsely triggering on `--cksum` and assuming there is a "fixed value", even though `:print` was specified?

**Comment by simonmichal** [comment]
Hi,
Thanks for reporting this issue. 

I had a brief look at the code and it seems that -adler is equivalent to --cksum adler32 rather than --cksum adler32:print

Anyway, --cksum adler32:print should work also with -r option

**Comment by simonmichal** [comment]
Actually  -adler is equivalent to --cksum adler32:source which is not mentioned in the man pages, I have to investigate.
