### ISSUE TITLE
cryptic error message when TPC not supported

### ISSUE THREAD

**Issue by cshimmin** [xrootd/xrootd#308]
This is perhaps related to #270, but I found that when running `xrdcp --tpc only ...` with a destination that does not support TPC, I get the following rather unhelpful error message:
```
Run: [ERROR] Server responded with an error: [3011] Unable to write file; r/o file already exists.
```

It took me quite some time to find out that I can query the destination with `query config TPC`, only to learn that the destination doesn't support TPC.

I understand from #270 it's not possible to determine _beforehand_ whether TPC is supported on the destination. But is there any reason one couldn't print a more helpful message _after_, e.g. something like `The destination site does not support TPC.`?

**Comment by abh3** [comment]
This message has nothing to do with TPC support. The message should be taken literally. It means that you are trying to write a file (i.e. open in  r/w mode) and could potentially do so if it were not for the fact that some node in the cluster is exporting that very same file in r/o mode. In this case, you cannot open the file r/w.

**Comment by cshimmin** [comment]
Sorry, I'm still a bit confused. Before running `xrdcp --tpc only -p <some_source_file> <some_dest_file>`, the file does _not_ exist at all on the destination cluster at all. So how is it that a node can be already exporting it in r/o mode?

**Comment by cshimmin** [comment]
I noticed now that _after_ running the above command, the file does exist, but is 0 bytes and is listed with r/w permissions (when I log in). But I am guessing that the source site does not have write permissions on this file, so that is consistent with what you were saying.

So I think I understand now your point, but it's still a confusing message for a new user ;)

**Comment by abh3** [comment]
That I cannot tell you. However, you can always find out the state of the 
file by using xrdfs <headnode>:<port> locate -n <file>

this will tell where the file is and accessibility.

Andy
