### ISSUE TITLE
spurious mails from logrotation 'postrotate' script

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#312]
Occasionally getting mails such as the following:
```
/etc/cron.daily/logrotate:

logrotate_script: line 2: [: /var/log/xrootd/.*.log: binary operator expected
```
This comes from /etc/logrotate.d/xrootd (as shipped by /etc/logrotate.d/xrootd):
```
/var/log/xrootd/*/*.log /var/log/xrootd/*.log
{
  missingok
  nomail
  nocreate
  rotate 100
  notifempty
  daily
  compress
  postrotate
    PIPE=`dirname $1`/.`basename $1`
    if [ -p $PIPE ]; then
      /usr/bin/expect -c "set timeout 2; spawn /bin/sh -c \"echo ping > $PIPE\"; expect timeout { exit 1 } eof { exit 0 }" > /dev/null;
    fi
  endscript
}
```
Suspect that this error is due to the log file being absent at the time the 'postrotate' script runs. The script then gets passed the "raw" glob pattern '/var/log/xrootd/*.log', and when trying to guess the pipe name ends up with several items, which confuse the next line:

```
$ h='/var/log/xrootd/*.log'
$ PIPE=`dirname $h`/.`basename $h`
$ echo $PIPE
/var/log/xrootd/.*.log /var/log/xrootd/.xrootd.log
$ if [ -p $PIPE ]; then echo OK; fi
-bash: [: /var/log/xrootd/.*.log: binary operator expected
```
Suggest to at least quote "$PIPE" (possibly also the other variables), and/or review the logic (expect?)

Seen with
```
$ rpm -qf /etc/logrotate.d/xrootd
xrootd-server-4.2.3-2.CERN.el6.x86_64
```

**Comment by simonmichal** [comment]
Hi Jan,
This has been already reported by Sebastien in #302

Cheers,
Michal
