### ISSUE TITLE
xrdfs retries too aggressive on rm

### ISSUE THREAD

**Issue by sponce** [xrootd/xrootd#315]
I'm playing with an xrootd server having a ceph backend. I wrote some relatively big file (5GB) and wanted to drop it using xrdfs. One thing is that the ceph plugin to xroot is not at all optimized for deletion of big files and thus this deletion takes long (70s).

What I see on the client side is the following (note that the deletion is successful) :

# xrdfs lxbrl59a04.cern.ch:1095 rm /testbigfilenewws
[ERROR] Server responded with an error: [3011] Unable to remove /testbigfilenewws; no such file or directory

Now here is what happened on the server :

151204 16:30:20 30792 XrdInet: Accepted connection from 33@lxc2cert5-a.cern.ch
151204 16:30:20 30792 XrootdXeq: root.12416:33@lxc2cert5-a pub IPv4 login
ceph_posix_unlink : /testbigfilenewws
151204 16:31:20 30793 XrdInet: Accepted connection from 7@lxc2cert5-a.cern.ch
151204 16:31:20 30793 XrootdXeq: root.12416:7@lxc2cert5-a pub IPv4 login
151204 16:31:20 30793 root.12416:7@lxc2cert5-a XrootdProtocol: endsess 30598:33.16
151204 16:31:20 30793 root.12416:7@lxc2cert5-a XrootdProtocol: endsess 30598:33.16 rc=4 (Resource temporarily unavailable)
ceph_posix_unlink : /testbigfilenewws
ceph_posix_unlink : /testbigfilenewws
151204 16:31:25 30792 XrootdXeq: root.12416:33@lxc2cert5-a disc 0:01:05
ceph_posix_unlink : /testbigfilenewws
151204 16:31:30 30787 ofs_remove: root.12416:7@lxc2cert5-a Unable to remove /testbigfilenewws; no such file or directory
151204 16:31:30 30787 root.12416:7@lxc2cert5-a XrootdResponse: sending err 3011: Unable to remove /testbigfilenewws; no such file or directory

As you can see, the client was getting impatient and has retried the rm several times. Sadly, the last one cam just when the deletion was finally over, hence the final "File not found".

**Comment by abh3** [comment]
Hi Sebastien,

The default transaction timeout is set to 60 seconds. When reached, the 
client will reconnect the server and try again. The only solution is to up 
the timeout.

Andy

P.S. ut of curiosity,what do you have to tune in Ceph to get a round this.

**Comment by sponce** [comment]
Well, my problem is not the timeout, I find it reasonable and I'm absolutely ready to accept a timeout error when the backend takes ages to drop a file. My problem is that the client view here is that it gets an ENOENT while the file was there and the deletion was done.

Concerning your curiosity, I'm using the radosstriper library to ceph, and the implementor (a nasty guy ;-)) did not take the time to optimize the deletion. It's a simple while loop on the objects doing deletions in a row and synchronously. With 5GB and thus thousands of objects, it's not really optimal... I'll improve that in the future.

**Comment by abh3** [comment]
Hi Sebastien.

The problem here is that the deletion effectively occurred in the background while the client was reconnecting. Since xrootd is relatively stateless it would follow the client may get an ENOENT. The way we prevent this is to place the client in polling wait until the deletion has completed. Another way is to use client callbacks for long running tasks. However, “rm” does not support a callback (though we can add that pretty easily if you need it).

Andy

**Comment by sponce** [comment]
I think that for my case, the fix in ceph will be sufficient, I do not want to complicate the code with extra callbacks. But in general, this "blind" retry may reserve some surprises on calls which are not idempotent (like rm).

**Comment by abh3** [comment]
OK, looks like the issue will be resolved within the ceph plugin.
