### ISSUE TITLE
Standalone xrootd server has this error in log file -  cms_Open: Unable to connect socket...

### ISSUE THREAD

**Issue by dougbenjamin** [xrootd/xrootd#317]
Hi
I have a stand alone xrootd data server with this configuration file -

set xrdr = t3nfs.physics.nyu.edu
set exportpath = /atlas
all.export $(exportpath)
all.adminpath /var/spool/xrootd/admin
xrootd.fslib /usr/lib64/libXrdOfs.so
xrd.port 1094 if exec xrootd
all.role server
xrootd.chksum max 10 adler32 /usr/bin/xrdadler32
oss.space public /export/data1 xa
oss.space public /export/data2 xa
oss.space public /export/data3 xa
oss.space public /export/data4 xa
oss.space public /export/data5 xa
oss.space public /export/data6 xa
oss.usage log /var/log/xrootd
xrootd.seclib /usr/lib64/libXrdSec.so
sec.protocol /usr/lib64 unix
acc.authdb /export/share/atlas/xrootd/auth_file_nfs
ofs.authorize 
sec.protbind *.physics.nyu.edu unix
xrd.network routes split use em1,em2

I see these error messages in the xrootd.log 

151215 15:32:06 19447 cms_Open: Unable to connect socket to /var/spool/xrootd/admin/.olb/olbd.admin; connection refused
151215 15:33:16 19447 cms_Open: Unable to connect socket to /var/spool/xrootd/admin/.olb/olbd.admin; connection refused
151215 15:34:26 19447 cms_Open: Unable to connect socket to /var/spool/xrootd/admin/.olb/olbd.admin; connection refused
151215 15:35:36 19447 cms_Open: Unable to connect socket to /var/spool/xrootd/admin/.olb/olbd.admin; connection refused
151215 15:36:46 19447 cms_Open: Unable to connect socket to /var/spool/xrootd/admin/.olb/olbd.admin; connection refused
151215 15:37:56 19447 cms_Open: Unable to connect socket to /var/spool/xrootd/admin/.olb/olbd.admin; connection refused

How can I make them go away.  cmsd is not running on the data sever

**Comment by xrootd-dev** [comment]
Simply delete

all.role server

The "role" tells xrootd it is running in a cluster. A cmsd is needed to 
cluster servers, so the expectation is taht one is runnng. Since you are 
not clustering this server (ie. it's standalone) it has no cluster role. 
Hence, do not specify that directive.

Andy

**Comment by dougbenjamin** [comment]
Hi Andy,

    Thanks... perhaps some words in this manual at this section.

http://xrootd.org/doc/prod/cms_config.htm#_Toc339484335

Stating that stand alone (unclustered) data servers do not need the
all.role directive.

Doug

**Comment by ivukotic** [comment]
Hi,

would the same be true for a standalone caching proxy server?

Ilija

On Dec 15, 2015, at 18:21 , dougbenjamin <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Andy,

Thanks... perhaps some words in this manual at this section.

http://xrootd.org/doc/prod/cms_config.htm#_Toc339484335

Stating that stand alone (unclustered) data servers do not need the
all.role directive.

Doug

**Comment by abh3** [comment]
Yes, that would be true for a standalone proxy cache. Also, in reference 
to Doug's point. The cms manal is only relevant for clustered 
configurations. That is why the role directive is *only* mentioned in that 
manual. I do agree it might be difficult to connect the dots here so I 
will add additional wordage.

Andy

**Comment by abh3** [comment]
The documentation has been updated to explicit say you shouldn't use this directive for stand-alone servers. Please note that this directive was documented on the cmsd reference and when setting up a stand-alone server one should not have consulted that document as it's only meant for setting up clustered servers. Needless to say, I don't think this will solve the problem which appears to be a copy-paste configuration issue.
