### ISSUE TITLE
kXR_dirlist request format backwards compatibility and path length limitations

### ISSUE THREAD

**Issue by gbehrmann** [xrootd/xrootd#332]
I got a question regarding the XRootd Protocol Specification version 3.0.0. It specifies the kXR_dirlist request format as:

    kXR_char   streamid[2]
    kXR_unt16  kXR_dirlist
    kXR_char   reserved[15]
    kXR_char   plen                
    kXR_int32  options            
    kXR_char   path[plen]

while the Xrootd Protocol Specification version 2.9.9 lists the request format as:

    kXR_char   streamid[2]
    kXR_unt16  kXR_dirlist
    kXR_char   reserved[16]       
    kXR_int32  plen 
    kXR_char   path[plen]

The motivation for the change is clearly the addition of an options field, however the two records as documented in the specification are incompatible. Note how the path length field in 2.9.9 is at offset 20 and is 4 bytes long, while in 3.0.0 is is at offset 19 and 1 byte long.

Is this a bug in the specification or is this indeed the intended format? If so, does that mean that xrootd 3.0.0 (the protocol) is limited to paths shorter than 255 bytes, and how is a server to provide backwards compatibility with older clients?

**Comment by abh3** [comment]
Clearly, this is a documentation typo (reversed names) and I will correct it. The actual format is:

kXR_char   streamid[2]
kXR_unt16  kXR_dirlist
kXR_char   reserved[15]
kXR_char   options
kXR_int32  plen
kXR_char   path[plen]

**Comment by gbehrmann** [comment]
Thanks. I guessed as much, but wasn't certain whether the options field would be 8 bit or more (for some other requests it is wider). I could have checked the source, but there is value in being able to implement a protocol purely from spec.
