### ISSUE TITLE
Character encoding for paths and file names

### ISSUE THREAD

**Issue by gbehrmann** [xrootd/xrootd#333]
Hi,

The question was raised within the dCache team how xrootd handles non-ASCII characters in file names and paths. The spec doesn't say anything in particular about UTF8 or ASCII encoding, so I wonder if you have a recommendation regarding what to do with non-ascii characters.

Thanks,

Gerd

**Comment by abh3** [comment]
You are correct that the spec does not explicitly state the encoding. However, it is implied in

http://xrootd.org/doc/dev42/XRdv300.htm#_Toc414892705

with the conclusion that paths are plain old ASCII with certain characters outlawed. By implication, it would include non-ASCII characters. I must admit we have gone ying and yang over this and current implementation does not fully enforce this (which some people like and some do not). Technically, a path should be rejected as described in the above section. We have never gotten any request to support more than this. If we get a significant desire we could add it; but that seems unlikely given how people interpret paths.

**Comment by gbehrmann** [comment]
Excellent - thank you.
