### ISSUE TITLE
Unused parameters in XrdSecInterface.hh

### ISSUE THREAD

**Issue by bastianbeischer** [xrootd/xrootd#337]
I'm getting the following warnings when building ROOT against xrootd version ae07ce1 (master branch)

It would be great if these could be fixed.

> In file included from /home/beischer/abs/root6/src/root/proof/proofd/src/XrdProofConn.cxx:47:0:
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:193:40: warning: unused parameter ‘inbuff’ [-Wunused-parameter]
 virtual int     Encrypt(const char    *inbuff,  // Data to be encrypted
                                        ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:194:40: warning: unused parameter ‘inlen’ [-Wunused-parameter]
                               int      inlen,   // Length of data in inbuff
                                        ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:195:40: warning: unused parameter ‘outbuff’ [-Wunused-parameter]
                         XrdSecBuffer **outbuff  // Returns encrypted data
                                        ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:210:38: warning: unused parameter ‘inbuff’ [-Wunused-parameter]
 virtual int     Decrypt(const char  *inbuff,   // Data to be decrypted
                                      ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:211:38: warning: unused parameter ‘inlen’ [-Wunused-parameter]
                               int    inlen,    // Length of data in inbuff
                                      ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:212:38: warning: unused parameter ‘outbuff’ [-Wunused-parameter]
                       XrdSecBuffer **outbuff   // Buffer for decrypted data
                                      ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:227:35: warning: unused parameter ‘inbuff’ [-Wunused-parameter]
 virtual int     Sign(const char  *inbuff,   // Data to be signed
                                   ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:228:35: warning: unused parameter ‘inlen’ [-Wunused-parameter]
                            int    inlen,    // Length of data in inbuff
                                   ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:229:35: warning: unused parameter ‘outbuff’ [-Wunused-parameter]
                    XrdSecBuffer **outbuff   // Buffer for the signature
                                   ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:245:37: warning: unused parameter ‘inbuff’ [-Wunused-parameter]
 virtual int     Verify(const char  *inbuff,   // Data to be decrypted
                                     ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:246:37: warning: unused parameter ‘inlen’ [-Wunused-parameter]
                              int    inlen,    // Length of data in inbuff
                                     ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:247:37: warning: unused parameter ‘sigbuff’ [-Wunused-parameter]
                        const char  *sigbuff,  // Buffer for signature
                                     ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:248:37: warning: unused parameter ‘siglen’ [-Wunused-parameter]
                              int    siglen)   // Length if signature
                                     ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:264:37: warning: unused parameter ‘buff’ [-Wunused-parameter]
 virtual int     getKey(char *buff = 0, int size = 0) {return -ENOTSUP;}
                                     ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:264:51: warning: unused parameter ‘size’ [-Wunused-parameter]
 virtual int     getKey(char *buff = 0, int size = 0) {return -ENOTSUP;}
                                                   ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:276:30: warning: unused parameter ‘buff’ [-Wunused-parameter]
 virtual int     setKey(char *buff, int size) {return -ENOTSUP;}
                              ^
/opt/xrootd/4.2.3.2.CERN.130.gae07ce1-git/include/xrootd/XrdSec/XrdSecInterface.hh:276:40: warning: unused parameter ‘size’ [-Wunused-parameter]
 virtual int     setKey(char *buff, int size) {return -ENOTSUP;}

**Comment by xrootd-dev** [comment]
Hi,

  Could you please give details on the OS and its version and on the compiler and its version?

  Thanks,

  Gerardo GANIS
  CERN, PH Dept, SFT group
  gerardo.ganis@cern.ch
  tel/cell: (+41) 22 767 6439 / 75 411 1128

**Comment by bastianbeischer** [comment]
This is with Arch Linux x86_64, GCC 5.3.0.

g++ --version gives:

`g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Anything else? :)

**Comment by abh3** [comment]
Hi Bastian,

Ah, yes, I thought we had corrected those everywhere they occur. 
Apparently, this slipped through the cracks which is suprising. Anyway, it 
will be corrected.

Andy

**Comment by ljanyst** [comment]
https://github.com/xrootd/xrootd/pull/323

**Comment by ljanyst** [comment]
See this PR: https://github.com/xrootd/xrootd/pull/323

**Comment by bastianbeischer** [comment]
Yes, I can understand why this PR added the parameters back for doxygen.

Unfortunately I think there's no way to refer to the parameter names in the doxygen docu using 'param[in]' etc when the actual parameter names are removed / commented out, safe for preprocessor magic just for doygen (#ifdef DOXYPROCESSING - see also http://doxygen.10944.n7.nabble.com/commented-function-parameters-td3718.html)

You could of course (void) cast the unused arguments before returning ENOTSUP...

**Comment by ljanyst** [comment]
Yes, void casting is the way to go.

**Comment by abh3** [comment]
Yes, I see now what happened. A patch witn unintended side-effects. This 
will be fixed. Thanks for pointing it out.

Andy
