### ISSUE TITLE
readdir_r is deprecated

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#339]
In the latest glibc headers (2.24) the readdir_r and readdir64_r functions have been marked deprecated.

https://sourceware.org/bugzilla/show_bug.cgi?id=19056

Since xrootd uses -Werror, this causes xrootd to fail compilation on system that uses the latest glibc headers.

I found this on what will become Fedora 25. (Yes, Fedora 24 is not yet released, so this is for the release after the next release.)

~~~
/builddir/build/BUILD/xrootd-4.3.0/src/XrdSfs/XrdSfsNative.cc: In member function 'virtual const char* XrdSfsNativeDirectory::nextEntry()':
/builddir/build/BUILD/xrootd-4.3.0/src/XrdSfs/XrdSfsNative.cc:201:16: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
    if ((retc = readdir_r(dh, d_pnt, &rp)))
                ^~~~~~~~~
In file included from /usr/include/features.h:368:0,
                 from /usr/include/sys/types.h:25,
                 from /builddir/build/BUILD/xrootd-4.3.0/src/XrdSfs/XrdSfsNative.cc:30:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
~~~

There are more places that uses the functions in the code than this one.

How should this be solved? The recommendation in the glibc documentation is to use readdir instead of readdir_r, but that is not always guaranteed to be thread safe, and I don't know if something will break if it is used instead.

**Comment by ellert** [comment]
I added -Wno-error=deprecated-declarations as a workaround to get the compilation to complete.
There are 4 warnings in total:
~~~
/builddir/build/BUILD/xrootd-4.3.0/src/XrdSfs/XrdSfsNative.cc:201:16: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
/builddir/build/BUILD/xrootd-4.3.0/src/XrdSfs/XrdSfsNative.cc:201:40: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
/builddir/build/BUILD/xrootd-4.3.0/src/XrdDig/XrdDigFS.cc:243:16: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
/builddir/build/BUILD/xrootd-4.3.0/src/XrdDig/XrdDigFS.cc:243:40: warning: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Wdeprecated-declarations]
~~~

**Comment by abh3** [comment]
Yes, nice of them to deprecate a standard POSIX function with this very recent patch

https://www.sourceware.org/ml/libc-alpha/2016-02/msg00093.html

Of course, the corresponding glibc 2.24 should make readdir thread-safe or the patch doesn't make much sense (though that kind of mistake has happened before). Apparently, this was a security issue with programs passing a too small buffer. Anyway, there are several problems here, one of which is that we do not always use glibc; so the gnu approach is not portable. I don't see a good solution here. Likely, others will complain as well.

**Comment by abh3** [comment]
This has been fixed by commit 4179c7.

**Comment by rpv-tomsk** [comment]
Commit: 4179c70670d41c1ebc0efe43cca440e5491882f4
