### ISSUE TITLE
Problems with accessing files from lxplus

### ISSUE THREAD

**Issue by xealits** [xrootd/xrootd#343]
Hi,

For the last ~5 days I'm having problems with accessing files in jobs on CERN's LSF batch service. `TNetXNGFile::Open` fails with 3 types of errors:

 1. `Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/data/Run2015D/SingleMuon/MINIAOD/05Oct2015-v1/10000/D6F278BA-896F-E511-97DF-0025905A60C6.root; No such file or directory`
 2. `Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Permission denied`
 3. `Error in <TNetXNGFile::Open>: [ERROR] Operation expired`

However, some of the same jobs on the same files do pass successfully when resubmitted.

So, I tried to run plain `xrdcp` to get the files from my datasets and the result is either of:

    $ xrdcp root://xrootd-cms.infn.it//store/data/Run2015D/SingleElectron/MINIAOD/05Oct2015-v1/10000/00991D45-4E6F-E511-932C-0025905A48F2.root .
    [64MB/696.4MB][  9%][====>                                             ][264.3kB/s]  ^C
    $ xrdcp root://xrootd-cms.infn.it//store/data/Run2015D/SingleElectron/MINIAOD/05Oct2015-v1/10000/00991D45-4E6F-E511-932C-0025905A48F2.root .
    [0B/0B][100%][==================================================][0B/s]  
    Run: [ERROR] OS Error: File exists
    $ xrdcp root://xrootd-cms.infn.it//store/data/Run2015D/SingleElectron/MINIAOD/05Oct2015-v1/10000/00991D45-4E6F-E511-932C-0025905A48F2.root .
    160314 18:16:38 24962 secgsi_ProtocolgsiInit: unsupported debug value from env XrdSecDEBUG: 0 - setting to 1
    160314 18:16:38 24962 secgsi_InitOpts: *** ------------------------------------------------------------ ***
    160314 18:16:38 24962 secgsi_InitOpts:  Mode: client
    160314 18:16:38 24962 secgsi_InitOpts:  Debug: 1
    160314 18:16:38 24962 secgsi_InitOpts:  CA dir: /etc/grid-security/certificates/
    160314 18:16:38 24962 secgsi_InitOpts:  CA verification level: 1
    160314 18:16:38 24962 secgsi_InitOpts:  CRL dir: /etc/grid-security/certificates/
    160314 18:16:38 24962 secgsi_InitOpts:  CRL extension: .r0
    160314 18:16:38 24962 secgsi_InitOpts:  CRL check level: 1
    160314 18:16:38 24962 secgsi_InitOpts:  CRL refresh time: 86400
    160314 18:16:38 24962 secgsi_InitOpts:  Certificate: /afs/cern.ch/user/o/otoldaie/.globus/usercert.pem
    160314 18:16:38 24962 secgsi_InitOpts:  Key: /afs/cern.ch/user/o/otoldaie/.globus/userkey.pem
    160314 18:16:38 24962 secgsi_InitOpts:  Proxy file: /tmp/x509up_u47863
    160314 18:16:38 24962 secgsi_InitOpts:  Proxy validity: 12:00
    160314 18:16:38 24962 secgsi_InitOpts:  Proxy dep length: 0
    160314 18:16:38 24962 secgsi_InitOpts:  Proxy bits: 512
    160314 18:16:38 24962 secgsi_InitOpts:  Proxy sign option: 1
    160314 18:16:38 24962 secgsi_InitOpts:  Proxy delegation option: 0
    160314 18:16:38 24962 secgsi_InitOpts:  Allowed server names: [*/]<target host name>[/*]
    160314 18:16:38 24962 secgsi_InitOpts:  Crypto modules: ssl
    160314 18:16:38 24962 secgsi_InitOpts:  Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
    160314 18:16:38 24962 secgsi_InitOpts:  MDigests: sha1:md5
    160314 18:16:38 24962 secgsi_InitOpts: *** ------------------------------------------------------------ ***
    160314 18:16:38 24962 cryptossl_X509::IsCA: certificate has 4 extensions
    160314 18:16:38 24962 cryptossl_X509::IsCA: certificate has 11 extensions
    160314 18:16:38 24962 cryptossl_X509::IsCA: certificate has 11 extensions
    160314 18:16:38 24962 cryptossl_X509::IsCA: certificate has 9 extensions
    160314 18:16:38 24962 cryptossl_X509::IsCA: certificate has 9 extensions
    [0B/0B][100%][==================================================][0B/s]  
    Run: [FATAL] Redirect limit has been reached

-- so, first attempt is successful, the following fail with the errors.

Could you help me with the problem?
Should I report an issue in the batch service?

Regards,
Alex.

**Comment by abh3** [comment]
Hi Alex,

This is actually not he right place to post this issue as it is an operational problem not an xrootd systemic problem.  I would think there is a cms specific mailing list where this question should be posted. 

That said, the reason you got a "file exists" error is because the previous failed copy left a partial file in the destination directory. Without the '-f' option, that file cannot be replaced as a protection against over writing an existing file. Otherwise, it looks like there are problems with host xrootd-cms.infn.it.

Andy

**Comment by xealits** [comment]
Thanks,
Indeed I will contact the `xrootd-cms.infn.it` guys.

Regards,
Alex.

PS
For those who get to this issue by googling the same problem:
apparently there is `computing-tools` mailing list and [here is debug info they want to be posted there](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookXrootdService#Support).

**Comment by abh3** [comment]
Alex found a better place to post issue.
