### ISSUE TITLE
˜TLSv1_2_method was not declared in this scope

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#355]
This problem in XrdHttpProtocol.cc causes builds to fail. Specifically,

#ifdef TLS1_2_VERSION
  meth = TLSv1_2_method();

 ... it seems that TLS1_2_VERSION is defined but the function TLSv1_2_method() can't
be found

/builddir/build/BUILD/xrootd/xrootd/src/XrdHttp/XrdHttpProtocol.cc: In static member
function 'static int XrdHttpProtocol::InitSecurity()':
/builddir/build/BUILD/xrootd/xrootd/src/XrdHttp/XrdHttpProtocol.cc:1326: error:
'TLSv1_2_method' was not declared in this scope

**Comment by simonmichal** [comment]
If we check the content of /usr/include/openssl/tls1.h on a epel-5 machine (openssl-devel-0.9.8e-39.el5_11) we will find:

#define TLS1_2_VERSION                  0x0303
/* TLS 1.1 and 1.2 are not supported by this version of OpenSSL, so
 * TLS_MAX_VERSION indicates TLS 1.0 regardless of the above
 * definitions. (s23_clnt.c and s23_srvr.c have an OPENSSL_assert()
 * check that would catch the error if TLS_MAX_VERSION was too low.)
 */
#define TLS_MAX_VERSION                 TLS1_VERSION

#define TLS1_VERSION_MAJOR              0x03
#define TLS1_VERSION_MINOR              0x01

It is worth noticing what the comment says ;-) 
We need to use TLS_MAX_VERSION to check the max tls version that is supported!

Michal

**Comment by simonmichal** [comment]
so my suggestion is to replace the current conditional-compilation directives, with:

#ifndef TLS_MAX_VERSION
  eDest.Say(" warning: TLS is not available, falling back to SSL23 (deprecated).");
  meth = SSLv23_method();
#elif TLS_MAX_VERSION == TLS1_2_VERSION 
  meth = TLSv1_2_method();
  eDest.Say(" Using TLS 1.2");
#elif TLS_MAX_VERSION == TLS1_1_VERSION
  eDest.Say(" Using deprecated TLS version 1.1.");
  meth = TLSv1_1_method();
#elif TLS_MAX_VERSION == TLS1_VERSION
  eDest.Say(" Using deprecated TLS version 1.");
  meth = TLSv1_method();
#endif

**Comment by abh3** [comment]
I think this problem has been solved, has it not? Is there agreement that Michal's proposed solution works? If not, please speak up.

**Comment by xrootd-dev** [comment]
Hi Andy,

  did you accept my last pull request ? I guess so, so if it compiles then everything is fine for me.

  I will be able to check in the next few days if the updated daemon now passes
the newer rules of the cern security team.

Thank you
Fabrizio

**Comment by simonmichal** [comment]
Yep, I merged Fabrizio's pr, it compiles just fine!

Michal
