### ISSUE TITLE
http redirector and browser woes

### ISSUE THREAD

**Issue by osschar** [xrootd/xrootd#368]
1. Accessing paths on a redirector through http (browser) that do not exist in the federation get interpreted as local paths. Having export / on a redirector thus leads to being able to accessing any file on the redirector. I believe redirector should never fall back to local file system.

2. The generated html includes too many slashes when a directory is the last thing in the url and ends with a /. Also, if one access a server as http://server//foo/bar (note doulbe // after server) the links to files are broken, they point to 'foo/bar/file' (note, all slashes stripped).

**Comment by xrootd-dev** [comment]
Hi,

  are you referring to XrdHttp or something else ?

Fabrizio

Il 5/18/16 21:13, Matevž Tadel ha scritto:

**Comment by osschar** [comment]
Hi Fabrizio,

Yes, I think so :) But I don't know the details of how the things are connected under the hatch.

Matevz

**Comment by ffurano** [comment]
Any chance to have a redirector debug log for point 1 ?

**Comment by ffurano** [comment]
I also need more info for point 2, as I can't reproduce it in my test data server. You may want to try my test too, the service is open to outside:

$ davix-get http://littlexrdhttp.cern.ch:1094/dynafeds_demo/testfile3 |wc
    611    2662   19558   <-------- OK
$ davix-get http://littlexrdhttp.cern.ch:1094//dynafeds_demo/testfile3 |wc
    611    2662   19558   <-------- OK
$ davix-get http://littlexrdhttp.cern.ch:1094//dynafeds_demo//testfile3 |wc
    611    2662   19558   <-------- OK
$ davix-get http://littlexrdhttp.cern.ch:1094////////////dynafeds_demo//testfile3 |wc
    611    2662   19558   <-------- OK

**Comment by ffurano** [comment]
Instead I see the issue with the embedded HTML generation (point 2). I'll have a look at it.

**Comment by osschar** [comment]
Thanks for fixing issue #2!

I tried reproducing #1 with my own setup (redir exporting / and a single server exporting /tmp) and it indeed works as its should.

I believe the setup I was playing with earlier (and had no control over) had one server with all.export / and oss.localroot /. Sigh, sorry for misdirection.
