### ISSUE TITLE
xrootd segmenation fault

### ISSUE THREAD

**Issue by george-patargias** [xrootd/xrootd#370]
Hello, 

xrootd had a segmentation fault on our xrootd redirection server. I attach the gdb output from the dumped core and the backtrace
[xrootd_gdb_core.txt](https://github.com/xrootd/xrootd/files/274651/xrootd_gdb_core.txt)
[xrootd_gdb_backtrace.txt](https://github.com/xrootd/xrootd/files/274652/xrootd_gdb_backtrace.txt)

and copy/paste the log messages. If you could help that would be great. Many thanks! 
# In  /var/log/xrootd/manager/atlas/xrootd.log.20160516

160514 18:43:13 5124 XrdInet: Accepted connection from 471@uc3-c014.mwt2.org
160514 18:43:13 5124 XrdProtocol: matched protocol xrootd
160514 18:43:13 5124 ?:471@uc3-c014.mwt2.org XrdPoll: FD 471 attached to poller 2; num=48
160514 18:43:13 26385 XrdSched: running main accept inq=0
160514 18:43:13 2491 XrdPoll: Poller 0 enabled nobody.1084399:469@uc3-c012.mwt2.org
160514 18:43:13 2391 XrdSched: running nobody.3932624:84@uct3-c024.mwt2.org inq=0
160514 18:43:13 2391 XrootdXeq: nobody.3932624:84@uct3-c024.mwt2.org disc 0:07:44
160514 18:43:13 320 XrdPoll: Poller 2 enabled nobody.2958914:169@uct3-c026.mwt2.org
160514 18:43:13 5119 XrootdXeq: nobody.2861836:470@uct3-c028.mwt2.org pub IPv4 login as atlas001
160514 18:43:13 24149 XrdSched: running nobody.1084399:469@uc3-c012.mwt2.org inq=0
160514 18:43:13 26385 XrdInet: Accepted connection from 473@uct3-c024.mwt2.org
160514 18:43:13 3792 XrdSched: running main accept inq=0
160514 18:43:13 26385 XrdProtocol: matched protocol xrootd
160514 18:43:13 26385 ?:473@uct3-c024.mwt2.org XrdPoll: FD 473 attached to poller 0; num=49
160516 14:40:07 18407 Starting on Linux 2.6.32-573.12.1.el6.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.2.2
++++++ xrootd atlas@atlas-xrd-proxy01.gridpp.rl.ac.uk initialization started.
Config using configuration file /etc/xrd.cf
=====> xrd.port 1094
=====> all.sitename RAL-LCG2
=====> xrd.trace all
=====> xrd.report uct2-int.mwt2.org:9931 every 60s all -buff -poll sync
Config maximum number of connections restricted to 65536
160516 14:40:07 18407 XrdConfig: sendfile enabled.

I al

**Comment by xrootd-dev** [comment]
Hi George,

What version are you running? Could I also get a copy of the config file? 
We may need the core file to fully understand what happened here.

Andy

**Comment by george-patargias** [comment]
Hello Andy, 
Thanks for your reply. 
We are running v4.2.2. I attach the configuration file.
[xrd_cf.txt](https://github.com/xrootd/xrootd/files/277070/xrd_cf.txt)
The core file is 2.3 GB big; I cannot attach it. Is there any other way to send it? 

George

**Comment by abh3** [comment]
Hi George,

Just put it somewhere accessible by http for a download. Alternatively, if you turn on remote debugging, I can download it myself from the xrootd server. Let me know which you prefer and likely we should start using direct email instead of github.

Andy

**Comment by abh3** [comment]
Hi George,

Just following up as there has been a significant amount of time that has gone by. Is this still a problem for you or did you upgrade  to a newer release?

**Comment by abh3** [comment]
Hi George,

Any more news or should I close this?

**Comment by george-patargias** [comment]
Hi Andrew,

Sorry for not replying earlier. No, we haven't had this problem again.

Thanks,

George
________________________________

**Comment by abh3** [comment]
We can reopen this if it ever happens again.
