### ISSUE TITLE
Double counting with "xrd ___ queryspace / " in xrootd 4.3.0 when using a distributed file system

### ISSUE THREAD

**Issue by jknedlik** [xrootd/xrootd#375]
Hello,
I discovered the reason of a problem, we had for a little while.
We run machines using xrootd 4.3.0 data servers and a redirector on debian jessie(8.3) for our ALICE SE's (storage elements).
All of our  data-servers are using a underlying mounted distributed [Lustre](http://lustre.org/), which is why we configured our redirectors/data-manager 's config with:
`cms.dfs limit 0 lookup distrib mdhold 0 redirect immed`
But unfortunately, the ALICE Monitoring Software ["Monalisa"](https://alimonitor.cern.ch/) still reported a multiple of our storage available(storage_available * number_of_data-servers), even after changes to prevent that from happening in 4.3.0 (like in XrdCmsCluster::Space for example ) 

So, I dug a little deeper and found out, that Monalisa calls a local "sensor" ( which we cannot change ...),
which uses "xrd data-manager:1094 queryspace /" periodically to get storage information.

This in turn finally led me  to XrdClient/XrdClientAdmin.cc:
```
// Compute an estimation of the available free space in the given cachefs partition 
// The estimation can be fooled if multiple servers mount the same network storage  
bool XrdClientAdmin::GetSpaceInfo(const char *logicalname,long long &totspace,long long &totfree,long long &totused,long long &largestchunk)
```
Which is the root of our problem.
I might try and code around a bit next week.
The best thing would be, if the client could query the redirector's cms daemon, for that "isDfs"-flag and only iterate over all hosts if it is unset.
But I actually don't know if and how that can be done (or what problems might occur, if it would be implemented).
Which is why I think someone more experienced can do this or at least tell me how it is done.

Regards,
JK

**Comment by abh3** [comment]
The problem here is that you are  using the deprecated xrd command. What release are you running? The correct command to use is xrdfs. If you point it to your redirector, it should return the correct space statistics. Please let us know.

**Comment by jknedlik** [comment]
(xrootd 4.3.0, debian jessie)
Hello, thank you very much for your help!

The xrdfs command is indeed working right under 4.3.0 .
I guess we have to change some monitoring functions ( but still support legacy options... )  depending on the xrootd version in use.
This issue can be closed
