### ISSUE TITLE
"Permission denied" on deleting files

### ISSUE THREAD

**Issue by marcelkuri** [xrootd/xrootd#400]
We have an automount folder named "/atlas". Here is its "auto.fuse" file:
/atlas -fstype=fuse,rw,uid=496,allow_other,entry_timeout=8,attr_timeout=8,rdr=root://lipnode01:1094//data/xrootdfs :xrootdfs.sh

When I send command "rm file" inside this folder I receive a "Permission denied" message.

This folder has 770 permission.
The version of xrootd on the machines is v4.1.1, v4.2.2,  v4.2.3, v4.3.0.

Thanks in advance

Marcel.

**Comment by abh3** [comment]
Has this been resolved?

**Comment by wyang007** [comment]
sorry, I likely missed this one...

Like the AFS directory/file permission, the permission bit in xrootdfs mounted directory doesn't mean much. It is the Xrootd ACL that controls the permission. So uid=496 should have the permission to do the 'rm' operation in that directory.

**Comment by wyang007** [comment]
I guess this ticket is too old. If the problem persist, please re-open this ticket or open a new ticket.
