### ISSUE TITLE
XrdCl: add the capability to copy a single root file from a zip archive

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#402]
ATLAS is planning to zip small files together for storage and transfer purposes. In order to facilitate access of those files, it has been requested that xrdcp supports copying a single file from a zip archive.

**Comment by bbockelm** [comment]
Ah, what's old is new again!  (CMS did this circa 2004)

Do you envision this as a plugin or as a core functionality?

**Comment by abh3** [comment]
I think we are looking at this as core functionality. It’s widely useful.

Andy

**Comment by abh3** [comment]
Done!

**Comment by rodwalker** [comment]
xrdcp --zip DAOD_BPHY5.11854502._000301.pool.root.1 root://bohr3226.tier2.hep.manchester.ac.uk:1094//dpm/tier2.hep.manchester.ac.uk/home/atlas/atlasdatadisk/rucio/data16_valid/da/d1/DAOD_BPHY5.11905128._000017.zip.1 DAOD_BPHY5.11905128._000017.zip.1
[0B/0B][100%][==================================================][0B/s] 
Run: [ERROR] Server responded with an error: [14] Central-directory-file-header signature not found.

Problem was identified, and needs a fix.
