### ISSUE TITLE
RFE: document various 'XrdSec*' environment variables

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#409]
Xroot authentication is influenced by several environment variables, but the majority is not documented. Could these perhaps be added to the "Authentication & Access Control Configuration Reference"  at http://xrootd.org/doc/dev44/sec_config.htm ?

The code mentions ('getenv(.XrdSec'):

XrdSecCREDS
XrdSecDEBUG
XrdSecGSICACHECK
XrdSecGSICADIR
XrdSecGSICRLCHECK -- mentioned for 3.1.0 changelog
XrdSecGSICRLDIR
XrdSecGSICRLEXT
XrdSecGSICRLRefresh
XrdSecGSIDELEGPROXY  -- documented
XrdSecGSIPROXYDEPLEN
XrdSecGSIPROXYKEYBITS
XrdSecGSIPROXYVALID
XrdSecGSISIGNPROXY
XrdSecGSISRVNAMES
XrdSecGSIUSEDEFAULTHASH
XrdSecGSIUSERCERT
XrdSecGSIUSERKEY
XrdSecGSIUSERPROXY
XrdSecHOST
XrdSecKRB5INITTKN
XrdSecNETRC
XrdSecPROTOCOL  -- mentioned in the 3.3.0 release notes 
XrdSecPWDALOGFILE
XrdSecPWDAUTOLOG
XrdSecPWDMAXPROMPT
XrdSecPWDSRVPUK
XrdSecPWDVERIFYSRV
XrdSecSECTOKEN
XrdSecsssKT -- mentioned in 3.1.0 release notes, "as documented"?
XrdSecUSER

**Comment by gganis** [comment]
Hi,
Most of these are actually already documented in the place that you mention: see, for example, http://xrootd.org/doc/dev44/sec_config.htm#_Toc454139124 or http://xrootd.org/doc/dev44/sec_config.htm#_Toc454139132 .

We will complete this and perhaps make a summary section with all the variables .

**Comment by jmuf** [comment]
Apologies, don't know how I could have overlooked them :-( - please feel free to close.
(I had started by looking for XrdSecPROTOCOL which indeed is missing, but the GSI* things and many others are present).

**Comment by abh3** [comment]
The envars were documented.
