### ISSUE TITLE
Expose arbitrary extended attributes via XRootD

### ISSUE THREAD

**Issue by LincolnBryant** [xrootd/xrootd#410]
We would like to be able to expose arbitrary extended attributes of our underlying filesystem via XRootD. 

Currently, if I try this locally:

```
$ xrd stash.osgconnect.net
(C) 2004-2010 by the Xrootd group. Xrootd version: v4.2.3
Welcome to the xrootd command line interface.
Type 'help' for a list of available commands.
root://stash.osgconnect.net:1094//> query xattr //user/lincolnb/public
root://stash.osgconnect.net:1094//>
```

I see no xattrs returned. However if I run a getfattr on the directory locally:

```
# getfattr -d -m ceph.dir.* /stash/user/lincolnb/public
getfattr: Removing leading '/' from absolute path names
# file: stash/user/lincolnb/public
ceph.dir.entries="9"
ceph.dir.files="7"
ceph.dir.rbytes="1162431911"
ceph.dir.rctime="1467926762.09188774289"
ceph.dir.rentries="15"
ceph.dir.rfiles="12"
ceph.dir.rsubdirs="3"
ceph.dir.subdirs=“2"
```

**Comment by abh3** [comment]
This has been implemented in R5 and you can set and query file extended attributes if they are supported by the file system. The xattr option here is misleading (and an unfortunate choice) to query internal attributes assigned to a path. Check out xrdfs to see how that is done,.
