### ISSUE TITLE
third party copy fails

### ISSUE THREAD

**Issue by ivmfnal** [xrootd/xrootd#419]
Hello.

When I am trying to do 3rd party copy using "xrdcp --tpc only ..." it creates a zero length file at the destination and stops with error "File exists". This behavior is invariant to whether I use --force option or not, or whether the transfers occur between XRooD cluster via the manager or between isolated servers.

For example: 

[protodune@protodunefts ~]$ xrdcp --tpc only xroot://protodunexrootd.fnal.gov:1094//tmp/tmp_file xroot://protodunexrde1.fnal.gov:1094//tmp/tmp_file2
[0B/919.6kB][  0%][>                                                 ][0B/s]  
Run: [ERROR] Server responded with an error: [3005] [ERROR] OS Error: File exists

**Comment by simonmichal** [comment]
Could you please provide more input, like the configuration of xrootd endpoints?

(after doing a simple test I was not able to reproduce it)

Thanks, 
Michal

**Comment by ivmfnal** [comment]
I am attaching source and destination config files

[destination.txt](https://github.com/xrootd/xrootd/files/493628/destination.txt)
[source.txt](https://github.com/xrootd/xrootd/files/493627/source.txt)

**Comment by xrootd-dev** [comment]
I think you need at least the --server option for the xrdcp program in the 
tpc config:
   ofs.tpc pgm /usr/bin/xrdcp --server

Cheers,
   Wilko

**Comment by ivmfnal** [comment]
Yes, that worked. Thanks !

By the way, where can I find the documentation for ofs.tpc option ?

**Comment by klabattermann** [comment]
Glad it is working.
The tpc config is documented in the
   Open File System & Open Storage System Configuration Reference
(ofs, oss) available on the xrootd documentation page.
The current version for xrootd v4 is
  http://xrootd.org/doc/dev41/ofs_config.htm

Cheers,
   Wilko
