### ISSUE TITLE
logical space info double counting if oss.cache on same partition/device

### ISSUE THREAD

**Issue by maxfischer2781** [xrootd/xrootd#425]
We have a server use a large parallel filesystem on which there are multiple directories configured for `oss.cache` to reduce inodes per directory. Querying the space available on the server reports the actual size _multiplied by the number of directories_.

```
# xrdfs f01-101-130:1094 spaceinfo / | grep Total
Total:              28627434496589824
# xrdfs f01-101-130:1094 query space /
oss.cgroup=public&oss.space=28627434496589824&oss.free=14835776160268288&oss.maxf=927236010016768&oss.used=0&oss.quota=-1

# df /export/gka6201
Filesystem         1K-blocks         Used    Available Use% Mounted on
/dev/gka6201   1747279937536 841776730112 905503207424  49% /export/gka6201
# ls -d /export/gka6201/xrootd/data*
/export/gka6201/xrootd/data-00/  /export/gka6201/xrootd/data-04/  /export/gka6201/xrootd/data-08/  /export/gka6201/xrootd/data-12/
/export/gka6201/xrootd/data-01/  /export/gka6201/xrootd/data-05/  /export/gka6201/xrootd/data-09/  /export/gka6201/xrootd/data-13/
/export/gka6201/xrootd/data-02/  /export/gka6201/xrootd/data-06/  /export/gka6201/xrootd/data-10/  /export/gka6201/xrootd/data-14/
/export/gka6201/xrootd/data-03/  /export/gka6201/xrootd/data-07/  /export/gka6201/xrootd/data-11/  /export/gka6201/xrootd/data-15/
```

The filesystem correctly exports a consistent device ID.

```
$ stat /export/gka6201/xrootd/data-* --format='%d' | sort | uniq -c
    16 19
```

Apparently, the method called by `query space` and `spaceinfo` recalculates the OSS volume, using each `oss.cache` directory without checking device overlap.

Our minimal config for this problem is this:

```
all.export / nolock r/w nocheck norcreate
oss.defaults nomig nodread nocheck norcreate nolock
oss.alloc 512M 2 0
oss.localroot /export/xrootd
oss.space public /export/gka6201/xrootd/data*
```

**Comment by abh3** [comment]
Hi Max,

This is indeed a bug and will be fixed. For other people that have 
encountered this problem, the bypass until we have fixed this is to define 
a singletom space group that points to the distributed file system and 
perform queries against that space group. This avoids the problem, albeit 
in sort of a klunky way.

Andy
