### ISSUE TITLE
Throttling appears to not work

### ISSUE THREAD

**Issue by PerilousApricot** [xrootd/xrootd#427]
Hi all,

With `4.4.0-1.osg33.el7` / `"Copr.  2004-2012 Stanford University, xrd version v4.4.0`, the following config stanza appears to have no affect:

```
xrootd.fslib throttle default
throttle.throttle concurrency 100
throttle.trace ioload
```

The full startup log is:

```
161025 14:09:07 42186 Starting on Linux 3.10.0-327.36.1.el7.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.4.0
++++++ xrootd clustered@se8.accre.vanderbilt.edu initialization started.
Config using configuration file /etc/xrootd/xrootd-clustered.cfg
=====> xrd.port 1094
=====> xrd.trace conn
=====> all.sitename T2_US_Vanderbilt
=====> xrd.report xrootd.t2.ucsd.edu:9931 every 30s all sync
Config maximum number of connections restricted to 65536
Copr.  2012 Stanford University, xrootd protocol 3.0.0 version v4.4.0
++++++ xrootd protocol initialization started.
=====> all.export /store
=====> xrootd.fslib throttle default
=====> xrootd.trace emsg login stall redirect
=====> xrootd.seclib /usr/lib64/libXrdSec.so
Config warning: ignoring fslib; libXrdOfs.so is built-in.
=====> xrootd.fslib /usr/lib64/libXrdOfs.so
=====> xrootd.monitor all auth flush 30s mbuff 1472 window 5s dest files io info user xrootd.t2.ucsd.edu:9930
Config exporting /store
Plugin loaded 
++++++ Authentication system initialization started.
Plugin loaded 
161025 14:09:07 42186 secgsi_InitOpts: *** ------------------------------------------------------------ ***
161025 14:09:07 42186 secgsi_InitOpts:  Mode: server
161025 14:09:07 42186 secgsi_InitOpts:  Debug: -1
161025 14:09:07 42186 secgsi_InitOpts:  CA dir: /etc/grid-security/certificates
161025 14:09:07 42186 secgsi_InitOpts:  CA verification level: 1
161025 14:09:07 42186 secgsi_InitOpts:  CRL dir: /etc/grid-security/certificates/
161025 14:09:07 42186 secgsi_InitOpts:  CRL extension: .r0
161025 14:09:07 42186 secgsi_InitOpts:  CRL check level: 1
161025 14:09:07 42186 secgsi_InitOpts:  CRL refresh time: 86400
161025 14:09:07 42186 secgsi_InitOpts:  Certificate: /etc/grid-security/hostcert-xrootd.pem
161025 14:09:07 42186 secgsi_InitOpts:  Key: /etc/grid-security/hostkey-xrootd.pem
161025 14:09:07 42186 secgsi_InitOpts:  Proxy delegation option: 0
161025 14:09:07 42186 secgsi_InitOpts:  GRIDmap file: /etc/grid-security/grid-mapfile
161025 14:09:07 42186 secgsi_InitOpts:  GRIDmap option: 1
161025 14:09:07 42186 secgsi_InitOpts:  GRIDmap cache entries expiration (secs): 600
161025 14:09:07 42186 secgsi_InitOpts:  Client proxy availability in XrdSecEntity.endorsement: 0
161025 14:09:07 42186 secgsi_InitOpts:  VOMS option: 1
161025 14:09:07 42186 secgsi_InitOpts:  MonInfo option: 1
161025 14:09:07 42186 secgsi_InitOpts:  Crypto modules: ssl
161025 14:09:07 42186 secgsi_InitOpts:  Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
161025 14:09:07 42186 secgsi_InitOpts:  MDigests: sha1:md5
161025 14:09:07 42186 secgsi_InitOpts: *** ------------------------------------------------------------ ***
161025 14:09:07 42186 secgsi_XrdOucGMap: cannot access grid map file '/etc/grid-security/grid-mapfile'in read mode; errno: 2 - aborting
=====> sec.protocol /usr/lib64 gsi -certdir:/etc/grid-security/certificates -cert:/etc/grid-security/hostcert-xrootd.pem -key:/etc/grid-security/hostkey-xrootd.pem -crl:1 -moninfo
Config 1 authentication directives processed in /etc/xrootd/xrootd-clustered.cfg
------ Authentication system initialization completed.
Config Routing for se8.accre.vanderbilt.edu: local pub4 prv4 
Config Route all4: se8.accre.vanderbilt.edu Dest=[::129.59.197.227]:1094
++++++ File system initialization started.
=====> all.role server
Config warning: ignoring invalid trace option 'conn'.
=====> ofs.trace conn
=====> ofs.authorize
++++++ Storage system initialization started.
=====> all.export /store
Config effective /etc/xrootd/xrootd-clustered.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32768 65536
       oss.maxsize      0
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33668452352
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path /store r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
++++++ Authorization system initialization started.
161025 14:09:07 42186 acc_Config: Authorization system using configuration in /etc/xrootd/xrootd-clustered.cfg
=====> acc.authdb /etc/xrootd/Authfile
=====> acc.audit deny grant
Config 2 authorization directives processed in /etc/xrootd/xrootd-clustered.cfg
Config 1 auth entries processed in /etc/xrootd/Authfile
------ Authorization system initialization completed.
++++++ Configuring server role. . .
=====> all.manager se1.accre.vanderbilt.edu:1214
Config warning: ignoring invalid trace option 'conn'.
=====> cms.trace conn
Config effective /etc/xrootd/xrootd-clustered.cfg ofs configuration:
       all.role server
       ofs.authorize
       ofs.maxdelay   60
       ofs.persist    manual hold 600 logdir /tmp/clustered/.ofs/posc.log
       ofs.trace      0
------ File system server initialization completed.
161025 14:09:07 42212 cms_Finder: Connected to cmsd via /tmp/clustered/.olb/olbd.admin
Config warning: 'xrootd.prepare logdir' not specified; prepare tracking disabled.
------ xrootd protocol initialization completed.
------ xrootd clustered@se8.accre.vanderbilt.edu:1094 initialization completed.
```

A check of the opened files yields:

```
# lsof -p $(pidof xrootd) | grep -i xrd
xrootd  42186 xrootd  mem       REG              253,0   165784 210055279 /usr/lib64/libXrdCryptossl-4.so
xrootd  42186 xrootd  mem       REG              253,0   115040 210055276 /usr/lib64/libXrdCrypto.so.1.0.0
xrootd  42186 xrootd  mem       REG              253,0   168888 210055281 /usr/lib64/libXrdSecgsi-4.so
xrootd  42186 xrootd  mem       REG              253,0    57576 210055280 /usr/lib64/libXrdSec-4.so
xrootd  42186 xrootd  mem       REG              253,0   576776 210055290 /usr/lib64/libXrdUtils.so.2.0.0
xrootd  42186 xrootd  mem       REG              253,0   806400 202580919 /usr/lib64/libXrdServer.so.2.0.0
```

A slight change to the configuration `xrootd.fslib throttle /usr/lib64/libXrdThrottle-4.so` and  `xrootd.fslib throttle /robots/usr/lib64/libXrdThrottle-4.so` yields a similar configuration and loaded libraries

The file `/usr/lib64/libXrdThrottle-4.so` itself exists, but it appears xrootd doesn't load it.

**Comment by abh3** [comment]
Thanks for reporting this. I’ll look into it. BTW when specifying plugin libraries you should never specify the ‘-x’ (in this case x is 4) suffix. The system will automatically choose the correct suffix. This is how the built-in versioning system works. This allows you to not worry about pairing the correct version of a plugin with some version of xrootd. That gets defeated when you specify the suffix and the versioning system then downgrades to the lowest compatible point, which isn’t always the best choice but one that usually works.

Andy

From: Andrew Melo 
Sent: Tuesday, October 25, 2016 12:12 PM
To: xrootd/xrootd 
Subject: [xrootd/xrootd] Throttling appears to not work (#427)

Hi all,

With 4.4.0-1.osg33.el7 / "Copr. 2004-2012 Stanford University, xrd version v4.4.0, the following config stanza appears to have no affect:

xrootd.fslib throttle default
throttle.throttle concurrency 100
throttle.trace ioload
The full startup log is:

161025 14:09:07 42186 Starting on Linux 3.10.0-327.36.1.el7.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.4.0
++++++ xrootd clustered@se8.accre.vanderbilt.edu initialization started.
Config using configuration file /etc/xrootd/xrootd-clustered.cfg
=====> xrd.port 1094
=====> xrd.trace conn
=====> all.sitename T2_US_Vanderbilt
=====> xrd.report xrootd.t2.ucsd.edu:9931 every 30s all sync
Config maximum number of connections restricted to 65536
Copr.  2012 Stanford University, xrootd protocol 3.0.0 version v4.4.0
++++++ xrootd protocol initialization started.
=====> all.export /store
=====> xrootd.fslib throttle default
=====> xrootd.trace emsg login stall redirect
=====> xrootd.seclib /usr/lib64/libXrdSec.so
Config warning: ignoring fslib; libXrdOfs.so is built-in.
=====> xrootd.fslib /usr/lib64/libXrdOfs.so
=====> xrootd.monitor all auth flush 30s mbuff 1472 window 5s dest files io info user xrootd.t2.ucsd.edu:9930
Config exporting /store
Plugin loaded 
++++++ Authentication system initialization started.
Plugin loaded 
161025 14:09:07 42186 secgsi_InitOpts: *** ------------------------------------------------------------ ***
161025 14:09:07 42186 secgsi_InitOpts:  Mode: server
161025 14:09:07 42186 secgsi_InitOpts:  Debug: -1
161025 14:09:07 42186 secgsi_InitOpts:  CA dir: /etc/grid-security/certificates
161025 14:09:07 42186 secgsi_InitOpts:  CA verification level: 1
161025 14:09:07 42186 secgsi_InitOpts:  CRL dir: /etc/grid-security/certificates/
161025 14:09:07 42186 secgsi_InitOpts:  CRL extension: .r0
161025 14:09:07 42186 secgsi_InitOpts:  CRL check level: 1
161025 14:09:07 42186 secgsi_InitOpts:  CRL refresh time: 86400
161025 14:09:07 42186 secgsi_InitOpts:  Certificate: /etc/grid-security/hostcert-xrootd.pem
161025 14:09:07 42186 secgsi_InitOpts:  Key: /etc/grid-security/hostkey-xrootd.pem
161025 14:09:07 42186 secgsi_InitOpts:  Proxy delegation option: 0
161025 14:09:07 42186 secgsi_InitOpts:  GRIDmap file: /etc/grid-security/grid-mapfile
161025 14:09:07 42186 secgsi_InitOpts:  GRIDmap option: 1
161025 14:09:07 42186 secgsi_InitOpts:  GRIDmap cache entries expiration (secs): 600
161025 14:09:07 42186 secgsi_InitOpts:  Client proxy availability in XrdSecEntity.endorsement: 0
161025 14:09:07 42186 secgsi_InitOpts:  VOMS option: 1
161025 14:09:07 42186 secgsi_InitOpts:  MonInfo option: 1
161025 14:09:07 42186 secgsi_InitOpts:  Crypto modules: ssl
161025 14:09:07 42186 secgsi_InitOpts:  Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
161025 14:09:07 42186 secgsi_InitOpts:  MDigests: sha1:md5
161025 14:09:07 42186 secgsi_InitOpts: *** ------------------------------------------------------------ ***
161025 14:09:07 42186 secgsi_XrdOucGMap: cannot access grid map file '/etc/grid-security/grid-mapfile'in read mode; errno: 2 - aborting
=====> sec.protocol /usr/lib64 gsi -certdir:/etc/grid-security/certificates -cert:/etc/grid-security/hostcert-xrootd.pem -key:/etc/grid-security/hostkey-xrootd.pem -crl:1 -moninfo
Config 1 authentication directives processed in /etc/xrootd/xrootd-clustered.cfg
------ Authentication system initialization completed.
Config Routing for se8.accre.vanderbilt.edu: local pub4 prv4 
Config Route all4: se8.accre.vanderbilt.edu Dest=[::129.59.197.227]:1094
++++++ File system initialization started.
=====> all.role server
Config warning: ignoring invalid trace option 'conn'.
=====> ofs.trace conn
=====> ofs.authorize
++++++ Storage system initialization started.
=====> all.export /store
Config effective /etc/xrootd/xrootd-clustered.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32768 65536
       oss.maxsize      0
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33668452352
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path /store r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
++++++ Authorization system initialization started.
161025 14:09:07 42186 acc_Config: Authorization system using configuration in /etc/xrootd/xrootd-clustered.cfg
=====> acc.authdb /etc/xrootd/Authfile
=====> acc.audit deny grant
Config 2 authorization directives processed in /etc/xrootd/xrootd-clustered.cfg
Config 1 auth entries processed in /etc/xrootd/Authfile
------ Authorization system initialization completed.
++++++ Configuring server role. . .
=====> all.manager se1.accre.vanderbilt.edu:1214
Config warning: ignoring invalid trace option 'conn'.
=====> cms.trace conn
Config effective /etc/xrootd/xrootd-clustered.cfg ofs configuration:
       all.role server
       ofs.authorize
       ofs.maxdelay   60
       ofs.persist    manual hold 600 logdir /tmp/clustered/.ofs/posc.log
       ofs.trace      0
------ File system server initialization completed.
161025 14:09:07 42212 cms_Finder: Connected to cmsd via /tmp/clustered/.olb/olbd.admin
Config warning: 'xrootd.prepare logdir' not specified; prepare tracking disabled.
------ xrootd protocol initialization completed.
------ xrootd clustered@se8.accre.vanderbilt.edu:1094 initialization completed.
A check of the opened files yields:

# lsof -p $(pidof xrootd) | grep -i xrd
xrootd  42186 xrootd  mem       REG              253,0   165784 210055279 /usr/lib64/libXrdCryptossl-4.so
xrootd  42186 xrootd  mem       REG              253,0   115040 210055276 /usr/lib64/libXrdCrypto.so.1.0.0
xrootd  42186 xrootd  mem       REG              253,0   168888 210055281 /usr/lib64/libXrdSecgsi-4.so
xrootd  42186 xrootd  mem       REG              253,0    57576 210055280 /usr/lib64/libXrdSec-4.so
xrootd  42186 xrootd  mem       REG              253,0   576776 210055290 /usr/lib64/libXrdUtils.so.2.0.0
xrootd  42186 xrootd  mem       REG              253,0   806400 202580919 /usr/lib64/libXrdServer.so.2.0.0
A slight change to the configuration xrootd.fslib throttle /usr/lib64/libXrdThrottle-4.so and xrootd.fslib throttle /robots/usr/lib64/libXrdThrottle-4.so yields a similar configuration and loaded libraries

The file /usr/lib64/libXrdThrottle-4.so itself exists, but it appears xrootd doesn't load it.

**Comment by abh3** [comment]
I am closing this because it is a configuration problem. Notice the following lines regarding your configuration file in the log:

=====> xrootd.fslib throttle default
=====> xrootd.trace emsg login stall redirect
=====> xrootd.seclib /usr/lib64/libXrdSec.so
Config warning: ignoring fslib; libXrdOfs.so is built-in.
=====> xrootd.fslib /usr/lib64/libXrdOfs.so

Essentially, the did specify the xrootd.fslib directive but later in he config file another xrootd.fslib directive was specified that overrode the throttle one. In fact, that directive was definitely not need and xrootd issued a warning that it was superfluous but it did nullify the first one (ok, granted "ignoring" is a very misleading word here). I would suggest either eliminating the superfluous directive or putting the throttle directive at the end.

Also, notice that you will likely be seeing enormously large log files because of the  "throttle.trace ioload" directive which causes a message to be issued every second which is many times essentially the same message. I will ask the developer to do something about hat but unless this is for testing I would not use that directive.
