### ISSUE TITLE
CRL cache issue

### ISSUE THREAD

**Issue by andrea-manzi** [xrootd/xrootd#435]
Hello,
we have a problem on a DPM installation when contacted via Xrootd. 
The issue looks similar to the issue https://github.com/xrootd/xrootd/issues/116, which has been fixed if i'm not wrong in v 4.2.3

The installation is running v 4.4.1 but still we are seeing this error:

161128 10:04:33 130539 secgsi_GetCA: CRL entry for '4339b4bc.0:1' needs refreshing: clean the related entry cache first

even if the corresponding CRL is still valid

[root@xdpmhn02 certificates]# openssl crl -in 4339b4bc.r0 -text | grep Next
Next Update: Dec 2 16:16:15 2016 GMT
[root@xdpmhn02 certificates]# openssl crl -in 4339b4bc.r0 -text | grep Last
Last Update: Nov 28 06:20:15 2016 GMT

could be that there is still an issue with the CRLs caching?

thanks
regards
Andrea

**Comment by andrea-manzi** [comment]
Sorry i forgot to add that we see this issue lasting for a while, then it looks like the cache is getting updated again and we don't see failures

**Comment by maarten-litmaath** [comment]
Hi,
around 08:04 CET (07:04 GMT) the service still looked OK in an upload test,
while by 10:04 CET the service failed such a test; as I write this, it has failed
such tests at 12:04, 14:04 and 16:04.

Note that the start of the failures is suspiciously close to the last update time
of the given CRL: could there be a mistake in the calculation of the time
at which the CRL needs to be reloaded from disk?

**Comment by maarten-litmaath** [comment]
Hi,
for the record, the tests also failed at 18:04 and 20:04,
while it finally worked again at 22:04.

While this problem is not fixed, what would be a workaround?
Does there exist a "reload" functionality?
Would the daemon have to be restarted?

**Comment by gganis** [comment]
I am having a look.
I let you know asap.

**Comment by andrea-manzi** [comment]
Hello
did you have time to have a look at this?
thanks!
Andrea

**Comment by gganis** [comment]
Yes, I did understand the problem (the new CRL is not actually loaded), no obvious workaround, though. I have started preparing a solution but then I was taken by a few other urgent things and could not finalize; sorry for that. I think I can give you something to try within a couple of days: in which form will you be able to try it out?
Gerri

**Comment by andrea-manzi** [comment]
HI Gerri,
thanks a lot! 
would it be possible to tag the xrootd version with the fix so that we can build it and do some testing? i can speak with @simonmichal  to help me with the build
thanks!
Andrea

**Comment by simonmichal** [comment]
Hi guys,
A separate branch with the bug fix would be the easiest way IMHO ;-)

Cheers,
Michal

**Comment by gganis** [comment]
Hi Andrea,
Can you post the xrdgsi configuration directives you have in your setup?
Would also be possible to have a larger snapshot of the log file around the messages, say 10 lines before and 100 lines after?
 
Thanks,
Gerri

**Comment by andrea-manzi** [comment]
Hi Gerri,
the xrdgsi conf is

xrootd.seclib libXrdSec.so
sec.protocol /usr/lib64 gsi -crl:3 -key:/etc/grid-security/dpmmgr/dpmkey.pem -cert:/etc/grid-security/dpmmgr/dpmcert.pem -md:sha256:sha1 -ca:2 -gmapopt:10 -vomsfun:/usr/lib64/libXrdSecgsiVOMS.so

we are using vomsxrd as well to extract voms attributes

concerning the logs i'm afraid the machine where i reproduced the issue has been shutdown and i didn't save the logs, i can ask the site in production who reported the problem if they still have them. otherwise we will have to wait that the problem appears again (it's not happening so often)
thanks
cheers
Andrea

**Comment by gganis** [comment]
Hi,
I have just uploaded a patch that should fix the problem. This should go in the release candidate for 4.6 which should come soon. Hopefully you will be able to try the rc.

Gerri

**Comment by andrea-manzi** [comment]
thanks a lot!
i will coordinate with Michal to get the RC and do some testing
cheers
Andrea


2017-01-19 10:09 GMT+01:00 gganis <notifications@github.com>:

**Comment by simonmichal** [comment]
@andrea-manzi : Has this been fixed? Can I close this issue?

Thanks,
Michal

**Comment by andrea-manzi** [comment]
Hi Michal,
we have seen this issue on one production site only  and never been able to
reproduce it,
so i would wait to deploy the fix to that site and see if the issue appear
again before closing it. what do you think?
thanks
Andrea

**Comment by simonmichal** [comment]
Thanks for the update, let's wait then.

Michal

**Comment by maarten-litmaath** [comment]
Hi all,

> we have seen this issue on one production site only

2 sites, actually.  That is how we realized it was not a site's fault.

**Comment by andrea-manzi** [comment]
a yes you are right:-) but the second site is not available anymore ..

**Comment by abh3** [comment]
Andrea,

Any status update on this?

**Comment by andrea-manzi** [comment]
Hi Andy,
i would like to give you an update but i need the site which reported this issue to install the Xrootd in production and see if this issue can be reproduced or not. Given the problems affecting 4.6 this has not happened. So i guess we should wait for 4.6.1 to have an update on this or if you prefer we can close this ticket and reopen it in case the problem is not fixed.
cheers
Andrea

**Comment by abh3** [comment]
This seems to be fixed in git head and will appear in 4.6.1.
