### ISSUE TITLE
Checksum calculation fails

### ISSUE THREAD

**Issue by ivmfnal** [xrootd/xrootd#441]
I am trying to calculate checksum using 2 methods:

xrdcp --cksum adler32:print 
xrfds ... query checksum ...

And I get essentially the same error:

[ERROR] Server responded with an error: [3013] query chksum is not supported

What am I doing wrong ?

Igor

**Comment by esindril** [comment]
Hi Ivan,
Do you have checksum support enabled on the server side?
http://xrootd.org/doc/prod/xrd_config.htm#_Toc310725356

**Comment by ivmfnal** [comment]
Yes, you are right. That was what I needed. Thanks !

**Comment by esindril** [comment]
Great!
