### ISSUE TITLE
xrdcp -f isn’t supported for uploads using libXrdCeph

### ISSUE THREAD

**Issue by alastairdewhurst** [xrootd/xrootd#442]
Hi

When attempting to upload a file to Ceph it gives and error that the operation is not supported: 

% xrdcp --verbose -f grid-squids.json root://xrootd.echo.stfc.ac.uk/atlas:scratchdisk/LoadTest/File1
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3005] Unable to open atlas:scratchdisk/LoadTest/File1; operation not supported

If I look at the log on the server I can see:
161217 13:17:52 104092 XrdProtocol: matched protocol xrootd
161217 13:17:52 104092 ?:26@lxplus089.cern.ch XrdPoll: FD 26 attached to poller 0; num=1
161217 13:17:52 104092 XrootdXeq: dewhurst.32174:26@lxplus089.cern.ch pub IPv4 login as atlasprod
161217 13:17:52 104092 acc_Audit: dewhurst.32174:26@lxplus089.cern.ch grant gsi atlasprod@lxplus089.cern.ch stat atlas:scratchdisk/LoadTest/File1
ceph_stat : atlas:scratchdisk/LoadTest/File1
161217 13:17:52 104092 acc_Audit: dewhurst.32174:26@lxplus089.cern.ch grant gsi atlasprod@lxplus089.cern.ch create atlas:scratchdisk/LoadTest/File1
ceph_open : fd 1 associated to atlas:scratchdisk/LoadTest/File1
161217 13:17:52 104092 ofs_open: dewhurst.32174:26@lxplus089.cern.ch Unable to open atlas:scratchdisk/LoadTest/File1; operation not supported
161217 13:17:52 104092 XrootdXeq: dewhurst.32174:26@lxplus089.cern.ch disc 0:00:00
161217 13:17:52 104092 dewhurst.32174:26@lxplus089.cern.ch XrdPoll: FD 26 detached from poller 0; num=0

Adny H commented that it could be because:
Normally, the output file is opened "Update+New" with force it is opened "Update+Delete". It's up to the Ceph plugin on how to interpret that combination. I suspect it doesn't know what to do with "Delete".

Alastair

**Comment by glpatcern** [comment]
Hi @alastairdewhurst, is this still an issue?

It was brought to my attention by @simonmichal as they're reviewing old outstanding issues, but as a matter of fact in our CASTOR/Ceph deployment I cannot reproduce it:

`itglp@lxc2cert1:user/i/itglp> xrdcp -f --verbose /etc/group root://lxc2cert1//castor/cern.ch/dev/i/itglp/testxrdcpf -ODsvcClass=cephpool`
`[918B/918B][100%][==================================================][918B/s]`

where the server side shows:
`170928 16:53:57 8253 itglp.14650:21@lxc2cert1 castor2ofs_open: 4200-40644 fn=castorcert@castorcert1:5001080635@cnsdev.7588290`
while we would have `open_mode=4102` without the `-f` flag.

**Comment by glpatcern** [comment]
Just to clarify, that would actually exclude Andy's hypothesis, and by code inspection I can see that the truncation operation is actually honoured.

Please let us know!

Giuseppe
