### ISSUE TITLE
checksum not supported by libXrdCephXattr

### ISSUE THREAD

**Issue by alastairdewhurst** [xrootd/xrootd#443]
Hi

I am unable to get checksums when uploading files to a Ceph backed storage cluster or from using the xrdadler32 command to get a checksum. Both of these functions are part of libXrdCephXattr.so.

-bash-4.1$ xrdcp --cksum adler32:print /tmp/deleteme2222
root://xrootd.echo.stfc.ac.uk:1094/atlas:scratchdisk/test/file2
[35.24MB/35.24MB][100%][==================================================][35.24MB/s]

Run: [ERROR] Server responded with an error: [3013] query chksum is not
supported

-bash-4.1$ xrdadler32
root://xrootd.echo.stfc.ac.uk:1094/atlas:scratchdisk/rucio/user/gangarbt/7c/9e/user.gangarbt.hc20099477.tid808.ANALY_RAL_ECHO.333._3091749186.log.tgz
Error_accessing:
root://xrootd.echo.stfc.ac.uk:1094/atlas:scratchdisk/rucio/user/gangarbt/7c/9e/user.gangarbt.hc20099477.tid808.ANALY_RAL_ECHO.333._3091749186.log.tgz

I have doubled checked that the library is being loaded correctly:
A suggestion from the XrootD developers was that the plugin wasn't being
loaded properly, but the config contains the correct lines and logs seem
to indicate it is being loaded in my config and when I start the servce:

Config:
ofs.osslib /usr/lib64/libXrdCeph.so xrootd@
ofs.xattrlib /usr/lib64/libXrdCephXattr.so

XrootD log:
++++++ File system initialization started.
=====> ofs.osslib /usr/lib64/libXrdCeph.so xrootd@ 
=====> ofs.xattrlib /usr/lib64/libXrdCephXattr.so 
=====> ofs.authorize
Plugin loaded unreleased XrdCephOss v20161202-69bd779 from osslib /usr/lib64/libXrdCeph-4.so
++++++ CERN/IT-DSS XrdCeph
Plugin loaded unreleased XrdCephXAttr v20161202-69bd779 from xattrlib /usr/lib64/libXrdCephXattr-4.so
++++++ CERN/IT-DSS XrdCephXattr

If I look at the object manually in Ceph I can see that a checksum value is being store as an external attribute, so I am not sure where the problem lies.

Alastair

**Comment by abh3** [comment]
Hi Alastair,

The Ceph library merely implements the checksum recording you still have 
to configure it. Please read:

http://xrootd.org/doc/dev44/xrd_config.htm#_Toc454222307

Andy

**Comment by alastairdewhurst** [comment]
Hi Andy

Sorry I had missed that piece of documentation.  If I try adding:
xrootd.chksum max 3 adler32 /usr/bin/xrdadler32

When I run a command I get:
$ xrdcp  --cksum adler32:print /tmp/vm21_site_bdii root://ceph-gw2.gridpp.rl.ac.uk:1094/atlas:scratchdisk/test/file35
[353.8kB/353.8kB][100%][==================================================][353.8kB/s]  
Run: [ERROR] Invalid response


If instead I try:
xrootd.chksum adler32

When I run a command I get:
-bash-4.1$ xrdcp --debug 1 --cksum adler32:print /tmp/vm21_site_bdii root://ceph-gw2.gridpp.rl.ac.uk:1094/atlas:scratchdisk/test/file36
[353.8kB/353.8kB][100%][==================================================][70.77kB/s]  
Run: [ERROR] Server responded with an error: [3005] Unable to checksum atlas:scratchdisk/test/file36; no data available


I have actually looked again at the xattr stored by Xrootd and it isn't actually writing a checksum to Ceph.  The GridFTPplugin which is based on the same libradosstriper libaries is writing a checksum, which is what confused me.

I have tried the xrdadler32 command on files with and without  a checksum stored and I am still getting the same error: "Error accessing <file>"

Not sure what I should try next?

Alastair

**Comment by wyang007** [comment]
Hi Alastair,


both the xrootd servers' built-in adler32 checksum and /usr/bin/xrdadler32 calculated the checksum and then try to save the result into an extended attribute. So a simple way to test is to run /usr/bin/xrdadler32 command on the server (ceph-gw2.gridpp.rl.ac.uk) against file /atlas:scratchdisk/test/file35. Hopefully this will give you the same error and help you debug.


regards,

--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338
________________________________

**Comment by abh3** [comment]
I beleive we fixed this in the latest Ceph plugin.
