### ISSUE TITLE
Allow systemd socket inheritance

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#446]
Xrootd is a bit of a strange HTTP server in that it cannot actually run on port 80.

The traditional blocker for this is the fact that `xrootd` runs unprivileged, which limits access to the low port ranges.

On systemd platforms, we can have the best of both worlds.  Systemd itself will reserve the socket, bind it, and allow the daemon to receive it via FD inheritance.  It even provides a simple library interface for determining which FD to use.  This way, the daemon can continue to run as unprivileged.

Background material:
- High-level overview: http://0pointer.de/blog/projects/socket-activation.html
- Reference page for socket unit files: https://www.freedesktop.org/software/systemd/man/systemd.socket.html
- Some API documentation: https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html#

**Comment by simonmichal** [comment]
Hi Brian,

We have implemented the systemd socket inheritance in xrootd:
15e1836fe4836319f975b6a8234a088e82db92ea
f31bff6c314cc84a70db93a29796441662e27dfd
c755af947572ec6f7ebf5fa7c7dd34e0232ed7ce
9c8ac9cf922718cc991f63a47af8ac6f8ff49c5d

Would like to review or test before I close this one?

Cheers,
Michal

**Comment by bbockelm** [comment]
Hi Michal,

Yes - we'll be happy to review/test.  Give us a few days!

Thanks,

Brian

**Comment by bbockelm** [comment]
What branch is that in?  Can you create a corresponding PR so I can send the link to someone?

**Comment by simonmichal** [comment]
It is already in the master.

**Comment by xrootd-dev** [comment]
Hi Brian,

I believe it's in git head.

Andy

**Comment by bbockelm** [comment]
Hi,

I only see a systemd socket defined for HTTP in the packaging/ subdir -- is there packaging for the xrootd protocol socket too?

Brian

**Comment by abh3** [comment]
Hi Brian,

We decided that there was no reason to use port inheritance for non-privileged ports. Indeed, there really is none except for individual preference.

Andy

**Comment by bbockelm** [comment]
Port inheritance:
- Allows reservation of the port at the init level.  This prevents other random processes from grabbing it.
- Allows containers / sandboxes to utilize ports on a network they may not otherwise have access to.
  - I.e., allows you to use the PrivateNetwork feature

I find it quite useful (often, more useful) for non-privileged ports.

Brian

**Comment by simonmichal** [comment]
Hi Brian,

AFAIR if you create a systemd socket for a XRootD instance bound to port 1094 (or the port configured in your config file if you are not using the default one), XRootD server will use it ;)

There is no packaging for a XRootD socket because we didn't wanted this to be the default behavior, also the socket has to be created per instance so this would be anyway just an example.

Cheers,
Michał

**Comment by bbockelm** [comment]
Ok, I think I got everything working.  Looks good!

We might need to really rethink how we approach the packaging here (as noted previously).  But, at a technical level, this seems to work well.

**Comment by simonmichal** [comment]
Good :-)

Regarding packaging, I would say:

1. We add xrootd@.socket that reserves port 1094 for respective instance. Since it's a systemd socket template it will be generally usable (not just an example). Keep the socket by default disabled.

2. We can keep the xrdhttp.socket as it is, or make it a socket template too? I don't have a strong opinion on this one. Let me know what you would find better!

**Comment by xrootd-dev** [comment]
I think we should keep it disabled as well. I dislike leaving open but unused sockets hanging about. It’s likely considered poor security as well.

**Comment by bbockelm** [comment]
Seems that it would make sense to have some symmetry here - either both templated or both single-instance.  [Obviously, for hosts with multiple instances, one would have to provide an override for the port number.]

**Comment by simonmichal** [comment]
Yes, for hosts with multiple instances, an overwrite for the port is necessary, but I don't think there is anything we can do about it.

I just added the socket templates for both XRootD and XrdHttp. Is there anything else, or can I close the ticket?
