### ISSUE TITLE
xrootd install some libraries without proper SONAME

### ISSUE THREAD

**Issue by bircoph** [xrootd/xrootd#447]
xrootd-4 (all versions I tested including 4.5.0) installs some (but not all) libraries without proper *.so* names/symlinks _and_ with invalid SONAME value in shared object file.

This list matches pattern "libXrd.*-4\.so"; for xrootd-4.5.0 and my cmake flags:
`-DCMAKE_INSTALL_PREFIX=/usr -DENABLE_FUSE=no -DENABLE_HTTP=no -DENABLE_KRB5=yes -DENABLE_READLINE=yes -DENABLE_CRYPTO=yes -DENABLE_TESTS=no -DENABLE_CEPH=OFF -DENABLE_PYTHON=OFF`
the list of problematic libraries is as follows:

```
/usr/lib64/libXrdSecsss-4.so
/usr/lib64/libXrdSecProt-4.so
/usr/lib64/libXrdBwm-4.so
/usr/lib64/libXrdPss-4.so
/usr/lib64/libXrdSecgsi-4.so
/usr/lib64/libXrdBlacklistDecision-4.so
/usr/lib64/libXrdSecgsiAUTHZVO-4.so
/usr/lib64/libXrdThrottle-4.so
/usr/lib64/libXrdCksCalczcrc32-4.so
/usr/lib64/libXrdOssSIgpfsT-4.so
/usr/lib64/libXrdSeckrb5-4.so
/usr/lib64/libXrdSecunix-4.so
/usr/lib64/libXrdSec-4.so
/usr/lib64/libXrdFileCache-4.so
/usr/lib64/libXrdXrootd-4.so
/usr/lib64/libXrdSecgsiGMAPDN-4.so
/usr/lib64/libXrdCryptossl-4.so
/usr/lib64/libXrdSecgsiGMAPLDAP-4.so
/usr/lib64/libXrdSecpwd-4.so
```

Is there any reason for these libraries not to follow standard naming scheme:
'$foo.so -> $foo.so.$maj.$mid.$min
$foo.so.$maj -> $foo.so.$maj.$mid.$min'
_and_ have invalid SONAME fields (which should be at least $foo.so.$maj).

Xrootd own documentation point to the correct library naming rules:
[http://xrootd.org/development.html](http://xrootd.org/development.html), see Library versions section.

So please explain me if this is a bug or intended behaviour. If this is a bug, it should be fixed, if this behaviour is intended, please explain why.

ATM Gentoo's QA checks are yelling at these files ;-(

**Comment by ellert** [comment]
This is intended. These are plugins loaded at runtime. Nothing should link to these libraries directly.

**Comment by bircoph** [comment]
Thanks.
