### ISSUE TITLE
xrootd will not build on Fedora 25

### ISSUE THREAD

**Issue by TomDaub** [xrootd/xrootd#454]
Having a build error coming from xrootd while trying to build root 6 as part of an ILCSoft installation.

Trying to compile on a Fedora 25 virtual machine (made with VirtualBox). GCC version 6.3.1.

Log files are attached. Sorry if I have not included any vital info...

[release-standalone-2017-1-26_11-54.log.txt](https://github.com/xrootd/xrootd/files/732847/release-standalone-2017-1-26_11-54.log.txt)
[XROOTD-build-err.log.txt](https://github.com/xrootd/xrootd/files/732848/XROOTD-build-err.log.txt)

**Comment by bbockelm** [comment]
Thanks for the report!

Unfortunately, these are all fixed warnings.  I think the two options are:
* Upgrade your version of Xrootd to a more recent one (`4.6.0-rc1` has just been tagged).
* Change the flags in the ROOT build so warnings are not upgraded to build failures.

**Comment by TomDaub** [comment]
Thank you very much for you help and fast response. I will give your suggestions a try!

**Comment by simonmichal** [comment]
@TomDaub can I close this one? (4.6.0 does compile on all fedora platforms)

Thanks,
Michal

**Comment by TomDaub** [comment]
Yes, thank you.

Cheers
