### ISSUE TITLE
xrootd 4.6.0 backward incompatibilities

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#470]
I have received additional comments on the 4.6.0 update in EPEL testing:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-9b2cd39ee3

First comment:

> It appears this PR breaks ABI / API compatibility in the XrdSecXtractor interface: https://github.com/xrootd/xrootd/pull/444
> 
> My plugin https://github.com/bbockelm/xrootd-lcmaps fails to compile after the update.
> karma: -1

Second comment:

> The configuration of for the pfc.* attributes changed, meaning existing configurations that use the caching proxy fail to start after upgrade.
> 
> The old-style attributes should still be permitted (especially as there appears to be a simple translation between old and new).

PR #444 that is referenced does mention that there is breakage, so maybe this was intentional?

**Comment by xrootd-dev** [comment]
Hi,

 I never knew that the SecXtractor was considered
a public interface, for sure that was not
intended. Was it ?

 The recent changes wanted to comply with the guidelines
for xrootd plugins loading, in order to make it possible to
become a public interface with version checking, etc.

 Andy ? What do you prefer that we do here ?

f

**Comment by abh3** [comment]
Well, the issue now is that XrdHttp/XrdHttpSecXtractor.hh is in the public 
header section. It should have been in the private header section since 
it's part of the compiled package and no user would actually use it. 
According to EPEL rules we can't move it until a major release change. Of 
course, given the circumstances we could get dispensation but that is up 
to Mattias.

Andy

**Comment by xrootd-dev** [comment]
> On Feb 20, 2017, at 7:24 PM, Andrew Hanushevsky <notifications@github.com> wrote:
> 
> Well, the issue now is that XrdHttp/XrdHttpSecXtractor.hh is in the public 
> header section. It should have been in the private header section since 
> it's part of the compiled package and no user would actually use it. 

Hi,

The only two plugins that utilize this interface (xrootd-lcmaps, xrdhttpvoms) are both external projects and not part of the compiled package -- meaning the header is correctly marked as public.

In fact, I'm a bit confused by the comment as there are no concrete implementations of the interface in the xrootd codebase.

(Plus, it's an extremely useful interface as it allows a single authorization plugin for both the xrootd and HTTP protocols...)

> According to EPEL rules we can't move it until a major release change. Of 
> course, given the circumstances we could get dispensation but that is up 
> to Mattias.
> 

Why not:

- Rename InitCtx back to the original Init
- Make InitSSL / FreeSSL not pure-virtual (put in the trivial inline implementation in the base class).

That fixes the API issue.  Then beg forgiveness on the ABI break, given it's a new interface and the two consumers of the interface both can work with this (simple coordinated RPM "Conflicts:" statement).

Brian

**Comment by xrootd-dev** [comment]
You are correct Brian. I missed that use case. Your suggestions are quite 
reasonable.

Andy

**Comment by osschar** [comment]
About pfc configuration ... there is a new mandatory configuration directive pfc.ram so accepting old pfc configuration syntax will not help.

I assume we are talking about pfc.prefetch that now requires an argument? Pfc can now prefetch data blocks in a more efficient manner so, if prefetching is used, it makes a lot of sense to set it to some value other than 1 (which would be the default).

Matevž

**Comment by abh3** [comment]
Hi Matevz,

Uhhhh, no not on this thread – it has nothing to do with pfc. But now that yiou bring it up, you should still try to be backward compatible in the config file. It may mean ignoring a directive but certainly changes should not cause the server to abort.

**Comment by osschar** [comment]
Andy, this is mentioned as the second item :)

If you want me to fix this I need an os independent way to find total system memory ... the idea would be to use 50% of it as pfc.ram default. Just making up a number really won't cut it or, better, could cut it both ways, not completely unlike as: "And out of his mouth goes a sharp two-edged sword ..."

**Comment by abh3** [comment]
The almost OS independent way of fixing this is to use sysconf() to get _SC_PHYS_PAGES and _SC_PAGESIZE and multiply them after casting to long long. I say almost because those two values are usually available in practically all modern OS's. If we get to one that doesn't support it, then we can ifdef special code for that one (yes, ugly but the only way I see how to do it).

**Comment by xrootd-dev** [comment]
Hi,

 I am on it. My very personal opinion is that the original mistake
was to keep it outside, hence my preference would still be to cleanly incorporate
the voms extractor into the main codebase (with a well made Cmakelists of course).

 I am anyway investigating Brian's workarounds. Not very confident on the final outcome though.

f

**Comment by xrootd-dev** [comment]
Hi,

 I just submitted a pull request containing the minifixes to XrdHttp proposed by Brian.

 Brian, please review and let me know if it's fine for you.

Cheers
Fabrizio

**Comment by bbockelm** [comment]
@osschar @abh3  - I think we're over-thinking things.  We simply need the server to still function after upgrade: we don't need to have it appropriately optimized to take advantage of new features!

There's no way to reliably determine "optimal" memory usage, especially not in Linux.  Even looking at the number of the memory pages in the system can be wildly incorrect (systemd starts you up in a cgroup, after all!).

Suggestion:
* Pick a random default value.  Say, 1GB RAM.
* Have a BIG LOUD WARNING message in the log if V1-style attributes are utilized and use the default value for RAM.
* If V2-style attributes are used, refuse to startup unless the admin specifies the RAM option.

This way, admins are forced to make a decision for new installs - but old installs continue to work (albeit sub-optimally).  The analogy here is `ext3`: even though the filesystem dates back to ~RHEL3, if you didn't reformat the partition when upgrading RHEL4 -> RHEL5, it would have quite sub-optimal performance as the old data formats were still present.

**Comment by simonmichal** [comment]
@bbockelm : Could you please comment on Fabrizio's PR (#471)

@ellert  : If we have a green light from Brian, can we consider the XrdSecXtractor issue as solved, or is the ABI incompatibility still a problem?

@osschar & @abh3 : I do agree with Brian: we simply need the existing instances of caching proxy to be able to start after an upgrade.

Michal

**Comment by ellert** [comment]
Hi!

I updated the package in EPEL testing (4.6.0-5), changes w.r.t. the previous version:
* updated the patches to use the changes applied in git instead of the proposed changes from the pull requests where different
* backported additional changes to CRL handling from git
* applied a modified version to the patch from #471 (see my comment of that pull request)
* applied the proposed patch from #472

**Comment by abh3** [comment]
We have merged in fixes for both compatibility problems mention here. I assume that the issues have been resolved to everyone's satisfaction. So, if I don't see any more posts to this issue I am going to close it. Please speak up if you still see any backward compatibility issues.

**Comment by bbockelm** [comment]
I can verify that with the new approach, the API issues are fixed for `XrdSecXtractor`.  That has a green light from me.

**Comment by bbockelm** [comment]
The test with the cache failed; one of the old parameters was safely ignored, but the other one triggered an assert.  See #473 for a reasonable fix.

**Comment by bbockelm** [comment]
Note - I can't verify further fixes because (I think) the issue in #476 causes the service to die instantly.  Once that gets resolved, I'll validate these other issues.

**Comment by bbockelm** [comment]
Ok, the issue in #476 seems to be resolved for me.  Everything appears good!

**Comment by ellert** [comment]
Something went wrong with the recent changes. The problem that an absent CRL cause an error when CRLCheck is 1 has returned. This was fixed in commit 2b64a32, but some change made after that reintroduced the problem.

**Comment by ellert** [comment]
I.e. #465 is back.

**Comment by gganis** [comment]
Ok, I see it, I forgot one case in the improved logic.
Sorry, I'll fix tomorrow morning.

**Comment by ellert** [comment]
With the latest fix, the absent CRL case works again. However, a warning message i printed out that shouldn't be there:
170306 21:21:08 2183 secgsi_GetCA: CRL entry for '70d35895.0:1' needs refreshing: clean the related entry cache first (0x7fd3b002d700)

**Comment by simonmichal** [comment]
Can we close this one? (I suppose yes, since 4.6.0 made it finally to stable ;)

Michal

**Comment by ellert** [comment]
Yes, closing...
