### ISSUE TITLE
More problems with 4.6.0

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#476]
Hi!

I have received one more problem report with xrootd 4.6.0:
https://bodhi.fedoraproject.org/updates/FEDORA-2017-0eca8dbb12

The report says the followong:
* xrootd-4.6.0-5.fc25 don't work http://pastebin.com/raw/GKPxXJXr
* xrootd-4.6.0-4.fc25 was fine http://pastebin.com/raw/GHXnwMEs

The problem is caused by the commit 00b2cd8 where in the call to LoadCRL(), chain->Begin() is changed to chain->EffCA(). But here chain->EffCA() is 0, so the LoadCRL fails. Nothing has triggered a call to SetEffectiveCA() on the chain object since it was built in the call to ParseFile().

I am not sure how to fix this. SetEffectiveCA() is protected so adding a call to chain->SetEffectiveCA() is not possible without making it public. And where should such a call be added? Just before the call to LoadCRL or in the ParseFile function or ...?

**Comment by bbockelm** [comment]
I'm not sure if it's related, but `master` fails with something that looks awfully similar:
```
170302 22:32:30 16250 secgsi_LoadCRL: Invalid inputs
170302 22:32:30 16250 secgsi_LoadCRL: Invalid inputs
170302 22:32:30 16250 secgsi_GetSrvCertEnt: failed to load certificate for the issuing CA '70d35895.0|d690e530.0'
170302 22:32:30 16250 secgsi_Init: problems loading srv cert
170302 22:32:30 16250 secgsi_Init: Secgsi: ErrError: no valid server certificate found
Secgsi: ErrError: no valid server certificate found
```

Worked prior to the upgrade -- seems `LoadCRL` is the originator of the error.

**Comment by abh3** [comment]
Yes, this problem was discovered by Mattias. The issue is known; the 
solution is not obvious. Gerri is working on it.

**Comment by bbockelm** [comment]
Fix LGTM.

**Comment by simonmichal** [comment]
I suppose we can we close this issue?

Michal

**Comment by ellert** [comment]
Yes, closing...
