### ISSUE TITLE
XrdPosix.hh not installed

### ISSUE THREAD

**Issue by suhlatwork** [xrootd/xrootd#479]
Hi,

the file `XrdPosix.hh` is not copied to `include/XrdPosix` when XRootD is installed. Digging through the git history, it seems that this is the case since commit 67ab0ed53f80572680802f6de993adb2cc4499c6. Given that this commit is already several years old with no one complaining about this so far, I wonder whether this was done on purpose or is a simple oversight.
This missing header means one cannot simply use the POSIX file functions like `open`, ..., but has to write `XrdPosix_Open`, ... in code making use of XrdPosix.

Thanks for the clarification!

**Comment by xrootd-dev** [comment]
Hmm, that is strange. I will have to research the history of that commit 
to see why the header file was removed from the public headers.

Andy

**Comment by ljanyst** [comment]
Why would you need this header? You can use the interface via preload or direct linking...

**Comment by xrootd-dev** [comment]
Because some people did not want to do either and the header file gves you 
that capability. It used to be public aand we couldn't find a reason why 
it was removed from public and couldn't think of a reason why it shouldn't 
be public.
