### ISSUE TITLE
Request/response mismatch, when the retry logics tries to recover from an error.

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#482]
When the client gets redirected to a data server and afterwards tries to recover form an error at the manager, it reuses the SID from the 'client - data server' channel in the 'client - load balancer' channel.
A SID should be unique per channel and hence this behaviour may result in request/response mismatch.

**Comment by simonmichal** [comment]
Fixed in 36c4edb93c0278c116d91f2b35ec2e913407ace3

**Comment by simonmichal** [comment]
Possible scenario:

1. Client sends a request, the request was assigned with a SID.

2. The request times-out, the SID goes to the set with timed-out SID.

3. Due to bug #482, another request uses exactly the same SID to send 
   a complitly unrelated request. So now our SID is in the timed-out 
   set but also there exists a XRootDMsgHandler assigned to it !!!

4. The response to the original request comes in. The AsyncSocketHandler
   creates a new message object, and afterwards it calls 
   Stream::InstallIncHandler (XrdClAsyncSocketHandler.cc : 613). As a 
   result:
   - the XRootDMsgHandler object takes ownership of the message 
     object (XRootDMsgHandler::pResponse points to our message).
   - pSubStream[stream]->inMsgHelper holds a pointer to the XRootDMsgHandler
     object

5. Subsequently, the AsyncSocketHandler calls Stream::OnIncoming, which
   calls XRootDTransport::MessageReceived(), and in here the message 
   object is deleted. Stream::OnIncomming returns without resetting the 
   pSubStream[stream]->inMsgHelper !!!

6. Next time the AsyncSocketHandler::OnRead() will be called, and will
   ask for a handler (Stream::InstallIncHandler), it will get the 
   XRootDMsgHandler that took ownership of the deleted message, because
   the pSubStream[stream]->inMsgHelper was not reset. The response 
   together with the XRootDMsgHandler will be submitted to the thread-pool.

7. When the task in question gets executed the XRootDMsgHandler::Process
   will be called, and the pResponse (which points to the messages that
   has been created in 4.) will be destroyed. Hence, we get a double delete.

@bbockelm : 
#482, which is the root of all evil in this scenario, has been fixed in 4.6.1,
so could you check if you can reproduce the problem with RC1 and let me 
know?

Thanks,
Michal

**Comment by abh3** [comment]
Hmmm, I thought sids put in the timeout set couldn't be reallocated 
because ones doesn't know whn the response will come back. Of course, they 
are lost if no responds comes back. However, they are reclaimed when the 
connection closes (the server cancels all requests when that happons). So, 
the big question here is how did the sid get reallocated?

Andy
