### ISSUE TITLE
Add continuous integration builds

### ISSUE THREAD

**Issue by alexpearce** [xrootd/xrootd#502]
It's always nice for developers to have some immediate and obvious feedback when
making pull requests. I think a really nice way of giving them this is to have some form of continuous integration that runs for every new PR, like [using Travis CI](https://travis-ci.org/getting_started).

For xrootd, this could mean building the project (i.e. running `cmake ...` and then `make/make install`) and then running the tests (those under `tests` and those that are bindings specific). The CI configuration can be written like a matrix for different platforms and parameters, so one could easily set up CI for all combinations of linux and macOS, and Python 2.7 and 3.5, for example.

If the xrootd developers are willing to [flick the switch](https://travis-ci.org/getting_started) to enable Travis, I'm happy to work on the configuration file in a PR.

**Comment by simonmichal** [comment]
Hi Alex,

Thanks for the offer! :-)

Actually, we do have a CI:
https://st-ci.cern.ch/

We use a Jenkins instance at CERN. Currently, there is also some ongoing work to mirror our github repo in cern gitlab and use gitlab runner for continuous integration.

That said, I would be more than happy to use Travis CI and have everything in one place!

But before we go ahead could you clarify few things:

1) Can we provide our own build nodes? Or does Travis provide their own build nodes? If we can only relay on Travis build nodes, how many do we get?
 
2) Are you willing to maintain the Travis CI for XRootD?

3) For what platforms can we build? Currently we are interested in epel6, epel7, latest 3 fedora releases, fedora-rawhide, and OSX, can we cover that with Travis?

4) At least the release builds should be done with mock, as they go to epel/fedora, can we do that with Travis CI?

5) Can we run unit/functional tests in docker containers?

Cheers,
Michal

**Comment by alexpearce** [comment]
> Actually, we do have a CI:
> https://st-ci.cern.ch/

Aha! I did not know about this. That's already quite useful. It looks like it doesn't test GitHub PRs, but still 👍 

For your questions:

> Can we provide our own build nodes? Or does Travis provide their own build nodes? If we can only relay on Travis build nodes, how many do we get?

Travis provide the nodes. You're allowed to run whatever you like, but within a time limit of around an hour, I think.

> Are you willing to maintain the Travis CI for XRootD?

Yes.

> For what platforms can we build? Currently we are interested in epel6, epel7, latest 3 fedora releases, fedora-rawhide, and OSX, can we cover that with Travis?

The available environments are defined here:

https://docs.travis-ci.com/user/ci-environment/

You only get 'one Linux', Ubuntu, and macOS. So, Travis won't replace your more comprehensive Jenkins tests (not to write it off entirely, but testing on multiple platforms _is_ a good idea).

> At least the release builds should be done with mock, as they go to epel/fedora, can we do that with Travis CI?

The only "mock" I'm familiar with is the Python testing module, and then I don't understand what you mean 😄 So I guess there must be another mock?

> Can we run unit/functional tests in docker containers?

Yep! You can run whatever commands you like, defined in a [Travis configuration file](https://docs.travis-ci.com/user/customizing-the-build/).

**Comment by bbockelm** [comment]
Wonderful idea!  While Jenkins exists, the setup is poorly integrated with GitHub.

@alexpearce - in other projects, I've found that you can always run Docker inside Ubuntu and hence use Travis to build on basically any supported Linux platform.

@simonmichal - it might be worthwhile (in a separate ticket) to investigate enabling the relevant plugins to integrate Jenkins with GH.  Travis would still be better as it will allow you to test PRs.

**Comment by alexpearce** [comment]
Ah yes, you can run your own Docker images on Travis. This allows testing on a much wider range of platforms 🎉

**Comment by ljanyst** [comment]
@bbockelm GitHub's pull requests are just branches, so it should be fairly easy to build/test them with any CI system. You just add extra fetch reference to your remote's config:

```
fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```

And you can fetch them:

```
]==> git fetch
remote: Counting objects: 1478, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 1478 (delta 219), reused 205 (delta 205), pack-reused 1234
Receiving objects: 100% (1478/1478), 25.87 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (907/907), completed with 145 local objects.
From github.com:xrootd/xrootd
 * [new ref]           refs/pull/10/head  -> origin/pr/10
 * [new ref]           refs/pull/100/head -> origin/pr/100
 * [new ref]           refs/pull/101/head -> origin/pr/101
 * [new ref]           refs/pull/102/head -> origin/pr/102
 * [new ref]           refs/pull/106/head -> origin/pr/106
 * [new ref]           refs/pull/108/head -> origin/pr/108
 * [new ref]           refs/pull/111/head -> origin/pr/111
 * [new ref]           refs/pull/112/head -> origin/pr/112
 * [new ref]           refs/pull/119/head -> origin/pr/119
 * [new ref]           refs/pull/122/head -> origin/pr/122
 * [new ref]           refs/pull/123/head -> origin/pr/123
...
```

**Comment by bbockelm** [comment]
Correct - but the question is whether you _trust_ the remote user to run their unverified code on your CI system.  Travis-CI takes the risk for us!

Didn't know how to get the extra refs for PRs though!  Will file that one away for later use.

**Comment by ljanyst** [comment]
You'd likely have to pay a closer attention to CVEs, but isn't it the reason why we have containers and cgroups?

**Comment by simonmichal** [comment]
@bbockelm & @ljanyst  : Yep, we have containers and chroot so we should be rather safe ;-)

@alexpearce : Let's give Travis CI a chance :-) I enabled it for xrootd/xrootd, now the ball is in your court ;-) Let's see how good is it :-)

Thanks,
Michal
