### ISSUE TITLE
XrootdFS allow_other default is impossible to unset

### ISSUE THREAD

**Issue by fizmat** [xrootd/xrootd#508]
As far as I understand, there is no option that can be passed to fuse to unset the allow_other option. This creates an error 

> fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

that a user with no write access to /etc/fuse.conf can't correct. Maybe allow_other should not be on by default? Or is there a way to unset this option?

**Comment by wyang007** [comment]
Addressed by commit 27d6b65.
