### ISSUE TITLE
Support building a Python wheel for the python bindings

### ISSUE THREAD

**Issue by ThiefMaster** [xrootd/xrootd#511]
This would make installing them e.g. in a virtualenv much easier.

I managed to build a wheel locally (after installing xrootd through my OS's package manager) by just changing this:

```diff
diff --git a/bindings/python/setup_pypi.py b/bindings/python/setup_pypi.py
index 2830e2d7..831a3bde 100644
--- a/bindings/python/setup_pypi.py
+++ b/bindings/python/setup_pypi.py
@@ -1,4 +1,5 @@
-from distutils.core import setup, Extension
+from setuptools import setup
+from distutils.core import Extension
 from distutils import sysconfig
 from os import getenv, walk, path, path, getcwd, chdir
 from platform import system
```

and then running `python setup_pypi.py bdist_wheel` (after writing e.g. 0.0.0 to VERSION_INFO).

It would be nice if this change (using `setup()` from `setuptools` instead of `distutils`) was part of the default setup.py.

Having the package on PyPI (both as source and as prebuilt binary wheels) would be even better.

**Comment by simonmichal** [comment]
Thanks for bringing this up, and sorry for the delay. The change proposed by you has been integrated into master:
6a836647fbe75b40dfab677f1b9b14d991d2b10d

For now we don't have time/men power to push it to PyPI, however if a volunteer shows up, he will be more than welcome to do it.
