### ISSUE TITLE
gcc 7.1 hiccups on XrdXrootJob and XrdCnsSsi

### ISSUE THREAD

**Issue by vp1981** [xrootd/xrootd#522]
Hello,
I'm using Archlinux x86_64 with gcc 7.1.1. I tried to compiled vanilla xrootd 4.6.1 but failed due to two places in the code. I prepared patch for both.

```
diff --git a/src/XrdCns/XrdCnsSsi.cc b/src/XrdCns/XrdCnsSsi.cc
index f3f358f1..f98518c8 100644
--- a/src/XrdCns/XrdCnsSsi.cc
+++ b/src/XrdCns/XrdCnsSsi.cc
@@ -60,7 +60,8 @@ struct XrdCnsSsiFRec
 {
 char Info[XrdCnsLogRec::FixDLen];
 
-void Updt(const char *nInfo) {strncpy(Info, nInfo, sizeof(Info));}
+void Updt(const char *nInfo) {
+  if(nInfo != nullptr) strncpy(Info, nInfo, sizeof(Info));}
 
      XrdCnsSsiFRec(const char *Data) {if (!Data) Data = XrdCnsLogRec::iArg;
                                       strncpy(Info, Data, sizeof(Info));
diff --git a/src/XrdXrootd/XrdXrootdJob.cc b/src/XrdXrootd/XrdXrootdJob.cc
index 9f7994ba..3c4e4a59 100644
--- a/src/XrdXrootd/XrdXrootdJob.cc
+++ b/src/XrdXrootd/XrdXrootdJob.cc
@@ -324,7 +324,7 @@ int XrdXrootdJob2Do::verClient(int dodel)
    for (i = 0; i < numClients; i++)
        if (!Client[i].Link->isInstance(Client[i].Inst))
           {k = i;
-           for (j = i+1; j < numClients; j++,k++) Client[k] = Client[j];
+           for (j = i+1; j < numClients && j < maxClients; j++,k++) Client[k] = Client[j];
            numClients--; i--;
           }
 
```

Both changes are more cosmetic than functional but they are allowed me to compile xrootd on my host.

---
WBR, Vladimir Lomov

**Comment by simonmichal** [comment]
Hi Vladimir,

Thanks for reporting this issue. Mind that currently by default we are not compiling with --std=c++11!

Could you prepare a pull request?

Cheers,
Michal

**Comment by vp1981** [comment]
Ok, I'll try.

**Comment by bbockelm** [comment]
@simonmichal - would it be possible to have a way to configure `cmake` to drop `-Wall`?  That would make it easier to avoid breaking the ROOT build (which is often done with very new compiler versions).

**Comment by ljanyst** [comment]
Michal, consider adding debian unstable (or even experimental) to Jenkins. I was using unstable as my devbox and we were typically ahead of these things.

**Comment by vp1981** [comment]
@bbockelm why to drop ```-Wall```? Let me explain how I faced with these two issues from GCC and found that GCC may be right here.

As for ```array-bounds``` (```XrdXrootdJob```) at first I thought that GCC is wrong here, because code looks innocent, I even prepared small example that gives zero messages from GCC though I compiled it with ```-Wall -Wextra -pedantic``` (I think it is enough to trigger maximum number of checks). Looking more closely to the code I found that method ```addClient``` assumes that it is possible (how?) to have more than ```maxClients``` clients. I think GCC here warns because it "thinks" that here possible situation when array index goes beyond the limit. I didn't dig dipper into the code and didn't try to make correct example which will give always false-positive message from GCC.

The second place where GCC stops with ```nonnull``` (```XrdCnsSsi```) looks more suspicious. I would assume that someone can pass null pointer (just zero) to the ```Updt``` method.

IMHO, if compilation stops due to ```-Wall``` then it is worth to check the code and to improve it.

**Comment by vp1981** [comment]
I wonder why you don't use c++11 (or c++14). Is it related with your Linux distribution that comes with "old" compiler?

**Comment by simonmichal** [comment]
I agree, we should stick to -Wall, those warnings are there for a reason ;-)

@ljanyst : that's a good idea, once we migrate from jenkins to gitlab, I will add it

@vp1981 : yes we still support slc5, however the upcoming release 4.7.0 will be the last one, afterwards we drop support for slc5 and we can think about --std=c++0x or --std=c++11 (we still have to support slc6)

**Comment by vp1981** [comment]
Got it, thank you.

**Comment by abh3** [comment]
We were notified about this problem a couple years ago from an early gcc 
adopter and did an analysis. Indeed, the gcc compiler can't make the 
connection that the number of clients can't exceed maximum number of 
clients because both are co-dependent variables. They needed to make 
the analysis a bit smarter. Well, that didn't happen.So, the easiest 
solution is to add the unnecessary check to squelch the message.

Andy

**Comment by abh3** [comment]
This was a compiler limitations. Using gcc 7.2 we do not see any hiccups.
