### ISSUE TITLE
XrdCl is not correctly parsing client response?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#528]
CMS is struggling to get RelVals for a data taking out the door because of a exception due to the Xrootd client.  See:

https://ggus.eu/index.php?mode=ticket_info&ticket_id=128888

(particularly, the attached log has a full stdout).

It seems that the client will randomly be unable to handle a ReadV response.  It looks like it subsequently gets confused by the state of the session, causing the server to abruptly close the socket.

CMSSW then retries against the EOS headnode and gets a socket timeout.

I'd like to focus on the ReadV response issue; it's not clear if the issue with the socket timeout is related to this.

**Comment by simonmichal** [comment]
@bbockelm : we were not able to reproduce this, is it still an issue?

Michal

**Comment by bbockelm** [comment]
I think it can be closed for now - it's probably still an issue somewhere, but we haven't had it recur since the EOS headnode became more stable.
