### ISSUE TITLE
GetRequest should be const

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#538]
XrdSsiRequest::GetRequest returns char* but I think it should be const char*

**Comment by abh3** [comment]
Actually, we do return char * for icky reasons. In some scenarios you need 
to modify the request data in order to efficiently and quickly parse it. 
Returning char * gives you that ability without requiring that you first 
copy te data.

Andy

**Comment by slithy** [comment]
Wouldn't it be better to make the default const char* and allow the user to use a const_cast<char*> to override it in those specific use cases?

**Comment by simonmichal** [comment]
IMHO if there are use cases when the request has to be non-const it should be non-const, making it const will make things only more misleading ;-)

It's good practise to limit const_cast<> only to places where one has to use legacy non-const-correct functions and to remove volatile modifiers.

Michal

**Comment by slithy** [comment]
The reason I suggested the change is that in my code, my request pointer is const char*, so I am forced to use const_cast<> in my implementation of GetRequest. (In principle the request is not something the client needs to change, notwithstanding the "icky reasons" Andy mentions).

But I see your point. I can live with it, I'll close the ticket.

**Comment by abh3** [comment]
Technically, yes; though (also technically) there is no gaurantee that 
casting away constness will actually work the way you think it will. 
Returning a char* gaurantees that the underlying storage is changeable.

Andy
