### ISSUE TITLE
XrdCl: make it known to the server that an open request is a retry

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#552]
In case of xrootd servers that allow multiple concurrent writers to a file (like EOS), it's crucial to be able to tell that two open requests are actually the same request, one of them being a retry (in order to prevent data loss).

**Comment by abh3** [comment]
I see this is closed now, but I don't see any resolution. What did I mess here?

**Comment by simonmichal** [comment]
It turned out this was an internal EOS problem that can be fixed on EOS level without need for any enhancements in the xrootd client.
