### ISSUE TITLE
incomplete/misleading error message from xrdcopy when file not found

### ISSUE THREAD

**Issue by moscicki** [xrootd/xrootd#565]
Pre-discussed with Michal already. xrtood client: 4.6.1-1

My command fails like that (I am trying to copy a file which does not exist on the local eos instance (source)):

`env XrdSecPROTOCOL=sss xrdcp --tpc only --nopbar --verbose --force root://localhost.localdomain//eos/\?eos.lfn=fid:5639827871\&eos.ruid=2\&eos.rgid=2 root://eosbackup.cern.ch//eos/dest.file`

Run: [FATAL] Redirect limit has been reached

With XRD_LOGLEVEL=Error it says a bit more:

`
2017-08-18 11:50:04.204501 +0200][Error  ][Utility           ] Cannot open source file root://localhost.localdomain:1094//eos/?eos.lfn=fid:5639827871&eos.rgid=2&eos.ruid=2: [FATAL] Redirect limit has been reached
Run: [FATAL] Redirect limit has been reached
`

With XRD_LOGLEVEL=Dump I finally find the error string which I expected in the first place:

`[2017-08-18 11:49:27.218079 +0200][Dump   ][XRootD            ] [eosuser-srv-b2.cern.ch:1094] Got a kXR_error response to request kXR_open (file: /eos/?eos.lfn=fid:5639827871&eos.rgid=2&eos.ruid=2&tpc.stage=placement, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ) [3011] Unable to open - you specified a not existing inode number fid:5639827871; No such file or directory`

**Comment by simonmichal** [comment]
This has been partially addressed in f8df11c6581b6c535cf2f899a64d55aa0961b6f2,
and will be fully addressed once #389 is implemented.
