### ISSUE TITLE
secxtractor attributes not used for authentication

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#566]
I am using xrootd 4.6.1 with xrdhttpvoms 0.2.4 from EPEL on a CentOS 7 system. 

While normal VOMS authentication via xRootD protocol works fine, it does not work for HTTPS / WebDAV. 

Here some details from a verbose log:
```
170818 15:52:44 18556 ?:25@atlas-get4 sysXrdHttp:  Entering SSL_accept...
170818 15:52:44 18556 ?:25@atlas-get4 sysXrdHttp:  SSL_accept returned :1
170818 15:52:44 18556 ?:25@atlas-get4 sysXrdHttp:  SSL_get_verify_result returned :0
170818 15:52:44 18556 ?:25@atlas-get4 sysXrdHttp:  Extracting auth info.
170818 15:52:44 18556 ?:25@atlas-get4 sysXrdHttp:  SSL_get_peer_certificate returned :0x7f50a4014300
170818 15:52:44 18556 ?:25@atlas-get4 sysXrdHttp:  Setting link name: 'eyermuth'
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  SSL_get_peer_certificate returned :0x7f50a4014300
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  SSL_get_verify_result returned :0
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  SSL_get_peer_cert_chain :0x7f50a4013b30
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  fqan :/atlas/Role=NULL/Capability=NULL
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  fqan :/atlas/de/Role=NULL/Capability=NULL
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  Setting VO: atlas roles :/atlas/Role=NULL/Capability=NULL
170818 15:52:44 18556 sysXrdHttp: getDataOneShot BuffAvailable: 1048576 maxread: 1048576
170818 15:52:44 18556 sysXrdHttp: getDataOneShot sslavail: 1048576
170818 15:52:44 18556 sysXrdHttp: read 225 of 1048576 bytes
170818 15:52:44 18556 sysXrdHttp:  rc:59 got hdr line: PROPFIND /beegfs/grid/atlas/atlaslocalgroupdisk/ HTTP/1.1

170818 15:52:44 18556 sysXrdHttp:  rc:40 got hdr line: User-Agent: libdavix/0.6.4 neon/0.0.29

170818 15:52:44 18556 sysXrdHttp:  rc:14 got hdr line: Keep-Alive: 

170818 15:52:44 18556 sysXrdHttp:  rc:24 got hdr line: Connection: Keep-Alive

170818 15:52:44 18556 sysXrdHttp:  rc:14 got hdr line: TE: trailers

170818 15:52:44 18556 sysXrdHttp:  rc:41 got hdr line: Host: xrootd001.physik.uni-bonn.de:1094

170818 15:52:44 18556 sysXrdHttp:  rc:10 got hdr line: Depth: 1

170818 15:52:44 18556 sysXrdHttp:  rc:21 got hdr line: Content-Length: 303

170818 15:52:44 18556 sysXrdHttp:  rc:2 got hdr line: 

170818 15:52:44 18556 sysXrdHttp:  rc:2 detected header end.
170818 15:52:44 18556 XrootdBridge: Oliver F.1:25@atlas-get4 login as Oliver Freyermuth
170818 15:52:44 18556 Oliver F.1:25@atlas-get4 sysXrdHttp:  Process. lp:0x7f50a4000ca8 reqstate: 0
170818 15:52:44 18556 sysXrdHttp: Reading request body 303 bytes.
170818 15:52:44 18556 sysXrdHttp: BuffgetData: need to read 303 bytes
170818 15:52:44 18556 sysXrdHttp: getDataOneShot BuffAvailable: 1048576 maxread: 303
170818 15:52:44 18556 sysXrdHttp: getDataOneShot sslavail: 303
170818 15:52:44 18556 sysXrdHttp: read 303 of 303 bytes
170818 15:52:44 18556 Oliver F.1:25@atlas-get4 sysXrdHttp: Process is exiting rc:0
170818 15:52:44 18556 ofs_stat: Oliver F.1:25@atlas-get4 Unable to locate /beegfs/grid/atlas/atlaslocalgroupdisk/; permission denied
170818 15:52:44 18556 sysXrdHttp:  XrdHttpReq::Error
170818 15:52:44 18556 Oliver F.1:25@atlas-get4 sysXrdHttp: PostProcessHTTPReq req: 8 reqstate: 0
170818 15:52:44 18556 Oliver F.1:25@atlas-get4 sysXrdHttp: Sending resp: 404 len:75
170818 15:52:44 18556 sysXrdHttp: Sending 46 bytes
170818 15:52:44 18556 sysXrdHttp: Sending 75 bytes
170818 15:52:44 18556 sysXrdHttp:  XrdHttpReq request ended.
170818 15:52:44 18556 sysXrdHttp:  Cleanup
170818 15:52:44 18556 sysXrdHttp:  SSL_shutdown failed
170818 15:52:44 18556 sysXrdHttp:  Reset
170818 15:52:44 18556 sysXrdHttp:  XrdHttpReq request ended.
170818 15:52:44 18556 XrootdXeq: Oliver F.1:25@atlas-get4 disc 0:00:00 (send failure)
```
From that I deduce, that extraction works fine, since:
```
170818 15:52:44 18556 eyermuth.0:25@atlas-get4  Setting VO: atlas roles :/atlas/Role=NULL/Capability=NULL
```
However, in the end I see a 404 on the client, and as you can see above, a permission denied on the server. 
The auth_file contains:
```
g /atlas /beegfs/grid/atlas/atlaslocalgroupdisk
```
Changing that to:
```
u * /beegfs/grid/atlas/atlaslocalgroupdisk
```
let's things work fine, but of course I do not want that. 

The authentication rule works perfectly fine via the xrootd protocol. 

My configuration is:
```
acc.authdb /etc/xrootd/auth_file-grid
acc.authrefresh 60
all.export /beegfs/grid/atlas/atlaslocalgroupdisk r/w
all.role server
all.sitename XXX
cms.allow localhost
desthttps yes
http.cadir /etc/grid-security/certificates
http.cert /etc/grid-security/hostcert.pem
http.key /etc/grid-security/hostkey.pem
http.secxtractor /usr/lib64/libXrdHttpVOMS.so
http.selfhttps2http no
http.trace all
http.secretkey someverylongthingiwillnotincludehereasyoumayguess
http.embeddedstatic yes
if exec xrootd
xrd.protocol XrdHttp /usr/lib64/libXrdHttp.so
fi
ofs.authorize
sec.protocol /usr/lib64 gsi -ca:1 -crl:3 -gridmap:/dev/null -cert:/etc/grid-security/hostcert.pem -key:/etc/grid-security/hostkey.pem -certdir:/etc/grid-security/certificates
sec.protparm gsi -vomsfun:/usr/lib64/libXrdSecgsiVOMS.so -vomsfunparms:certfmt=raw|vos=atlas,ops|grps=/atlas,/ops
xrd.port 1094
xrootd.seclib /usr/lib64/libXrdSec.so
```

Any ideas?

Also, where's the source code of xrdhttpvoms available?

**Comment by ffurano** [comment]
Hi,
as you correctly spotted, XrdHTTP only does authentication and
internally fills the XrdSecEntity structure, while authorization
in theory is demanded to the rest of the Xrootd framework.

Which authorization plugin is your system using ?

I see an "/atlas" in your auth_file, while XrdHTTP detects the VO name as "atlas". Maybe it's a question of removing a slash there ?

**Comment by ffurano** [comment]
Ah, the code of xrdhttpvoms is here:
https://svnweb.cern.ch/trac/lcgdm/browser/xrdhttpvoms

... otherwise you can just download the source RPM from epel.

**Comment by olifre** [comment]
> Which authorization plugin is your system using ?

I only have
```
ofs.authorize
xrootd.seclib /usr/lib64/libXrdSec.so
```
in my configuration... isn't that sufficient? 

Using another line with 
```
g atlas /beegfs/grid/atlas/atlaslocalgroupdisk a
```
does not change anything. 

Thanks for the link with the code! 👍

**Comment by ffurano** [comment]
uhm I mean which XrdAcc and which acc directives, according to the docs:
http://xrootd.org/doc/dev47/sec_config.htm#_Toc489606556

**Comment by olifre** [comment]
Ah... well, I only use `acc.authdb` and `acc.authrefresh` as you can see... what else would I need? 
Doesn't it only need to check the content of the authdb file against the secxtracted attributes?

**Comment by olifre** [comment]
@ffurano Any further ideas? Am I missing something in the configuration? Since all works fine with the xrootd protocol, I thought my configuration would be complete.

**Comment by bbockelm** [comment]
This line sticks out to me:

```
170818 15:52:44 18556 ofs_stat: Oliver F.1:25@atlas-get4 Unable to locate /beegfs/grid/atlas/atlaslocalgroupdisk/; permission denied
```

It's not quite clear from the file - I think that `permission denied` may be coming from the underlying filesystem, not necessarily Xrootd.  Usually if you are stuck in the `acc` authorization system, the lines are prefixed with `acc` somewhere.

Are you trying to access the same directory via HTTP and Xrootd protocols?

**Comment by olifre** [comment]
> Are you trying to access the same directory via HTTP and Xrootd protocols?

Yes, I am. Furthermore, the folder belongs to the xrootd user.

**Comment by olifre** [comment]
Furthermore, things work fine if I put `u * /beegfs/grid/atlas/atlaslocalgroupdisk` in the auth-file, see above...

**Comment by bbockelm** [comment]
Alright - there's probably a debugging level for the `acc` system we're missing somewhere.  Can you try adding this:

```
acc.audit deny grant
```

Looking at the code from Fabrizio, it seems that the `group` field is not populated but the `org` one is.  Maybe:

```
o atlas /beegfs/grid/atlas/atlaslocalgroupdisk lr
```

?

(note: we don't use this plugin for authorizing locally, so I'm just guessing here...)

**Comment by olifre** [comment]
Seems like version 4.6.1 which we use from stable repos does not like `o`:
```
Config 3 authorization directives processed in /etc/xrootd/xrootd-grid.cfg
170820 18:18:27 25967 acc_AuthFile: Invalid id type - o
Config 3 auth entries processed in /etc/xrootd/auth_file-grid
------ Authorization system initialization failed.
```

Trying without that, but with:
```
acc.audit deny grant
```
at least the output confirms:
```
170820 18:20:18 25996 Oliver F.1:26@atlas-get4 ofs_stat:  fn=/beegfs/grid/atlas/atlaslocalgroupdisk/
170820 18:20:18 25996 acc_Audit:  deny  Oliver Freyermuth@[::ffff:131.220.165.108] stat /beegfs/grid/atlas/atlaslocalgroupdisk/
170820 18:20:18 25996 ofs_stat: Oliver F.1:26@atlas-get4 Unable to locate /beegfs/grid/atlas/atlaslocalgroupdisk/; permission denied
170820 18:20:18 25996 Oliver F.1:26@atlas-get4 XrootdProtocol: 0000 rc=-1 stat /beegfs/grid/atlas/atlaslocalgroupdisk/
170820 18:20:18 25996 Oliver F.1:26@atlas-get4 XrootdResponse: 0000 sending err 3010: Unable to locate /beegfs/grid/atlas/atlaslocalgroupdisk/; permission denied
170820 18:20:18 25996 sysXrdHttp:  XrdHttpReq::Error
170820 18:20:18 25996 Oliver F.1:26@atlas-get4 sysXrdHttp: PostProcessHTTPReq req: 8 reqstate: 0
170820 18:20:18 25996 Oliver F.1:26@atlas-get4 sysXrdHttp: Sending resp: 404 len:75
```
So it seems permission denied really is translated into 404.

**Comment by olifre** [comment]
@bbockelm I also see that only the organisation field seems to be filled by `xrdhttpvoms`... 
Does this mean I'll have to wait until 4.7 (which supports org and role) becomes stable to use that? 
I wonder how `xrdhttpvoms` is used by others then, since `xrdhttpvoms` seems to be already about 2 years old.

**Comment by bbockelm** [comment]
Oh, indeed - I see this ticket indicating the `o` option is fairly new: https://github.com/xrootd/xrootd/issues/416

Yeah - I don't know how `xrdhttpvoms` is meant to be used then.  Locally, we use `XrdLcmaps`, which hooks into the LCMAPS stack for proxy attribute extraction.  Here's an example config file:

http://opensciencegrid.github.io/StashCache/admin/configure-cache/

LCMAPS provides the username mapping and extraction, then maps VOMS groups to the Xrootd group names.

**Comment by olifre** [comment]
> LCMAPS provides the username mapping and extraction, then maps VOMS groups to the Xrootd group names.

This sounds like a nice alternative! I looked at `xrdhttpvoms` since it seemed to be more lightweight. 

I'll have a look after my holidays are over - unless xrootd 4.7 comes out in the meanwhile and let's `xrdhttpvoms` magically work when using `o` ;-).

**Comment by xrootd-dev** [comment]
It would appear that the voms plugin used by xrootd authentication 
populates te group field while the HTTP one does not (or populates it in a 
different way). This I deduce because you said:

g /atlas /beegfs/grid/atlas/atlaslocalgroupdisk
```
Changing that to:
```
u * /beegfs/grid/atlas/atlaslocalgroupdisk
```
let's things work fine, but of course I do not want that.

The authentication rule works perfectly fine via the xrootd protocol.

So, the question is why is this he case?

Yes, to switch to using o and r as well as composite rules (i.e. ones that 
"and" o and r, among others), will be available in 4.7.0.

Andy

On Sun, 20 Aug 2017, olifre wrote:

>> LCMAPS provides the username mapping and extraction, then maps VOMS groups to the Xrootd group names.
>
> This sounds like a nice alternative! I looked at `xrdhttpvoms` since it seemed to be more lightweight.
>
> I'll have a look after my holidays are over - unless xrootd 4.7 comes out in the meanwhile and let's `xrdhttpvoms` magically work when using `o` ;-).
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xrootd/xrootd/issues/566#issuecomment-323602010
>
> ########################################################################
> Use REPLY-ALL to reply to list
>
> To unsubscribe from the XROOTD-DEV list, click the following link:
> https://listserv.slac.stanford.edu/cgi-bin/wa?SUBED1=XROOTD-DEV&A=1

**Comment by bbockelm** [comment]
FWIW - here's the relevant code for `xrdhttpvoms` extracting the VOMS attributes and putting it into the `XrdSecEntity` object: https://svnweb.cern.ch/trac/lcgdm/browser/xrdhttpvoms/trunk/XrdHttpVoms.cc#L160

In the meantime, I'd point out that the first release candidate for 4.7.0 has been tagged.  I believe we are running it on one host locally.  I'm sure feedback would be greatly appreciated!

For `XrdLcmaps`, the relevant code is here:

https://github.com/opensciencegrid/xrootd-lcmaps/blob/master/src/XrdLcmapsKey.cc#L19

(there's quite a bit of other stuff to the plugin, since it has to invoke an external library and it caches the lookups).  One logical difference is that `libXrdLcmaps.so` serves as an authentication plugin for both the `xrootd` and `https` protocols, allowing a unified set of logic across both.

**Comment by ffurano** [comment]
Hi,

 well, if you think that xrdhttpvoms should populate one more
field (group) we can do it and publish pretty quickly to epel.

 How should it be populated ? Shall the group names start with
a slash ?

Cheers
Fabrizio

**Comment by xrootd-dev** [comment]
Hi Fabrizio,

My first take is that the group field should be populated; it's part of 
the x509 cert. I'd like to say that it should be populated just the same 
way as the VOMS plugin does. I say "like" because I'm not convinced that 
the VOMS plugin actually does it the right way (hence your question about 
the slash). So, let's see what other people say before we change 
anything. Mind you we do have compatability issues here but it would be 
good to hear from others anyway.

Andy

**Comment by ffurano** [comment]
Hi Andy,

 I agree on being careful and asking others. At the same time
it seems to me that the main consumer of that field is the default
Acc plugin. Which format does it expect for the "group" field ?

 - comma-separated list of groups or just one?
 - should they start with a slash (why?!?!) as I see in the example
   configs?

As I said, we can publish a fix to epel pretty quickly, and I would like it to be
the right thing :-)

Cheers
Fabrizio

**Comment by bbockelm** [comment]
Looking at what I did for `XrdLcmaps`:
- *space*-separated list of groups. 
- They should start with a slash; VOMS groups are hierarchical (i.e., `/atlas/foo/bar` is distinct from `/atlas/baz`) unlike Unix groups.

One open question is how we should handle a proxy certificate with multiple VOMS extensions present - i.e., a proxy certificate with both ATLAS and CMS extensions.  After all, it's perfectly acceptable for the CMS VOMS server to sign an extensions with FQAN `/atlas`.  It's traditional that CMS group names are prefixed with `/cms`, but not enforced or validated by the client.

**Comment by gganis** [comment]
Sorry for entering the discussion late.
Sometime ago we had a similar discussion which ended up in the choice for space-separated list of groups. This is also what vomsxrd does.
For the slashes, I am not sure why we should enforce something different from what the service filling the extensions does. Now, it happens that VOMS proxies typically have groups starting with a '/', but should we modify what they have in the extension?

**Comment by olifre** [comment]
Just to chime in (I'm more "user" / sysadmin than developer here):
I would indeed expect the group field to be filled with the data from the VOMS extension as it is provided, i.e. starting with a '/'. Space-separated if multiple groups are present sounds consistent. 

Summarizing, this seems to be compatible with `XrdLcmaps` and the existing VOMS plugin for the xrootd protocol. 

So if I see it correctly, if `xrdhttpvoms` fills the group field like that, all existing plugins would fill the group field in the same way, allowing for a common `authdb` with xrootd < 4.7. 
For xrootd >= 4.7, one would likely prefer to use `o` and `r` to adjust permissions in a more fine-grained manner (i.e. only atlas people / robots with production role are allowed to write to the rucio data disks).

**Comment by xrootd-dev** [comment]
Hi Fabrizio,

It expects a space separated list of groups, though as far as I can see, 
certs usually (if not exclusively) only have one group specified. As for 
teh leading slash, I have always been confused by that and no one has been 
able to provide a good reason why that is the case. Perhaps Wei can chime 
in.

Andy

**Comment by xrootd-dev** [comment]
Thank you Brian for explaining slash usage.

**Comment by ffurano** [comment]
Hi,

 FYI, we will push a new release of XrdHttpVOMS (0.2.5) to epel-testing in the next few days,
here's an example of the way it extracts groupnames from the primary fqan:

170831 17:27:12 4327 furano.0:24@lxplus023  VOMS data - user: '/DC=ch/DC=cern/OU=Organic
Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano'
170831 17:27:12 4327 furano.0:24@lxplus023  VOMS data - vorg: 'dteam'
170831 17:27:12 4327 furano.0:24@lxplus023  VOMS data - fqan[0]:/dteam/Role=NULL/Capability=NULL
170831 17:27:12 4327 furano.0:24@lxplus023  VOMS data - grps: '/dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL'
170831 17:27:12 4327 furano.0:24@lxplus023  VOMS data - role: 'NULL'
170831 17:27:12 4327 furano.0:24@lxplus023  VOMS proxy info - name: '/DC=ch/DC=cern/OU=Organic
Units/OU=Users/CN=furano/CN=644746/CN=Fabrizio Furano' VO: dteam grps: '/dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL'

 Please let me know if you think that there's anything to fix for XrdAcc to treat correctly these fields.

Cheers
Fabrizio

**Comment by wyang007** [comment]
I think LCMAPS is probably a good approach for sites that already deployed Grid middleware. It provides a consistent and familiar interface to site admins. In data transfer use case, the overhead of LCMAPS is also acceptable - we have used it with SRM and GridFTP for years. One question for LCMAPS is whether it is used in EU or not.

Having said that, there are cases that we want something light weight such as VOMSXRD or XrdHTTPVOMS. One question is that we normally have several VOMS attribute attached to a proxy, like this:

subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yangw/CN=667097/CN=Wei Yang
issuer    : /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
attribute : /atlas/Role=production/Capability=NULL
attribute : /atlas/Role=NULL/Capability=NULL
attribute : /atlas/lcg1/Role=NULL/Capability=NULL
attribute : /atlas/usatlas/Role=NULL/Capability=NULL
attribute : nickname = yangw (atlas)



I _think_ when we initiate the proxy, we can control which one is first in the list of attributes. So we can either take all attributes (if we figure out how), or the first one (or last one), similar to what VOMSXRD does.

I think something like "grps: '/dteam /dteam/Role=NULL /dteam/Role=NULL/Capability=NULL’” is the cleanest. People can tell immediately who gets what in authdb. Q: Can the NULL items be ignored? How do we handle those spaces in authdb?

regards,
--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

**Comment by xrootd-dev** [comment]
Hi Wei,

 thank you for the feedback, as far as I can understand you like the current
way of exploding the first fqan, and you leave a door open to
the possibility of exploding them all into groupnames.

 About the spaces I have no idea, as Andy suggested that format previously
in this thread. I simply honoured it, and I assume that XrdAcc treats
correctly such a string.

 I'd say then that we can push the current version to epel-testing (likely today)
and if anyone thinks that they need some other token from the
secondary fqans then it can be added later.

 Cheers
Fabrizio

**Comment by bbockelm** [comment]
Hi,

VOMS extensions have two (somewhat orthogonal) concepts - groups and roles.
- An extension can have _one_ Role and it has to show up in the first FQAN.  This most cleanly maps to the `role` field in the security entity.
- It can have multiple, ordered groups.  The user _may_ control the first one if desired.  It really makes most sense to take the group names in the same order - and a bit of sense to provide an option for including only the first.  I never figured out why `vomsxrd` presents an option to only take the last one, as the last group is server-defined and not managed by the user.
  - This is a close analog to Unix groups, where the primary group has special meaning but the remainder are basically treated as unordered.
- The "capability" stuff was abandoned about a decade ago but never removed completely from the libraries.

IIRC, VOMSXRD also copies over the FQAN (the first entry in the list of attributes) into the endorsements field.

I'm quite happy with the way `XrdLCMAPS` and `VOMSXRD` work currently - if we could document those and make sure the `XrdHTTPVOMS` plugin has the same logic, it'd be quite useful to have consistency across the board.

Brian

PS - Wei: LCMAPS is developed and maintained by NIKHEF, originally for EGEE / EGI.  Should be awfully familiar to many sysadmins (there are a few other supported options, of course).

**Comment by xrootd-dev** [comment]
Hi,

 FYI, the latest release of XrdHttpVOMS was pushed to epel-testing
last Friday, and is available in the mirrors for testing.

 Please have a look at it and report to me your findings.

 In the absence of feedback we will promote it to epel-stable
right after the canonical period.

Cheers
Fabrizio

**Comment by wyang007** [comment]
Hi Brian,

thanks for the reminder  - I was confused about LCMAPS and its xrootd plugin…

regards,
--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338

**Comment by ffurano** [comment]
FYI, the canonical test period for epel-testing has abundantly passed. In the absence of further comments on XrdHTTPVoms I'd assume that now it's fine and push it to stable.

**Comment by simonmichal** [comment]
So, can we close this issue?

Michal

**Comment by bbockelm** [comment]
Yes, I think we can resolve it - the last few comments were an (interesting!) sub-thread.
