### ISSUE TITLE
Reverse IPv6 resolution seems to be broken

### ISSUE THREAD

**Issue by herver** [xrootd/xrootd#578]
(Could be related to #407)

Context: In EOS, we use `XrdSysDNS::getAddrName` to to a reverse resolution of the client's IP address: https://gitlab.cern.ch/dss/eos/blob/master/mgm/http/HttpServer.cc#L111 

When we pass an IPv6 address (`2001:1458:301:bb::100:43` for instance), the `XrdSysDNS::getAddrName` call fails despite the IP address having a valid reverse record:

```
$ dig PTR 3.4.0.0.0.0.1.0.0.0.0.0.0.0.0.0.b.b.0.0.1.0.3.0.8.5.4.1.1.0.0.2.ip6.arpa +short
eoslhcbhttp01.cern.ch.
```

It seems that the code around https://github.com/xrootd/xrootd/blob/master/src/XrdSys/XrdSysDNS.cc#L173 and https://github.com/xrootd/xrootd/blob/master/src/XrdSys/XrdSysDNS.cc#L69 is not really IPv6 aware.

**Comment by abh3** [comment]
Ah, you are absolutely correct! However, XrdSysDNS is now deprecated for everything including IPv6 (it never really had IPv6 support). Please migrate to XrdNetAddr which has complete IPv6 support.
