### ISSUE TITLE
Improve XrdHttpExtHandler flexibility

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#585]
I started looking into using the `XrdHttpExtHandler`, but immediately started to hit some problems.

1.  The only mechanism for handling a request is from path-based matching.  It's not possible to filter based on the verb (GET vs POST) or one of the headers.
    - Proposal: Either change the `MatchesPath` function to include the HTTP verb, or allow the `ProcessReq` to return a special value indicating the handler did not actually want to handle the request in the end.  The latter, of course, has a higher CPU overhead.
2.  I need more information from the authentication session than what is in the `XrdHttpExtReq` object.  For example - there's no VOMS information here (i.e., the contents of `vorg`).  As I started to add the information I need for making authorization decisions, I find myself quickly replicating the `XrdSecEntity` structure.
    - Proposal: Add a `const XrdSecEntity *` to the `XrdHttpExtReq`
3.  The `XrdHttpExtHandler` headers are not public, meaning I can't actually link against them yet.
    - Proposal: Once the above binary-compat-breaking changes are made, make the header public and require the standard version-checking scheme.

Thoughts?

**Comment by bbockelm** [comment]
Toward (2) -- it seems that this is in the object (well, in the `XrdHttpProtocol` member); we just need to add an accessor function.

**Comment by ffurano** [comment]
Hi Brian,
 I am very happy that this component generated so much interest. I'll try to follow your arguments and comment:

1) indeed, MatchesPath() only matches the path, matching the verb was not in my requirements, so I did not think at that. I should have.
    For a future enhancement maybe the latter is preferable and would preserve the ABI, which is a little bonus
2) Same as 1) In the context of DPM the auth info comes through the header adn does not need the vorg, so it was not thought at. To be sincere, in that context I have done wat you say, i.e. creating my own sec structure, where the things have the right name and proper data structures.
  PS I see your other comment, yes an accessor function may be possible.
3) It's in the xrootd-private-devel RPM. If DPM links against them, then you can too.

**Comment by bbockelm** [comment]
Toward (3) -- from the RPM metadata of the private headers:

"Legacy xrootd headers ... The use of these headers is strongly discouraged. Backward compatibility between versions is not guaranteed for these headers."

Since backward compatibility is not guaranteed, we can make the change we want to in (1), no?

If we have to link against private headers to reasonable implement external plugins, it makes sense to call them public at that point -- otherwise, what's the point of calling it "private" vs "public"?

@abh3 - what are your thoughts here?

**Comment by bbockelm** [comment]
Another thing to think about - `XrdHttpExtReq` was added in 4.7.0, meaning that we probably want to make sure the runtime version compatibility checker makes that as the minimum version number.

**Comment by ffurano** [comment]
I am definitely not a philosopher of ABI compatibility, and I have put those headers with the private ones exactly to have more freedom, until the interface stabilizes, which can take quite some time.
 Hence I am proposing that you use them where they are now, and once we are happy we decide what to do. We will need to coordinate a bit the changes, which may be less expensive in this phase than pushing an immature interface.

**Comment by ffurano** [comment]
BTW what is the "runtime version compatibility checker" that you are referring to ?
