### ISSUE TITLE
A client cannot specify which key to use from an SSS keytab file

### ISSUE THREAD

**Issue by murrayc3** [xrootd/xrootd#591]
XRootD does not provide an explicit mechanism for a client to specify which key to use from an SSS keytab file.

Applications currently rely on the fact that a client will use the last key specified within an SSS keytab file.

**Comment by abh3** [comment]
Just touching back on whether this is needed. In R5, the client reports which keyname it is using so that the right key can be extracted from a composite keytab. Generally, we advise allowing client to access a keytab that is being used by different clients. So, generally, the client's keytab would have a single keyname. Just want to be sure that given the change in R5 this is still relevant.

**Comment by murrayc3** [comment]
Hi Andy,

It’s OK.  You could throw an error if there is more than one entry in the keytab of a client.  I understand that you simply need to know that there should only be one entry in a client keytab and that if there are many then one will be chosen for you which you should avoid.

Cheers,

Steve

**Comment by xrootd-dev** [comment]
Hi Steven,

Not so fast! We now have the capability to select a particulat key 
client-side. That ofcource would be done via an envar setting. The 
question is do you really need to do that. I really don't want to throw 
exceptions plus it very difficult to figure out of there is more than one 
keyname in the file (we generally recommend against that). So, the 
question remains, do you really want this feature?

Andy

**Comment by murrayc3** [comment]
Hi Andy,

| see your point.  The reason for the original ticket was the confusion around client keytab files.  Clients could be given multi entry keytab files and you had to know that the last entry won.  Now that I have experience with XRootD I see that it was wrong for us to be giving clients multi entry keytabs.  You can drop the feature if you like.  I am now wiser when I encounter a multi-entry keytab file.  My first reaction will be to ask the responsible for the file to reduce it to just one entry, otherwise I’ll know that the last entry wins.

Cheers,

Steve

**Comment by abh3** [comment]
Reporter has said this feature is no longer needed
