### ISSUE TITLE
[SSI] Incorrect response type on Metadata-only messages

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#594]
Since the updates on 29/09/2017, when the server sends a Metadata-only response:

On the server side: SetNilResponse() is called, which sets the response type to isData

On the client side, in Request::ProcessResponse(): the response type received is isStream

The client always sees the same response, isStream.

**Comment by abh3** [comment]
I have not been able to reproduce this in any way. Perhaps something went wrong with the installation or maybe something else is wrong. So...

On my client (interactive test program):
run /tmp echo ?metadata
/tmp@rhel6-64h:1094: Rcvd isData response with 9 metabytes 'metadata'
Received 0 bytes from /tmp@rhel6-64h:1094

Notice the server responded 'isData' with some metadata. On the server tracing with gdb:

400        if (!(*rData))
401           {if ((rc = SetNilResponse())) ResponseFailed(rc);
(gdb) c
171002 14:55:53 3078 abh.2193:23@rhel6-64k Ssi_ProcessResponse: 0:/tmp [bound xqReq] Response presented wtr=False
171002 14:55:53 3078 abh.2193:23@rhel6-64k Ssi_ProcessResponse: 0:/tmp [bound doRsp] Resp data sz=0

**Comment by slithy** [comment]
Just to confirm, you are testing against commit b065688 ?

This problem appeared when we installed xrootd commit b065688 on our production instance (without changing any other software). I recompiled on my dev box against b065688 and the problem appeared. When I rolled back to 4.7.0 it disappeared.

I will try tomorrow to step back one commit at a time to work out exactly at what point the problem appeared.

**Comment by slithy** [comment]
I used git bisect to track down when the problem first occurred:

a6784c3b9b562860ec175b973b343fb8c705927a is the first bad commit

**Comment by slithy** [comment]
The offending line of code is src/XrdSsi/XrdSsiFileReq.cc line 333:
```
if (haveResp)
   respWait = true;
```
After the above commit, in the following method on the client side:
```
Request::ProcessResponse(const XrdSsiErrInfo &eInfo, const XrdSsiRespInfo &rInfo)
```
the client receives rInfo.rType == XrdSsiRespInfo::isStream (incorrect, there are no stream messages in this setup).

If I change line 333 back to what it was previously:
```
if (XrdSsiRRAgent::RespP(this)->rType == XrdSsiRespInfo::isNone)
   respWait = true;
```
then I the client receives rInfo.rType == XrdSsiRespInfo::isData (correct).

Is that enough information to diagnose the problem?

**Comment by abh3** [comment]
Well, we can change it to be that but it violates what the commit was trying to do (referencing a member that wan't locked). So, the problem is more devious. I'm OK to reverting the commit is that gets you going. I will look into it further,

**Comment by slithy** [comment]
I don't have enough detailed knowledge of the code to understand what "haveResp" is. Can you suggest how changing the line to "haveResp" might cause the response type to be given as isStream?

**Comment by abh3** [comment]
Hi Michael,

There really is no way that changing that line would affect what type for response is sent. In fact, that line was changed on the first update (that I might add worked for you) to haveResp – that was the fix. So, something else has changed that I don’t know about. So, some questions:

a) Does the wrong response gets posted every time or just once in a while?
b) Can you send me a log (server-size and client side) with debugging turned on (for SSI it’s in the config file for the client it’s turned on via envar XRDSSIDEBUG – any value will do).

I will look again but right now I don’t see how this could be happening. The only way would be if you were using the wrong header files (for instance) or, perhaps, the wrong shared library (i.e. a previous version of libXrdSsiLib.so or libXrdSsi.so).

Andy
