### ISSUE TITLE
CMSSW, stable-4.7x, invalid reads/writes ReOpenFileAtServer -> ~XrdSysMutexHelper -> UnLock ->  pthread_mutex_unlock

### ISSUE THREAD

**Issue by davidlt** [xrootd/xrootd#610]
This weekend I updated xrootd to tip of `stable-4.7.x` which solved valgrind issues mentioned here: https://github.com/cms-sw/cmssw/issues/21059 Later I found an addition issue and details are here: https://github.com/cms-sw/cmssw/issues/21071

**Comment by simonmichal** [comment]
Hi David,

Thanks for reporting the problem!
It has been addressed in: 186bde704b347b29085d4ea0892500a5fe09b6f2

Cheers,
Michal

**Comment by davidlt** [comment]
Do you plan to put that into stable-4.7.x (i.e. before 4.7.1 released)?

**Comment by simonmichal** [comment]
If there is a strong desire I can include this in 4.7.1 as this requires only testing on my side ;-)
(I don't think we need an RC for this one)

**Comment by davidlt** [comment]
I would prefer not to put out-of-tree patches on top of 4.7.1. Thus would be nice to have in 4.7.1 as we are hitting it.

**Comment by bbockelm** [comment]
Yeah, I would also vote to hold up the release for this one.  We have the technical ability to do out-of-tree patches, but it's always best to avoid it...

**Comment by simonmichal** [comment]
No problem, it's already ported to stable-4.7.x.
