### ISSUE TITLE
python binding RPM packaging - "xrootd-python" vs "python2-xrootd"?

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#614]
The proper name for the xrootd python bindings seems disputed:
The "canonical" repo on http://xrootd.org/binaries/stable/slc/7/x86_64/ has "xrootd-python", but widely-used EPEL calls them "python2-xrootd" since

> * Thu Aug 10 2017 Mattias Ellert <mattias.ellert@physics.uu.se> - 1:4.6.1-6
>   - Rename python sub-package

and this of course can cause issues on machines that "see" both repositories.

**Comment by bbockelm** [comment]
The EPEL version is correct.  See the platform guidelines for python package naming: https://fedoraproject.org/wiki/Packaging:Python.  In addition to following the community guidelines, the EPEL style allows multiple python major versions (`python2-xrootd`, `python3-xrootd`).

Note the EPEL packaging takes backward compatibility into account: the package also has `Provides: xrootd-python`, meaning other package dependencies will continue to resolve.

It'd be useful for Xrootd to follow this change.
