### ISSUE TITLE
Specify max number of migrations and staging separately

### ISSUE THREAD

**Issue by ycalas** [xrootd/xrootd#617]
As far as I know (and if I am not wrong), it is not possible to specify the maximum number of migration and staging separately in the XRootD configuration file. You can only use the copymax directive which represents the "maximum number of transfers allowed to occur at the same time", and "migration competes with staging".

Would it be possible to propose (in a coming release) new frm directives in order to specify the maximum number of staging and the maximum number of migration separately? It would be a nice feature IMHO ;)

**Comment by abh3** [comment]
Sorry for taking so long to getting back to this but we do have a lot of other issues to address. The proposal to allow separate limits for each activity is a good one but I think needs to be a bit more flexible. So, I would suggest something like:

xfrmax  <xfrmax> in <inmin> out <outmin> 

The <inmin> value is the number of transfer threads that must be reserved to handle traffic for in and <outmin> the same for out activity. The sum <inmin>+<outmin> may not exceed <xfrmax> and usually should be less than <xfrmax>. This allows load shifting from in to out activity depending on what work is queued but also reserves threads to exclusively handle a particular activity, leavng <xfrmax>-<inmin>-<outmin> to handle either activity.

Now, all that said, the current implementation round robins across all the queues, picking the oldest request if it has a choice within a queue. So, while migrations compete against staging they compete on an equal level and neither activity should be starved, though not necessarily in a fair way if the queue is suddenly filled with one type of request. However, you could argue that's OK as we are trying to empty the queues as fast as possible, assuming that neither activity is more important than the other. That is a naive assumption for certain workflows but seems to work in most cases.

**Comment by abh3** [comment]
OK, three years in the making, I hope you still want the feature. Look at the frm.xfr.copymax directive split feature:
https://xrootd.slac.stanford.edu/doc/dev50/frm_config.htm#_Toc38055273

It will be available in Rrelease 5.
