### ISSUE TITLE
XrdHttpExtReq should expose protocol used

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#619]
In my external handler, I want to refuse certain actions unless they were done via HTTPS.

However, there's no way to determine whether the current request came in via HTTP or HTTPS.  Can we add this as a field to the request?

**Comment by xrootd-dev** [comment]
Hi Brian,
uhm, can't you check the DN ?
f

**Comment by bbockelm** [comment]
It's not a safe assumption that any DN is present, especially as we start to transition away from client certificates...

**Comment by ffurano** [comment]
Ok. Would it be fine for you to use SecEntity.prot and write "http" or "https" into it ?

Please be aware that one can always use the self-redirection https->http

**Comment by bbockelm** [comment]
Yes, filling in `SecEntity` sounds like a very good idea.

I'm doing this to avoid:
- Using bearer tokens when working over HTTP (inherently insecure due to trivial MITM issues, particularly if we want to do this with write-based workflows).
- Avoid inadvertent "downgrades" from HTTPS to HTTP.
