### ISSUE TITLE
[XrdHttp] HTTP PUT does not allow overwrites

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#620]
HTTP PUT is meant to be an idempotent operation:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

That is, it should be possible to PUT multiple times against the same resource - i.e., it should allow overwrites.

Unfortunately, XRootD does not do this - it disallows overwrites.

Seems to be as simple as changing this line: https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L1093

**Comment by abh3** [comment]
Actually, more correctly, xrootd *does* allow overwrites. It's just the 
http option selection directs it not to.

**Comment by bbockelm** [comment]
Correct - I should have written "XRootD's XrdHttp implementation of PUT does not do this".

As far as I can tell, one simply needs to remove an unnecessary flag when interacting with the bridge.  If there's no objections, I can put in the PR for this.

**Comment by abh3** [comment]
I don't have any objects but perhaps Fabrizio knows something we don't. 
Never hurts to have a PR out there :-)

Andy

**Comment by ffurano** [comment]
Hi,
 I can't recall any particular reason for that. It could be that noone (including me) has ever tried to
overwrite a file so far.
Brian, since you already have the tiny fix would you mind to do a pull request with it?
f

**Comment by bbockelm** [comment]
PR is #621.

**Comment by abh3** [comment]
Brian, do this get solved for you?

**Comment by bbockelm** [comment]
Yes, I believe #621 fixed this.  Closing the ticket.
