### ISSUE TITLE
[XrdHttp] Allow streaming HTTP ("Transfer-Encoding: chunked") responses

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#622]
For implementing the COPY requests with performance markers, we need to be able to respond using chunked transfer encoding (see: https://en.wikipedia.org/wiki/Chunked_transfer_encoding).

This would require a external handler interface that looks something like this:

```
XrdHttpExtReq::StartChunkedResp(int code, char *desc, char *header_to_add, char *body);
XrdHttpExtReq::ChunkResp(char *body, long long bodylen);
```

where a session would look like

```
req.StartChunkedResp(201, "OK", NULL);
req.ChunkResp("chunk 1", 0);
req.ChunkResp("chunk 2", 0);
req.ChunkResp(NULL, 0);
```

where `ChunkResp(NULL, 0)` indicates to send an end-of-response.

Would this be possible?

**Comment by abh3** [comment]
Fxed
