### ISSUE TITLE
Cannot install xroot-python

### ISSUE THREAD

**Issue by massimolamanna** [xrootd/xrootd#634]
Hi,
following the instruction I check out the code:

`git clone git://github.com/xrootd/xrootd-python.git`

and then (I am root on the node) I tried to install it (`python setup.py install`) but I got the  error listed at the end of this ticket. 

Thank you in advance,
Massimo

=== host information
It is a lxplus like node
uname -a:  

> Linux eospluswig701.cern.ch 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

with 4.8.0-rc1 installed

> [root@eospluswig701 xrootd-python]# rpm -aq | grep xroot
> xrootd-client-libs-4.8.0-0.rc1.el7.cern.x86_64
> xrootd-libs-4.8.0-0.rc1.el7.cern.x86_64
> xrootd-client-4.8.0-0.rc1.el7.cern.x86_64

and _*no* AFS installed_

=== setup.py error

[

> root@eospluswig701 xrootd-python]# python setup.py install
> XRootD library dir: /usr/lib
> XRootD include dir: /usr/include/xrootd
> [I] Determining version from git
> v0.3.0
> 
> running install
> running build
> running build_py
> running build_ext
> building 'pyxrootd.client' extension
> gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/xrootd -I/usr/include/python2.7 -c src/PyXRootDCopyProcess.cc -o build/temp.linux-x86_64-2.7/src/PyXRootDCopyProcess.o -g
> In file included from src/PyXRootDCopyProcess.cc:26:0:
> src/PyXRootDCopyProcess.hh:30:37: fatal error: XrdCl/XrdClCopyProcess.hh: No such file or directory
>  #include "XrdCl/XrdClCopyProcess.hh"
>                                      ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> [root@eospluswig701 xrootd-python]#

**Comment by massimolamanna** [comment]
Following Michal's advise, I installed python2-xrootd  and the package is there (the missing-file problem comes from the fact I do not have the dev stuff...

Maybe instructions can be updated

Thanx, Massimo

**Comment by simonmichal** [comment]
Hi Massimo,

I suppose we can close this one, right?

Thanks,
Michal
