### ISSUE TITLE
Correct combination of flags for "create with overwrite" for HTTP PUT?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#637]
Is it possible to "create with overwrite"?  This is needed for the HTTP PUT implementation, but doesn't seem possible.

We started with this:
```
xrdreq.open.options = htons(kXR_mkpath | kXR_open_updt | kXR_new );
```

this successfully creates the file, but doesn't allow it to be overwritten.  So, it was then changed to:

```
xrdreq.open.options = htons(kXR_mkpath | kXR_open_wrto );
```

This overwrites the file, but doesn't allow one to be created.

A bit of `grep`ing through the code, it seems like this does work

```
xrdreq.open.options = htons(kXR_mkpath | kXR_open_wrto | kXR_delete);
```

Any thoughts or opinions on this?  It would imply that HTTP PUT requires delete permission (which I recall is distinct from being able to create files?)

**Comment by bbockelm** [comment]
@ffurano - you might be interested in this ticket.

**Comment by xrootd-dev** [comment]
Hi Brian,

I think you want to drop the kXR_new which adds O_EXCL POSIX option which 
is causing your problems. Give it a try.

Andy
