### ISSUE TITLE
third party transfer authentication

### ISSUE THREAD

**Issue by imandr** [xrootd/xrootd#647]
I have a question. What is the correct way to use X509 and Kerberos authentication with third party transfers ?

Thanks.

**Comment by simonmichal** [comment]
Just use your credentials the same way as if this would be an ordinary transfer.

If you are interested in the details on how the TPC protocol is implemented visit:
http://xrootd.org/doc/dev4/tpc_protocol.htm

Does this answer your question?

**Comment by abh3** [comment]
I believe the previous post answered the question.
