### ISSUE TITLE
PID file /var/run/xrootd not re-created after reboot in RHEL7

### ISSUE THREAD

**Issue by zvada** [xrootd/xrootd#648]
The issue originates from #365 which has been marked as resolved. However, it seems like the resolution of #365 doesn't provide a very optimal solution to RHEL7 nature of handling the service run files. I.e. while `/var/run/xrootd` is created after `yum update|install xrootd`, it is not re-created when host is rebooted. 

We think this is a bug on the packaging level and requires better solution than currently sysadmin do: a) systemd override using `WorkingDirectory=/var/spool/xrootd` or b) setting `all.pidpath /var/run/xrootd -> /var/spool/xrootd` in the xrootd config. 

There were couple of options discussed, most viable and permanent solution according to tmpfiles.d manpages suggest create the file `/usr/lib/tmpfiles.d/xrootd.conf` with content:
```
/var/run/xrootd 0755 xrootd xrootd 
```

Thanks,
Marian

**Comment by zvada** [comment]
@simonmichal, any luck with a patch for this? I'm going to build 4.8.1 for OSG and realized fix has not been included yet.

**Comment by simonmichal** [comment]
Could you have a look at: https://github.com/xrootd/xrootd/commit/375abb579f1e6f71e04f9c95a545ed8347539b66
Isn't it exactly what you want?

From what I see on my CC7 installation the /usr/lib/tmpfiles.d/xrootd.conf is in place, and if I do a reboot it correctly recreates the /var/run/xrootd directory.

**Comment by zvada** [comment]
Yep! Obviously, this is an issue on the OSG side of packaging which I didn't notice beforehand. Fixing it now. Wish we can converge to the 1:1 spec content one day :). Closing.
