### ISSUE TITLE
pss.localroot not honored

### ISSUE THREAD

**Issue by herver** [xrootd/xrootd#650]
Affected version: 4.8.x (the option was broken in 4.7, working fine in 4.6)

We use `pss.localroot` to restrict the directories available to clients via proxies, but it turns out that the path restriction is not honored on recent XRootD versions:

The following file sits outside the configured `pss.localroot` but can happily be accessed by clients:
```
xrdfs xrdcmstzero6.cern.ch:1094 stat /store/mc/RunIISummer17PrePremix/Neutrino_E-10_gun/GEN-SIM-DIGI-RAW/MC_v2_94X_mc2017_realistic_v9-v1/40005/C0482830-37C9-E711-B00A-0242AC130002.root
Path:   /store/mc/RunIISummer17PrePremix/Neutrino_E-10_gun/GEN-SIM-DIGI-RAW/MC_v2_94X_mc2017_realistic_v9-v1/40005/C0482830-37C9-E711-B00A-0242AC130002.root
Id:     223196565536001
Size:   4148278104
MTime:  2017-11-16 05:40:15
Flags:  16 (IsReadable)
```

**Comment by abh3** [comment]
This seems to have regressed when we added additional name2name variants to accommodate caching proxies. In order for us to make sure this is also not due to a feature interaction, could you send (or post) your configuration file?

**Comment by abh3** [comment]
One more thing, does the proxy log show the message

Config warning: ignoring namelib ....

If so, what is the complete message as this will give us a what the configuration process is getting upset about.

**Comment by bbockelm** [comment]
Hi --

For context, this is causing quite a bit of havoc for CMS jobs in Europe (proxy servers are exporting way too much data and getting overloaded).  So, it's a pretty urgent one for CMS.

@herver - thanks for tracking this down.  I will report up the chain that we at least think we have identified the problem.

Brian

**Comment by herver** [comment]
Hi @abh3 

Unfortunately the line you mention is nowhere to be found in the logs...

(Even when running with `*.trace all`)

**Comment by abh3** [comment]
Hi Herve,

OK, how about the config file so I have a template to work from.

Andy

**Comment by herver** [comment]
I just sent it to your @cern.ch address
