### ISSUE TITLE
XrdPosix: rename does not automatically replaces existing file

### ISSUE THREAD

**Issue by gganis** [xrootd/xrootd#659]
This issue was discussed by email last summer but I realized that I never filled an issue in here.

According to the rename man page:
If newpath already exists, it will be atomically replaced, ...

However, this is not honored by XrdPosix::rename: if the target file exists the call always fails.

In the above-mentioned email exchange the reason for this was tracked back to the difficulty to accomplish a 'true' rename behavior when dealing with non-POSIX file systems.
As a possible 'partial' fix it was proposed to allow a 'true' rename as long as the existing target is neither remote nor symlinked.
Could this be implemented?

Gerri

**Comment by abh3** [comment]
This has been addressed by commit 23adaf.
