### ISSUE TITLE
PSS + PFC delete operation: file gets deleted from origin but not from the cache

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#669]
Hello,

I've noticed that running a delete operation through a proxy with disk caching enabled (PSS + PFC components) goes through and deletes the file from the origin but the local copy is still kept.

Setup:
client --> proxy (with cache) --> origin

Steps to reproduce:
1. write file from client to origin
2. read file from proxy (file gets cached)
3. send delete command to the proxy (file gets deleted on origin)
4. read file from proxy (local copy is served)

Log messages from the proxy:

180314 16:59:21 1277 XrdInet: Accepted connection from 21@xdc-test-fst1.cern.ch
180314 16:59:21 1277 XrdProtocol: matched protocol xrootd
180314 16:59:21 1277 ?:21@xdc-test-fst1 XrdPoll: FD 21 attached to poller 0; num=1
180314 16:59:21 1257 XrdSched: running main accept inq=0
180314 16:59:21 1277 ?:21@xdc-test-fst1 XrootdProtocol: 0000 req=login dlen=96
180314 16:59:21 1277 sec_getParms: xdc-test-fst1.cern.ch sectoken=&P=sss,0.13:/etc/eos.keytab&P=unix
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 XrootdResponse: 0000 sending 50 data bytes; status=0
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 XrootdProtocol: 0000 req=auth dlen=151
sec_PM: Using sss protocol, args='0.13:/etc/eos.keytab'
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 XrootdResponse: 0000 sending OK
180314 16:59:21 1277 XrootdXeq: root.23091:21@xdc-test-fst1 pub IP46 login as daemon
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 XrootdProtocol: 0100 req=rm dlen=26
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 ofs_remove: f fn=/eos/xdc/testing/delete.me
180314 16:59:21 1277 Posix_P2L: unlink /eos/xdc/testing/delete.me pfn2lfn p9
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 XrootdProtocol: 0100 rc=0 rm /eos/xdc/testing/delete.me
180314 16:59:21 1277 root.23091:21@xdc-test-fst1 XrootdResponse: 0100 sending OK

I suppose the expected outcome would be for the file to get deleted from the cache as well.

**Comment by osschar** [comment]
@abh ... how come the unlink request got forwarded to the origin?

XrdOucCaheIO::Unlink() is really just { return 0; } and the function is not reimplemented downstream.

How do we want to handle this then? If unlink at the origin succeeds (or returns something to the effect of ENOENT), we remove it on the cache as well?

**Comment by abh3** [comment]
Well, actually, Unlink should remove the file from the cache. That’s the only way we have to do that.

**Comment by osschar** [comment]
So you already do:
1. call unlink at the origin
2. if 1 succeeds, call unlink at the cache?
Or we want to separate those two things and do cache unlink in any case?

**Comment by abh3** [comment]
No, we first call unlink to the cache because it never hurts to do that first. Then we call unlink on the origin. The Cache Context Manager may decide to call Unlink() only on the cache to force a cache refresh.

**Comment by osschar** [comment]
So you already do:
1. call unlink at the origin
2. if 1 succeeds, call unlink at the cache?
Or we want to separate those two things and do cache unlink in any case?

**Comment by osschar** [comment]
Fixed through #997

**Comment by abh3** [comment]
No, we always unlink the cache first and then the origin.
