### ISSUE TITLE
xrootd server (4.8.0) crashes on EL6 when receiving an HTTPS request

### ISSUE THREAD

**Issue by cvuosalo** [xrootd/xrootd#674]
An HTTPS request like the following:

davix-get https://xrootdredirector.youruniv.edu:1094//store/user/smith/test_file -E /tmp/x509up_u1234 --capath /etc/grid-security/certificates

works with XRootD 4.8.0 on EL7 but will crash the xrootd server on EL6. If the redirector is EL6, its xrootd server crashes. If the redirector is EL7 but the data server it connects to is EL6, the xrootd server on the data server crashes.

The log message for the crash is:

pure virtual method called
terminate called without an active exception

**Comment by bbockelm** [comment]
Hi Carl,

Could you provide a core dump (or a backtrace) for this?

Brian

**Comment by cvuosalo** [comment]
A core file can be found here:
/afs/hep.wisc.edu/user/cvuosalo/public/xrootdCore/core.29178

**Comment by ffurano** [comment]
Hi Carl,
are you loading XrdHttp plugins ?
If yes, I think this may be due to a change in the ABI on the private headers, and likely you will have to recompile the plugins. Please confirm.
Fabrizio

**Comment by cvuosalo** [comment]
Hi Fabrizio,
We are using OSG release 3.3.31. We are following the instructions for enabling HTTS requests here:
https://twiki.cern.ch/twiki/bin/view/Main/XRootDoverHTTP
I don't know what plug-ins are being loaded, nor how to compile plug-ins.

**Comment by abh3** [comment]
This has been fixed.
