### ISSUE TITLE
XrdCl should never return "No more free SDIs" to an application

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#688]
We easily trigger "errc=301, msg=[ERROR] No more free SIDs" in XrdCl e.g. sending a 1M file in 1b chunks. Once the condition appears all other calls living in the same process suffer from this condition by getting errors for any type of call. If this condition is not handled in XrdCl itself I have to write loops around every XrdCl method I use, which is very inconvenient because actually this is a temporary condition ...

**Comment by simonmichal** [comment]
Since the source of the problem has been fixed in f80d8d474177a29b839921713cb93c95863e5698
I'll close this one (as it requires major re-factoring).
