### ISSUE TITLE
XrdHTTP assumes that the path refers to a directory if Depth=1 is specified on a PROPFIND request on a file

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#691]
According to WebDAV spec, PROPFIND should work on any resource. 
With xrootd's http protocol, I observe:
```
    => PROPFIND /some_folder/some_file HTTP/1.1
    => Host: myServer:1094
    => User-Agent: PycURL/7.43.0 libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11 c-ares/1.13.0 libidn2/2.0.4 libssh2/1.7.0 nghttp2/1.31.1 librtmp/2.3
    => Accept: */*
    => Depth: 1
    => Content-Length: 78
    => Content-Type: application/x-www-form-urlencoded
    => 
    => <?xml version="1.0"?><a:propfind xmlns:a="DAV:"><a:prop></a:prop></a:propfind>
    <= HTTP/1.1 404 Not found
    <= Content-Length: 110
    <= 
    <= Unable to open directory /some_folder/some_file; not a directory
```
This actively breaks Grid monitoring code ( https://gitlab.cern.ch/lcgdm/nagios-plugins-webdav ) which performs exactly this check on a created and moved test-file.

**Comment by bbockelm** [comment]
It's not clear from the ticket description -- are you pointing out that it should respond with an XML block that contains in the response a 404 (e.g., the example response here https://tools.ietf.org/html/rfc4918#section-9.1.3)?

Or is 404 not the correct response code even ignoring the WebDAV issue?

**Comment by olifre** [comment]
Sorry for not being clear. 
In any case, an XML block has to be returned to match specification. 

However, for an existing file, this is still wrong in my opinion. `PROPFIND` should then usually return file properties, e.g. last modification time, size, hash etc. 
I would accept a 404 if the file does not exist, but for existing files, I don't see this as being correct.

**Comment by bbockelm** [comment]
Oh - that's surprising then.  I'm getting it an appropriate response for files that exist.

*NOTE* that `XrdHttp` doesn't do a very good job of getting the HTTP status code correct.  I get a 404 if the file exists but the current user is unauthorized to read it.  We may have hit such a case?

**Comment by olifre** [comment]
> Oh - that's surprising then. I'm getting it an appropriate response for files that exist.

That's not the case for me. Look at this:

```
ofreyerm@lxplus016 ~ $ davix-put -P Grid debug.root https://xrootd.physik.uni-bonn.de:1094/cephfs/grid/atlas/user/scratch/freyermu/debug.root
ofreyerm@lxplus016 ~ $ davix-ls -P Grid https://xrootd.physik.uni-bonn.de:1094/cephfs/grid/atlas/user/scratch/freyermu/debug.root
(Davix::HttpRequest) Error: HTTP 404 : File not found
```
Checking the filesystem, the file is indeed present. Also:
```
ofreyerm@lxplus016 ~ $ davix-get -P Grid https://xrootd.physik.uni-bonn.de:1094/cephfs/grid/atlas/user/scratch/freyermu/debug.root > /dev/null
ofreyerm@lxplus016 ~ $
```
So clearly, permission are fine, and the file is there. But `davix-ls` which uses `PROPFIND` gets a 404. That's not really correct.

**Comment by bbockelm** [comment]
Ah-ha, I think that's indeed what is happening here.

Here's a session where I'm appropriately authenticated:
```
> PROPFIND //user/ligo/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: example.unl.edu:1094
> Accept: */*
> 
< HTTP/1.1 207 Multi-Status
< Content-Length: 650
< Content-Type: text/xml; charset="utf-8"
< 
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns1="http://apache.org/dav/props/" xmlns:ns0="DAV:">
<D:response xmlns:lp1="DAV:" xmlns:lp2="http://apache.org/dav/props/" xmlns:lp3="LCGDM:">
<D:href>/user/ligo/</D:href>
<D:propstat>
<D:prop>
<lp1:getcontentlength>4096</lp1:getcontentlength>
<lp1:getlastmodified>Mon, 05 Feb 2018 21:33:42 GMT</lp1:getlastmodified>
<lp1:resourcetype><D:collection/></lp1:resourcetype>
<lp1:iscollection>1</lp1:iscollection>
<lp1:executable>T</lp1:executable>
<lp1:iscollection>1</lp1:iscollection>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>
```

However, if I don't authenticate:
```
> PROPFIND //user/ligo/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: example.unl.edu:1094
> Accept: */*
> 
< HTTP/1.1 404 Not found
< Content-Length: 47
< 
```

From the server log for the second access:
```
180521 16:42:05 18957 unknown.264985:171@example2 XrootdResponse: sending err 3010: Unable to locate /user/ligo/; permission denied
```
So indeed - instead of a 403 unauthorized I get a rather surprising 404.

**Comment by olifre** [comment]
@bbockelm Can you also try on a file, instead of a directory? 
In that case, you'll also get a 404, even if properly authenticated (see my example). 
That's what this bug is about. Of course, 404 in case not authenticated is also bad, but that's a different issue.

**Comment by bbockelm** [comment]
Yup, this seems to work well on a file:
```
> PROPFIND //user/ligo/frames/S6/LDAShoftC02/LHO/H-H1_LDAS_C02_L2-9716/H-H1_LDAS_C02_L2-971622144-128.gwf HTTP/1.1
> User-Agent: curl/7.29.0
> Host: example.unl.edu:1094
> Accept: */*
> 
< HTTP/1.1 207 Multi-Status
< Content-Length: 644
< Content-Type: text/xml; charset="utf-8"
< 
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns1="http://apache.org/dav/props/" xmlns:ns0="DAV:">
<D:response xmlns:lp1="DAV:" xmlns:lp2="http://apache.org/dav/props/" xmlns:lp3="LCGDM:">
<D:href>/user/ligo/frames/S6/LDAShoftC02/LHO/H-H1_LDAS_C02_L2-9716/H-H1_LDAS_C02_L2-971622144-128.gwf</D:href>
<D:propstat>
<D:prop>
<lp1:getcontentlength>16139370</lp1:getcontentlength>
<lp1:getlastmodified>Tue, 31 Jan 2017 04:52:18 GMT</lp1:getlastmodified>
<lp1:iscollection>0</lp1:iscollection>
<lp1:executable>F</lp1:executable>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>
```

`gfal-ls` seems happy with the response, although it's unhappy with the `ctime`:

```
$ gfal-ls -l https://example.unl.edu:1094//user/ligo/frames/S6/LDAShoftC02/LHO/H-H1_LDAS_C02_L2-9716/H-H1_LDAS_C02_L2-971622144-128.gwf                                                                                                                                                                                    
-rwxr-xr-x   0 0     0      16139370 Dec 31  1969 https://example.unl.edu:1094//user/ligo/frames/S6/LDAShoftC02/LHO/H-H1_LDAS_C02_L2-9716/H-H1_LDAS_C02_L2-971622144-128.gwf
```

What are you getting in terms of the server-side log?

**Comment by olifre** [comment]
Checking the RFC:
https://tools.ietf.org/html/rfc4918#appendix-F.1
I find in the changelog that clients must specify the `Depth` header when issuing `PROPFIND`. Checking further in https://tools.ietf.org/html/rfc2518#section-8.1 , servers should assume `infinitiy` if `Depth` is not provided. 
In any case, https://stackoverflow.com/a/31285282 suggests `Depth` should not have any effects on files.

**Comment by abh3** [comment]
Hash.t this been fixed in 4.9.0?

**Comment by olifre** [comment]
> Hash.t this been fixed in 4.9.0?

Trying it now with `Depth: 1` (via `davix-ls`), I get the following back from xrootd 4.9.0:
```
< HTTP/1.1 500 Internal Server Error
< Connection: Close
< Content-Length: 98
<
```
Checking the logs from xrootd, I see:
```
190227 12:48:39 4153613 ofs_opendir: /C=DE/O=.507:30@lxplus110.cern.ch Unable to open directory /cephfs/grid/atlas/atlaslocalgroupdisk/space-usage.json; not a directory
```
So things have indeed changed, but for the worse - we now get 500 instead of 404.

**Comment by olifre** [comment]
For those using xrootd-WebDAV for Grid purposes: EGI has begun using the mentioned Nagios script and we got a GGUS ticket right now (for those who are interested and can access it: https://ggus.eu/index.php?mode=ticket_info&ticket_id=139931 ). 
There are apparently ideas to include that test into the critical profile, which (unless the Nagios check is changed, I asked just now or XRootD behaviour is changed) would lead to XRootD-WebDAV being unusable in EGI for providing Grid storage.

**Comment by ffurano** [comment]
Hi, it took some effort to me to understand this thread, mixing various things.
I would summarize this issue as "XrdHTTP assumes that the path refers to a directory if Depth=1 is specified on a PROPFIND request on a file". Should be not terrible to fix.
I pasted here two examples, showing the issue. (Please do not assume that littlexrdhttp will
work for you in the future, that's my playground)

 Example of a working PROPFIND:
$ davix-http -X PROPFIND -P grid https://littlexrdhttp.cern.ch:1094/1M --trace header
HTTP session to https://littlexrdhttp.cern.ch:1094 begins.
> PROPFIND /1M HTTP/1.1
> User-Agent: libdavix/0.7.1 neon/0.0.29
> Keep-Alive:
> Connection: Keep-Alive
> TE: trailers
> Host: littlexrdhttp.cern.ch:1094
>

< HTTP/1.1 207 Multi-Status
< Connection: Keep-Alive
< Content-Length: 553
< Content-Type: text/xml; charset="utf-8"
<
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns1="http://apache.org/dav/props/" xmlns:ns0="DAV:">
<D:response xmlns:lp1="DAV:" xmlns:lp2="http://apache.org/dav/props/" xmlns:lp3="LCGDM:">
<D:href>/1M</D:href>
<D:propstat>
<D:prop>
<lp1:getcontentlength>1048576</lp1:getcontentlength>
<lp1:getlastmodified>Wed, 04 Oct 2017 14:57:10 GMT</lp1:getlastmodified>
<lp1:iscollection>0</lp1:iscollection>
<lp1:executable>F</lp1:executable>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>



Example of a troubled PROPFIND:
$ davix-http -X PROPFIND -H "Depth: 1" -P grid https://littlexrdhttp.cern.ch:1094/1M --trace header
HTTP session to https://littlexrdhttp.cern.ch:1094 begins.
> PROPFIND /1M HTTP/1.1
> User-Agent: libdavix/0.7.1 neon/0.0.29
> Keep-Alive:
> Connection: Keep-Alive
> TE: trailers
> Host: littlexrdhttp.cern.ch:1094
> Depth: 1
>

< HTTP/1.1 500 Internal Server Error
< Connection: Close
< Content-Length: 46
<
Unable to open directory /1M; not a directory

(Davix::HttpRequest) Error: HTTP 500 : Unexpected server error: 500

**Comment by olifre** [comment]
> XrdHTTP assumes that the path refers to a directory if Depth=1 is specified on a PROPFIND request on a file

Indeed, that's a nice and to-the-point summary! :smile:

**Comment by bbockelm** [comment]
(For posterity - does anyone have the permissions necessary to change the issue title to reflect Fabrizio's findings?  I don't appear to...)

**Comment by ffurano** [comment]
Yup, I directly merged the minifix. Could anyone confirm that this solves it ?

**Comment by abh3** [comment]
Fabrizio should be able to do that. If not, let me know and I will try. Of 
course, it would help to have a suggested new title.

Andy

**Comment by olifre** [comment]
> Could anyone confirm that this solves it ?

Sadly, we still don't have the test setup we wanted to set up, so we only have production endpoints available and especially we don't have build infrastructure available for custom XRootD builds :cry: . 
So I can only promise to test when 4.9.1 comes out, sadly, but if somebody runs an endpoint I can test against, of course I can do that.

**Comment by olifre** [comment]
> Fabrizio should be able to do that. If not, let me know and I will try.

I've adapted the title to Fabrizio's suggestion (I can also edit it since I opened the issue). In case there's a better choice of title, let me know :wink:
