### ISSUE TITLE
SEGV in XrdCryptosslX509SignProxyReq()

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#696]
When envar  XrdSecGSIDELEGPROXY is set to 1 (ask the server to send back a proxy request to be signed;) we get a SEGV:
#0  0x00007f01c74e7381 in XrdCryptosslX509SignProxyReq (xcpi=0x7f01c0053f40, kcpi=
    0x7f01c0052f90, xcri=0x7f01c002a950, xcpo=0x7f01caf6ecc8)
    at /u/sf/abh/xtest/xrootd/src/XrdCrypto/XrdCryptosslgsiAux.cc:1070

because xriext is zero.which indicates that the certificate had no extensions (it was a proxy certificate generated by voms-proxy-init with no request for a voms extension). The full traceback is below.

#0  0x00007f01c74e7381 in XrdCryptosslX509SignProxyReq (xcpi=0x7f01c0053f40,
    kcpi=0x7f01c0052f90, xcri=0x7f01c002a950, xcpo=0x7f01caf6ecc8)
    at /u/sf/abh/xtest/xrootd/src/XrdCrypto/XrdCryptosslgsiAux.cc:1070
#1  0x00007f01c793ff5a in XrdSecProtocolgsi::ClientDoPxyreq (this=0x7f01c0004cb0, br=
    0x7f01c005c410, bm=0x7f01caf6ee68, emsg=...)
    at /u/sf/abh/xtest/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:3200
#2  0x00007f01c793de46 in XrdSecProtocolgsi::ParseClientInput (this=0x7f01c0004cb0,
    br=0x7f01c005c410, bm=0x7f01caf6ee68, cmsg=...)
    at /u/sf/abh/xtest/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:2817
#3  0x00007f01c7934bed in XrdSecProtocolgsi::getCredentials (this=0x7f01c0004cb0,
    parm=0x7f01c005e900, ei=0x7f01caf6f0d0)
    at /u/sf/abh/xtest/xrootd/src/XrdSecgsi/XrdSecProtocolgsi.cc:1379
#4  0x00007f01cd483529 in XrdCl::XRootDTransport::DoAuthentication (this=0x11defd0,
    hsData=0x7f01c00008c0, info=0x11e2b30)
    at /u/sf/abh/xtest/xrootd/src/XrdCl/XrdClXRootDTransport.cc:1707
#5  0x00007f01cd47f817 in XrdCl::XRootDTransport::HandShakeMain (this=0x11defd0,
    handShakeData=0x7f01c00008c0, channelData=...)
    at /u/sf/abh/xtest/xrootd/src/XrdCl/XrdClXRootDTransport.cc:430
#6  0x00007f01cd47f467 in XrdCl::XRootDTransport::HandShake (this=0x11defd0,
    handShakeData=0x7f01c00008c0, channelData=...)
    at /u/sf/abh/xtest/xrootd/src/XrdCl/XrdClXRootDTransport.cc:326
#7  0x00007f01cd4e732d in XrdCl::AsyncSocketHandler::OnReadWhileHandshaking (
    this=0x11e2e60) at /u/sf/abh/xtest/xrootd/src/XrdCl/XrdClAsyncSocketHandler.cc:779
#8  0x00007f01cd4e5762 in XrdCl::AsyncSocketHandler::Event (this=0x11e2e60,
    type=1 '\001') at /u/sf/abh/xtest/xrootd/src/XrdCl/XrdClAsyncSocketHandler.cc:234
#9  0x00007f01cd46a96b in (anonymous namespace)::SocketCallBack::Event (
    this=0x11e3650, chP=0x11e3670, cbArg=0x0, evFlags=1)
    at /u/sf/abh/xtest/xrootd/src/XrdCl/XrdClPollerBuiltIn.cc:82
#10 0x00007f01ccebf4ec in XrdSys::IOEvents::Poller::CbkXeq (this=0x11deec0,
    cP=0x11e3670, events=1, eNum=0, eTxt=0x0)
    at /u/sf/abh/xtest/xrootd/src/XrdSys/XrdSysIOEvents.cc:693
#11 0x00007f01ccec140e in XrdSys::IOEvents::PollE::Dispatch (this=0x11deec0,
    cP=0x11e3670, pollEv=1)
    at /u/sf/abh/xtest/xrootd/src/./XrdSys/XrdSysIOEventsPollE.icc:270
#12 0x00007f01ccec12b9 in XrdSys::IOEvents::PollE::Begin (this=0x11deec0,
    syncsem=0x11dd820, retcode=@0x7fff8f05e330, eTxt=0x7fff8f05e328)
    at /u/sf/abh/xtest/xrootd/src/./XrdSys/XrdSysIOEventsPollE.icc:225
#13 0x00007f01ccebde0c in XrdSys::IOEvents::BootStrap::Start (parg=0x7fff8f05e320)
    at /u/sf/abh/xtest/xrootd/src/XrdSys/XrdSysIOEvents.cc:131
---Type <return> to continue, or q <return> to quit---
#14 0x00007f01ccebaa5e in XrdSysThread_Xeq (myargs=0x11ddcb0)
    at /u/sf/abh/xtest/xrootd/src/XrdSys/XrdSysPthread.cc:86
#15 0x00007f01cc133aa1 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f01cc431bcd in clone () from /lib64/libc.so.6

**Comment by gganis** [comment]
Looking at it

**Comment by gganis** [comment]
Ok, I managed to reproduce it.
Hopefully I will understand this soon.

**Comment by gganis** [comment]
This can be closed.
