### ISSUE TITLE
XrdCl: specify file for extraction from ZIP archive also through opaque info

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#701]

**Comment by mlassnig** [comment]
@simonmichal Hi, sorry to open this again, but I just tried this:

```$ xrdcp -vf "root://lapp-se01.in2p3.fr:1094//dpm/in2p3.fr/home/atlas/atlasdatadisk/rucio/data16_valid/a4/b5/DRAW_RPVLL.14459284._000061.zip.1?xrdcl.unzip=DRAW_RPVLL.11106701._001950.pool.root.1" temp.file```

and it tried to get the whole file, instead of just the file in the zip. This is with xrdcp v4.8.4.

**Comment by abh3** [comment]
What release was the xrdcp? Simply do xrdcp --version

**Comment by mlassnig** [comment]
@abh3 It's v4.8.4

**Comment by simonmichal** [comment]
@mlassnig : could you make the zip file available for me (e.g. copy it to EOS)? I cannot reproduce the problem with my test files?

**Comment by mlassnig** [comment]
I've copied the file to: /eos/atlas/user/m/mlassnig/DRAW_RPVLL.14459284._000061.zip.1

Can you send me a private mail how I can make it available to you? (EOS attr is a mystery to me).
