### ISSUE TITLE
xrdHttp does not support checksumming

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#711]
Attempting Grid transfers, the other end issues a request such as:
```
180523 14:44:58 144824 sysXrdHttp:  rc:111 got hdr line: HEAD /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/mc15_13TeV/0b/59/EVNT.13048527._000001.pool.root.1 HTTP/1.1
180523 14:44:58 144824 sysXrdHttp:  Parsing first line: HEAD /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/mc15_13TeV/0b/59/EVNT.13048527._000001.pool.root.1 HTTP/1.1
180523 14:44:58 144824 sysXrdHttp:  rc:57 got hdr line: User-Agent: fts_url_copy/3.7.8 gfal2/2.15.4 neon/0.0.29
180523 14:44:58 144824 sysXrdHttp:  rc:14 got hdr line: Keep-Alive: 
180523 14:44:58 144824 sysXrdHttp:  rc:24 got hdr line: Connection: Keep-Alive
180523 14:44:58 144824 sysXrdHttp:  rc:14 got hdr line: TE: trailers
180523 14:44:58 144824 sysXrdHttp:  rc:41 got hdr line: Host: xrootd001.physik.uni-bonn.de:1094
180523 14:44:58 144824 sysXrdHttp:  rc:22 got hdr line: Want-Digest: ADLER32
180523 14:44:58 144824 sysXrdHttp:  rc:83 got hdr line: ClientInfo: job-id=6f242aab-f121-5a1c-89b0-1dfb01d96abb;file-id=781292397;retry=0
180523 14:44:58 144824 sysXrdHttp:  rc:2 got hdr line: 
180523 14:44:58 144824 sysXrdHttp:  rc:2 detected header end.
```
However, xrootd only replies with the filesize, as can be seen in https://github.com/xrootd/xrootd/blob/f4860902138e2d791ac4873a28de3117bd79a182/src/XrdHttp/XrdHttpReq.cc#L1434 and from the logs:
```
180523 14:44:58 144824 /DC=ch/D.1966:37@fts119.cern.ch ofs_stat:  fn=/cephfs/grid/atlas/atlaslocalgroupdisk/rucio/mc15_13TeV/0b/59/EVNT.13048527._000001.pool.root.1
180523 14:44:58 144824 /DC=ch/D.1966:37@fts119.cern.ch XrootdProtocol: 0000 rc=0 stat /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/mc15_13TeV/0b/59/EVNT.13048527._000001.pool.root.1
180523 14:44:58 144824 /DC=ch/D.1966:37@fts119.cern.ch XrootdResponse: 0000 sending 42 data bytes
180523 14:44:58 144824 sysXrdHttp:  XrdHttpReq::Data! final=0
```
Checksumming in general is activated in the configuration:
```
xrootd.chksum adler32 crc32 md5
```
Is this a missing feature or am I missing something?

**Comment by ffurano** [comment]
Hi,

 did you use the master branch?
 In theory the checksumming had been contributed by Brian a few weeks ago:
https://github.com/xrootd/xrootd/commit/9501f2a202a97ade5f7769886f1fcea15bf369dd

f

**Comment by olifre** [comment]
@ffurano Nice, that's good to know, thanks for pointing this out!
Sadly, we only have resources for a single production setup right now, so we stay with the last stable release. A dev setup is on our agenda, but we won't get to it in the very near future. 

So maybe the next release will be faster than us ;-).

**Comment by abh3** [comment]
Good point. So, I think this issue is closed because support exists and will likely appear in R 4.9 which will be here within 2 months.
