### ISSUE TITLE
acc.authdb does not support DNs with whitespace

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#712]
DNs often include whitespace, e.g.:
```
= ddmadmhttp o: atlas u: '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management'
```
Authdb does not parse that well, and at least for HTTPS auth, the DN hash is not printed even at highest debug level, making it hard to find the correct SubjectHash.

**Comment by olifre** [comment]
Hi @bbockelm ,

we simply map based on VOMS attributes - which works fine in most cases, but fails for the ddmadmin robot, which (for some protocols, from some FTS machines) does not have deliver VOMS proxy extensions. 
So for that one, we only get the DN.... 

Cheers,
Oliver

**Comment by bbockelm** [comment]
Huh.  That's a bit strange - personally, I'd bounce such a session.  Transfers should have a valid VOMS proxy.

In the case of HTTPS - are you getting VOMS groupings in some cases?  Or is it totally missing for that protocol?

**Comment by olifre** [comment]
> Huh. That's a bit strange - personally, I'd bounce such a session. Transfers should have a valid VOMS proxy.

There's too many, this affects almost all FTS xrootd connections to our site. But since it seems that we are in any case the first site which planned to make use of xrootd TPC, probably nobody else noticed yet (I told DDM, they are aware). 



> In the case of HTTPS - are you getting VOMS groupings in some cases? Or is it totally missing for that protocol?

In most cases, they are present for HTTPS.

**Comment by wyang007** [comment]
I am also using LCMAPs on a few of my machines for Xrootd TPCs. Is there a way to separate out a minimum set of RPMs needed to use xrootd-lcmaps, Note the VOMS based mapping is also need.

one way to hide the complexity of all these RPMs is to build a container and provide it as an appliance. The dilemma is that Kebernetes only work with Docker. Singularity is nicer but doesn’t work with Kebernetes.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338 (O)

**Comment by bbockelm** [comment]
It might be worthwhile to run down one such example of a VOMS-less proxy in order to figure out what's generating the incorrect proxies.  Unless there's a particular urgency, I think this probably indicates there's a use case I don't understand or a bug...

**Comment by abh3** [comment]
I see this really hasn't progressed. No matter, would providing a way of specifying a "space character" which, when it appears in an "id", is replaced by a space be an acceptable solution for your problem here?

**Comment by olifre** [comment]
Many thanks for coming back to this! Yes, that would be an acceptable solution indeed.

**Comment by bbockelm** [comment]
@olifre - coming back to this.

I was able to reverse-engineer the hash algorithm that OpenSSL uses (and hence Xrootd uses).  The code is here:

https://github.com/opensciencegrid/topology/blob/0a0cb488ba1ea8c4c28807faefd5dde3e4e008da/src/stashcache.py#L44-L81

With this, you can translate a DN to an equivalent hash and generate the appropriate Authfile.

It's pretty gross code -- gives you a feel for how fragile DNs are (and why they were a bad idea originally!).

**Comment by bbockelm** [comment]
Happy to help!  It took me quite awhile to reverse engineer (and brush up on DER encoding of ASN1...), so I wanted to make sure someone else would benefit.
