### ISSUE TITLE
XrdHttp should have appropriate HTTP status code for permission denied

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#713]
In #691, @olifre noted the `XrdHttp` plugin always returns a 404 (File Not Found) in the case of an error.

This is particularly confusing when there's a permission denied, as that would more naturally map to a "403 Unauthorized User".

Let's implement the translation between permission denied and 403 status code.

(There are, of course, many other translations we could make... let's start with something concrete and move forward).

**Comment by abh3** [comment]
Didn't this get fixed on some recent pull request?

**Comment by ffurano** [comment]
Hi Andy,

 I think so, but did not have time to verify... sorry. I'll verify today :-)

f


Il 21/08/18 06:43, Andrew Hanushevsky ha scritto:

**Comment by ffurano** [comment]
Hi Andy,

 yes AFAIK :-)

f

**Comment by abh3** [comment]
OK, so I am closing this as solved.

**Comment by ffurano** [comment]
yup
