### ISSUE TITLE
specs: ClientProtocolRequest binary layout not implemented as specs

### ISSUE THREAD

**Issue by sbinet** [xrootd/xrootd#717]
this was uncovered in https://github.com/go-hep/hep/pull/195 (thanks @EgorMatirov for the detective work!).

it seems the [specs](http://xrootd.org/doc/dev45/XRdv310.pdf) for `ClientProtocolRequest` say (p71):
```
Request
kXR_char streamid[2]
kXR_unt16 kXR_protocol
kXR_int32 clientpv
kXR_char reserved[11]
kXR_char options
kXR_int32 0
```

while [XProtocol/XProtocol.hh@d96a61a](https://github.com/xrootd/xrootd/blob/d96a61a07947e75e69cd2eed8c3cbcc86ee0e52c/src/XProtocol/XProtocol.hh#L480): 
```c++
struct ClientProtocolRequest {
   kXR_char  streamid[2];
   kXR_unt16 requestid;
   kXR_int32 clientpv;      // 2.9.7 or higher
   kXR_char  flags;         // 3.1.0 or higher
   kXR_char  reserved[11];
   kXR_int32 dlen;
};
```

_ie:_ the order of `reserved[11]` and `options` from the specs are reversed in the implementation.

I guess updating the `specs` is easier :)

**Comment by abh3** [comment]
Thanks for the heads up. This has been corrected.

Andy
