### ISSUE TITLE
kXR_open: cpsize and cptype are not specified when kXR_retstat is not specified and file is not compressed.

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#721]
The [specs](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248823) for `kXR_open` say:
>cpsize   is the compression page size. The cpsize field is returned when the kXR_compress or kXR_retstat have been specified. Subsequent reads must be equal to this value and read offsets must be an integral multiple of this value. If cpsize is zero, the file is not compressed and subsequent reads may use any offset and read length.
>cptype  is the compression algorithm used to compress the file. The cptype field is returned when the kXR_compress or kXR_retstat have been specified. If the file is not compressed, the first byte of the four byte field is a null byte (\0).

However, if I specify only `kXR_compress` without `kXR_retstat`, then `cpsize` and `cptype` are not specified when the file is not compressed.

Expected response  (`streamid` = 2, `resplen` = 12, `fhandle` = 0, `cpsize` and `cptype` are specified and equals to 0 and '\0'):
```
0002 0000 0000 000C 0000 0000 0000 0000 0000 0000
```

Actual response (`streamid` = 2, `resplen` = 4, `fhandle` = 0, `cpsize` and `cptype` are not specified):
```
0002 0000 0000 0004 0000 0000
```

**Comment by abh3** [comment]
Hi Mikhail,

You are correct. This is a bug. Fortunately, no one uses compressed files so it’s not critical. However, it will be corrected for the next release.

Andy

From: Mikhail Ivchenko 
Sent: Saturday, June 02, 2018 8:22 AM
To: xrootd/xrootd 
Cc: Subscribed 
Subject: [xrootd/xrootd] kXR_open: cpsize and cptype are not specified when kXR_retstat is not specified and file is not compressed. (#721)

The specs for kXR_open say:

  cpsize is the compression page size. The cpsize field is returned when the kXR_compress or kXR_retstat have been specified. Subsequent reads must be equal to this value and read offsets must be an integral multiple of this value. If cpsize is zero, the file is not compressed and subsequent reads may use any offset and read length.
  cptype is the compression algorithm used to compress the file. The cptype field is returned when the kXR_compress or kXR_retstat have been specified. If the file is not compressed, the first byte of the four byte field is a null byte (\0).

However, if I specify only kXR_compress without kXR_retstat, then cpsize and cptype are not specified when the file is not compressed.

Expected response (streamid = 2, resplen = 12, fhandle = 0, cpsize and cptype are specified and equals to 0 and '\0'):

0002 0000 0000 000C 0000 0000 0000 0000 0000 0000
Actual response (streamid = 2, resplen = 4, fhandle = 0, cpsize and cptype are not specified):

0002 0000 0000 0004 0000 0000
