### ISSUE TITLE
xrootdfs writing to EOS "fails" due to redirection count 1

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#723]
Dear xrootdfs experts,

I observe the following when mounting EOS via xrootdfs when having a corresponding Kerberos ticket:
```
$ setupATLAS
$ lsetup xrootd
$ mkdir mnt
$ xrootdfs mnt -o rdr=xroot://eosuser.cern.ch//eos/user/o/ofreyerm
$ cd mnt
$ touch testfile
touch: cannot touch `testfile': No such file or directory
```
Quickly checking with "ls -la", I see:
```
-rw-rw-rw-. 1 ofreyerm zp 0 May 29 18:03 someotherfile
??????????? ? ? ? ? ? testfile
```
Waiting a bit, and trying "ls -la" again:
```
-rw-rw-rw-. 1 ofreyerm zp 0 May 29 18:03 someotherfile
-rw-rw-rw-. 1 ofreyerm zp 0 Jun 2 20:09 testfile
```
It seems it takes some time until the file attributes and owner are set. 

I opened an incident with EOS support and was told after some investigations that this is due to redirection count being limited to 1 with xrootdfs. @apeters1971 can add more details on the necessary changes to have xrootdfs work fine with EOS again.

**Comment by apeters1971** [comment]
I fixed that in the EOS dev branch. Will take some time to get this on EOSUSER.

commit 32d4725e145073e663dbdad00142997e2513936c
Author: Andreas Joachim Peters <andreas.joachim.peters@cern.ch>
Date:   Wed Jun 6 13:08:46 2018 +0200

    MGM: discover 'xrootdfs' application name and treat as a regular EOS FUSE client

**Comment by olifre** [comment]
> I fixed that in the EOS dev branch. Will take some time to get this on EOSUSER.

Many thanks for keeping at it and implementing a fix so quickly, @apeters1971 ! Then I'll already close the issue here as issue reporter :-). 
I'll test again in a few weeks and let our user who complained at our site know that a fix is implemented and is going to be rolled out in the not-too-far future.

**Comment by abh3** [comment]
Hi Andreas,

That would seem to be more likely to go into the environment that the sec 
entity object as it has nothing to do with security. I don't know how fuse 
would pass along the aplication name but we do know it from a regular 
client login. I also dislike special casing dedicated fields and gthere is 
no end in sight here. That's why I prefer puting it in open-ended 
environment table under something like xrd.ClientAppName.

Andy

**Comment by wyang007** [comment]
I don't think xrootdfs intentionally set the application flag somewhere. Maybe it inherited the flag from somewhere else.

**Comment by apeters1971** [comment]
Ap[pName is set here in the client:
````
//--------------------------------------------------------------------------
    // Monitoring settings
    //--------------------------------------------------------------------------
    char *tmp = strdup( XrdSysUtils::ExecName() );
    char *appName = basename( tmp );
    PutString( "AppName", appName );
    free( tmp );
    ImportString( "AppName", "XRD_APPNAME" );
    PutString( "MonInfo", "" );
    ImportString( "MonInfo", "XRD_MONINFO" );
````
The sec entity object is only one accesible at the moment in the Ofs layer, that's why it would be beneficial to have it there. 

Indeed the moninfo is also in the sec entity object and probably has nothing to do with security.
So if moninfo is filled by default, that would be enough for me.

**Comment by xrootd-dev** [comment]
Well, that's not true. We can always add stuff to the opaque information 
that is sent to the OFS layer. Normally, the OFS layer feeds that into the 
XrdOuc Env object that establishes the environment. If you really want it 
in the entity object then it would be handled (in R5) as a CGI string so 
we don't have to revisit this again.

Andy

**Comment by apeters1971** [comment]
Yes, sure. That is also fine. I just need the application name in whatever way is simplest/best in the Ofs layer.

**Comment by olifre** [comment]
> I fixed that in the EOS dev branch. Will take some time to get this on EOSUSER.

Dear @apeters1971 ,
I checked just now after giving things some time to go through to EOSUSER, and the issue still persists - is your patch still in the queue and not propagated to EOSUSER yet?

**Comment by apeters1971** [comment]
I have no easy access to the application name in the OFS layer. It is in sec.monifo, but it can be overwritten when you use GSI authentication. If you need to write to EOSHOME, I can disable the atomic upload flag in your home directory. Maybe it would be worthwhile to have all this client specific information exposed in a simple way in XROOTD5 e.g. in a key value map with key namespaces. Once I can see the application in the sec entity struct, it is trivial to adjust it on the EOS side.

**Comment by xrootd-dev** [comment]
We can do that on R5 as it includes a key-value map in the sec entity 
structure. I assume all you want is the login CGI placed in there.

**Comment by olifre** [comment]
@apeters1971 For me personally, this is not a pressing issue, it's rather of use for several users at our site who would love to easily access EOS via xrootdfs from their desktop machines or laptops without installing an additional EOS client. 
So I am certainly in favour of the long-term solution possible with XROOTD5 :wink: .

**Comment by olifre** [comment]
Hi @apeters1971 and others,

now that XRootD 5.0.0 is out, is there a possibility to access the application name and disable the atomic upload flag?

**Comment by apeters1971** [comment]
Yes, it is was in XrootdXeq.cc :

if (AppName) Client->eaAPI->Add("xrd.appname", (std::string)AppName);

However it will take some time before we will run EOS with XRootd5 in production.

**Comment by olifre** [comment]
> However it will take some time before we will run EOS with XRootd5 in production.

Thanks! That's all I'm asking for, as long as this is still on the todo list, it is fine with me (and I can tell our users who want to FUSE mount EOS on distros for which there is no EOS client that they will get it one day via XRootD) :-).

**Comment by apeters1971** [comment]
Side remark: people can use sshfs from nearly all platforms via lxplus. Works quite well!

**Comment by olifre** [comment]
Point taken indeed, thanks!
While sshfs has its issues with some software (see e.g. https://sft.its.cern.ch/jira/browse/ROOT-7637 ), I've also recommended that often (but some users claimed they have unstable connectivity to lxplus from their home networks — I never could reproduce that).
