### ISSUE TITLE
kXR_close doesn't fail when wrong fsize is passed

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#727]
During working on https://github.com/go-hep/hep/pull/222 I found that [specs](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248813) states that
>fsize     the size, in bytes, that the file is to have. The close operation fails and the file is erased if it is not of the indicated size. An fsize of zero suppresses the check.

I have tried the following scenario:
1) Open a new file.
2) Close it immediately with `fsize` equal to `47`.

Following the spec expected behavior is `the close operation fails`, however, I'm getting an `ok` response.

Is this expected behavior? Am I doing something wrong?

Thanks!

**Comment by abh3** [comment]
Hi Mikhail,

NO you are not dreaming. That feature was never implemented.

Andy

**Comment by sbinet** [comment]
great! one less thing to implement from our side :)
(assuming this will be removed from the specs?)

**Comment by abh3** [comment]
Good question. It seems sort of useless given that people would rather use 
checksums to make sure the file is correct. So, I'm leaning toward 
removing it.

Andy

**Comment by abh3** [comment]
I have removed the field from the kXR_close request description in v4 of the protocol documentation.
