### ISSUE TITLE
specs: kXR_stat lacks info that path is required when kXR_vfs is present

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#728]
From [specs for the kXR_stat](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248850) it's unclear that `path` is required when `kXR_vfs` is present (in other words, `kXR_vfs` doesn't work with `fhandle`).

I'm getting in https://github.com/go-hep/hep/pull/221 `error 3001: Required argument not present` if I try to make a `kXR_stat` request with `kXR_vfs` passing only `fhandle`.

Can you please make it more clear if that's expected behavior? 

Thanks!

**Comment by abh3** [comment]
I have removed the ambiguities from the kXR_stat request description in v4 of the protocol documentation.
