### ISSUE TITLE
RFE: TPC should support the case of a destination xrootd running on top of external storage (Ceph)

### ISSUE THREAD

**Issue by glpatcern** [xrootd/xrootd#729]
As discussed with @simonmichal, we have the case of xrootd servers that run as gateways in front of a Ceph storage (but for the context of this issue, this can be any external non-local storage).

The current TPC runs in such a way that the destination pulling the file, for efficiency reasons, uses a stripped-down URL for the destination, which does not include the server (`root://localhost...`) and instead only includes the file path. This makes such a case of xrootd gateways break as the file path cannot be interpreted as a local path.

A possible solution is to have the destination server choose (e.g. by a configuration option) whether to use a local path or a full root URL: that would allow forcing the traffic to go through the xrootd local server, which already knows how to forward it to the external storage.

**Comment by wyang007** [comment]
I don’t know if I correctly understand you. In my case, I use a script for TPC copying, and I do this in the script


xrdcp --server -f $src root://$XRDXROOTD_PROXY/$dst

Here XRDXROOTD_PROXY is actually the hostname pointed by the pss.origin (which I guess is the CEPH storage in your case). Does this address your problem? The name XRDXROOTD_PROXY is misleading. I though Andy was going to it a new name…

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338 (O)

**Comment by glpatcern** [comment]
Hi Wei,

Thanks for the feedback, indeed this approach ought to work (and I could have thought about it given the other discussions around TPC...).

I've deployed a script with `root://localhost:1095/$2` as second parameter and I'll see how it goes. I will likely close this issue on Monday, once I deploy that everywhere.

**Comment by glpatcern** [comment]
I confirm the workaround works, so I close the issue.
Nevertheless, I must say that having a built-in possibility to force the full URL would still be a plus.
