### ISSUE TITLE
[Server] support SFS_STARTED for close and opaque query

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#733]

**Comment by abh3** [comment]
I already have a working prototype for close (I think we already support it for opaque queries). It isn't the easiest to do as close is a complicated path that passively interacts with open().. Anyway, in the close() async response you can only do one final response: kXR_ok or kXR_error; that should be good enough. While the file is being closed a) he file remains locked in whatever mode it was locked in, and b) it's file handle is not reassigned. Once the final response is sent, the lock is dropped and the handle is available for reassignment. Any attempt to issue any operation against a file being closed will return a "file not open" error. I should have this committed in a week or so after some more testing.

**Comment by abh3** [comment]
Fixed by commit  db20cdea633b4f50bd8eda9be1af90e52c389313
