### ISSUE TITLE
[XrdCl] Add an API to close connection.

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#734]

**Comment by abh3** [comment]
I already have a working prototype for close (I think we already support it for opaque queries). It isn't the easiest to do as close is a complicated path that passively interacts with open().. Anyway, in the close() async response you can only do one final response: kXR_ok or kXR_error; that should be good enough. While the file is being closed a) he file remains locked in whatever mode it was locked in, and b) it's file handle is not reassigned. Once the final response is sent, the lock is dropped and the handle is available for reassignment. Any attempt to issue any operation against a file being closed will return a "file not open" error. I should have this committed in a week or so after some more testing.

**Comment by simonmichal** [comment]
I think this comment should go to #733  ;-) except for that it does sound reasonable :-)

Regarding opaque queries I recall we checked together and you don't set the callback hence it does not support STARTED.

**Comment by bbockelm** [comment]
:) Just for historical reference, can you provide some simple motivation as to what you'll be using this for?

Thanks!

**Comment by simonmichal** [comment]
Hi Brian,

It has been request by EOS, they have the following use case: if an eos fuse user destroys their credential (e.g. kerberos) and provides a new one with different identity then they want to be able to force disconnect so the user logs in with new credential ;-)

Cheers,
Michal

**Comment by bbockelm** [comment]
Great, thanks!
