### ISSUE TITLE
specs: wrong options info for the kXR_mkdir request

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#736]
[Spec](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248823) states that `kXR_mkpath` is used as an option.
This doesn't make much sense because:
1) it equals to 256;
2) options field is unsigned char in `kXR_mkdir` request;
3) `unsigned char(256)` equals to 0.

From the [protocol header](https://github.com/xrootd/xrootd/blob/master/src/XProtocol/XProtocol.hh#L161) I can guess that `kXR_mkdirpath` is used instead.

Could you please update the specs? :)

**Comment by abh3** [comment]
I have corrected the flag name used in the kkXR_mkdir request description in v4 of the protocol documentation.
