### ISSUE TITLE
kXR_verifyw request is not supported

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#738]
The `kXR_verifyw` request is described in the [protocol spec](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248856), however I'm getting `error 3006: Invalid request code`.

I wasn't able to find any issue regarding that, so I'm adding this one to receive info \ track implementation progress.

**Comment by abh3** [comment]
Hi Mikhail,

That request code was never implement and serves only as a placeholder. O 
doubt t will ever be implemented by anyone but you neve know. There are 
several such codes with "not implemented" status.

Andt

**Comment by abh3** [comment]
I have noted that kXR_verifyw request is a future placeholder in v4 of the protocol documentation.
