### ISSUE TITLE
specs: kXR_dirlist doesn't follow specs for empty dirs

### ISSUE THREAD

**Issue by sbinet** [xrootd/xrootd#739]
According to the specs of `kXR_dirlist`:
- http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248815

the normal response to a `kXR_dirlist` command (with `kXR_dstat`) is:
```
Normal Response w/ kXR_dstat
   kXR_char  streamid[2]
   kXR_unt16 0
   kXR_int32 dlen
   kXR_char  “.\n”
   kXR_char  “0 0 0 0\n”
   kXR_char  dirname\n
   kXR_char  statinfo\n
     •
     •
     •
   kXR_char  0
```

also, it says:
> 6) An empty directory will return the eight-byte triplet `{streamid, 0, 0}`.

I'd assume the note `6)` was written when `kXR_dirlist` is issued w/o `kXR_dstat`, because when issueing it w/ `kXR_dstat` I get a `dlen != 0` and the following trailing bytes:
```
.\n0 0 0 0\x00
```
whereas, at the very least (for consistency's sake), we should get:
```
.\n0 0 0 0\n\x00
```

**Comment by abh3** [comment]
I have removed the ambiguities from the kXR_dirlist request description in v4 of the protocol documentation.

**Comment by abh3** [comment]
Hi Sebastien,

Yes, I typo – didn’t catch it because it was still a correct word 

Andy
