### ISSUE TITLE
selfhttps2http does not allow auth based on roles

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#745]
Using:
```
http.selfhttps2http yes
``` 
and authenticating with VOMS extensions, e.g.:
```
VOMS data - user: '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management'
VOMS data - vorg: 'atlas'
VOMS data - fqan[0]:/atlas/Role=production/Capability=NULL
VOMS data - fqan[1]:/atlas/Role=NULL/Capability=NULL
VOMS data - fqan[2]:/atlas/lcg1/Role=NULL/Capability=NULL
VOMS data - fqan[3]:/atlas/usatlas/Role=NULL/Capability=NULL
```
The redirection URL may be something like:
```
somepath?xrdhttptk=sometoken&xrdhttptime=1529048080&xrdhttpname=thelongdn&xrdhttpvorg=atlas&xrdhttphost=somehost&xrdhttpdn=thelongdn
```
i.e. it will only contain name, DN and vorg, but none of the roles. Hence, authentication based on roles does not work, and one has to use https also for data traffic.

**Comment by bbockelm** [comment]
`http.selfhttps2http` has always been an extremely worrying option to me.  Are you really sure you want to use it?

CloudFlare did some impressive benchmarking of modern encryption overhead: https://blog.cloudflare.com/how-expensive-is-crypto-anyway/, benchmarking modern algorithms at 30Gbps per core.

**Comment by bbockelm** [comment]
Note - some simple benchmarking on my dev VM indicates that `curl` can get over 5Gbps fairly easily...

**Comment by olifre** [comment]
@bbockelm  Interesting links! 
The documentation of xrootd made me think this option would be sufficiently safe and favourable. Also, I was more thinking about "the other end", e.g. FTS streaming data to hundreds of sites in parallel with a many-Gbps link. On our end, we actually have 6 dataservers with 16 real cores, so we won't be saturated. The peak CPU load I saw from an xrootd with 1 GBit/s connectivity was about 35-40% (on a single core), of which most was probably not SSL. 

So I agree, it might not be needed (at least not at an almost receive-only end), but the documentation talks rather optimistic about this flag (too ptimistic maybe?), and the missing auth by role is still a bug. 
But we'll likely stay with https now anyways unless somebody starts to complain about high load ;-).

**Comment by bbockelm** [comment]
Yeah - I don't know much about the internals here, but I don't see have a bearer-token-based security infrastructure can work safely without encryption.

For FTS streaming data -- well, for the most part it doesn't actually stream data.  It only does this as a fallback if TPC fails.  Might be more worthwhile to try and get TPC working (I think you have an email from me on this exact topic)...

**Comment by xrootd-dev** [comment]
Ah, but it should work fine with authentication if the bearer’s identity is included in the token. I thinks this is similar to what ALICE does.

Andy

**Comment by ffurano** [comment]
In theory the roles can be added to the token, however I would consider not using this option at the redirector. You may want to do the full https/voms authorization at the redirector, and use this option only at the data servers, of course you shall do this only if you don't need data encryption.

About the performance, I can't comment on the use cases cited by Brian, basically involving big streams. I can comment on mine, involving 10-20KHz of transactions of a few bytes, and there used to be a big difference, so for the DPM cluster control protocol this option is giving benefits.

**Comment by bbockelm** [comment]
For the DPM use case - are you reusing the same TCP connections?

**Comment by abh3** [comment]
@bbockelm Actually, TLS does have some drawbacks that aren't revealed in the papers (so I'm not quite sure what they were actually measuring but I am quite sure they are the only ones who could repeat those measurements :-) Anyway, if you use TLS you can't use sendfile() nor can you use io vectors (i.e. readv() and writev()). Depending on your workload, the lack of those can increase CPU usage a significant amount. So, I think it's a bit misleading to simply say TLS is cheap.  More accurately, TLS may be cheap depending on what you're doing.

In any case, I think Fabrizio should fix the url tokens anyway. Though, I agree with you, this is a security headache.

**Comment by ffurano** [comment]
Hi,

 I totally agree with Andy, and remark that https has a measurably lower performance than http. The only case
I know where the difference is small is the transfer of a big file, but can't comment for high parallelism
or about CPU limits.
 For example, here is a snippet of the DPM nightly tests performing a stat storm towards
the trunk testbed. HTTP scores 10.3KHz, while HTTPS scores 9.4KHz. The server is Apache with
persistent connections, hence there are very few handshakes/connections.
I expect a much bigger difference in the case of a larger population of random clients
from different machines, as this case is pretty artificial, however it shows a measurable
difference even in an easy case.

    .    http :: stat (0 sec)
    ..   http :: stat (0 sec)                                                                                    [local]
    ...  http :: stat (10 sec)                                                                          [local] Finished
    PASS http :: stat (init: 0.10 sec, main: 4.84 sec)
         Agent: jenkins-perf-tester01.cern.ch
             Command: /usr/bin/hammer-http --url http://dpmhead-trunk.cern.ch//dpm/cern.ch/home/dteam/nightly-50k-heavy-
             read/ --nthreads 40 --cert /tmp/x509up_u0 --key /tmp/x509up_u0 --operation stat --firstfile 0 --lastfile
             50000 --initialization true --max-in-flight 1000
             Assigned files [0-50000) and 40 threads
             Rate: 10333.64 Hz
             Latency span: from 0.00 to 0.04 sec
         Rate: 10333.64 Hz
         Latency span: from 0.00 to 0.04 sec

    .    https :: stat (0 sec)
    ..   https :: stat (0 sec)                                                                                   [local]
    ...  https :: stat (10 sec)                                                                         [local] Finished
    PASS https :: stat (init: 0.14 sec, main: 5.30 sec)
         Agent: jenkins-perf-tester01.cern.ch
             Command: /usr/bin/hammer-http --url https://dpmhead-trunk.cern.ch//dpm/cern.ch/home/dteam/nightly-50k-
             heavy-read/ --nthreads 40 --cert /tmp/x509up_u0 --key /tmp/x509up_u0 --operation stat --firstfile 0
             --lastfile 50000 --initialization true --max-in-flight 1000
             Assigned files [0-50000) and 40 threads
             Rate: 9438.29 Hz
             Latency span: from 0.00 to 0.68 sec
         Rate: 9438.29 Hz
         Latency span: from 0.00 to 0.68 sec

Cheers
f

**Comment by ffurano** [comment]
Hi,
PR #801 fixes this shortcoming
