### ISSUE TITLE
[SSI] SIGABRT when XrdSsiProvider::Init() returns false

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#751]
bool XrdSsiProvider::Init() returns `true` on successful initialisation and `false` if initialisation failed.

If Init() returns `false`, XRootD generates a SIGABRT and dumps core:
```
Plugin loaded unreleased ssi v4.8.2-rc2 from fslib libXrdSsi-4.so
++++++ ssi phase 1 initialization started.
=====> ssi.svclib libXrdSsiCta.so 
------ ssi phase 1 initialization completed.
++++++ ssi phase 2 initialization started.
Config Configuring standalone server.
180621 11:25:01 16498 ssi_XrdSsiCtaServiceProvider: pid:16498 tid:140388032784512 XrdSsiCtaServiceProvider() constructor
180621 11:25:01 16498 ssi_XrdSsiCtaServiceProvider: pid:16498 tid:140388032784512 Called Init(/etc/cta/cta-frontend-xrootd.conf,)
180621 11:25:01 16498 ssi_Config: Provider initialization failed.
------ ssi phase 2 initialization failed.
./start_cta: line 8: 16498 Aborted                 (core dumped) XRD_DEBUG=1 xrootd -n cta -c /etc/cta/cta-frontend-xrootd.conf -I v4 ${OPTIONS}
```
Instead, XRootD should shut down gracefully.

**Comment by slithy** [comment]
Hi Andy, could this please be fixed?

**Comment by abh3** [comment]
I certainly will look into it but it's buried deep inside a long call stack so it may be impossible, but let me see.  Do you simply want a clean exit -- not an abort?

**Comment by abh3** [comment]
OK, this has been fixed but is only available in R5 or later as it relies 
on the enhanced calling conventions in R5 which were done to avoid such 
issues in the future.

**Comment by slithy** [comment]
Thanks, Andy. Great to know the fix is in the pipeline.

**Comment by abh3** [comment]
This has been fixed.
