### ISSUE TITLE
Crash in XrdHttpReq::ProcessHTTPReq

### ISSUE THREAD

**Issue by osschar** [xrootd/xrootd#753]
I got this on UCSD StashCache instance with xrootd-4.8.3-1.osg34.el6.x86_64:
`
Core was generated by `/usr/bin/xrootd -l /var/log/xrootd/xrootd.log -c /etc/xrootd/stashcache-server.'.
Program terminated with signal 11, Segmentation fault.
#0  XrdOucHash<XrdHttpProtocol::StaticPreloadInfo>::Find (this=0x0,
    KeyVal=0x7fb5a40071d0 "/static/help/content/admin/whats_new.htm", KeyTime=0x0)
    at /usr/src/debug/xrootd-4.8.3/src/XrdOuc/XrdOucHash.icc:173
173        if ((hip = hashtable[kent]))
Missing separate debuginfos, use: debuginfo-install keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 openssl-1.0.1e-57.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  XrdOucHash<XrdHttpProtocol::StaticPreloadInfo>::Find (this=0x0,
    KeyVal=0x7fb5a40071d0 "/static/help/content/admin/whats_new.htm", KeyTime=0x0)
    at /usr/src/debug/xrootd-4.8.3/src/XrdOuc/XrdOucHash.icc:173
#1  0x00007fb5b61c6c34 in XrdHttpReq::ProcessHTTPReq (this=0x7fb5a4003ee0)
    at /usr/src/debug/xrootd-4.8.3/src/XrdHttp/XrdHttpReq.cc:892
#2  0x00007fb5b61c0371 in XrdHttpProtocol::Process (this=0x7fb5a4003dc0, lp=<value optimized out>)
    at /usr/src/debug/xrootd-4.8.3/src/XrdHttp/XrdHttpProtocol.cc:951
#3  0x00007fb5b74dbf80 in XrdXrootdTransit::Process (this=0x7fb56c005c00, lp=0x7fb56c002c28)
    at /usr/src/debug/xrootd-4.8.3/src/XrdXrootd/XrdXrootdTransit.cc:365
#4  0x00007fb5b7261c49 in XrdLink::DoIt (this=0x7fb56c002c28) at /usr/src/debug/xrootd-4.8.3/src/Xrd/XrdLink.cc:435
#5  0x00007fb5b7264ddb in XrdScheduler::Run (this=0x610758) at /usr/src/debug/xrootd-4.8.3/src/Xrd/XrdScheduler.cc:357
#6  0x00007fb5b7264f29 in XrdStartWorking (carg=<value optimized out>)
    at /usr/src/debug/xrootd-4.8.3/src/Xrd/XrdScheduler.cc:87
#7  0x00007fb5b7220a6f in XrdSysThread_Xeq (myargs=0x7fb5a4000b60)
    at /usr/src/debug/xrootd-4.8.3/src/XrdSys/XrdSysPthread.cc:86
#8  0x00000030e7607aa1 in start_thread (arg=0x7fb5b43d5700) at pthread_create.c:301
#9  0x00000030e6ee8bcd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115
`

Apparently this happens during Qualys scan of the machine. These are the lines from the log prior to crash:
`
180622` 20:10:47 2160139 XrootdXeq: unknown.7371:38@[::ffff:64.39.99.187] disc 0:00:05 (send failure)
180622 20:10:48 2316273 XrootdBridge: unknown.7377:36@[::ffff:64.39.99.187] login as nobody
180622 20:10:48 2316273 ofs_stat: unknown.7377:36@[::ffff:64.39.99.187] Unable to locate /wp-login.php; no such file or directory
180622 20:10:48 2316273 unknown.7377:36@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to locate /wp-login.php; no such file or directory
180622 20:10:48 2316273 ofs_open: unknown.7377:36@[::ffff:64.39.99.187] Unable to open /wp-login.php; no such file or directory
180622 20:10:48 2316273 unknown.7377:36@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to open /wp-login.php; no such file or directory
180622 20:10:48 2316273 XrootdXeq: unknown.7377:36@[::ffff:64.39.99.187] disc 0:00:00 (send failure)
180622 20:10:48 1469156 XrootdBridge: unknown.7378:38@[::ffff:64.39.99.187] login as nobody
180622 20:10:48 2316274 ofs_stat: unknown.7373:25@[::ffff:64.39.99.187] Unable to locate /login.action; no such file or directory
180622 20:10:48 2316284 ofs_stat: unknown.7372:37@[::ffff:64.39.99.187] Unable to locate /uddiexplorer/SearchPublicRegistries.jsp; no such file or directory
180622 20:10:48 2316274 unknown.7373:25@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to locate /login.action; no such file or directory
180622 20:10:48 2316284 unknown.7372:37@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to locate /uddiexplorer/SearchPublicRegistries.jsp; no such file or directory
180622 20:10:48 2316274 ofs_open: unknown.7373:25@[::ffff:64.39.99.187] Unable to open /login.action; no such file or directory
180622 20:10:48 2316274 unknown.7373:25@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to open /login.action; no such file or directory
180622 20:10:48 2316284 ofs_open: unknown.7372:37@[::ffff:64.39.99.187] Unable to open /uddiexplorer/SearchPublicRegistries.jsp; no such file or directory
180622 20:10:48 2316284 unknown.7372:37@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to open /uddiexplorer/SearchPublicRegistries.jsp; no such file or directory
180622 20:10:48 2316274 XrootdXeq: unknown.7373:25@[::ffff:64.39.99.187] disc 0:00:05 (send failure)
180622 20:10:48 2316284 XrootdXeq: unknown.7372:37@[::ffff:64.39.99.187] disc 0:00:05 (send failure)
180622 20:10:49 1470733 XrootdBridge: unknown.7379:25@[::ffff:64.39.99.187] login as nobody
180622 20:10:49 2164851 XrootdBridge: unknown.7380:36@[::ffff:64.39.99.187] login as nobody
180622 20:10:49 2164851 ofs_stat: unknown.7380:36@[::ffff:64.39.99.187] Unable to locate /index.htm; no such file or directory
180622 20:10:49 2164851 unknown.7380:36@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to locate /index.htm; no such file or directory
180622 20:10:49 2164851 ofs_open: unknown.7380:36@[::ffff:64.39.99.187] Unable to open /index.htm; no such file or directory
180622 20:10:49 2164851 unknown.7380:36@[::ffff:64.39.99.187] XrootdResponse: sending err 3011: Unable to open /index.htm; no such file or directory
180622 20:10:49 2164851 XrootdXeq: unknown.7380:36@[::ffff:64.39.99.187] disc 0:00:00 (send failure)
180622 20:10:49 1469157 XrootdBridge: unknown.7381:37@[::ffff:64.39.99.187] login as nobody
`

**Comment by abh3** [comment]
Did this happen at start up or when it was running for a while. What was 
the server doing at the time?

This looks like a new issue.

Andy

**Comment by ffurano** [comment]
Hi,

 I got to the same conclusion. This client is sort of scanning /static/ . This is a bug and
I would have suggested the same workaround. Just preloading whatever little file should avoid the crash.
I'll prepare a small fix.

Fabrizio
