### ISSUE TITLE
xrdfs query checksum ... issues

### ISSUE THREAD

**Issue by ffurano** [xrootd/xrootd#759]
Hi (sorry for the noise...)

 implementing xrootd checksums for DPM I found that there is no  way to specify the wanted checksum on the xrdfs command line.

 Ultimately this comes from the query checksum request, which apparently misses a field with the checksum name to be requested.

 Since xrootd now supports multiple kinds of checksums, how is a particular checksum requested ?

 This issue also affects the gfal-sum/gfal-copy client commands

**Comment by ffurano** [comment]
Wrong text... by mistake I was not using the xrd command line :-D

**Comment by abh3** [comment]
This is handled via cgi information. using element cks.type=<digest>. This element is automatically checked if more than one digest has been configured. The details can be found at

http://xrootd.org/doc/dev48/xrd_config.htm#_Toc496911333
