### ISSUE TITLE
Duplicate the symbol

### ISSUE THREAD

**Issue by peremato** [xrootd/xrootd#760]
We are using openssl 1.0.2d with Xrootd 4.8.2 on MacOS 10.13 and get the following linker error when building.
```
/Library/Developer/CommandLineTools/usr/bin/clang++  -std=c++0x -Wno-deprecated-declarations -O2 -g -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o libXrdHttp-4.so CMakeFiles/XrdHttp-4.dir/XrdHttp/XrdHttpProtocol.cc.o CMakeFiles/XrdHttp-4.dir/XrdHttp/XrdHttpReq.cc.o CMakeFiles/XrdHttp-4.dir/XrdHttp/XrdHttpExtHandler.cc.o CMakeFiles/XrdHttp-4.dir/XrdHttp/XrdHttpTrace.cc.o CMakeFiles/XrdHttp-4.dir/XrdHttp/XrdHttpUtils.cc.o libXrdServer.2.0.0.dylib libXrdCrypto.1.0.0.dylib -ldl -lpthread /build/jenkins/workspace/lcg_geant4ext_build/BUILDTYPE/Release/COMPILER/native/LABEL/mac1013/install/openssl/1.0.2d/x86_64-mac1013-clang91-opt/lib/libssl.a /build/jenkins/workspace/lcg_geant4ext_build/BUILDTYPE/Release/COMPILER/native/LABEL/mac1013/install/openssl/1.0.2d/x86_64-mac1013-clang91-opt/lib/libcrypto.a /build/jenkins/workspace/lcg_geant4ext_build/BUILDTYPE/Release/COMPILER/native/LABEL/mac1013/install/openssl/1.0.2d/x86_64-mac1013-clang91-opt/lib/libcrypto.a libXrdUtils.2.0.0.dylib 
duplicate symbol _BIO_set_flags in:
    CMakeFiles/XrdHttp-4.dir/XrdHttp/XrdHttpProtocol.cc.o
    /build/jenkins/workspace/lcg_geant4ext_build/BUILDTYPE/Release/COMPILER/native/LABEL/mac1013/install/openssl/1.0.2d/x86_64-mac1013-clang91-opt/lib/libcrypto.a(bio_lib.o)
ld: 1 duplicate symbol for architecture x86_64
```
or what versions of OpenSSL has been tested?

**Comment by simonmichal** [comment]
Hi Pere,

We are building against 1.0.2g by default in our CI.

In XrdHttpProtocol.cc we do define couple of functions that are not available in older versions of openssl:

https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpProtocol.cc#L124-L152

Could it be that in your case there's a mismatch between _OPENSSL_VERSION_NUMBER_ and the actual library that is being linked against XRootD?

Cheers,
Michal

**Comment by simonmichal** [comment]
@peremato : do you still have the problem? If yes could you grant me access to your build node (as I cannot reproduce the problem on our build machine)? If no, I suppose I can close the ticket?

Michal

**Comment by abh3** [comment]
Is this still a problem?

**Comment by peremato** [comment]
Sorry, I probably missed some of the replies. 
Now we are using XROOT 4.8.4 with OpenSSL 1.1.0h and we do not see any problem.
