### ISSUE TITLE
Issue with CRLs caching

### ISSUE THREAD

**Issue by andrea-manzi** [xrootd/xrootd#761]
i'm having an issue with Xrootd and the GSI plugin related to CRLs caching

basically we have a service ( FTS bringonline) which uses the Xrootd Client and it seems that after 2/3 days when the CRLs expires on the server the client does not refresh the CRL cache and we have this error:

180629 09:48:26 16956 secgsi_GetCACheck: CRL entry for '5168735f.0:1' needs refreshing: clean the related entry cache first (0x7fef4000eb80)

is there a way to force the refresh of the cache?

i have now configured the environment with XrdSecGSICRLCHECK=0, but we would like to understand and fix this behaviour

thanks!

**Comment by gganis** [comment]
Hi Andrea,
Sorry for the late reply.
Could you please specify:
  1. Who is issuing the message (client or server)
  2. Do you get a failure after this? What is the message?
  3. The XRootD version.

Thanks!
Gerri

**Comment by andrea-manzi** [comment]
Hi Gerri,
i have this problem client side ( my service is acting as client using the xrootd client), and after the message i got a failure cause GSI is not avaialble as auth method. ( i don't have the exact error  message  now as i have disabled CRLs verification and in any case to reproduce it i have to wait that the CRL expires). The version is 4.8.3-1
If the error message after that warning is important i will reproduce it and give you also the full GSI debug log
cheers
Andrea

**Comment by abh3** [comment]
The latest release has addressed this issue so I am closing this.
