### ISSUE TITLE
specs: kXR_unbind is mentioned despite being removed

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#764]
`kXR_unbind` request was removed, however [kXR_bind section](http://xrootd.org/doc/dev49/XRdv400.htm#_Toc517297840) still mentions it:

> 5) Should the client close a bound socket, the client should issue a kXR_unbind request specifying the pathid of the socket that was just closed. Failure to do so may cause future kXR_bind requests to fail.

**Comment by abh3** [comment]
It has been removed from the latest documentation.
