### ISSUE TITLE
bind: error 3010: cross-host bind not allowed

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#765]
I'm working on [adding bind request support](https://github.com/go-hep/hep/pull/288) to a pure-Go xrootd client.

Running tests locally works fine, however during Travis CI [build](https://travis-ci.org/go-hep/hep/builds/402681814) bind request fails with `error 3010: cross-host bind not allowed`.

I have tried to generate random usernames passed to the `login` request in hope that issue is appearing due to 4 clients on different VMs trying to log in with the same username, however, it's not the case.

Clients don't share any state between them, the `bind` request comes from the same process as a `login` one and uses `sessid` from it.

Can someone please explain what's meaning of this error and how can I verify it \ fix it?

**Comment by abh3** [comment]
It's likely hat from the servers perspective, he target of the bind does 
not match the issuer's host name. This can occur in a containerized 
environment. I don't know how Travis runs the tests so it's hard to telll 
you if that is the problem bt I suspect it is.

Andy

**Comment by sbinet** [comment]
ah.
indeed, travis-ci is using containers.

so, if I understand correctly, this error message is kind of like a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) error in http?

**Comment by abh3** [comment]
Yes, it's basically that, both protocols prohibit it for scurity reasons.

Andy

**Comment by abh3** [comment]
I'm closing this as a security requirement. However, it would be nice to have a full trace of this issue (i.e. just run with the -d flag and post the log for this case only).
