### ISSUE TITLE
cosmetic: noisy "cryptossl_ASN1toUTC" debug messages

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#772]
In debug mode, the line in `src/XrdCrypto/XrdCryptosslAux.cc`
```c++
   DEBUG(" UTC: "<<etime<<"  isdst: "<<ltm.tm_isdst);
```
causes several hundred log lines at daemon startup (it also does not contain further info). Could this perhaps be bumped to some "higher" debug level?

**Comment by abh3** [comment]
Sort of an off request. What are you trying to debug in the first place?

**Comment by jmuf** [comment]
We seem to be running in general "debug" mode (possibly to diagnose issue with X509 mappings, after the fact, i.e. keep log data). Most of the extra logging seems fairly benign.

**Comment by abh3** [comment]
Perhaps benign, but if you mean you used the -d option when starting the server it's actually running about 20% slower then it could otherwise. That's not what I exactly call benign.
