### ISSUE TITLE
Using built-in checksum calculation for filesystems without xattr support

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#774]
Right now, the built-in checksum calculation library only works if the underlying filesystem supports extended attributes.

If a site wants to run xrootd on a filesystem without xattrs (such as an NFS mount), then the site has to reimplement their own version of checksum calculation script.

It seems strange to tie the calculation functionality to the ability to record checksum values in the filesystem.  If this isn't handled transparently, it seems like it would be better to allow the admin to provide a configuration variable to enable the checksum calculations rather than relying on them to implement their own script.

**Comment by abh3** [comment]
The final decision here is that for filesystems that don't support xattrs one would need to supply a checksum manager plugin that does the appropriate thing (e.g. record the checksum in a database, a parallel file, etc.). The universal solution is beyond the scope of the XRootD project  and relies on the community to provide an acceptable solution for such sites as the framework allows for such a solution.
