### ISSUE TITLE
Ignore `xrd.protocol` in non-xrootd daemons?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#793]
Is it possible to only parse `xrd.protocol` in `xrootd` itself?

We have this annoying configuration line:
```
if exec xrootd
    xrd.protocol http:1094 libXrdHttp.so
fi
```

It's the only place where we have to use the `if exec xrootd` syntax and I would rather not expose it to the sysadmins if we don't have to.

Are there any cases where other daemons can use the protocol bridge?  If not, seems like we could keep it `xrootd`-specific until someone wants to write a new plugin.

**Comment by bbockelm** [comment]
@efajardo - I filed this after our discussion on https://github.com/opensciencegrid/docs/pull/411

**Comment by abh3** [comment]
Hi Brian,

The only other place is cmsd where it wouldn't make sense to load the HTTP 
protocol. Yes, the cmsd can also run multiple protocols but there is no 
bridge there. Currently, xrootd and http are the only protocols but I 
could imagine http2 on the horizon as well. Who knows, maybe someone brave 
enough will want to add NFS4 :-)

Oddly, I see you accept http at he xrootd port. I thought hat most http 
people dislike that and use he standard http port, 80. But that's a side 
issue.

Andy

On Thu, 2 Aug 2018, Brian Bockelman wrote:

> Is it possible to only parse `xrd.protocol` in `xrootd` itself?
>
> We have this annoying configuration line:
> ```
> if exec xrootd
>    xrd.protocol http:1094 libXrdHttp.so
> fi
> ```
>
> It's the only place where we have to use the `if exec xrootd` syntax 
and I would rather not expose it to the sysadmins if we don't have to.
>
> Are there any cases where other daemons can use the protocol bridge? 
If not, seems like we could keep it `xrootd`-specific until someone wants 
to write a new plugin.

**Comment by abh3** [comment]
OK, I see that there is little interest in following up on this. So, I am closing it. If there are srong feelings (which there appear not to be) we can re-open this.
