### ISSUE TITLE
pidpath : -s option should override the all.pidpath option

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#802]
Hi! The usage of -s option is somehow inconsistent with existence of all.pidpath setting.
1. -s declaration should invalidate/override any pidpath option from the configuration file
(one also could argue that being a service steering option, there should be only the command line option)
2. pid files generated by the pidpath declaration (not by -s) are inconsistent with each other: the cmsd.pid from pidpath directory (or /tmp/<instance> if pidpath is not defined) have extra information beside the pid (so the contents is not consistent with xrootd.pid that have only the xrootd pid)

Thank you!
Adrian

**Comment by abh3** [comment]
This has now been addressed in R5 under the rubric of "rationalizing pidfile creation". The cli -s option will indeed make sure that the pidfile is created where you said it should be created. If a pidfile directive appears in he config file, a pidfile may be created there as well. All pidfile will only have a pid in them, nothing more.
