### ISSUE TITLE
adminpath : no cli option for adminpath

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#803]
The all.adminpath service steering variable have no corresponding option for cli and it should have.
Could an cli option be added for adminpath that would override the option from configuration file?
Alternatively, just remove the option and just automatically create all adminpath files in $(dirname pidfile) 
(all these file are transient, isn't it ?)
Thank you!

**Comment by adriansev** [comment]
Well, IMHO service settings should be flexible in configuration. It is way harder to automatically modify the admin.path in config file PRIOR to starting of service by systemd then to have an option that can be modified by simple systemd override.conf  
Moreover the non-transient files _should_not_ be in the same place with the transient ones .. having files with different lifetimes and purposes in the same location is not very safe, i would say, and they should be configured by different switches.

**Comment by bbockelm** [comment]
IIRC, Xrootd 4.9 allows config.d-style directories.  That would allow a packager drop-in a override of the `all.adminpath` without having to do this inside systemd configs.

I agree on the comment about splitting out persistent-vs-transient files, but that seems to be a completely different ticket, no?

What are you trying to fix, exactly?  The fact that the various admin files appear to be incorrectly placed?

**Comment by adriansev** [comment]
> IIRC, Xrootd 4.9 allows config.d-style directories. That would allow a packager drop-in a override of the `all.adminpath` without having to do this inside systemd configs.

well, thats a very good news but is somehow beside the point i try to make.  
i was trying to make an argument that any service should also have a cli switch to specify the location
of runtime generated files (pid, sockets etc...). adminpath is such a location and IMHO the service should have an cli option to specify it.

> 
> I agree on the comment about splitting out persistent-vs-transient files, but that seems to be a completely different ticket, no?

yes, that would be another issue, but i think a lot more complex than to add an "-a adminpath"
(-s for pidfile was taken) as argument of xrootd/cmsd

> What are you trying to fix, exactly? The fact that the various admin files appear to be incorrectly placed?  

well, the issue of redundant (and inconsistent) contents of adminpath is another thing. i am just trying to ask a feature that consist of an argument of executable that would set the location of the sockets used by the service...  
Thank you!

**Comment by xrootd-dev** [comment]
On Tue, 9 Oct 2018, Brian P Bockelman wrote:

> (Would probably be good to file a ticket about splitting 
> persistent-vs-transient files... I think that question is very 
> interesting!)
>
> Andy, re-reading your original response - are you opposed to exposing 
> this via a config switch?  Why is the PID path a CLI (I see `-s 
> /var/run/xrootd/xrootd-clustered.pid` in the runtime arguments) but not 
> the admin path.
I'm not opposed but what is in the admin oath is purely of interest to 
xrootd and should not interest anyone else. The reason we added -s is 
because site admins wanted it and no one cared about the adminpath 
because it was purely opaque (as it should be) and was good enough to be 
in the config file for everyon up until now. Hey, not even you complained. 
Generally, I'd prefer it to be in the config file under the premise you 
would have a single config for the cmsd and the xrootd. Putting it in the 
cli puts the onus on you to make sure you specify the same path for each 
daemon. If you don't a lot of things just won't work.

**Comment by abh3** [comment]
I've given this a lot of thought (what else to do in a lock down, eh?) and the answer is no, there will not be a cli option for the adminpath. The major reason is that one-size does not fill all. The xrootd admin path has a lot of important information (e.g. POSC information, credenials, etc) which, as the reference says, deserves a higher quality of storage as opposed to the cmsd adminpath that has somewhat mundane information. So, the easiest way to  accomplish this is to set the xrootd adminpath to high quality storage and the cmsd adminpath to regular type of storage, A cli override would make that differentiation impossible. Given that what is in the adminpath is relatively opaque there is no practical reason to have a cli for this other than someone wants complete control.

**Comment by adriansev** [comment]
@abh3 well, the direct consequence is that the those files will stay (are staying) in tmp (which is tmpfs) because no one can spend time to adapt for each server/fst the xrootd configurations. 
and yes, an system admin HAVE TO have complete control.   
also, i strongly believe that any application that is to be run as a server should have knobs to adapt it's usage at starting point (yeah, one can use systemd generators, but what can you do in scenarios like singularity or dockers that have shared tmp?) .. well, i exhausted all my arguments, i have nothing left to say

**Comment by xrootd-dev** [comment]
Not so fast! I see that what you are really trying to solve is sloppy 
configuration files. While we don't have much control over that we can do 
this. If you specify the cli to set the admin path it is not an override, 
it merely sets the default. So, those sites that are fastidious will get 
the admin path they want and those that are not will get something that 
works better that /tmp. Will that be an acceptable solution?

**Comment by adriansev** [comment]
@xrootd-dev well, the scenario that i have i mind is this: the xrootd configs is generated/regenerated/site-wide synchronized  for the same time of service but the actual service is used/started on various machines/containers etc... so actually what is common is the xrootd functionality (same export/role/params) but the deployment could wildly differ, and this is usually tune by provisioning tools (like dropping a override file in system/my_service.d/ )
So, as long i can specify in the systemd unit where the files will be written is good enough for me.
and just to offer complete explanation: i recently deployed my first EOS and it is annoying like hell this :
```
[root@mgm ~]# ll /tmp | grep daemon
drwx------. 2 daemon   daemon   4096 Apr  6 21:50 eos.mgm
drwx------. 4 daemon   daemon   4096 Apr  7 09:50 mgm
drwx------. 4 daemon   daemon   4096 Apr  7 14:43 mq
prw-r-----. 1 daemon   daemon      0 Apr 11 01:20 ofsEvents
drwx------. 5 daemon   daemon   4096 Apr  6 18:57 quarkdb1
drwx------. 5 daemon   daemon   4096 Apr  6 18:57 quarkdb2
drwx------. 5 daemon   daemon   4096 Apr  6 18:57 quarkdb3
-rw-r--r--. 1 daemon   daemon    164 Apr 11 01:20 xrootd.anon.env
-rw-r--r--. 1 daemon   daemon    145 Apr  9 02:20 xrootd.mgm.env
-rw-r--r--. 1 daemon   daemon    138 Apr  7 17:04 xrootd.mq.env
-rw-r--r--. 1 daemon   daemon      5 Apr 11 01:20 xrootd.pid
-rw-r--r--. 1 daemon   daemon    178 Apr 11 01:25 xrootd.quarkdb1.env
```
as a side note, i think that if -b is not used the pid file is useless (unless used internally by xrootd)

**Comment by abh3** [comment]
Hi Adrian,

The -b foible has been fixed in the R5 series. The pidfile will always be 
written to where the -s option said it should be written. The original 
implementation assumed that it should go into effect if you were 
deamonized. Wrong assumption for containers (we are still learning here).

OK, I will change the code to allow you to specify a default for the 
unfortunates. Mind you if someone wants to override it via a config file, 
it's obvious they need to know how to do it in a containerized 
environment. I will add an admonition of this in the docs.

Andy

**Comment by adriansev** [comment]
@abh3 Thanks a lot!
