### ISSUE TITLE
xrdfs man page should document return code 55

### ISSUE THREAD

**Issue by murrayc3** [xrootd/xrootd#806]
The xrdfs man page describes the “stat” subcommand.  The description of this subcommand is not complete because it does not explain how to determine if the error code returned is really an error of if the command has succeeded to read a flag that is not set.

The description of the “stat” subcommand only states:

    -q query optional flag query parameter that makes xrdfs return error code to the shell if the requested flag combination is not present;

The description should be augmented to also state that a return value of 55 indicates that the command successfully read a flag that is not set. 

In all fairness a RETURN CODES section should be added to the man page of xrdfs.  Something very similar to the man page of the xrdcp command, for example

RETURN CODES

       50  : generic error (e.g. config, internal, data, OS)

       51  : socket related error

       52  : postmaster related error

       53  : XRootD related error

       54  : redirection error

       55 : query response was negative (this is not an error)

**Comment by murrayc3** [comment]
I have sent the following patch to xrootd-l@slac.stanford.edu.

```
[itctabuild02] xrootd (master) > cat 0001-xrdfs-man-page-should-document-return-code-55-806.patch
From d48151ae5eb9c18316f6b1e85504a9fc7ac0ca2e Mon Sep 17 00:00:00 2001
From: Steven Murray <Steven.Murray@cern.ch>
Date: Thu, 23 Aug 2018 10:24:18 +0200
Subject: [PATCH] xrdfs man page should document return code 55 #806

Done
---
 docs/man/xrdfs.1 | 18 ++++++++++++++++--
 1 file changed, 16 insertions(+), 2 deletions(-)

diff --git a/docs/man/xrdfs.1 b/docs/man/xrdfs.1
index 8b9dfe6..d33699f 100644
--- a/docs/man/xrdfs.1
+++ b/docs/man/xrdfs.1
@@ -77,8 +77,8 @@ Move path1 to path2 locally on the same server.
 .RS 3
 Get info about the file or directory.
 .br
-\fI-q\fR query optional flag query parameter that makes
-xrdfs return error code to the shell if the
+\fI-q\fR \fB<flags>\fR Makes
+xrdfs return error code 55 to the shell if the
 requested flag combination is not present;
 flags may be combined together using '|' or '&'
 .br
@@ -212,6 +212,20 @@ Output last part of files to stdout.
 .RS 3
 Get space statistics for given path.
 
+.SH RETURN CODES
+.RE
+\fB50\fR  : generic error (e.g. config, internal, data, OS)
+
+\fB51\fR  : socket related error
+
+\fB52\fR  : postmaster related error
+
+\fB53\fR  : XRootD related error
+
+\fB54\fR  : redirection error
+
+\fB55\fR  : query response was negative (this is not an error)
+
 .SH NOTES
 For the list of available environment variables please refere to xrdcopy(1)
 
-- 
1.8.3.1

[itctabuild02] xrootd (master) > 
```

**Comment by simonmichal** [comment]
I applied the path in 409f58e9b07e22f7834361fd106b57bcaea8514a
