### ISSUE TITLE
kXR_mkdir does not accept kXR_mkpath in options field. 

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#815]
The xrootd protocol spec (v3.1.0) describes how `kXR_mkdir` and `kXR_open` operations both have an `options` field.  In both cases, this field act as a bit mask for flags that affect the behaviour of the respective commands.  According to the spec, both accept the value `kXR_mkpath` with similar semantics:

`kXR_mkdir`:
http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248821

`kXR_open`:
http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248823

This is wrong as the xrootd code uses bit-0 in `kXR_mkdir` options to indicate parent directory elements should be created, whereas `kXR_open` uses bit-8 for the same behaviour.  Therefore, the flags cannot be described using the same constant (`kXR_mkpath`).

Further, these constants appear not to be defined anywhere in the spec.  This makes the spec. incomplete.

**Comment by abh3** [comment]
This problem is well known and was introduced some time ago. We left the bug in so as not to introduce different semantic behavior from what was expected with the goal of correcting it on a major release boundary. As for dCache, you should follow the spec not the implementation.

**Comment by paulmillar** [comment]
Hi Andy,

I don't really understand your comment about backwards compatibility.  `kXR_mkpath` is defined as `256` ([defn](https://github.com/xrootd/xrootd/blob/master/src/XProtocol/XProtocol.hh#L222)).  However, the `options` field of the `kXR_mkdir` command is only 8-bit wide, so cannot hold this flag. 

In fact, the SLAC xrootd implementation uses the undocumented `kXR_mkdirpath` flag ([defn](https://github.com/xrootd/xrootd/blob/master/src/XProtocol/XProtocol.hh#L161)).

>  As for dCache, you should follow the spec not the implementation.

That is, indeed, our goal.

Our problem is that the SLAC xrootd does not follow the xrootd specification and we have users that depend on dCache behaving like SLAC xrood implementation.

My proposed solution is simple: update the documentation to accurately describe the SLAC xrootd software behaviour.  This simply means changing the label `kXR_mkpath` to `kXR_mkdirpath` when describing the `kXR_mkdir` command.

Do you have an estimate when the protocol document will be updated?

**Comment by abh3** [comment]
Well, the issue here is that it works because it grabs bits from another flag that usually gets set. So, we wanted to keep that behavior and then case it out in 5.0 to correspond to the spec. You probably have noticed that no one is complaining about the unruly behavior because, well the implementation does roughly what people expect, even though it's wrong.

**Comment by abh3** [comment]
Oh, yes, I suppose I can put that in the sec but that is not the right place to mention such things. The spec documents what you should do not what is not being done.

**Comment by paulmillar** [comment]
Are you saying that the specification is correct, and the same numerical value (`kXR_mkpath`) should be used in both `kXR_mkdir` and `kXR_open` commands?

If so, fixing this in SLAC xrootd would require a non-backwards compatible change in SLAC xrootd software.

However, this breaking backwards incompatibility is simply not needed.

There is no reason the same semantics must be represented by the same numerical value in different  operations.  The current SLAC xrootd behaviour is perfectly reasonable: using 0x01 in `kXR_mkdir` and 0x100 in `kXR_open` to indicate paths should be created automatically.

Therefore, my proposal to fix this (update documentation, changing the `kXR_mkdir` command's constant from `kXR_mkpath` to `kXR_mkdirpath`) will resolve this issue without requiring any changes in SLAC xrootd and without breaking backwards compatibility.

This solution treats the problem as a simple typo in the specification.  Fixing it is equally easy.

**Comment by kofemann** [comment]
@abh3 Paul's proposal is quite simple and clean without introducing any client/server incompatibilities:

> update documentation, changing the kXR_mkdir command's constant from kXR_mkpath to kXR_mkdirpath

Even if the original intention was to use kXR_mkpath option for kXR_mkdir command you cant change it any more as there are SLAC client and server in deployment which are not xrootd spec compliant (I can't believe saying that).

**Comment by abh3** [comment]
Unfortunately, I totally disagree. Regardless of what the current implementation of xrootd does, it's quite wrong and it should follow the specs. The proposed solution is a total hack and I don't consider it acceptable. There are better ways of resolving this problem.

**Comment by kofemann** [comment]
Well, fine with us.

* please confirm that current dCache implementation is xrootd spec complied.
* please fix and rollout clients which are spec compliment.
* please inform users that they have to update to the bugfix version of xrttod client

**Comment by abh3** [comment]
As far as I can tell, dCache has been compliant since day 1 and there 
have been no complaints. So, it follows that if xrootd becomes compliant, 
the same should hold true.

**Comment by abh3** [comment]
Actually, it does. The protocol documentation is wrong. It must have been regressed at some point but I'll add it back in. In the mean time, in XrdFileSystem, you can specify you want the path created. I'll keep this open until the docs are corrected.

**Comment by abh3** [comment]
This has been corrected in V4 of the protocol document,
