### ISSUE TITLE
Feature request: glob functionality for python bindings

### ISSUE THREAD

**Issue by benkrikler** [xrootd/xrootd#832]
Is it reasonable to consider adding glob functionality to the python bindings?  I'd be happy to try and implement this myself, but I wanted to check how it would be received and if there were suggested approaches.   I imagine this being a new function within the FileSystem module.  Given a path containing wildcards (potentially more than one), a list of files that match this (as per fnmatch) should be returned.

Just some context on why I'd like to do this:  I've previously added such functionality into the rootpy project ([here](https://github.com/rootpy/rootpy/blob/master/rootpy/utils/ext_glob.py)), but I now wanted to get such functionality without requiring ROOT to be installed rootpy.

**Comment by simonmichal** [comment]
Hi Ben,

As I said in https://github.com/xrootd/xrootd-python/issues/19 thanks for taking initiative and sorry for the late response! 

Could you prepare a PR based on https://gitlab.cern.ch/fast-hep/public/fast-curator/blob/master/fast_curator/xrootd_glob.py, I'll try to do a review once it's done ;-)

Is this a full globbing functionality or a subset?

Michal

**Comment by simonmichal** [comment]
Since #854 has been merged I'm closing it.
