### ISSUE TITLE
Logrotation with `fifo` gets broken from time to time

### ISSUE THREAD

**Issue by glpatcern** [xrootd/xrootd#837]
Observed with CASTOR @ CERN and discussed with @simonmichal:

By using the standard xrootd logrotation script and starting xrootd with an instance name and the fifo option as follows:
```
[root@host]# grep Exec !$
grep Exec /etc/systemd/system/xrootd\@.service.d/xrootd.conf
ExecStart=
ExecStart=/usr/bin/xrootd -I v4 -l /var/log/xrootd/xrootd.log -c /etc/xrd.cf.%i -k fifo -s /var/run/xrootd/xrootd-%i.pid -n %i
```
It may happen that at log rotation time the xrootd process does not pick up the `ping` message and keeps logging on the (now deleted) log:
```
[root@host]# lsof -p 13852 | grep var
xrootd  13852 stage  cwd       DIR              253,1        4096    37298201 /var/spool/xrootd/server
xrootd  13852 stage    2w      REG              253,1  2199257567    46776392 /var/log/xrootd/server/xrootd.log-20180612 (deleted)
```
At that point, only a manual operation like `echo x >> /var/log/xrootd/server/.xrootd.log` unblocks the situation.

Unfortunately, we don't seem to find a way to reproduce the problem, so comments are much appreciated.

For internal reference, this is also tracked at https://its.cern.ch/jira/browse/CASTOR-5520 (behind CERN SSO)

**Comment by abh3** [comment]
I am closing this. We have seen similar problems in SELinux where the SE policy changes after an upgrade and prevents logrotate from writing to the FIFO.

**Comment by glpatcern** [comment]
Hi Andy, that's fine with me - our workaround did not have issues for >1 year.

Otherwise, just to comment that I don't understand the relationship with SELinux: are you saying that you see this behavior also in other contexts involving SE, and somehow people live with it?

**Comment by xrootd-dev** [comment]
Hi Giuseppe,

Indeed, we do. The most recent one was Oklahoma State where if you looked 
in the SE log (there is a separate log for security violations) you would 
see hat logrotate was denied access to the FIFO. Issuing the logrotate 
fifo part of the command as root worked flawlessly. So, yes, we think most 
of the problems have to do with the SE policy in effect.

Andy

**Comment by glpatcern** [comment]
OK, thank you Andy. Indeed we run the service not as root, and SELinux is typically `enforced` in the cluster. I'd still expect the issue to happen all the time, not only sporadically, but there's a clear correlation nevertheless. So we can close the discussion.
Thanks again,
Giuseppe
