### ISSUE TITLE
Grafting parts of the exported namespace

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#840]
For the OSG data federation, we want to assign each VO a certain namespace (let's say the "Xenon1T" VO gets assigned `/xenon1t`).

The Xrootd server that wants to export its data has the Xenon1T files mounted at `/mnt/data`.  So, the Xenon1T file `/foo` is physically at:

```
/mnt/data/foo
```

but should be exported as:

```
/xenon1t/foo
```

That is, `root://xrootd.example.com:1094//xenon1t/foo`.

Looking at the documentation, I thought `oss.remoteroot` was the way to integrate this: I think was incorrect.

What's the right way to configure the OFS / OSS for this setup?

**Comment by wyang007** [comment]
I think it is

all.export /xenon1t
oss.localroot /mnt/data

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338 (O)

**Comment by adriansev** [comment]
i am not sure if i understand your problem, but under localroot there could be a number of aggregated oss.space directories (mount points that hold the data) .. so you could have :   
`
all export /
oss.localroot /somewhere/xenon1t_xrd_namespace
oss.space xenon1t /mnt/data1
oss.space xenon1t /mnt/data2
`
or
`
all export /xenon1t
oss.localroot /somewhere/xrd_namespace
oss.space xenon1t /mnt/data1
oss.space xenon1t /mnt/data2
`
so all /mnt/data* storage spaces are aggregated under specified localroot and the actual / of xrootd is the oss.localroot (is you don't use oss.namelib that make another set of translations)

**Comment by abh3** [comment]
Hi Brian,

Well, an interesting predicament you have. I’d suggest a symlink.

/xenon1t –> /mnt/data

and then export xenon1t

It’s much easier if the name spaces are straightened out well ahead of people storing files into the server.

Andy

From: Brian P Bockelman 
Sent: Friday, October 12, 2018 11:12 AM
To: xrootd/xrootd 
Cc: Subscribed 
Subject: [xrootd/xrootd] Grafting parts of the exported namespace (#840)

For the OSG data federation, we want to assign each VO a certain namespace (let's say the "Xenon1T" VO gets assigned /xenon1t).

The Xrootd server that wants to export its data has the Xenon1T files mounted at /mnt/data. So, the Xenon1T file /foo is physically at:

/mnt/data/foo
but should be exported as:

/xenon1t/foo
That is, root://xrootd.example.com:1094//xenon1t/foo.

Looking at the documentation, I thought oss.remoteroot was the way to integrate this: I think was incorrect.

What's the right way to configure the OFS / OSS for this setup?

**Comment by bbockelm** [comment]
Hm, I suppose the symlink trick works.

We're working with various pre-existing data sources and documenting how to export the data over Xrootd - it'd be nice to be able to setup the prefixed exports only via config file, but I think symlinks would do (ends up being somewhat difficult to explain to admins why they have to go through the process, but we'll survive!).
