### ISSUE TITLE
xrdcopy ignores subject alternative names from the x509 host certificate 

### ISSUE THREAD

**Issue by XMol** [xrootd/xrootd#841]
Hello,

we recently have changed our layout for our dCache storage element, which also affected the xrootd capabilities. As you may know, [dCache](https://www.dcache.org/) has so-called "doors", that implement the support for different transfer protocols, including [xrootd](https://www.dcache.org/manuals/Book-3.2/config/cf-xrootd-fhs.shtml). That xrootd door may use a gsi plugin to enforce grid security standards for xroot transfers. With our changes however, we ran into a new issue, we avoided before by coincidence: The xrootd transfers fail with an "auth error", because the (primary) host name of the dCache xrootd door does not match the (primary) subject name in the host's certificate.

> Auth protocol handler for gsi refuses to give us more credentials Secgsi: ErrParseBuffer: server certificate CN 'f01-081-126.gridka.de' does not match the expected format(s): '[*/]dcachesrm-kit.gridka.de[/*]' (default); exceptions are controlled by the env XrdSecGSISRVNAMES: kXGS_cert
--- snippet from [xfer.log](https://github.com/xrootd/xrootd/files/2483307/xfer.log)

In my opinion, this is a bug in the xrdcopy tool, since the name we used in the transfer URL is listed among the subject alternative names inside the host certificate.
```
$ openssl x509 -in /etc/grid-security/dcache/hostcert.pem -noout -text | grep -A 1 "Subject Alternative"
            X509v3 Subject Alternative Name:
                DNS:f01-080-118.gridka.de, DNS:dcachedcap-kit.gridka.de, DNS:dcachegridftp-kit.gridka.de, DNS:dcachesrm-kit.gridka.de, DNS:dcachewebdav-kit.gridka.de, DNS:dcachexrootd-kit.gridka.de, DNS:f01-080-118-v4.gridka.de, DNS:f01-080-118-v6.gridka.de
```

The error may be overruled by exporting `XrdSecGSISRVNAMES="f01-080-118.gridka.de"`. Though that is not what we can demand from all our customers around the world ("Please ignore the security issues and simply trust our servers." 😉 ).

At first I blamed the plugin in dCache for this, but one of the developers from dCache.org told me, that they do not interfer with that. That is, they provide the host certificate as is to the client and it should extract the information that it is interested in - maybe you can find evidence for that in the [attached log file](https://github.com/xrootd/xrootd/files/2483307/xfer.log) of the transfer.

Lastly I want to mention that we're currently working with version 4.8.4 of xrdcopy and removing the gsi plugin from the dCache door will make the error go away, too (which means, that xroot transfers can happen without it).

I was unable to find similar complaints among the issues here on GitHub or the mail archive at xrootd.org. In case you need more information, I'd gladly provide it to you.

Best regards,
Xavier Mol.

**Comment by bbockelm** [comment]
@XMol -

The Xrootd client does not support subject alternative names until the upcoming 4.9.0 release.  The work is done and committed - just not released yet.

Given the rate of turnover of old clients and software, it'll likely be many years before you can assume this version is available at all clients.  For CMS - probably the start of LHC Run3 or later.

Brian

**Comment by XMol** [comment]
Thanks for the information, @bbockelm.

Then I'll close this issue already. Maybe someone with the necessary rights can label this issue appropriately and put version 4.9.0 as milestone, just for clearness sake.

Ciao,
Xavier.

**Comment by abh3** [comment]
Hi Xavier,

Don't be so fast to close this issue. We are seeing identical problems 
with the 4.9.0 pre-release. So, there is a problem here and we don't yet 
understand what it is but it's pretty clear it's ASN related. We also 
don't understand why you are getting the problem as we don't see it with 
similar setups using 4.8.4. So, I'd keep this open until we can figure out 
where the real problem is.

Oh yes, when you say 4.8.4, which distribution are you actually using?

Andy

**Comment by XMol** [comment]
Hi Andrew.

> Oh yes, when you say 4.8.4, which distribution are you actually using?

We're using the package build for Fedora which came from epel on an SL7.3 machine (if that's the information you asked for).

Ciao,
Xavier.

```
$ rpm -qi xrootd-client
Name        : xrootd-client
Epoch       : 1
Version     : 4.8.4
Release     : 1.el7
Architecture: x86_64
Install Date: Wed 01 Aug 2018 09:42:04 PM CEST
Group       : Unspecified
Size        : 543871
License     : LGPLv3+
Signature   : RSA/SHA256, Wed 11 Jul 2018 08:44:38 AM CEST, Key ID 6a2faea2352c64e5
Source RPM  : xrootd-4.8.4-1.el7.src.rpm
Build Date  : Wed 11 Jul 2018 06:38:08 AM CEST
Build Host  : buildvm-02.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://xrootd.org/
Bug URL     : https://bugz.fedoraproject.org/xrootd
Summary     : Xrootd command line client tools
Description :
This package contains the command line tools used to communicate with
xrootd servers.

$ yum -d0 list installed xrootd-client
Installed Packages
xrootd-client.x86_64             1:4.8.4-1.el7           @epel

$ cat /etc/redhat-release
Scientific Linux release 7.3 (Nitrogen)
```

**Comment by xrootd-dev** [comment]
Yes, we need to know if ASN support was included in that distribution to 
narrow down the problem. Thanks!

**Comment by XMol** [comment]
>It looks to me that Xavier's case and the case I encountered are different.

If you say, that your host certificate for uct2-xrootd.mwt2.org actually does _not_ have "fax.mwt2.org" as an alternative name in it, then yes, our situations are different - in your case, the error is justified, in my opinion.  
It could be, that client tools do a name resolution of the alias and a subsequent reverse lookup of the IP to verify whether _that_ name is mentioned as the subject name in the certificate, possibly? That's the only way how an DNS alias could still work with these grid security regulations.

**Comment by bbockelm** [comment]
Hi @XMol -

Actually, the 4.9.0 client is meant to duplicate the (insecure) existing reliance on reverse DNS, so Andy's case should be working as the DN matches the reverse DNS lookup of the IP.

This is controllable by the environment variable `XrdSecGSITRUSTDNS` (defaults to `1`; set to `0` to disable use of reverse DNS lookups).

Looks like there's a regression in master after SAN support was added - maybe a bad merge?  Seems that the `trustdns` variable is set but never used, which is a touch suspicious.

Brian

**Comment by bbockelm** [comment]
Looks like two things:

1.  (Unrelated to this ticket) It doesn't appear possible to disable `TrustDNS`.
2.  If a valid hostname is provided by the user in 4.9.0, we compare that to the DN and SANs.  However, we no longer do a reverse DNS lookup in case that fails.

Note that if you use the IP address directly (`root://192.170.227.207//bar/baz`), it works.

Should be a straightfoward fix.

**Comment by XMol** [comment]
Hi Brian.

> Note that if you use the IP address directly (root://192.170.227.207//bar/baz), it works.

That is supposed to work for Andrew only, right? In my case, it does not, since the IPs are not included in the host certificate, nor does the name from the reverse lookup match the subject name of the certificate.

Ciao,
Xavier.

**Comment by gganis** [comment]
> Looks like there's a regression in master after SAN support was added - maybe a bad merge? Seems that the trustdns variable is set but never used, which is a touch suspicious.
> (Unrelated to this ticket) It doesn't appear possible to disable TrustDNS.
I looks like a missing piece. I think I forgot it when I revised the patch. Anyhow, I have fixed it now.

**Comment by bbockelm** [comment]
One addendum:

> I must admit that the whole notion of not trusting DNS generally breaks many x509 features (at least in the way certs are issued today).

We should make it clear that this is only true in the Xrootd context.  HTTP solved this issue a few years back and GridFTP stopped relying on DNS in 2016 or 2017 (can't recall).

We now have isolated the use of DNS for resolution to explicit fallback code.  We have the ability to issue a warning for these cases (perhaps notifying that the configuration is deprecated and may be removed in the future).

In my testing, there's only a handful of endpoints and implementations that are affected (biggest one is EOS) as admins have to include SANs for other protocols they configure (which is why Xavier filed the ticket in the first place...).

**Comment by maarten-litmaath** [comment]
Hi all,
I think Xrootd should imitate Globus in this matter: by default, the client should compare
the name it used to contact the service with the names in the SAN and fall back on the
subject DN as needed.  Better yet, for the time being it could still fall back on the DNS
if no match was found yet.  Just as Globus did, at some point the latter fall-back is no
longer tried by default, but still available through a run-time configuration option.
In the end, possibly after a few years, that route is removed altogether.

**Comment by xrootd-dev** [comment]
Hi Brian, Gerri, Andy,

I went through the "Endpoint Identification" section of RFC 2818. Will the following works?

1. By default require that a subjectAltName be presented in server's host certificate.  subjectAltName includes DNS aliases, IP addresses, wildcard. 
2. Print a warning and terminate if not matching is found between name/IP in client URI and hostname/subjectAltName.
3. Provide a switch for client to overrule the matching checks.

I think 
1) is there
2) is almost there but only exist in debugging level 2 (in xrdcp). The warning is needed even without using the debugging option, and needed by all clients, not just from xrdcp (so better in XrdCl)
3) We current have a switch XrdSecGSITRUSTDNS. It is an environment variable. We can reuse use it to both 3) and suppress the warning message in 2). This help automated clients (like Xcache, XrootdFS, xrdcp in TPC). For xrdcp, we can also provide an command line option to set this environment.

Comments?

regards,
--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

?-----Original Message-----

**Comment by msalle** [comment]
Hi,
your step 1) is a bit too restrictive. It's not mandatory to have subjectAltNames (SANs) in a hostcert, but if they are there, they MUST match. If there is no SAN, then the most specific CN field MUST match the hostname. This latter option is not recommended, but allowed. See second paragraph on https://tools.ietf.org/html/rfc2818#page-5

**Comment by bbockelm** [comment]
Hi @msalle -

I interpreted Wei's input as basically "do RFC2818 first; emit a warning; then, based on configuration, decide whether to fallback to DNS (and/or other overrides)".

The only "tweak" I'd make is to disallow the client from delegating proxies (e.g., a new use case) if it trusted DNS.  As we add proxy delegation to the Xrootd client, I'd prefer to start out right.

Brian

**Comment by msalle** [comment]
Hi @bbockelm,
maybe I misunderstood, but I commented on the suggested implementation of RFC2818, which doesn't require the use of SANs, but allows using CN=hostname instead. If that check matches, there is no need to go steps 2 and 3.
I fully agree with your 'tweak'

**Comment by bbockelm** [comment]
Right - if the check from RFC2818 matches, all is fine and we return successful.

If step one _fails_, then we always go to step 2 (warn).  Depending on configuration, we can go to 3 (trust DNS / fallback).

**Comment by wyang007** [comment]
Hi Brian,

Thanks and yes that is what I meant, and I think we already had a campaign to ask sites to use subjectAltName...

In terms of disallowing delegation if client choose to trust DNS, I tend to think it is the client's responsibility to do what is right, not ours. But I don't think I have a strong preference one way or the other. Perhaps such a stricter rule will also help reduce negative PR down the road. So ... OK.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

?-----Original Message-----
