### ISSUE TITLE
full list of xrootd servers

### ISSUE THREAD

**Issue by vkuznet** [xrootd/xrootd#842]
Hi,
while resolving issue #836 with local network admin I learnt that they block all traffic by default. I was asked to provide list of xrootd servers which needs to be connected. Can this be arranged? Could you please provide full list of xrootd servers used by CERN/FNAL global redirectors. And, if this list is changed dynamically could you please explain how to find out the full list then. If this list cannot be distributed via ticket, I'll be happy to adjust to any form of communication if you want to send it secretly.

Thanks,
Valentin.

**Comment by abh3** [comment]
You can do this by using the xrdmapc command. The argument is the host:port of the redirector who's nodes you want to see. Use --help to get additional options. So, with this answer I'm closing this.
