### ISSUE TITLE
xrdcp v4.8.4 can hang when using multiple streams if connection issues occur

### ISSUE THREAD

**Issue by chrissamuel** [xrootd/xrootd#843]
Hi there,

I was trying to copy ~15TB of LIGO public data to our local clusters Lustre filesystem and found that when using multiple streams with the -S option xrdcp could hang when connection issues occurred (there was a firewall "upgrade" that caused a lot of issues).  When run without the -S option xrdcp would correctly eventually give up on copying and exit with an error.

Unfortunately this happened just before I had to head overseas for urgent family business and I only learned about this location to report issues on my return by a colleague overseas who suggested I open an issue about it, so I'm afraid I have no extra useful information to add.  I did run pstack at the time to check stack traces but I'm afraid I don't have a record of them.

Host OS: CentOS 7.5
xrdcp version: 4.8.4

All the best,
Chris

**Comment by abh3** [comment]
We tried to reproduce this in a 4.11.0 fter we changed the substream selection and could not reproduce the problem. So, we think this has been fixed.
