### ISSUE TITLE
chmod not working with xrootdfs mount

### ISSUE THREAD

**Issue by dougbenjamin** [xrootd/xrootd#86]
we have xrootd data server mounted on another machine using xrootdfs

Here is the auto mount line -
/grid/atlas -fstype=fuse,rw,uid=xrootd,rdr=root\://atlasfs02.hep.anl.gov\:1094//grid/atlas :xrootdfs.sh

[dbenjamin@ascinode ~]$ cat /usr/bin/xrootdfs.sh
#!/bin/bash
exec /usr/bin/xrootdfs $@ >/dev/null 2>&1

and 

[dbenjamin@ascinode ~]$ mount | grep grid
xrootdfs on /grid/atlas type fuse (rw,allow_other)

yet when I try to change permissions on the file -

[dbenjamin@ascinode ~]$ ls -l /grid/atlas/hpc/common/alpgen/executables/zjetgen
-rw-rw-rw- 1 xrootd xrootd 502036 Feb 21 19:49 /grid/atlas/hpc/common/alpgen/executables/zjetgen

to 755 nothing changed.

[dbenjamin@ascinode ~]$ chmod -v 755 /grid/atlas/hpc/common/alpgen/executables/zjetgen
mode of `/grid/atlas/hpc/common/alpgen/executables/zjetgen' changed to 0755 (rwxr-xr-x)
[dbenjamin@ascinode ~]$ ls -l /grid/atlas/hpc/common/alpgen/executables/zjetgen
-rw-rw-rw- 1 xrootd xrootd 502036 Feb 21 19:49 /grid/atlas/hpc/common/alpgen/executables/zjetgen

The file server xrootd log shows no error.

I can change the permission with :

[dbenjamin@ascinode ~]$ xrdfs atlasfs02.hep.anl.gov ls -l /grid/atlas/hpc/common/alpgen/executables | grep zjetgen
-rwx 2013-12-13 16:21:18      756362 /grid/atlas/hpc/common/alpgen/executables/zjetgen77
-rwx 2014-02-22 01:46:56      502036 /grid/atlas/hpc/common/alpgen/executables/zjetgen90
-rw- 2014-02-22 01:49:58      502036 /grid/atlas/hpc/common/alpgen/executables/zjetgen

[dbenjamin@ascinode ~]$ xrdfs atlasfs02.hep.anl.gov chmod /grid/atlas/hpc/common/alpgen/executables/zjetgen rwxr-xr-x 
[dbenjamin@ascinode ~]$ xrdfs atlasfs02.hep.anl.gov ls -l /grid/atlas/hpc/common/alpgen/executables | grep zjetgen
-rwx 2013-12-13 16:21:18      756362 /grid/atlas/hpc/common/alpgen/executables/zjetgen77
-rwx 2014-02-22 01:46:56      502036 /grid/atlas/hpc/common/alpgen/executables/zjetgen90
-rwx 2014-02-22 01:49:58      502036 /grid/atlas/hpc/common/alpgen/executables/zjetgen

on the data server  - here is the contents of the authorization file -

[root@atlasfs02 ~]# cat /etc/xrootd/auth_file
# This means that all the users have read access to the datasets
u * /grid lr

# This means that all the users have full access to their private dirs
u = /grid/atlas/local/@=/ a

# This means that this privileged user can do everything
# You need at least one user like that, in order to create the
# private dir for each user willing to store his data in the facility
u apf /grid a
u xrootd /grid a
u lecompte /grid a
u dbenjamin /grid a
u jchilders /grid a
u bestman /grid/atlas a
u root    /grid a
u usatlas1 /grid/atlas/dq2 a
#u usatlas3 /grid/atlas/dq2 a
u usatlas4 /grid/atlas/dq2 a
u usatlas3 /grid a
#

**Comment by wyang007** [comment]
I guess Doug also lost track of this --- not just me. Closing this ticket. Had talked to and will talk again to Andy about rethinking implementing ownership, permission, time etc.

**Comment by wyang007** [comment]
close.
