### ISSUE TITLE
xrootd TPC change in v4.9.0-rc1

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#864]
It seems xrootd TPC in 4.9.0-rc1 has made some change and is incompatible with dCache xrootd TPC. See the link below

[xrdcp-log.txt](https://github.com/xrootd/xrootd/files/2626847/xrdcp-log.txt)

**Comment by abh3** [comment]
Has this been resolved?

**Comment by alrossi** [comment]
We have modified our code so that the redirected endpoint (the pools) now also supports this query which in the past was not necessary.  So yes, this issue can be closed.
