### ISSUE TITLE
XrdPosix Stat does not handle symlink flag

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#868]
I've noticed that XrdPosixXrootd::Stat() does not offer symlink support.

Eventually, a translation from Xrootd flags to POSIX mode flags occurs in XrdPosixAdmin::Stat(), which does not treat the S_IFLNK value, losing the symlink flag.

**Comment by abh3** [comment]
Actually, the reason that there is no test for a symlink is because XRootD servers never indicate whether something is a symlink or not. So, there is no need to test for it. Specifically, XRootD always returns the actual attributes of symlink targets not of symlinks themselves.
