### ISSUE TITLE
Documentation: wrong paths for stopfiles

### ISSUE THREAD

**Issue by ycalas** [xrootd/xrootd#870]
Hi,

In the XRootD documentation:

http://xrootd.org/doc/dev4/frm_config.htm#_Toc374035685

it is said that the stopfiles must be in /apath/frm[/name]. On my servers running 4.6.1-1 (I didn't check for other versions), it is instead in /apath[/name]/frm/, e.g.: 

/tmp/alicet1/frm/STOPMIGR

HTH ;)

**Comment by abh3** [comment]
Correc, whenever an instance name is specified, admin paths are qualified 
with the instance name. I will update the documentation. Thanks for 
letting us know.

Andy

**Comment by abh3** [comment]
Thanks, fixed!
