### ISSUE TITLE
XCache should fail if cache directory doesn't exist

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#871]
While testing out a new configuration of XCache, I ran into this error message:

```
181209 23:08:36 8835 XrdFileCache_Cache::ConfigParameters(): pfc.diskusage should have lowWatermark < highWatermark.
```

I was quite befuddled, as the `pfc.diskusage` setting is reasonable:

```
pfc.diskusage 0.90 0.95
```

Turns out that `totalSpace` is multiplied by the watermarks -- and I had set the cache directory to something that didn't exist, resulting in the high-water mark and low-water mark both being set to zero.

Let's just fail instead (or, lacking that, allow this strange configuration to be non-fatal).

**Comment by osschar** [comment]
I added a check like this (needs to be merged!):
https://github.com/osschar/xrootd/commit/077e35258274785a50ab70c41787bb371e819ed4
but I'd really expect the check above (on line 237) to fail beforehand if the path does not exist.

**Comment by osschar** [comment]
@abh3 shouldn't this
https://github.com/xrootd/xrootd/blob/master/src/XrdFileCache/XrdFileCacheConfiguration.cc#L236
fail if the path does not exist?

**Comment by xrootd-dev** [comment]
Well, not necessarily. I think VFS resolves to "logical" space which can 
be defined eventhough the underlying path does not exist. You won'y get 
much space information but it won't fail either.You best bet is to do an 
actual stat against the path you want to use.

Andy

**Comment by xrootd-dev** [comment]
Correct, the oss handles localroot as it may be more complicated than that 
(usually not for Xcache). Yes, on start-up the pfc should do a simple 
stat() on the what it thinks is the cache path using the oss plugin. If 
the result is an error or if it r/o or it has less, say, 10 MB of space 
(choose whatever) then simply say the appropriate thing and return 
failure.

As for whetehr or not it mkes it to 4.9.0, only Michal can say for sure 
but the sooner you submit the sooner I can merge. It will definitely go 
into 4.9.1!

Andy

**Comment by osschar** [comment]
OK, see #899

**Comment by osschar** [comment]
Andy, how come oss.localroot does not complain? :)

**Comment by abh3** [comment]
It never did, we kept it that way. I suppose we should put in a check. The question is whether or not it should fail. Obviously not when using a name2name plugin as we don’t know what that does. Anyway, for Xcache it’s not only that the directory does not exist but that it might be pointing to a mount point point and you wouldn’t want to use that either. That’s why a size check is needed as well.

Andy
