### ISSUE TITLE
Reserve `/etc/xrootd/config.d` for configuration drop-ins

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#872]
Before we release 4.9.0, we should agree on the directory for "drop-in" configuration files.

That is, the OSG would like to ship a config-only RPM that adds a few sane defaults to the Xrootd config as a separate configuration file.  We would naturally put these extensions in `/etc/xrootd/config.d` (to mirror `/etc/condor/config.d`); however, we'd really hate to adopt a naming scheme that differs from upstream.

For example, if OSG used `/etc/xrootd/config.d` and XRootD upstream used `/etc/xrootd/conf.d` starting in 5.0, many folks would be confused.

Even if we don't update the upstream templates in 4.9.0 to look at a config directory, I'd like to "reserve" the appropriate value for the future.

**Comment by abh3** [comment]
I'm not sure what the proposal is relative to our standard distribution. Indeed, we provide sample configuration files but they are simply examples and really need to be modified to work in any reasonable way. Is the proposal that we add the line

continue ?/etc/xrootd/config.d

to each such sample config file? That sort of tells people that is the directory that should be used but in no practical way reserves it.

**Comment by wyang007** [comment]
we already have a client drop in config directory like this ­ not quite resolving ³conf² vs ³config² :--)


[yangw@cent7a xrootd]$ ls -al

total 28

drwxr-xr-x.   3 root root  4096 Dec  5 05:32 ./

drwxr-xr-x. 138 root root 12288 Dec 10 02:00 ../

-rw-r--r--.   1 root root  6149 Oct 22 03:02 client.conf

drwxr-xr-x.   2 root root  4096 Dec  5 05:32 client.plugins.d/


--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by bbockelm** [comment]
Nothing really needs to be changed for the 4.9.0 release, but if OSG starts using this directory, it quickly becomes a nightmare for upstream to chose a different directory.  So, when OSG starts using `/etc/xrootd/config.d` by default, it means that we get effectively stuck with it.

(At some point it'd be good to start shipping more viable default config files in the RPM, but that's a topic for another day...)

**Comment by adriansev** [comment]
Hi! just an outsider view : the inclusion of "include" syntax (that would support also directories and globbing) for both configuration file and command line could solve this kind of problems ... this could be picked up by configuration overrides from /etc/systemd/system/xrootd@<conf file specific name>.service.d/

**Comment by adriansev** [comment]
@bbockelm cool! well, i would say is not very intuitive when talking about a configuration file syntax, but i'm glad that is there. i did not find the commit that add this improvement so i would have some questions:   
after a 'continue' to a config file is there a return?(or it is a dead end?)   
would the variables defined "upstream" be seen by this continuation config?   
also if variables are defined in that file, would be seen by the main file?    
thank you!!

**Comment by xrootd-dev** [comment]
On Mon, 10 Dec 2018, Adrian Sevcenco wrote:

>questions:
> after a 'continue' to a config file is there a return?(or it is a dead end?)
It is a dead end.A continue is essentially an apppend from the point the 
continue apperas. There is no return.

> would the variables defined "upstream" be seen by this continuation config?
Yes, variables are not discard on a contiue.

> also if variables are defined in that file, would be seen by the main file?
Since there is no return the question is moot..

Andy

**Comment by adriansev** [comment]
@xrootd-dev Thank you for info! yes, the 3rd question was in case first one was positive .. but it was a dead end :)) Would you consider to add an 'include' statement? (that would return or maybe something like a building block - meaning that would function like the '#include' statement in c; this way conditionals could also work )

**Comment by abh3** [comment]
Unfortunately, an include statement would require quite a bit of 
rewriting. After a lot of considerattion, we determined that a continue 
statement provided pretty close to what was needed for the expressed use 
cases and yielded a more comprehensible config file in the end.

**Comment by adriansev** [comment]
well... true, if you would process in one step the statement would be complicated .. but you could do it in 2 steps : make a temporary config file (in memory or /tmp) in which you replace the include statements with the content of the respective files and _then_ process the resulting configuration file. this way you avoid the syntax modification and just add a small step at the starting of service.

**Comment by abh3** [comment]
Actually, it would still b a serious rewrite of the existing code. There 
is no such concept as in-memory config files. This is further coplicated 
by arbitrary if/else statements. We really looked at this in great detail 
and include statements were just unworkable in the way config files are 
processed. If you really need include statements you can always run the 
preporcessor on your config file to create whatever config file you want 
and feed the result into  xrootd.

**Comment by adriansev** [comment]
ok, thanks for info! actually this is something that i am doing already in some form (wrapper script to xrootd/cmsd).

**Comment by simonmichal** [comment]
Is there anything else that needs to be done regarding this issue, or can we close it?
