### ISSUE TITLE
Provide GSI authorization function with configuration file

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#903]
The GSI authorization configuration is a beast.  Here's a current snippet I use:

```
   sec.protocol /usr/lib64 gsi \
     -certdir:/etc/grid-security/certificates \
     -cert:/etc/grid-security/xrd/xrdcert.pem \
     -key:/etc/grid-security/xrd/xrdkey.pem \
     -crl:1 \
     -authzfun:libXrdLcmaps.so \
     -authzfunparms:--lcmapscfg,/etc/xrootd/lcmaps.cfg,--no-authz \
     -gmapopt:0 \
     -authzto:3600
```

There are 8 configuration flags passed to the protocol, including 3 sub-configs passed to the plugin.

Seems it would be much better if we could pass these as separate configuration directives.  This would allow us to cleanly override defaults via the new `continue` directive via drop-in config files.

Further, it'd greatly simplify the authorization function plugins if they could access the whole configuration instead of forcing us to squash all configuration into the value passed to `authzfunparms`.

**Comment by abh3** [comment]
This is likely a good idea but given that the move is away from GSI it hardly worth the effort now. That's especially true as the gsi authentication parameters can now be specified in human understandable terms. Most new plugin of this type have moved to config file based configuration which was made trivial by adding a config directive collector which eliminates the boiler plate to handle a config file (i.e. it's now trivial to do). So, based on where the community is heading we will never get to this before GSI is no longer the premiere protocol.
