### ISSUE TITLE
internal log rotation and FileCache

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#907]
xrootd's internal log rotate works in most cases, except for Xcache. With Xcache, while base xrootd logs to the new xrootd.log, the FIleCache part still logs to rotated log, which is named as xrootd.log.20190230 ...

**Comment by abh3** [comment]
I still an issue?

**Comment by abh3** [comment]
Is this still a problem. All of pfc uses the standard logging interface so the file descriptor to the log file can't be leaked and cause the log file to be open. So, should I close this issue or are you still seeing he log file permanently open?

**Comment by wyang007** [comment]
This was a problem a long time ago, but I don’t think it is still a problem.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by abh3** [comment]
The reporter of this problem has indicated this is no longer an issue.
