### ISSUE TITLE
Implement ofs do multi-stack

### ISSUE THREAD

**Issue by zvada** [xrootd/xrootd#908]
Hello!

I've debugged this and discuss with @abh3. `ofs` only supports single stacking while we have a case we'd require multi-stack. Here is example when trying to load `throttle` plugin:

```
[root@hcc-marian ~]# grep -i "throttle" /var/log/xrootd/local-redirector/xrootd.log
...
=====> xrootd.fslib throttle default
Initializing a Throttled file system.
(Throttle Config)> throttle.throttle concurrency 20
```

It loads `throttle` just fine! However, when I put at the end of the xrootd config line e.g. "xrootd.fslib /usr/lib64/libXrdOfs.so" and restart I see only this:
```
[root@hcc-marian ~]# grep -i "throttle" /var/log/xrootd/local-redirector/xrootd.log
...
=====> xrootd.fslib throttle default
=====> xrootd.fslib throttle default
```

We also have use case in CMS where Multiuser support is required, i.e. `xrootd.fslib libXrdMultiuser.so default`, and `throttle` enabled at the same time. Long story short, xrootd.fslib directive overrides and only one option or the another (always latter one) can be used, an example:

*1) This loads multiuser and throttle default but not throttle concurrency (it's overridden):*
```
xrootd.fslib throttle default
throttle.throttle concurrency 20
multiuser.umask 0002
xrootd.fslib libXrdMultiuser.so default
```

*2) This loads throttle but doesn't multiuser:*
```
xrootd.fslib libXrdMultiuser.so default
multiuser.umask 0002
xrootd.fslib throttle default
throttle.throttle concurrency 20
```

Could you implement *multi-stack* support to address this problem?

Thanks,
Marian

**Comment by bbockelm** [comment]
@zvada - it appears what you want to do is utilize the `libXrdMultiuser.so` OSS plug-in layered underneath the throttle plugin.

If I look at the documentation, it appears the syntax for this line is:

```
xrootd.fslib [throttle | [-2] path2] {default | [-2] path1}
```

So, I'd guess the way to do what you want to accomplish is:
```
xrootd.fslib throttle libXrdMultiuser.so
```

You didn't mention above that you had already tried this (but perhaps you did mention it in an email?).  Anyhow, can you confirm that doing `xrootd.fslib throttle libXrdMultiuser.so` doesn't do what you intend?

Thanks!

**Comment by zvada** [comment]
The multiuser example actually comes from Florida. I was testing on my local VM with `xrootd.fslib /usr/lib64/libXrdOfs.so` only which shouldn't be different, though. Given your suggestion when I do the following:
```
xrootd.fslib throttle /usr/lib64/libXrdOfs.so
throttle.throttle concurrency 20
```
It works! I'll report back to Florida try it out on their system with multiuser (I just haven't succeeded with multiuser setup on my localhost, should be quicker to load the lines directly at Florida, though). I get back to this thread soon. Thanks again!

**Comment by bockjoo** [comment]
@bbocklem, after adding the multiuser at the end like so:
xrootd.fslib throttle libXrdMultiuser.so 
, I get this error:
Config Route all4: 172.16.200.175 Dest=[::172.16.200.175]:1094
Plugin unreleased XrdOfsLoader v4.9.0-rc2 is using Multiuser v4.8.4 version in fslib libXrdMultiuser-4.so
190218 18:21:51 5455 multiuser_Initialize: Encountered a runtime failure: The multi-user plugin must be chained with another filesystem.
190218 18:21:51 5455 XrootdConfig: Unable to create file system object via libXrdMultiuser.so
190218 18:21:51 5455 XrootdConfig: Unable to load file system.
------ xrootd protocol initialization failed.
190218 18:21:51 5455 XrdProtocol: Protocol xrootd could not be loaded
------ xrootd clustered@cmsio3.ufhpc:1094 initialization failed.

**Comment by bbockelm** [comment]
Very useful, thanks!  This then suggests it is a multiuser plugin limitation, not a generic XRootD problem.

I'm in the throes of proposal writing now - @zvada can you please open a ticket in https://github.com/opensciencegrid/xrootd-multiuser, referencing this one as the source?  That way Andy can close out this one....

**Comment by abh3** [comment]
Now that I think about this, isn't macaroons really involve authorization> If so (which I suspect), he OFS plugin has nothing to do with it. That should be handled by the authorization plugin. So, while I agree that multiple stacking of the OFS plugin may be a good idea, the motivation here is very suspect. So, where do Macaroons fit in?

**Comment by bbockelm** [comment]
@abh3 - Macaroons don't fit into this ticket.  It looks like your mention of macaroons is the first one so far?  Was there an email where someone wrote "macaroons" where they meant to write "multiuser"?

**Comment by xrootd-dev** [comment]
I believe that Marian mentioned macaroons relative to having more than one 
OFS wrapper. The subject line of that email thread (not put in the ticket) 
was "macaroons and throttle so you see how could conflate the two. If that 
is not the case, then I withdraw my comments.

Andy

**Comment by zvada** [comment]
> Very useful, thanks! This then suggests it is a multiuser plugin limitation, not a generic XRootD problem.
> 
> I'm in the throes of proposal writing now - @zvada can you please open a ticket in https://github.com/opensciencegrid/xrootd-multiuser, referencing this one as the source? That way Andy can close out this one....

Sounds good, ticket created:
https://github.com/opensciencegrid/xrootd-multiuser/issues/6

**Comment by abh3** [comment]
This is now available in 5.
