### ISSUE TITLE
CMakeLists should look for libcurl and treat it appropriately

### ISSUE THREAD

**Issue by ffurano** [xrootd/xrootd#913]
For example, this should not happen:

[ 72%] Built target XrdHttp-4
make[2]: *** No rule to make target `/usr/lib64/libcurl.so', needed by `src/libXrdHttpTPC-4.so'.  Stop.

... either the CMake phase should exit with an error, or the compilation of libXrdHttpTPC should be disabled

**Comment by ffurano** [comment]
I'd say that the same applies to Pyxrootd:
/afs/cern.ch/user/f/furano/Park/xrootd/xrootd-fbx4/bindings/python/src/PyXRootD.hh:28:20: error: Python.h: No such file or directory
.... followed by an avalanche of compiler error blabber

**Comment by bbockelm** [comment]
Strange - I see an explicit check for curl:

https://github.com/xrootd/xrootd/blob/master/cmake/XRootDFindLibs.cmake#L72-L84

If curl is not found, then we already should turn off TPC:

https://github.com/xrootd/xrootd/blob/master/src/XrdTpc.cmake#L12

What's the value of `BUILD_TPC` and `CURL_FOUND` in your setup?

**Comment by ffurano** [comment]
Uhm, I don't think I have those option variables. "cmake -LAH" does not print them

**Comment by bbockelm** [comment]
Those aren't options in CMake, they are internal variables.

At least the `CURL_FOUND` one should be serialized in the cache:
```
$ grep -RIi curl_found CMakeCache.txt                                                                                                                          
CURL_FOUND:INTERNAL=1
```

**Comment by ffurano** [comment]
... and it seems that I can't reproduce it anymore. Actually I found a rogue CMakeCache.txt one level up, that likely was messing things up. Sorry for the noise.

**Comment by simonmichal** [comment]
No worries and thanks for checking!
