### ISSUE TITLE
Macaroon generation lists wrong activities in log

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#921]
Requesting a macaroon with activities `DOWNLOAD,UPLOAD` against XRootD 4.9.0, I get the following the logfile:
```
190301 15:52:17 2542 sysMacaroonGen: ID=<this_is_some_uuid>, name=/C=DE/<remaining_part_of_cn>, host=[::ffff:<my_ipv4_address>], vorg=atlas, role=NULL, groups=/atlas /atlas/de /atlas/de/Role=NULL /atlas/de/Role=NULL/Capability=NULL, endorsements=/atlas/de/Role=NULL/Capability=NULL, activity=activity:READ_METADATA,UPLOAD,DOWNLOAD,DELETE,MANAGE,UPDATE_METADATA,LIST, expires=<some_date> 
```
i.e. this lists all activities, potentially those the original requestor had and not only those the issued with the macaroon. 

It might just be a logging issue, but that should be checked. 

ping @bbockelm

**Comment by bbockelm** [comment]
@olifre - indeed, it's just a logging issue.

Basically, the line is logging all the activities your user session has.  You have additionally asked a limit to be appended on the macaroon to narrow the scope.  The latter was not logged and is now in #929.

**Comment by olifre** [comment]
@bbockelm Good, that's very comforting :smile:. Thanks for fixing the logs!
