### ISSUE TITLE
Provide tools to dump ABI versions

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#926]
To date, we've not been able to actually use any of the clever ABI at the packaging level because there's no great way to export, from an Xrootd server build, the set of minimal plugin versions.  All of this is encoded in C++ and packaging systems, of course, aren't C++ parsers!

Could we have two tools:

1.  Tool that prints in a simple, machine-parseable, line-delimited format, all the plugin APIs provided by the version of Xrootd the tool was packaged with.
2.  Tool that scans a given shared module for known Xrootd versioning symbol names and prints out the corresponding build-time information from within the module.

Given this, we could write RPM macros that automatically generate package dependency information, allowing us to detect incompatibilities at install time (and even have `yum` resolve these issues during upgrades).

**Comment by abh3** [comment]
For 1: Could you give me an example of the information you would like to see (pick your favorite plugin). I would assume you would also like to have a --human option to see this information in an eyeball readable format, right?

For 2: We could scan for the version information but we don't include build time information. The closest would simply be the build time of the actual library which I'm not sure would meet your requirement here (if I understand it correctly). In any case, could you give an example of the output you would like to see.

**Comment by bbockelm** [comment]
For 1:  I think it's good enough to have a machine-friendly version of the contents of `XrdVersionPlugin.hh`.  So, the snippet of the header looks like this:

```
#define XrdVERSIONPLUGINRULES \
        XrdVERSIONPLUGIN_Rule(Required,  4,  0, XrdAccAuthorizeObject         )\
        XrdVERSIONPLUGIN_Rule(Optional,  4,  0, XrdBwmPolicyObject            )\
        XrdVERSIONPLUGIN_Rule(Required,  4,  0, XrdCksCalcInit                )\
```

I think a corresponding output from the tool would be along the lines of:

```
XrdAccAuthorizeObject 4.0 Required
XrdBwmPolicyObject 4.0 Optional
XrdCksCalcInit 4.0 Required
```

The first column is the unmangled symbol name; the second is the minimum required Xrootd version the object must be built against to work with the current Xrootd; the third is whether the version info is required or optional.

This would be translated to RPM "Provides" (in the `xrootd` RPM) of the form:
```
Provides: xrootd(XrdAccAuthorizeObject) = 4.0
Provides: xrootd(XrdBwmPolicyObject) = 4.0
Provides: xrootd(XrdCksCalcInit) = 4.0
```

For 2: For the Xrootd-HDFS RPM, we have:

```
XrdVERSIONINFO(XrdOssGetStorageSystem,"hdfs");
```

This creates two symbols in the output binary:

```
00000000000011c0 T XrdOssGetStorageSystem
00000000002020c0 D XrdOssGetStorageSystem_
```

I assume, in the latter symbol, we actually set the version info.  Thus, for `libXrdHdfs-4.so`, I'd like some output along the lines of:

```
XrdOssGetStorageSystem 4.9.1
```

where `4.9.1` was the version of the Xrootd headers the binary was built against.  This would allow us to add the following to the `xrootd-hdfs` package:

```
Requires: xrootd(XrdOssGetStorageSystem) <= 4.9.1
```

The logic indeed looks a bit backwards.  I think of it as the xrootd RPM saying "I provide compatibility with the XrdOssGetStorageSystem ABI starting with 4.0.0" and the xrootd-hdfs RPM saying "I require a version of xrootd with the XrdOssGetStorageSystem ABI that supports at least 4.9.1".

**Comment by abh3** [comment]
This is now available in R5.
