### ISSUE TITLE
xrdcp corrupts last file from zip

### ISSUE THREAD

**Issue by rodwalker** [xrootd/xrootd#936]
Hi,
Extracting the last file from some zip files is corrupting with xrdcp. I can download the zip and extract by hand, e.g.
$ unzip HITS.17117996._000001.zip.1 HITS.14859379._008207.pool.root.1
$ adler32 HITS.14859379._008207.pool.root.1 
c14ce6a8

But using xrdcp to several storages corrupts the file to adler32 771c5546. Even don locally
$ xrdcp -z HITS.14859379._008207.pool.root.1 file:///tmp/walkerr/HITS.17117996._000001.zip.1 HITS.14859379._008207.pool.root.1.xroot
[70.35MB/70.35MB][100%][==================================================][70.35MB/s]  
$ adler32 HITS.14859379._008207.pool.root.1.xroot
771c5546

$ cmp HITS.17117996._000001.zip.1 HITS.14859379._008207.pool.root.1.xroot
HITS.17117996._000001.zip.1 HITS.14859379._008207.pool.root.1.xroot differ: byte 1, line 1

I found 2 examples, bit corrupting the last file added to the zip. The zip files are 12GB, which might play a role. Not sure how I can share one - lxplus?

Cheers,
Rod.

**Comment by simonmichal** [comment]
Hi Rod,

Thanks for reporting this problem. lxplus would work for me!

Cheers,
Michal

**Comment by rodwalker** [comment]
Hi,
Please check you can read
lxplus096:/tmp/walkerr/HITS.17117996._000001.zip.1

Cheers,
Rod.

**Comment by simonmichal** [comment]
Hi Rod,

Thanks for the file! I'll have time to look into the problem only later this week (the fix will probably included only in 4.9.2 or 4.10.0).

Cheers,
Michal
