### ISSUE TITLE
python xrootd :: CopyProcess - no batch size

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#948]
Hi! The CopyProcess does not expose a method for setting the number of simultaneous downloads, which would be needed for large list of files download.

**Comment by simonmichal** [comment]
@adriansev : this is for python bindings right?

**Comment by adriansev** [comment]
@simonmichal yes, of course

**Comment by simonmichal** [comment]
Done in f60662ee2f44e0eb4bd152071eda026843044482

Now the copy process has a method `parallel` that will allow you the set the number of parallel copy jobs.
