### ISSUE TITLE
python bindings :: checksum is not written on the server

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#956]
HI! While using .addJob(..., checksumtype = 'md5') after a successful message of file uploading i get `none` when doing `xrdfs query checksum` and if i use -C md5 i get `Run: [ERROR] CheckSum error`. Any idea what can be the problem?  
Thank you

**Comment by simonmichal** [comment]
@adriansev : the `checksumtype` option is used when verifying if the data were not corrupted during transfer. Basically, you need to set

- checksumtype : the type of the checksum, e.g. md5 (server needs to be configured to support it)
- checksummode : `end2end` if you want the client to verify if the data were not corrupted during transfer
- checksumpreset : pre-computed checksum to be used as source checksum (it's optional)

Those options are not used to store a file checksum on the server.
For the `xrdfs query checksum` to work checksuming has to be enabled on the server side.

I hope this answer your question.

**Comment by adriansev** [comment]
Thank you, this answers my questions! (it would be great if these explanations make it to xrootd binding doc).

**Comment by simonmichal** [comment]
Absolutely, we will updates our documentation.
