### ISSUE TITLE
python binding 4.9.1 :: still no python3 install, and /usr/lib64 based 

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#960]
Hi! 4.9.1 still cannot be pip3 installed in user mode on el7, fedora27 and fedora29
full logs (-vvv to pip3) can be found here http://issaf.spacescience.ro/adrian/xrootd_py/

**Comment by simonmichal** [comment]
@adriansev : it has been fixed in b1c3f22e07c974adb0e33251d47f43e35dcb020e, however due to time constraints this fix was not included in 4.9.1, but will be in 4.10.0.

**Comment by adriansev** [comment]
ok, i see! with all the commits that were in 4.9.1 i thought that this fix was also there
