### ISSUE TITLE
Directory listing with the stat option takes a long time

### ISSUE THREAD

**Issue by aperloff** [xrootd/xrootd#962]
Hello,

I've implemented a python os.walk style function using xrootd bindings in place of the local file system calls. One of the ingredients of this is testing whether or not a directory listing is a file or a folder. Initially I was using the dirlist command with the DirListFlags.STAT flag. However, for large directories (>30K files) this takes an exceedingly long time (even in the command line client version). Example commands for python can be in [1] and for the command line can be found in [2].

Another option is to get the dirlist without requesting the stat information and then to call stat on each file/folder individually. However, this means that the server will receive many requests quite rapidly. This could, in principle, cause server side issues.

Is there a recommendation on how to identify the directories and/or files in a dirlist without returning all of the stat information?

Thank you,
Alexx

[1]
from XRootD import client
from XRootD.client.flags import DirListFlags, StatInfoFlags
xrdfs = client.FileSystem(xrootd_endpoint)
status, listing = xrdfs.dirlist(directory,DirListFlags.STAT)

[2]
xrdfs root://<endpoint>/ ls -l <path>

**Comment by simonmichal** [comment]
@aperloff : I don't think currently we can offer anything else than `dirlist` with `stat` flag. However, we could think about adding a 'streaming' `dirlist` that would allow you to handle partial results of the operation. Would this help?

**Comment by aperloff** [comment]
@simonmichal: I do think a streaming option would be helpful. Anything to allow us to begin working on the partial list without waiting for the entire process to finish.

**Comment by simonmichal** [comment]
@aperloff : OK, so that's the way to go, however there's one but: I wont be able to filter out duplicates for chunked `dirlist` operation, it will be up to you to filter them out.

**Comment by aperloff** [comment]
Does dirlist normally include duplicates? Where would the multiple copies come from? Different management nodes? I wasn't aware of any duplicate removal taking place.

I think this should be fine as long as this caveat is made clear in the documentation.

**Comment by abh3** [comment]
Well, technically you could by keeping a an std::set of what you saw and 
not passing through things you have aleady seen. If you do that, it should 
be an option (by default on). That is likely what the pplicatoin would do. 
Doing in the client avoids everyone having to reinvent the wheel.

Andy

**Comment by abh3** [comment]
Duplicates occur when a site decides to replicate files across data 
servers (always in DFS environments). Duplicates naturally occur in 
regional and global federations.

Andy

**Comment by simonmichal** [comment]
True enough, I'll try to provide something after Eastern.

**Comment by aperloff** [comment]
Wonderful! Thank you both. If possible, please also port this to the python bindings in addition to the command line client.

**Comment by simonmichal** [comment]
@aperloff : I just pushed 9fd293c2124b86984a75944d39e553e722982d84, it exposes the chunked dirlist handling that has been implemented in cc83c0918f3835329846621b5f5e603ffa24f783

The chunked semantics is available only for asynchronous calls, here's an example:

```
from XRootD import client
from XRootD.client.flags import DirListFlags, OpenFlags, MkDirFlags, QueryCode
from XRootD.client import responses

import time

def callback(st, rsp, hosts):

  if st.ok:

    for ent in rsp:
      print ent # or do something else

    if st.code == responses.XRootDStatus.suDone:
      # this is the last chunk
      print 'We are done.'

    if st.code == responses.XRootDStatus.suPartial:
      # this happens if some of the requests failed, e.g. 
      # in case of recursive dirls client might fail listing
      # some subdirectories
      print 'We are done, but this is only partial result'

    if st.code == responses.XRootDStatus.suContinue:
      #more chunks will follow
      print 'We will continue with this callback'

fs = client.FileSystem('root://slc7-test:1094')
fs.dirlist( '/tmp', DirListFlags.RECURSIVE | DirListFlags.CHUNKED, 0, callback )

# make sure you wait until the callback gets the final response
time.sleep(3)
```

I hope this helps! Let me know if there's anything else you need or if the issue can be closed!

**Comment by aperloff** [comment]
@simonmichal thank you for the update! This is fantastic. I can't wait to give it a try. I guess the issue can be closed. If something else comes up I'll either reopen it or open a new issue.

**Comment by abh3** [comment]
As per user request.
