### ISSUE TITLE
xrdadler32: document use of stored checksum in file attributes

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#966]
We've come across "user.XrdCks.adler32" extended attributes on some files. Turns out that these get created when running `xrdadler32` against a file, and that subsequent `xrdadler32` runs will just return the stored checksum (instead of recomputing the checksum).

This behaviour (and in particular the fact that this command persistently changes file state, at least for local files) isn't really obvious from the documentation:
```
$ man xrdadler32
NAME
       xrdadler32 - compute and display an adler32 checksum

SYNOPSIS
       xrdadler32 [file]


DESCRIPTION
       The xrdadler32 utiliity computes and displays an adler32 checksum value for a file.  Usage synopsis can be displayed by typing "xrdadler32 -h".  Currently, only the usage synopsis is available as documentation.
[..]

$ xrdadler32 -h
Usage: xrdadler32 file. Calculating adler32 checksum of a given file.
A file can be local file, stdin (if omitted), or root URL (including via XROOTD_VMP)
```
Would it perhaps be possible to document the caching behaviour?

**Comment by abh3** [comment]
Done!
