### ISSUE TITLE
users banning

### ISSUE THREAD

**Issue by lumorganti** [xrootd/xrootd#967]
Hi all,
a way to block specific users would be mostly welcomed.
Thanks!

**Comment by abh3** [comment]
There is a post-authentication plugin you can write that can be used to bad authenticated users, See
https://xrootd.slac.stanford.edu/doc/dev56/sec_config.htm#_Toc119617428
Mind you if you are using tokens there is no equivalent as there is no authenticated entity only an authorized one. So, there is no way of controlling fundamental processes.  In any case, I am closing this as there is a solution here by using a user written plugin.
