### ISSUE TITLE
wrong xrdcp error code

### ISSUE THREAD

**Issue by ivukotic** [xrootd/xrootd#972]
Here example of file transfer that fails due to bad cksum but error code is 53

~ >xrdcp -f --cksum adler32:111b2fe1 root://xcache.mwt2.org:1094//root://xrootd.aglt2.org:1094//pnfs/aglt2.org/atlasdatadisk/rucio/data15_13TeV/96/bb/DESDM_EGAMMA.17824239._015051.pool.root.1 /dev/null
[97.94MB/97.94MB][100%][==================================================][97.94MB/s]
Run: [ERROR] CheckSum error
~ >echo $?                                                                                                                                                                         
53

**Comment by simonmichal** [comment]
Hi Ilia,

53 is a xrootd 'related' error, which includes checksum error, here's the full list:

```
  const uint16_t errNoMoreFreeSIDs     = 301;
  const uint16_t errInvalidRedirectURL = 302;
  const uint16_t errInvalidResponse    = 303;
  const uint16_t errNotFound           = 304;
  const uint16_t errCheckSumError      = 305;
  const uint16_t errRedirectLimit      = 306;
```

Why do you claim the error code is wrong?

Cheers,
Michal

**Comment by ivukotic** [comment]
Ah... Is there a way to get actual xrootd error code? This way it is not very helpful.
Thanks,
Ilija

**Comment by simonmichal** [comment]
@ivukotic : unfortunately this is not possible as the return code is a value in range `0-255` and the xrootd error codes takes values in range `0-500`,

That's why from the return code you can only get info about the error type:
```
RETURN CODES
       50  : generic error (e.g. config, internal, data, OS, command line
       option)
       51  : socket related error
       52  : postmaster related error
       53  : XRootD related error
       54  : redirection error
       55  : query response was negative (this is not an error)
```

If you need detailed xrootd status in your script I would advice to to use Python and XRootD Python bindings.

**Comment by simonmichal** [comment]
I suppose there's not much we can do, may I close it?

**Comment by ivukotic** [comment]
Hi,

Yes please.

Thanks,
Ilija
