### ISSUE TITLE
[XCache] XRDDEBUG env variable overrides pfc.trace dump setting

### ISSUE THREAD

**Issue by mpatrascoiu** [xrootd/xrootd#973]
I've noticed that the XRDDEBUG env variable (enables debug trace level globally) overwrites the more verbose _pfc.trace dump_ setting of the file caching component.

Is this intended behavior? Should XRDDEBUG force exactly the debug level?
I assumed it meant a minimum of debug level.

The culprit is in the Configuration file, line 308:
https://github.com/xrootd/xrootd/blob/master/src/XrdFileCache/XrdFileCacheConfiguration.cc#L308

**Comment by xrootd-dev** [comment]
Thanks for spotting this, I will set the cache level to max of both values.

Matevz
