### ISSUE TITLE
[XrdSecgsi] Client is reusing cached proxy although xrd.gsiusrpxy cgi points to a new one

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#976]
Here's a simple reproducer:
```
  FileSystem fs1( std::string( "root://user1@hostname//tmp?xrd.gsiusrpxy=/tmp/user1proxy" ) );
  DirectoryList *rsp1 = 0;
  XRootDStatus st1 = fs1.DirList( "/tmp", DirListFlags::None, rsp1 );
  std::cout << st1.ToString() << std::endl;

  FileSystem fs2( std::string( "root://user2@hostname//tmp?xrd.gsiusrpxy=/tmp/user2proxy" ) );
  DirectoryList *rsp2 = 0;
  XRootDStatus st2 = fs2.DirList( "/tmp", DirListFlags::None, rsp2 );
  std::cout << st2.ToString() << std::endl;
```
In this scenario, a new connection is created for `user1` and is authenticated with `/tmp/user1proxy` credential. Afterwards, a new connection is being created for `user2` and is being authenticated with the cached credential (again `/tmp/user1proxy`).

This is easy to spot if one uses expired proxy as the second credential, in this case the second
dirls should fail, but it never does.

**Comment by chaen** [comment]
I confirm the fix works

**Comment by simonmichal** [comment]
@chaen: Perfect! Thank you very much for testing!
