### ISSUE TITLE
systemd service :: arguments for service

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#978]
Hi! Is my intention of moving the script based usage of xrootd service to systemd but i would see some details that can be improved :      
i believe that log specification should not be fenced as all other options are relative to the name of configuration file .. so   
`-l /var/log/xrootd/xrootd.log`   
should be :  
`-l =/var/log/xrootd-%i.log`   
for both xrootd and cmsd ; i omitted the directory as multiple services with different users can potentially be run on the server   
moreover i would say that the configuration file name is too long so i would suggest to replace    
`-c /etc/xrootd/xrootd-%i.cfg`    
with    
`-c /etc/xrootd/%i.cfg`    
Of course, it remains the problem of adminpath, with the mix of resident and non-resident files, the multiple pid files (found also in ADMINPATH/<instance>/ even is -s options was used) , the extra text found in ADMINPATH/<instance>/cmsd.pid, the core files location specified by symlinks in ADMINPATH/<instance>/.xrd/=/core/ that point to $HOME/<instance> (and this is potentially problematic for services started by root), impossibility to specify the adminpath with cli argument so lacking the control of location to write files into if adminpath specification is missing in configuration file .... but these are of course for some other time

Thank you!!

**Comment by abh3** [comment]
Unfortunately, that is true for the particular way you run the system but it isn't necessarily true for many others. As you correctly point out, every site has it's own foibles and ways of doing things. The example startup script are just that, examples. They should be modified to meet the needs of the site. In practice, we can't possibly come up with a generic startup script that satisfies anyone, really. So, sites need to accept that it's just a starting point.
