### ISSUE TITLE
GSI/Daylight Savings Time authentication issue

### ISSUE THREAD

**Issue by brianhlin** [xrootd/xrootd#985]
With the US DST transition (March 9/10), CMS saw failures at US-CMS sites using a proxy certificate generated between 2-3am UTC:

```
Authentication with gsi failed: Secgsi: ErrParseBuffer: certificate chain
verification failed: Proxy: certificate expired: kXGC_cert
```

This issue did not appear for non-US sites using the same certificate and connections using proxies generated after 3am UTC worked with US sites. In the original support ticket [2], we proposed reproducing this ticket by setting up an XRootD server with its clock set to March 9/10 with a US time zone and a second host acting as a client set to the same time with a European time zone.

[1] http://wlcg-sam-cms.cern.ch/templates/ember/#/historicalsmry/heatMap?end_time=2019%2F03%2F10%2006%3A00&metrics=org.cms.SE-xrootd%20(connection)%2Corg.cms.SE-xrootd%20(contain)%2Corg.cms.SE-xrootd%20(read)%2Corg.cms.SE-xrootd%20(version)%2Corg.cms.WN-analysis%20(%2Fcms%2FRole_lcgadmin)%2Corg.cms.WN-xrootd-access%20(%2Fcms%2FRole_lcgadmin)&profile=CMS_CRITICAL_FULL&site=T1_US_FNAL%2CT2_BR_SPRACE%2CT2_US_Caltech%2CT2_US_Florida%2CT2_US_MIT%2CT2_US_Nebraska%2CT2_US_Purdue%2CT2_US_UCSD%2CT2_US_Vanderbilt%2CT2_US_Wisconsin&start_time=2019%2F03%2F10%2000%3A00&time=manual&view=Test%20History
[2] https://support.opensciencegrid.org/public/tickets/ae8dc3e90125b8499e6dd7a06ecfe6025ccad8a0e871b6d7dbd4cb34c00393a0

**Comment by bbockelm** [comment]
Bumping this ticket - what's the latest?

**Comment by abh3** [comment]
We have not had time to work on this and, frankly, this is not a high 
priority as there is some time before this issue rears it's ugly head.

**Comment by bbockelm** [comment]
Does it happen at all transitions?  If so, the next occurrence is November 3.  Given the cadence of releases and site upgrades, this likely has to be done in the next month or so, right?

**Comment by abh3** [comment]
From my understanding, this happens when the clocks move forward not 
backward. If actually true, we have 6 more months :-)

**Comment by abh3** [comment]
We are coming up to he next clock change. Let's see what happens and collect more information on this.

**Comment by abh3** [comment]
Hey, we just went through a timezone change and I didn't hear any objections was it because we went one hour ahead and no one complained or is this still an issue?

**Comment by ckristi** [comment]
We have experienced a similar thing with the time change (getting auth failed for GSI authentication) from our monitoring box to all EOS instances:

> [2020-03-29 04:00:06.381766 +0200][Error  ][XRootDTransport   ] [128.142.32.19:1094 #0.0] No protocols left to try
> [2020-03-29 04:00:06.381827 +0200][Error  ][AsyncSock         ] [128.142.32.19:1094 #0.0] Socket error while handshaking: [FATAL] Auth failed
> [2020-03-29 04:00:06.381896 +0200][Error  ][PostMaster        ] [128.142.32.19:1094 #0] elapsed = 0, pConnectionWindow = 120 seconds.
> [2020-03-29 04:00:06.381909 +0200][Error  ][PostMaster        ] [128.142.32.19:1094 #0] Unable to recover: [FATAL] Auth failed.
> [2020-03-29 04:00:06.381936 +0200][Error  ][XRootD            ] [128.142.32.19:1094] Impossible to send message kXR_stat (path: /eos/opstest/slstest-eosalicedaq/test-eosalicedaq.cern.ch-from-eosmon01.cern.ch-xrdcp.static, flags: none). Trying to recover.
> [2020-03-29 04:00:06.382639 +0200][Error  ][XRootD            ] [128.142.32.19:1094] Unable to send the message kXR_open (file: /eos/opstest/slstest-eosalicedaq/test-eosalicedaq.cern.ch-from-eosmon01.cern.ch-xrdcp.static?oss.asize=48, mode: 0644, flags: kXR_delete kXR_open_updt kXR_async kXR_retstat ): [FATAL] Auth failed

**Comment by osschar** [comment]
I grepped for localtime function ... mostly it is used in Dump/Print/Browse functions. A potentially relevant usage is in initialization of  static time_t TZCorr in src/XrdCrypto/XrdCryptoAux.cc:
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptoAux.cc#L85

Then, there are the following usages of this variable to translate to localtime:
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptosslgsiAux.cc#L887
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptoX509.cc#L112
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptoX509.cc#L124
while NotAfter() and friends seems to return it in UTC:
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptosslX509.cc#L455

This seems to be the location where the error from the original post is hit:
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptoX509Chain.cc#L825

**Comment by bbockelm** [comment]
Why don't we just dump all the hand-calculations of validity and let OpenSSL do the work?  E.g.,

```
bool IsValid() {
   now = time(NULL)
   int day, sec;
   if (1 != ASN1_TIME_diff(&day, &sec, cert_expiry_time, NULL)) { return false; } // Error... 
   return (day > 0 || sec > 0);
}
```

I don't see much value in hand-calculating timezone and DST offsets (which, quite obviously, have some bug somewhere) when there's an OpenSSL API function to do precisely this.

**Comment by stlammel** [comment]
Hallo Andy, all,
   i took a look at the references Matevz put into the chat. XrdCrypto/XrdCryptoAux.cc
seems to be the issue: The local offset to UTC is calculated once and then saved, i.e.
gets wrong by an hour when the xrootd server passes into/outoff daylight-savings.
(I assume each connection doesn't start a fresh process/re-initializes.) Easiest would
be to calculate the local offset to UTC each time, i.e. remove lines 81 and 88.
   Let me know in case i misunderstood the code.
   Thanks,
          cheers,  Stephan

**Comment by bbockelm** [comment]
> Easiest would be to calculate the local offset to UTC each time, i.e. remove lines 81 and 88.

Or just never used local time in the first place.  It seems that we might just use the wrong OpenSSL APIs for conversion as all the inputs are in UTC to begin with.

**Comment by abh3** [comment]
Ah, that doesn't mean that I am not open to suggestions on how to 
standardize the way the specifications get propogated. By all means, 
suggest a policy that perculates the specification across all of the uses.

Andy

**Comment by stlammel** [comment]
Independent on how we fix this, we have a one hour shift until we restart xrootd services after daylight-savings change, i.e. not just an impact for an hour after daylight-savings change.

**Comment by xrootd-dev** [comment]
Agreed, let's take a deep breath and figure out the best way to solve 
this. I like the idea of just letting OpenSSL figure it out but I would 
like to know why Gerri didn't do that as there must have been a reason 
which may or may not be important and may cause other unintended side 
effects.

**Comment by abh3** [comment]
So, now it's 2022 and we have gone through several day/night changes and there have been no complaints. So, is this still an issue?

**Comment by stlammel** [comment]
Hallo Andy,
   well, i assume the fix went into a v5. We in CMS have not yet started a v5 upgrade campaign as a few sites that upgraded run into issues. Bockjoo (who took over from Marian Z) is tracking things and we hope site can upgrade once the high load issue is resolved.
   Thanks,
        cheers,  Stephan

**Comment by stlammel** [comment]
This seems to not fixed or broken again (don't know which). Can this please be addressed asap, so the next v5 xrootd version can have day-light saving switched correctly?
Thanks,
- Stephan

**Comment by amadio** [comment]
Closing, #1958 has been merged.
