### ISSUE TITLE
WebDAV TPC issue with 4.10.0rc1

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#988]
Trying 4.10.0-rc1, we do now finally see WebDAV TPC pull requests in our logs. However, all of them fail like:
```
190515 16:30:45 3510148 sysProcessReq: Pull request from https://dcgftp.usatlas.bnl.gov:443/pnfs/usatlas.bnl.gov/BNLT0D1/rucio/mc16_13TeV/4f/88/DAOD_HIGG4D3.17227694._000758.pool.root.1
190515 16:30:45 3510148 ofs_open:  Unable to create /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/mc16_13TeV/4f/88/DAOD_HIGG4D3.17227694._000758.pool.root.1?authz=Bearer VERY_LONG_BEARER_TOKEN_....._VERY_LONG; file name too long
```
i.e. the file name xrootd tries to create seems to include the URI parameters (in this case the bearer token, which is very long. 

Since previous versions do not work for us due to #968 , I can not tell if this issue is new.

**Comment by bbockelm** [comment]
This might be related to https://github.com/xrootd/xrootd/pull/970

Basically, instead of forcing the client to repeat the `Authorization` header when redirected (fewer and fewer clients elect to do this anymore), include the information as part of the opaque string.

I would be curious:

(a) How long is the entire string?
(b) Does this happen in the redirector or data server?

**Comment by olifre** [comment]
I can confirm we have `http.header2cgi Authorization authz` in our config (both on redirector and data server). 

> (a) How long is the entire string?

Starting from the path `/cephfs`, and ending at the `;` before the message (i.e. up to the end of the bearer token), it's the full glory of 794 characters. 

>  (b) Does this happen in the redirector or data server?

The error was seen on the data server.

**Comment by bbockelm** [comment]
I should mention that, before #989, I see:
```
190516 07:54:20 3966443  ofs_open: 201-644 fn=/home/cse496/bbockelm/tmp/xrootd_export/foo.google?authz=Bearer baz
```

With #989, I see:
```
190515 22:35:08 3867622 unknown.1:31@hcc-briantest7 ofs_open: 0-600 fn=/home/cse496/bbockelm/tmp/xrootd_export/foo
```

It's not logged, but stepping through with a debugger, I verified that the `authz` header is copied to the separate internal structure for authorization.

**Comment by olifre** [comment]
@bbockelm Many thanks for the quick patch! 
I'll also give it a go in our production setup with the next RC for sure and report back :smile:
