### ISSUE TITLE
gsiusrpxy taken into account for connection cache

### ISSUE THREAD

**Issue by chaen** [xrootd/xrootd#992]
This is a follow up of https://github.com/xrootd/xrootd/issues/976

At the moment, the gsiusrpxy parameter in the URL is not used to distinguish the different identities. A trick consists in adding a virtual user. It would be nice if this trick was not necessary anymore, and the gsiusrpxy parameter respected

**Comment by simonmichal** [comment]
This has been implemented in 50a49b04743d18f6d7dc8d4e8914a32d43ed5a2f and will be released in R5.
