### ISSUE TITLE
Provide an official way of building/installing only the client libraries

### ISSUE THREAD

**Issue by amadio** [xrootd/xrootd#996]
As mentioned in [this comment](https://github.com/xrootd/xrootd/issues/959#issuecomment-482487811), it is possible to build only the client part of XRootD using `make`. I would like to request an officially supported way of doing this since with other CMake generators (e.g. Ninja) this approach does not work. Also, you need all dependencies for the server to configure, even though only the client is being built. It would be nice to have an option to disable building of the server part.

**Comment by simonmichal** [comment]
@amadio : from what I've seen proof requires not only xrootd client public headers but also some from XrdUtils (etc.), I suppose you would like those headers to be installed too, right?

**Comment by simonmichal** [comment]
@amadio : in 8c90ab20dc737a50a09fa10e117005717f58d3bd I added a new switch to our CMake infrastructure, you should be now able to build only the client by using `-DXRDCL_ONLY=ON`

**Comment by amadio** [comment]
Thank you! I will try it out.
